# -*- coding: utf-8 -*-
"""Testcase Lộ trình học — viết theo ngôn ngữ UI thật cho tester."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from _tc_builder import build

DESCRIPTION_BLOCK = [
    ("1. Mục đích tính năng",
     "Màn 'Lộ trình học' để tạo chuỗi nhiều Khóa học theo thứ tự, cấu hình điều kiện đạt lộ trình, có thể bắt buộc học tuần tự, gán người học và cấp chứng chỉ. Form có 4 tab: 'Thông tin lộ trình học', 'Cấu hình kết quả', 'Cấu hình người học', 'Chứng chỉ'."),
    ("2. Đối tượng được tính / hiển thị",
     "► Trạng thái: 'Nháp' / 'Đang dùng' / 'Đã khoá' (ở danh sách) — trong tab Thông tin hiển thị 'Khoá' (không 'Đã').\n► Public → hiển thị cho học viên ngoài.\n► Điều kiện đạt: Tất cả khoá bắt buộc ĐẠT / Tất cả khoá ĐẠT / Đạt tối thiểu X%."),
    ("3. Đối tượng bị ẩn / không tính",
     "► Lộ trình Public KHÔNG được chứa khóa chưa Public → chặn lưu.\n► Nút khoá bị VÔ HIỆU khi lộ trình đang 'Đang dùng' (không cho khoá trực tiếp)."),
    ("4. Bộ lọc thời gian áp dụng cho",
     "'Ngày cập nhật từ' ... 'Ngày cập nhật đến' lọc theo ngày cập nhật."),
    ("5. Cấu trúc dữ liệu / cây phân cấp",
     "Lộ trình → nhiều Khóa học (kéo thả sắp xếp) → mỗi khóa gồm bài học (chỉ xem). Đặt 'Bắt buộc'/'Không bắt buộc' cho từng khóa trong lộ trình."),
    ("6. Quy tắc cộng dồn / deduplicate",
     "Mã lộ trình (LP-...) tự sinh, không trùng. Điều kiện đạt tính theo Đạt/Không đạt của từng khóa; % lộ trình = trung bình tiến độ các khóa."),
    ("7. Phân quyền cấp",
     "• Quyền quản lý lộ trình học (module Đào tạo). Không phân quyền theo công ty/phòng ban."),
    ("8. Cách tính các ô thống kê",
     "Bảng hiện Số khoá học, Tổng bài học, Thời lượng, Điều kiện đạt (pill: 'Bắt buộc ĐẠT'/'Tất cả khoá ĐẠT'/'≥X% khoá ĐẠT')."),
    ("9. Ghi chú đọc bảng",
     "Nút Lưu ở màn tạo luôn lưu ở trạng thái 'Đang dùng'. Label điều kiện đạt khác nhau giữa filter, tab Kết quả và cột bảng (xem cột J từng TC)."),
]

ROLE_TCS = [
    ("01", "Vào màn khi CÓ quyền", "P0",
     "Tài khoản có quyền quản lý lộ trình; có ≥3 lộ trình",
     "1. Vào menu Đào tạo > Lộ trình học",
     "Tài khoản: có quyền",
     "- Hiển thị bảng 'Danh sách lộ trình học tập' + nút 'Tạo mới'\n- Mỗi dòng có nút Xem/Sửa/Xoá + nút khoá",
     "—"),
    ("02", "Thao tác khi KHÔNG có quyền", "P0",
     "Tài khoản không có quyền",
     "1. Thử tạo lộ trình và bấm Lưu",
     "Tài khoản: không quyền",
     "- Bị chặn, không lưu được",
     "—"),
]

SECTIONS = [
    ("I", "HIỂN THỊ & LỌC", [
        ("001", "Xem danh sách mặc định", "P0",
         "Có 15 lộ trình",
         "1. Vào màn Lộ trình học\n2. Quan sát bảng",
         "—",
         "- Cột: STT, Mã lộ trình • Tên lộ trình, Loại đào tạo, Người tạo, Số khoá học, Tổng bài học, Thời lượng, Điều kiện đạt, Trạng thái, Cập nhật\n- Trạng thái hiện 'Nháp'/'Đang dùng'/'Đã khoá'",
         "—"),
        ("002", "Lọc theo Trạng thái = Đang dùng", "P1",
         "Có lộ trình Nháp/Đang dùng/Đã khoá",
         "1. Bấm 'Tìm kiếm nâng cao'\n2. Ở 'Trạng thái' chọn 'Đang dùng'",
         "Trạng thái: Đang dùng",
         "- Bảng chỉ còn lộ trình 'Đang dùng'",
         "—"),
        ("003", "Lọc theo Điều kiện đạt", "P2",
         "Có lộ trình nhiều điều kiện đạt",
         "1. Ở 'Điều kiện đạt' chọn 'Đạt tối thiểu X%'",
         "Điều kiện đạt: Đạt tối thiểu X%",
         "- Bảng chỉ còn lộ trình dùng quy tắc đạt tối thiểu %",
         "—"),
        ("004", "Tìm nhanh theo mã/tên", "P0",
         "Có lộ trình 'LT Backend'",
         "1. Gõ 'Backend' vào ô 'Tìm theo mã lộ trình, tên lộ trình...'",
         "Từ khóa: Backend",
         "- Bảng chỉ còn lộ trình khớp",
         "—"),
    ]),
    ("II", "TẠO/SỬA — THÔNG TIN", [
        ("001", "Tạo lộ trình hợp lệ (private)", "P0",
         "Có 2 khóa học",
         "1. Bấm 'Tạo mới'\n2. Tab 'Thông tin lộ trình học': nhập Tên, chọn Loại đào tạo, Kỹ năng\n3. Bấm 'Thêm khoá học' chọn 2 khóa\n4. Tab 'Cấu hình kết quả' chọn 'Tất cả khoá bắt buộc ĐẠT'\n5. Bấm 'Lưu'",
         "Tên: LT Backend",
         "- Toast 'Tạo lộ trình học thành công!'\n- Lộ trình có mã LP-..., trạng thái 'Đang dùng'",
         "—"),
        ("002", "Thiếu Tên lộ trình", "P0",
         "Form tạo",
         "1. Để trống 'Tên lộ trình học'\n2. Bấm 'Lưu'",
         "Tên: (trống)",
         "- Toast 'Vui lòng kiểm tra lại thông tin'\n- Báo lỗi 'Vui lòng nhập tên lộ trình học' (nhảy tab Thông tin)",
         "—"),
        ("003", "Thiếu Kỹ năng", "P0",
         "Form tạo",
         "1. Không chọn 'Kỹ năng'\n2. Bấm 'Lưu'",
         "Kỹ năng: (trống)",
         "- Báo lỗi 'Vui lòng chọn kỹ năng'",
         "—"),
        ("004", "Thiếu Loại đào tạo", "P1",
         "Form tạo",
         "1. Không chọn 'Loại đào tạo'\n2. Bấm 'Lưu'",
         "Loại đào tạo: (trống)",
         "- Báo lỗi 'Vui lòng chọn loại đào tạo'",
         "—"),
    ]),
    ("III", "KHÓA HỌC TRONG LỘ TRÌNH & PUBLIC", [
        ("001", "Bật Public chứa khóa chưa Public", "P0",
         "Có khóa SUB-0002 chưa Public",
         "1. Bật toggle 'Public'\n2. 'Thêm khoá học' chọn khóa SUB-0002 (chưa Public)\n3. Bấm 'Lưu'",
         "Public + khóa SUB-0002 chưa Public",
         "- Báo lỗi: 'Lộ trình Public chỉ được chứa khoá học Public. Vui lòng bỏ 1 khoá chưa Public (SUB-0002) hoặc tắt Public trước khi lưu.'\n- Khóa vi phạm hiện badge 'Cần Public'",
         "Public chỉ chứa khóa Public"),
        ("002", "Public chứa toàn khóa Public", "P0",
         "Các khóa đều Public",
         "1. Bật 'Public'\n2. Thêm 2 khóa Public\n3. Lưu",
         "Public + khóa Public",
         "- Toast 'Tạo lộ trình học thành công!'",
         "—"),
        ("003", "Modal ngân hàng khóa khi Public", "P1",
         "Lộ trình đang bật Public",
         "1. Bấm 'Thêm khoá học'\n2. Quan sát danh sách trong 'Ngân hàng khoá học'",
         "—",
         "- Chỉ hiển thị khóa Public (ghi chú: 'Lộ trình đang Public nên danh sách chỉ hiển thị các khoá học Public.')",
         "—"),
        ("004", "Sắp xếp thứ tự khóa", "P2",
         "Lộ trình có 3 khóa",
         "1. Kéo icon để đổi vị trí khóa\n2. Lưu",
         "—",
         "- Thứ tự khóa cập nhật đúng",
         "—"),
        ("005", "Đặt khóa Bắt buộc", "P2",
         "Lộ trình có 2 khóa",
         "1. Bấm 'Cấu hình khoá trong lộ trình' 1 khóa\n2. 'Bắt buộc' = Bắt buộc\n3. Nhập Ghi chú\n4. Lưu",
         "Bắt buộc: 1 khóa",
         "- Khóa đánh dấu bắt buộc trong lộ trình",
         "—"),
    ]),
    ("IV", "CẤU HÌNH KẾT QUẢ", [
        ("001", "Đạt tối thiểu % thiếu ngưỡng", "P0",
         "Tab 'Cấu hình kết quả'",
         "1. 'Điều kiện đạt lộ trình' = Đạt tối thiểu X% số khoá\n2. Để trống 'Ngưỡng (%)'\n3. Bấm 'Lưu'",
         "MIN_PERCENT, ngưỡng trống",
         "- Báo lỗi 'Vui lòng nhập ngưỡng % hợp lệ (1-100)' (nhảy tab Kết quả)",
         "—"),
        ("002", "Ngưỡng % ngoài 1-100", "P1",
         "Điều kiện đạt = Đạt tối thiểu X%",
         "1. Nhập 'Ngưỡng (%)' = 0\n2. Bấm 'Lưu'",
         "Ngưỡng: 0",
         "- Báo lỗi 'Vui lòng nhập ngưỡng % hợp lệ (1-100)'",
         "—"),
        ("003", "Đạt tối thiểu % hợp lệ", "P0",
         "Tab Kết quả",
         "1. 'Điều kiện đạt lộ trình' = Đạt tối thiểu X% số khoá\n2. 'Ngưỡng (%)' = 60\n3. Lưu",
         "Ngưỡng: 60",
         "- Lưu thành công; cột Điều kiện đạt hiện '≥60% khoá ĐẠT'",
         "—"),
        ("004", "Tất cả khoá ĐẠT (không cần %)", "P1",
         "Tab Kết quả",
         "1. 'Điều kiện đạt lộ trình' = Tất cả khoá trong lộ trình ĐẠT\n2. Lưu",
         "ALL_COURSES",
         "- Lưu thành công (không hiện ô Ngưỡng %)",
         "—"),
        ("005", "Hạn hoàn thành", "P2",
         "Tab Kết quả",
         "1. Nhập 'Hạn hoàn thành sau (ngày)' = 30\n2. Lưu",
         "30 ngày",
         "- Lưu OK; hạn = ngày tham gia + 30 ngày",
         "—"),
    ]),
    ("V", "NGƯỜI HỌC NỘI BỘ & CHỨNG CHỈ", [
        ("001", "Gán bắt buộc theo Phòng ban", "P0",
         "Tab 'Cấu hình người học'",
         "1. Khối 'Đối tượng bắt buộc phải học' tick pill 'Phòng ban'\n2. Chọn 2 phòng\n3. Lưu",
         "Bắt buộc: 2 phòng ban",
         "- Nhân viên thuộc phòng đó thuộc diện bắt buộc học lộ trình",
         "Gán theo nhóm"),
        ("002", "Gán khuyến khích theo Năng lực", "P1",
         "Tab người học",
         "1. Khối 'Đối tượng khuyến khích học' tick pill 'Năng lực'\n2. Chọn năng lực\n3. Lưu",
         "Khuyến khích: năng lực",
         "- Lưu OK",
         "—"),
        ("003", "Chứng chỉ đủ 4 trường", "P1",
         "Có ảnh mẫu PNG/JPG",
         "1. Tab 'Chứng chỉ' bật toggle (badge ON)\n2. 'Chọn ảnh' mẫu\n3. Điền 4 trường: Tên lộ trình, Họ tên, Ngày cấp, Người ký\n4. 'Render lại' xem preview\n5. Lưu",
         "4 trường",
         "- Preview đúng, lưu thành công",
         "—"),
    ]),
    ("VI", "KHÓA / MỞ KHÓA / XÓA", [
        ("001", "Nút khoá bị vô hiệu khi Đang dùng", "P0",
         "Lộ trình 'Đang dùng'",
         "1. Rê chuột vào nút khoá của dòng đó",
         "—",
         "- Nút khoá bị mờ/vô hiệu (tooltip 'Lộ trình đang dùng → không cho khoá')",
         "Đang dùng không cho khoá trực tiếp"),
        ("002", "Mở khoá lộ trình Đã khoá", "P1",
         "Lộ trình 'Đã khoá'",
         "1. Bấm nút mở khoá\n2. Popup 'Xác nhận mở khoá' → bấm 'Mở khoá'",
         "—",
         "- Toast 'Mở khoá lộ trình thành công', trạng thái → 'Đang dùng'",
         "—"),
        ("003", "Xóa lộ trình", "P0",
         "Lộ trình không ràng buộc",
         "1. Bấm Xoá\n2. Popup 'Xác nhận xóa': Bạn có chắc muốn xóa lộ trình \"{tên}\"? → bấm 'Xóa'",
         "—",
         "- Toast 'Xóa lộ trình học thành công', biến mất khỏi danh sách",
         "—"),
    ]),
    ("VII", "LUỒNG XUYÊN SUỐT (E2E)", [
        ("001", "Tạo lộ trình public đầy đủ", "P0",
         "Có ≥2 khóa Public, kỹ năng",
         "1. Tab Thông tin: Tên, Loại đào tạo, Kỹ năng, bật Public, thêm 2 khóa Public\n2. Tab Kết quả: Đạt tối thiểu 70%\n3. Tab Người học: gán 1 phòng ban bắt buộc\n4. Bấm 'Lưu'",
         "—",
         "- Toast 'Tạo lộ trình học thành công!', lộ trình có mã LP-...",
         "—"),
    ]),
]

build(
    output_file=r"d:\CompanyProject\hrm-cursor\.plans\elearning-quan-ly\lo-trinh-hoc\testcase.xlsx",
    sheet_name="LoTrinhHoc",
    feature_name="Lộ trình học",
    module_name="Lộ trình học",
    description_block=DESCRIPTION_BLOCK,
    sections=SECTIONS,
    role_tcs=ROLE_TCS,
)
