# -*- coding: utf-8 -*-
"""Testcase Cấu hình trang chủ Elearning — viết theo nhãn UI thật."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from _tc_builder import build

DESCRIPTION_BLOCK = [
    ("1. Mục đích tính năng",
     "Màn 'Cấu hình trang chủ Elearning' (Đào tạo > Cấu hình trang chủ) cho phép quản lý điều chỉnh Hero slide (banner đầu trang) và Footer của portal Elearning. Cấu hình lưu 1 dòng duy nhất; portal đọc lại qua API công khai site-config."),
    ("2. Đối tượng được tính / hiển thị",
     "► Màn gồm 2 tab: 'Hero slide' (mặc định) và 'Footer'.\n► Tab Hero: ô 'Tổng số slide tối đa hiển thị' + bảng 4 nguồn (Bạn cần học, Khuyến nghị, Nổi bật, Nội dung mới) với Số lượng tối đa + switch Hiển thị + kéo-thả thứ tự.\n► Tab Footer: switch khối Giới thiệu + Nội dung giới thiệu + Email/SĐT/Địa chỉ.\n► Chỉ người có quyền 'Quản lý cấu hình trang chủ elearning' mới vào được."),
    ("3. Đối tượng bị ẩn / không tính",
     "► Không có quyền → menu ẩn; mở URL trực tiếp thấy trang lỗi 403.\n► Nguồn đang TẮT 'Hiển thị' → ô Số lượng tối đa bị vô hiệu và không cấp slide cho portal.\n► Danh mục/khóa nổi bật/hoạt động gần đây KHÔNG cấu hình ở màn này."),
    ("4. Bộ lọc thời gian áp dụng cho",
     "Không áp dụng — màn cấu hình, không có bộ lọc thời gian."),
    ("5. Cấu trúc dữ liệu / cây phân cấp",
     "Bảng singleton elearning_home_settings (1 dòng). hero_sources là JSON 4 phần tử {key,is_active,sort_order,max_slots}. Footer gồm intro_enabled + intro + email/phone/address."),
    ("6. Quy tắc cộng dồn / deduplicate",
     "Portal trộn Hero (buildHeroSlides): lấy theo quota max_slots từng nguồn theo thứ tự → bù chỗ trống từ item dư → khử trùng theo type_id → cắt tối đa max_slides; rỗng → 1 slide dự phòng."),
    ("7. Phân quyền cấp",
     "• Quản lý cấu hình trang chủ elearning — quyền DUY NHẤT kiểm soát toàn màn (xem + lưu Hero + lưu Footer). Không phân quyền theo công ty/phòng ban. Định nghĩa tại PermissionsTableSeeder id=1084."),
    ("8. Cách tính các ô thống kê",
     "Không có ô thống kê. Số slide thực tế trên portal = min(max_slides, tổng slot các nguồn bật sau khử trùng). Mỗi nguồn góp tối đa max_slots slide."),
    ("9. Ghi chú đọc bảng",
     "Mỗi tab có nút 'Lưu' riêng (2 API riêng). Chỉ 'Tổng số slide tối đa hiển thị' có dấu bắt buộc (*); các trường Footer đều không bắt buộc. Thứ tự dòng trong bảng nguồn = thứ tự ưu tiên (sort_order) gửi lên."),
]

ROLE_TCS = [
    ("01", "Vào màn khi CÓ quyền", "P0",
     "Đăng nhập tài khoản có quyền 'Quản lý cấu hình trang chủ elearning'",
     "1. Vào menu Đào tạo > Cấu hình trang chủ",
     "Tài khoản: có quyền",
     "- Hiển thị tiêu đề 'Cấu hình trang chủ Elearning' + 2 tab 'Hero slide' / 'Footer'\n- Tab Hero mặc định active, đổ sẵn cấu hình đang lưu",
     "Quyền: Quản lý cấu hình trang chủ elearning"),
    ("02", "Vào màn khi KHÔNG có quyền", "P0",
     "Đăng nhập tài khoản không có quyền cấu hình trang chủ",
     "1. Mở trực tiếp đường dẫn /training/home_config",
     "Tài khoản: không quyền",
     "- Hiển thị trang lỗi 403, không thấy form cấu hình\n- Menu 'Cấu hình trang chủ' không hiện trong sidebar",
     "FE guard toàn trang + BE checkPermission"),
]

SECTIONS = [
    ("I", "HIỂN THỊ & TẢI CẤU HÌNH", [
        ("001", "Tải cấu hình lần đầu (chưa từng lưu)", "P1",
         "Bảng cấu hình chưa có dòng nào",
         "1. Vào màn Cấu hình trang chủ",
         "—",
         "- Tab Hero: 'Tổng số slide tối đa hiển thị' = 5\n- Nguồn: Bạn cần học (bật, SL 2), Khuyến nghị (bật, SL 1), Nổi bật (bật, SL 2), Nội dung mới (TẮT, SL 2)",
         "Giá trị mặc định trong bộ nhớ"),
        ("002", "Tải cấu hình đã lưu", "P0",
         "Đã từng lưu Hero max_slides=6, tắt nguồn Khuyến nghị",
         "1. Vào màn, xem tab Hero",
         "—",
         "- Ô tổng slide = 6\n- Nguồn Khuyến nghị switch Hiển thị = tắt, ô Số lượng của nó bị vô hiệu",
         "—"),
        ("003", "Tải cấu hình lỗi", "P2",
         "API GET cấu hình lỗi (mô phỏng)",
         "1. Vào màn khi API lỗi",
         "—",
         "- Toast 'Không tải được cấu hình trang chủ'",
         "—"),
        ("004", "Chuyển tab Footer", "P1",
         "Đang ở màn cấu hình",
         "1. Bấm tab 'Footer'",
         "—",
         "- Hiện switch khối 'Giới thiệu', ô 'Nội dung giới thiệu', mục 'Thông tin liên hệ' (Email/SĐT/Địa chỉ)",
         "—"),
    ]),
    ("II", "TAB HERO SLIDE — LƯU", [
        ("001", "Lưu Hero hợp lệ", "P0",
         "Ở tab Hero, cấu hình hợp lệ",
         "1. Nhập 'Tổng số slide tối đa hiển thị' = 5\n2. Bật cả 4 nguồn, mỗi nguồn Số lượng = 2\n3. Bấm 'Lưu'",
         "Tổng slide: 5",
         "- Toast 'Lưu thành công'\n- Cấu hình được lưu, updated_by = người đang đăng nhập",
         "BR-01, BR-03"),
        ("002", "Tổng số slide để trống", "P0",
         "Ở tab Hero",
         "1. Xóa trống ô 'Tổng số slide tối đa hiển thị'\n2. Bấm 'Lưu'",
         "Tổng slide: (trống)",
         "- Lỗi inline dưới ô: 'Bắt buộc nhập'\n- Toast 'Bạn chưa nhập đầy đủ thông tin'\n- Không lưu",
         "BR-01 (required)"),
        ("003", "Tổng số slide > 10", "P0",
         "Ở tab Hero",
         "1. Nhập 'Tổng số slide tối đa hiển thị' = 15\n2. Bấm 'Lưu'",
         "Tổng slide: 15",
         "- Lỗi inline 'Tối đa 10 slide'\n- Không lưu",
         "BR-01 (max:10)"),
        ("004", "Tổng số slide = 0", "P1",
         "Ở tab Hero",
         "1. Nhập 'Tổng số slide tối đa hiển thị' = 0\n2. Bấm 'Lưu'",
         "Tổng slide: 0",
         "- Lỗi inline 'Tối thiểu 1 slide'\n- Không lưu",
         "BR-01 (min:1)"),
        ("005", "Số lượng tối đa nguồn > 10", "P0",
         "Ở tab Hero, nguồn 'Nổi bật' đang bật",
         "1. Nhập Số lượng của 'Nổi bật' = 12\n2. Bấm 'Lưu'",
         "Số lượng Nổi bật: 12",
         "- Lỗi inline 'Tối đa 10' tại nguồn đó\n- Không lưu",
         "BR-03 (max:10)"),
        ("006", "Số lượng tối đa nguồn để trống", "P1",
         "Ở tab Hero, một nguồn để trống Số lượng",
         "1. Xóa trống ô Số lượng của 1 nguồn\n2. Bấm 'Lưu'",
         "Số lượng: (trống)",
         "- Lỗi inline 'Bắt buộc nhập số lượng'\n- Không lưu",
         "BR-03 (required)"),
        ("007", "Tắt Hiển thị → vô hiệu ô số lượng", "P1",
         "Nguồn 'Nội dung mới' đang bật",
         "1. Tắt switch 'Hiển thị' của 'Nội dung mới'",
         "—",
         "- Ô 'Số lượng tối đa' của nguồn đó chuyển sang bị vô hiệu (disabled)",
         "—"),
        ("008", "Đổi thứ tự ưu tiên bằng kéo-thả", "P1",
         "Ở tab Hero, 4 nguồn theo thứ tự mặc định",
         "1. Kéo nguồn 'Nổi bật' lên vị trí đầu\n2. Bấm 'Lưu'",
         "—",
         "- Thứ tự dòng cập nhật (Nổi bật đứng #1)\n- Toast 'Lưu thành công'\n- sort_order lưu theo thứ tự mới",
         "BR-04"),
        ("009", "Tắt hết các nguồn rồi lưu", "P2",
         "Ở tab Hero",
         "1. Tắt Hiển thị cả 4 nguồn\n2. Bấm 'Lưu'",
         "—",
         "- Lưu thành công (BE vẫn chấp nhận 4 nguồn is_active=0)\n- Portal khi render sẽ dùng slide dự phòng vì không nguồn nào cấp slide",
         "BR-05, BR-09"),
    ]),
    ("III", "TAB FOOTER — LƯU", [
        ("001", "Lưu Footer hợp lệ đầy đủ", "P0",
         "Ở tab Footer",
         "1. Bật switch khối 'Giới thiệu'\n2. Nhập 'Nội dung giới thiệu' hợp lệ\n3. Nhập Email = support@tanphatetek.com.vn, SĐT, Địa chỉ\n4. Bấm 'Lưu'",
         "Email: support@tanphatetek.com.vn",
         "- Toast 'Lưu thành công'\n- Footer portal cập nhật nội dung mới",
         "BR-06, BR-07"),
        ("002", "Ẩn khối Giới thiệu", "P1",
         "Ở tab Footer, khối Giới thiệu đang bật",
         "1. Tắt switch khối 'Giới thiệu' (chuyển 'Đang ẩn')\n2. Bấm 'Lưu'",
         "—",
         "- Toast 'Lưu thành công'\n- Portal ẩn khối Giới thiệu ở footer",
         "intro_enabled=0"),
        ("003", "Email sai định dạng", "P0",
         "Ở tab Footer",
         "1. Nhập Email = 'abc@' (sai)\n2. Bấm 'Lưu'",
         "Email: abc@",
         "- Lỗi inline 'Email không hợp lệ'\n- Toast 'Bạn chưa nhập đầy đủ thông tin'\n- Không lưu",
         "BR-07 (email)"),
        ("004", "Nội dung giới thiệu quá 1000 ký tự", "P1",
         "Ở tab Footer",
         "1. Nhập 'Nội dung giới thiệu' > 1000 ký tự\n2. Bấm 'Lưu'",
         "Độ dài: >1000",
         "- Lỗi inline 'Tối đa 1000 ký tự' (hoặc textarea chặn maxlength)\n- Không lưu nếu vượt",
         "BR-06 (max:1000)"),
        ("005", "Email vượt 150 ký tự", "P2",
         "Ở tab Footer",
         "1. Nhập Email dài > 150 ký tự\n2. Bấm 'Lưu'",
         "Độ dài email: >150",
         "- Lỗi inline 'Email tối đa 150 ký tự'\n- Không lưu",
         "BR-07 (max:150)"),
        ("006", "Để trống toàn bộ liên hệ", "P1",
         "Ở tab Footer",
         "1. Xóa trống Email/SĐT/Địa chỉ, tắt hoặc để trống Giới thiệu\n2. Bấm 'Lưu'",
         "—",
         "- Toast 'Lưu thành công' (các trường đều nullable)",
         "BR-07 (nullable)"),
    ]),
    ("IV", "PORTAL ĐỌC CẤU HÌNH (SITE-CONFIG)", [
        ("001", "Portal hiển thị hero theo quota", "P0",
         "Đã lưu: max_slides=5, need bật SL2, popular bật SL2, còn lại tắt",
         "1. Mở portal Elearning trang chủ",
         "—",
         "- Hero carousel hiển thị tối đa 5 slide, ưu tiên nội dung need rồi popular\n- Nguồn tắt không xuất hiện",
         "BR-05, BR-09"),
        ("002", "Hero dùng slide dự phòng khi không có nội dung", "P1",
         "Cấu hình bật nguồn nhưng không có nội dung phù hợp",
         "1. Mở trang chủ portal",
         "—",
         "- Hero hiển thị 1 slide dự phòng (banner mặc định, không CTA)",
         "BR-09"),
        ("003", "Footer portal theo cấu hình", "P1",
         "Đã lưu footer: bật Giới thiệu + Email/SĐT/Địa chỉ",
         "1. Cuộn xuống footer portal",
         "—",
         "- Khối Giới thiệu hiện đúng nội dung; hiện Email/SĐT/Địa chỉ đã cấu hình",
         "—"),
    ]),
    ("V", "LUỒNG XUYÊN SUỐT (E2E)", [
        ("001", "Đổi Hero → kiểm tra portal", "P0",
         "Có quyền cấu hình",
         "1. Tab Hero: đặt tổng slide=4, chỉ bật Nổi bật (SL4)\n2. Lưu\n3. Mở portal trang chủ",
         "—",
         "- Lưu thành công\n- Hero portal chỉ lấy nội dung nguồn Nổi bật, tối đa 4 slide",
         "BR-01, BR-04, BR-05, BR-09"),
        ("002", "Đổi Footer → kiểm tra portal", "P1",
         "Có quyền cấu hình",
         "1. Tab Footer: đổi Email + Nội dung giới thiệu\n2. Lưu\n3. Mở portal, xem footer",
         "—",
         "- Footer portal hiển thị Email + giới thiệu mới",
         "—"),
    ]),
]

build(
    output_file=r"d:\CompanyProject\hrm-cursor\.plans\elearning-quan-ly\cau-hinh-trang-chu\testcase.xlsx",
    sheet_name="CauHinhTrangChu",
    feature_name="Cấu hình trang chủ Elearning",
    module_name="Cấu hình trang chủ",
    description_block=DESCRIPTION_BLOCK,
    sections=SECTIONS,
    role_tcs=ROLE_TCS,
)
