# -*- coding: utf-8 -*-
"""Testcase Chi tiết khóa học (elearning) — theo nhãn UI thật."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from _tc_builder import build

DESCRIPTION_BLOCK = [
    ("1. Mục đích tính năng",
     "Trang chi tiết khóa học: giới thiệu khóa, cho tham gia (ghi danh), xem tiêu chí hoàn thành, xem nội dung chương→bài và vào học, thảo luận/đánh giá. Khóa exam-mode (nhân viên) có khối bài thi."),
    ("2. Đối tượng được tính / hiển thị",
     "► Trạng thái học: Chưa tham gia / Đã tham gia / Đang học / Đã hoàn thành → nút card đổi theo trạng thái.\n► Bài trong outline: Bắt buộc/Đã xong/Đang học/Khoá/Chưa học.\n► Khối bài thi chỉ hiện với khóa exam-mode + đã ghi danh."),
    ("3. Đối tượng bị ẩn / không tính",
     "► Khách chưa đăng nhập: bấm Tham gia/Học → yêu cầu đăng nhập.\n► Học viên ngoài + khóa exam-mode → bị chặn (chỉ dành cho nhân viên).\n► Không có quyền/khóa không tồn tại → khối lỗi."),
    ("4. Bộ lọc thời gian áp dụng cho", "Không áp dụng."),
    ("5. Cấu trúc dữ liệu / cây phân cấp", "Hero → Card ghi danh → Tabs (Tổng quan/Tiêu chí hoàn thành/Thảo luận) → Outline chương→bài."),
    ("6. Quy tắc cộng dồn / deduplicate", "Vào học yêu cầu đăng nhập + đã ghi danh + bài không khóa. Sau ghi danh khóa học → vào thẳng màn học."),
    ("7. Phân quyền cấp", "Không phân quyền cấp. Nhân viên nội bộ học khóa được gán; học viên ngoài học khóa Public."),
    ("8. Cách tính các ô thống kê", "Rating {avg}/5 ({n} đánh giá); tiến độ {progress}%; điều kiện đạt hiển thị theo cấu hình khóa."),
    ("9. Ghi chú đọc bảng", "Ghi danh khóa → toast 'Đã tham gia môn học' rồi vào thẳng màn học. Nút 'Làm đề thi' sang HRM."),
]

SECTIONS = [
    ("I", "XEM CHI TIẾT", [
        ("001", "Xem trang chi tiết khóa", "P0", "Khóa tồn tại, public",
         "1. Mở /khoa-hoc/:slug", "—",
         "- Hiện Hero (#mã + tên, rating, thời lượng), card ghi danh, 3 tab, outline 'Nội dung môn học'", "—"),
        ("002", "Khóa không tồn tại", "P1", "slug sai",
         "1. Mở /khoa-hoc/slug-sai", "—",
         "- Khối 'Không tìm thấy' + 'Khoá học bạn đang tìm không tồn tại hoặc đã bị xoá...' + nút 'Về trang chủ'", "—"),
        ("003", "Không có quyền + chưa đăng nhập", "P1", "Khóa yêu cầu đăng nhập",
         "1. Mở khóa khi chưa đăng nhập", "—",
         "- 'Bạn không có quyền truy cập' + 'Khoá học này yêu cầu đăng nhập...' + nút 'Đăng nhập'", "—"),
        ("004", "Xem tab Tổng quan", "P2", "Ở trang chi tiết",
         "1. Mở tab 'Tổng quan'", "—",
         "- 3 thẻ: 'Khoá học này có gì?', 'Dành cho ai?', 'Bạn sẽ học được gì?' (rỗng: 'Chưa có thông tin.')", "—"),
        ("005", "Xem tab Tiêu chí hoàn thành", "P1", "Ở trang chi tiết",
         "1. Mở tab 'Tiêu chí hoàn thành'", "—",
         "- Thẻ 'Điều kiện đạt của khoá học' + bảng chương/bài (Yêu cầu đạt, Trạng thái)", "—"),
    ]),
    ("II", "GHI DANH & VÀO HỌC", [
        ("001", "Tham gia khi chưa đăng nhập", "P0", "Chưa đăng nhập, trạng thái 'Chưa tham gia'",
         "1. Bấm 'Tham gia'", "—",
         "- Chuyển sang trang đăng nhập", "—"),
        ("002", "Tham gia thành công", "P0", "Đã đăng nhập, chưa tham gia khóa",
         "1. Bấm 'Tham gia'", "—",
         "- Toast 'Đã tham gia môn học'\n- Vào thẳng màn học", "Ghi danh khóa → vào học ngay"),
        ("003", "Nút card theo trạng thái Đang học", "P1", "Đã học dở khóa",
         "1. Quan sát card ghi danh", "—",
         "- Nhãn 'Đang học' + 'Tiến độ hiện tại: {n}%' + nút 'Tiếp tục học'", "—"),
        ("004", "Nút Chứng chỉ khi hoàn thành", "P1", "Đã hoàn thành khóa có chứng chỉ",
         "1. Quan sát card", "—",
         "- Nhãn 'Đã hoàn thành' + nút 'Chứng chỉ' + 'Xem lại nội dung'", "—"),
        ("005", "Vào học 1 bài từ outline", "P0", "Đã ghi danh, bài A không khóa",
         "1. Mở outline\n2. Bấm 'Mở' ở bài A", "—",
         "- Mở màn học đúng bài A", "—"),
        ("006", "Vào học khi chưa ghi danh", "P1", "Đã đăng nhập, chưa tham gia khóa",
         "1. Bấm 'Mở' ở 1 bài", "—",
         "- Toast 'Vui lòng tham gia khoá học trước khi học'", "—"),
        ("007", "Vào học bài đang khóa", "P1", "Bài B bị khóa",
         "1. Bấm 'Mở' ở bài B", "—",
         "- Toast 'Bài đang bị khoá: cần hoàn thành bài trước'", "—"),
        ("008", "Mở/đóng tất cả chương", "P2", "Khóa có nhiều chương",
         "1. Bấm 'Mở tất cả chương'\n2. Bấm 'Đóng tất cả chương'", "—",
         "- Bung/thu toàn bộ danh sách bài", "—"),
    ]),
    ("III", "BÀI THI (EXAM-MODE)", [
        ("001", "Khối bài thi hiển thị", "P0", "Nhân viên đã ghi danh khóa exam-mode",
         "1. Xem card ghi danh", "—",
         "- Hiện khối 'Đánh giá bằng bài thi' + 'Lượt thi: {used}/{limit}' + nút 'Làm đề thi'", "—"),
        ("002", "Học viên ngoài bị chặn exam-mode", "P0", "Học viên ngoài, khóa exam-mode",
         "1. Xem card ghi danh", "—",
         "- Ẩn nút; hiện 'Khoá học này hoàn thành bằng bài thi trên hệ thống nội bộ — chỉ dành cho nhân viên...'", "BR-04"),
        ("003", "Chưa đủ điều kiện thi", "P1", "Chưa hoàn thành đủ % bài học",
         "1. Xem nút 'Làm đề thi'", "—",
         "- Nút bị vô hiệu + 'Cần hoàn thành ≥ {X}% bài học để được thi.'", "—"),
        ("004", "Làm đề thi deep-link HRM", "P1", "Đủ điều kiện thi",
         "1. Bấm 'Làm đề thi'", "—",
         "- Chuyển sang hệ thống HRM (kèm link quay lại)", "—"),
        ("005", "Xem lịch sử thi", "P2", "Đã thi ≥1 lần",
         "1. Bấm 'Lịch sử thi ({n})'", "—",
         "- Mở popup lịch sử các lượt thi", "—"),
    ]),
    ("IV", "THẢO LUẬN", [
        ("001", "Gửi bình luận + đánh giá", "P1", "Đã đăng nhập, tab Thảo luận",
         "1. Chọn 'Đánh giá' = 5 - Rất tốt\n2. Nhập 'Nội dung'\n3. Bấm 'Gửi'", "5 sao + nội dung",
         "- Toast 'Đã gửi bình luận', bình luận xuất hiện", "—"),
        ("002", "Gửi bình luận trống", "P2", "Tab Thảo luận",
         "1. Để trống 'Nội dung'\n2. Bấm 'Gửi'", "(trống)",
         "- Toast 'Vui lòng nhập nội dung bình luận'", "—"),
        ("003", "Bình luận khi chưa đăng nhập", "P2", "Chưa đăng nhập",
         "1. Bấm 'Gửi' bình luận", "—",
         "- Chuyển sang trang đăng nhập", "—"),
        ("004", "Trả lời / Thích / Báo cáo", "P2", "Có bình luận sẵn",
         "1. Bấm 'Trả lời' / 'Thích' / 'Báo cáo' một bình luận", "—",
         "- Trả lời: mở ô 'Viết câu trả lời...'; Báo cáo: popup 'Báo cáo bình luận' (Spam/Nội dung không phù hợp/...)", "—"),
        ("005", "Trang thảo luận riêng + lọc sao", "P2", "Khóa có nhiều đánh giá",
         "1. Mở /khoa-hoc/:slug/thao-luan\n2. Bấm lọc '5 sao'", "—",
         "- Hiện tổng đánh giá {avg}/5, các thanh sao; lọc theo '5 sao' đúng", "—"),
    ]),
]

build(
    output_file=r"d:\CompanyProject\hrm-cursor\.plans\elearning-hoc-vien\chi-tiet-khoa-hoc\testcase.xlsx",
    sheet_name="ChiTietKhoaHoc", feature_name="Chi tiết khóa học", module_name="Chi tiết khóa",
    description_block=DESCRIPTION_BLOCK, sections=SECTIONS, role_tcs=None,
)
