# -*- coding: utf-8 -*-
"""Testcase Học theo danh mục (elearning) — theo nhãn UI thật, phân biệt vai trò."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from _tc_builder import build

DESCRIPTION_BLOCK = [
    ("1. Mục đích tính năng",
     "Màn 'Học theo danh mục' (/hoc-theo-danh-muc) cho học viên duyệt & lọc nội dung học tập TRỘN Khóa học + Lộ trình theo Loại đào tạo (danh mục), Loại nội dung và Trạng thái. Mở khi bấm vào 1 danh mục ở trang chủ. Có sidebar lọc, sắp xếp, phân trang, card đi tới chi tiết."),
    ("2. Đối tượng được tính / hiển thị",
     "► Card = Khóa học (type=course) hoặc Lộ trình (type=path).\n► Nhân viên nội bộ (employee): thấy TẤT CẢ nội dung Hoạt động (kể cả không công khai).\n► Khách (guest) & học viên độc lập (learner): CHỈ thấy nội dung công khai (is_public=1).\n► Badge trạng thái học (Đang học/Đã hoàn thành) + Hạn: chỉ hiện khi đã đăng nhập & đã học."),
    ("3. Đối tượng bị ẩn / không tính",
     "► Guest/learner không thấy nội dung không công khai.\n► Guest không có badge trạng thái học, không có 'Hạn', nút card luôn 'Chi tiết'.\n► Lọc 'Bắt buộc' với guest/không hồ sơ → gần như rỗng."),
    ("4. Bộ lọc thời gian áp dụng cho",
     "Không có bộ lọc theo khoảng thời gian ở màn này (khác màn 'Học theo loại đào tạo' có lọc Thời lượng)."),
    ("5. Cấu trúc dữ liệu / cây phân cấp",
     "Danh sách phẳng trộn 2 nguồn (Subject + LearningPath), phân trang. Sidebar lọc: Loại nội dung / Loại đào tạo / Trạng thái + ô tìm từ khoá."),
    ("6. Quy tắc cộng dồn / deduplicate",
     "BE gộp Subject + LearningPath, sort chung bằng comparator theo sort_by, rồi cắt trang. per_page tối đa 24 (mặc định 18)."),
    ("7. Phân quyền cấp",
     "Route CÔNG KHAI, không phân quyền cấp. Middleware elearning.auth.optional xác định user_type (guest/learner/employee) để quyết định phạm vi nội dung & trạng thái học."),
    ("8. Cách tính các ô thống kê",
     "Pill đếm = '{total} nội dung • Trang {page}/{totalPages}'. total = số nội dung khớp bộ lọc (theo vai trò). Đánh giá card = '{sao} ({số} vote)' hoặc 'Chưa có đánh giá'."),
    ("9. Ghi chú đọc bảng",
     "Sort options: Phổ biến (popular, mặc định) / Mới nhất (newest) / Đánh giá cao (rating). Page size: 12/18/24 (mặc định 18). Đổi filter/sort/keyword → reset về trang 1 + đồng bộ URL. Card path → /lo-trinh/:slug; course → /khoa-hoc/:slug."),
]

ROLE_TCS = [
    ("00", "Truy cập mặc định (khách chưa đăng nhập)", "P0",
     "Chưa đăng nhập; mở /hoc-theo-danh-muc",
     "1. Mở màn không đăng nhập",
     "Vai trò: guest",
     "- Vào được (route công khai)\n- Chỉ thấy nội dung công khai\n- Card không có badge 'Đang học'/'Đã hoàn thành', không 'Hạn', nút luôn 'Chi tiết'",
     "user_type=guest; chỉ is_public=1"),
    ("01", "Học viên độc lập (learner)", "P0",
     "Đăng nhập học viên elearning; đã học dở vài nội dung công khai",
     "1. Mở màn",
     "Vai trò: learner",
     "- Chỉ thấy nội dung công khai\n- Nội dung đã học hiện badge 'Đang học {%}' / 'Đã hoàn thành' + nút 'Học tiếp'/'Xem lại'",
     "user_type=learner; is_public=1 + tiến độ riêng"),
    ("02", "Nhân viên nội bộ (employee)", "P0",
     "Đăng nhập SSO nhân viên HRM",
     "1. Mở màn",
     "Vai trò: employee",
     "- Thấy TẤT CẢ nội dung Hoạt động (kể cả KHÔNG công khai)\n- Có badge trạng thái học + Hạn hoàn thành nếu được giao",
     "user_type=employee; thấy toàn bộ Hoạt động"),
]

SECTIONS = [
    ("I", "VÀO MÀN & HIỂN THỊ", [
        ("001", "Mở từ danh mục ở trang chủ", "P0",
         "Ở trang chủ, có danh mục 'An toàn lao động'",
         "1. Bấm danh mục 'An toàn lao động' trên trang chủ",
         "—",
         "- Chuyển sang /hoc-theo-danh-muc?training_type_id=...\n- Breadcrumb: Trang chủ / Học theo danh mục / An toàn lao động\n- Chip 'Loại đào tạo: An toàn lao động'",
         "UC-01"),
        ("002", "Mở trực tiếp không kèm danh mục", "P1",
         "Mở URL /hoc-theo-danh-muc",
         "1. Mở màn trực tiếp",
         "—",
         "- Hiển thị TẤT CẢ nội dung\n- Pill 'Tất cả danh mục'",
         "UC-01 alt"),
        ("003", "Card trộn Khóa học + Lộ trình", "P0",
         "Có ≥1 khóa học và ≥1 lộ trình công khai",
         "1. Xem lưới card",
         "—",
         "- Card có badge loại 'Khoá học' và 'Lộ trình'\n- Cả 2 loại cùng xuất hiện",
         "BR-01"),
        ("004", "Loading skeleton", "P2",
         "Mạng chậm / đang tải",
         "1. Mở màn, quan sát khi đang tải",
         "—",
         "- Hiển thị lưới 6 ô skeleton trước khi ra card",
         "—"),
        ("005", "Nhiều danh mục → pill gộp", "P2",
         "Chọn 2 loại đào tạo",
         "1. Tick 2 danh mục ở 'Loại đào tạo'",
         "—",
         "- Pill hiển thị '2 loại đào tạo'",
         "—"),
    ]),
    ("II", "BỘ LỌC & TÌM KIẾM", [
        ("001", "Tìm theo từ khoá", "P0",
         "Có nội dung tên chứa 'Excel'",
         "1. Gõ 'Excel' vào ô 'Tìm theo từ khoá'",
         "Từ khoá: Excel",
         "- Danh sách chỉ còn nội dung khớp 'Excel'\n- Chip 'Từ khoá: Excel'\n- Về trang 1",
         "BR-06"),
        ("002", "Lọc Loại nội dung = Lộ trình", "P0",
         "Có cả khóa học và lộ trình",
         "1. Tick 'Lộ trình' ở block 'Loại nội dung'",
         "Loại nội dung: Lộ trình",
         "- Chỉ còn card badge 'Lộ trình'\n- Chip 'Loại nội dung: Lộ trình'",
         "BR-01"),
        ("003", "Lọc Loại nội dung = Khoá học", "P1",
         "Có cả 2 loại",
         "1. Tick 'Khoá học'",
         "Loại nội dung: Khoá học",
         "- Chỉ còn card badge 'Khoá học'",
         "—"),
        ("004", "Lọc Trạng thái = Tự chọn", "P1",
         "Có nội dung tự chọn và bắt buộc",
         "1. Tick 'Tự chọn' ở block 'Trạng thái'",
         "Trạng thái: Tự chọn",
         "- Danh sách còn nội dung tự chọn\n- Chip 'Trạng thái: Tự chọn'",
         "BR-04"),
        ("005", "Lọc Trạng thái = Bắt buộc (nhân viên có hồ sơ)", "P1",
         "Nhân viên có nội dung bắt buộc theo phòng ban",
         "1. Đăng nhập nhân viên\n2. Tick 'Bắt buộc'",
         "Vai trò: employee",
         "- Chỉ còn nội dung bắt buộc theo hồ sơ nhân viên đó",
         "BR-04"),
        ("006", "Lọc 'Bắt buộc' khi là khách", "P2",
         "Khách chưa đăng nhập",
         "1. Tick 'Bắt buộc'",
         "Vai trò: guest",
         "- Danh sách gần như rỗng (không có hồ sơ để khớp)",
         "BR-04"),
        ("007", "Kết hợp nhiều bộ lọc", "P1",
         "Có dữ liệu đa dạng",
         "1. Tick 'Khoá học' + 1 danh mục + gõ từ khoá",
         "—",
         "- Danh sách khớp đồng thời cả 3 điều kiện\n- Nhiều chip 'Đang lọc' cùng hiện",
         "BR-06"),
        ("008", "Không có kết quả", "P1",
         "Không nội dung nào khớp",
         "1. Gõ từ khoá 'zzzxyz'",
         "Từ khoá: zzzxyz",
         "- Empty state: 'Không có nội dung phù hợp bộ lọc' + 'Thử bỏ bớt lựa chọn hoặc bấm Reset.' + nút 'Reset bộ lọc'",
         "—"),
    ]),
    ("III", "SẮP XẾP & PHÂN TRANG", [
        ("001", "Sắp xếp Mới nhất", "P1",
         "Có nhiều nội dung",
         "1. Mở 'Sắp xếp', chọn 'Mới nhất'",
         "Sort: Mới nhất",
         "- Danh sách sắp theo mới nhất\n- Về trang 1",
         "BR-05"),
        ("002", "Sắp xếp Đánh giá cao", "P2",
         "Nội dung có đánh giá",
         "1. Chọn 'Đánh giá cao'",
         "Sort: Đánh giá cao",
         "- Nội dung điểm sao cao lên đầu",
         "BR-05"),
        ("003", "Đổi số dòng/trang", "P1",
         "Có > 24 nội dung",
         "1. Chọn '24 / trang'",
         "Page size: 24",
         "- Mỗi trang hiển thị tối đa 24 card\n- Số trang tính lại",
         "BR-05 (per_page ≤ 24)"),
        ("004", "Chuyển trang", "P0",
         "Có 3 trang kết quả",
         "1. Bấm '2' rồi '►'",
         "—",
         "- Tải trang tương ứng, tự cuộn lên đầu\n- Số 'Trang x/3' cập nhật",
         "—"),
        ("005", "Phân trang ẩn khi 1 trang", "P2",
         "Kết quả ≤ 1 trang",
         "1. Lọc còn ít kết quả",
         "—",
         "- Không hiển thị thanh phân trang",
         "—"),
    ]),
    ("IV", "XÓA BỘ LỌC", [
        ("001", "Bỏ 1 chip lọc", "P1",
         "Đang lọc theo 'Loại đào tạo' + từ khoá",
         "1. Bấm x trên chip 'Loại đào tạo: ...'",
         "—",
         "- Bỏ nhóm lọc đó, giữ từ khoá\n- Danh sách tải lại",
         "UC-04"),
        ("002", "Xoá tất cả", "P0",
         "Đang có nhiều bộ lọc",
         "1. Bấm 'Xoá tất cả'",
         "—",
         "- Xóa toàn bộ chip; danh sách mở rộng lại",
         "UC-04"),
        ("003", "Reset ở sidebar", "P1",
         "Đang có bộ lọc",
         "1. Bấm 'Reset' ở đầu sidebar 'Bộ lọc'",
         "—",
         "- Toàn bộ filter về mặc định",
         "UC-04"),
        ("004", "Reset từ empty state", "P2",
         "Đang ở trạng thái không có kết quả",
         "1. Bấm 'Reset bộ lọc' trong empty state",
         "—",
         "- Xóa lọc, danh sách hiển thị lại",
         "—"),
        ("005", "Breadcrumb 'Học theo danh mục' reset", "P2",
         "Đang lọc theo danh mục",
         "1. Bấm 'Học theo danh mục' trên breadcrumb",
         "—",
         "- Reset về tất cả danh mục",
         "—"),
    ]),
    ("V", "MỞ CHI TIẾT TỪ CARD", [
        ("001", "Mở chi tiết Khóa học", "P0",
         "Có card 'Khoá học'",
         "1. Bấm card một Khóa học (hoặc nút 'Chi tiết')",
         "—",
         "- Chuyển /khoa-hoc/:slug (trang chi tiết khóa học)",
         "BR-07"),
        ("002", "Mở chi tiết Lộ trình", "P0",
         "Có card 'Lộ trình'",
         "1. Bấm card một Lộ trình",
         "—",
         "- Chuyển /lo-trinh/:slug (trang chi tiết lộ trình)",
         "BR-07"),
        ("003", "Nút 'Học tiếp' khi đang học", "P1",
         "Học viên đăng nhập, có nội dung đang học",
         "1. Bấm 'Học tiếp' trên card 'Đang học {%}'",
         "Vai trò: learner",
         "- Vào chi tiết để tiếp tục học",
         "BR-03"),
        ("004", "Nút 'Xem lại' khi đã hoàn thành", "P2",
         "Có nội dung đã hoàn thành",
         "1. Bấm 'Xem lại'",
         "—",
         "- Vào chi tiết nội dung đã hoàn thành",
         "—"),
    ]),
    ("VI", "LUỒNG XUYÊN SUỐT (E2E)", [
        ("001", "Từ trang chủ → lọc → chi tiết", "P0",
         "Học viên đăng nhập",
         "1. Bấm danh mục ở trang chủ\n2. Tick 'Khoá học' + gõ từ khoá\n3. Chọn 'Mới nhất'\n4. Bấm 1 card",
         "—",
         "- B1: vào màn đúng danh mục\n- B2-3: danh sách lọc + sắp đúng\n- B4: vào chi tiết khóa học",
         "—"),
    ]),
]

build(
    output_file=r"d:\CompanyProject\hrm-cursor\.plans\elearning-hoc-vien\hoc-theo-danh-muc\testcase.xlsx",
    sheet_name="HocTheoDanhMuc",
    feature_name="Học theo danh mục",
    module_name="Học theo danh mục",
    description_block=DESCRIPTION_BLOCK,
    sections=SECTIONS,
    role_tcs=ROLE_TCS,
)
