# -*- coding: utf-8 -*-
"""Testcase Khóa học — viết theo ngôn ngữ UI thật cho tester."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from _tc_builder import build

DESCRIPTION_BLOCK = [
    ("1. Mục đích tính năng",
     "Màn 'Danh sách khoá học' để thiết kế khóa học gồm nhiều bài học theo chương/bài, chọn cách đánh giá (Theo % hoàn thành bài học hoặc Theo bài thi), gán người học và cấp chứng chỉ. Form builder có 4 tab: 'Thông tin khoá học', 'Cấu hình đánh giá', 'Cấu hình người học', 'Chứng chỉ'."),
    ("2. Đối tượng được tính / hiển thị",
     "► Khóa 'Hoạt động': sửa/khóa/xóa (theo điều kiện).\n► Khóa 'Khoá': không sửa được.\n► Khóa 'Nháp': lưu nhanh, luôn sửa/xóa được.\n► Bộ lọc Hình thức đánh giá: 'Theo % hoàn thành bài học' / 'Theo bài thi'."),
    ("3. Đối tượng bị ẩn / không tính",
     "► Không có quyền quản lý khoá học → không thao tác được.\n► Khóa 'Khoá' → không sửa.\n► Khóa 'Hoạt động' đã bị dùng ở nơi khác → không xóa được."),
    ("4. Bộ lọc thời gian áp dụng cho",
     "'Cập nhật từ' ... 'Đến' lọc theo ngày cập nhật gần nhất."),
    ("5. Cấu trúc dữ liệu / cây phân cấp",
     "Khóa học → Chương → Bài học (builder nằm ở nửa phải tab 'Thông tin khoá học'). Có thể chọn 'Có chương' hoặc 'Không có chương'. Mỗi bài có thể ghi đè tiêu chí hoàn thành + đặt điều kiện mở khoá (prerequisite)."),
    ("6. Quy tắc cộng dồn / deduplicate",
     "Mã khóa (SUB-xxxx) tự sinh, không trùng. Chứng chỉ phải cấu hình đủ 4 trường: Tên khoá học, Họ tên, Ngày cấp, Người ký."),
    ("7. Phân quyền cấp",
     "• Quản lý khoá học — quyền DUY NHẤT cho tạo/sửa/khóa/xóa/xuất Excel. Không phân quyền theo công ty/phòng ban."),
    ("8. Cách tính các ô thống kê",
     "Không có ô thống kê. Bảng hiển thị Số chương, Số bài học, Thời gian học. Trạng thái: 'Hoạt động'/'Khoá'/'Nháp'."),
    ("9. Ghi chú đọc bảng",
     "Nút lưu là 'Lưu' (kích hoạt) hoặc 'Lưu nháp'. LƯU Ý wording: danh sách dùng 'Khoá', dropdown Trạng thái trong tab Thông tin dùng 'Khóa'. Tên tab thứ 3 là 'Cấu hình người học' (gán theo nhóm đối tượng)."),
]

ROLE_TCS = [
    ("01", "Vào màn khi CÓ quyền", "P0",
     "Tài khoản có quyền quản lý khoá học; có ≥3 khóa",
     "1. Vào menu Đào tạo > Khoá học",
     "Tài khoản: có quyền",
     "- Hiển thị bảng 'Danh sách khoá học' + nút 'Tạo mới', 'Xuất Excel'\n- Mỗi dòng có nút Xem/Sửa/Xoá/Khoá",
     "Quyền: Quản lý khoá học"),
    ("02", "Thao tác khi KHÔNG có quyền", "P0",
     "Tài khoản không có quyền quản lý khoá học",
     "1. Thử tạo/sửa khóa và bấm Lưu",
     "Tài khoản: không quyền",
     "- Bị chặn, không lưu được",
     "—"),
]

SECTIONS = [
    ("I", "HIỂN THỊ & LỌC", [
        ("001", "Xem danh sách mặc định", "P0",
         "Có 20 khóa học",
         "1. Vào màn Khoá học\n2. Quan sát bảng",
         "—",
         "- Cột: STT, Mã khoá học - Tên khoá học, Loại đào tạo, Hình thức đánh giá, Số chương, Số bài học, Thời gian học, Trạng thái, Cập nhật\n- Trạng thái hiện 'Hoạt động'/'Khoá'/'Nháp'",
         "—"),
        ("002", "Lọc theo Hình thức đánh giá", "P1",
         "Có khóa đánh giá theo % và theo bài thi",
         "1. Bấm 'Tìm kiếm nâng cao'\n2. Ở 'Hình thức đánh giá' chọn 'Theo bài thi'",
         "Hình thức đánh giá: Theo bài thi",
         "- Bảng chỉ còn khóa đánh giá theo bài thi",
         "—"),
        ("003", "Lọc theo Trạng thái = Nháp", "P1",
         "Có khóa Hoạt động/Khoá/Nháp",
         "1. Ở 'Trạng thái' chọn 'Nháp'",
         "Trạng thái: Nháp",
         "- Bảng chỉ còn khóa Nháp",
         "—"),
        ("004", "Tìm nhanh theo mã/tên", "P0",
         "Có khóa mã SUB-0001 'Laravel cơ bản'",
         "1. Gõ 'Laravel' vào ô 'Tìm theo mã khoá học (SUB-0001), tên khoá học...'",
         "Từ khóa: Laravel",
         "- Bảng chỉ còn khóa khớp",
         "—"),
    ]),
    ("II", "TẠO/SỬA — THÔNG TIN & LƯU NHÁP", [
        ("001", "Lưu nháp chỉ với tên", "P0",
         "Có quyền",
         "1. Bấm 'Tạo mới'\n2. Tab 'Thông tin khoá học' nhập 'Tên khoá học'\n3. Bấm 'Lưu nháp'",
         "Tên: KH nháp",
         "- Toast 'Lưu tạm khoá học thành công'\n- Khóa có mã SUB-xxxx, trạng thái Nháp",
         "Lưu nháp bỏ qua kiểm tra chi tiết"),
        ("002", "Lưu (kích hoạt) thiếu Tên", "P0",
         "Tab Thông tin",
         "1. Để trống 'Tên khoá học'\n2. Bấm 'Lưu'",
         "Tên: (trống)",
         "- Báo lỗi 'Vui lòng nhập tên khoá học' (nhảy về tab Thông tin)",
         "—"),
        ("003", "Lưu thiếu Kỹ năng", "P0",
         "Tab Thông tin",
         "1. Không chọn 'Kỹ năng'\n2. Bấm 'Lưu'",
         "Kỹ năng: (trống)",
         "- Báo lỗi 'Vui lòng chọn kỹ năng'",
         "—"),
        ("004", "Lưu thiếu Độ khó", "P0",
         "Tab Thông tin",
         "1. Không chọn 'Độ khó'\n2. Bấm 'Lưu'",
         "Độ khó: (trống)",
         "- Báo lỗi 'Vui lòng chọn độ khó'",
         "Độ khó: Cơ bản/Trung cấp/Nâng cao"),
        ("005", "Lưu thiếu Loại đào tạo", "P1",
         "Tab Thông tin",
         "1. Không chọn 'Loại đào tạo'\n2. Bấm 'Lưu'",
         "Loại đào tạo: (trống)",
         "- Báo lỗi 'Vui lòng chọn loại đào tạo'",
         "—"),
    ]),
    ("III", "BUILDER CHƯƠNG / BÀI HỌC", [
        ("001", "Thêm chương thiếu mã/tên", "P0",
         "Tab Thông tin, chọn 'Có chương'",
         "1. Bấm 'Thêm chương'\n2. Popup 'Thêm chương' để trống 'Mã chương' hoặc 'Tên chương'\n3. Bấm 'Lưu'",
         "Mã/Tên chương: (trống)",
         "- Báo lỗi 'Mã chương bắt buộc' / 'Tên chương bắt buộc'",
         "—"),
        ("002", "Tạo khóa có chương + bài hợp lệ", "P0",
         "Có bài học trong ngân hàng",
         "1. Chọn 'Có chương'\n2. 'Thêm chương' (mã CH-01, tên Tổng quan)\n3. Trong chương bấm + chọn 2 bài từ 'Ngân hàng bài học'\n4. Điền đủ Thông tin\n5. Bấm 'Lưu'",
         "1 chương + 2 bài",
         "- Toast 'Thêm khoá học thành công'\n- Khóa có 1 chương, 2 bài đúng thứ tự",
         "—"),
        ("003", "Chọn 'Không có chương'", "P1",
         "Có bài học trong ngân hàng",
         "1. Chọn 'Không có chương'\n2. Bấm 'Thêm bài học (từ ngân hàng)' chọn 2 bài\n3. Lưu",
         "2 bài phẳng",
         "- Lưu thành công, khóa có 2 bài không chương",
         "—"),
        ("004", "Sắp xếp thứ tự chương", "P2",
         "Khóa có 3 chương",
         "1. Kéo icon để đổi vị trí chương\n2. Lưu",
         "—",
         "- Thứ tự chương cập nhật đúng",
         "—"),
        ("005", "Đặt điều kiện mở khoá bài", "P2",
         "Bài B muốn mở sau khi xong bài A",
         "1. Mở 'Cấu hình bài học trong môn (Mapping)' của bài B\n2. Bật 'Bật điều kiện mở khoá'\n3. Chế độ 'ALL (phải xong hết)'\n4. Tick bài A ở 'Danh sách bài cần hoàn thành trước'\n5. Lưu cấu hình",
         "Prerequisite: bài A",
         "- Bài B hiện badge 'Mở khoá'; phía học viên phải xong A mới học B",
         "—"),
    ]),
    ("IV", "ĐÁNH GIÁ — THEO % HOÀN THÀNH", [
        ("001", "Chọn đánh giá theo % + rule", "P0",
         "Khóa đã có chương/bài",
         "1. Tab 'Cấu hình đánh giá'\n2. 'Hình thức đánh giá' = Theo % hoàn thành bài học\n3. 'Rule đạt khoá' = Hoàn thành 100% bài bắt buộc\n4. Lưu",
         "completion + 100% bắt buộc",
         "- Lưu thành công",
         "—"),
        ("002", "Rule theo % nhập tỷ lệ", "P1",
         "Hình thức = Theo % hoàn thành",
         "1. 'Rule đạt khoá' = Hoàn thành theo %\n2. 'Tỷ lệ yêu cầu (%)' = 80\n3. 'Cách tính %' = Chỉ tính bài bắt buộc\n4. Lưu",
         "percent 80, required_only",
         "- Lưu thành công",
         "—"),
    ]),
    ("V", "ĐÁNH GIÁ — THEO BÀI THI", [
        ("001", "Chọn bài thi nhưng chưa chọn đề", "P0",
         "Hình thức = Theo bài thi",
         "1. Tab 'Cấu hình đánh giá' chọn 'Theo bài thi'\n2. Không chọn đề nào ở 'Chọn đề thi (ngân hàng đề thi)'\n3. Bấm 'Lưu'",
         "Đề thi: (chưa chọn)",
         "- Báo lỗi 'Vui lòng chọn ít nhất một đề thi'",
         "—"),
        ("002", "Đề tự luận thiếu người chấm", "P1",
         "Đề đã chọn có câu tự luận",
         "1. Chọn đề có câu tự luận, để trống 'Người chấm thi'\n2. Bấm 'Lưu'",
         "Người chấm: (trống)",
         "- Báo lỗi 'Đề có câu tự luận, vui lòng chọn ít nhất 1 người chấm'",
         "—"),
        ("003", "Quy tắc điểm Trung bình thiếu ngưỡng", "P0",
         "Hình thức = Theo bài thi, đã chọn đề",
         "1. 'Quy tắc lấy điểm (theo khoá)' = Trung bình\n2. Để trống 'Ngưỡng đạt khóa (%)'\n3. Bấm 'Lưu'",
         "Quy tắc: Trung bình; ngưỡng trống",
         "- Báo lỗi (từ hệ thống) yêu cầu nhập ngưỡng đạt cấp khóa",
         "average bắt buộc ngưỡng"),
        ("004", "Bắt buộc học trước thi thiếu %", "P1",
         "Hình thức = Theo bài thi",
         "1. 'Quy tắc tham gia thi' = Bắt buộc học trước khi thi\n2. Để trống 'Tối thiểu % bài bắt buộc đã hoàn thành'\n3. Bấm 'Lưu'",
         "participation required; % trống",
         "- Báo lỗi yêu cầu nhập % tối thiểu",
         "—"),
        ("005", "Bài thi hợp lệ (Lấy điểm cao nhất)", "P0",
         "Đã chọn đề, điền đủ",
         "1. 'Quy tắc lấy điểm' = Lấy điểm cao nhất\n2. Nhập 'Số lần thi'=2\n3. Nhập 'Điểm đạt (%)' cho đề\n4. Lưu",
         "highest, 2 lần",
         "- Toast 'Thêm khoá học thành công'",
         "—"),
    ]),
    ("VI", "CHỨNG CHỈ", [
        ("001", "Bật chứng chỉ nhưng chưa upload mẫu", "P1",
         "Tab 'Chứng chỉ'",
         "1. Bật toggle chứng chỉ (badge chuyển ON)\n2. Không 'Chọn ảnh' mẫu\n3. Bấm 'Lưu'",
         "certificate ON, chưa có mẫu",
         "- Báo lỗi yêu cầu chọn ảnh mẫu chứng chỉ",
         "—"),
        ("002", "Chứng chỉ hợp lệ đủ 4 trường", "P1",
         "Có ảnh mẫu PNG/JPG",
         "1. Bật chứng chỉ, 'Chọn ảnh' mẫu\n2. Điền 4 trường: Tên khoá học, Họ tên, Ngày cấp, Người ký (X/Y/Cỡ chữ/Weight)\n3. Bấm 'Render lại' để xem preview\n4. Lưu",
         "4 trường đầy đủ",
         "- Preview hiển thị đúng vị trí\n- Lưu thành công",
         "Chứng chỉ cần đủ 4 trường"),
    ]),
    ("VII", "NGƯỜI HỌC NỘI BỘ — GÁN & ONBOARDING", [
        ("001", "Gán bắt buộc theo Phòng ban", "P0",
         "Tab 'Cấu hình người học'",
         "1. Ở khối 'Đối tượng bắt buộc phải học' tick pill 'Phòng ban'\n2. Chọn 2 phòng ban\n3. Lưu",
         "Bắt buộc: 2 phòng ban",
         "- Nhân viên thuộc 2 phòng ban đó thuộc diện bắt buộc học khóa",
         "Gán theo nhóm (không đích danh)"),
        ("002", "Gán khuyến khích theo Chức vụ", "P1",
         "Tab 'Cấu hình người học'",
         "1. Ở khối 'Đối tượng khuyến khích học' tick pill 'Chức vụ'\n2. Chọn chức vụ\n3. Lưu",
         "Khuyến khích: chức vụ",
         "- Nhân viên chức vụ đó được khuyến nghị học",
         "—"),
        ("003", "Bật Onboarding thiếu số ngày", "P1",
         "Tab người học",
         "1. Bật toggle 'Onboarding'\n2. Để trống 'Ngưỡng nhân viên mới (ngày)' hoặc 'Phải hoàn thành sau (ngày)'\n3. Lưu (kích hoạt)",
         "onboarding ON, ngày trống",
         "- Báo lỗi yêu cầu nhập số ngày nhân viên mới / phải hoàn thành",
         "—"),
        ("004", "Onboarding ngưỡng = 0", "P2",
         "Onboarding bật",
         "1. 'Ngưỡng nhân viên mới (ngày)' = 0\n2. 'Phải hoàn thành sau (ngày)' = 20\n3. Lưu",
         "new=0, finish=20",
         "- Lưu OK; mọi nhân viên coi là mới; hạn = ngày gán + 20 ngày",
         "0 = luôn coi là mới"),
    ]),
    ("VIIb", "KHÓA / XÓA", [
        ("001", "Khoá khóa học Hoạt động", "P0",
         "Khóa 'Hoạt động'",
         "1. Bấm nút Khoá\n2. Popup 'Xác nhận khoá': Bạn có chắc muốn khoá khoá học '<tên>'? → bấm 'Khoá'",
         "—",
         "- Toast 'Thao tác thành công', trạng thái → 'Khoá', không còn sửa",
         "—"),
        ("002", "Xóa khóa Nháp", "P1",
         "Khóa 'Nháp'",
         "1. Bấm Xoá → xác nhận",
         "—",
         "- Toast 'Xóa thành công', khóa biến mất (Nháp luôn xóa được)",
         "—"),
        ("003", "Xóa khóa Hoạt động đã được dùng", "P0",
         "Khóa 'Hoạt động' đã có yêu cầu/khoá con tham chiếu",
         "1. Bấm Xoá → xác nhận",
         "—",
         "- Bị chặn, không xóa được",
         "Khóa đã dùng thì không xóa"),
    ]),
    ("VIII", "LUỒNG XUYÊN SUỐT (E2E)", [
        ("001", "Tạo khóa thi đầy đủ", "P0",
         "Có bài học, đề thi, kỹ năng",
         "1. Tab Thông tin: Tên, Kỹ năng, Độ khó, thêm chương + 2 bài\n2. Tab Cấu hình đánh giá: Theo bài thi, chọn đề, Quy tắc Trung bình + ngưỡng\n3. Tab Cấu hình người học: gán 1 phòng ban bắt buộc\n4. Tab Chứng chỉ: bật + 4 trường\n5. Bấm 'Lưu'",
         "—",
         "- Toast 'Thêm khoá học thành công', khóa có mã SUB-xxxx",
         "—"),
    ]),
]

build(
    output_file=r"d:\CompanyProject\hrm-cursor\.plans\elearning-quan-ly\khoa-hoc\testcase.xlsx",
    sheet_name="KhoaHoc",
    feature_name="Khóa học",
    module_name="Khóa học",
    description_block=DESCRIPTION_BLOCK,
    sections=SECTIONS,
    role_tcs=ROLE_TCS,
)
