# -*- coding: utf-8 -*-
# Cấu hình tài liệu màn Danh mục tài khoản (Tài chính → Danh mục → Danh mục tài khoản).
# Nguồn: code gop_db 26/09/2026 — FE pages/finance/accounts/index.vue, add.vue, _id/index.vue, _id/edit.vue,
# components/AccountFormComponent.vue, static/Mau_import_tai_khoan.xlsx, utils/mixins/CatalogImportMixin.js,
# exportFieldsMixin.js; BE Modules/Finance: AccountController, AccountService, Http/Requests/Account/AccountRequest,
# Entities/Account/Account, Transformers/AccountResource; app/ExcelExport/ExportColumnRegistry ('accounts'),
# app/Services/CatalogHistoryService, middleware recordNotLocked / importRowLimit; quyền ở
# Modules/Timesheet/Database/Seeders/PermissionsTableSeeder.php (id 1107, 1108). Không ghi URL.
# Màn dạng TRANG RIÊNG: Thêm mới / Sửa / Chi tiết đều mở trang riêng, không phải cửa sổ.

DT = 'tài khoản'
Q_QL = 'Quản lý danh mục tài khoản'
Q_XEM = 'Xem danh mục tài khoản'
MSG_CON = 'Tài khoản đang có tài khoản con nên không được đổi Số tài khoản và Bậc. Hãy chuyển hoặc xóa các tài khoản con trước.'

CFG = {
    'slug': 'accounts',
    'ten': 'Danh mục tài khoản',
    'doi_tuong': DT,
    'file_hdsd': 'HDSD_Danh muc tai khoan.docx',
    'file_srs': 'SRS - Danh mục tài khoản.docx',
    'menu': [('Tài chính', 'menu_phanhe'), ('Danh mục', 'menu_nhom'), ('Danh mục tài khoản', 'menu_muc')],
    'form_type': 'page',

    'thuat_ngu': [
        ['Tài khoản', 'Tài khoản kế toán dùng khi hạch toán chứng từ, lên sổ sách, báo cáo tài chính và theo dõi công nợ.'],
        ['Số tài khoản', 'Mã định danh của tài khoản, duy nhất trong danh mục. Chỉ gồm chữ số, dài từ 3 đến 15 chữ số, ví dụ 131, 1311, 13111. Số 0 ở đầu được giữ nguyên (001 là số hợp lệ).'],
        ['Bậc tài khoản', 'Vị trí của tài khoản trong cây: Cấp 1 (gốc, không có tài khoản mẹ), Cấp 2 (mẹ là một tài khoản Cấp 1), Cấp 3 (mẹ là một tài khoản Cấp 2).'],
        ['Tài khoản mẹ', 'Tài khoản bậc liền trên mà tài khoản đang khai báo thuộc về. Gắn theo SỐ tài khoản; số tài khoản con phải BẮT ĐẦU BẰNG số tài khoản mẹ (mẹ 131 thì con là 1311, 1312…).'],
        ['Loại tài khoản', 'Nhóm phân loại lấy từ Danh mục loại tài khoản (tài khoản tài sản, nợ phải trả, vốn chủ sở hữu…).'],
        ['Theo dõi công nợ', 'Đánh dấu tài khoản dùng để theo dõi công nợ phải thu / phải trả theo từng khách hàng, nhà cung cấp.'],
        ['Trạng thái Hoạt động', 'Tài khoản dùng được, chọn được khi hạch toán chứng từ mới.'],
        ['Trạng thái Khóa', 'Tài khoản ngừng sử dụng: không còn chọn được khi hạch toán chứng từ mới, không sửa được; chứng từ cũ vẫn hiển thị đúng tài khoản này.'],
        ['Cổng cũ', 'Phần mềm quản trị cũ. Hai cổng dùng CHUNG một danh mục tài khoản.'],
    ],
    'phien_ban': [
        ['1.0', '14/08/2026', 'Đội phát triển phần mềm', 'Tạo mới cho màn Danh mục tài khoản.'],
        ['1.1', '26/09/2026', 'Đội phát triển phần mềm', 'Cập nhật theo phiên bản hiện tại: quy tắc Số tài khoản (3–15 chữ số, giữ số 0 đầu, tự gợi ý Bậc), cột Số tài khoản thay cho 3 cột Cấp 1/2/3, bấm Số tài khoản để xem trang Chi tiết, nút Khóa/Mở khóa và Lịch sử chuyển về cột Hành động, bộ lọc nhãn nổi, cửa sổ Chọn trường xuất file, cửa sổ Import có Validate/Bỏ dòng lỗi, In danh sách xem trước ngay trên màn, Tùy chỉnh cột; trình bày theo mẫu tài liệu danh mục chung.'],
    ],
    'muc_dich': [
        'Danh mục tài khoản dùng để khai báo và quản lý hệ thống tài khoản kế toán ba bậc của toàn hệ thống. Đây là danh mục nền của phân hệ Tài chính: mọi nghiệp vụ hạch toán, sổ sách, báo cáo tài chính và theo dõi công nợ đều lấy tài khoản từ đây.',
        'Tài khoản được tổ chức thành cây ba bậc gắn với nhau theo SỐ tài khoản: tài khoản Cấp 1 là gốc, Cấp 2 thuộc một tài khoản Cấp 1, Cấp 3 thuộc một tài khoản Cấp 2; số tài khoản con luôn bắt đầu bằng số tài khoản mẹ.',
        'Danh mục dùng CHUNG dữ liệu với màn tương ứng bên cổng cũ: sửa ở cổng nào thì cổng còn lại cũng thấy ngay.',
    ],
    'quyen': {
        'truoc': ['Màn hình dùng hai quyền riêng. Mục menu chỉ hiện khi tài khoản có ít nhất một trong hai quyền; không có quyền nào thì không vào được màn hình và máy chủ không trả dữ liệu.'],
        'rows': [
            [Q_XEM, 'Vào màn hình, xem danh sách, tìm kiếm, lọc, bấm Số tài khoản để xem chi tiết, xem Lịch sử, In danh sách, Xuất Excel, Tùy chỉnh cột.'],
            [Q_QL, 'Toàn bộ quyền Xem, cộng thêm: Tạo mới, Sửa, Import Excel; Khóa, Mở khóa và Xóa (chỉ với tài khoản do chính mình tạo — xem dưới).'],
        ],
        'sau': [
            'Ràng buộc riêng của màn này: Khóa, Mở khóa và Xóa chỉ dành cho CHÍNH NGƯỜI ĐÃ TẠO tài khoản đó. Người khác dù có quyền Quản lý cũng không thấy các nút này; ô Trạng thái trong trang Sửa cũng bị khóa. Riêng Sửa thì không bị ràng buộc: người có quyền Quản lý sửa được tài khoản do người khác tạo.',
            'Danh mục KHÔNG phân quyền theo công ty, phòng ban hay bộ phận. Thiếu quyền Quản lý thì các nút Tạo mới, Import Excel, Sửa, Xóa, Khóa/Mở khóa không hiển thị; gọi thẳng chức năng bỏ qua giao diện cũng bị máy chủ từ chối.',
        ],
    },

    'danh_sach': {
        'mo_ta_vao': 'Hệ thống hiển thị danh sách tài khoản hiện có, mặc định 10 dòng mỗi trang, xếp theo cây: tài khoản con nằm ngay dưới tài khoản mẹ của nó.',
        'bo_cuc': [
            'Khu vực tìm kiếm và lọc — ô tìm kiếm nhanh, nút Tìm kiếm, Làm mới và nút Tìm kiếm nâng cao (mở thêm các ô Bậc tài khoản, Loại tài khoản, Theo dõi công nợ, Trạng thái, Người tạo, Người cập nhật).',
            'Thanh công cụ — nút Tạo mới, In danh sách, Xuất Excel, Import Excel và biểu tượng Cấu hình cột hiển thị.',
            'Bảng danh sách — các cột thông tin, cột Hành động ở cuối, và phân trang bên dưới.',
        ],
        'cot': [
            ['STT', 'Số thứ tự, chạy liên tục qua các trang. Luôn hiển thị.'],
            ['Số tài khoản', 'Luôn hiển thị, sắp xếp được. Bấm vào số để mở trang Chi tiết tài khoản.'],
            ['Tên tài khoản', 'Tên đầy đủ, nội dung dài được xuống dòng trong ô, sắp xếp được.'],
            ['Bậc', 'Bậc 1, 2 hoặc 3. Mặc định ẩn.'],
            ['Tài khoản mẹ', 'Số tài khoản mẹ; tài khoản Cấp 1 để trống. Mặc định ẩn.'],
            ['Loại tài khoản', 'Tên loại lấy từ Danh mục loại tài khoản; chưa gán loại thì để trống. Mặc định ẩn.'],
            ['Theo dõi công nợ', 'Dấu tích xanh nếu tài khoản có bật theo dõi công nợ (rê chuột hiện “Có theo dõi công nợ”); không bật thì để trống. Mặc định ẩn.'],
            ['Người cập nhật', 'Người sửa bản ghi gần nhất. Mặc định ẩn.'],
            ['Ngày cập nhật', 'Thời điểm sửa gần nhất, dạng dd/mm/yyyy hh:mm. Mặc định ẩn, sắp xếp được.'],
            ['Người tạo', 'Người đã thêm bản ghi.'],
            ['Ngày tạo', 'Thời điểm thêm, dạng dd/mm/yyyy hh:mm, sắp xếp được.'],
            ['Trạng thái', 'Nhãn Hoạt động hoặc Khóa.'],
            ['Hành động', 'Các nút thao tác của dòng (xem mục 4).'],
        ],
        'hanh_dong': {
            'intro': 'Trên mỗi dòng, cột Hành động có các nút:',
            'bullets': [
                'Biểu tượng bút chì {icon:btn_sua} — mở trang Sửa tài khoản. Chỉ hiện với người có quyền Quản lý và khi tài khoản đang Hoạt động.',
                'Biểu tượng thùng rác {icon:btn_xoa} — xóa tài khoản. Chỉ hiện với người có quyền Quản lý khi thỏa ĐỦ ba điều kiện: chính mình là người tạo, tài khoản KHÔNG có tài khoản con, và CHƯA từng được hạch toán ở chứng từ nào.',
                'Khóa — chỉ hiện với người có quyền Quản lý, khi tài khoản đang Hoạt động và chính mình là người tạo. Mở khóa — hiện với tài khoản đang Khóa do chính mình tạo.',
                'Lịch sử — mở cửa sổ Lịch sử thay đổi. Mọi người vào được màn hình đều thấy.',
                'Có từ 4 nút trở lên thì 2 nút đầu hiện thẳng, các nút còn lại nằm trong nút ba chấm {icon:btn_bacham} “Hành động khác”.',
            ],
            'anh': 'Các nút ở cột Hành động của một tài khoản',
            'luu_y': ['Lưu ý quan trọng: nút không đủ điều kiện sẽ bị ẨN hẳn chứ không làm mờ. Người có quyền Quản lý nhưng KHÔNG phải người tạo tài khoản chỉ thấy Sửa và Lịch sử; người chỉ có quyền Xem chỉ thấy nút Lịch sử.',
                      'Tài khoản ĐÃ KHÓA thì nút Sửa biến mất; muốn sửa phải Mở khóa trước.'],
        },
        'phan_trang': [
            'Khi chưa sắp xếp, danh sách xếp theo cây tài khoản: 131 rồi 1311 rồi 13111, sau đó mới tới 1312…',
            'Cuối bảng có dòng “Hiển thị a–b / N”: N là tổng số tài khoản khớp bộ lọc đang áp dụng, không phải tổng toàn danh mục.',
            'Ô Số dòng/trang có các mức 5, 10, 20, 50, 100 (mặc định 10). Đổi số dòng thì hệ thống tự quay về trang 1.',
            'Các cột sắp xếp được: Số tài khoản, Tên tài khoản, Ngày tạo, Ngày cập nhật. Bấm tiêu đề cột để sắp xếp, bấm lần hai để đảo chiều. Thứ tự sắp xếp được giữ nguyên khi chuyển trang.',
        ],
    },

    'loc': {
        'buoc2': 'Bước 2: Nhập chữ vào ô tìm kiếm nhanh; bấm Tìm kiếm nâng cao để chọn thêm Bậc tài khoản, Loại tài khoản, Theo dõi công nợ, Trạng thái, Người tạo, Người cập nhật.',
        'rows': [
            ['Ô tìm kiếm nhanh', 'Placeholder “Tìm theo số hoặc tên tài khoản...”. Với Số tài khoản, khớp theo PHẦN ĐẦU của số (gõ 131 ra 131, 1311, 13111…); với Tên tài khoản, gõ một phần bất kỳ của tên cũng ra (gõ “khách hàng” ra “Phải thu của khách hàng ngắn hạn”), không phân biệt hoa thường. Nhấn Enter hoặc bấm Tìm kiếm để lọc.'],
            ['Bậc tài khoản', 'Cấp 1, Cấp 2 hoặc Cấp 3. Lọc ngay khi chọn.'],
            ['Loại tài khoản', 'Chọn một loại tài khoản. Lọc ngay khi chọn.'],
            ['Theo dõi công nợ', 'Có hoặc Không. Lọc ngay khi chọn.'],
            ['Trạng thái', 'Hoạt động hoặc Khóa. Bỏ trống thì hiện cả hai. Lọc ngay khi chọn.'],
            ['Người tạo', 'Chọn một nhân viên để chỉ xem tài khoản do người đó tạo. Lọc ngay khi chọn.'],
            ['Người cập nhật', 'Chọn một nhân viên để chỉ xem tài khoản do người đó sửa gần nhất. Lọc ngay khi chọn.'],
        ],
        'ap_dung': [
            'Các tiêu chí kết hợp với nhau theo kiểu VÀ — chỉ bản ghi thỏa đồng thời tất cả các tiêu chí mới hiện ra. Mỗi lần đổi tiêu chí, danh sách quay về trang 1.',
            'Bấm {icon:btn_lammoi} để xóa toàn bộ tiêu chí; danh sách nạp lại đầy đủ ngay lập tức.',
            'Hệ thống ghi nhớ bộ lọc trong 10 phút: rời màn rồi quay lại trong khoảng đó thì điều kiện lọc cũ vẫn còn.',
        ],
        'anh_ket_qua': 'Kết quả tìm nhanh theo tên tài khoản (gõ “phải thu”)',
    },

    'form': {
        'kieu': 'trang',
        'buoc_tao': [
            'Bước 1: Truy cập vào màn hình Danh mục tài khoản.',
            'Bước 2: Bấm {icon:btn_taomoi}. Hệ thống mở TRANG RIÊNG “Thêm tài khoản” (không phải cửa sổ nhỏ như các danh mục khác).',
            'Bước 3: Nhập/ chọn thông tin trong khối “Thông tin chung”: Số tài khoản, Tên tài khoản, Loại tài khoản, Theo dõi công nợ, Tài khoản mẹ, Bậc tài khoản, Trạng thái.',
            'Bước 4: Bấm {icon:btn_luu} để lưu và quay về danh sách, hoặc {icon:btn_luutieptuc} để lưu rồi nhập tiếp tài khoản khác.',
        ],
        'anh_tao': 'Trang Thêm tài khoản',
        'truong': [
            ['Số tài khoản', 'Ô nhập giá trị', 'Có', 'Trống', 'Chỉ nhận chữ số, từ 3 đến 15 chữ số. Ô không nhận chữ cái, dấu chấm, khoảng trắng (gõ không lên; dán vào thì ký tự không phải số bị bỏ, quá 15 chữ số bị cắt). Nhập chưa đủ 3 số báo ngay “Chỉ được nhập chữ số, từ 3 đến 15 chữ số”. Số 0 ở đầu được giữ nguyên. Duy nhất; trùng báo “Số tài khoản đã tồn tại”. Khi Thêm mới mà chưa chọn Bậc, hệ thống tự gợi ý Bậc theo độ dài số: 3 chữ số → Cấp 1, 4 chữ số → Cấp 2, từ 5 chữ số → Cấp 3.'],
            ['Tên tài khoản', 'Ô nhập giá trị', 'Có', 'Trống', 'Tối đa 255 ký tự. Được phép trùng tên tài khoản khác. Bỏ trống báo “Bắt buộc phải nhập”.'],
            ['Loại tài khoản', 'Ô chọn giá trị', 'Có', 'Trống', 'Lấy từ Danh mục loại tài khoản, hiển thị dạng “Mã - Tên”, chỉ liệt kê loại đang Hoạt động. Bỏ trống báo “Bắt buộc phải chọn”.'],
            ['Theo dõi công nợ', 'Ô đánh dấu', 'Không', 'Không đánh dấu', 'Bật khi tài khoản dùng để theo dõi công nợ theo từng khách hàng, nhà cung cấp.'],
            ['Tài khoản mẹ', 'Ô chọn giá trị', 'Bắt buộc với Cấp 2 và Cấp 3', 'Trống — ô bị khóa cho tới khi chọn Bậc', 'Chỉ liệt kê tài khoản đang Hoạt động ở bậc liền trên bậc đang chọn; đã nhập Số tài khoản thì chỉ còn các tài khoản mẹ có số là phần đầu của số đang nhập. Cấp 1 thì ô khóa với chữ “Tài khoản cấp 1 không có tài khoản mẹ”.'],
            ['Bậc tài khoản', 'Ô chọn giá trị', 'Có', 'Trống (tự gợi ý theo Số tài khoản)', 'Cấp 1 / Cấp 2 / Cấp 3. Đổi Bậc thì ô Tài khoản mẹ bị xóa trắng để chọn lại. Bỏ trống báo “Bắt buộc phải chọn”.'],
            ['Trạng thái', 'Ô chọn giá trị', 'Không', 'Hoạt động', 'Hoạt động / Khóa.'],
        ],
        'sau_truong': ['Các trường bắt buộc có dấu sao đỏ bên cạnh nhãn. Ô Tài khoản mẹ chỉ có dấu sao khi Bậc là Cấp 2 hoặc Cấp 3.'],
        'nut': [
            ['Lưu', 'Ghi bản ghi, báo “Thêm mới thành công” (hoặc “Cập nhật thành công” khi sửa) rồi quay về danh sách.'],
            ['Lưu và tiếp tục', 'Ghi bản ghi nhưng Ở LẠI trang, xóa trắng các ô và GIỮ NGUYÊN Bậc + Tài khoản mẹ để nhập nhanh các tài khoản cùng nhánh. Chỉ có khi Thêm mới.'],
            ['Quay lại', 'Về danh sách, không ghi gì. Nếu đã nhập dở, hệ thống hỏi “Bạn có thông tin chưa lưu. Có chắc chắn muốn thoát?”.'],
        ],
        'loi': [
            ['Bắt buộc phải nhập', 'Chưa nhập Số tài khoản hoặc Tên tài khoản.'],
            ['Bắt buộc phải chọn', 'Chưa chọn Bậc tài khoản hoặc Loại tài khoản.'],
            ['Chỉ được nhập chữ số, từ 3 đến 15 chữ số', 'Số tài khoản ngắn hơn 3 chữ số.'],
            ['Số tài khoản đã tồn tại', 'Đã có tài khoản khác cùng số.'],
            ['Bắt buộc phải chọn tài khoản mẹ với bậc 2 và 3', 'Bậc Cấp 2 / Cấp 3 mà bỏ trống Tài khoản mẹ.'],
            ['Tài khoản mẹ phải là tài khoản bậc N (tài khoản X đang là bậc M)', 'Tài khoản mẹ không đúng bậc liền trên.'],
            ['Số tài khoản con phải bắt đầu bằng số tài khoản mẹ: mẹ là X thì con phải là X1, X2...', 'Số tài khoản không nối tiếp số tài khoản mẹ. Sửa lại số hoặc chọn mẹ khác.'],
            ['Vui lòng nhập tối đa 255 ký tự.', 'Tên tài khoản quá dài.'],
            ['Bạn chưa nhập đầy đủ thông tin', 'Thông báo chung khi còn ô bị lỗi; xem các ô báo đỏ trên trang.'],
        ],
    },

    'sua': {
        'buoc': [
            'Bước 1: Truy cập vào màn hình Danh mục tài khoản.',
            'Bước 2: Bấm nút {icon:btn_sua} ở cột Hành động của tài khoản cần sửa (hoặc bấm Sửa ở cuối trang Chi tiết).',
            'Bước 3: Hệ thống mở trang “Sửa tài khoản” với dữ liệu hiện tại.',
            'Bước 4: Cập nhật các thông tin cần sửa (quy tắc nhập như Thêm mới).',
            'Bước 5: Bấm {icon:btn_luu} để xác nhận thay đổi hoặc Quay lại nếu muốn hủy.',
        ],
        'anh': 'Trang Sửa tài khoản',
        'ghi_chu': [
            'Trang Sửa không có nút “Lưu và tiếp tục”. Giữ nguyên Số tài khoản của chính nó thì không bị báo trùng.',
            'Tài khoản ĐANG CÓ tài khoản con: ô Số tài khoản và Bậc tài khoản bị khóa, bên dưới ghi “%s” Tên, Loại tài khoản, Theo dõi công nợ vẫn sửa được bình thường.' % MSG_CON,
            'Ô Trạng thái chỉ đổi sang Khóa được khi chính mình là người tạo tài khoản; người khác thấy ô này bị khóa (máy chủ cũng chặn với thông báo “Bạn không có quyền khóa tài khoản này”).',
            'Bản ghi cũ chưa gán Loại tài khoản: đầu trang hiện nhắc “Bản ghi này chưa được gán Loại tài khoản. Hãy chọn loại trước khi lưu.”',
            'Tài khoản đang Khóa không có nút Sửa; vào thẳng trang Sửa sẽ bị đưa về trang Chi tiết kèm thông báo “Tài khoản đang bị khoá, vui lòng mở khoá trước khi sửa.”. Nếu vừa bị người khác khóa, bấm Lưu nhận thông báo “Tài khoản đang bị khoá, vui lòng mở khoá trước khi cập nhật.”',
        ],
    },
    'xoa': {
        'buoc': [
            'Bước 1: Ở cột Hành động (hoặc cuối trang Chi tiết), Người dùng bấm {icon:btn_xoa}.',
            'Bước 2: Hệ thống hiện hộp “Xác nhận xóa” — “Bạn có chắc muốn xóa tài khoản \'<số> - <tên>\'?”. Bấm {icon:btn_confirm_xoa} để xác nhận: hệ thống báo “Xóa thành công”, bản ghi biến mất khỏi danh sách.',
            'Bấm {icon:btn_huy} nếu bấm nhầm. Không có gì thay đổi.',
        ],
        'anh': 'Hộp xác nhận xóa tài khoản',
        'ghi_chu': [
            'Nút Xóa chỉ hiện khi thỏa ĐỦ ba điều kiện: chính mình là người tạo, KHÔNG có tài khoản con, CHƯA được hạch toán ở chứng từ nào. Muốn xóa cả một nhánh phải xóa từ dưới lên: xóa hết tài khoản con trước thì nút Xóa của tài khoản mẹ mới hiện.',
            'Nếu điều kiện vừa thay đổi ngay trước khi xác nhận (vd có người hạch toán vào tài khoản), máy chủ chặn với thông báo “Không xóa được: tài khoản có tài khoản con, đã phát sinh dữ liệu, hoặc bạn không phải người tạo”. Xóa tài khoản xóa luôn lịch sử thay đổi của nó; thao tác không lùi lại được.',
        ],
    },
    'khoa': {
        'y_nghia': [
            'Bản ghi VẪN nằm trong danh sách, cột Trạng thái hiện chữ Khóa.',
            'Vẫn xem được chi tiết và lịch sử thay đổi của bản ghi.',
            'Tài khoản đã khóa không còn chọn được khi hạch toán chứng từ mới; chứng từ đã hạch toán vẫn hiện đúng tài khoản này.',
            'Nút Sửa của dòng đó biến mất.',
            'Khóa tài khoản mẹ KHÔNG tự khóa các tài khoản con; muốn khóa cả nhánh phải khóa từng tài khoản.',
            'Chỉ người đã tạo tài khoản mới Khóa / Mở khóa được.',
        ],
        'buoc_khoa': [
            'Bước 1: Ở cột Hành động, Người dùng chọn Khóa (trong nút ba chấm nếu dòng có nhiều nút), hoặc bấm Khóa ở cuối trang Chi tiết.',
            'Bước 2: Hệ thống hiện hộp “Xác nhận khóa” — “Bạn có chắc muốn khóa tài khoản \'<số> - <tên>\'?”. Bấm Khóa để xác nhận; hệ thống báo “Khóa thành công”, cột Trạng thái đổi thành Khóa. Bấm Hủy nếu bấm nhầm.',
        ],
        'buoc_mo': [
            'Bước 1: Ở cột Hành động của tài khoản đang Khóa, Người dùng chọn Mở khóa.',
            'Bước 2: Bấm Mở khóa trong hộp “Xác nhận mở khóa”. Hệ thống báo “Mở khóa thành công”, cột Trạng thái đổi thành Hoạt động. Bấm Hủy nếu bấm nhầm.',
        ],
        'ghi_chu': ['Có thể khóa ngay trong trang Sửa bằng cách chọn Trạng thái = Khóa rồi Lưu (chỉ khi chính mình là người tạo). Gọi thẳng chức năng khóa / mở khóa tài khoản của người khác, máy chủ báo “Bạn không có quyền khóa tài khoản này” / “Bạn không có quyền mở khóa tài khoản này”.'],
    },
    'lich_su': {
        'buoc': [
            'Xem từ màn danh sách: ở cột Hành động, Người dùng chọn Lịch sử.',
            'Xem từ trang chi tiết: bấm vào Số tài khoản để mở trang Chi tiết, khối Lịch sử nằm cuối trang (mặc định thu gọn, bấm để mở).',
        ],
        'ghi_chu': ['Với danh mục này, lịch sử ghi các lần Thay đổi thông tin (Số tài khoản, Tên, Tài khoản mẹ, Bậc, Loại tài khoản, Theo dõi công nợ, Trạng thái); Khóa / Mở khóa hiện dưới dạng Thay đổi thông tin ở trường Trạng thái (Hoạt động → Khóa). Thao tác Tạo mới và Import chưa sinh mốc lịch sử. Cửa sổ có bộ lọc riêng (loại hành động, người thực hiện, khoảng thời gian).'],
    },
    'chi_tiet': {
        'buoc': ['Bước 1: Truy cập vào màn hình Danh mục tài khoản.',
                 'Bước 2: Bấm vào số ở cột Số tài khoản. Hệ thống mở trang “Chi tiết tài khoản: <số tài khoản>”.'],
        'anh': 'Trang Chi tiết tài khoản ở chế độ chỉ đọc',
        'ghi_chu': ['Trang hiển thị đủ các ô như trang Thêm mới ở chế độ chỉ đọc, kèm khối Lịch sử ở cuối. Cuối trang có các nút giống cột Hành động của dòng đó (cùng điều kiện hiện): Sửa, Xóa, Khóa / Mở khóa, và Quay lại. Người chỉ có quyền Xem chỉ thấy nút Quay lại.'],
    },
    'phan_rieng': [
        {'tieu_de': 'IN DANH SÁCH', 'noi_dung': [
            ('s', 'Bước 1: Lọc danh sách theo đúng dữ liệu cần in (xem PHẦN 2).'),
            ('s', 'Bước 2: Bấm nút In danh sách. Hệ thống mở cửa sổ “Xem trước danh sách tài khoản” ngay trên màn hình.'),
            ('s', 'Bước 3: Kiểm tra bản xem trước rồi bấm In để mở hộp thoại in của trình duyệt.'),
            ('p', 'Bản in dùng chung biểu mẫu “Danh sách tài khoản” với cổng cũ, có letterhead của công ty ở đầu trang, lấy đúng tập dữ liệu đang lọc (mọi dòng, không chỉ trang đang xem). Tài khoản Cấp 1 in đậm. Cột in ra chạy theo các cột đang hiển thị trên bảng; các cột STT, Số tài khoản, Bậc, Tài khoản mẹ, Người tạo, Người cập nhật luôn có trên bản in. Người chỉ có quyền Xem vẫn in được.'),
        ]},
    ],
    'xuat': {
        'buoc': [
            'Bước 1: Lọc danh sách theo đúng dữ liệu cần lấy (xem PHẦN 2). File xuất ra chạy theo đúng bộ lọc và thứ tự sắp xếp đang áp dụng.',
            'Bước 2: Bấm nút {icon:btn_xuatexcel}. Hệ thống mở cửa sổ “Chọn trường xuất file”.',
            'Bước 3: Tích chọn, kéo biểu tượng ☰ để đổi vị trí các trường cần xuất. Mặc định hệ thống tích sẵn đúng những cột đang hiển thị trên bảng.',
            'Bước 4: Bấm {icon:btn_xuatfile}. Hệ thống tải về file danh_muc_tai_khoan.xlsx và báo “Xuất Excel thành công”.',
        ],
        'truong': 'Chọn nhiều trường: Số tài khoản, Tên tài khoản, Tài khoản mẹ, Bậc, Loại tài khoản, Trạng thái, Người tạo, Ngày tạo.',
        'ghi_chu': ['Lưu ý: file xuất chứa TOÀN BỘ kết quả của bộ lọc, không chỉ các dòng của trang đang xem; có cột STT ở đầu và tiêu đề “Danh mục tài khoản”. Cột Theo dõi công nợ, Người cập nhật, Ngày cập nhật không có trong file xuất. Người chỉ có quyền Xem vẫn xuất được Excel.'],
    },
    'import': {
        'tieu_de': 'Import tài khoản',
        'file': 'Mau_import_tai_khoan.xlsx',
        'cot_text': 'Số tài khoản (bắt buộc), Tên tài khoản (bắt buộc), Bậc (bắt buộc, 1 / 2 / 3), Tài khoản mẹ (bắt buộc với bậc 2 và 3), Loại tài khoản (bắt buộc, ghi Mã hoặc Tên loại, vd TKTS hoặc Tài khoản tài sản), Theo dõi công nợ (Có / Không; để trống = Không). Hàng 1 là tiêu đề, dữ liệu nhập từ hàng 2 (file mẫu có sẵn 3 dòng ví dụ 8888, 88881, 888811 — xóa đi trước khi nhập)',
        'toast': 'Import thành công N tài khoản.',
        'loi': [
            ['Số tài khoản không được để trống', 'Dòng đó bỏ trống cột Số tài khoản.'],
            ['Chỉ được nhập chữ số, từ 3 đến 15 chữ số', 'Số tài khoản có chữ, dấu hoặc không đủ / quá độ dài cho phép.'],
            ['Số tài khoản bị trùng trong file import (dòng N)', 'Trong chính file có hai dòng cùng số tài khoản. Xoá bớt một dòng.'],
            ['Số tài khoản đã tồn tại trong hệ thống', 'Danh mục đã có tài khoản cùng số.'],
            ['Tên tài khoản không được để trống', 'Dòng đó bỏ trống cột Tên tài khoản.'],
            ['Tên tài khoản tối đa 255 ký tự', 'Tên quá dài, rút gọn lại.'],
            ['Bậc tài khoản không được để trống', 'Dòng đó bỏ trống cột Bậc.'],
            ['Bậc tài khoản chỉ nhận 1, 2 hoặc 3', 'Cột Bậc ghi giá trị khác.'],
            ['Tài khoản bậc 2 và 3 bắt buộc có tài khoản mẹ', 'Bậc 2 / 3 mà bỏ trống cột Tài khoản mẹ.'],
            ['Không tìm thấy tài khoản mẹ', 'Số tài khoản mẹ không có trong danh mục và cũng không có trong chính file.'],
            ['Tài khoản mẹ phải là tài khoản bậc N (tài khoản X đang là bậc M)', 'Tài khoản mẹ không đúng bậc liền trên.'],
            ['Số tài khoản con phải bắt đầu bằng số tài khoản mẹ: mẹ là X thì con phải là X1, X2...', 'Số tài khoản không nối tiếp số tài khoản mẹ.'],
            ['Loại tài khoản không được để trống', 'Dòng đó bỏ trống cột Loại tài khoản.'],
            ['Không tìm thấy loại tài khoản', 'Giá trị cột Loại tài khoản không khớp Mã hay Tên loại nào trong Danh mục loại tài khoản.'],
            ["Theo dõi công nợ chỉ nhận 'Có' hoặc 'Không' (để trống = Không)", 'Cột Theo dõi công nợ ghi giá trị khác.'],
        ],
        'ghi_chu': [
            'Lưu ý: tài khoản mẹ được phép nằm ngay trong cùng file — hệ thống tự tạo bậc 1 trước, rồi bậc 2, rồi bậc 3, nên nhập cả một nhánh trong một file vẫn được. Tài khoản nhập vào luôn ở trạng thái Hoạt động; Người tạo là chính người thực hiện nhập.',
            'Mỗi lần nhập tối đa 500 dòng; file dài hơn hệ thống báo “File có X dòng dữ liệu, vượt quá giới hạn 500 dòng mỗi lần import. Vui lòng tách file và import nhiều lần.” File không có dòng dữ liệu báo “Không có dòng dữ liệu hợp lệ.”',
        ],
    },
    'tuy_chinh_cot': {'cot_khoa': 'Ba cột STT, Số tài khoản và Hành động'},

    'shots': {'list': '01_list.png', 'rowmenu': '03_rowmenu.png', 'filter': 'filter.png', 'filter_result': '04_filter_result.png',
              'create': '10_create.png', 'create_error': '11_create_error.png', 'code_error': '11b_code_error.png', 'edit': '12_edit.png',
              'delete': '13_delete.png', 'lock': '14_lock.png', 'unlock': '15_unlock.png', 'history': '16_history.png',
              'detail': '17_detail.png', 'export': '20_export.png', 'import_open': '21_import_open.png',
              'import_loaded': '22_import_loaded.png', 'import_validated': '23_import_validated.png', 'colcfg': '25_colcfg.png',
              'print': '26_print.png'},

    'capture': {'route': '/finance/accounts',
                'menu': {'phanhe': 'TÀI CHÍNH', 'nhom': 'Danh mục', 'muc': 'Danh mục tài khoản'},
                'search': 'Tìm theo số hoặc tên', 'searchText': 'phải thu', 'detailCol': 1,
                'lockName': 'DOC-Tài khoản thử khóa', 'codeInput': 'VD: 1311', 'create': True, 'lock': True,
                'manual': 'Form là TRANG RIÊNG (add / _id/edit / _id), không phải popup: 10_create, 11_create_error, 11b_code_error, 12_edit, 17_detail chụp trên trang. 11b_code_error: gõ "13" vào ô Số tài khoản (ô chặn chữ nên không gõ chữ được). Khóa/Mở khóa/Xóa chỉ hiện với tài khoản do CHÍNH người chụp tạo → tạo trước 1 tài khoản thử (vd 997 "DOC-Tài khoản thử") rồi dùng làm lockName. 26_print.png: bấm In danh sách, chụp cửa sổ Xem trước.'},

    'import_test': {
        'cols': ['Số tài khoản', 'Tên tài khoản', 'Bậc', 'Tài khoản mẹ', 'Loại tài khoản', 'Theo dõi công nợ'],
        'rows': [
            ['976', 'DOC-Tài khoản cấp 1', '1', '', 'TKTS', ''],
            ['9761', 'DOC-Tài khoản cấp 2', '2', '976', 'Tài khoản tài sản', 'Có'],
            ['97611', 'DOC-Tài khoản cấp 3', '3', '9761', 'TKTS', 'Không'],
            ['', 'DOC-Thiếu số tài khoản', '1', '', 'TKTS', ''],
            ['976', 'DOC-Trùng số trong file', '1', '', 'TKTS', ''],
            ['131', 'DOC-Trùng số hệ thống', '1', '', 'TKTS', ''],
            ['8888', 'DOC-Con không nối tiếp mẹ', '2', '976', 'TKTS', ''],
            ['9762', 'DOC-Loại không tồn tại', '2', '976', 'LOAI-KHONG-CO', 'Chưa rõ'],
        ],
    },

    'uml': {
        'mains': [('FR-01', 'Xem danh sách tài khoản', 'view'), ('FR-03', 'Thêm mới tài khoản', 'crud'),
                  ('FR-04', 'Chỉnh sửa tài khoản', 'crud'), ('FR-05', 'Xóa tài khoản', 'action'),
                  ('FR-06', 'Khóa / Mở khóa tài khoản', 'action'), ('FR-08', 'Import file tài khoản', 'io'),
                  ('FR-09', 'Xuất danh sách tài khoản ra Excel', 'io'), ('FR-12', 'In danh sách tài khoản', 'io')],
        'subs': [('FR-02', 'Tìm kiếm và lọc tài khoản', 'view'), ('FR-10', 'Xem chi tiết tài khoản', 'view'),
                 ('FR-11', 'Tùy chỉnh cột hiển thị', 'view'), ('FR-07', 'Xem lịch sử thay đổi', 'view')],
        'rieng': [('FR-10', 'Xem chi tiết tài khoản', 'view'), ('FR-12', 'In danh sách tài khoản', 'io')],
    },

    'srs': {
        'muc_dich': ['Là căn cứ nghiệm thu chức năng.',
                     'Làm rõ quy tắc Số tài khoản, ràng buộc cây tài khoản ba bậc, và ràng buộc chỉ người tạo mới Khóa / Mở khóa / Xóa được tài khoản.'],
        'quyen_truoc': ['Màn hình dùng hai quyền riêng thuộc nhóm “Danh mục tài chính”. Không có quyền nào thì không vào được màn hình. Máy chủ kiểm tra quyền ở từng chức năng, không chỉ dựa vào việc ẩn nút.'],
        'quyen_rows': [[Q_XEM, 'Xem danh sách, tìm kiếm/lọc, xem chi tiết, xem lịch sử, in danh sách, xuất Excel, tùy chỉnh cột.'],
                       [Q_QL, 'Toàn bộ quyền Xem + Thêm mới, Sửa, Import Excel; Khóa/Mở khóa và Xóa chỉ với tài khoản do chính mình tạo.']],
        'ma_tran': [['Chức năng', Q_QL, Q_XEM]] + [[f, q, x] for f, q, x in [
            ('FR-01 Xem danh sách tài khoản', 'Có', 'Có'), ('FR-02 Tìm kiếm và lọc', 'Có', 'Có'),
            ('FR-03 Thêm mới tài khoản', 'Có', 'Không'), ('FR-04 Chỉnh sửa tài khoản', 'Có', 'Không'),
            ('FR-05 Xóa tài khoản', 'Có (chỉ người tạo)', 'Không'), ('FR-06 Khóa / Mở khóa tài khoản', 'Có (chỉ người tạo)', 'Không'),
            ('FR-07 Xem lịch sử thay đổi', 'Có', 'Có'), ('FR-08 Import file tài khoản', 'Có', 'Không'),
            ('FR-09 Xuất danh sách ra Excel', 'Có', 'Có'), ('FR-10 Xem chi tiết tài khoản', 'Có', 'Có'),
            ('FR-11 Tùy chỉnh cột hiển thị', 'Có', 'Có'), ('FR-12 In danh sách tài khoản', 'Có', 'Có')]],
        'ma_tran_widths': [2.4, 1.6, 1.6],
        'quyen_sau': ['Danh mục KHÔNG phân quyền theo công ty / phòng ban / bộ phận. Khóa, Mở khóa, Xóa còn yêu cầu người thực hiện là người đã tạo tài khoản.'],
        'fr': [
            {'ten': 'Xem danh sách tài khoản',
             'qtc': 'Màn Danh sách, Sắp xếp dữ liệu bảng, Phân trang và Cấu hình cột. Chỉ bổ sung các quy tắc riêng của Danh mục tài khoản tại phần mô tả chi tiết.',
             'gioi_thieu': [['Tên chức năng', 'Xem danh sách tài khoản'],
                            ['Mô tả', 'Hiển thị toàn bộ tài khoản trong danh mục theo thứ tự cây, có phân trang và sắp xếp.'],
                            ['Tác nhân', 'Người có quyền “%s” hoặc “%s”' % (Q_QL, Q_XEM)],
                            ['Điều kiện ban đầu', 'Người dùng đã đăng nhập và có một trong hai quyền trên.'],
                            ['Dòng sự kiện chính', '1. Người dùng vào menu Tài chính → Danh mục → Danh mục tài khoản.\n2. Hệ thống nạp trang đầu tiên (10 dòng), xếp theo cây: tài khoản con ngay dưới tài khoản mẹ.\n3. Bảng hiển thị dữ liệu kèm tổng số bản ghi.'],
                            ['Dòng sự kiện phụ', '• Không có bản ghi khớp → bảng hiện “Không có dữ liệu phù hợp bộ lọc.”\n• Không có quyền → không vào được màn hình.']],
             'anh': [('list', 'Màn Danh mục tài khoản lúc mới truy cập')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Mô tả'],
                    ['1', 'STT', 'Table/Grid', 'Read-only', 'Số thứ tự, chạy liên tục qua các trang. Luôn hiển thị.'],
                    ['2', 'Số tài khoản', 'Table/Grid', 'Read-only', 'Luôn hiển thị, sắp xếp được. Bấm vào số mở trang Chi tiết (xem 2.10).'],
                    ['3', 'Tên tài khoản', 'Table/Grid', 'Read-only', 'Xuống dòng khi dài, sắp xếp được.'],
                    ['4', 'Bậc', 'Table/Grid', 'Read-only', '1 / 2 / 3. Mặc định ẩn.'],
                    ['5', 'Tài khoản mẹ', 'Table/Grid', 'Read-only', 'Số tài khoản mẹ. Mặc định ẩn.'],
                    ['6', 'Loại tài khoản', 'Table/Grid', 'Read-only', 'Tên loại từ Danh mục loại tài khoản. Mặc định ẩn.'],
                    ['7', 'Theo dõi công nợ', 'Icon', 'Read-only', 'Dấu tích nếu có bật. Mặc định ẩn.'],
                    ['8', 'Người cập nhật', 'Table/Grid', 'Read-only', 'Mặc định ẩn.'],
                    ['9', 'Ngày cập nhật', 'Table/Grid', 'Read-only', 'dd/mm/yyyy hh:mm. Mặc định ẩn, sắp xếp được.'],
                    ['10', 'Người tạo', 'Table/Grid', 'Read-only', 'Người đã thêm bản ghi.'],
                    ['11', 'Ngày tạo', 'Table/Grid', 'Read-only', 'dd/mm/yyyy hh:mm, sắp xếp được.'],
                    ['12', 'Trạng thái', 'Badge', 'Read-only', 'Hoạt động hoặc Khóa.'],
                    ['13', 'Hành động', 'Table/Grid', 'Read-only', 'Sửa (quyền Quản lý, đang Hoạt động), Xóa (quyền Quản lý, người tạo, không có con, chưa hạch toán), Khóa / Mở khóa (quyền Quản lý, người tạo), Lịch sử (mọi người).'],
                    ['14', 'Nút Tạo mới', 'Button', 'Enable', 'Chỉ hiện với quyền Quản lý. Mở trang Thêm tài khoản.'],
                    ['15', 'Nút In danh sách', 'Button', 'Enable', 'Mở cửa sổ Xem trước bản in (xem 2.12).'],
                    ['16', 'Nút Xuất Excel', 'Button', 'Enable', 'Mở cửa sổ Chọn trường xuất file (xem 2.9).'],
                    ['17', 'Nút Import Excel', 'Button', 'Enable', 'Chỉ hiện với quyền Quản lý (xem 2.8).'],
                    ['18', 'Biểu tượng Cấu hình cột hiển thị', 'Icon Button', 'Enable', 'Mở cửa sổ Tuỳ chỉnh cột (xem 2.11).'],
                    ['19', 'Phân trang', 'Pagination', 'Enable', 'Số dòng/trang 5 / 10 / 20 / 50 / 100, mặc định 10.']],
             'ui_widths': [0.6, 1.4, 0.9, 0.8, 3],
             'events': [['Mở màn hình', 'System', 'After:\n– Nạp trang đầu theo thứ tự cây, hiển thị tổng số bản ghi.'],
                        ['Bấm tiêu đề cột sắp xếp được', 'Click', 'After:\n– Đổi chiều sắp xếp và nạp lại danh sách từ trang 1.'],
                        ['Chuyển trang', 'Click', 'Before:\n– Giữ nguyên bộ lọc và thứ tự sắp xếp.\nAfter:\n– Nạp dữ liệu trang mới.'],
                        ['Đổi số dòng mỗi trang', 'Change', 'After:\n– Quay về trang 1 và nạp lại theo số dòng mới.']]},
            {'ten': 'Tìm kiếm và lọc',
             'qtc': 'Kịch bản tìm kiếm, Bộ lọc, Dropdown, Phân trang. Chỉ bổ sung các tiêu chí tìm kiếm/lọc riêng của Danh mục tài khoản.',
             'gioi_thieu': [['Tên chức năng', 'Tìm kiếm và lọc danh sách'],
                            ['Mô tả', 'Thu hẹp danh sách bằng ô tìm kiếm nhanh và khối Tìm kiếm nâng cao (Bậc tài khoản, Loại tài khoản, Theo dõi công nợ, Trạng thái, Người tạo, Người cập nhật).'],
                            ['Tác nhân', 'Người có quyền Quản lý hoặc Xem danh mục tài khoản'],
                            ['Điều kiện ban đầu', 'Đang ở màn Danh mục tài khoản.'],
                            ['Dòng sự kiện chính', '1. Người dùng nhập từ khóa và bấm Tìm kiếm / Enter, hoặc mở Tìm kiếm nâng cao và chọn tiêu chí (lọc ngay).\n2. Hệ thống áp đồng thời mọi tiêu chí và nạp lại danh sách từ trang 1.'],
                            ['Dòng sự kiện phụ', '• Không có kết quả → bảng hiện thông báo không có dữ liệu.\n• Bấm Làm mới → xóa hết tiêu chí VÀ nạp lại danh sách đầy đủ ngay.']],
             'anh': [('filter', 'Khu vực tìm kiếm và lọc của màn Danh mục tài khoản')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Phạm vi', 'Mô tả'],
                    ['1', 'Ô tìm kiếm nhanh', 'Textbox', 'Enable', '0–255 ký tự', 'Placeholder “Tìm theo số hoặc tên tài khoản...”. Số tài khoản khớp phần đầu; Tên khớp một phần bất kỳ.'],
                    ['2', 'Bậc tài khoản', 'Dropdown', 'Enable', 'Cấp 1 / Cấp 2 / Cấp 3', 'Nhãn nổi.'],
                    ['3', 'Loại tài khoản', 'Dropdown', 'Enable', 'Danh sách loại tài khoản', 'Nhãn nổi.'],
                    ['4', 'Theo dõi công nợ', 'Dropdown', 'Enable', 'Có / Không', 'Nhãn nổi.'],
                    ['5', 'Trạng thái', 'Dropdown', 'Enable', 'Hoạt động / Khóa', 'Nhãn nổi. Bỏ trống thì hiện cả hai.'],
                    ['6', 'Người tạo', 'Dropdown', 'Enable', 'Danh sách nhân viên', 'Nhãn nổi.'],
                    ['7', 'Người cập nhật', 'Dropdown', 'Enable', 'Danh sách nhân viên', 'Nhãn nổi.'],
                    ['8', 'Nút Tìm kiếm', 'Button', 'Enable', '–', 'Áp dụng các tiêu chí.'],
                    ['9', 'Nút Làm mới', 'Button', 'Enable', '–', 'Xóa hết tiêu chí VÀ nạp lại danh sách ngay.'],
                    ['10', 'Nút Tìm kiếm nâng cao', 'Button', 'Enable', '–', 'Mở / thu gọn khối lọc nâng cao.']],
             'ui_widths': [0.6, 1.2, 0.8, 0.7, 1.1, 2.6],
             'events': [['Bấm Tìm kiếm / Enter', 'Click', 'After:\n– Áp đồng thời các tiêu chí, nạp lại bảng từ trang 1.'],
                        ['Chọn một ô lọc', 'Change', 'After:\n– Lọc ngay, nạp lại bảng từ trang 1.'],
                        ['Bấm Làm mới', 'Click', 'After:\n– Xóa trắng mọi tiêu chí VÀ nạp lại danh sách đầy đủ.']]},
            {'ten': 'Thêm mới tài khoản', 'uc': 'uc_fr03',
             'qtc': 'Màn Thêm mới, Validate dữ liệu, Thông báo và UI/UX.',
             'gioi_thieu': [['Tên chức năng', 'Thêm mới tài khoản'],
                            ['Mô tả', 'Thêm một tài khoản mới vào cây tài khoản thông qua trang nhập liệu riêng.'],
                            ['Tác nhân', 'Người có quyền “%s”' % Q_QL],
                            ['Điều kiện ban đầu', 'Đang ở màn Danh mục tài khoản. Muốn thêm tài khoản Cấp 2 / 3 thì tài khoản mẹ phải có sẵn và đang Hoạt động.'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm Tạo mới.\n2. Hệ thống mở trang “Thêm tài khoản”, Trạng thái mặc định Hoạt động.\n3. Người dùng nhập Số tài khoản (hệ thống tự gợi ý Bậc theo độ dài số), Tên, chọn Loại, Tài khoản mẹ (Cấp 2/3), đánh dấu Theo dõi công nợ nếu cần, bấm Lưu.\n4. Hệ thống kiểm tra dữ liệu và quy tắc cây, ghi bản ghi mới.\n5. Quay về danh sách, báo “Thêm mới thành công”.'],
                            ['Dòng sự kiện phụ', '• Thiếu trường bắt buộc, sai định dạng, trùng số hoặc sai quy tắc cây → báo lỗi đỏ dưới ô, trang KHÔNG đóng.\n• Bấm “Lưu và tiếp tục” → ghi bản ghi rồi ở lại trang, giữ Bậc + Tài khoản mẹ.\n• Bấm Quay lại khi đã nhập dở → hỏi “Bạn có thông tin chưa lưu. Có chắc chắn muốn thoát?”.'],
                            ['Yêu cầu đặc biệt', 'Trang có ba nút: Lưu, Lưu và tiếp tục, Quay lại.']],
             'menu_them': ' => Tạo mới {icon:btn_taomoi}',
             'ghi_chu_layout': 'Thêm mới mở một trang riêng, không phải cửa sổ trên màn danh sách.',
             'anh': [('create', 'Trang Thêm tài khoản'), ('create_error', 'Lỗi đỏ ngay dưới ô còn thiếu'), ('code_error', 'Lỗi định dạng Số tài khoản hiện ngay khi gõ')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Phạm vi', 'Bắt buộc', 'Mô tả'],
                    ['1', 'Số tài khoản', 'Textbox', 'Enable (Disable khi đang có tài khoản con)', '3–15 chữ số 0-9', 'Có', 'Placeholder “VD: 1311”. Không nhận ký tự khác chữ số. Giữ số 0 đầu. Duy nhất: “Số tài khoản đã tồn tại”. Ngắn hơn 3 số: “Chỉ được nhập chữ số, từ 3 đến 15 chữ số”. Tự gợi ý Bậc khi Thêm mới.'],
                    ['2', 'Tên tài khoản', 'Textbox', 'Enable', '1–255 ký tự', 'Có', 'Được trùng. Bỏ trống “Bắt buộc phải nhập”.'],
                    ['3', 'Loại tài khoản', 'Dropdown', 'Enable', 'Loại đang Hoạt động', 'Có', 'Hiển thị “Mã - Tên”. Bỏ trống “Bắt buộc phải chọn”.'],
                    ['4', 'Theo dõi công nợ', 'Checkbox', 'Enable', 'Có / Không', 'Không', 'Mặc định không đánh dấu.'],
                    ['5', 'Tài khoản mẹ', 'Dropdown', 'Disable tới khi chọn Bậc 2/3', 'Tài khoản Hoạt động ở bậc liền trên', 'Cấp 2, 3', 'Chỉ liệt kê mẹ có số là phần đầu của Số tài khoản đang nhập. Sai: “Số tài khoản con phải bắt đầu bằng số tài khoản mẹ…”, thiếu: “Bắt buộc phải chọn tài khoản mẹ với bậc 2 và 3”.'],
                    ['6', 'Bậc tài khoản', 'Dropdown', 'Enable (Disable khi đang có tài khoản con)', 'Cấp 1 / 2 / 3', 'Có', 'Đổi Bậc → xóa trắng Tài khoản mẹ. Bỏ trống “Bắt buộc phải chọn”.'],
                    ['7', 'Trạng thái', 'Dropdown', 'Enable', 'Hoạt động / Khóa', 'Không', 'Mặc định Hoạt động. Khi Sửa: chỉ người tạo mới đổi được.'],
                    ['8', 'Nút Lưu', 'Button', 'Enable', '', '', 'Ghi bản ghi rồi quay về danh sách.'],
                    ['9', 'Nút Lưu và tiếp tục', 'Button', 'Enable', '', '', 'Ghi bản ghi, ở lại trang, giữ Bậc + Tài khoản mẹ.'],
                    ['10', 'Nút Quay lại', 'Button', 'Enable', '', '', 'Về danh sách, không ghi gì.']],
             'ui_widths': [0.5, 1.2, 0.8, 0.8, 1.2, 0.5, 2.2],
             'events': [['Bấm nút Tạo mới', 'Click', 'After:\n– Mở trang Thêm tài khoản, các ô trống, Trạng thái = Hoạt động.'],
                        ['Gõ Số tài khoản', 'Input', 'During:\n– Chặn ký tự không phải chữ số; chưa đủ 3 số → báo đỏ ngay dưới ô.\nAfter:\n– Chưa chọn Bậc → tự gợi ý Bậc theo độ dài số (3 → Cấp 1, 4 → Cấp 2, ≥5 → Cấp 3) và nạp danh sách tài khoản mẹ.'],
                        ['Đổi Bậc tài khoản', 'Change', 'After:\n– Xóa trắng Tài khoản mẹ, nạp lại danh sách tài khoản mẹ bậc liền trên.'],
                        ['Bấm Lưu', 'Click', 'During:\n– Kiểm tra bắt buộc, định dạng, trùng số, bậc tài khoản mẹ, số con nối tiếp số mẹ.\n– Có lỗi → báo đỏ dưới ô, không thực hiện After.\nAfter:\n– Ghi bản ghi mới, quay về danh sách, báo “Thêm mới thành công”.'],
                        ['Bấm Lưu và tiếp tục', 'Click', 'During:\n– Như nút Lưu.\nAfter:\n– Ghi bản ghi, xóa trắng các ô trừ Bậc và Tài khoản mẹ, ở lại trang.'],
                        ['Bấm Quay lại', 'Click', 'After:\n– Chưa nhập gì → về danh sách. Đã nhập → hỏi xác nhận thoát.']]},
            {'ten': 'Chỉnh sửa tài khoản', 'uc': 'uc_fr04',
             'qtc': 'Validate dữ liệu, Thông báo, Quy định chung về danh mục và Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Chỉnh sửa tài khoản'],
                            ['Mô tả', 'Sửa thông tin một tài khoản đã có. Dùng chung trang với Thêm mới.'],
                            ['Tác nhân', 'Người có quyền “%s”' % Q_QL],
                            ['Điều kiện ban đầu', 'Tài khoản đang ở trạng thái Hoạt động.'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm biểu tượng bút chì ở dòng cần sửa (hoặc nút Sửa ở trang Chi tiết).\n2. Hệ thống mở trang “Sửa tài khoản” với dữ liệu hiện tại.\n3. Người dùng sửa và bấm Lưu.\n4. Hệ thống kiểm tra, ghi thay đổi và ghi lịch sử các trường đã đổi.\n5. Quay về danh sách, báo “Cập nhật thành công”.'],
                            ['Dòng sự kiện phụ', '• Tài khoản đang có con → ô Số tài khoản và Bậc bị khóa kèm ghi chú; gọi thẳng chức năng đổi thì máy chủ chặn “Tài khoản đang có N tài khoản con nên không được đổi số tài khoản / bậc…”.\n• Không phải người tạo mà đổi Trạng thái sang Khóa → “Bạn không có quyền khóa tài khoản này”.\n• Bản ghi vừa bị khóa → “Tài khoản đang bị khoá, vui lòng mở khoá trước khi cập nhật.”']],
             'menu_them': ' => Sửa {icon:btn_sua}',
             'anh': [('edit', 'Trang Sửa tài khoản')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Phạm vi', 'Bắt buộc', 'Giá trị ban đầu', 'Mô tả'],
                    ['1', 'Tiêu đề trang', 'Label', 'Read-only', '–', '–', 'Sửa tài khoản', 'Trang riêng, không phải cửa sổ trên màn danh sách.'],
                    ['2', 'Dòng nhắc chưa có loại', 'Label', 'Hiển thị có điều kiện', '–', '–', 'Ẩn', 'Chỉ hiện khi bản ghi chưa được gán loại: “Bản ghi này chưa được gán Loại tài khoản. Hãy chọn loại trước khi lưu.”'],
                    ['3', 'Số tài khoản', 'Textbox', 'Enable / Disable khi đang có tài khoản con', '3–15 chữ số 0-9', 'Có', 'Dữ liệu hiện tại', 'Không nhận ký tự khác chữ số, giữ số 0 đầu. Trùng tài khoản khác: “Số tài khoản đã tồn tại” (bỏ qua chính bản ghi). Đang có con: ô bị khóa, dưới ô ghi “%s”' % MSG_CON],
                    ['4', 'Tên tài khoản', 'Textbox', 'Enable', '1–255 ký tự', 'Có', 'Dữ liệu hiện tại', 'Được trùng. Bỏ trống: “Bắt buộc phải nhập”.'],
                    ['5', 'Loại tài khoản', 'Dropdown', 'Enable', 'Loại đang Hoạt động', 'Có', 'Dữ liệu hiện tại', 'Hiển thị “Mã - Tên”. Loại đang dùng nay đã Khóa vẫn hiện đúng tên kèm 🔒. Bỏ trống: “Bắt buộc phải chọn”.'],
                    ['6', 'Theo dõi công nợ', 'Checkbox', 'Enable', 'Có / Không', 'Không', 'Dữ liệu hiện tại', 'Đánh dấu = Có.'],
                    ['7', 'Tài khoản mẹ', 'Dropdown', 'Enable / Disable khi Bậc = Cấp 1', 'Tài khoản Hoạt động ở bậc liền trên', 'Cấp 2, 3', 'Dữ liệu hiện tại', 'Cấp 1: placeholder “Tài khoản cấp 1 không có tài khoản mẹ”. Thiếu: “Bắt buộc phải chọn tài khoản mẹ với bậc 2 và 3”; số con không nối tiếp số mẹ: “Số tài khoản con phải bắt đầu bằng số tài khoản mẹ…”.'],
                    ['8', 'Bậc tài khoản', 'Dropdown', 'Enable / Disable khi đang có tài khoản con', 'Cấp 1 / 2 / 3', 'Có', 'Dữ liệu hiện tại', 'Đổi Bậc → xóa trắng Tài khoản mẹ. Đang có con: ô bị khóa kèm cùng ghi chú như ô Số tài khoản.'],
                    ['9', 'Trạng thái', 'Dropdown', 'Enable / Disable khi không phải người tạo', 'Hoạt động / Khóa', 'Không', 'Dữ liệu hiện tại', 'Chỉ người tạo mới đổi sang Khóa được; máy chủ chặn “Bạn không có quyền khóa tài khoản này”.'],
                    ['10', 'Nút Lưu', 'Button', 'Enable', '–', '–', 'Hiển thị', 'Ghi thay đổi rồi quay về danh sách.'],
                    ['11', 'Nút Quay lại', 'Button', 'Enable', '–', '–', 'Hiển thị', 'Về danh sách, không ghi gì; đã sửa dở thì hỏi xác nhận thoát.']],
             'ui_widths': [0.4, 1.0, 0.7, 0.9, 1.0, 0.5, 0.7, 2.0],
             'events': [['Bấm biểu tượng bút chì (hoặc nút Sửa ở trang Chi tiết)', 'Click', 'Before:\n– Bản ghi đã Khóa thì nút không hiển thị.\nAfter:\n– Mở trang Sửa với dữ liệu hiện tại; tài khoản có con thì khóa ô Số tài khoản và Bậc; không phải người tạo thì khóa ô Trạng thái.'],
                        ['Mở trang Sửa của tài khoản đang Khóa (không qua nút Sửa)', 'System', 'During:\n– Phát hiện bản ghi đang Khóa.\nAfter:\n– Báo “Tài khoản đang bị khoá, vui lòng mở khoá trước khi sửa.” và chuyển sang trang Chi tiết.'],
                        ['Đổi Bậc tài khoản', 'Change', 'After:\n– Xóa trắng Tài khoản mẹ, nạp lại danh sách tài khoản mẹ bậc liền trên.'],
                        ['Bấm Lưu', 'Click', 'Before:\n– Bản ghi vừa bị người khác Khóa → máy chủ từ chối “Tài khoản đang bị khoá, vui lòng mở khoá trước khi cập nhật.”\nDuring:\n– Kiểm tra như Thêm mới, bỏ qua trùng với chính bản ghi.\n– Đang có con mà đổi Số / Bậc → “Tài khoản đang có N tài khoản con nên không được đổi số tài khoản / bậc. Hãy chuyển hoặc xóa các tài khoản con trước.”\n– Có lỗi → báo đỏ dưới ô, không thực hiện After.\nAfter:\n– Ghi thay đổi, ghi lịch sử “Thay đổi thông tin” cho từng trường đổi.\n– Quay về danh sách, báo “Cập nhật thành công”.'],
                        ['Bấm Quay lại', 'Click', 'After:\n– Chưa sửa gì → về danh sách. Đã sửa → hỏi “Bạn có thông tin chưa lưu. Có chắc chắn muốn thoát?”.']]},
            {'ten': 'Xóa tài khoản', 'uc': 'uc_fr05',
             'qtc': 'Quy tắc Xóa, Thông báo, Quy định chung về danh mục.',
             'gioi_thieu': [['Tên chức năng', 'Xóa tài khoản'],
                            ['Mô tả', 'Xóa hẳn một tài khoản chưa có con và chưa được hạch toán.'],
                            ['Tác nhân', 'Người có quyền “%s” VÀ là người đã tạo tài khoản' % Q_QL],
                            ['Điều kiện ban đầu', 'Tài khoản không có tài khoản con và chưa phát sinh ở chứng từ nào.'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm biểu tượng thùng rác.\n2. Hệ thống hiện hộp “Xác nhận xóa” nêu rõ số và tên tài khoản.\n3. Người dùng bấm Xóa.\n4. Hệ thống xóa bản ghi cùng lịch sử của nó, báo “Xóa thành công”, nạp lại danh sách.'],
                            ['Dòng sự kiện phụ', '• Bấm Hủy → đóng hộp, không thay đổi.\n• Không đủ điều kiện → nút Xóa KHÔNG hiển thị; nếu điều kiện vừa đổi trước khi xác nhận → “Không xóa được: tài khoản có tài khoản con, đã phát sinh dữ liệu, hoặc bạn không phải người tạo”.']],
             'menu_them': ' => Xóa {icon:btn_xoa}',
             'anh': [('delete', 'Hộp xác nhận xóa tài khoản')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Mô tả'],
                    ['1', 'Nút Xóa (biểu tượng thùng rác)', 'Icon Button', 'Ở cột Hành động. Chỉ hiện khi có quyền Quản lý VÀ là người tạo, tài khoản không có con và chưa phát sinh hạch toán.'],
                    ['2', 'Nút Xóa ở cuối trang Chi tiết', 'Button', 'Cùng điều kiện hiện như ở danh sách.'],
                    ['3', 'Tiêu đề hộp xác nhận', 'Label', '“Xác nhận xóa”.'],
                    ['4', 'Nội dung hộp xác nhận', 'Label', '“Bạn có chắc muốn xóa tài khoản \'<số> - <tên>\'?”'],
                    ['5', 'Nút Xóa', 'Button', 'Xác nhận thực hiện.'],
                    ['6', 'Nút Hủy', 'Button', 'Đóng hộp, không làm gì.']],
             'ui_widths': [0.5, 1.8, 1.0, 3.4],
             'events': [['Bấm biểu tượng thùng rác (hoặc Xóa ở trang Chi tiết)', 'Click', 'Before:\n– Không đủ điều kiện thì nút không hiển thị.\nAfter:\n– Hiện hộp “Xác nhận xóa” kèm số và tên tài khoản.'],
                        ['Bấm Xóa', 'Click', 'During:\n– Tài khoản đang Khóa → máy chủ từ chối “Tài khoản đang bị khoá, vui lòng mở khoá trước khi cập nhật.”\n– Máy chủ kiểm tra lại người tạo, tài khoản con, dữ liệu hạch toán; không đạt → “Không xóa được: tài khoản có tài khoản con, đã phát sinh dữ liệu, hoặc bạn không phải người tạo”.\nAfter:\n– Xóa hẳn bản ghi cùng lịch sử của nó, báo “Xóa thành công”.\n– Ở danh sách: nạp lại danh sách. Ở trang Chi tiết: quay về danh sách.'],
                        ['Bấm Hủy', 'Click', 'After:\n– Đóng hộp, không thay đổi.']]},
            {'ten': 'Khóa / Mở khóa tài khoản', 'uc': 'uc_fr06',
             'qtc': 'Quy tắc Khóa/Mở khóa, Thông báo, Quy định chung về danh mục và Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Khóa / Mở khóa tài khoản'],
                            ['Mô tả', 'Đổi trạng thái tài khoản giữa Hoạt động và Khóa.'],
                            ['Tác nhân', 'Người có quyền “%s” VÀ là người đã tạo tài khoản' % Q_QL],
                            ['Điều kiện ban đầu', 'Khóa: tài khoản đang Hoạt động. Mở khóa: tài khoản đang Khóa.'],
                            ['Dòng sự kiện chính', '1. Người dùng chọn Khóa (hoặc Mở khóa) ở cột Hành động hoặc cuối trang Chi tiết.\n2. Hệ thống hiện hộp xác nhận nêu rõ số và tên tài khoản.\n3. Người dùng xác nhận.\n4. Hệ thống đổi trạng thái, ghi lịch sử trường Trạng thái, báo “Khóa thành công” / “Mở khóa thành công”.'],
                            ['Dòng sự kiện phụ', '• Bấm Hủy → không thay đổi.\n• Không phải người tạo (gọi thẳng chức năng) → “Bạn không có quyền khóa tài khoản này” / “Bạn không có quyền mở khóa tài khoản này”.\n• Khóa tài khoản mẹ không khóa các tài khoản con.']],
             'menu_them': ' => Khóa / Mở khóa',
             'anh': [('lock', 'Hộp xác nhận khóa tài khoản'), ('rowmenu', 'Các nút ở cột Hành động')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Mô tả'],
                    ['1', 'Mục Khóa / Mở khóa ở cột Hành động', 'Button', 'Nhãn và biểu tượng ổ khóa đổi theo trạng thái hiện tại. Chỉ hiện với quyền Quản lý VÀ người đã tạo tài khoản.'],
                    ['2', 'Nút Khóa / Mở khóa ở cuối trang Chi tiết', 'Button', 'Cùng điều kiện hiện như ở danh sách. Khóa màu cam, Mở khóa màu xanh lá.'],
                    ['3', 'Tiêu đề hộp xác nhận', 'Label', '“Xác nhận khóa” hoặc “Xác nhận mở khóa”.'],
                    ['4', 'Nội dung hộp xác nhận', 'Label', '“Bạn có chắc muốn khóa tài khoản \'<số> - <tên>\'?” (mở khóa tương tự).'],
                    ['5', 'Nút Khóa / Mở khóa', 'Button', 'Xác nhận thực hiện.'],
                    ['6', 'Nút Hủy', 'Button', 'Đóng hộp, không làm gì.'],
                    ['7', 'Cột Trạng thái', 'Badge', 'Hoạt động hoặc Khóa, hai màu khác nhau.']],
             'ui_widths': [0.5, 1.8, 1.0, 3.4],
             'events': [['Chọn Khóa / Mở khóa', 'Click', 'After:\n– Hiện hộp xác nhận kèm số và tên tài khoản.'],
                        ['Xác nhận', 'Click', 'During:\n– Máy chủ kiểm tra lại người tạo và trạng thái hiện tại; không đạt → “Bạn không có quyền khóa tài khoản này” / “Bạn không có quyền mở khóa tài khoản này”.\nAfter:\n– Đổi trạng thái (KHÔNG xóa dữ liệu, KHÔNG khóa tài khoản con), ghi lịch sử trường Trạng thái.\n– Báo “Khóa thành công” / “Mở khóa thành công”, cập nhật cột Trạng thái và các nút (danh sách nạp lại; trang Chi tiết nạp lại tại chỗ).'],
                        ['Bấm Hủy', 'Click', 'After:\n– Đóng hộp, không thay đổi.']]},
            {'ten': 'Xem lịch sử thay đổi',
             'qtc': 'Quy tắc ghi lịch sử và hiển thị lịch sử. Chỉ bổ sung thông tin riêng của Danh mục tài khoản.',
             'gioi_thieu': [['Tên chức năng', 'Xem lịch sử thay đổi'],
                            ['Mô tả', 'Liệt kê các lần thay đổi của một tài khoản, kèm giá trị cũ → mới, người thực hiện và thời điểm.'],
                            ['Tác nhân', 'Người có quyền Quản lý hoặc Xem danh mục tài khoản'],
                            ['Dòng sự kiện chính', '1. Người dùng chọn Lịch sử ở cột Hành động, hoặc mở khối Lịch sử ở trang Chi tiết.\n2. Hệ thống hiển thị các mốc thay đổi, mới nhất ở trên cùng.'],
                            ['Dòng sự kiện phụ', '• Khóa / Mở khóa hiện là Thay đổi thông tin ở trường Trạng thái.\n• Tạo mới / Import chưa sinh mốc lịch sử; bản ghi chưa từng sửa → “Chưa có lịch sử thao tác nào.”']],
             'menu_them': ' => Lịch sử',
             'anh': [('history', 'Cửa sổ Lịch sử thay đổi của tài khoản')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Giá trị ban đầu', 'Mô tả'],
                    ['1', 'Mục Lịch sử ở cột Hành động', 'Button', 'Hiển thị', 'Hiện với mọi người vào được màn hình.'],
                    ['2', 'Tiêu đề cửa sổ', 'Label', 'Lịch sử thay đổi: <số> - <tên>', 'Kèm biểu tượng đồng hồ.'],
                    ['3', 'Nút Bộ lọc', 'Button', 'Hiển thị', 'Mở / thu gọn khối lọc; khối lọc ghim ở đầu khi cuộn.'],
                    ['4', 'Loại hành động', 'Dropdown', 'Trống (“Tất cả loại hành động”)', 'Lọc theo loại hành động có trong lịch sử của bản ghi.'],
                    ['5', 'Người thực hiện', 'Dropdown', 'Trống (“Tất cả người thực hiện”)', 'Lọc theo người đã thao tác.'],
                    ['6', 'Từ ngày / Đến ngày', 'Date picker', 'Trống', 'dd/mm/yyyy, tính cả hai đầu.'],
                    ['7', 'Nút Làm mới (trong khối lọc)', 'Button', 'Hiển thị', 'Xóa các tiêu chí lọc.'],
                    ['8', 'Thông tin thay đổi', 'Text', 'Theo dữ liệu', '- Thời điểm thay đổi.\n- Loại hành động (Khóa / Mở khóa cũng hiện là Thay đổi thông tin).\n- “Người thực hiện: …” kèm phòng ban.\n- Từng trường đã đổi: giá trị cũ → giá trị mới.\nMới nhất ở trên cùng.'],
                    ['9', 'Trạng thái rỗng', 'Label', 'Ẩn', '“Chưa có lịch sử thao tác nào.” khi bản ghi chưa có mốc; “Không có lịch sử phù hợp bộ lọc.” khi lọc không khớp.'],
                    ['10', 'Nút Đóng', 'Button', 'Hiển thị', 'Đóng cửa sổ.'],
                    ['11', 'Khối Lịch sử ở trang Chi tiết', 'Section', 'Thu gọn', 'Nút “Xem lịch sử” / “Thu gọn”; khi đã mở có thêm nút “Làm mới”. Nội dung và bộ lọc giống hệt cửa sổ.']],
             'ui_widths': [0.5, 1.5, 0.9, 1.4, 2.8],
             'events': [['Chọn Lịch sử ở cột Hành động', 'Click', 'After:\n– Mở cửa sổ, nạp các mốc thay đổi, mới nhất ở trên cùng.'],
                        ['Bấm Xem lịch sử ở trang Chi tiết', 'Click', 'After:\n– Mở khối Lịch sử; chỉ nạp dữ liệu ở lần mở đầu tiên.'],
                        ['Đổi tiêu chí lọc', 'Change', 'After:\n– Lọc ngay danh sách mốc theo các tiêu chí, không cần bấm nút.'],
                        ['Bấm Làm mới', 'Click', 'After:\n– Trong khối lọc: xóa các tiêu chí. Ở tiêu đề khối (trang Chi tiết): nạp lại lịch sử.'],
                        ['Bấm Đóng', 'Click', 'After:\n– Đóng cửa sổ; danh sách phía sau giữ nguyên bộ lọc và trang.']]},
            {'ten': 'Import file tài khoản', 'uc': 'uc_fr08',
             'qtc': 'Quy tắc Import file, Validate dữ liệu, Thông báo và Quy định chung về danh mục. Chỉ bổ sung mapping/validation riêng.',
             'gioi_thieu': [['Tên chức năng', 'Import file tài khoản'],
                            ['Mô tả', 'Thêm nhiều tài khoản cùng lúc từ file Excel mẫu, có bước Validate trước khi ghi.'],
                            ['Tác nhân', 'Người có quyền “%s”' % Q_QL],
                            ['Điều kiện ban đầu', 'Đang ở màn Danh mục tài khoản và đã chuẩn bị file theo mẫu.'],
                            ['Dòng sự kiện chính', '1. Bấm Import Excel.\n2. Bấm Tải file mẫu (Mau_import_tai_khoan.xlsx), điền dữ liệu từ hàng 2.\n3. Bấm Chọn file Excel rồi Load lên bảng.\n4. Bấm Validate; hệ thống kiểm tra từng dòng, khóa dòng hợp lệ.\n5. Sửa dòng lỗi rồi Validate lại, hoặc bấm Bỏ dòng lỗi.\n6. Bấm Import; hệ thống ghi các dòng hợp lệ theo thứ tự bậc 1 → 2 → 3, báo “Import thành công N tài khoản.”, đóng cửa sổ và nạp lại danh sách.'],
                            ['Dòng sự kiện phụ', '• File không phải .xlsx/.xls → “Vui lòng chọn file .xlsx hoặc .xls”.\n• File không có dòng dữ liệu → “Không có dòng dữ liệu hợp lệ.”\n• Quá 500 dòng → báo vượt giới hạn 500 dòng.\n• Còn dòng lỗi → nút Import không bấm được.'],
                            ['Yêu cầu đặc biệt', 'Validate không ghi dữ liệu. Tài khoản mẹ được phép nằm ngay trong file. Tài khoản nhập vào luôn Hoạt động. Người tạo là người thực hiện.']],
             'menu_them': ' => Import Excel {icon:btn_import}',
             'ghi_chu_layout': 'Cửa sổ Import được mở ngay trên màn hình danh sách.',
             'anh': [('import_open', 'Cửa sổ Import tài khoản khi vừa mở'), ('import_loaded', 'Dữ liệu đã được load lên bảng xem trước'),
                     ('import_validated', 'Kết quả Validate — mỗi dòng lỗi nêu rõ lý do')],
             'bang_them': [('Quy tắc kiểm tra riêng của file Import', [['Cột', 'Quy tắc / thông báo lỗi'],
                            ['Số tài khoản *', 'Bắt buộc (“Số tài khoản không được để trống”), chỉ chữ số 3–15 ký tự (“Chỉ được nhập chữ số, từ 3 đến 15 chữ số”), không trùng trong file (“Số tài khoản bị trùng trong file import (dòng N)”), không trùng hệ thống (“Số tài khoản đã tồn tại trong hệ thống”).'],
                            ['Tên tài khoản *', 'Bắt buộc (“Tên tài khoản không được để trống”), tối đa 255 ký tự (“Tên tài khoản tối đa 255 ký tự”).'],
                            ['Bậc *', 'Bắt buộc (“Bậc tài khoản không được để trống”), chỉ 1 / 2 / 3 (“Bậc tài khoản chỉ nhận 1, 2 hoặc 3”).'],
                            ['Tài khoản mẹ', 'Bắt buộc với bậc 2, 3 (“Tài khoản bậc 2 và 3 bắt buộc có tài khoản mẹ”); phải có trong danh mục hoặc trong file (“Không tìm thấy tài khoản mẹ”); đúng bậc liền trên (“Tài khoản mẹ phải là tài khoản bậc N…”); số con bắt đầu bằng số mẹ (“Số tài khoản con phải bắt đầu bằng số tài khoản mẹ…”). Bậc 1 thì bỏ qua cột này.'],
                            ['Loại tài khoản *', 'Bắt buộc (“Loại tài khoản không được để trống”); ghi Mã hoặc Tên loại, không phân biệt hoa thường (“Không tìm thấy loại tài khoản”).'],
                            ['Theo dõi công nợ', 'Có / Không; để trống = Không; giá trị khác báo “Theo dõi công nợ chỉ nhận \'Có\' hoặc \'Không\' (để trống = Không)”.']], [1.3, 4])],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Bắt buộc', 'Giá trị ban đầu', 'Mô tả'],
                    ['1', 'Nút Import Excel', 'Button', 'Enable', '–', 'Hiển thị với quyền Quản lý', 'Trên thanh công cụ của bảng. Mở cửa sổ “Import tài khoản”, dòng phụ “Import từ Excel • Validate xong dòng hợp lệ sẽ bị khoá”.'],
                    ['2', 'Nút Chọn file Excel', 'Button', 'Enable', 'Có', 'Chưa chọn file', 'Chỉ nhận .xlsx / .xls; tên file hiện ngay cạnh nút.'],
                    ['3', 'Nút Tải file mẫu', 'Button', 'Enable', '–', 'Hiển thị', 'Tải Mau_import_tai_khoan.xlsx: Số tài khoản *, Tên tài khoản *, Bậc *, Tài khoản mẹ, Loại tài khoản *, Theo dõi công nợ, kèm 3 dòng ví dụ.'],
                    ['4', 'Nút Load lên bảng', 'Button', 'Enable / Disable', '–', 'Mờ khi chưa chọn file', 'Đọc file và đổ dữ liệu lên bảng xem trước.'],
                    ['5', 'Nút Validate', 'Button', 'Enable / Disable', '–', 'Mờ khi bảng chưa có dòng', 'Kiểm tra từng dòng ở máy chủ; dòng hợp lệ bị khóa, không sửa được nữa.'],
                    ['6', 'Nút Import', 'Button', 'Enable / Disable', '–', 'Mờ', 'Chỉ bấm được khi đã Validate, KHÔNG còn dòng lỗi và có ít nhất 1 dòng hợp lệ.'],
                    ['7', 'Bảng xem trước', 'Table/Grid', 'Enable', '–', 'Trống', 'STT + 6 cột như file mẫu; 4 cột bắt buộc có dấu * đỏ; ô Theo dõi công nợ gợi ý “Có / Không”. Sửa trực tiếp được ở dòng lỗi.'],
                    ['8', 'Ô Tổng / Hợp lệ / Lỗi', 'Label', 'Read-only', '–', 'Tổng: 0', 'Sau Load hiện Tổng; sau Validate hiện thêm Hợp lệ và Lỗi. Có dòng vừa sửa → “Có dòng đã sửa (cần validate lại)”.'],
                    ['9', 'Thông báo lỗi theo dòng', 'Label', 'Hiển thị', '–', 'Ẩn', 'Dòng lỗi viền đỏ, lý do ghi ngay dưới dòng (xem bảng quy tắc kiểm tra ở trên).'],
                    ['10', 'Nút Bỏ dòng lỗi', 'Button', 'Enable', '–', 'Hiển thị', 'Loại toàn bộ dòng lỗi khỏi bảng xem trước.'],
                    ['11', 'Nút Xoá trạng thái validate', 'Button', 'Enable', '–', 'Hiển thị', 'Bỏ khóa các dòng hợp lệ và bỏ thông báo lỗi validate.'],
                    ['12', 'Nút Làm mới', 'Button', 'Enable', '–', 'Hiển thị', 'Xóa file đã chọn và bảng xem trước, đưa cửa sổ về trạng thái rỗng.'],
                    ['13', 'Nút Đóng', 'Button', 'Enable', '–', 'Hiển thị', 'Đóng cửa sổ, không ghi gì.']],
             'ui_widths': [0.4, 1.2, 0.8, 0.8, 0.5, 1.0, 2.5],
             'events': [['Bấm Import Excel', 'Click', 'After:\n– Mở cửa sổ Import tài khoản ở trạng thái rỗng.'],
                        ['Bấm Tải file mẫu', 'Click', 'After:\n– Tải Mau_import_tai_khoan.xlsx về máy; lỗi → “Lỗi khi tải file mẫu”.'],
                        ['Chọn file', 'Change', 'During:\n– File không phải .xlsx / .xls → “Vui lòng chọn file .xlsx hoặc .xls”, không nhận file.\nAfter:\n– Hiện tên file, nút Load lên bảng sáng lên.'],
                        ['Bấm Load lên bảng', 'Click', 'During:\n– Không đọc được file → “Không đọc được file Excel.”\n– File không có dòng dữ liệu → “Không có dòng dữ liệu hợp lệ.”\n– Quá 500 dòng → “File có N dòng dữ liệu, vượt quá giới hạn 500 dòng mỗi lần import. Vui lòng tách file và import nhiều lần.”\nAfter:\n– Đổ dữ liệu lên bảng xem trước, cập nhật ô Tổng.'],
                        ['Bấm Validate', 'Click', 'During:\n– Máy chủ kiểm tra từng dòng theo quy tắc của Thêm mới (mục 2.3) và bảng quy tắc riêng ở trên; tài khoản mẹ được tìm cả trong file.\nAfter:\n– Báo “Validate thành công” hoặc “Validate xong: X hợp lệ, Y không hợp lệ”.\n– Dòng lỗi ghi lý do, dòng hợp lệ bị khóa, cập nhật Hợp lệ / Lỗi.\n– KHÔNG ghi bản ghi nào ở bước này.'],
                        ['Sửa ô ở dòng lỗi', 'Input', 'After:\n– Đánh dấu dòng đã sửa, nhắc Validate lại; nút Import mờ cho tới khi Validate lại.'],
                        ['Bấm Bỏ dòng lỗi', 'Click', 'During:\n– Chưa Validate → “Hãy Validate trước rồi mới bỏ dòng lỗi.”\nAfter:\n– Loại dòng lỗi, báo “Đã bỏ N dòng lỗi. Còn lại M dòng hợp lệ.”'],
                        ['Bấm Import', 'Click', 'During:\n– Máy chủ kiểm tra lại toàn bộ dòng gửi lên; không còn dòng hợp lệ → “Không có dòng nào hợp lệ để import”.\nAfter:\n– Ghi các dòng hợp lệ theo thứ tự Cấp 1 → 2 → 3, trạng thái Hoạt động, người tạo là người thực hiện.\n– Báo “Import thành công N tài khoản.” (có dòng lỗi khi ghi → “Import thành công X/Y tài khoản. Z dòng thất bại.”), đóng cửa sổ và nạp lại danh sách.'],
                        ['Bấm Làm mới / Đóng', 'Click', 'After:\n– Làm mới: đưa cửa sổ về trạng thái rỗng. Đóng: đóng cửa sổ, không ghi gì.']]},
            {'ten': 'Xuất danh sách ra Excel', 'uc': 'uc_fr09',
             'qtc': 'Quy tắc Excel và Cấu hình cột. Chỉ bổ sung danh sách trường được phép xuất riêng.',
             'gioi_thieu': [['Tên chức năng', 'Xuất danh sách tài khoản ra Excel'],
                            ['Mô tả', 'Xuất kết quả đang lọc ra file Excel, cho phép chọn trường và thứ tự cột.'],
                            ['Tác nhân', 'Người có quyền Quản lý hoặc Xem danh mục tài khoản'],
                            ['Dòng sự kiện chính', '1. Bấm Xuất Excel.\n2. Hệ thống mở cửa sổ “Chọn trường xuất file”, tích sẵn đúng các cột đang hiển thị trên bảng.\n3. Người dùng tích chọn và kéo ☰ để sắp thứ tự.\n4. Bấm Xuất file; hệ thống tải danh_muc_tai_khoan.xlsx theo đúng bộ lọc và thứ tự trường, báo “Xuất Excel thành công”.'],
                            ['Dòng sự kiện phụ', '• Bỏ chọn hết trường → nút Xuất file không bấm được.\n• Bấm Đóng → không xuất gì.'],
                            ['Yêu cầu đặc biệt', 'File chứa toàn bộ kết quả lọc, có cột STT ở đầu và tiêu đề “Danh mục tài khoản”.']],
             'menu_them': ' => Xuất Excel {icon:btn_xuatexcel}',
             'anh': [('export', 'Cửa sổ Chọn trường xuất file')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
                    ['1', 'Nút Xuất Excel', 'Button', 'Enable', 'Hiển thị', 'Trên thanh công cụ của bảng, màu xanh lá. Mở cửa sổ “Chọn trường xuất file”.'],
                    ['2', 'Danh sách trường', 'Checkbox chọn nhiều', 'Enable', 'Tích sẵn cột đang hiển thị trên bảng', 'Tám trường: Số tài khoản, Tên tài khoản, Tài khoản mẹ, Bậc, Loại tài khoản, Trạng thái, Người tạo, Ngày tạo. Kéo ☰ đổi thứ tự cột trong file.'],
                    ['3', 'Nút Chọn tất cả / Bỏ chọn hết', 'Button', 'Enable', 'Hiển thị', 'Tích / bỏ tích toàn bộ.'],
                    ['4', 'Dòng đếm', 'Label', 'Read-only', 'Đang chọn N/8 trường', 'Cập nhật theo số trường đang tích.'],
                    ['5', 'Nút Xuất file', 'Button', 'Enable/Disable', 'Mờ khi chưa chọn trường', 'Sinh file và tải về.'],
                    ['6', 'Nút Đóng', 'Button', 'Enable', 'Hiển thị', 'Đóng cửa sổ, không xuất.']],
             'ui_widths': [0.6, 1.5, 1, 0.8, 1.2, 2.6],
             'events': [['Bấm Xuất Excel', 'Click', 'After:\n– Mở cửa sổ Chọn trường xuất file, tích sẵn đúng các cột đang hiển thị trên bảng.'],
                        ['Tích / bỏ tích, kéo ☰ đổi thứ tự', 'Change', 'During:\n– Ghi nhận thứ tự trường để quyết định thứ tự cột trong file; cập nhật “Đang chọn N/8 trường”.\n– Bỏ chọn hết thì nút Xuất file mờ đi.'],
                        ['Bấm Xuất file', 'Click', 'During:\n– Lấy TOÀN BỘ kết quả theo đúng bộ lọc và sắp xếp đang áp dụng, không giới hạn ở trang đang xem.\nAfter:\n– Tải danh_muc_tai_khoan.xlsx (tiêu đề “Danh mục tài khoản”, cột STT ở đầu), báo “Xuất Excel thành công”; lỗi → “Lỗi khi xuất Excel”.'],
                        ['Bấm Đóng', 'Click', 'After:\n– Đóng cửa sổ, không xuất gì.']]},
            {'ten': 'Xem chi tiết tài khoản', 'uc': 'uc_fr10',
             'qtc': 'Màn Xem chi tiết và Phân quyền.',
             'gioi_thieu': [['Tên chức năng', 'Xem chi tiết tài khoản'],
                            ['Mô tả', 'Trang “Chi tiết tài khoản: <số>” hiển thị đủ thông tin ở chế độ chỉ đọc, kèm khối Lịch sử và các nút thao tác giống cột Hành động.'],
                            ['Tác nhân', 'Người có quyền Quản lý hoặc Xem danh mục tài khoản'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm Số tài khoản ở danh sách.\n2. Hệ thống mở trang Chi tiết; cuối trang có Sửa, Xóa, Khóa / Mở khóa (theo cùng điều kiện như danh sách) và Quay lại.']],
             'menu_them': ' => bấm Số tài khoản',
             'anh': [('detail', 'Trang Chi tiết tài khoản ở chế độ chỉ đọc')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
                    ['1', 'Số tài khoản ở danh sách', 'Link', 'Enable', 'Hiển thị', 'Bấm để mở trang Chi tiết; chuột phải mở được ở tab mới.'],
                    ['2', 'Tiêu đề trang', 'Label', 'Read-only', 'Chi tiết tài khoản: <số>', 'Trang riêng, không phải cửa sổ.'],
                    ['3', 'Dòng nhắc chưa có loại', 'Label', 'Hiển thị có điều kiện', 'Ẩn', 'Bản ghi chưa được gán loại → “Bản ghi này chưa được gán Loại tài khoản. Hãy chọn loại trước khi lưu.”'],
                    ['4', 'Số tài khoản', 'Textbox', 'Read-only', 'Dữ liệu hiện tại', 'Khối “Thông tin chung”.'],
                    ['5', 'Tên tài khoản', 'Textbox', 'Read-only', 'Dữ liệu hiện tại', ''],
                    ['6', 'Loại tài khoản', 'Dropdown', 'Read-only', 'Dữ liệu hiện tại', '“Mã - Tên”; loại đã Khóa vẫn hiện đúng tên kèm 🔒.'],
                    ['7', 'Theo dõi công nợ', 'Checkbox', 'Read-only', 'Dữ liệu hiện tại', ''],
                    ['8', 'Tài khoản mẹ', 'Dropdown', 'Read-only', 'Dữ liệu hiện tại', 'Trống với tài khoản Cấp 1.'],
                    ['9', 'Bậc tài khoản', 'Dropdown', 'Read-only', 'Dữ liệu hiện tại', 'Cấp 1 / 2 / 3.'],
                    ['10', 'Trạng thái', 'Dropdown', 'Read-only', 'Dữ liệu hiện tại', 'Hoạt động / Khóa.'],
                    ['11', 'Khối Lịch sử', 'Section', 'Enable', 'Thu gọn', 'Xem mục 2.7.'],
                    ['12', 'Nút Sửa', 'Button', 'Enable', 'Ẩn nếu không đủ điều kiện', 'Quyền Quản lý VÀ tài khoản đang Hoạt động.'],
                    ['13', 'Nút Xóa', 'Button', 'Enable', 'Ẩn nếu không đủ điều kiện', 'Cùng điều kiện với nút Xóa ở danh sách (mục 2.5).'],
                    ['14', 'Nút Khóa / Mở khóa', 'Button', 'Enable', 'Ẩn nếu không đủ điều kiện', 'Quyền Quản lý VÀ người tạo; Khóa màu cam, Mở khóa màu xanh lá (mục 2.6).'],
                    ['15', 'Nút Quay lại', 'Button', 'Enable', 'Hiển thị', 'Về màn danh sách.']],
             'ui_widths': [0.5, 1.4, 0.8, 0.9, 1.2, 2.6],
             'events': [['Bấm Số tài khoản ở danh sách', 'Click', 'After:\n– Mở trang Chi tiết, nạp dữ liệu; lỗi → “Lỗi khi tải dữ liệu tài khoản” và quay về danh sách.'],
                        ['Bấm Sửa', 'Click', 'After:\n– Mở trang Sửa tài khoản (mục 2.4).'],
                        ['Bấm Xóa', 'Click', 'After:\n– Hiện hộp “Xác nhận xóa”; xóa xong quay về danh sách (mục 2.5).'],
                        ['Bấm Khóa / Mở khóa', 'Click', 'After:\n– Hiện hộp xác nhận; xác nhận xong nạp lại trang tại chỗ, các nút đổi theo trạng thái mới (mục 2.6).'],
                        ['Bấm Quay lại', 'Click', 'After:\n– Về màn danh sách.']]},
            {'ten': 'Tùy chỉnh cột hiển thị',
             'qtc': 'Tùy chỉnh cột.',
             'gioi_thieu': [['Tên chức năng', 'Tùy chỉnh cột hiển thị'],
                            ['Mô tả', 'Bật/tắt và sắp xếp thứ tự cột của bảng; cấu hình lưu riêng theo người dùng.'],
                            ['Yêu cầu đặc biệt', 'Cột STT, Số tài khoản, Hành động bị khóa. Mặc định ẩn: Bậc, Tài khoản mẹ, Loại tài khoản, Theo dõi công nợ, Người cập nhật, Ngày cập nhật.']],
             'menu_them': ' => Cấu hình cột {icon:btn_cauhinhcot}',
             'anh': [('colcfg', 'Cửa sổ Tuỳ chỉnh cột')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
                    ['1', 'Biểu tượng Cấu hình cột hiển thị', 'Icon Button', 'Enable', 'Hiển thị', 'Cuối thanh công cụ của bảng, chú thích “Cấu hình cột hiển thị”. Mở cửa sổ “Tuỳ chỉnh cột”.'],
                    ['2', 'Danh sách cột', 'Checkbox chọn nhiều', 'Enable', 'Theo cấu hình đã lưu; lần đầu theo mặc định', '13 cột: STT, Số tài khoản, Tên tài khoản, Bậc, Tài khoản mẹ, Loại tài khoản, Theo dõi công nợ, Người cập nhật, Ngày cập nhật, Người tạo, Ngày tạo, Trạng thái, Hành động. Mặc định ẩn: Bậc, Tài khoản mẹ, Loại tài khoản, Theo dõi công nợ, Người cập nhật, Ngày cập nhật.'],
                    ['3', 'Cột bắt buộc', 'Checkbox', 'Disable', 'Luôn tích', 'STT, Số tài khoản, Hành động: xám, có biểu tượng ổ khóa “Cột bắt buộc — không thể ẩn hoặc đổi vị trí”.'],
                    ['4', 'Biểu tượng ☰', 'Drag handle', 'Enable', 'Hiển thị', 'Kéo thả để đổi thứ tự cột (trừ cột bắt buộc).'],
                    ['5', 'Nút Lưu', 'Button', 'Enable', 'Hiển thị', 'Áp dụng và lưu cấu hình theo từng người dùng.'],
                    ['6', 'Nút Đóng', 'Button', 'Enable', 'Hiển thị', 'Đóng cửa sổ, không lưu.']],
             'ui_widths': [0.5, 1.5, 1.0, 0.8, 1.3, 2.6],
             'events': [['Bấm biểu tượng Cấu hình cột hiển thị', 'Click', 'After:\n– Mở cửa sổ Tuỳ chỉnh cột với cấu hình đang áp dụng.'],
                        ['Tích / bỏ tích, kéo thả cột', 'Change', 'During:\n– Cột bắt buộc không bỏ tích, không kéo được.'],
                        ['Bấm Lưu', 'Click', 'After:\n– Áp ngay bộ cột mới vào bảng, lưu cấu hình theo người dùng trên máy chủ (dùng lại ở lần sau, máy khác).\n– Báo “Cập nhật thành công”; lỗi → “Thao tác thất bại”.\n– Bộ cột này cũng quyết định trường tích sẵn khi Xuất Excel và cột in khi In danh sách.'],
                        ['Bấm Đóng / dấu X', 'Click', 'After:\n– Đóng cửa sổ, trả danh sách cột về cấu hình đang áp dụng.']]},
            {'ten': 'In danh sách tài khoản', 'uc': 'uc_fr12',
             'qtc': 'Quy tắc In. Chỉ bổ sung biểu mẫu và cột in riêng.',
             'gioi_thieu': [['Tên chức năng', 'In danh sách tài khoản'],
                            ['Mô tả', 'Xem trước và in danh sách tài khoản theo bộ lọc đang áp dụng, dùng chung biểu mẫu “Danh sách tài khoản” với cổng cũ.'],
                            ['Tác nhân', 'Người có quyền Quản lý hoặc Xem danh mục tài khoản'],
                            ['Dòng sự kiện chính', '1. Bấm In danh sách.\n2. Hệ thống mở cửa sổ “Xem trước danh sách tài khoản” với letterhead công ty và bảng dữ liệu.\n3. Người dùng bấm In để mở hộp thoại in của trình duyệt.'],
                            ['Dòng sự kiện phụ', '• Không tìm thấy biểu mẫu → “Không tìm thấy mẫu in \"Danh sách tài khoản\"”.'],
                            ['Yêu cầu đặc biệt', 'In mọi dòng khớp bộ lọc. Cột in theo cột đang hiển thị; STT, Số tài khoản, Bậc, Tài khoản mẹ, Người tạo, Người cập nhật luôn in. Tài khoản Cấp 1 in đậm.']],
             'menu_them': ' => In danh sách',
             'ghi_chu_layout': 'Cửa sổ Xem trước bản in được mở ngay trên màn hình danh sách.',
             'anh': [('print', 'Cửa sổ Xem trước danh sách tài khoản')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
                    ['1', 'Nút In danh sách', 'Button', 'Enable', 'Hiển thị', 'Trên thanh công cụ của bảng, hiện với mọi người vào được màn hình. Mở cửa sổ xem trước.'],
                    ['2', 'Tiêu đề cửa sổ', 'Label', 'Read-only', 'Xem trước danh sách tài khoản', ''],
                    ['3', 'Nút In', 'Button', 'Enable / Disable', 'Mờ khi đang tải hoặc không có nội dung', 'Nằm cạnh tiêu đề. Mở hộp thoại in của trình duyệt.'],
                    ['4', 'Dòng đang tải', 'Label', 'Hiển thị', '“Đang tải dữ liệu in…”', 'Hiện trong lúc chờ máy chủ dựng bản in.'],
                    ['5', 'Thông báo lỗi', 'Label', 'Hiển thị có điều kiện', 'Ẩn', '“Không có dữ liệu để in”; “Không tải được dữ liệu in”; “Không tìm thấy mẫu in \"Danh sách tài khoản\"”.'],
                    ['6', 'Tờ giấy xem trước', 'Panel', 'Read-only', 'Khổ A4 dọc', 'Letterhead công ty + tiêu đề biểu mẫu “Danh sách tài khoản” + bảng dữ liệu.'],
                    ['7', 'Bảng in', 'Table/Grid', 'Read-only', 'Theo dữ liệu', 'Luôn in: STT, Số tài khoản, Bậc, Tài khoản mẹ, Người tạo, Người cập nhật. In thêm theo cột đang hiển thị: Tên tài khoản, Loại tài khoản, Theo dõi công nợ (“có”), Trạng thái, Ngày tạo, Ngày cập nhật (dd/mm/yyyy). Tài khoản Cấp 1 in đậm.'],
                    ['8', 'Dấu X', 'Button', 'Enable', 'Hiển thị', 'Đóng cửa sổ.']],
             'ui_widths': [0.5, 1.3, 0.9, 0.9, 1.3, 2.7],
             'events': [['Bấm In danh sách', 'Click', 'During:\n– Gửi bộ lọc, sắp xếp và danh sách cột đang hiển thị; lấy TẤT CẢ dòng khớp bộ lọc, không theo trang.\n– Không tìm thấy biểu mẫu → “Không tìm thấy mẫu in \"Danh sách tài khoản\"”.\nAfter:\n– Mở cửa sổ “Xem trước danh sách tài khoản” với bản in đã dựng sẵn.'],
                        ['Bấm In', 'Click', 'After:\n– Mở hộp thoại in của trình duyệt với đúng nội dung tờ giấy xem trước.'],
                        ['Bấm dấu X', 'Click', 'After:\n– Đóng cửa sổ; danh sách phía sau giữ nguyên bộ lọc và trang.']]},
        ],
        'quy_tac': [
            ('BR-01', 'Quyền và phạm vi dữ liệu',
             ['Tách riêng quyền Xem và quyền Quản lý danh mục tài khoản.',
              'Danh mục dùng chung với cổng cũ, không phân quyền theo công ty/phòng ban.'],
             ['Tất cả chức năng của màn hình']),
            ('BR-02', 'Cấu trúc cây ba bậc',
             ['Cây tài khoản có đúng ba bậc: Cấp 1, Cấp 2, Cấp 3.',
              'Cấp 1 không có tài khoản mẹ; Cấp 2, Cấp 3 bắt buộc có tài khoản mẹ. Thông báo khi thiếu: “Bắt buộc phải chọn tài khoản mẹ với bậc 2 và 3”.',
              'Tài khoản mẹ phải ở đúng bậc liền trên. Thông báo khi sai: “Tài khoản mẹ phải là tài khoản bậc N (tài khoản X đang là bậc M)”.'],
             ['Thêm mới tài khoản', 'Chỉnh sửa tài khoản', 'Import file tài khoản']),
            ('BR-03', 'Số tài khoản con nối tiếp số mẹ',
             ['Số tài khoản con phải bắt đầu bằng số tài khoản mẹ (mẹ 131 thì con 1311, 1312…).',
              'Thông báo khi sai: “Số tài khoản con phải bắt đầu bằng số tài khoản mẹ: mẹ là X thì con phải là X1, X2...”.'],
             ['Thêm mới tài khoản', 'Chỉnh sửa tài khoản', 'Import file tài khoản']),
            ('BR-04', 'Ràng buộc số tài khoản',
             ['Số tài khoản chỉ gồm chữ số, dài 3–15 chữ số; số 0 ở đầu được giữ nguyên. Thông báo khi sai: “Chỉ được nhập chữ số, từ 3 đến 15 chữ số”.',
              'Số tài khoản không được trùng trên toàn hệ thống. Thông báo khi trùng: “Số tài khoản đã tồn tại”.',
              'Tên tài khoản được phép trùng.'],
             ['Thêm mới tài khoản', 'Chỉnh sửa tài khoản', 'Import file tài khoản']),
            ('BR-05', 'Tài khoản đang có tài khoản con',
             ['Tài khoản đang có tài khoản con thì KHÔNG đổi được Số tài khoản và Bậc; các trường khác vẫn sửa được.',
              'Thông báo: “Tài khoản đang có N tài khoản con nên không được đổi số tài khoản / đổi bậc. Hãy chuyển hoặc xóa các tài khoản con trước.”'],
             ['Chỉnh sửa tài khoản']),
            ('BR-06', 'Điều kiện Khóa / Mở khóa / Xóa',
             ['Khóa, Mở khóa, Xóa chỉ dành cho người đã tạo tài khoản; áp dụng cả khi chọn Khóa trong cửa sổ Sửa. Thông báo: “Bạn không có quyền khóa tài khoản này”.',
              'Xóa còn yêu cầu tài khoản không có tài khoản con và chưa từng hạch toán; không đạt thì báo “Không xóa được: tài khoản có tài khoản con, đã phát sinh dữ liệu, hoặc bạn không phải người tạo”.',
              'Khóa tài khoản mẹ không khóa các tài khoản con.'],
             ['Xóa tài khoản', 'Khóa / Mở khóa tài khoản', 'Chỉnh sửa tài khoản']),
            ('BR-07', 'Tài khoản đang Khóa',
             ['Tài khoản đang Khóa không sửa, không xóa được; máy chủ chặn với thông báo “Tài khoản đang bị khoá, vui lòng mở khoá trước khi cập nhật.”',
              'Tài khoản Khóa không còn chọn được khi hạch toán chứng từ mới; chứng từ cũ vẫn hiện đúng tài khoản kèm 🔒.'],
             ['Chỉnh sửa tài khoản', 'Xóa tài khoản', 'Các màn chứng từ có hạch toán']),
            ('BR-08', 'Giới hạn Import',
             ['Mỗi lần nhập tối đa 500 dòng; bước Validate chỉ kiểm tra, không ghi dữ liệu.',
              'Tài khoản mẹ được phép nằm ngay trong cùng file; hệ thống ghi theo thứ tự Cấp 1 → Cấp 2 → Cấp 3.',
              'Tài khoản nhập vào luôn ở trạng thái Hoạt động.'],
             ['Import file tài khoản']),
            ('BR-09', 'Ghi lịch sử thay đổi',
             ['Mọi thay đổi thông tin và đổi trạng thái đều ghi lịch sử kèm người thực hiện.',
              'Xóa tài khoản xóa luôn lịch sử của nó.'],
             ['Chỉnh sửa tài khoản', 'Khóa / Mở khóa tài khoản', 'Xóa tài khoản', 'Xem lịch sử thay đổi']),
        ],
    },

    'loi_code': [
        'Bộ lọc “Loại tài khoản” ở màn danh sách vẫn dùng hằng số cứng Account::TYPES (7 loại, qua API finance/accounts/types) thay vì bảng type_accounts → loại tự tạo thêm (id 8, 9…) không có trong ô lọc nên không lọc được; loại id 6 ô lọc ghi “Tài khoản chi phí khác” trong khi bảng / cột Loại tài khoản ghi “Tài khoản thu nhập khác”. Form Thêm/Sửa và cột bảng thì đã đọc bảng type_accounts.',
        'Cùng gốc lỗi hằng Account::TYPES: (a) bản IN danh sách cột “Loại tài khoản” lấy accessor type_name từ hằng (AccountService::printColumnDefinitions) → loại ngoài hằng in TRỐNG, loại id 6 in sai tên; (b) Lịch sử thay đổi trường Loại tài khoản (Account::displayValue) cũng tra hằng → đổi sang loại ngoài hằng thì lịch sử hiện số id thay vì tên.',
        'Import đánh số dòng lệch 1: thông báo “Số tài khoản bị trùng trong file import (dòng N)” lấy N = thứ tự dòng dữ liệu + 2 (= số hàng Excel), còn cột STT trên bảng xem trước đánh 1, 2, 3… → số dòng trong thông báo lớn hơn 1 so với STT người dùng nhìn thấy.',
        'Nút Xóa vẫn hiện với tài khoản đang Khóa (is_can_delete chỉ xét người tạo / con / hạch toán, không xét trạng thái) — bấm Xóa thì máy chủ trả “Tài khoản đang bị khoá, vui lòng mở khoá trước khi cập nhật.” (middleware recordNotLocked). Áp cho cả cột Hành động lẫn footer trang Chi tiết.',
        'Import tra Loại tài khoản trên toàn bảng type_accounts, KHÔNG loại bỏ loại đang Khóa → qua Import gán được loại đã khóa, trong khi form nhập tay chỉ cho chọn loại Hoạt động. Tương tự tài khoản mẹ đang Khóa vẫn được nhận khi Import (form chỉ liệt kê mẹ đang Hoạt động).',
        'Tạo mới và Import không sinh mốc lịch sử (store()/import() không tạo AccountVersion) → cửa sổ Lịch sử không có mốc Tạo mới; Khóa/Mở khóa ghi action “update” nên hiện là “Thay đổi thông tin” thay vì “Thay đổi trạng thái”.',
        'File mẫu Import là file tĩnh static/Mau_import_tai_khoan.xlsx (không sinh bằng buildImportTemplate): không có cột STT, không có hàng mô tả in nghiêng, không có ô chọn giá trị cho Bậc / Theo dõi công nợ — lệch khuôn file mẫu dùng chung. Dòng ví dụ bậc 1 là 8888 (4 chữ số) trong khi form gợi ý Cấp 1 = 3 chữ số.',
        'Ô Số tài khoản TỰ SỬA giá trị người dùng nhập (AccountFormComponent::sanitizeIdentifyNumber + chặn phím): dán “13A1” thành “131”, dán 20 chữ số bị cắt còn 15 — trái quy tắc chung “không tự sửa giá trị user vừa nhập, phải báo đỏ dưới ô”. Tài liệu đang tả đúng hành vi hiện tại; cần chốt giữ hay sửa.',
        'In danh sách không bao giờ in được cột Trạng thái: FE gửi key cột “accountStatus” (tên cột trên bảng) nhưng định nghĩa cột in bên máy chủ (AccountService::printColumnDefinitions) dùng key “status” → không khớp nên cột bị bỏ dù đang hiển thị trên bảng. Các cột khác khớp key.',
        'FE form: ô Số tài khoản chỉ gắn rule digits_between (không required) → bấm Lưu khi bỏ trống TẤT CẢ các ô thì FE chỉ báo đỏ ô Tên (rule required) rồi dừng, không gọi máy chủ; các ô Số tài khoản / Bậc / Loại chỉ báo “Bắt buộc…” sau khi đã nhập Tên (cần kiểm trên màn hình).',
    ],
}

# ---- Sửa tab testcase "3. DM tài khoản" (đọc từ ref/testcase_tab.txt) ----
_PRE = 'Đăng nhập TK "Quản lý".'
CFG['tc'] = {
    'tab': '3. DM tài khoản',
    'hdr_row': 164,            # "X. LỊCH SỬ THAY ĐỔI"
    'blocks': [
        # Quy tắc Số tài khoản mới — chèn cuối nhóm IX. RÀNG BUỘC NHẬP LIỆU (TC_09.001 hàng 150 … TC_09.014 hàng 163)
        {'after': 163, 'merge_from': 150, 'cases': [
            ('TC_09.015', 'Số tài khoản bắt đầu bằng số 0 được giữ nguyên', 'P1', _PRE,
             '1. Bấm Tạo mới\n2. Nhập Số tài khoản = "009", Bậc = Cấp 1, nhập Tên, chọn Loại\n3. Bấm Lưu, tìm lại số 009 ở danh sách',
             'Số: 009; Tên: DOC-Số có 0 đầu',
             '- Lưu thành công\n- Danh sách hiện ĐÚNG "009" (không bị rút thành 9)\n- Nhập "009" lần nữa thì báo "Số tài khoản đã tồn tại"'),
            ('TC_09.016', 'Tự gợi ý Bậc theo độ dài Số tài khoản khi Thêm mới', 'P1', _PRE,
             '1. Bấm Tạo mới, CHƯA chọn Bậc\n2. Nhập Số tài khoản 3 chữ số, quan sát ô Bậc\n3. Mở trang Tạo mới khác, nhập 4 chữ số; lần thứ ba nhập 5 chữ số',
             'Số: 975; 9751; 97511',
             '- 3 chữ số: ô Bậc tự chọn Cấp 1, ô Tài khoản mẹ khóa với chữ "Tài khoản cấp 1 không có tài khoản mẹ"\n- 4 chữ số: Bậc tự chọn Cấp 2, ô Tài khoản mẹ mở ra, chỉ liệt kê tài khoản Cấp 1 có số là phần đầu của số vừa nhập\n- 5 chữ số: Bậc tự chọn Cấp 3\n- Nếu đã chọn Bậc trước khi gõ số thì Bậc giữ nguyên'),
        ]},
    ],
    'edits': [
        # --- Quy tắc Số tài khoản (mã) ---
        ('I101', '- Ô Tài khoản mẹ báo đỏ "Số tài khoản con phải bắt đầu bằng số tài khoản mẹ: mẹ là 991 thì con phải là 9911, 9912..."\n- Không tạo bản ghi'),
        ('G104', '1. Bấm Sửa dòng 991\n2. Quan sát ô Số tài khoản, ô Bậc tài khoản và dòng ghi chú bên dưới\n3. Thử sửa ô Số tài khoản'),
        ('I104', '- Ô Số tài khoản và ô Bậc tài khoản bị khóa, không sửa được\n- Dưới ô có ghi chú "%s"\n- Tên, Loại tài khoản, Theo dõi công nợ vẫn sửa được' % MSG_CON),
        ('G151', '1. Bấm Tạo mới\n2. Gõ "13A1" vào ô Số tài khoản\n3. Xoá ô, dán (Ctrl+V) chuỗi "13A1" vào ô'),
        ('I151', '- Khi gõ: chữ A không lên ô, ô chỉ còn "131"\n- Khi dán: hệ thống tự bỏ chữ cái, ô còn "131"\n- Không có cách nào lưu Số tài khoản chứa chữ cái'),
        ('G152', '1. Bấm Tạo mới\n2. Gõ "131.1" vào ô Số tài khoản\n3. Quan sát giá trị trong ô'),
        ('I152', '- Dấu chấm không lên ô, ô chỉ còn "1311"\n- Không lưu được Số tài khoản có dấu chấm'),
        ('I153', '- Ô Số tài khoản báo đỏ ngay khi gõ "Chỉ được nhập chữ số, từ 3 đến 15 chữ số"\n- Bấm Lưu: không lưu'),
        ('I155', '- Ô chỉ nhận tối đa 15 chữ số, gõ thêm không lên\n- Dán chuỗi 20 chữ số thì ô chỉ giữ 15 chữ số đầu'),
        ('G163', '1. Bấm Tạo mới\n2. Gõ " 983 " (có khoảng trắng hai đầu) vào ô Số tài khoản\n3. Nhập các ô còn lại, bấm Lưu và xem danh sách'),
        ('I163', '- Ô Số tài khoản không nhận khoảng trắng, chỉ còn "983"\n- Danh sách hiện số 983 không có khoảng trắng thừa'),
        # --- Xuất Excel ---
        ('G136', '1. Không lọc gì\n2. Bấm Xuất Excel\n3. Trong cửa sổ "Chọn trường xuất file", giữ nguyên các trường đã tích, bấm Xuất file\n4. Mở file tải về'),
        ('I136', '- Thông báo "Xuất Excel thành công"\n- Tải về file danh_muc_tai_khoan.xlsx, mở được\n- File có tiêu đề "Danh mục tài khoản", số dòng dữ liệu bằng tổng số bản ghi ở cuối bảng'),
        ('G137', '1. Bấm Xuất Excel\n2. Đọc danh sách trường trong cửa sổ "Chọn trường xuất file"\n3. Bấm Xuất file, đối chiếu tiêu đề cột với bảng trên màn hình'),
        ('I137', '- Cửa sổ có đủ 8 trường: Số tài khoản, Tên tài khoản, Tài khoản mẹ, Bậc, Loại tài khoản, Trạng thái, Người tạo, Ngày tạo\n- Tích sẵn đúng các cột đang hiển thị trên bảng (mặc định: Số tài khoản, Tên tài khoản, Người tạo, Ngày tạo, Trạng thái)\n- File có cột STT đầu tiên, tiếp theo đúng các trường đã tích theo thứ tự trong cửa sổ, tiêu đề cột bằng tiếng Việt'),
        ('G138', '1. Lọc Bậc tài khoản = Cấp 3\n2. Bấm Xuất Excel → Xuất file\n3. Mở file'),
        ('H138', 'Bậc: Cấp 3'),
        ('I138', '- File chỉ chứa các tài khoản bậc 3, số dòng bằng tổng ở cuối bảng'),
        ('G139', '1. Đứng ở trang 1 với cỡ trang 10\n2. Bấm Xuất Excel → Xuất file\n3. Đếm số dòng trong file'),
        ('I139', '- File chứa TOÀN BỘ kết quả khớp bộ lọc (bằng tổng ở cuối bảng), không phải 10 dòng của trang đang xem'),
        # --- Import ---
        ('I140', '- Tải về file Mau_import_tai_khoan.xlsx\n- Hàng 1 là tiêu đề 6 cột: Số tài khoản *, Tên tài khoản *, Bậc *, Tài khoản mẹ, Loại tài khoản *, Theo dõi công nợ (cột bắt buộc có dấu * sau tên)\n- Từ hàng 2 là 3 dòng ví dụ (8888 bậc 1, 88881 bậc 2, 888811 bậc 3)'),
        ('G141', '1. Bấm Import Excel\n2. Bấm Chọn file Excel, chọn file 3 dòng có số tài khoản mới và đúng cây\n3. Bấm Load lên bảng, kiểm tra bảng xem trước\n4. Bấm Validate\n5. Bấm Import'),
        ('H141', '3 dòng: 981 (Bậc 1, Loại TKTS), 9811 (Bậc 2, mẹ 981, Loại TKTS), 98111 (Bậc 3, mẹ 9811, Loại Tài khoản tài sản)'),
        ('I141', '- Sau Load: bảng xem trước hiện đủ 3 dòng, ô Tổng = 3\n- Sau Validate: báo "Validate thành công", cả 3 dòng hợp lệ và bị khoá\n- Sau Import: báo "Import thành công 3 tài khoản.", cửa sổ đóng; danh sách có 3 tài khoản mới ở trạng thái Hoạt động, con nằm ngay dưới mẹ'),
        ('G142', '1. Chọn file có 1 dòng bậc 2 nhưng số không bắt đầu bằng số mẹ, bấm Load lên bảng\n2. Bấm Validate, đọc thông báo dưới dòng lỗi'),
        ('I142', '- Dòng đó tô nền đỏ, báo "Số tài khoản con phải bắt đầu bằng số tài khoản mẹ: mẹ là 981 thì con phải là 9811, 9812..."\n- Nút Import không bấm được cho tới khi sửa dòng lỗi hoặc bấm Bỏ dòng lỗi; chỉ dòng hợp lệ mới được ghi vào'),
        ('G143', '1. Chọn file có 1 dòng mang số tài khoản đã tồn tại, bấm Load lên bảng\n2. Bấm Validate'),
        ('I143', '- Dòng đó báo "Số tài khoản đã tồn tại trong hệ thống"\n- Không tạo bản ghi trùng'),
        ('I144', '- Báo "Vui lòng chọn file .xlsx hoặc .xls", không nạp dữ liệu, không lỗi trắng trang'),
        ('G145', '1. Chọn file có cả dòng hợp lệ và dòng lỗi, bấm Load lên bảng\n2. Bấm Validate\n3. Quan sát bảng xem trước'),
        ('I145', '- Báo "Validate xong: 3 hợp lệ, 2 không hợp lệ" và dải thông báo "Validate xong: 3 hợp lệ, 2 không hợp lệ. (Dòng hợp lệ đã bị khoá, chỉ có thể sửa dòng lỗi)"\n- Dòng hợp lệ bị khoá, không sửa được; dòng lỗi vẫn cho sửa tại chỗ rồi Validate lại\n- Phần mô tả dưới tiêu đề cửa sổ ghi "Import từ Excel • Validate xong dòng hợp lệ sẽ bị khoá"'),
    ],
    'clear_k': [101, 104, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 151, 152, 153, 155, 163],
}

CFG['tc_ngoai_pham_vi'] = [
    'B3/B10 + TC_01.001 (hàng 33) + TC_01.002 (hàng 34): còn ghi 11 cột với 3 cột Cấp 1/Cấp 2/Cấp 3 — nay bảng có cột Số tài khoản (định danh, bấm vào mở trang Chi tiết), các cột Bậc, Tài khoản mẹ, Loại tài khoản, Theo dõi công nợ, Người cập nhật, Ngày cập nhật mặc định ẩn; nút đặt ở đầu bảng gồm Tạo mới, In danh sách, Xuất Excel, Import Excel, Cấu hình cột.',
    'B10 + TC-ROLE-01/02 (hàng 19-20) + TC_01.007 (hàng 39) + TC_06.001/003/008 (hàng 110/112/117): còn ghi nút Khóa/Mở khóa nằm TRONG cột Trạng thái, nút "bị mờ / rê chuột đọc lý do" — nay Khóa/Mở khóa ở cột Hành động (trong nút ba chấm) và bị ẨN hẳn khi không đủ điều kiện; cột Hành động có thêm nút Lịch sử (tên "Lịch sử", không phải "Lịch sử chỉnh sửa").',
    'TC_04.011 (hàng 88) "Nút Sửa bị vô hiệu", TC_07.003/004/005 (hàng 123-125) "Nút Xóa bị mờ, rê chuột hiện chú thích", TC_07.008 (hàng 128): nay nút bị ẨN hẳn, không có chú thích.',
    'TC_03.006 (hàng 71) "Bấm Xem một dòng rồi Đóng", TC_04.012 (hàng 89) "Bấm Sửa để xem chi tiết": nay có trang Chi tiết riêng (bấm Số tài khoản), cuối trang có Sửa / Xóa / Khóa-Mở khóa / Quay lại và khối Lịch sử.',
    'TC_04.001 (hàng 78): trang Thêm mới nay chỉ có MỘT khối "Thông tin chung" (không còn 2 khối "Vị trí trong hệ thống tài khoản" / "Thông tin tài khoản"), không còn dòng nhắc dưới ô Số tài khoản; nút là Lưu, Lưu và tiếp tục, Quay lại (ở cuối trang). "Lưu và tiếp tục" giữ lại Bậc + Tài khoản mẹ.',
    'TC_05.007 (hàng 103) đổi Bậc tài khoản đang có con: nay ô Bậc bị KHÓA sẵn kèm ghi chú (không còn bước bấm Lưu rồi mới báo lỗi).',
    'TC_02.001 (hàng 46) "Kết quả gồm các tài khoản có số CHỨA 1311": thực tế Số tài khoản tìm theo PHẦN ĐẦU (131 ra 1311, nhưng 311 không ra 1311). TC_02.006/007: ô lọc Bậc hiển thị "Cấp 1/2/3". TC_02.008: ô lọc Loại tài khoản lấy từ hằng số cứng (xem loi_code).',
    'TC_09.001 (hàng 150) bỏ trống tất cả: FE chỉ báo đỏ ô Tên rồi dừng, các ô khác chỉ báo sau khi đã nhập Tên (xem loi_code) — cần chốt expected.',
    'TC_09.010 (hàng 159) Tên > 255 ký tự: câu lỗi thực tế là "Vui lòng nhập tối đa 255 ký tự." (báo ngay khi gõ), không phải "Tối đa 255 ký tự".',
    'TC_08.001-004 (hàng 132-135) In danh sách: nay mở cửa sổ "Xem trước danh sách tài khoản" ngay trên màn (không mở thẻ mới), bản in có cột Số tài khoản + Bậc thay cho 3 cột Cấp.',
    'TC_10.003 (hàng 167) bộ lọc Loại hành động có "Thay đổi trạng thái": với màn này Khóa/Mở khóa ghi là "Thay đổi thông tin", Tạo mới không sinh mốc (xem loi_code) → case TC_10.003 / TC_10.011 có thể lệch thực tế.',
    'Chưa có case Import cho: bỏ trống Tên / Bậc / Loại, "Không tìm thấy tài khoản mẹ", "Tài khoản mẹ phải là tài khoản bậc N", "Không tìm thấy loại tài khoản", "Theo dõi công nợ chỉ nhận…", trùng số trong file (dòng N), vượt 500 dòng, nút Bỏ dòng lỗi (theo quy tắc không thêm case Import khi tab đã có nhóm Import).',
]
