# -*- coding: utf-8 -*-
# Cấu hình tài liệu màn Danh mục tài khoản ngân hàng (tài khoản ngân hàng CỦA CÔNG TY).
# Nguồn: code gop_db 25/09/2026 — FE pages/finance/account-banks/index.vue + AccountBankModal.vue;
# BE Modules/Finance CompanyAccountController / CompanyAccountService / CompanyAccountRequest / Entity CompanyAccount,
# ExportColumnRegistry['company_accounts'], route checkPermission 'Quản lý danh mục tài khoản ngân hàng'.
# Không ghi URL. Chữ UI / message lấy nguyên văn code.

DT = 'tài khoản ngân hàng'
Q = 'Quản lý danh mục tài khoản ngân hàng'

_FR = ['FR-01 Xem danh sách tài khoản ngân hàng', 'FR-02 Tìm kiếm và lọc', 'FR-03 Thêm mới tài khoản ngân hàng',
       'FR-04 Chỉnh sửa tài khoản ngân hàng', 'FR-06 Khóa / Mở khóa tài khoản ngân hàng', 'FR-07 Xem lịch sử thay đổi',
       'FR-08 Import file tài khoản ngân hàng', 'FR-09 Xuất danh sách ra Excel', 'FR-10 Xem chi tiết tài khoản ngân hàng',
       'FR-11 Tùy chỉnh cột hiển thị']

CFG = {
    'slug': 'account-banks',
    'ten': 'Danh mục tài khoản ngân hàng',
    'doi_tuong': DT,
    'file_hdsd': 'HDSD_Danh muc tai khoan ngan hang.docx',
    'file_srs': 'SRS - Danh mục tài khoản ngân hàng.docx',
    'menu': [('Tài chính', 'menu_phanhe'), ('Danh mục', 'menu_nhom'), ('Danh mục tài khoản ngân hàng', 'menu_muc')],
    'form_type': 'popup',

    'thuat_ngu': [
        ['Tài khoản ngân hàng của công ty', 'Một dòng trong danh mục: số tài khoản, chủ tài khoản, ngân hàng, chi nhánh, loại tiền tệ. Đây là tài khoản của CÔNG TY, không phải tài khoản cá nhân của nhân viên.'],
        ['Chủ tài khoản', 'Tên chủ tài khoản in trên sổ/thẻ ngân hàng. Hệ thống tự chuyển thành CHỮ IN HOA khi lưu.'],
        ['Ngân hàng / Chi nhánh', 'Lấy từ Danh mục ngân hàng (phân hệ Danh mục). Chi nhánh phải thuộc đúng ngân hàng đã chọn.'],
        ['Loại tiền tệ', 'Lấy từ Danh mục tiền tệ (phân hệ Tài chính), hiển thị dạng “Mã — Tên”.'],
        ['Phạm vi công ty', 'Mỗi người chỉ thấy và thao tác trên tài khoản ngân hàng thuộc công ty ghi trong hồ sơ nhân sự của mình.'],
        ['Trạng thái Hoạt động', 'Tài khoản dùng bình thường, sửa được.'],
        ['Trạng thái Khóa', 'Tài khoản ngừng sử dụng nhưng KHÔNG bị xóa; khi đang khóa thì không sửa được.'],
    ],
    'phien_ban': [
        ['1.0', '17/08/2026', 'Đội phát triển phần mềm', 'Tạo mới cho màn Danh mục tài khoản ngân hàng sau khi chuyển màn từ phần mềm cũ sang phân hệ Tài chính.'],
        ['1.1', '25/09/2026', 'Đội phát triển phần mềm', 'Cập nhật theo phiên bản hiện tại: bổ sung Xuất Excel, Import Excel, nút Lưu và tiếp tục, cảnh báo thông tin chưa lưu, giữ ngân hàng/tiền tệ đã khóa kèm biểu tượng 🔒; trình bày theo mẫu tài liệu danh mục chung.'],
    ],
    'muc_dich': [
        'Danh mục tài khoản ngân hàng là nơi khai báo các tài khoản ngân hàng CỦA CÔNG TY: số tài khoản, chủ tài khoản, ngân hàng, chi nhánh và loại tiền tệ.',
        'Dữ liệu ở đây được dùng lại ở các nghiệp vụ thu chi, đề nghị thanh toán và các chứng từ cần chọn tài khoản nhận / chuyển tiền của công ty, nên khai báo sai sẽ kéo theo sai ở chứng từ. Mỗi người chỉ nhìn thấy tài khoản của công ty mình.',
    ],
    'quyen': {
        'truoc': ['Màn hình dùng đúng MỘT quyền cho mọi thao tác, kể cả xem danh sách:'],
        'rows': [[Q, 'Thấy mục menu, xem danh sách, tìm kiếm, tạo mới, sửa, khóa / mở khóa, xem chi tiết, xem lịch sử, Import Excel và Xuất Excel.']],
        'sau': ['Thiếu quyền thì mục menu bị ẩn và mở trực tiếp màn hình cũng bị từ chối. Ngoài quyền, dữ liệu còn giới hạn theo CÔNG TY của người đăng nhập: tài khoản của công ty khác không hiển thị, tìm kiếm không ra, mở trực tiếp báo “Không tìm thấy tài khoản ngân hàng”.'],
    },

    'danh_sach': {
        'mo_ta_vao': 'Hệ thống hiển thị bảng “Danh sách tài khoản ngân hàng” của công ty người đăng nhập, mặc định 10 dòng mỗi trang, mới tạo nhất ở trên cùng.',
        'bo_cuc': [
            'Khu vực tìm kiếm và lọc — ô tìm kiếm nhanh, ô Chi nhánh, ô Trạng thái, nút Tìm kiếm và Làm mới.',
            'Thanh công cụ — nút Tạo mới, nút Xuất Excel, nút Import Excel và biểu tượng Cấu hình cột hiển thị.',
            'Bảng danh sách — các cột thông tin, cột Hành động ở cuối, và phân trang bên dưới.',
        ],
        'cot': [
            ['STT', 'Số thứ tự, chạy liên tục qua các trang. Luôn hiển thị.'],
            ['Số tài khoản', 'Luôn hiển thị, sắp xếp được. Bấm vào số tài khoản để mở cửa sổ Xem tài khoản ngân hàng.'],
            ['Chủ tài khoản', 'Luôn là CHỮ IN HOA. Sắp xếp được.'],
            ['Ngân hàng', 'Tên ngân hàng, đọc trực tiếp từ Danh mục ngân hàng (đổi tên ở danh mục thì cột này đổi theo).'],
            ['Loại tiền tệ', 'Mã loại tiền tệ, ví dụ VNĐ, USD. Mặc định ẩn.'],
            ['Chi nhánh', 'Tên chi nhánh ngân hàng. Mặc định ẩn.'],
            ['Người cập nhật', 'Người sửa bản ghi gần nhất. Mặc định ẩn.'],
            ['Ngày cập nhật', 'Thời điểm sửa gần nhất, dạng dd/mm/yyyy hh:mm. Mặc định ẩn, sắp xếp được.'],
            ['Người tạo', 'Người đã thêm bản ghi.'],
            ['Ngày tạo', 'Thời điểm thêm, dạng dd/mm/yyyy hh:mm, sắp xếp được.'],
            ['Trạng thái', 'Nhãn Hoạt động hoặc Khóa.'],
            ['Hành động', 'Các nút thao tác của dòng (xem mục 4).'],
        ],
        'hanh_dong': {
            'intro': 'Trên mỗi dòng, cột Hành động có tối đa 3 nút, hiện thẳng ra (không có nút ba chấm):',
            'bullets': [
                'Biểu tượng bút chì {icon:btn_sua} — mở cửa sổ Sửa tài khoản ngân hàng. Chỉ hiện khi tài khoản đang Hoạt động.',
                'Khóa / Mở khóa — đổi trạng thái tài khoản.',
                'Lịch sử — mở cửa sổ Lịch sử thay đổi.',
            ],
            'anh': 'Các nút ở cột Hành động của một tài khoản ngân hàng',
            'luu_y': ['Màn hình KHÔNG có nút Xóa — tài khoản không dùng nữa thì Khóa lại. Tài khoản ĐÃ KHÓA chỉ còn Mở khóa và Lịch sử; muốn sửa phải Mở khóa trước.'],
        },
        'phan_trang': [
            'Cuối bảng có dòng “Hiển thị a–b / N”: N là tổng số tài khoản khớp bộ lọc trong công ty của người đăng nhập.',
            'Ô Số dòng/trang có các mức 5, 10, 20, 50, 100 (mặc định 10). Đổi số dòng thì hệ thống tự quay về trang 1.',
            'Các cột sắp xếp được: Số tài khoản, Chủ tài khoản, Ngày tạo, Ngày cập nhật. Bấm tiêu đề cột để sắp xếp, bấm lần hai để đảo chiều. Thứ tự sắp xếp được giữ nguyên khi chuyển trang.',
        ],
    },

    'loc': {
        'buoc2': 'Bước 2: Nhập chữ vào ô tìm kiếm nhanh, ô Chi nhánh hoặc chọn giá trị ở ô Trạng thái.',
        'rows': [
            ['Ô tìm kiếm nhanh', 'Placeholder “Tìm theo số tài khoản, chủ tài khoản, ngân hàng”. Khớp một phần, không phân biệt hoa thường. Nhấn Enter hoặc bấm Tìm kiếm để lọc.'],
            ['Chi nhánh', 'Nhập một phần tên chi nhánh. Lọc ngay khi thay đổi.'],
            ['Trạng thái', 'Hoạt động hoặc Khóa. Bỏ trống thì hiện cả hai trạng thái. Lọc ngay khi chọn.'],
        ],
        'ap_dung': [
            'Các tiêu chí kết hợp với nhau theo kiểu VÀ — chỉ bản ghi thỏa đồng thời tất cả các tiêu chí mới hiện ra. Mỗi lần đổi tiêu chí, danh sách quay về trang 1.',
            'Bấm {icon:btn_lammoi} để xóa toàn bộ tiêu chí; danh sách nạp lại đầy đủ ngay lập tức.',
            'Hệ thống ghi nhớ bộ lọc trong 10 phút khi rời màn rồi quay lại.',
        ],
        'anh_ket_qua': 'Kết quả tìm nhanh theo số tài khoản / chủ tài khoản / ngân hàng',
    },

    'form': {
        'kieu': 'popup',
        'buoc_tao': [
            'Bước 1: Truy cập vào màn hình Danh mục tài khoản ngân hàng.',
            'Bước 2: Bấm {icon:btn_taomoi}. Hệ thống mở cửa sổ “Tạo tài khoản ngân hàng”.',
            'Bước 3: Nhập/ chọn thông tin: Số tài khoản, Loại tiền tệ, Chủ tài khoản, Ngân hàng, Chi nhánh (bắt buộc) và Trạng thái. Chọn Ngân hàng TRƯỚC rồi mới chọn Chi nhánh.',
            'Bước 4: Bấm {icon:btn_luu} để lưu và đóng cửa sổ, hoặc {icon:btn_luutieptuc} để lưu rồi nhập tiếp tài khoản khác.',
        ],
        'anh_tao': 'Cửa sổ Tạo tài khoản ngân hàng',
        'truong': [
            ['Số tài khoản', 'Ô nhập giá trị', 'Có', 'Trống', 'Placeholder “Nhập số tài khoản”. Không được trùng với bất kỳ tài khoản nào trên TOÀN HỆ THỐNG, kể cả của công ty khác; trùng báo “Số tài khoản đã tồn tại”.'],
            ['Loại tiền tệ', 'Ô chọn giá trị', 'Có', 'Trống', 'Dạng “Mã — Tên”, ví dụ “VNĐ — VNĐ”. Chỉ liệt kê loại tiền tệ đang Hoạt động.'],
            ['Chủ tài khoản', 'Ô nhập giá trị', 'Có', 'Trống', 'Placeholder “Hệ thống tự chuyển thành CHỮ IN HOA khi lưu”. Bỏ trống báo “Bắt buộc phải nhập” ngay khi bấm Lưu.'],
            ['Ngân hàng', 'Ô chọn giá trị', 'Có', 'Trống', 'Chỉ liệt kê ngân hàng đang Hoạt động.'],
            ['Chi nhánh', 'Ô chọn giá trị', 'Có', 'Trống', 'Bị khoá cho tới khi chọn Ngân hàng; chỉ liệt kê chi nhánh của ngân hàng đã chọn. Đổi ngân hàng thì ô Chi nhánh tự xoá trắng.'],
            ['Trạng thái', 'Ô chọn giá trị', 'Có', 'Hoạt động', 'Chỉ chọn 1 trong 2 giá trị: Hoạt động / Khóa. Không xoá trắng được.'],
        ],
        'sau_truong': ['Công ty, Người tạo và Ngày tạo do hệ thống tự ghi theo người đăng nhập, không có ô nhập.'],
        'nut': [
            ['Lưu', 'Ghi bản ghi rồi đóng cửa sổ, báo “Thêm mới thành công” (hoặc “Cập nhật thành công” khi sửa) và nạp lại danh sách.'],
            ['Lưu và tiếp tục', 'Ghi bản ghi nhưng GIỮ cửa sổ mở và xóa trắng các ô để nhập tiếp. Chỉ có khi Tạo mới.'],
            ['Đóng', 'Đóng cửa sổ, không ghi gì. Nếu đã nhập dở, hệ thống hỏi “Thông tin chưa lưu” — “Bạn có thông tin chưa lưu. Có chắc chắn muốn thoát?” (Thoát / Ở lại).'],
        ],
        'loi': [
            ['Bắt buộc phải nhập', 'Chưa nhập Chủ tài khoản (báo ngay), hoặc chưa nhập/chọn Số tài khoản, Loại tiền tệ, Ngân hàng, Chi nhánh (báo sau khi hệ thống kiểm tra).'],
            ['Số tài khoản đã tồn tại', 'Đã có tài khoản khác dùng số này trên toàn hệ thống, kể cả tài khoản của công ty khác mà Người dùng không nhìn thấy.'],
            ['Ngân hàng không tồn tại hoặc đã bị khóa', 'Ngân hàng vừa bị khóa ở Danh mục ngân hàng. Chọn ngân hàng khác hoặc đề nghị mở khóa.'],
            ['Chi nhánh không thuộc ngân hàng đã chọn hoặc đã bị khóa', 'Chi nhánh và ngân hàng không khớp nhau, hoặc chi nhánh vừa bị khóa. Chọn lại Ngân hàng rồi chọn Chi nhánh.'],
            ['Loại tiền tệ không tồn tại hoặc đã bị khóa', 'Loại tiền tệ vừa bị khóa ở Danh mục tiền tệ. Chọn loại khác.'],
            ['Tài khoản đăng nhập chưa gắn công ty, không thể thao tác', 'Hồ sơ nhân sự của Người dùng chưa gắn công ty. Báo bộ phận nhân sự bổ sung rồi đăng nhập lại.'],
        ],
    },

    'sua': {
        'buoc': [
            'Bước 1: Truy cập vào màn hình Danh mục tài khoản ngân hàng.',
            'Bước 2: Bấm nút {icon:btn_sua} ở cột Hành động của tài khoản cần sửa.',
            'Bước 3: Hệ thống hiển thị cửa sổ “Sửa tài khoản ngân hàng” với dữ liệu hiện tại.',
            'Bước 4: Cập nhật các thông tin cần sửa (quy tắc nhập như Thêm mới).',
            'Bước 5: Bấm {icon:btn_luu} để xác nhận thay đổi hoặc Đóng nếu muốn hủy.',
        ],
        'anh': 'Cửa sổ Sửa tài khoản ngân hàng',
        'ghi_chu': [
            'Giữ nguyên số tài khoản của chính bản ghi đang sửa thì không bị báo trùng.',
            'Nếu ngân hàng hoặc loại tiền tệ của tài khoản đã bị khóa ở danh mục gốc, ô đó VẪN giữ đúng giá trị cũ kèm biểu tượng 🔒 và lưu lại được bình thường; chỉ không chọn MỚI được ngân hàng / tiền tệ đã khóa.',
            'Đổi Trạng thái sang Khóa ngay trong cửa sổ Sửa có tác dụng như nút Khóa ngoài danh sách.',
            'Tài khoản đang Khóa không có nút Sửa. Nếu tài khoản vừa bị người khác khóa sau khi mở cửa sổ Sửa, bấm Lưu sẽ nhận thông báo “Tài khoản ngân hàng đang bị khoá, vui lòng mở khoá trước khi cập nhật.”',
        ],
    },
    'xoa': None,
    'khoa': {
        'y_nghia': [
            'Bản ghi VẪN nằm trong danh sách, cột Trạng thái hiện chữ Khóa.',
            'Vẫn xem được chi tiết và lịch sử thay đổi của bản ghi.',
            'Nút Sửa của dòng đó biến mất cho tới khi Mở khóa.',
        ],
        'buoc_khoa': [
            'Bước 1: Ở cột Hành động, Người dùng chọn Khóa.',
            'Bước 2: Hệ thống hiện hộp “Xác nhận khóa” — “Bạn có chắc muốn khóa tài khoản \'…\'?”. Bấm Khóa để xác nhận; hệ thống báo “Khóa thành công”, cột Trạng thái đổi thành Khóa. Bấm Hủy nếu bấm nhầm.',
        ],
        'buoc_mo': [
            'Bước 1: Ở cột Hành động của tài khoản đang Khóa, Người dùng chọn Mở khóa.',
            'Bước 2: Bấm Mở khóa trong hộp “Xác nhận mở khóa”. Hệ thống báo “Mở khóa thành công”, cột Trạng thái đổi thành Hoạt động. Bấm Hủy nếu bấm nhầm.',
        ],
        'ghi_chu': ['Nếu bản ghi không còn (hoặc thuộc công ty khác), hệ thống báo “Dữ liệu đã thay đổi, vui lòng tải lại”.'],
    },
    'lich_su': {
        'buoc': [
            'Xem từ màn danh sách: ở cột Hành động, Người dùng chọn Lịch sử.',
            'Xem từ màn chi tiết: bấm vào số tài khoản để mở cửa sổ Xem tài khoản ngân hàng, khối Lịch sử nằm ở cuối cửa sổ.',
        ],
        'ghi_chu': ['Cửa sổ có bộ lọc riêng (loại hành động, người thực hiện, khoảng thời gian). Các trường được theo dõi: Số tài khoản, Chủ tài khoản, Ngân hàng, Chi nhánh, Loại tiền tệ, Trạng thái.'],
    },
    'chi_tiet': {
        'buoc': ['Bước 1: Truy cập vào màn hình Danh mục tài khoản ngân hàng.',
                 'Bước 2: Bấm vào số tài khoản ở cột Số tài khoản. Hệ thống mở cửa sổ “Xem tài khoản ngân hàng”.'],
        'ghi_chu': ['Cửa sổ hiển thị toàn bộ thông tin ở chế độ chỉ đọc (không có nút Lưu), kèm khối Lịch sử ở cuối. Ngân hàng / tiền tệ đã khóa vẫn hiện đúng tên kèm 🔒. Tài khoản đang Khóa vẫn xem được bình thường.'],
    },
    'xuat': {
        'buoc': [
            'Bước 1: Lọc danh sách theo đúng dữ liệu cần lấy (xem PHẦN 2). File xuất ra chạy theo đúng bộ lọc đang áp dụng.',
            'Bước 2: Bấm nút {icon:btn_xuatexcel}. Hệ thống mở cửa sổ “Chọn trường xuất file”.',
            'Bước 3: Tích chọn, kéo biểu tượng ☰ để đổi vị trí các trường cần xuất. Mặc định hệ thống tích sẵn đúng những cột đang hiển thị trên bảng.',
            'Bước 4: Bấm {icon:btn_xuatfile}. Hệ thống tải về file danh_muc_tai_khoan_ngan_hang.xlsx và báo “Xuất Excel thành công”.',
        ],
        'truong': 'Chọn nhiều trường: Số tài khoản, Chủ tài khoản, Ngân hàng, Chi nhánh, Loại tiền tệ, Trạng thái, Người tạo, Ngày tạo, Người cập nhật, Ngày cập nhật.',
        'ghi_chu': ['Lưu ý: file xuất chứa TOÀN BỘ kết quả của bộ lọc trong công ty của Người dùng (tối đa 10,000 dòng), không chỉ các dòng của trang đang xem.'],
    },
    'import': {
        'tieu_de': 'Import tài khoản ngân hàng',
        'file': 'Mau_import_tai_khoan_ngan_hang.xlsx',
        'cot_text': 'Số tài khoản (bắt buộc), Chủ tài khoản (bắt buộc), Mã ngân hàng (bắt buộc), Chi nhánh (bắt buộc, ghi tên chi nhánh thuộc ngân hàng đó), Mã tiền tệ (bắt buộc), Trạng thái (chọn Hoạt động / Khóa trong danh sách sổ xuống; bỏ trống = Hoạt động)',
        'toast': 'Import thành công N tài khoản ngân hàng.',
        'loi': [
            ['Số tài khoản không được để trống', 'Dòng đó bỏ trống cột Số tài khoản.'],
            ['Số tài khoản bị trùng với dòng N trong file', 'Trong chính file có hai dòng cùng số tài khoản.'],
            ['Số tài khoản đã tồn tại trong hệ thống', 'Số tài khoản đã có trên hệ thống (kể cả của công ty khác).'],
            ['Chủ tài khoản không được để trống', 'Dòng đó bỏ trống cột Chủ tài khoản.'],
            ['Mã ngân hàng không được để trống', 'Dòng đó bỏ trống cột Mã ngân hàng.'],
            ['Không tìm thấy ngân hàng: X', 'Mã ngân hàng ghi sai, không có trong Danh mục ngân hàng.'],
            ['Chi nhánh không được để trống', 'Dòng đó bỏ trống cột Chi nhánh.'],
            ['Không tìm thấy chi nhánh "X" thuộc ngân hàng Y', 'Tên chi nhánh không có, hoặc không thuộc ngân hàng đã ghi.'],
            ['Mã tiền tệ không được để trống', 'Dòng đó bỏ trống cột Mã tiền tệ.'],
            ['Không tìm thấy tiền tệ: X', 'Mã tiền tệ ghi sai, không có trong Danh mục tiền tệ.'],
            ['Trạng thái chỉ nhận "Hoạt động" hoặc "Khóa"', 'Cột Trạng thái ghi giá trị khác hai giá trị trên.'],
        ],
        'ghi_chu': [
            'Lưu ý: tài khoản nhập từ Excel thuộc công ty của người thực hiện nhập; Chủ tài khoản được tự chuyển thành CHỮ IN HOA; Mã ngân hàng và Mã tiền tệ không phân biệt hoa thường. Hệ thống KHÔNG tự tạo ngân hàng / chi nhánh / tiền tệ mới khi tra không thấy.',
            'Mỗi lần nhập tối đa 500 dòng; file dài hơn hệ thống báo “File có X dòng dữ liệu, vượt quá giới hạn 500 dòng mỗi lần import. Vui lòng tách file và import nhiều lần.”',
        ],
    },
    'tuy_chinh_cot': {'cot_khoa': 'Ba cột STT, Số tài khoản và Hành động'},

    'shots': {'list': '01_list.png', 'rowmenu': '03_rowmenu.png', 'filter': 'filter.png', 'filter_result': '04_filter_result.png',
              'create': '10_create.png', 'create_error': '11_create_error.png', 'edit': '12_edit.png',
              'lock': '14_lock.png', 'unlock': '15_unlock.png', 'history': '16_history.png',
              'detail': '17_detail.png', 'export': '20_export.png', 'import_open': '21_import_open.png',
              'import_loaded': '22_import_loaded.png', 'import_validated': '23_import_validated.png', 'colcfg': '25_colcfg.png'},

    'capture': {'route': '/finance/account-banks',
                'menu': {'phanhe': 'TÀI CHÍNH', 'nhom': 'Danh mục', 'muc': 'Danh mục tài khoản ngân hàng'},
                'search': 'Tìm theo số tài khoản', 'searchText': 'TÂN PHÁT', 'detailCol': 1,
                'lockName': '88838888', 'create': True, 'lock': True},

    'import_test': {
        # File mẫu sinh bằng buildImportTemplate: cột A = STT, cột bắt buộc có hậu tố ' *'
        'cols': ['STT', 'Số tài khoản *', 'Chủ tài khoản *', 'Mã ngân hàng *', 'Chi nhánh *', 'Mã tiền tệ *', 'Trạng thái'],
        'rows': [
            [1, 'DOC-0001', 'DOC-Công ty kiểm thử 01', 'VIETCOMBANK', 'Hoàn Kiếm', 'VNĐ', 'Hoạt động'],
            [2, 'DOC-0002', 'DOC-Công ty kiểm thử 02', 'mb', 'Long Biên', 'usd', ''],
            [3, 'DOC-0003', 'DOC-Công ty kiểm thử 03', 'BIDV', 'Sở giao dịch số 3', 'VNĐ', 'Khóa'],
            [4, '', 'DOC-Thiếu số tài khoản', 'VIETCOMBANK', 'Hoàn Kiếm', 'VNĐ', ''],
            [5, 'DOC-0001', 'DOC-Trùng số trong file', 'VIETCOMBANK', 'Hoàn Kiếm', 'VNĐ', ''],
            [6, '88838888', 'DOC-Trùng số hệ thống', 'VIETCOMBANK', 'Hoàn Kiếm', 'VNĐ', ''],
            [7, 'DOC-0004', 'DOC-Ngân hàng sai mã', 'NHKHONGCO', 'Hoàn Kiếm', 'VNĐ', ''],
            [8, 'DOC-0005', 'DOC-Chi nhánh không thuộc NH', 'VIETCOMBANK', 'Long Biên', 'XYZ', ''],
        ],
    },

    'uml': {
        'mains': [('FR-01', 'Xem danh sách tài khoản ngân hàng', 'view'), ('FR-03', 'Thêm mới tài khoản ngân hàng', 'crud'),
                  ('FR-04', 'Chỉnh sửa tài khoản ngân hàng', 'crud'), ('FR-06', 'Khóa / Mở khóa tài khoản ngân hàng', 'action'),
                  ('FR-08', 'Import file tài khoản ngân hàng', 'io'), ('FR-09', 'Xuất danh sách ra Excel', 'io')],
        'subs': [('FR-02', 'Tìm kiếm và lọc', 'view'), ('FR-10', 'Xem chi tiết tài khoản ngân hàng', 'view'),
                 ('FR-11', 'Tùy chỉnh cột hiển thị', 'view'), ('FR-07', 'Xem lịch sử thay đổi', 'view')],
        'rieng': [('FR-10', 'Xem chi tiết tài khoản ngân hàng', 'view')],
        'actor': 'Người dùng có quyền ' + Q,
    },

    'srs': {
        'muc_dich': ['Là căn cứ nghiệm thu chức năng.',
                     'Làm rõ phạm vi dữ liệu theo công ty, ràng buộc số tài khoản duy nhất toàn hệ thống và quan hệ Ngân hàng → Chi nhánh.'],
        'quyen_truoc': ['Màn hình dùng đúng một quyền cho mọi chức năng, kể cả xem danh sách. Máy chủ kiểm tra quyền trên từng thao tác.'],
        'quyen_rows': [[Q, 'Xem danh sách, tìm kiếm, tạo mới, sửa, khóa / mở khóa, xem chi tiết, xem lịch sử, Import Excel, Xuất Excel. Thiếu quyền: ẩn menu, mở trực tiếp bị từ chối.']],
        'ma_tran': [['Chức năng', Q]] + [[f, 'Có'] for f in _FR],
        'ma_tran_widths': [2.4, 2.4],
        'quyen_sau': ['Ngoài quyền, dữ liệu luôn giới hạn theo công ty ghi trong hồ sơ nhân sự của người đăng nhập.'],
        'fr': [
            {'ten': 'Xem danh sách tài khoản ngân hàng',
             'qtc': 'Màn Danh sách, Sắp xếp dữ liệu bảng, Phân trang và Cấu hình cột.',
             'gioi_thieu': [['Tên chức năng', 'Xem danh sách tài khoản ngân hàng'],
                            ['Mô tả', 'Hiển thị tài khoản ngân hàng của công ty người đăng nhập, có phân trang và sắp xếp.'],
                            ['Tác nhân', 'Người dùng có quyền ' + Q],
                            ['Dòng sự kiện chính', '1. Người dùng vào menu Tài chính → Danh mục → Danh mục tài khoản ngân hàng.\n2. Hệ thống nạp trang đầu (10 dòng), mới tạo nhất trước.\n3. Bảng hiển thị dữ liệu kèm tổng số bản ghi.'],
                            ['Dòng sự kiện phụ', '• Người dùng chưa gắn công ty → danh sách rỗng.\n• Không có bản ghi khớp → “Không có dữ liệu phù hợp bộ lọc.”']],
             'anh': [('list', 'Màn Danh mục tài khoản ngân hàng lúc mới truy cập')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Mô tả'],
                    ['1', 'Tiêu đề bảng', 'Label', 'Read-only', '“Danh sách tài khoản ngân hàng”.'],
                    ['2', 'STT', 'Table/Grid', 'Read-only', 'Số thứ tự, chạy liên tục qua các trang. Luôn hiển thị.'],
                    ['3', 'Số tài khoản', 'Table/Grid', 'Read-only', 'Luôn hiển thị, sắp xếp được. Bấm vào số tài khoản mở cửa sổ “Xem tài khoản ngân hàng” (xem 2.9).'],
                    ['4', 'Chủ tài khoản', 'Table/Grid', 'Read-only', 'CHỮ IN HOA, xuống dòng khi dài, sắp xếp được.'],
                    ['5', 'Ngân hàng', 'Table/Grid', 'Read-only', 'Tên ngân hàng đọc trực tiếp từ Danh mục ngân hàng.'],
                    ['6', 'Loại tiền tệ', 'Table/Grid', 'Read-only', 'Mã loại tiền tệ. Mặc định ẩn.'],
                    ['7', 'Chi nhánh', 'Table/Grid', 'Read-only', 'Tên chi nhánh ngân hàng. Mặc định ẩn.'],
                    ['8', 'Người cập nhật', 'Table/Grid', 'Read-only', 'Mặc định ẩn.'],
                    ['9', 'Ngày cập nhật', 'Table/Grid', 'Read-only', 'dd/mm/yyyy hh:mm. Mặc định ẩn, sắp xếp được.'],
                    ['10', 'Người tạo', 'Table/Grid', 'Read-only', 'Người đã thêm bản ghi.'],
                    ['11', 'Ngày tạo', 'Table/Grid', 'Read-only', 'dd/mm/yyyy hh:mm, sắp xếp được.'],
                    ['12', 'Trạng thái', 'Badge', 'Read-only', 'Hoạt động hoặc Khóa, hai màu khác nhau.'],
                    ['13', 'Hành động', 'Table/Grid', 'Read-only', 'Tối đa 3 nút hiện thẳng, không có nút ba chấm: Sửa (chỉ khi đang Hoạt động), Khóa / Mở khóa (nhãn đổi theo trạng thái), Lịch sử. Không có nút Xóa.'],
                    ['14', 'Nút Tạo mới', 'Button', 'Enable', 'Mở cửa sổ Tạo tài khoản ngân hàng (xem 2.3).'],
                    ['15', 'Nút Xuất Excel', 'Button', 'Enable', 'Mở cửa sổ Chọn trường xuất file (xem 2.8).'],
                    ['16', 'Nút Import Excel', 'Button', 'Enable', 'Mở cửa sổ Import tài khoản ngân hàng (xem 2.7).'],
                    ['17', 'Biểu tượng Cấu hình cột hiển thị', 'Icon Button', 'Enable', 'Mở cửa sổ Tuỳ chỉnh cột (xem 2.10).'],
                    ['18', 'Phân trang', 'Pagination', 'Enable', 'Dòng “Hiển thị a–b / N”; số dòng/trang 5 / 10 / 20 / 50 / 100, mặc định 10.'],
                    ['19', 'Trạng thái rỗng', 'Label', 'Ẩn', 'Hiện “Không có dữ liệu phù hợp bộ lọc.” khi không có bản ghi.']],
             'ui_widths': [0.6, 1.6, 0.9, 0.8, 2.8],
             'events': [['Mở màn hình', 'System', 'Before:\n– Kiểm tra quyền “' + Q + '”; không có quyền thì không vào được.\n– Khôi phục bộ lọc đã dùng trong 10 phút gần nhất (nếu có) và cấu hình cột của người dùng.\nAfter:\n– Nạp trang đầu (10 dòng) các tài khoản thuộc công ty người đăng nhập, mới tạo nhất ở trên cùng, hiển thị tổng số bản ghi.'],
                        ['Bấm tiêu đề cột sắp xếp được (Số tài khoản, Chủ tài khoản, Ngày tạo, Ngày cập nhật)', 'Click', 'After:\n– Đổi chiều sắp xếp (tăng / giảm) và nạp lại danh sách từ trang 1.'],
                        ['Chuyển trang', 'Click', 'Before:\n– Giữ nguyên bộ lọc và thứ tự sắp xếp.\nAfter:\n– Nạp dữ liệu trang mới.'],
                        ['Đổi số dòng mỗi trang', 'Change', 'After:\n– Quay về trang 1 và nạp lại theo số dòng mới.'],
                        ['Bấm số tài khoản', 'Click', 'After:\n– Mở cửa sổ “Xem tài khoản ngân hàng” ở chế độ chỉ đọc (xem 2.9).']]},
            {'ten': 'Tìm kiếm và lọc',
             'qtc': 'Kịch bản tìm kiếm, Bộ lọc, Dropdown, Phân trang.',
             'gioi_thieu': [['Tên chức năng', 'Tìm kiếm và lọc danh sách'],
                            ['Mô tả', 'Thu hẹp danh sách bằng ô tìm kiếm nhanh (số tài khoản, chủ tài khoản, ngân hàng), ô Chi nhánh và ô Trạng thái.'],
                            ['Dòng sự kiện chính', '1. Nhập từ khóa và bấm Tìm kiếm / Enter, hoặc đổi ô Chi nhánh / Trạng thái (lọc ngay).\n2. Hệ thống áp đồng thời các tiêu chí, nạp lại từ trang 1.']],
             'anh': [('filter', 'Khu vực tìm kiếm và lọc')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Phạm vi', 'Mô tả'],
                    ['1', 'Ô tìm kiếm nhanh', 'Textbox', 'Enable', 'Chuỗi ký tự bất kỳ', 'Placeholder “Tìm theo số tài khoản, chủ tài khoản, ngân hàng”. Khớp một phần, không phân biệt hoa thường. Có nút ✕ để xóa nhanh từ khóa. Chỉ lọc khi nhấn Enter hoặc bấm Tìm kiếm.'],
                    ['2', 'Chi nhánh', 'Textbox', 'Enable', 'Chuỗi ký tự bất kỳ', 'Nhãn nổi “Chi nhánh”. Khớp một phần tên chi nhánh. Lọc ngay khi thay đổi.'],
                    ['3', 'Trạng thái', 'Dropdown', 'Enable', 'Hoạt động / Khóa', 'Nhãn nổi “Trạng thái”. Bỏ trống thì hiện cả hai trạng thái. Lọc ngay khi chọn.'],
                    ['4', 'Nút Tìm kiếm', 'Button', 'Enable', '–', 'Áp dụng các tiêu chí, nạp lại từ trang 1.'],
                    ['5', 'Nút Làm mới', 'Button', 'Enable', '–', 'Xóa hết tiêu chí VÀ nạp lại danh sách đầy đủ ngay.']],
             'ui_widths': [0.6, 1.2, 0.8, 0.7, 1.1, 2.6],
             'events': [['Nhập từ khóa rồi nhấn Enter / bấm Tìm kiếm', 'Click', 'Before:\n– Thu thập từ khóa và giá trị ô Chi nhánh, Trạng thái.\nDuring:\n– Áp đồng thời các tiêu chí theo kiểu “và”, chỉ trong công ty của người đăng nhập.\nAfter:\n– Nạp lại bảng từ trang 1 và cập nhật tổng số bản ghi.'],
                        ['Nhập ô Chi nhánh / chọn Trạng thái', 'Change', 'After:\n– Lọc ngay, nạp lại bảng từ trang 1.'],
                        ['Bấm Làm mới', 'Click', 'After:\n– Xóa trắng mọi tiêu chí VÀ nạp lại danh sách đầy đủ ngay lập tức.'],
                        ['Rời màn rồi quay lại trong 10 phút', 'System', 'After:\n– Khôi phục các tiêu chí lọc đã dùng.']]},
            {'ten': 'Thêm mới tài khoản ngân hàng', 'uc': 'uc_fr03',
             'qtc': 'Màn Thêm mới, Validate dữ liệu, Thông báo và UI/UX; Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Thêm mới tài khoản ngân hàng'],
                            ['Mô tả', 'Thêm một tài khoản ngân hàng của công ty qua cửa sổ nhập liệu.'],
                            ['Tác nhân', 'Người dùng có quyền ' + Q],
                            ['Dòng sự kiện chính', '1. Bấm Tạo mới.\n2. Hệ thống mở cửa sổ “Tạo tài khoản ngân hàng”, Trạng thái = Hoạt động.\n3. Nhập Số tài khoản, Chủ tài khoản; chọn Loại tiền tệ, Ngân hàng rồi Chi nhánh; bấm Lưu.\n4. Hệ thống kiểm tra, ghi bản ghi (gắn công ty người tạo, chủ tài khoản in hoa), ghi lịch sử.\n5. Đóng cửa sổ, báo “Thêm mới thành công”.'],
                            ['Dòng sự kiện phụ', '• Thiếu trường / trùng số tài khoản / ngân hàng, tiền tệ vừa bị khóa / chi nhánh lệch ngân hàng → lỗi đỏ dưới ô, cửa sổ không đóng.\n• Người dùng chưa gắn công ty → “Tài khoản đăng nhập chưa gắn công ty, không thể thao tác”.\n• Lưu và tiếp tục → giữ cửa sổ, xóa trắng form.\n• Đóng khi đang nhập dở → hỏi “Thông tin chưa lưu”.']],
             'menu_them': ' => Tạo mới {icon:btn_taomoi}',
             'ghi_chu_layout': 'Cửa sổ Tạo tài khoản ngân hàng được mở ngay trên màn hình danh sách.',
             'anh': [('create', 'Cửa sổ Tạo tài khoản ngân hàng'), ('create_error', 'Lỗi đỏ ngay dưới ô còn thiếu')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Phạm vi', 'Bắt buộc', 'Mô tả'],
                    ['1', 'Tiêu đề cửa sổ', 'Label', 'Read-only', '', '', '“Tạo tài khoản ngân hàng”.'],
                    ['2', 'Số tài khoản', 'Textbox', 'Enable', '1–255 ký tự', 'Có', 'Placeholder “Nhập số tài khoản”. Tự bỏ khoảng trắng hai đầu. Duy nhất trên TOÀN HỆ THỐNG (kể cả công ty khác). Bỏ trống “Bắt buộc phải nhập”; trùng “Số tài khoản đã tồn tại”.'],
                    ['3', 'Loại tiền tệ', 'Dropdown', 'Enable', 'Tiền tệ đang Hoạt động', 'Có', 'Hiển thị dạng “Mã — Tên”. Bỏ trống “Bắt buộc phải nhập”; tiền tệ vừa bị khóa “Loại tiền tệ không tồn tại hoặc đã bị khóa”.'],
                    ['4', 'Chủ tài khoản', 'Textbox', 'Enable', '1–255 ký tự', 'Có', 'Placeholder “Hệ thống tự chuyển thành CHỮ IN HOA khi lưu”. Bỏ trống báo “Bắt buộc phải nhập” ngay khi bấm Lưu (kiểm tra tại màn hình).'],
                    ['5', 'Ngân hàng', 'Dropdown', 'Enable', 'Ngân hàng đang Hoạt động', 'Có', 'Bỏ trống “Bắt buộc phải nhập”; ngân hàng vừa bị khóa “Ngân hàng không tồn tại hoặc đã bị khóa”. Đổi ngân hàng thì ô Chi nhánh tự xóa trắng.'],
                    ['6', 'Chi nhánh', 'Dropdown', 'Disable / Enable', 'Chi nhánh của ngân hàng đã chọn', 'Có', 'Bị khóa (Disable) cho tới khi chọn Ngân hàng. Bỏ trống “Bắt buộc phải nhập”; lệch ngân hàng hoặc chi nhánh đã khóa “Chi nhánh không thuộc ngân hàng đã chọn hoặc đã bị khóa”.'],
                    ['7', 'Trạng thái', 'Dropdown', 'Enable', 'Hoạt động / Khóa', 'Có', 'Mặc định Hoạt động. Không xóa trắng được.'],
                    ['8', 'Nút Lưu', 'Button', 'Enable', '', '', 'Ghi bản ghi rồi đóng cửa sổ, báo “Thêm mới thành công”.'],
                    ['9', 'Nút Lưu và tiếp tục', 'Button', 'Enable', '', '', 'Ghi bản ghi rồi giữ cửa sổ mở, xóa trắng các ô để nhập tiếp.'],
                    ['10', 'Nút Đóng / biểu tượng ✕', 'Button', 'Enable', '', '', 'Đóng cửa sổ, không ghi gì; đã nhập dở thì hỏi “Thông tin chưa lưu”.'],
                    ['11', 'Thông báo lỗi', 'Label', 'Ẩn', '', '', 'Chữ đỏ ngay dưới ô bị lỗi, kèm toast “Vui lòng kiểm tra lại dữ liệu nhập”.']],
             'ui_widths': [0.5, 1.2, 0.8, 0.7, 1.2, 0.5, 2.4],
             'events': [['Bấm nút Tạo mới', 'Click', 'After:\n– Mở cửa sổ “Tạo tài khoản ngân hàng” với các ô trống, Trạng thái = Hoạt động, ô Chi nhánh bị khóa.\n– Nạp danh sách ngân hàng, chi nhánh và loại tiền tệ đang Hoạt động.'],
                        ['Chọn Ngân hàng', 'Change', 'After:\n– Mở khóa ô Chi nhánh, chỉ liệt kê chi nhánh của ngân hàng vừa chọn.\n– Chi nhánh đang chọn không thuộc ngân hàng mới → tự xóa trắng.'],
                        ['Bấm Lưu', 'Click', 'Before:\n– Kiểm tra tại màn hình ô Chủ tài khoản; bỏ trống → “Bắt buộc phải nhập”, dừng.\nDuring:\n– Máy chủ kiểm tra: bắt buộc Số tài khoản, Loại tiền tệ, Ngân hàng, Chi nhánh (“Bắt buộc phải nhập”); trùng “Số tài khoản đã tồn tại”; ngân hàng / tiền tệ vừa bị khóa; chi nhánh lệch ngân hàng.\n– Người dùng chưa gắn công ty → toast “Tài khoản đăng nhập chưa gắn công ty, không thể thao tác”.\n– Có lỗi → báo đỏ dưới ô, cửa sổ KHÔNG đóng, không thực hiện After.\nAfter:\n– Ghi bản ghi mới gắn công ty của người tạo, Chủ tài khoản CHỮ IN HOA; ghi lịch sử Tạo mới.\n– Đóng cửa sổ, nạp lại danh sách, báo “Thêm mới thành công”.'],
                        ['Bấm Lưu và tiếp tục', 'Click', 'During:\n– Như nút Lưu.\nAfter:\n– Ghi bản ghi, báo “Thêm mới thành công”, xóa trắng các ô và GIỮ cửa sổ mở.'],
                        ['Bấm Đóng / ✕ / bấm ra ngoài cửa sổ', 'Click', 'After:\n– Chưa nhập gì → đóng cửa sổ.\n– Đã nhập dở → hỏi “Thông tin chưa lưu” — “Bạn có thông tin chưa lưu. Có chắc chắn muốn thoát?”; Thoát thì đóng, Ở lại thì giữ nguyên dữ liệu.']]},
            {'ten': 'Chỉnh sửa tài khoản ngân hàng', 'uc': 'uc_fr04',
             'qtc': 'Validate dữ liệu, Thông báo, Quy định chung về danh mục và Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Chỉnh sửa tài khoản ngân hàng'],
                            ['Điều kiện ban đầu', 'Tài khoản đang Hoạt động và thuộc công ty người dùng.'],
                            ['Dòng sự kiện chính', '1. Bấm bút chì.\n2. Sửa và bấm Lưu.\n3. Hệ thống ghi thay đổi, ghi lịch sử, báo “Cập nhật thành công”.'],
                            ['Dòng sự kiện phụ', '• Ngân hàng / tiền tệ đang dùng đã bị khóa → vẫn giữ giá trị kèm 🔒, lưu lại được.\n• Tài khoản vừa bị người khác khóa → bấm Lưu báo “Tài khoản ngân hàng đang bị khoá, vui lòng mở khoá trước khi cập nhật.”']],
             'menu_them': ' => Sửa {icon:btn_sua}',
             'anh': [('edit', 'Cửa sổ Sửa tài khoản ngân hàng')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Phạm vi', 'Bắt buộc', 'Giá trị ban đầu', 'Mô tả'],
                    ['1', 'Tiêu đề cửa sổ', 'Label', 'Read-only', '', '', '“Sửa tài khoản ngân hàng”', ''],
                    ['2', 'Số tài khoản', 'Textbox', 'Enable', '1–255 ký tự', 'Có', 'Dữ liệu hiện tại', 'Duy nhất toàn hệ thống, bỏ qua chính bản ghi đang sửa. Bỏ trống “Bắt buộc phải nhập”; trùng “Số tài khoản đã tồn tại”.'],
                    ['3', 'Loại tiền tệ', 'Dropdown', 'Enable', 'Tiền tệ đang Hoạt động + tiền tệ bản ghi đang giữ', 'Có', 'Dữ liệu hiện tại', 'Tiền tệ đang giữ đã bị khóa vẫn hiện đúng tên kèm 🔒 và lưu lại được; đổi sang giá trị khác thì chỉ chọn được tiền tệ đang Hoạt động.'],
                    ['4', 'Chủ tài khoản', 'Textbox', 'Enable', '1–255 ký tự', 'Có', 'Dữ liệu hiện tại', 'Tự chuyển CHỮ IN HOA khi lưu. Bỏ trống “Bắt buộc phải nhập”.'],
                    ['5', 'Ngân hàng', 'Dropdown', 'Enable', 'Ngân hàng đang Hoạt động + ngân hàng bản ghi đang giữ', 'Có', 'Dữ liệu hiện tại', 'Ngân hàng đang giữ đã bị khóa vẫn hiện kèm 🔒 và lưu lại được. Đổi ngân hàng thì ô Chi nhánh tự xóa trắng.'],
                    ['6', 'Chi nhánh', 'Dropdown', 'Enable', 'Chi nhánh của ngân hàng đã chọn', 'Có', 'Dữ liệu hiện tại', 'Lệch ngân hàng hoặc chọn mới chi nhánh đã khóa → “Chi nhánh không thuộc ngân hàng đã chọn hoặc đã bị khóa”.'],
                    ['7', 'Trạng thái', 'Dropdown', 'Enable', 'Hoạt động / Khóa', 'Có', 'Dữ liệu hiện tại', 'Chọn Khóa rồi Lưu có tác dụng như nút Khóa ngoài danh sách.'],
                    ['8', 'Nút Lưu', 'Button', 'Enable', '–', '', 'Hiển thị', 'Ghi thay đổi rồi đóng cửa sổ, báo “Cập nhật thành công”.'],
                    ['9', 'Nút Đóng / biểu tượng ✕', 'Button', 'Enable', '–', '', 'Hiển thị', 'Hủy bỏ, không ghi gì; đã sửa dở thì hỏi “Thông tin chưa lưu”. Cửa sổ Sửa KHÔNG có nút Lưu và tiếp tục.']],
             'ui_widths': [0.5, 1.1, 0.8, 0.6, 1.2, 0.5, 0.9, 2.2],
             'events': [['Bấm biểu tượng bút chì', 'Click', 'Before:\n– Tài khoản đã Khóa thì nút này không hiển thị; dữ liệu trên bảng cũ (tài khoản vừa bị khóa) thì báo “Tài khoản ngân hàng đang bị khóa, không thể sửa”.\nAfter:\n– Mở cửa sổ “Sửa tài khoản ngân hàng” với dữ liệu hiện tại; ngân hàng / tiền tệ đã khóa đang giữ hiện kèm 🔒.\n– Bản ghi không còn hoặc thuộc công ty khác → báo “Không tìm thấy tài khoản ngân hàng”, đóng cửa sổ.'],
                        ['Bấm Lưu', 'Click', 'Before:\n– Tài khoản vừa bị người khác khóa → dừng, báo “Tài khoản ngân hàng đang bị khoá, vui lòng mở khoá trước khi cập nhật.”\nDuring:\n– Kiểm tra như Thêm mới, bỏ qua trùng với chính bản ghi; cho phép giữ nguyên ngân hàng / chi nhánh / tiền tệ đã khóa đang dùng.\n– Có lỗi → báo đỏ dưới ô, cửa sổ không đóng, không thực hiện After.\nAfter:\n– Ghi thay đổi (Chủ tài khoản CHỮ IN HOA), ghi lịch sử từng trường đổi (giá trị cũ → mới).\n– Đóng cửa sổ, nạp lại danh sách, báo “Cập nhật thành công”.'],
                        ['Bấm Đóng / ✕', 'Click', 'After:\n– Chưa sửa gì → đóng cửa sổ. Đã sửa → hỏi “Thông tin chưa lưu” (Thoát / Ở lại).']]},
            {'ten': 'Khóa / Mở khóa tài khoản ngân hàng', 'uc': 'uc_fr06',
             'qtc': 'Quy tắc Khóa/Mở khóa, Thông báo và Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Khóa / Mở khóa tài khoản ngân hàng'],
                            ['Dòng sự kiện chính', '1. Chọn Khóa / Mở khóa.\n2. Xác nhận trong hộp “Xác nhận khóa” / “Xác nhận mở khóa”.\n3. Hệ thống đổi trạng thái, ghi lịch sử, báo “Khóa thành công” / “Mở khóa thành công”.']],
             'menu_them': ' => Khóa / Mở khóa',
             'anh': [('lock', 'Hộp xác nhận khóa tài khoản'), ('rowmenu', 'Các nút ở cột Hành động')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Mô tả'],
                    ['1', 'Nút Khóa / Mở khóa', 'Icon Button', 'Nằm thẳng ở cột Hành động của từng dòng (không qua nút ba chấm). Tài khoản đang Hoạt động hiện Khóa (biểu tượng ổ khóa), đang Khóa hiện Mở khóa.'],
                    ['2', 'Tiêu đề hộp xác nhận', 'Label', '“Xác nhận khóa” hoặc “Xác nhận mở khóa” theo trạng thái hiện tại.'],
                    ['3', 'Nội dung hộp xác nhận', 'Label', '“Bạn có chắc muốn khóa tài khoản \'<số tài khoản>\'?” (hoặc “… mở khóa tài khoản …”).'],
                    ['4', 'Nút Khóa / Mở khóa', 'Button', 'Xác nhận thực hiện.'],
                    ['5', 'Nút Hủy', 'Button', 'Đóng hộp, không làm gì.'],
                    ['6', 'Cột Trạng thái', 'Badge', 'Hoạt động hoặc Khóa, hai màu khác nhau; cập nhật ngay sau khi thao tác.']],
             'ui_widths': [0.6, 1.6, 1, 3.6],
             'events': [['Bấm Khóa hoặc Mở khóa ở cột Hành động', 'Click', 'After:\n– Hiện hộp xác nhận kèm số tài khoản.'],
                        ['Bấm Khóa / Mở khóa trong hộp xác nhận', 'Click', 'During:\n– Bản ghi không còn hoặc thuộc công ty khác → báo “Dữ liệu đã thay đổi, vui lòng tải lại”, dừng xử lý.\nAfter:\n– Đổi trạng thái bản ghi, KHÔNG xóa dữ liệu; ghi lịch sử Khóa / Mở khóa.\n– Báo “Khóa thành công” / “Mở khóa thành công”, nạp lại danh sách.\n– Sau khi Khóa, nút Sửa của dòng biến mất; sau khi Mở khóa, nút Sửa hiện lại.'],
                        ['Bấm Hủy', 'Click', 'After:\n– Đóng hộp xác nhận, không thay đổi gì.']]},
            {'ten': 'Xem lịch sử thay đổi',
             'qtc': 'Quy tắc ghi lịch sử và hiển thị lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Xem lịch sử thay đổi'],
                            ['Mô tả', 'Liệt kê các lần thay đổi của một tài khoản, giá trị cũ → mới, người thực hiện, thời điểm.']],
             'menu_them': ' => Lịch sử',
             'anh': [('history', 'Cửa sổ Lịch sử thay đổi')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Giá trị ban đầu', 'Mô tả'],
                    ['1', 'Nút Lịch sử', 'Icon Button', 'Hiển thị', 'Nằm ở cột Hành động của mọi dòng, kể cả tài khoản đang Khóa.'],
                    ['2', 'Tiêu đề cửa sổ', 'Label', 'Lịch sử thay đổi: <số tài khoản> - <chủ tài khoản>', 'Nêu rõ bản ghi đang xem.'],
                    ['3', 'Nút Bộ lọc', 'Button', 'Thu gọn', 'Mở / thu gọn vùng lọc; vùng lọc ghim ở đầu khi cuộn.'],
                    ['4', 'Loại hành động', 'Dropdown', 'Tất cả loại hành động', 'Ví dụ Tạo mới, Thay đổi thông tin, Khóa, Mở khóa.'],
                    ['5', 'Người thực hiện', 'Dropdown', 'Tất cả người thực hiện', 'Danh sách người đã thao tác trên bản ghi.'],
                    ['6', 'Từ ngày / Đến ngày', 'Datepicker', 'Trống', 'dd/mm/yyyy, lọc theo thời điểm thao tác.'],
                    ['7', 'Thông tin thay đổi', 'Text', 'Theo dữ liệu', '- Thời điểm: dd/mm/yyyy hh:mm.\n- Loại hành động, tô màu theo loại.\n- Người thực hiện kèm mã NV và phòng ban.\n- Từng trường đã đổi: giá trị cũ → giá trị mới (Số tài khoản, Chủ tài khoản, Ngân hàng, Chi nhánh, Loại tiền tệ, Trạng thái).\nMới nhất ở trên cùng.'],
                    ['8', 'Trạng thái rỗng', 'Label', 'Ẩn', '“Chưa có lịch sử thao tác nào.” khi bản ghi chưa có mốc nào; “Không có lịch sử phù hợp bộ lọc.” khi lọc không ra.'],
                    ['9', 'Nút Đóng / ✕', 'Button', 'Hiển thị', 'Đóng cửa sổ.']],
             'ui_widths': [0.6, 1.4, 0.9, 1.4, 2.8],
             'events': [['Bấm Lịch sử ở cột Hành động', 'Click', 'After:\n– Mở cửa sổ “Lịch sử thay đổi: <số tài khoản> - <chủ tài khoản>”, nạp danh sách thay đổi, mới nhất ở trên cùng.'],
                        ['Đổi tiêu chí trong vùng Bộ lọc', 'Change', 'After:\n– Thu hẹp danh sách theo loại hành động, người thực hiện, khoảng ngày đã chọn.'],
                        ['Bấm Đóng / ✕', 'Click', 'After:\n– Đóng cửa sổ; danh sách phía sau giữ nguyên bộ lọc và trang.']]},
            {'ten': 'Import file tài khoản ngân hàng', 'uc': 'uc_fr08',
             'qtc': 'Quy tắc Import file, Validate dữ liệu, Thông báo. Chỉ bổ sung mapping/validation riêng.',
             'gioi_thieu': [['Tên chức năng', 'Import file tài khoản ngân hàng'],
                            ['Mô tả', 'Thêm nhiều tài khoản cùng lúc từ file Excel mẫu, có bước Validate trước khi ghi.'],
                            ['Tác nhân', 'Người dùng có quyền ' + Q],
                            ['Dòng sự kiện chính', '1. Bấm Import Excel.\n2. Tải file mẫu Mau_import_tai_khoan_ngan_hang.xlsx, điền dữ liệu.\n3. Chọn file Excel, Load lên bảng.\n4. Validate: tra Mã ngân hàng, tên Chi nhánh thuộc ngân hàng đó, Mã tiền tệ; kiểm tra trùng số tài khoản.\n5. Sửa dòng lỗi / Bỏ dòng lỗi, Validate lại.\n6. Import: báo “Import thành công N tài khoản ngân hàng.”'],
                            ['Yêu cầu đặc biệt', 'Không tự tạo ngân hàng / chi nhánh / tiền tệ mới. Tối đa 500 dòng mỗi lần.']],
             'menu_them': ' => Import Excel {icon:btn_import}',
             'anh': [('import_open', 'Cửa sổ Import tài khoản ngân hàng'), ('import_loaded', 'Dữ liệu đã load lên bảng'),
                     ('import_validated', 'Kết quả Validate')],
             'bang_them': [('Quy tắc kiểm tra riêng của file Import', [['Cột', 'Quy tắc / thông báo lỗi'],
                            ['Số tài khoản *', 'Bắt buộc, tối đa 255 ký tự, không trùng trong file, không trùng hệ thống.'],
                            ['Chủ tài khoản *', 'Bắt buộc, tối đa 255 ký tự.'],
                            ['Mã ngân hàng *', 'Bắt buộc; sai mã báo “Không tìm thấy ngân hàng: X”.'],
                            ['Chi nhánh *', 'Bắt buộc; phải là tên chi nhánh thuộc ngân hàng đã ghi — sai báo “Không tìm thấy chi nhánh "X" thuộc ngân hàng Y”.'],
                            ['Mã tiền tệ *', 'Bắt buộc; sai mã báo “Không tìm thấy tiền tệ: X”.'],
                            ['Trạng thái', 'Hoạt động / Khóa; bỏ trống = Hoạt động.']], [1.4, 4])],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Bắt buộc', 'Giá trị ban đầu', 'Mô tả'],
                    ['1', 'Nút Import Excel', 'Button', 'Enable', '–', 'Hiển thị', 'Nằm trên thanh công cụ của bảng danh sách. Mở cửa sổ “Import tài khoản ngân hàng”, dòng phụ “Import từ Excel • Validate xong dòng hợp lệ sẽ bị khoá”.'],
                    ['2', 'Nút Tải file mẫu', 'Button', 'Enable', '–', 'Hiển thị', 'Tải file Mau_import_tai_khoan_ngan_hang.xlsx gồm STT, Số tài khoản *, Chủ tài khoản *, Mã ngân hàng *, Chi nhánh *, Mã tiền tệ *, Trạng thái (ô chọn Hoạt động / Khóa). Hàng 2 là dòng mô tả, dữ liệu nhập từ hàng 3.'],
                    ['3', 'Nút Chọn file Excel', 'Button', 'Enable', 'Có', 'Chưa chọn file', 'Chọn file .xlsx / .xls từ máy; tên file hiện ngay cạnh nút.'],
                    ['4', 'Nút Load lên bảng', 'Button', 'Enable / Disable', '–', 'Mờ khi chưa chọn file', 'Đọc file và đổ dữ liệu lên bảng xem trước.'],
                    ['5', 'Nút Validate', 'Button', 'Enable / Disable', '–', 'Mờ khi bảng chưa có dòng nào', 'Kiểm tra từng dòng; dòng hợp lệ bị khóa lại không sửa được nữa.'],
                    ['6', 'Nút Import', 'Button', 'Enable / Disable', '–', 'Mờ khi chưa Validate hoặc còn dòng lỗi', 'Chỉ bấm được khi đã Validate, không còn dòng lỗi và có ít nhất 1 dòng hợp lệ. Ghi các dòng hợp lệ vào hệ thống.'],
                    ['7', 'Bảng xem trước', 'Table/Grid', 'Enable', '–', 'Trống', 'Các cột như file mẫu. Sửa trực tiếp được ở dòng lỗi.'],
                    ['8', 'Ô Tổng / Hợp lệ / Lỗi', 'Label', 'Read-only', '–', 'Tổng: 0', 'Sau khi Load hiện “Tổng”; sau khi Validate hiện thêm “Hợp lệ” và “Lỗi”.'],
                    ['9', 'Thông báo lỗi theo dòng', 'Label', 'Hiển thị', '–', 'Ẩn', 'Dòng lỗi viền đỏ, lý do ghi ngay dưới dòng (xem bảng Quy tắc kiểm tra riêng của file Import).'],
                    ['10', 'Nút Bỏ dòng lỗi', 'Button', 'Enable / Disable', '–', 'Mờ khi bảng trống', 'Loại toàn bộ dòng lỗi khỏi bảng xem trước; chưa Validate thì báo “Hãy Validate trước rồi mới bỏ dòng lỗi.”'],
                    ['11', 'Nút Xoá trạng thái validate', 'Button', 'Enable / Disable', '–', 'Mờ khi bảng trống', 'Bỏ khóa các dòng hợp lệ và xóa thông báo lỗi validate.'],
                    ['12', 'Nút Làm mới', 'Button', 'Enable', '–', 'Hiển thị', 'Xóa file đã chọn và toàn bộ bảng xem trước, đưa cửa sổ về trạng thái ban đầu.'],
                    ['13', 'Nút Đóng', 'Button', 'Enable', '–', 'Hiển thị', 'Đóng cửa sổ, không ghi gì.']],
             'ui_widths': [0.5, 1.3, 0.8, 0.8, 0.5, 1.1, 2.6],
             'events': [['Bấm Import Excel', 'Click', 'After:\n– Mở cửa sổ “Import tài khoản ngân hàng” ở trạng thái rỗng.'],
                        ['Bấm Tải file mẫu', 'Click', 'After:\n– Tải về file Mau_import_tai_khoan_ngan_hang.xlsx.'],
                        ['Chọn file Excel', 'Change', 'During:\n– File khác .xlsx / .xls → “Vui lòng chọn file .xlsx hoặc .xls”.\nAfter:\n– Hiện tên file, nút Load lên bảng sáng lên.'],
                        ['Bấm Load lên bảng', 'Click', 'During:\n– Không có dòng dữ liệu → “Không có dòng dữ liệu hợp lệ.”\n– Quá 500 dòng → “File có X dòng dữ liệu, vượt quá giới hạn 500 dòng mỗi lần import. Vui lòng tách file và import nhiều lần.”\nAfter:\n– Đổ dữ liệu lên bảng xem trước, cập nhật ô Tổng.'],
                        ['Bấm Validate', 'Click', 'During:\n– Máy chủ kiểm tra từng dòng: bắt buộc, độ dài, trùng số tài khoản trong file / trên hệ thống, tra Mã ngân hàng, tên Chi nhánh thuộc ngân hàng đó, Mã tiền tệ, giá trị Trạng thái.\nAfter:\n– Dòng lỗi viền đỏ kèm lý do, dòng hợp lệ bị khóa; toast “Validate xong: X hợp lệ, Y không hợp lệ” hoặc “Validate thành công”.\n– KHÔNG ghi bất kỳ bản ghi nào ở bước này.'],
                        ['Sửa dòng lỗi / Bấm Bỏ dòng lỗi', 'Click', 'After:\n– Sửa trực tiếp trên bảng rồi Validate lại, hoặc loại toàn bộ dòng lỗi khỏi bảng.'],
                        ['Bấm Import', 'Click', 'During:\n– Máy chủ kiểm tra lại toàn bộ dòng gửi lên, bỏ qua dòng lỗi.\n– Không còn dòng hợp lệ → “Không có dòng nào hợp lệ để import”, dừng.\nAfter:\n– Ghi các dòng hợp lệ: gắn công ty người nhập, Chủ tài khoản CHỮ IN HOA, Trạng thái theo cột (trống = Hoạt động); ghi lịch sử Tạo mới.\n– Báo “Import thành công N tài khoản ngân hàng.” (có dòng thất bại: “Import thành công X/N tài khoản ngân hàng. Y dòng thất bại.”), đóng cửa sổ, nạp lại danh sách.'],
                        ['Bấm Làm mới / Đóng', 'Click', 'After:\n– Làm mới: xóa trạng thái hiện tại, giữ cửa sổ mở. Đóng: đóng cửa sổ, không ghi gì.']]},
            {'ten': 'Xuất danh sách ra Excel', 'uc': 'uc_fr09',
             'qtc': 'Quy tắc Excel và Cấu hình cột.',
             'gioi_thieu': [['Tên chức năng', 'Xuất danh sách tài khoản ngân hàng ra Excel'],
                            ['Dòng sự kiện chính', '1. Bấm Xuất Excel.\n2. Cửa sổ “Chọn trường xuất file” tích sẵn cột đang hiển thị.\n3. Tích chọn, kéo ☰ sắp thứ tự.\n4. Bấm Xuất file; tải danh_muc_tai_khoan_ngan_hang.xlsx theo đúng bộ lọc (từ khóa, Chi nhánh, Trạng thái) và thứ tự sắp xếp, báo “Xuất Excel thành công”.']],
             'menu_them': ' => Xuất Excel {icon:btn_xuatexcel}',
             'anh': [('export', 'Cửa sổ Chọn trường xuất file')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
                    ['1', 'Nút Xuất Excel', 'Button', 'Enable', 'Hiển thị', 'Nằm trên thanh công cụ của bảng danh sách. Mở cửa sổ “Chọn trường xuất file”.'],
                    ['2', 'Dòng hướng dẫn', 'Label', 'Read-only', 'Hiển thị', '“Tích chọn trường cần xuất, kéo ☰ để đổi thứ tự cột trong file.”'],
                    ['3', 'Danh sách trường', 'Checkbox chọn nhiều', 'Enable', 'Tích sẵn các cột đang hiển thị trên bảng', 'Mười trường: Số tài khoản, Chủ tài khoản, Ngân hàng, Chi nhánh, Loại tiền tệ, Trạng thái, Người tạo, Ngày tạo, Người cập nhật, Ngày cập nhật. Kéo ☰ để đổi thứ tự.'],
                    ['4', 'Nút Chọn tất cả', 'Button', 'Enable', 'Hiển thị', 'Tích hết toàn bộ trường.'],
                    ['5', 'Nút Bỏ chọn hết', 'Button', 'Enable', 'Hiển thị', 'Bỏ tích toàn bộ trường.'],
                    ['6', 'Bộ đếm', 'Label', 'Read-only', 'Đang chọn n/10 trường', 'Cập nhật theo số trường đang tích.'],
                    ['7', 'Nút Xuất file', 'Button', 'Enable / Disable', 'Mờ khi chưa chọn trường nào', 'Sinh file Excel và tải về máy.'],
                    ['8', 'Nút Đóng / ✕', 'Button', 'Enable', 'Hiển thị', 'Đóng cửa sổ, không xuất.']],
             'ui_widths': [0.6, 1.4, 1, 0.8, 1.3, 2.6],
             'events': [['Bấm Xuất Excel', 'Click', 'After:\n– Mở cửa sổ “Chọn trường xuất file”, tích sẵn đúng các cột đang hiển thị trên bảng.'],
                        ['Tích / bỏ tích, kéo ☰ đổi thứ tự trường', 'Change', 'During:\n– Thứ tự trường trong danh sách quyết định thứ tự cột trong file.\n– Bỏ chọn hết thì nút Xuất file mờ đi.'],
                        ['Bấm Xuất file', 'Click', 'During:\n– Lấy toàn bộ kết quả theo bộ lọc đang áp dụng (từ khóa, Chi nhánh, Trạng thái) và thứ tự sắp xếp, chỉ trong công ty người đăng nhập, tối đa 10,000 dòng.\nAfter:\n– Tải file danh_muc_tai_khoan_ngan_hang.xlsx (tiêu đề “Danh mục tài khoản ngân hàng”, cột STT ở đầu, các cột theo đúng thứ tự đã chọn), báo “Xuất Excel thành công”.\n– Lỗi → báo “Lỗi khi xuất Excel”.'],
                        ['Bấm Đóng', 'Click', 'After:\n– Đóng cửa sổ, không xuất gì.']]},
            {'ten': 'Xem chi tiết tài khoản ngân hàng', 'uc': 'uc_fr10',
             'qtc': 'Màn Xem chi tiết và Phân quyền.',
             'gioi_thieu': [['Tên chức năng', 'Xem chi tiết tài khoản ngân hàng'],
                            ['Dòng sự kiện chính', '1. Bấm số tài khoản ở danh sách.\n2. Hệ thống mở cửa sổ “Xem tài khoản ngân hàng” chỉ đọc, kèm khối Lịch sử.']],
             'anh': [('detail', 'Cửa sổ Xem tài khoản ngân hàng')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
                    ['1', 'Số tài khoản (cột trên danh sách)', 'Link', 'Enable', 'Hiển thị', 'Bấm vào để mở cửa sổ Xem. Màn hình không có nút “Xem” riêng.'],
                    ['2', 'Tiêu đề cửa sổ', 'Label', 'Read-only', '“Xem tài khoản ngân hàng”', ''],
                    ['3', 'Số tài khoản', 'Textbox', 'Read-only', 'Dữ liệu hiện tại', ''],
                    ['4', 'Loại tiền tệ', 'Dropdown', 'Read-only', 'Dữ liệu hiện tại', 'Dạng “Mã — Tên”; tiền tệ đã khóa hiện đúng tên kèm 🔒.'],
                    ['5', 'Chủ tài khoản', 'Textbox', 'Read-only', 'Dữ liệu hiện tại', 'CHỮ IN HOA.'],
                    ['6', 'Ngân hàng', 'Dropdown', 'Read-only', 'Dữ liệu hiện tại', 'Ngân hàng đã khóa hiện đúng tên kèm 🔒.'],
                    ['7', 'Chi nhánh', 'Dropdown', 'Read-only', 'Dữ liệu hiện tại', ''],
                    ['8', 'Trạng thái', 'Dropdown', 'Read-only', 'Dữ liệu hiện tại', 'Hoạt động hoặc Khóa.'],
                    ['9', 'Khối Lịch sử', 'Section', 'Enable', 'Thu gọn', 'Nằm cuối cửa sổ, có nút “Xem lịch sử” / “Thu gọn” và “Làm mới”; khi mở hiển thị giống cửa sổ Lịch sử thay đổi (xem 2.6).'],
                    ['10', 'Nút Đóng / ✕', 'Button', 'Enable', 'Hiển thị', 'Nút duy nhất ở chân cửa sổ — không có Lưu, Sửa hay In.']],
             'ui_widths': [0.6, 1.5, 0.9, 0.8, 1.2, 2.6],
             'events': [['Bấm số tài khoản ở danh sách', 'Click', 'After:\n– Mở cửa sổ “Xem tài khoản ngân hàng”, mọi ô ở chế độ chỉ đọc; tài khoản đang Khóa vẫn xem được.\n– Bản ghi không còn hoặc thuộc công ty khác → báo “Không tìm thấy tài khoản ngân hàng”, đóng cửa sổ.'],
                        ['Bấm Xem lịch sử trong khối Lịch sử', 'Click', 'After:\n– Mở khối, nạp danh sách thay đổi mới nhất ở trên cùng; bấm Thu gọn để đóng khối.'],
                        ['Bấm Đóng / ✕', 'Click', 'After:\n– Đóng cửa sổ, danh sách giữ nguyên bộ lọc và trang.']]},
            {'ten': 'Tùy chỉnh cột hiển thị',
             'qtc': 'Tùy chỉnh cột.',
             'gioi_thieu': [['Tên chức năng', 'Tùy chỉnh cột hiển thị'],
                            ['Yêu cầu đặc biệt', 'Cột STT, Số tài khoản, Hành động bị khóa. Mặc định ẩn: Loại tiền tệ, Chi nhánh, Người cập nhật, Ngày cập nhật.']],
             'menu_them': ' => Cấu hình cột {icon:btn_cauhinhcot}',
             'anh': [('colcfg', 'Cửa sổ Tuỳ chỉnh cột')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
                    ['1', 'Biểu tượng Cấu hình cột hiển thị', 'Icon Button', 'Enable', 'Hiển thị', 'Nằm cuối thanh công cụ của bảng. Mở cửa sổ “Tuỳ chỉnh cột”.'],
                    ['2', 'Danh sách cột', 'Checkbox chọn nhiều', 'Enable', 'Theo cấu hình đã lưu của người dùng', 'Mười hai cột: STT, Số tài khoản, Chủ tài khoản, Ngân hàng, Loại tiền tệ, Chi nhánh, Người cập nhật, Ngày cập nhật, Người tạo, Ngày tạo, Trạng thái, Hành động. Lần đầu mặc định ẩn Loại tiền tệ, Chi nhánh, Người cập nhật, Ngày cập nhật.'],
                    ['3', 'Cột bị khóa', 'Checkbox', 'Disable', 'Tích sẵn', 'STT, Số tài khoản, Hành động: hiện xám kèm biểu tượng ổ khóa (“Cột bắt buộc — không thể ẩn hoặc đổi vị trí”), không bỏ tích, không kéo được.'],
                    ['4', 'Biểu tượng ☰', 'Drag handle', 'Enable', 'Hiển thị', 'Kéo thả để đổi thứ tự các cột không bị khóa.'],
                    ['5', 'Nút Lưu', 'Button', 'Enable', 'Hiển thị', 'Lưu cấu hình theo tài khoản người dùng (dùng được trên máy khác), áp dụng ngay cho bảng, báo “Cập nhật thành công”.'],
                    ['6', 'Nút Đóng / ✕', 'Button', 'Enable', 'Hiển thị', 'Đóng cửa sổ, không lưu thay đổi.']],
             'ui_widths': [0.6, 1.4, 1, 0.8, 1.3, 2.6],
             'events': [['Bấm biểu tượng Cấu hình cột hiển thị', 'Click', 'After:\n– Mở cửa sổ “Tuỳ chỉnh cột” với trạng thái bật/tắt và thứ tự cột hiện tại.'],
                        ['Tích / bỏ tích, kéo ☰ đổi thứ tự', 'Change', 'During:\n– Cột bị khóa không bỏ tích và không kéo được.'],
                        ['Bấm Lưu', 'Click', 'After:\n– Lưu cấu hình theo người dùng, bảng hiển thị lại theo cột và thứ tự mới, báo “Cập nhật thành công”.\n– Lỗi → báo “Thao tác thất bại”.'],
                        ['Bấm Đóng / ✕', 'Click', 'After:\n– Đóng cửa sổ, bảng giữ nguyên cấu hình cũ.']]},
        ],
        'quy_tac': [
            ('BR-01', 'Phạm vi dữ liệu theo công ty',
             ['Người dùng chỉ thấy và thao tác trên tài khoản thuộc công ty ghi trong hồ sơ nhân sự của mình.',
              'Bản ghi mới (kể cả Import) tự gắn công ty của người tạo.',
              'Người dùng chưa gắn công ty: danh sách rỗng, không tạo được — thông báo “Tài khoản đăng nhập chưa gắn công ty, không thể thao tác”.'],
             ['Xem danh sách tài khoản ngân hàng', 'Thêm mới tài khoản ngân hàng', 'Import file tài khoản ngân hàng', 'Xuất danh sách ra Excel']),
            ('BR-02', 'Ràng buộc trùng số tài khoản',
             ['Số tài khoản không được trùng trên TOÀN HỆ THỐNG, không phân biệt công ty; khi sửa loại trừ chính bản ghi.',
              'Thông báo khi trùng: “Số tài khoản đã tồn tại”.'],
             ['Thêm mới tài khoản ngân hàng', 'Chỉnh sửa tài khoản ngân hàng', 'Import file tài khoản ngân hàng']),
            ('BR-03', 'Chủ tài khoản in hoa',
             ['Chủ tài khoản được tự động lưu dạng CHỮ IN HOA, bất kể người dùng gõ thế nào.'],
             ['Thêm mới tài khoản ngân hàng', 'Chỉnh sửa tài khoản ngân hàng', 'Import file tài khoản ngân hàng']),
            ('BR-04', 'Quan hệ với ngân hàng, chi nhánh, tiền tệ',
             ['Chi nhánh phải thuộc đúng ngân hàng đã chọn và đang Hoạt động: “Chi nhánh không thuộc ngân hàng đã chọn hoặc đã bị khóa”.',
              'Chỉ chọn mới được ngân hàng / tiền tệ đang Hoạt động: “Ngân hàng không tồn tại hoặc đã bị khóa”, “Loại tiền tệ không tồn tại hoặc đã bị khóa”.',
              'Bản ghi đang giữ ngân hàng / tiền tệ đã khóa vẫn hiển thị đúng (kèm 🔒) và lưu lại được.'],
             ['Thêm mới tài khoản ngân hàng', 'Chỉnh sửa tài khoản ngân hàng']),
            ('BR-05', 'Tài khoản đang Khóa',
             ['Không sửa được (máy chủ chặn): “Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.”; phải Mở khóa trước.',
              'Danh mục không có chức năng Xóa.'],
             ['Chỉnh sửa tài khoản ngân hàng', 'Khóa / Mở khóa tài khoản ngân hàng']),
            ('BR-06', 'Giới hạn Import',
             ['Mỗi lần nhập tối đa 500 dòng dữ liệu.',
              'Tra ngân hàng theo mã, chi nhánh theo tên trong ngân hàng đó, tiền tệ theo mã; không tìm thấy thì báo lỗi dòng, không tự tạo danh mục nền.',
              'Cột Trạng thái nhận “Hoạt động” hoặc “Khóa”; bỏ trống = Hoạt động.'],
             ['Import file tài khoản ngân hàng']),
            ('BR-07', 'Ghi lịch sử thay đổi',
             ['Mọi thao tác Tạo mới, Thay đổi thông tin, Khóa, Mở khóa đều ghi lịch sử kèm người thực hiện.'],
             ['Thêm mới tài khoản ngân hàng', 'Chỉnh sửa tài khoản ngân hàng', 'Khóa / Mở khóa tài khoản ngân hàng', 'Xem lịch sử thay đổi']),
        ],
    },

    'loi_code': [
        'File xuất BỎ QUA bộ lọc Chi nhánh: runExport (pages/finance/account-banks/index.vue) chỉ gửi status, keyword, sort_by, sort_desc — thiếu bank_branch, trong khi loadData có gửi → đang lọc theo Chi nhánh mà xuất ra vẫn đủ mọi chi nhánh.',
        'Import đánh số dòng lệch: CompanyAccountService::validateRows ghi row = index + 2 và “trùng với dòng N trong file” dùng index + 2, trong khi dữ liệu file mẫu bắt đầu ở dòng Excel 3 và bảng xem trước đánh STT từ 1 → N lệch 1 so với dòng Excel thật.',
        'Import nhận cả ngân hàng / tiền tệ đang KHÓA: importSnapshot() lấy toàn bộ banks/currencies không lọc status, trong khi cửa sổ Tạo mới chỉ cho chọn bản ghi đang Hoạt động (CompanyAccountRequest exists ... status) → hai đường nhập không nhất quán.',
        'Import khi người dùng CHƯA gắn công ty: store() chặn bằng “Tài khoản đăng nhập chưa gắn công ty, không thể thao tác” nhưng import()/createOrUpdate không kiểm tra → tạo bản ghi company_id = NULL, không ai nhìn thấy.',
        'Ô Số tài khoản và Chủ tài khoản ở cửa sổ Tạo / Sửa KHÔNG có giới hạn độ dài (CompanyAccountRequest thiếu rule max:255) trong khi cột lưu tối đa 255 ký tự → nhập quá 255 ký tự sẽ lỗi hệ thống thay vì báo “Vui lòng nhập tối đa 255 ký tự.”; Import thì đã chặn 255.',
        'Khóa / Mở khóa không kiểm tra trạng thái hiện tại (CompanyAccountController::lock/unlock): bản ghi đã bị người khác khóa trước đó, bấm Khóa lần nữa vẫn báo “Khóa thành công” và ghi thêm một dòng lịch sử, không báo “Dữ liệu đã thay đổi, vui lòng tải lại”. Hai route này còn dùng GET cho thao tác ghi dữ liệu.',
        'Import nhận cả CHI NHÁNH đang khóa (importSnapshot lấy bank_branches không lọc status), trong khi cửa sổ Tạo mới chặn “Chi nhánh không thuộc ngân hàng đã chọn hoặc đã bị khóa”.',
    ],
}

# ---- Sửa tab testcase "11. Danh mục tài khoản ngân hàn" ----
CFG['tc'] = {
    'tab': '11. Danh mục tài khoản ngân hàn',
    'hdr_row': 150,           # "IX. LỊCH SỬ THAY ĐỔI & LUỒNG TỔNG THỂ"
    'blocks': [{'after': 162,  # TC_09.012 — case cuối của tab
                'groups': [('X', 'XUẤT EXCEL (bổ sung 25/09/2026)', 10, 'export'),
                           ('XI', 'IMPORT TỪ FILE EXCEL (bổ sung 25/09/2026)', 11, 'import')]}],
    'import_rows_dung': 'File mẫu điền 3 tài khoản hợp lệ (DOC-0001 VIETCOMBANK – Hoàn Kiếm – VNĐ; DOC-0002 MB – Long Biên – USD; DOC-0003 BIDV – Sở giao dịch số 3 – VNĐ, Trạng thái Khóa), chưa có trong danh mục',
    'import_loi_data': {
        'Số tài khoản không được để trống': 'Số tài khoản: (để trống)',
        'Số tài khoản bị trùng với dòng N trong file': 'Hai dòng cùng số tài khoản DOC-0001',
        'Số tài khoản đã tồn tại trong hệ thống': 'Số tài khoản: 88838888 (đã có)',
        'Chủ tài khoản không được để trống': 'Chủ tài khoản: (để trống)',
        'Mã ngân hàng không được để trống': 'Mã ngân hàng: (để trống)',
        'Không tìm thấy ngân hàng: X': 'Mã ngân hàng: NHKHONGCO',
        'Chi nhánh không được để trống': 'Chi nhánh: (để trống)',
        'Không tìm thấy chi nhánh "X" thuộc ngân hàng Y': 'Mã ngân hàng: VIETCOMBANK; Chi nhánh: Long Biên (chi nhánh của MB)',
        'Mã tiền tệ không được để trống': 'Mã tiền tệ: (để trống)',
        'Không tìm thấy tiền tệ: X': 'Mã tiền tệ: XYZ',
        'Trạng thái chỉ nhận "Hoạt động" hoặc "Khóa"': 'Trạng thái: Tạm dừng',
    },
    'export_extra': [
        ('File xuất theo bộ lọc Chi nhánh', 'P0', 'Đang lọc ô Chi nhánh = Hoàn Kiếm, danh sách còn vài tài khoản.',
         '1. Nhập Hoàn Kiếm vào ô Chi nhánh\n2. Bấm Xuất Excel → Xuất file\n3. Đọc cột Chi nhánh trong file', 'Chi nhánh: Hoàn Kiếm',
         '- File CHỈ có các tài khoản thuộc chi nhánh chứa “Hoàn Kiếm”\n- Số dòng bằng tổng số bản ghi ở cuối bảng'),
        ('Chỉ xuất tài khoản của công ty mình', 'P0', 'Hệ thống có tài khoản của công ty khác.',
         '1. Không lọc gì, bấm Xuất Excel → Xuất file\n2. Đối chiếu file với danh sách', '',
         '- File chỉ có tài khoản thuộc công ty của người đăng nhập, không lộ tài khoản công ty khác'),
    ],
    'import_extra': [
        ('Chủ tài khoản và mã viết thường', 'P1', 'File có dòng ghi Chủ tài khoản chữ thường, Mã ngân hàng “mb”, Mã tiền tệ “usd”.',
         '1. Load, Validate, Import\n2. Xem dòng vừa tạo', 'Chủ tài khoản: doc-công ty kiểm thử 02; Mã NH: mb; Mã tiền tệ: usd',
         '- Validate hợp lệ (mã không phân biệt hoa thường)\n- Chủ tài khoản hiển thị CHỮ IN HOA, Ngân hàng là MB, Loại tiền tệ là USD'),
        ('Tài khoản import gắn đúng công ty người nhập', 'P0', 'Vừa import thành công.',
         '1. Đăng nhập tài khoản thuộc công ty khác\n2. Tìm số tài khoản vừa import', '',
         '- Người thuộc công ty khác KHÔNG thấy các tài khoản vừa import'),
        ('Import tài khoản gắn ngân hàng đang Khóa', 'P1', 'Danh mục ngân hàng có một ngân hàng đang Khóa (đã có chi nhánh).',
         '1. File ghi Mã ngân hàng của ngân hàng đang Khóa\n2. Load, Validate', '',
         '- Dòng đó báo lỗi, không được import (giống cửa sổ Tạo mới chỉ cho chọn ngân hàng đang Hoạt động)'),
    ],
    'edits': [
        ('I31', '- Có nút Tạo mới (nền xanh, dấu cộng)\n- Có nút Xuất Excel và nút Import Excel\n- Có nút Cấu hình cột hiển thị (biểu tượng cột)\n- Không có nút In'),
        ('B2', 'Quản lý danh mục tài khoản ngân hàng CỦA CÔNG TY (không phải tài khoản cá nhân của nhân viên): số tài khoản, chủ tài khoản, ngân hàng, chi nhánh, loại tiền tệ và trạng thái sử dụng.\n Dữ liệu của màn này là nguồn cho các nghiệp vụ thu chi, đề nghị thanh toán và các chứng từ cần chọn tài khoản nhận / chuyển tiền của công ty.\n Người dùng làm được: xem danh sách, tìm kiếm, lọc, tạo mới, sửa, xem chi tiết, khóa / mở khóa, xem lịch sử thay đổi, Xuất Excel và Import Excel (bổ sung 25/09/2026, xem nhóm X, XI). Màn hình KHÔNG có chức năng Xóa và In.'),
        ('B8', 'Màn hình dùng ĐÚNG MỘT quyền: "Quản lý danh mục tài khoản ngân hàng" (nhóm quyền Danh mục tài chính).\n- Có quyền: nhìn thấy mục menu, xem danh sách và làm được mọi thao tác (tạo mới, sửa, khóa, mở khóa, xem lịch sử, Xuất Excel, Import Excel).\n- Không có quyền: mục menu bị ẩn; gõ thẳng đường dẫn thì hệ thống từ chối, danh sách không tải được; gọi thẳng chức năng xuất / import cũng bị từ chối.\n Ngoài quyền trên, còn một lớp giới hạn nữa KHÔNG phụ thuộc quyền: người dùng chỉ thấy tài khoản của công ty mình (lấy theo công ty ghi trong hồ sơ nhân sự) — áp dụng cả cho file xuất. Không có phân quyền theo phòng ban hay bộ phận.'),
    ],
    'clear_k': [31],
}

CFG['tc_ngoai_pham_vi'] = [
    'Ô B6 và mục 3–5 của ô ghi chú B10: tên Ngân hàng / Chi nhánh trên danh sách nay đọc SỐNG từ Danh mục ngân hàng (đổi tên danh mục thì danh sách đổi theo), không còn “hiện tên cũ tới khi mở Sửa và lưu lại”.',
    'Mục 4 ô B10 + TC_04.019 (hàng 100), TC_04.020 (hàng 101): mở Sửa tài khoản có ngân hàng / tiền tệ đã khóa nay GIỮ nguyên giá trị kèm 🔒 và lưu lại được — không còn xoá trắng + thông báo chọn lại.',
    'Ô B4: “ngân hàng / tiền tệ đang khóa KHÔNG xuất hiện trong ô chọn” vẫn đúng với lựa chọn mới, nhưng bản ghi đang dùng thì vẫn hiện kèm 🔒.',
    'TC_04.002 (hàng 83) / cửa sổ Tạo mới: nay có thêm nút “Lưu và tiếp tục” — HDSD cũ ghi chỉ có Lưu và Đóng.',
    'TC_04.029 (hàng 110): cửa sổ nay hỏi “Thông tin chưa lưu” khi đóng lúc đang nhập dở — kiểm lại expected.',
    'TC_09.012 (hàng 162): vẫn đúng (không có Xóa).',
]
