# -*- coding: utf-8 -*-
# Cấu hình tài liệu màn Danh mục khu vực — MẪU CHUẨN cho các màn danh mục khác.
# Nguồn: code gop_db 25/09/2026 (FE pages/human/areas, components/AreasModel.vue; BE AreaController/AreaService/CreateAreasRequest).
# Không ghi URL. Chữ UI / message lấy nguyên văn code.

DT = 'khu vực'

CFG = {
    'slug': 'areas',
    'ten': 'Danh mục khu vực',
    'doi_tuong': DT,
    'file_hdsd': 'HDSD_Danh mục khu vực.docx',
    'file_srs': 'SRS - Danh mục khu vực.docx',
    'menu': [('Danh mục', 'menu_phanhe'), ('Địa lý', 'menu_nhom'), ('Khu vực', 'menu_muc')],

    'thuat_ngu': [
        ['Khu vực', 'Cấp thứ hai của cây địa chỉ, trực thuộc một Quốc gia. Mỗi Tỉnh/TP thuộc về một khu vực.'],
        ['Quốc gia', 'Quốc gia mà khu vực trực thuộc, chọn từ Danh mục quốc gia.'],
        ['Trạng thái Hoạt động', 'Khu vực dùng được ở các màn nghiệp vụ khác.'],
        ['Trạng thái Khóa', 'Khu vực không còn chọn được ở nơi khác nhưng vẫn nằm trong danh mục và vẫn xem được lịch sử.'],
    ],
    'phien_ban': [
        ['1.0', '17/08/2026', 'Đội phát triển phần mềm', 'Tạo mới cho màn Danh mục khu vực.'],
        ['1.1', '25/09/2026', 'Đội phát triển phần mềm', 'Cập nhật theo phiên bản hiện tại: bổ sung Xem chi tiết, Xuất Excel, Import Excel, Tùy chỉnh cột, ô Trạng thái trong cửa sổ Tạo/Sửa; trình bày theo mẫu tài liệu danh mục chung.'],
    ],
    'muc_dich': [
        'Danh mục khu vực là nơi khai báo các khu vực của từng quốc gia (ví dụ Miền Bắc, Miền Trung, Miền Nam). Khu vực là cấp trung gian giữa Quốc gia và Tỉnh/TP trong cây địa chỉ dùng chung của toàn hệ thống.',
    ],
    'quyen': {
        'truoc': ['Phân quyền ai được quyền tạo/ sửa/ xóa/ khóa/ mở khóa sẽ được cập nhật ngay sau khi có tài liệu phân quyền chi tiết của hệ thống.',
                  'Tại thời điểm xây dựng HDSD hiện tại, ai cũng được quyền truy cập màn hình danh mục khu vực và quyền tạo/sửa/xóa/khóa/mở khóa, import, xuất Excel.'],
        'rows': [],
    },

    'danh_sach': {
        'mo_ta_vao': 'Hệ thống hiển thị danh sách khu vực hiện có, mặc định 10 dòng mỗi trang.',
        'bo_cuc': [
            'Khu vực tìm kiếm và lọc — ô tìm kiếm nhanh, ô Quốc gia, ô Trạng thái, nút Tìm kiếm và Làm mới.',
            'Thanh công cụ — nút Tạo mới, nút Xuất Excel, nút Import Excel và biểu tượng Cấu hình cột hiển thị.',
            'Bảng danh sách — các cột thông tin, cột Hành động ở cuối, và phân trang bên dưới.',
        ],
        'cot': [
            ['STT', 'Số thứ tự, chạy liên tục qua các trang. Luôn hiển thị.'],
            ['Khu vực', 'Tên khu vực. Luôn hiển thị, sắp xếp được. Bấm vào tên để mở cửa sổ Xem khu vực.'],
            ['Quốc gia', 'Quốc gia mà khu vực trực thuộc.'],
            ['Người cập nhật', 'Người sửa bản ghi gần nhất. Mặc định ẩn.'],
            ['Ngày cập nhật', 'Thời điểm sửa gần nhất, dạng dd/mm/yyyy hh:mm. Mặc định ẩn, sắp xếp được.'],
            ['Người tạo', 'Người đã thêm bản ghi.'],
            ['Ngày tạo', 'Thời điểm thêm, dạng dd/mm/yyyy hh:mm, sắp xếp được.'],
            ['Trạng thái', 'Nhãn Hoạt động hoặc Khóa.'],
            ['Hành động', 'Các nút thao tác của dòng (xem mục 4).'],
        ],
        'hanh_dong': {
            'intro': 'Trên mỗi dòng, cột Hành động có các nút:',
            'bullets': [
                'Biểu tượng bút chì {icon:btn_sua} — mở cửa sổ Sửa khu vực. Chỉ hiện khi khu vực đang Hoạt động.',
                'Biểu tượng thùng rác {icon:btn_xoa} — xóa khu vực. Chỉ hiện khi khu vực đang Hoạt động và CHƯA có Tỉnh/TP nào trực thuộc.',
                'Khóa / Mở khóa — đổi trạng thái khu vực.',
                'Lịch sử — mở cửa sổ Lịch sử thay đổi.',
                'Có từ 4 nút trở lên thì 2 nút đầu hiện thẳng, các nút còn lại nằm trong nút ba chấm {icon:btn_bacham} “Hành động khác”.',
            ],
            'anh': 'Các nút ở cột Hành động của một khu vực',
            'luu_y': ['Lưu ý quan trọng: với bản ghi ĐÃ KHÓA, nút Sửa và Xóa sẽ BIẾN MẤT, chỉ còn Mở khóa và Lịch sử. Muốn sửa lại, Người dùng phải Mở khóa trước.'],
        },
        'phan_trang': [
            'Cuối bảng có dòng “Hiển thị a–b / N”: N là tổng số khu vực khớp bộ lọc đang áp dụng, không phải tổng toàn danh mục.',
            'Ô Số dòng/trang có các mức 5, 10, 20, 50, 100 (mặc định 10). Đổi số dòng thì hệ thống tự quay về trang 1.',
            'Các cột sắp xếp được: Khu vực, Ngày tạo, Ngày cập nhật. Bấm tiêu đề cột để sắp xếp, bấm lần hai để đảo chiều. Thứ tự sắp xếp được giữ nguyên khi chuyển trang.',
        ],
    },

    'loc': {
        'buoc2': 'Bước 2: Nhập chữ vào ô tìm kiếm nhanh hoặc chọn giá trị ở ô Quốc gia, Trạng thái.',
        'rows': [
            ['Ô tìm kiếm nhanh', 'Tìm theo TÊN khu vực (gõ một phần tên cũng ra). Nhấn Enter hoặc bấm Tìm kiếm để lọc.'],
            ['Quốc gia', 'Chọn một quốc gia để chỉ xem khu vực của quốc gia đó. Lọc ngay khi chọn.'],
            ['Trạng thái', 'Hoạt động hoặc Khóa. Bỏ trống thì hiện cả hai trạng thái. Lọc ngay khi chọn.'],
        ],
        'ap_dung': [
            'Các tiêu chí kết hợp với nhau theo kiểu VÀ — chỉ bản ghi thỏa đồng thời tất cả các tiêu chí mới hiện ra. Mỗi lần đổi tiêu chí, danh sách quay về trang 1.',
            'Bấm {icon:btn_lammoi} để xóa toàn bộ tiêu chí; danh sách nạp lại đầy đủ ngay lập tức.',
        ],
        'anh_ket_qua': 'Kết quả tìm nhanh theo tên khu vực (gõ “Miền”)',
    },

    'form': {
        'kieu': 'popup',
        'buoc_tao': [
            'Bước 1: Truy cập vào màn hình Danh mục khu vực.',
            'Bước 2: Bấm {icon:btn_taomoi}. Hệ thống mở cửa sổ “Tạo khu vực”.',
            'Bước 3: Nhập/ chọn đầy đủ thông tin: Tên khu vực, Quốc gia, Trạng thái.',
            'Bước 4: Bấm {icon:btn_luu} để lưu và đóng cửa sổ, hoặc {icon:btn_luutieptuc} để lưu rồi nhập tiếp khu vực khác.',
        ],
        'anh_tao': 'Cửa sổ Tạo khu vực',
        'truong': [
            ['Tên khu vực', 'Ô nhập giá trị', 'Có', 'Trống', 'Tối đa 255 ký tự, duy nhất toàn hệ thống. Bỏ trống báo “Bắt buộc phải nhập”; trùng báo “Tên khu vực này đã tồn tại”.'],
            ['Quốc gia', 'Ô chọn giá trị', 'Có', 'Trống', 'Chỉ liệt kê quốc gia đang Hoạt động. Khu vực đang dùng một quốc gia đã khóa vẫn hiện đúng tên quốc gia đó kèm biểu tượng 🔒. Bỏ trống báo “Bắt buộc phải nhập”.'],
            ['Trạng thái', 'Ô chọn giá trị', 'Có', 'Hoạt động', 'Chỉ chọn 1 trong 2 giá trị: Hoạt động / Khóa.'],
        ],
        'nut': [
            ['Lưu', 'Ghi bản ghi rồi đóng cửa sổ, báo “Thêm mới thành công” (hoặc “Cập nhật thành công” khi sửa) và nạp lại danh sách.'],
            ['Lưu và tiếp tục', 'Ghi bản ghi nhưng GIỮ cửa sổ mở và xóa trắng các ô để nhập tiếp. Chỉ có khi Tạo mới.'],
            ['Đóng', 'Đóng cửa sổ, không ghi gì. Nếu đã nhập dở, hệ thống hỏi “Thông tin chưa lưu” — “Bạn có thông tin chưa lưu. Có chắc chắn muốn thoát?” (Thoát / Ở lại).'],
        ],
        'loi': [
            ['Bắt buộc phải nhập', 'Chưa nhập Tên khu vực hoặc chưa chọn Quốc gia.'],
            ['Tên khu vực này đã tồn tại', 'Đã có khu vực khác cùng tên trên toàn hệ thống. Hãy kiểm tra lại danh sách trước khi thêm.'],
            ['Vui lòng nhập tối đa 255 ký tự.', 'Tên khu vực quá dài.'],
            ['Vui lòng kiểm tra lại dữ liệu nhập', 'Thông báo chung khi còn ô bị lỗi; xem các ô báo đỏ trong cửa sổ.'],
        ],
    },

    'sua': {
        'buoc': [
            'Bước 1: Truy cập vào màn hình Danh mục khu vực.',
            'Bước 2: Bấm nút {icon:btn_sua} ở cột Hành động của khu vực cần sửa.',
            'Bước 3: Hệ thống hiển thị cửa sổ “Sửa khu vực” với dữ liệu hiện tại.',
            'Bước 4: Cập nhật các thông tin cần sửa (quy tắc nhập như Thêm mới).',
            'Bước 5: Bấm {icon:btn_luu} để xác nhận thay đổi hoặc Đóng nếu muốn hủy.',
        ],
        'anh': 'Cửa sổ Sửa khu vực',
        'ghi_chu': [
            'Giữ nguyên tên của chính khu vực đang sửa thì không bị báo trùng.',
            'Khu vực đang Khóa không có nút Sửa. Nếu khu vực vừa bị người khác khóa, bấm Lưu sẽ nhận thông báo “Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.”',
            'Đổi tên quốc gia ở Danh mục quốc gia thì cột Quốc gia của khu vực tự hiển thị tên mới.',
        ],
    },
    'xoa': {
        'buoc': [
            'Bước 1: Ở cột Hành động, Người dùng bấm {icon:btn_xoa}.',
            'Bước 2: Hệ thống hiện hộp xác nhận “Xóa khu vực” — “Bạn có chắc muốn xóa khu vực "…"?”. Bấm {icon:btn_confirm_xoa} để xác nhận: hệ thống báo “Xoá khu vực thành công”, bản ghi biến mất khỏi danh sách.',
            'Bấm {icon:btn_huy} nếu bấm nhầm. Không có gì thay đổi.',
        ],
        'anh': 'Hộp xác nhận xóa khu vực',
        'ghi_chu': ['Nút Xóa chỉ hiện khi khu vực đang Hoạt động và CHƯA có Tỉnh/TP nào trực thuộc. Khu vực đã có Tỉnh/TP bên dưới thì dùng Khóa thay cho Xóa.'],
    },
    'khoa': {
        'y_nghia': [
            'Bản ghi VẪN nằm trong danh sách, cột Trạng thái hiện chữ Khóa.',
            'Vẫn xem được chi tiết và lịch sử thay đổi của bản ghi.',
            'Khu vực đã khóa không còn xuất hiện ở ô chọn khu vực của các màn khác (ví dụ Danh mục Tỉnh/TP); Tỉnh/TP đang dùng khu vực đó vẫn giữ nguyên.',
            'Nút Sửa và Xóa của dòng đó biến mất.',
        ],
        'buoc_khoa': [
            'Bước 1: Ở cột Hành động, Người dùng chọn Khóa (trong nút ba chấm nếu dòng có nhiều nút).',
            'Bước 2: Hệ thống hiện hộp xác nhận “Khóa khu vực” — “Bạn có chắc muốn khóa khu vực "…"?”. Bấm Khóa để xác nhận; hệ thống báo “Khóa thành công”, cột Trạng thái đổi thành Khóa. Bấm Hủy nếu bấm nhầm.',
        ],
        'buoc_mo': [
            'Bước 1: Ở cột Hành động của khu vực đang Khóa, Người dùng chọn Mở khóa.',
            'Bước 2: Bấm Mở khóa trong hộp xác nhận “Mở khóa khu vực”. Hệ thống báo “Mở khóa thành công”, cột Trạng thái đổi thành Hoạt động. Bấm Hủy nếu bấm nhầm.',
        ],
        'ghi_chu': ['Có thể khóa ngay trong cửa sổ Sửa bằng cách chọn Trạng thái = Khóa rồi Lưu. Nếu bản ghi vừa bị người khác đổi trạng thái, hệ thống báo “Trạng thái đã bị thay đổi. Vui lòng load lại trang”.'],
    },
    'lich_su': {
        'buoc': [
            'Xem từ màn danh sách: ở cột Hành động, Người dùng chọn Lịch sử.',
            'Xem từ màn chi tiết: bấm vào tên khu vực để mở cửa sổ Xem khu vực, khối Lịch sử nằm ở cuối cửa sổ.',
        ],
        'ghi_chu': ['Cửa sổ có bộ lọc riêng (loại hành động, người thực hiện, khoảng thời gian) để thu hẹp danh sách khi bản ghi có nhiều lần thay đổi.'],
    },
    'chi_tiet': {
        'buoc': ['Bước 1: Truy cập vào màn hình Danh mục khu vực.',
                 'Bước 2: Bấm vào tên khu vực ở cột Khu vực. Hệ thống mở cửa sổ “Xem khu vực”.'],
        'ghi_chu': ['Cửa sổ hiển thị Tên khu vực, Quốc gia và Trạng thái ở chế độ chỉ đọc (không gõ được, không có nút Lưu), kèm khối Lịch sử ở cuối. Khu vực đang Khóa vẫn xem được bình thường.'],
    },
    'xuat': {
        'buoc': [
            'Bước 1: Lọc danh sách theo đúng dữ liệu cần lấy (xem PHẦN 2). File xuất ra chạy theo đúng bộ lọc đang áp dụng.',
            'Bước 2: Bấm nút {icon:btn_xuatexcel}. Hệ thống mở cửa sổ “Chọn trường xuất file”.',
            'Bước 3: Tích chọn, kéo biểu tượng ☰ để đổi vị trí các trường cần xuất. Mặc định hệ thống tích sẵn đúng những cột đang hiển thị trên bảng.',
            'Bước 4: Bấm {icon:btn_xuatfile}. Hệ thống tải về file danh_muc_khu_vuc.xlsx và báo “Xuất Excel thành công”.',
        ],
        'truong': 'Chọn nhiều trường: Tên khu vực, Quốc gia, Trạng thái, Người tạo, Ngày tạo, Người cập nhật, Ngày cập nhật.',
        'ghi_chu': ['Lưu ý: file xuất chứa TOÀN BỘ kết quả của bộ lọc (tối đa 10,000 dòng), không chỉ các dòng của trang đang xem.'],
    },
    'import': {
        'tieu_de': 'Import khu vực',
        'file': 'Mau_import_khu_vuc.xlsx',
        'cot_text': 'Tên khu vực (bắt buộc), Tên quốc gia (bắt buộc, chọn trong danh sách sổ xuống)',
        'toast': 'Import thành công N khu vực.',
        'loi': [
            ['Tên khu vực không được để trống', 'Dòng đó bỏ trống cột Tên khu vực.'],
            ['Tên khu vực tối đa 255 ký tự', 'Tên quá dài, rút gọn lại.'],
            ['Tên khu vực bị trùng với dòng N trong file', 'Trong chính file có hai dòng cùng tên. Xoá bớt một dòng.'],
            ['Tên khu vực đã tồn tại trong hệ thống', 'Danh mục đã có khu vực trùng tên.'],
            ['Tên quốc gia không được để trống', 'Dòng đó bỏ trống cột Tên quốc gia.'],
            ['Không tìm thấy quốc gia: X', 'Tên quốc gia ghi sai, không có trong Danh mục quốc gia.'],
        ],
        'ghi_chu': ['Lưu ý: khu vực nhập từ Excel luôn được tạo ở trạng thái Hoạt động, người tạo là chính người thực hiện nhập. Mỗi lần nhập tối đa 500 dòng; file dài hơn hệ thống báo “File có X dòng dữ liệu, vượt quá giới hạn 500 dòng mỗi lần import. Vui lòng tách file và import nhiều lần.”'],
    },
    'tuy_chinh_cot': {'cot_khoa': 'Ba cột STT, Khu vực và Hành động'},

    'shots': {'list': '01_list.png', 'rowmenu': '03_rowmenu.png', 'filter': 'filter.png', 'filter_result': '04_filter_result.png',
              'create': '10_create.png', 'create_error': '11_create_error.png', 'edit': '12_edit.png',
              'delete': '13_delete.png', 'lock': '14_lock.png', 'unlock': '15_unlock.png', 'history': '16_history.png',
              'detail': '17_detail.png', 'export': '20_export.png', 'import_open': '21_import_open.png',
              'import_loaded': '22_import_loaded.png', 'import_validated': '23_import_validated.png', 'colcfg': '25_colcfg.png'},

    'uml': {
        'mains': [('FR-01', 'Xem danh sách khu vực', 'view'), ('FR-03', 'Thêm mới khu vực', 'crud'),
                  ('FR-04', 'Chỉnh sửa khu vực', 'crud'), ('FR-05', 'Xóa khu vực', 'action'),
                  ('FR-06', 'Khóa / Mở khóa khu vực', 'action'), ('FR-08', 'Import file khu vực', 'io'),
                  ('FR-09', 'Xuất danh sách khu vực ra Excel', 'io')],
        'subs': [('FR-02', 'Tìm kiếm và lọc khu vực', 'view'), ('FR-10', 'Xem chi tiết khu vực', 'view'),
                 ('FR-11', 'Tùy chỉnh cột hiển thị', 'view'), ('FR-07', 'Xem lịch sử thay đổi', 'view')],
        'rieng': [('FR-10', 'Xem chi tiết khu vực', 'view')],
    },

    'srs': {
        'muc_dich': ['Là căn cứ nghiệm thu chức năng.',
                     'Làm rõ ràng buộc trùng tên khu vực (duy nhất toàn hệ thống) và quan hệ Quốc gia → Khu vực → Tỉnh/TP.'],
        'quyen_truoc': ['Danh sách quyền sẽ được cập nhật sau khi có tài liệu phân quyền chi tiết của hệ thống. Tại thời điểm xây dựng SRS, màn hình chưa gắn quyền; mọi người dùng đã đăng nhập đều thực hiện được các chức năng.'],
        'quyen_rows': [['(chưa khai báo quyền nào)', 'Sẽ cập nhật sau khi có tài liệu phân quyền chi tiết']],
        'ma_tran': [['Chức năng', 'Người dùng đã đăng nhập']] + [[f, 'Chờ cập nhật theo ma trận phân quyền chi tiết'] for f in [
            'FR-01 Xem danh sách khu vực', 'FR-02 Tìm kiếm và lọc', 'FR-03 Thêm mới khu vực', 'FR-04 Chỉnh sửa khu vực',
            'FR-05 Xóa khu vực', 'FR-06 Khóa / Mở khóa khu vực', 'FR-07 Xem lịch sử thay đổi', 'FR-08 Import file khu vực',
            'FR-09 Xuất danh sách ra Excel', 'FR-10 Xem chi tiết khu vực', 'FR-11 Tùy chỉnh cột hiển thị']],
        'ma_tran_widths': [2.4, 2.4],
        'fr': [
            {'ten': 'Xem danh sách khu vực',
             'qtc': 'Màn Danh sách, Sắp xếp dữ liệu bảng, Phân trang và Cấu hình cột. Chỉ bổ sung các quy tắc riêng của Danh mục khu vực tại phần mô tả chi tiết.',
             'gioi_thieu': [['Tên chức năng', 'Xem danh sách khu vực'],
                            ['Mô tả', 'Hiển thị toàn bộ khu vực trong danh mục, có phân trang và sắp xếp.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Điều kiện ban đầu', 'Người dùng đã đăng nhập vào hệ thống.'],
                            ['Dòng sự kiện chính', '1. Người dùng vào menu Danh mục → Địa lý → Khu vực.\n2. Hệ thống nạp trang đầu tiên của danh sách (10 dòng).\n3. Bảng hiển thị dữ liệu kèm tổng số bản ghi.'],
                            ['Dòng sự kiện phụ', '• Không có bản ghi khớp → bảng hiện “Không có dữ liệu phù hợp bộ lọc.”\n• Phiên đăng nhập hết hạn → điều hướng về màn đăng nhập.']],
             'anh': [('list', 'Màn Danh mục khu vực lúc mới truy cập')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Mô tả'],
                    ['1', 'STT', 'Table/Grid', 'Read-only', 'Số thứ tự, chạy liên tục qua các trang. Luôn hiển thị, không ẩn được.'],
                    ['2', 'Khu vực', 'Table/Grid', 'Read-only', 'Tên khu vực. Luôn hiển thị, sắp xếp được. Bấm vào tên mở cửa sổ Xem (xem 2.10).'],
                    ['3', 'Quốc gia', 'Table/Grid', 'Read-only', 'Tên quốc gia trực thuộc (đọc trực tiếp từ Danh mục quốc gia).'],
                    ['4', 'Người cập nhật', 'Table/Grid', 'Read-only', 'Mặc định ẩn.'],
                    ['5', 'Ngày cập nhật', 'Table/Grid', 'Read-only', 'dd/mm/yyyy hh:mm. Mặc định ẩn, sắp xếp được.'],
                    ['6', 'Người tạo', 'Table/Grid', 'Read-only', 'Người đã thêm bản ghi.'],
                    ['7', 'Ngày tạo', 'Table/Grid', 'Read-only', 'dd/mm/yyyy hh:mm, sắp xếp được.'],
                    ['8', 'Trạng thái', 'Badge', 'Read-only', 'Hoạt động hoặc Khóa.'],
                    ['9', 'Hành động', 'Table/Grid', 'Read-only', 'Sửa (khi Hoạt động), Xóa (khi Hoạt động và chưa có Tỉnh/TP trực thuộc), Khóa / Mở khóa, Lịch sử. Từ 4 nút trở lên thì 2 nút đầu hiện thẳng, còn lại trong nút ba chấm.'],
                    ['10', 'Nút Tạo mới', 'Button', 'Enable', 'Mở cửa sổ Tạo khu vực.'],
                    ['11', 'Nút Xuất Excel', 'Button', 'Enable', 'Mở cửa sổ Chọn trường xuất file (xem 2.9).'],
                    ['12', 'Nút Import Excel', 'Button', 'Enable', 'Mở cửa sổ Import khu vực (xem 2.8).'],
                    ['13', 'Biểu tượng Cấu hình cột hiển thị', 'Icon Button', 'Enable', 'Mở cửa sổ Tuỳ chỉnh cột (xem 2.11).'],
                    ['14', 'Phân trang', 'Pagination', 'Enable', 'Số dòng/trang 5 / 10 / 20 / 50 / 100, mặc định 10.']],
             'ui_widths': [0.6, 1.4, 0.9, 0.8, 3],
             'events': [['Mở màn hình', 'System', 'After:\n– Nạp trang đầu, hiển thị tổng số bản ghi.'],
                        ['Bấm tiêu đề cột sắp xếp được', 'Click', 'After:\n– Đổi chiều sắp xếp và nạp lại danh sách từ trang 1.'],
                        ['Chuyển trang', 'Click', 'Before:\n– Giữ nguyên bộ lọc và thứ tự sắp xếp.\nAfter:\n– Nạp dữ liệu trang mới, số thứ tự tiếp tục liên tục.'],
                        ['Đổi số dòng mỗi trang', 'Change', 'After:\n– Quay về trang 1 và nạp lại theo số dòng mới.']]},
            {'ten': 'Tìm kiếm và lọc',
             'qtc': 'Kịch bản tìm kiếm, Bộ lọc, Dropdown, Phân trang. Chỉ bổ sung các tiêu chí tìm kiếm/lọc riêng của Danh mục khu vực.',
             'gioi_thieu': [['Tên chức năng', 'Tìm kiếm và lọc danh sách'],
                            ['Mô tả', 'Thu hẹp danh sách bằng ô tìm kiếm nhanh, ô Quốc gia và ô Trạng thái.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Điều kiện ban đầu', 'Đang ở màn Danh mục khu vực.'],
                            ['Dòng sự kiện chính', '1. Người dùng nhập từ khóa và bấm Tìm kiếm / Enter, hoặc chọn Quốc gia / Trạng thái (lọc ngay).\n2. Hệ thống áp đồng thời mọi tiêu chí và nạp lại danh sách từ trang 1.'],
                            ['Dòng sự kiện phụ', '• Không có kết quả → bảng hiện thông báo không có dữ liệu.\n• Bấm Làm mới → xóa hết tiêu chí VÀ nạp lại danh sách đầy đủ ngay.']],
             'anh': [('filter', 'Khu vực tìm kiếm và lọc của màn Danh mục khu vực')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Phạm vi', 'Mô tả'],
                    ['1', 'Ô tìm kiếm nhanh', 'Textbox', 'Enable', '0–255 ký tự', 'Placeholder “Tìm theo tên khu vực”. Tìm theo TÊN (khớp một phần).'],
                    ['2', 'Quốc gia', 'Dropdown', 'Enable', 'Danh mục quốc gia', 'Nhãn nổi. Bỏ trống thì hiện mọi quốc gia.'],
                    ['3', 'Trạng thái', 'Dropdown', 'Enable', 'Hoạt động / Khóa', 'Nhãn nổi. Bỏ trống thì hiện cả hai trạng thái.'],
                    ['4', 'Nút Tìm kiếm', 'Button', 'Enable', '–', 'Áp dụng các tiêu chí.'],
                    ['5', 'Nút Làm mới', 'Button', 'Enable', '–', 'Xóa hết tiêu chí VÀ nạp lại danh sách ngay.']],
             'ui_widths': [0.6, 1.2, 0.8, 0.7, 1.1, 2.6],
             'events': [['Bấm Tìm kiếm / Enter', 'Click', 'After:\n– Áp đồng thời các tiêu chí theo kiểu “và”, nạp lại bảng từ trang 1.'],
                        ['Chọn Quốc gia / Trạng thái', 'Change', 'After:\n– Lọc ngay, nạp lại bảng từ trang 1.'],
                        ['Bấm Làm mới', 'Click', 'After:\n– Xóa trắng mọi tiêu chí VÀ nạp lại danh sách đầy đủ.']]},
            {'ten': 'Thêm mới khu vực', 'uc': 'uc_fr03',
             'qtc': 'Màn Thêm mới, Validate dữ liệu, Thông báo và UI/UX. Logic ghi lịch sử áp dụng theo SRS Các quy tắc chung - Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Thêm mới khu vực'],
                            ['Mô tả', 'Thêm một khu vực mới thông qua cửa sổ nhập liệu.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập (chờ cập nhật theo phân quyền chi tiết).'],
                            ['Điều kiện ban đầu', 'Đang ở màn Danh mục khu vực.'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm Tạo mới.\n2. Hệ thống mở cửa sổ “Tạo khu vực”, Trạng thái mặc định Hoạt động.\n3. Người dùng nhập Tên khu vực, chọn Quốc gia và bấm Lưu.\n4. Hệ thống kiểm tra dữ liệu, ghi bản ghi mới và ghi lịch sử Tạo mới.\n5. Cửa sổ đóng, danh sách nạp lại, báo “Thêm mới thành công”.'],
                            ['Dòng sự kiện phụ', '• Thiếu trường bắt buộc hoặc trùng tên → báo lỗi đỏ dưới ô + toast “Vui lòng kiểm tra lại dữ liệu nhập”, cửa sổ KHÔNG đóng.\n• Bấm “Lưu và tiếp tục” → ghi bản ghi rồi giữ cửa sổ mở với các ô trống.\n• Bấm Đóng khi đã nhập dở → hỏi “Thông tin chưa lưu” (Thoát / Ở lại).'],
                            ['Yêu cầu đặc biệt', 'Cửa sổ có ba nút: Lưu, Lưu và tiếp tục, Đóng.']],
             'menu_them': ' => Tạo mới {icon:btn_taomoi}',
             'ghi_chu_layout': 'Cửa sổ Tạo khu vực được mở ngay trên màn hình danh sách.',
             'anh': [('create', 'Cửa sổ Tạo khu vực'), ('create_error', 'Lỗi đỏ ngay dưới ô còn thiếu')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Phạm vi', 'Bắt buộc', 'Mô tả'],
                    ['1', 'Tên khu vực', 'Textbox', 'Enable', '1–255 ký tự', 'Có', 'Duy nhất toàn hệ thống. Bỏ trống “Bắt buộc phải nhập”; trùng “Tên khu vực này đã tồn tại”; quá dài “Vui lòng nhập tối đa 255 ký tự.”'],
                    ['2', 'Quốc gia', 'Dropdown', 'Enable', 'Quốc gia đang Hoạt động', 'Có', 'Bỏ trống “Bắt buộc phải nhập”.'],
                    ['3', 'Trạng thái', 'Dropdown', 'Enable', 'Hoạt động / Khóa', 'Có', 'Mặc định Hoạt động.'],
                    ['4', 'Nút Lưu', 'Button', 'Enable', '', '', 'Ghi bản ghi rồi đóng cửa sổ.'],
                    ['5', 'Nút Lưu và tiếp tục', 'Button', 'Enable', '', '', 'Ghi bản ghi rồi giữ cửa sổ mở để nhập tiếp.'],
                    ['6', 'Nút Đóng', 'Button', 'Enable', '', '', 'Hủy bỏ, không ghi gì.']],
             'ui_widths': [0.6, 1.3, 0.8, 0.6, 1.1, 0.5, 2.3],
             'events': [['Bấm nút Tạo mới', 'Click', 'After:\n– Mở cửa sổ nhập liệu với các ô trống, Trạng thái = Hoạt động.'],
                        ['Bấm Lưu', 'Click', 'During:\n– Kiểm tra bắt buộc, độ dài, trùng tên toàn hệ thống.\n– Có lỗi → báo đỏ dưới ô, không thực hiện After.\nAfter:\n– Ghi bản ghi mới, ghi lịch sử Tạo mới.\n– Đóng cửa sổ, nạp lại danh sách, báo “Thêm mới thành công”.'],
                        ['Bấm Lưu và tiếp tục', 'Click', 'During:\n– Như nút Lưu.\nAfter:\n– Ghi bản ghi, xóa trắng các ô, GIỮ cửa sổ mở.'],
                        ['Bấm Đóng', 'Click', 'After:\n– Chưa nhập gì → đóng cửa sổ. Đã nhập → hỏi “Thông tin chưa lưu”.']]},
            {'ten': 'Chỉnh sửa khu vực', 'uc': 'uc_fr04',
             'qtc': 'Validate dữ liệu, Thông báo, Quy định chung về danh mục và Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Chỉnh sửa khu vực'],
                            ['Mô tả', 'Sửa thông tin một khu vực đã có. Dùng chung cửa sổ với Thêm mới.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Điều kiện ban đầu', 'Khu vực đang ở trạng thái Hoạt động.'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm biểu tượng bút chì ở dòng cần sửa.\n2. Hệ thống mở cửa sổ “Sửa khu vực” với dữ liệu hiện tại.\n3. Người dùng sửa và bấm Lưu.\n4. Hệ thống kiểm tra, ghi thay đổi và ghi lịch sử.\n5. Cửa sổ đóng, báo “Cập nhật thành công”.'],
                            ['Dòng sự kiện phụ', '• Giữ nguyên tên của chính bản ghi → không báo trùng.\n• Trùng tên với khu vực khác → báo “Tên khu vực này đã tồn tại”.\n• Bản ghi vừa bị người khác khóa → báo “Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.”']],
             'menu_them': ' => Sửa {icon:btn_sua}',
             'anh': [('edit', 'Cửa sổ Sửa khu vực')],
             'events': [['Bấm biểu tượng bút chì', 'Click', 'Before:\n– Bản ghi đã Khóa thì nút không hiển thị.\nAfter:\n– Mở cửa sổ với dữ liệu hiện tại.'],
                        ['Bấm Lưu', 'Click', 'During:\n– Kiểm tra như Thêm mới, bỏ qua trùng với chính bản ghi.\nAfter:\n– Ghi thay đổi, ghi lịch sử “Thay đổi thông tin” (đổi Trạng thái ghi “Khóa”/“Mở khóa”), báo “Cập nhật thành công”.']]},
            {'ten': 'Xóa khu vực', 'uc': 'uc_fr05',
             'qtc': 'Quy tắc Xóa, Thông báo, Quy định chung về danh mục và Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Xóa khu vực'],
                            ['Mô tả', 'Xóa hẳn một khu vực chưa có Tỉnh/TP trực thuộc.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Điều kiện ban đầu', 'Khu vực đang Hoạt động và chưa có Tỉnh/TP nào trực thuộc.'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm biểu tượng thùng rác.\n2. Hệ thống hiện hộp “Xóa khu vực” nêu rõ tên bản ghi.\n3. Người dùng bấm Xóa.\n4. Hệ thống xóa bản ghi, báo “Xoá khu vực thành công”, nạp lại danh sách.'],
                            ['Dòng sự kiện phụ', '• Bấm Hủy → đóng hộp, không thay đổi.\n• Khu vực đã có Tỉnh/TP hoặc đang Khóa → nút Xóa KHÔNG hiển thị.\n• Lỗi khi xóa → báo “Xoá khu vực thất bại”.']],
             'menu_them': ' => Xóa {icon:btn_xoa}',
             'anh': [('delete', 'Hộp xác nhận xóa khu vực')],
             'events': [['Bấm biểu tượng thùng rác', 'Click', 'After:\n– Hiện hộp xác nhận kèm tên bản ghi.'],
                        ['Bấm Xóa', 'Click', 'After:\n– Xóa bản ghi, nạp lại danh sách, báo thành công.'],
                        ['Bấm Hủy', 'Click', 'After:\n– Đóng hộp, không thay đổi.']]},
            {'ten': 'Khóa / Mở khóa khu vực', 'uc': 'uc_fr06',
             'qtc': 'Quy tắc Khóa/Mở khóa, Thông báo, Quy định chung về danh mục và Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Khóa / Mở khóa khu vực'],
                            ['Mô tả', 'Đổi trạng thái khu vực giữa Hoạt động và Khóa. Bản ghi đã Khóa vẫn nằm trong danh mục nhưng không chọn được ở màn khác.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Điều kiện ban đầu', 'Bản ghi cần đổi trạng thái đang có trong danh sách.'],
                            ['Dòng sự kiện chính', '1. Người dùng chọn Khóa (hoặc Mở khóa) ở cột Hành động.\n2. Hệ thống hiện hộp xác nhận nêu rõ tên bản ghi.\n3. Người dùng xác nhận.\n4. Hệ thống đổi trạng thái, ghi lịch sử, báo “Khóa thành công” / “Mở khóa thành công”.'],
                            ['Dòng sự kiện phụ', '• Bấm Hủy → không thay đổi.\n• Sau khi Khóa, nút Sửa và Xóa biến mất.\n• Bản ghi đã bị người khác đổi trạng thái → báo “Trạng thái đã bị thay đổi. Vui lòng load lại trang”.']],
             'menu_them': ' => Khóa / Mở khóa',
             'anh': [('lock', 'Hộp xác nhận khóa khu vực'), ('rowmenu', 'Các nút ở cột Hành động')],
             'events': [['Chọn Khóa / Mở khóa', 'Click', 'After:\n– Hiện hộp xác nhận kèm tên bản ghi.'],
                        ['Xác nhận', 'Click', 'During:\n– Bản ghi đã ở trạng thái đích → báo dữ liệu đã thay đổi, dừng.\nAfter:\n– Đổi trạng thái, KHÔNG xóa dữ liệu, ghi lịch sử, cập nhật cột Trạng thái và các nút.'],
                        ['Bấm Hủy', 'Click', 'After:\n– Đóng hộp, không thay đổi.']]},
            {'ten': 'Xem lịch sử thay đổi',
             'qtc': 'Quy tắc ghi lịch sử và hiển thị lịch sử. Chỉ bổ sung thông tin riêng của Danh mục khu vực nếu có.',
             'gioi_thieu': [['Tên chức năng', 'Xem lịch sử thay đổi'],
                            ['Mô tả', 'Liệt kê các lần thay đổi của một khu vực, kèm giá trị cũ → mới, người thực hiện và thời điểm.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Dòng sự kiện chính', '1. Người dùng chọn Lịch sử ở cột Hành động, hoặc mở cửa sổ Xem khu vực.\n2. Hệ thống mở cửa sổ “Lịch sử thay đổi: <tên>”, mốc mới nhất ở trên cùng.'],
                            ['Dòng sự kiện phụ', '• Bản ghi chưa từng sửa → “Chưa có lịch sử thao tác nào.”\n• Có bộ lọc theo loại hành động, người thực hiện, thời gian.']],
             'menu_them': ' => Lịch sử',
             'anh': [('history', 'Cửa sổ Lịch sử thay đổi của khu vực')]},
            {'ten': 'Import file khu vực', 'uc': 'uc_fr08',
             'qtc': 'Quy tắc Import file, Validate dữ liệu, Thông báo và Quy định chung về danh mục. Chỉ bổ sung mapping/validation riêng của Danh mục khu vực.',
             'gioi_thieu': [['Tên chức năng', 'Import file khu vực'],
                            ['Mô tả', 'Thêm nhiều khu vực cùng lúc từ file Excel mẫu, có bước Validate trước khi ghi.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Điều kiện ban đầu', 'Đang ở màn Danh mục khu vực và đã chuẩn bị file theo mẫu.'],
                            ['Dòng sự kiện chính', '1. Bấm Import Excel.\n2. Bấm Tải file mẫu (Mau_import_khu_vuc.xlsx), điền dữ liệu.\n3. Bấm Chọn file Excel rồi Load lên bảng.\n4. Bấm Validate; hệ thống kiểm tra từng dòng như quy tắc Thêm mới (mục 2.3), khóa dòng hợp lệ.\n5. Sửa dòng lỗi rồi Validate lại, hoặc bấm Bỏ dòng lỗi.\n6. Bấm Import; hệ thống ghi các dòng hợp lệ, báo “Import thành công N khu vực.”, đóng cửa sổ và nạp lại danh sách.'],
                            ['Dòng sự kiện phụ', '• File không phải .xlsx/.xls → “Vui lòng chọn file .xlsx hoặc .xls”.\n• Quá 500 dòng → “File có X dòng dữ liệu, vượt quá giới hạn 500 dòng mỗi lần import. Vui lòng tách file và import nhiều lần.”\n• Còn dòng lỗi → nút Import không bấm được.'],
                            ['Yêu cầu đặc biệt', 'Validate không ghi dữ liệu. Bản ghi import luôn ở trạng thái Hoạt động, người tạo là người thực hiện.']],
             'menu_them': ' => Import Excel {icon:btn_import}',
             'ghi_chu_layout': 'Cửa sổ Import được mở ngay trên màn hình danh sách.',
             'anh': [('import_open', 'Cửa sổ Import khu vực khi vừa mở'), ('import_loaded', 'Dữ liệu đã được load lên bảng xem trước'),
                     ('import_validated', 'Kết quả Validate — mỗi dòng lỗi nêu rõ lý do')],
             'bang_them': [('Quy tắc kiểm tra riêng của file Import', [['Cột', 'Quy tắc / thông báo lỗi'],
                            ['Tên khu vực *', 'Bắt buộc (“Tên khu vực không được để trống”), tối đa 255 ký tự, không trùng trong file (“Tên khu vực bị trùng với dòng N trong file”), không trùng hệ thống (“Tên khu vực đã tồn tại trong hệ thống”).'],
                            ['Tên quốc gia *', 'Bắt buộc (“Tên quốc gia không được để trống”), chọn trong danh sách sổ xuống; ghi sai báo “Không tìm thấy quốc gia: X”.']], [1.2, 4])]},
            {'ten': 'Xuất danh sách ra Excel', 'uc': 'uc_fr09',
             'qtc': 'Quy tắc Excel và Cấu hình cột. Chỉ bổ sung danh sách trường được phép xuất riêng của Danh mục khu vực.',
             'gioi_thieu': [['Tên chức năng', 'Xuất danh sách khu vực ra Excel'],
                            ['Mô tả', 'Xuất kết quả đang lọc ra file Excel, cho phép chọn trường và thứ tự cột.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Dòng sự kiện chính', '1. Bấm Xuất Excel.\n2. Hệ thống mở cửa sổ “Chọn trường xuất file”, tích sẵn đúng các cột đang hiển thị trên bảng.\n3. Người dùng tích chọn và kéo ☰ để sắp thứ tự.\n4. Bấm Xuất file; hệ thống tải danh_muc_khu_vuc.xlsx theo đúng bộ lọc và thứ tự trường, báo “Xuất Excel thành công”.'],
                            ['Dòng sự kiện phụ', '• Bỏ chọn hết trường → nút Xuất file không bấm được.\n• Bấm Đóng → không xuất gì.'],
                            ['Yêu cầu đặc biệt', 'File chứa toàn bộ kết quả lọc (tối đa 10,000 dòng), không giới hạn ở trang đang xem. Chỉ xuất Excel.']],
             'menu_them': ' => Xuất Excel {icon:btn_xuatexcel}',
             'anh': [('export', 'Cửa sổ Chọn trường xuất file')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
                    ['1', 'Danh sách trường', 'Checkbox chọn nhiều', 'Enable', 'Tích sẵn cột đang hiển thị', 'Tên khu vực, Quốc gia, Trạng thái, Người tạo, Ngày tạo, Người cập nhật, Ngày cập nhật. Kéo ☰ đổi thứ tự.'],
                    ['2', 'Nút Chọn tất cả / Bỏ chọn hết', 'Button', 'Enable', 'Hiển thị', 'Tích / bỏ tích toàn bộ.'],
                    ['3', 'Nút Xuất file', 'Button', 'Enable/Disable', 'Mờ khi chưa chọn trường', 'Sinh file và tải về.'],
                    ['4', 'Nút Đóng', 'Button', 'Enable', 'Hiển thị', 'Đóng cửa sổ.']],
             'ui_widths': [0.6, 1.5, 1, 0.8, 1.2, 2.6]},
            {'ten': 'Xem chi tiết khu vực', 'uc': 'uc_fr10',
             'qtc': 'Màn Xem chi tiết và Phân quyền.',
             'gioi_thieu': [['Tên chức năng', 'Xem chi tiết khu vực'],
                            ['Mô tả', 'Cửa sổ “Xem khu vực” hiển thị Tên khu vực, Quốc gia, Trạng thái ở chế độ chỉ đọc, kèm khối Lịch sử.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm tên khu vực ở danh sách.\n2. Hệ thống mở cửa sổ Xem, chỉ có nút Đóng.']],
             'anh': [('detail', 'Cửa sổ Xem khu vực ở chế độ chỉ đọc')]},
            {'ten': 'Tùy chỉnh cột hiển thị',
             'qtc': 'Tùy chỉnh cột.',
             'gioi_thieu': [['Tên chức năng', 'Tùy chỉnh cột hiển thị'],
                            ['Mô tả', 'Bật/tắt và sắp xếp thứ tự cột của bảng; cấu hình lưu riêng theo người dùng.'],
                            ['Yêu cầu đặc biệt', 'Cột STT, Khu vực, Hành động bị khóa. Mặc định ẩn: Người cập nhật, Ngày cập nhật.']],
             'menu_them': ' => Cấu hình cột {icon:btn_cauhinhcot}',
             'anh': [('colcfg', 'Cửa sổ Tuỳ chỉnh cột')]},
        ],
        'quy_tac': [
            ('BR-01', 'Ràng buộc trùng tên',
             [
              'Tên khu vực không được trùng trên toàn hệ thống (không phân theo quốc gia), kể cả khu vực đang Khóa.',
              'Thông báo khi trùng: “Tên khu vực này đã tồn tại”.',
              'Import Excel: báo “Tên khu vực đã tồn tại trong hệ thống” hoặc “Tên khu vực bị trùng với dòng N trong file”.',
             ],
             ['Thêm mới khu vực', 'Chỉnh sửa khu vực', 'Import file khu vực']),
            ('BR-02', 'Mối quan hệ với Quốc gia và Tỉnh/TP',
             [
              'Mỗi khu vực thuộc đúng một quốc gia; ô Quốc gia chỉ liệt kê quốc gia đang Hoạt động.',
              'Khu vực đang dùng quốc gia đã khóa vẫn giữ và hiển thị đúng tên quốc gia kèm 🔒.',
              'Mọi Tỉnh/TP đều phải trỏ về một khu vực của quốc gia tương ứng; khóa khu vực không tự khóa các Tỉnh/TP bên dưới.',
             ],
             ['Thêm mới khu vực', 'Chỉnh sửa khu vực', 'Thêm mới / Chỉnh sửa Tỉnh/TP']),
            ('BR-03', 'Điều kiện xóa',
             [
              'Chỉ xóa được khu vực đang Hoạt động và chưa có Tỉnh/TP trực thuộc; ngược lại nút Xóa bị ẩn.',
              'Khu vực đã có Tỉnh/TP thì dùng Khóa thay cho Xóa.',
              'Xóa là xóa hẳn bản ghi khỏi hệ thống.',
             ],
             ['Xóa khu vực']),
            ('BR-04', 'Khu vực đang Khóa',
             [
              'Không sửa, không xóa được; phải Mở khóa trước.',
              'Máy chủ chặn lưu khi sửa bản ghi đang Khóa: “Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.”',
              'Khu vực Khóa không còn chọn được ở các màn khác; bản ghi đang dùng vẫn hiển thị đúng tên kèm 🔒.',
             ],
             ['Chỉnh sửa khu vực', 'Xóa khu vực', 'Khóa / Mở khóa khu vực']),
            ('BR-05', 'Thao tác đồng thời',
             [
              'Hai người cùng Khóa / Mở khóa / Xóa một bản ghi: người bấm sau nhận thông báo “Trạng thái đã bị thay đổi. Vui lòng load lại trang”, thao tác không được thực hiện lại.',
             ],
             ['Xóa khu vực', 'Khóa / Mở khóa khu vực']),
            ('BR-06', 'Giới hạn Import',
             [
              'Mỗi lần nhập tối đa 500 dòng; phải Validate trước, bước Validate không ghi dữ liệu.',
              'Quốc gia tra theo tên (file cũ theo mã quốc gia vẫn nhận), không tự tạo quốc gia mới.',
              'Khu vực nhập từ Excel luôn ở trạng thái Hoạt động.',
             ],
             ['Import file khu vực']),
            ('BR-07', 'Ghi lịch sử thay đổi',
             [
              'Mọi thao tác Tạo mới, Thay đổi thông tin, Khóa, Mở khóa đều ghi lịch sử kèm người thực hiện.',
              'Đổi Trạng thái ngay trong cửa sổ Sửa được ghi thành dòng “Thay đổi trạng thái” riêng.',
             ],
             ['Xem lịch sử thay đổi']),
        ],
    },
}

# ---- Sửa tab testcase "14. DM khu vực" (đọc từ ref/testcase_tab.txt) ----
CFG['tc'] = {
    'tab': '14. DM khu vực',
    'hdr_row': 77,            # "VII. LỊCH SỬ THAY ĐỔI"
    # ĐÃ CHẠY 25/09/2026 — không chạy lại (sẽ chèn trùng)
    'blocks': [{'after': 89,  # TC_07.012 — case cuối của nhóm VII
                'groups': [('VIII', 'XUẤT EXCEL (bổ sung 25/09/2026)', 8, 'export'),
                           ('IX', 'IMPORT TỪ FILE EXCEL (bổ sung 25/09/2026)', 9, 'import')]}],
    'import_rows_dung': 'File mẫu điền 4 khu vực hợp lệ (Miền Bắc, Miền Trung, Miền Nam, Tây Nguyên — quốc gia Việt Nam), chưa có trong danh mục',
    'import_loi_data': {
        'Tên khu vực không được để trống': 'Tên khu vực: (để trống); Tên quốc gia: Việt Nam',
        'Tên khu vực tối đa 255 ký tự': 'Tên khu vực: chuỗi 256 ký tự',
        'Tên khu vực bị trùng với dòng N trong file': 'Dòng 2 và dòng 6 cùng tên “Miền Bắc”',
        'Tên khu vực đã tồn tại trong hệ thống': 'Tên khu vực: (tên đã có trong danh mục)',
        'Tên quốc gia không được để trống': 'Tên quốc gia: (để trống)',
        'Không tìm thấy quốc gia: X': 'Tên quốc gia: Nước không tồn tại',
    },
    'edits': [
        ('B8', 'Màn hình này KHÔNG khai báo quyền nào. Mọi người dùng đã đăng nhập đều mở được màn hình và thực hiện được đầy đủ Thêm mới, Chỉnh sửa, Xóa, Khóa, Mở khóa, Import Excel và Xuất Excel.\n Phía máy chủ cũng không kiểm tra quyền, nên gọi thẳng chức năng mà bỏ qua giao diện vẫn ghi được dữ liệu. Đây là hiện trạng của mã nguồn, đã được ghi nhận để bộ phận quản trị cân nhắc bổ sung quyền.'),
    ],
    'clear_k': [],
}


# ---- Bổ sung 28/09/2026: “Mô tả chi tiết giao diện” + “Danh sách event và xử lý event” cho SRS ----
# Tester báo thiếu 2 mục này ở các chức năng sau Thêm mới. Nguồn: code gop_db 28/09/2026 (FE pages/human/areas, component
# dùng chung V2BaseImportModal / export-fields-modal / column-customization-modal / CatalogHistoryModal; BE Modules/Human).
_FR = {f['ten']: f for f in CFG['srs']['fr']}
_FR['Chỉnh sửa khu vực'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Phạm vi', 'Bắt buộc', 'Giá trị ban đầu', 'Mô tả'],
        ['1', 'Tên khu vực', 'Textbox', 'Enable', '1–255 ký tự', 'Có', 'Dữ liệu hiện tại', 'Duy nhất toàn hệ thống, bỏ qua chính bản ghi đang sửa. Bỏ trống “Bắt buộc phải nhập”; trùng “Tên khu vực này đã tồn tại”; quá dài “Vui lòng nhập tối đa 255 ký tự.”'],
        ['2', 'Quốc gia', 'Dropdown', 'Enable', 'Quốc gia đang Hoạt động', 'Có', 'Dữ liệu hiện tại', 'Liệt kê quốc gia đang Hoạt động; quốc gia đã khóa mà bản ghi đang dùng vẫn hiện đúng tên kèm 🔒. Bỏ trống “Bắt buộc phải nhập”.'],
        ['3', 'Trạng thái', 'Dropdown', 'Enable', 'Hoạt động / Khóa', 'Có', 'Dữ liệu hiện tại', 'Chọn Khóa rồi Lưu cũng là khóa khu vực; lịch sử ghi dòng “Thay đổi trạng thái” riêng.'],
        ['4', 'Nút Lưu', 'Button', 'Enable', '–', '–', 'Hiển thị', 'Ghi thay đổi rồi đóng cửa sổ.'],
        ['5', 'Nút Đóng / biểu tượng X', 'Button', 'Enable', '–', '–', 'Hiển thị', 'Đóng cửa sổ, không ghi gì. Đã sửa dở thì hỏi “Thông tin chưa lưu” — “Bạn có thông tin chưa lưu. Có chắc chắn muốn thoát?” (Thoát / Ở lại). Chế độ Sửa không có nút “Lưu và tiếp tục”.'],
        ['6', 'Thông báo lỗi', 'Label', 'Hiển thị khi lỗi', '–', '–', 'Ẩn', 'Chữ đỏ ngay dưới ô bị lỗi, kèm thông báo chung “Vui lòng kiểm tra lại dữ liệu nhập”.'],
    ],
    'ui_widths': [0.5, 1.2, 0.8, 0.6, 1.1, 0.6, 0.8, 1.9],
    'events': [
        ['Bấm biểu tượng bút chì (Sửa)', 'Click', 'Before:\n– Nút chỉ hiển thị khi bản ghi đang Hoạt động; bản ghi Khóa không có nút Sửa.\nAfter:\n– Mở cửa sổ “Sửa khu vực” với dữ liệu hiện tại đã điền sẵn.'],
        ['Bấm Lưu', 'Click', 'During:\n– Tên khu vực để trống → “Bắt buộc phải nhập”; trùng với khu vực khác trên toàn hệ thống → “Tên khu vực này đã tồn tại”; quá 255 ký tự → “Vui lòng nhập tối đa 255 ký tự.”\n– Quốc gia để trống → “Bắt buộc phải nhập”.\n– Bỏ qua kiểm tra trùng đối với chính bản ghi đang sửa.\n– Bản ghi đang Khóa (vừa bị người khác khóa) → từ chối, báo “Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.”\n– Có lỗi → báo đỏ dưới ô, cửa sổ KHÔNG đóng, không thực hiện bước After.\nAfter:\n– Ghi thay đổi, ghi Người cập nhật và một dòng lịch sử “Thay đổi thông tin” nêu giá trị cũ → mới (đổi Trạng thái ghi dòng “Thay đổi trạng thái” riêng).\n– Đóng cửa sổ, nạp lại danh sách, báo “Cập nhật thành công”.'],
        ['Bấm Đóng / biểu tượng X / bấm ra ngoài cửa sổ', 'Click', 'After:\n– Chưa sửa gì → đóng cửa sổ.\n– Đã sửa → hỏi “Thông tin chưa lưu” — “Bạn có thông tin chưa lưu. Có chắc chắn muốn thoát?” (Thoát / Ở lại); chọn Thoát thì đóng, không ghi; chọn Ở lại thì giữ nguyên dữ liệu đang nhập.'],
    ],
})
_FR['Xóa khu vực'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Mô tả'],
        ['1', 'Biểu tượng thùng rác (Xóa)', 'Icon Button', 'Nằm ở cột Hành động của từng dòng. Chỉ hiển thị khi khu vực đang Hoạt động và CHƯA có Tỉnh/TP nào trực thuộc; ngược lại nút bị ẩn hẳn.'],
        ['2', 'Tiêu đề hộp xác nhận', 'Label', '“Xóa khu vực”.'],
        ['3', 'Nội dung hộp xác nhận', 'Label', '“Bạn có chắc muốn xóa khu vực "<tên>"?” — nêu rõ tên bản ghi để tránh xóa nhầm dòng.'],
        ['4', 'Nút Xóa', 'Button', 'Xác nhận xóa hẳn bản ghi khỏi hệ thống.'],
        ['5', 'Nút Hủy', 'Button', 'Đóng hộp, không thay đổi gì.'],
    ],
    'ui_widths': [0.6, 1.8, 1.0, 3.6],
    'events': [
        ['Bấm biểu tượng thùng rác', 'Click', 'Before:\n– Nút chỉ hiển thị khi khu vực đang Hoạt động và CHƯA có Tỉnh/TP nào trực thuộc.\nAfter:\n– Hiện hộp xác nhận “Xóa khu vực” kèm tên bản ghi.'],
        ['Bấm Xóa trong hộp xác nhận', 'Click', 'During:\n– Bản ghi không còn tồn tại (người khác vừa xóa) → báo “Trạng thái đã bị thay đổi. Vui lòng load lại trang”, dừng xử lý.\nAfter:\n– Xóa hẳn bản ghi (không khôi phục được), đóng hộp, nạp lại danh sách, báo “Xoá khu vực thành công”.\n– Lỗi khác → báo câu lỗi của hệ thống hoặc “Xoá khu vực thất bại”.'],
        ['Bấm Hủy', 'Click', 'After:\n– Đóng hộp xác nhận, không thay đổi gì.'],
    ],
})
_FR['Khóa / Mở khóa khu vực'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Mô tả'],
        ['1', 'Nút Khóa / Mở khóa', 'Button', 'Nằm ở cột Hành động (trong nút ba chấm nếu dòng có từ 4 nút trở lên). Nhãn đổi theo trạng thái. Luôn hiển thị: dòng Hoạt động có Khóa, dòng Khóa có Mở khóa.'],
        ['2', 'Nút ba chấm “Hành động khác”', 'Icon Button', 'Hiện khi dòng có từ 4 nút trở lên: 2 nút đầu hiện thẳng, các nút còn lại (Khóa, Lịch sử) nằm trong menu này.'],
        ['3', 'Tiêu đề hộp xác nhận', 'Label', '“Khóa khu vực” hoặc “Mở khóa khu vực” tùy trạng thái hiện tại.'],
        ['4', 'Nội dung hộp xác nhận', 'Label', '“Bạn có chắc muốn khóa khu vực "<tên>"?” / “Bạn có chắc muốn mở khóa khu vực "<tên>"?”.'],
        ['5', 'Nút Khóa / Mở khóa trong hộp', 'Button', 'Xác nhận thực hiện.'],
        ['6', 'Nút Hủy', 'Button', 'Đóng hộp, không làm gì.'],
        ['7', 'Cột Trạng thái', 'Badge', 'Hoạt động hoặc Khóa, hai màu khác nhau; cập nhật ngay sau thao tác.'],
    ],
    'ui_widths': [0.6, 1.8, 1.0, 3.6],
    'events': [
        ['Bấm nút ba chấm', 'Click', 'After:\n– Mở menu chứa các nút còn lại của dòng (Khóa / Mở khóa, Lịch sử).'],
        ['Chọn Khóa hoặc Mở khóa', 'Click', 'After:\n– Hiện hộp xác nhận kèm tên bản ghi.'],
        ['Bấm Khóa / Mở khóa trong hộp', 'Click', 'During:\n– Bản ghi không còn tồn tại hoặc đã ở trạng thái đích (người khác vừa thao tác) → báo “Trạng thái đã bị thay đổi. Vui lòng load lại trang”, dừng xử lý, không ghi thêm lịch sử.\nAfter:\n– Đổi trạng thái, KHÔNG xóa dữ liệu; ghi Người cập nhật và một dòng lịch sử “Khóa” / “Mở khóa”.\n– Đóng hộp, báo “Khóa thành công” / “Mở khóa thành công”, nạp lại danh sách: sau Khóa ẩn nút Sửa, Xóa; sau Mở khóa hiện lại nút Sửa (Xóa hiện lại nếu đủ điều kiện xóa).\n– Lỗi khác → báo câu lỗi của hệ thống hoặc “Thao tác thất bại”.'],
        ['Bấm Hủy', 'Click', 'After:\n– Đóng hộp xác nhận, trạng thái không đổi.'],
    ],
})
_FR['Xem lịch sử thay đổi'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Giá trị ban đầu', 'Mô tả'],
        ['1', 'Nút Lịch sử', 'Button', 'Hiển thị', 'Nằm ở cột Hành động (trong nút ba chấm nếu dòng có từ 4 nút). Luôn có ở mọi dòng, kể cả bản ghi Khóa.'],
        ['2', 'Tiêu đề cửa sổ', 'Label', 'Lịch sử thay đổi: <tên khu vực>', 'Ghép tên bản ghi để biết đang xem dòng nào.'],
        ['3', 'Nút Bộ lọc', 'Button', 'Vùng lọc đang ẩn', 'Bấm để hiện / ẩn vùng lọc; vùng lọc ghim ở đầu khi cuộn danh sách.'],
        ['4', 'Loại hành động', 'Dropdown', 'Trống (“Tất cả loại hành động”)', 'Lọc theo Tạo mới, Thay đổi thông tin, Thay đổi trạng thái, Khóa, Mở khóa… Chọn là lọc ngay.'],
        ['5', 'Người thực hiện', 'Dropdown', 'Trống (“Tất cả người thực hiện”)', 'Chọn là lọc ngay.'],
        ['6', 'Từ ngày / Đến ngày', 'Date picker', 'Trống', 'Định dạng dd/mm/yyyy. Chọn là lọc ngay.'],
        ['7', 'Nút Làm mới (vùng lọc)', 'Button', 'Hiển thị', 'Xóa hết tiêu chí lọc, hiện lại toàn bộ lịch sử.'],
        ['8', 'Danh sách thay đổi', 'Timeline', 'Mới nhất ở trên cùng', 'Mỗi mốc gồm: thời điểm (dd/mm/yyyy hh:mm); loại hành động (Tạo mới, Thay đổi thông tin, Thay đổi trạng thái, Khóa, Mở khóa); “Người thực hiện: …”; từng trường đã đổi dạng “Tên trường: giá trị cũ → giá trị mới”. Trường Quốc gia hiển thị bằng tên.'],
        ['9', 'Trạng thái rỗng', 'Label', 'Ẩn', '“Chưa có lịch sử thao tác nào.” khi bản ghi chưa có lịch sử; “Không có lịch sử phù hợp bộ lọc.” khi lọc không ra kết quả.'],
        ['10', 'Nút Đóng / biểu tượng X', 'Button', 'Hiển thị', 'Đóng cửa sổ.'],
    ],
    'ui_widths': [0.6, 1.5, 0.9, 1.2, 2.8],
    'events': [
        ['Chọn Lịch sử ở cột Hành động', 'Click', 'After:\n– Mở cửa sổ “Lịch sử thay đổi: <tên>”, nạp danh sách thay đổi theo thứ tự mới nhất trước.\n– Không tải được → hiện “Không tải được lịch sử phiếu.” kèm nút Thử lại.'],
        ['Bấm Bộ lọc', 'Click', 'After:\n– Hiện / ẩn vùng lọc.'],
        ['Đổi Loại hành động / Người thực hiện / Từ ngày / Đến ngày', 'Change', 'After:\n– Lọc ngay danh sách theo mọi tiêu chí đã chọn (không có nút Tìm kiếm).'],
        ['Bấm Làm mới trong vùng lọc', 'Click', 'After:\n– Xóa trắng tiêu chí, hiện lại toàn bộ lịch sử.'],
        ['Bấm Đóng / biểu tượng X', 'Click', 'After:\n– Đóng cửa sổ; danh sách phía sau giữ nguyên bộ lọc và trang đang xem.'],
    ],
})
_FR['Import file khu vực'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Bắt buộc', 'Giá trị ban đầu', 'Mô tả'],
        ['1', 'Nút Import Excel', 'Button', 'Enable', '–', 'Hiển thị', 'Nằm trên thanh công cụ của bảng danh sách. Mở cửa sổ “Import khu vực” (dòng phụ “Import từ Excel • Validate xong dòng hợp lệ sẽ bị khoá”).'],
        ['2', 'Nút Chọn file Excel', 'Button', 'Enable', 'Có', 'Chưa chọn file', 'Chọn file .xlsx hoặc .xls từ máy; tên file hiện ngay cạnh nút.'],
        ['3', 'Nút Tải file mẫu', 'Button', 'Enable', '–', 'Hiển thị', 'Tải file Mau_import_khu_vuc.xlsx gồm cột STT, Tên khu vực *, Tên quốc gia * (ô chọn sẵn danh sách quốc gia). Hàng 1 là tiêu đề, hàng 2 là dòng mô tả, dữ liệu nhập từ hàng 3.'],
        ['4', 'Nút Load lên bảng', 'Button', 'Enable / Disable', '–', 'Mờ khi chưa chọn file', 'Đọc file và đổ dữ liệu lên bảng xem trước.'],
        ['5', 'Nút Validate', 'Button', 'Enable / Disable', '–', 'Mờ khi bảng chưa có dòng nào', 'Gửi dữ liệu lên máy chủ kiểm tra từng dòng; dòng hợp lệ bị khóa lại, không sửa được nữa.'],
        ['6', 'Nút Import', 'Button', 'Enable / Disable', '–', 'Mờ', 'Chỉ bấm được khi đã Validate, không còn dòng lỗi và có ít nhất 1 dòng hợp lệ. Ghi các dòng hợp lệ vào danh mục.'],
        ['7', 'Ô Tổng / Hợp lệ / Lỗi', 'Label', 'Read-only', '–', 'Tổng: 0', 'Sau Load hiện “Tổng”; sau Validate hiện thêm “Hợp lệ”, “Lỗi”. Có dòng vừa sửa hiện “Có dòng đã sửa (cần validate lại)”.'],
        ['8', 'Bảng xem trước', 'Table/Grid', 'Enable', '–', 'Trống', 'Cột #, Tên khu vực *, Tên quốc gia *. Dòng lỗi sửa trực tiếp được (Tên khu vực gõ lại; Tên quốc gia chọn trong danh sách).'],
        ['9', 'Thông báo lỗi theo dòng', 'Label', 'Hiển thị', '–', 'Ẩn', 'Dòng lỗi viền đỏ, lý do ghi ngay dưới dòng: “Tên khu vực không được để trống”; “Tên khu vực tối đa 255 ký tự”; “Tên khu vực bị trùng với dòng N trong file”; “Tên khu vực đã tồn tại trong hệ thống”; “Tên quốc gia không được để trống”; “Không tìm thấy quốc gia: X”.'],
        ['10', 'Nút Bỏ dòng lỗi', 'Button', 'Enable / Disable', '–', 'Mờ khi bảng trống', 'Loại mọi dòng lỗi khỏi bảng, báo “Đã bỏ N dòng lỗi. Còn lại M dòng hợp lệ.”; chưa Validate thì báo “Hãy Validate trước rồi mới bỏ dòng lỗi.”'],
        ['11', 'Nút Xoá trạng thái validate', 'Button', 'Enable / Disable', '–', 'Mờ khi bảng trống', 'Bỏ khóa các dòng hợp lệ và xóa kết quả kiểm tra để sửa lại.'],
        ['12', 'Nút Làm mới', 'Button', 'Enable', '–', 'Hiển thị', 'Bỏ file đã chọn và toàn bộ bảng, đưa cửa sổ về trạng thái ban đầu.'],
        ['13', 'Nút Đóng / biểu tượng X', 'Button', 'Enable', '–', 'Hiển thị', 'Đóng cửa sổ, không ghi gì.'],
    ],
    'ui_widths': [0.5, 1.3, 0.9, 0.8, 0.5, 1.1, 2.4],
    'events': [
        ['Bấm Import Excel', 'Click', 'After:\n– Mở cửa sổ “Import khu vực” ở trạng thái rỗng.'],
        ['Bấm Tải file mẫu', 'Click', 'After:\n– Tải file Mau_import_khu_vuc.xlsx về máy.\n– Lỗi → báo “Lỗi khi tạo file mẫu”.'],
        ['Chọn file', 'Change', 'During:\n– File không phải .xlsx / .xls → báo “Vui lòng chọn file .xlsx hoặc .xls”, bỏ file.\nAfter:\n– Hiện tên file, nút Load lên bảng sáng lên.'],
        ['Bấm Load lên bảng', 'Click', 'During:\n– File không có dòng dữ liệu → “Không có dòng dữ liệu hợp lệ.”\n– Quá 500 dòng → “File có X dòng dữ liệu, vượt quá giới hạn 500 dòng mỗi lần import. Vui lòng tách file và import nhiều lần.”\n– File hỏng / không đọc được → “Không đọc được file Excel.”\nAfter:\n– Đổ dữ liệu lên bảng xem trước, cập nhật ô Tổng.'],
        ['Bấm Validate', 'Click', 'During:\n– Máy chủ kiểm tra từng dòng theo đúng quy tắc của chức năng Thêm mới và bảng “Quy tắc kiểm tra riêng của file Import”.\n– KHÔNG ghi bất kỳ bản ghi nào ở bước này.\nAfter:\n– Còn dòng lỗi: tô đỏ dòng lỗi kèm lý do, khóa dòng hợp lệ, báo “Validate xong: X hợp lệ, Y không hợp lệ. (Dòng hợp lệ đã bị khoá, chỉ có thể sửa dòng lỗi)”.\n– Không còn dòng lỗi: báo “Tất cả N dòng đã hợp lệ. Có thể import ngay.”, nút Import sáng lên.\n– Không dòng nào hợp lệ: báo “Không có dòng nào hợp lệ để import. Hãy sửa các dòng lỗi và validate lại.”'],
        ['Sửa ô ở dòng lỗi', 'Input', 'After:\n– Dòng chuyển về chưa kiểm tra, hiện “Có dòng đã sửa (cần validate lại)”; phải Validate lại mới Import được.'],
        ['Bấm Bỏ dòng lỗi / Xoá trạng thái validate', 'Click', 'After:\n– Bỏ dòng lỗi: chỉ giữ dòng hợp lệ, nút Import sáng lên.\n– Xoá trạng thái validate: mở khóa mọi dòng, xóa kết quả kiểm tra.'],
        ['Bấm Import', 'Click', 'During:\n– Chỉ gửi các dòng hợp lệ; máy chủ kiểm tra lại toàn bộ, không tin kết quả Validate trước đó.\n– Không còn dòng hợp lệ → báo “Không có dòng nào hợp lệ để import”, dừng.\nAfter:\n– Tạo khu vực mới ở trạng thái Hoạt động, người tạo là người đang thực hiện.\n– Báo “Import thành công N khu vực.” (có dòng thất bại: “Import thành công X/Y khu vực. Z dòng thất bại.”), đóng cửa sổ, nạp lại danh sách.'],
        ['Bấm Làm mới / Đóng', 'Click', 'After:\n– Làm mới: xóa file và bảng, giữ cửa sổ mở.\n– Đóng: đóng cửa sổ, không ghi gì.'],
    ],
})
_FR['Xuất danh sách ra Excel'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
        ['1', 'Nút Xuất Excel', 'Button', 'Enable', 'Hiển thị', 'Nằm trên thanh công cụ của bảng danh sách. Mở cửa sổ “Chọn trường xuất file”.'],
        ['2', 'Dòng hướng dẫn', 'Label', 'Read-only', 'Hiển thị', '“Tích chọn trường cần xuất, kéo ☰ để đổi thứ tự cột trong file.”'],
        ['3', 'Danh sách trường', 'Checkbox chọn nhiều', 'Enable', 'Tích sẵn đúng các cột đang hiển thị trên bảng, xếp lên đầu theo thứ tự trên bảng', 'Bảy trường: Tên khu vực, Quốc gia, Trạng thái, Người tạo, Ngày tạo, Người cập nhật, Ngày cập nhật. Kéo biểu tượng ☰ để đổi vị trí cột trong file.'],
        ['4', 'Nút Chọn tất cả', 'Button', 'Enable', 'Hiển thị', 'Tích toàn bộ trường.'],
        ['5', 'Nút Bỏ chọn hết', 'Button', 'Enable', 'Hiển thị', 'Bỏ tích toàn bộ trường.'],
        ['6', 'Dòng đếm trường', 'Label', 'Read-only', 'Hiển thị', '“Đang chọn a/N trường”.'],
        ['7', 'Nút Xuất file', 'Button', 'Enable / Disable', 'Mờ khi chưa chọn trường nào', 'Đóng cửa sổ, sinh file Excel và tải về máy.'],
        ['8', 'Nút Đóng / biểu tượng X', 'Button', 'Enable', 'Hiển thị', 'Đóng cửa sổ, không xuất.'],
    ],
    'ui_widths': [0.6, 1.5, 1.0, 0.8, 1.3, 2.3],
    'events': [
        ['Bấm Xuất Excel', 'Click', 'After:\n– Mở cửa sổ “Chọn trường xuất file”, tích sẵn đúng các cột đang hiển thị trên bảng (theo cấu hình cột của người dùng), các trường còn lại liệt kê bên dưới chưa tích. Không nhớ lựa chọn của lần xuất trước.'],
        ['Tích / bỏ tích trường, kéo ☰', 'Change', 'During:\n– Thứ tự trong danh sách là thứ tự cột trong file.\n– Bỏ chọn hết → nút Xuất file mờ đi.'],
        ['Bấm Xuất file', 'Click', 'During:\n– Sinh file theo ĐÚNG bộ lọc và thứ tự sắp xếp đang áp dụng (tối đa 10,000 dòng), các cột theo đúng thứ tự trường đã chọn.\nAfter:\n– Tải file danh_muc_khu_vuc.xlsx về máy, báo “Xuất Excel thành công”.\n– Lỗi → báo “Lỗi khi xuất Excel”.'],
        ['Bấm Đóng / biểu tượng X', 'Click', 'After:\n– Đóng cửa sổ, không xuất gì.'],
    ],
})
_FR['Xem chi tiết khu vực'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
        ['1', 'Tên khu vực ở cột Khu vực', 'Link', 'Enable', 'Hiển thị', 'Bấm vào tên để mở cửa sổ Xem (thay cho nút “Xem” ở cột Hành động). Bản ghi Khóa vẫn mở được.'],
        ['2', 'Tiêu đề cửa sổ', 'Label', 'Read-only', 'Xem khu vực', 'Kèm biểu tượng tròn ở đầu tiêu đề.'],
        ['3', 'Tên khu vực', 'Textbox', 'Read-only', 'Dữ liệu hiện tại', 'Chỉ đọc, không sửa được.'],
        ['4', 'Quốc gia', 'Dropdown', 'Read-only', 'Dữ liệu hiện tại', 'Chỉ đọc, không sửa được. Quốc gia đã khóa vẫn hiện đúng tên kèm 🔒.'],
        ['5', 'Trạng thái', 'Dropdown', 'Read-only', 'Dữ liệu hiện tại', 'Chỉ đọc, không sửa được.'],
        ['6', 'Khối Lịch sử', 'Panel thu gọn', 'Enable', 'Thu gọn', 'Tiêu đề “Lịch sử” kèm số lần thay đổi. Nút “Xem lịch sử” mở khối (đổi thành “Thu gọn”), nút “Làm mới” nạp lại. Nội dung, bộ lọc giống cửa sổ Lịch sử thay đổi.'],
        ['7', 'Nút Đóng / biểu tượng X', 'Button', 'Enable', 'Hiển thị', 'Đóng cửa sổ. Cửa sổ Xem KHÔNG có nút Lưu, Lưu và tiếp tục hay Sửa.'],
    ],
    'ui_widths': [0.6, 1.5, 1.0, 0.8, 1.3, 2.3],
    'events': [
        ['Bấm tên khu vực ở danh sách', 'Click', 'After:\n– Mở cửa sổ “Xem khu vực”, nạp dữ liệu hiện tại của bản ghi ở chế độ chỉ đọc.\n– Không tải được → báo “Lỗi khi tải dữ liệu” và đóng cửa sổ.'],
        ['Bấm Xem lịch sử / Thu gọn', 'Click', 'After:\n– Lần mở đầu tiên mới nạp lịch sử; hiện danh sách thay đổi mới nhất ở trên.\n– Thu gọn: ẩn khối, không nạp lại.'],
        ['Bấm Làm mới trong khối Lịch sử', 'Click', 'After:\n– Nạp lại lịch sử mới nhất của bản ghi.'],
        ['Bấm Đóng / biểu tượng X', 'Click', 'After:\n– Đóng cửa sổ, không hỏi xác nhận (không có gì để lưu).'],
    ],
})
_FR['Tùy chỉnh cột hiển thị'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
        ['1', 'Biểu tượng Cấu hình cột hiển thị', 'Icon Button', 'Enable', 'Hiển thị', 'Nút cuối cùng trên thanh công cụ của bảng. Mở cửa sổ “Tuỳ chỉnh cột”.'],
        ['2', 'Danh sách cột', 'Checkbox', 'Enable', 'Theo cấu hình đã lưu; chưa lưu lần nào thì hiện Quốc gia, Người tạo, Ngày tạo, Trạng thái, ẩn Người cập nhật, Ngày cập nhật', 'Liệt kê đủ 9 cột theo thứ tự trên bảng: STT, Khu vực, Quốc gia, Người cập nhật, Ngày cập nhật, Người tạo, Ngày tạo, Trạng thái, Hành động. Tích = hiện cột, bỏ tích = ẩn cột.'],
        ['3', 'Cột bắt buộc', 'Checkbox', 'Disable', 'Luôn tích', 'STT, Khu vực, Hành động: xám, có biểu tượng khóa, không bỏ tích và không kéo đổi vị trí được (rê chuột hiện “Cột bắt buộc — không thể ẩn hoặc đổi vị trí”).'],
        ['4', 'Biểu tượng ☰', 'Drag handle', 'Enable', 'Hiển thị', 'Kéo thả để đổi thứ tự các cột không bắt buộc.'],
        ['5', 'Nút Lưu', 'Button', 'Enable', 'Hiển thị', 'Áp dụng ngay cho bảng và lưu cấu hình theo TÀI KHOẢN người dùng trên máy chủ (đăng nhập máy/trình duyệt khác vẫn giữ).'],
        ['6', 'Nút Đóng / biểu tượng X', 'Button', 'Enable', 'Hiển thị', 'Đóng cửa sổ, bỏ các thay đổi chưa Lưu.'],
    ],
    'ui_widths': [0.6, 1.5, 1.0, 0.8, 1.3, 2.3],
    'events': [
        ['Bấm biểu tượng Cấu hình cột hiển thị', 'Click', 'After:\n– Mở cửa sổ “Tuỳ chỉnh cột”, tích đúng theo các cột đang hiển thị.'],
        ['Tích / bỏ tích, kéo ☰', 'Change', 'During:\n– Chỉ thay đổi trong cửa sổ, bảng chưa đổi.\n– Cột bắt buộc không bỏ tích, không kéo được.'],
        ['Bấm Lưu', 'Click', 'After:\n– Bảng hiện/ẩn và sắp cột theo cấu hình mới, lưu cấu hình theo người dùng, báo “Cập nhật thành công”; đóng cửa sổ.\n– Lần Xuất Excel sau tích sẵn đúng các cột đang hiện.\n– Lỗi lưu → báo “Thao tác thất bại”.'],
        ['Bấm Đóng / biểu tượng X', 'Click', 'After:\n– Đóng cửa sổ, trả danh sách về cấu hình đang áp dụng.'],
    ],
})

# Lỗi code phát hiện khi soạn mục giao diện/event SRS (28/09/2026) — báo user, KHÔNG sửa code.
CFG['loi_code'] = CFG.get('loi_code', []) + [
    'Xóa không được chặn ở máy chủ: AreaService::deleteArea chỉ kiểm tra bản ghi còn tồn tại, không kiểm tra canDelete() (đã có Tỉnh/TP trực thuộc) lẫn trạng thái Khóa; route DELETE human/areas/{id} cũng không gắn recordNotLocked. Gọi thẳng API vẫn xóa được khu vực đã khóa hoặc đang có Tỉnh/TP (Tỉnh/TP bị mồ côi). Nút Xóa chỉ bị ẩn ở FE (index.vue getRowActions).',
    'Chặn sửa bản ghi đã Khóa (AreaController::store dòng 56-58) đặt SAU CreateAreasRequest nên payload thiếu/sai trường bị trả 422 trước, không tới được câu 423 “Bản ghi đang bị khoá…” (CLAUDE.md yêu cầu guard ở middleware route như Quận/Huyện, Đường/Phố).',
    'Khối/cửa sổ Lịch sử dùng chung (components/assign/SystemInfoSection.vue dòng 443) báo lỗi tải bằng câu “Không tải được lịch sử phiếu.” — chữ “phiếu” không hợp với màn danh mục (ảnh hưởng mọi danh mục dùng catalog-histories).',
]


# Đồng bộ chỗ tester sửa tay trên Drive (so bản Drive 28/09/2026) — build_srs áp qua apply_tester_edits
CFG['srs_tester'] = {
 "del": [
  "Không có bản ghi khớp → bảng hiện “Không có dữ liệu phù hợp bộ lọc.”",
  "Không có kết quả → bảng hiện thông báo không có dữ liệu.",
  "Bấm “Lưu và tiếp tục” → ghi bản ghi rồi giữ cửa sổ mở với các ô trống.",
  "Giữ nguyên tên của chính bản ghi → không báo trùng.",
  "Lỗi khi xóa → báo “Xoá khu vực thất bại”.",
  "Bản ghi chưa từng sửa → “Chưa có lịch sử thao tác nào.”",
  "File không phải .xlsx/.xls → “Vui lòng chọn file .xlsx hoặc .xls”.",
  "Quá 500 dòng → “File có X dòng dữ liệu, vượt quá giới hạn 500 dòng mỗi lần import. Vui lòng tách file và import nhiều lần.”"
 ],
 "br": {
  "BR-04": [
   "BR-04",
   "Khu vực đang Khóa",
   [
    "Không sửa, không xóa được; phải Mở khóa trước.",
    "Khu vực Khóa không còn chọn được ở các màn khác; bản ghi đang dùng vẫn hiển thị đúng tên kèm 🔒."
   ],
   [
    "Chỉnh sửa khu vực",
    "Xóa khu vực",
    "Khóa / Mở khóa khu vực"
   ]
  ]
 }
}
