# -*- coding: utf-8 -*-
# Cấu hình tài liệu màn Danh mục tiền tệ (Tài chính → Danh mục → Danh mục tiền tệ).
# Nguồn: code gop_db 25/09/2026 — FE pages/finance/currencies/index.vue, components/modal/finance/currency-modal.vue;
# BE Modules/Finance: CurrencyController, CurrencyService, CurrencyRequest, Entities/Currency; app/Console/Commands/UpdateExchangeRateCurrencyCommand.
# Không ghi URL. Chữ UI / message lấy nguyên văn code.

DT = 'tiền tệ'
Q_QL = 'Quản lý danh mục tiền tệ'
Q_XEM = 'Xem danh mục tiền tệ'

CFG = {
    'slug': 'currencies',
    'ten': 'Danh mục tiền tệ',
    'doi_tuong': DT,
    'file_hdsd': 'HDSD_Danh muc tien te.docx',
    'file_srs': 'SRS - Danh mục tiền tệ.docx',
    'menu': [('Tài chính', 'menu_phanhe'), ('Danh mục', 'menu_nhom'), ('Danh mục tiền tệ', 'menu_muc')],
    'form_type': 'popup',

    'thuat_ngu': [
        ['Tiền tệ', 'Một loại tiền dùng trong chứng từ (VNĐ, USD, EUR…), gồm Mã, Tên, Tên gọi khác và Tỷ giá quy đổi.'],
        ['Mã tiền tệ', 'Mã viết tắt, duy nhất trong danh mục. Chỉ gồm chữ không dấu, số, dấu - và _; hệ thống tự chuyển sang chữ IN HOA khi lưu.'],
        ['Tỷ giá (VNĐ)', 'Một đơn vị tiền tệ đó bằng bao nhiêu Đồng Việt Nam. Hiển thị theo chuẩn quốc tế, ví dụ 26,520.00.'],
        ['Trạng thái Hoạt động', 'Tiền tệ chọn được khi lập chứng từ mới.'],
        ['Trạng thái Khóa', 'Tiền tệ không còn chọn được ở chứng từ mới; chứng từ đã lập trước đó vẫn hiện đúng tiền tệ này.'],
        ['Cổng cũ', 'Phần mềm quản trị cũ. Hai cổng dùng CHUNG một danh sách tiền tệ, sửa ở cổng nào cổng kia thấy ngay.'],
    ],
    'phien_ban': [
        ['1.0', '13/08/2026', 'Đội phát triển phần mềm', 'Tạo mới cho màn Danh mục tiền tệ.'],
        ['1.1', '25/09/2026', 'Đội phát triển phần mềm', 'Cập nhật theo phiên bản hiện tại: quy tắc Mã tiền tệ (ký tự cho phép, tự in hoa), Tên tiền tệ không được trùng, định dạng số quốc tế, nút Khóa/Mở khóa và Lịch sử chuyển về cột Hành động, bấm Mã để xem chi tiết, cửa sổ Chọn trường xuất file, bổ sung Import Excel và Tùy chỉnh cột; trình bày theo mẫu tài liệu danh mục chung.'],
    ],
    'muc_dich': [
        'Danh mục tiền tệ dùng để khai báo và quản lý các loại tiền tệ cùng tỷ giá quy đổi ra Đồng Việt Nam. Đây là danh mục nền, được dùng lại ở nhiều nghiệp vụ phía sau: báo giá, hợp đồng, hóa đơn, tờ khai hải quan, công nợ khách hàng và nhà cung cấp, các phiếu kế toán.',
        'Danh mục dùng CHUNG dữ liệu với màn tương ứng bên cổng cũ: sửa ở cổng nào thì cổng còn lại cũng thấy ngay, không cần đồng bộ thủ công.',
    ],
    'quyen': {
        'truoc': ['Màn hình dùng hai quyền riêng. Mục menu chỉ hiện khi tài khoản có ít nhất một trong hai quyền; không có quyền nào thì không vào được màn hình và máy chủ không trả dữ liệu.'],
        'rows': [
            [Q_XEM, 'Vào màn hình, xem danh sách, tìm kiếm, lọc, bấm Mã để xem chi tiết, xem Lịch sử, Xuất Excel, Tùy chỉnh cột.'],
            [Q_QL, 'Toàn bộ quyền Xem, cộng thêm: Tạo mới, Sửa, Xóa, Khóa, Mở khóa và Import Excel.'],
        ],
        'sau': ['Danh mục KHÔNG phân quyền theo công ty, phòng ban hay bộ phận: ai vào được màn hình đều thấy cùng một danh sách. Thiếu quyền Quản lý thì các nút Tạo mới, Import Excel, Sửa, Xóa, Khóa/Mở khóa không hiển thị; gọi thẳng chức năng bỏ qua giao diện cũng bị máy chủ từ chối.'],
    },

    'danh_sach': {
        'mo_ta_vao': 'Hệ thống hiển thị danh sách tiền tệ hiện có, mặc định 10 dòng mỗi trang, xếp theo thứ tự thêm vào danh mục.',
        'bo_cuc': [
            'Khu vực tìm kiếm và lọc — ô tìm kiếm nhanh, ô Trạng thái, nút Tìm kiếm và Làm mới nằm gọn trên một hàng.',
            'Thanh công cụ — nút Tạo mới, Xuất Excel, Import Excel và biểu tượng Cấu hình cột hiển thị.',
            'Bảng danh sách — các cột thông tin, cột Hành động ở cuối, và phân trang bên dưới.',
        ],
        'cot': [
            ['STT', 'Số thứ tự, chạy liên tục qua các trang. Luôn hiển thị.'],
            ['Mã tiền tệ', 'Mã viết tắt, ví dụ USD, EUR. Luôn hiển thị, sắp xếp được. Bấm vào mã để mở cửa sổ Xem tiền tệ.'],
            ['Tên tiền tệ', 'Tên đầy đủ. Luôn hiển thị, sắp xếp được.'],
            ['Tỷ giá (VNĐ)', 'Giá trị quy đổi ra Đồng Việt Nam, luôn 2 chữ số thập phân, dạng 26,520.00. Sắp xếp được.'],
            ['Tên gọi khác', 'Tên thông dụng, ví dụ “Đô la Mỹ”. Mặc định ẩn.'],
            ['Người cập nhật', 'Người sửa bản ghi gần nhất. Mặc định ẩn.'],
            ['Ngày cập nhật', 'Thời điểm sửa gần nhất, dạng dd/mm/yyyy hh:mm. Mặc định ẩn, sắp xếp được.'],
            ['Người tạo', 'Người đã thêm bản ghi.'],
            ['Ngày tạo', 'Thời điểm thêm, dạng dd/mm/yyyy hh:mm, sắp xếp được.'],
            ['Trạng thái', 'Nhãn Hoạt động hoặc Khóa.'],
            ['Hành động', 'Các nút thao tác của dòng (xem mục 4).'],
        ],
        'hanh_dong': {
            'intro': 'Trên mỗi dòng, cột Hành động có các nút:',
            'bullets': [
                'Biểu tượng bút chì {icon:btn_sua} — mở cửa sổ Sửa tiền tệ. Chỉ hiện với người có quyền Quản lý và khi tiền tệ đang Hoạt động.',
                'Biểu tượng thùng rác {icon:btn_xoa} — xóa tiền tệ. Chỉ hiện với người có quyền Quản lý và khi tiền tệ CHƯA được dùng ở chứng từ nào.',
                'Khóa / Mở khóa — đổi trạng thái tiền tệ. Chỉ hiện với người có quyền Quản lý.',
                'Lịch sử — mở cửa sổ Lịch sử thay đổi. Mọi người vào được màn hình đều thấy.',
                'Có từ 4 nút trở lên thì 2 nút đầu hiện thẳng, các nút còn lại nằm trong nút ba chấm {icon:btn_bacham} “Hành động khác”.',
            ],
            'anh': 'Các nút ở cột Hành động của một tiền tệ',
            'luu_y': ['Lưu ý: tình trạng “đang được dùng” được hệ thống kiểm tra sau khi bảng hiện ra khoảng vài trăm mili giây, nên nút Xóa có thể hiện thoáng qua rồi mới ẩn. Nếu bấm Xóa đúng lúc đó, hệ thống vẫn kiểm tra lại và chặn (xem PHẦN 4).',
                      'Người chỉ có quyền Xem chỉ thấy nút Lịch sử.'],
        },
        'phan_trang': [
            'Cuối bảng có dòng “Hiển thị a–b / N”: N là tổng số tiền tệ khớp bộ lọc đang áp dụng, không phải tổng toàn danh mục.',
            'Ô Số dòng/trang có các mức 5, 10, 20, 50, 100 (mặc định 10). Đổi số dòng thì hệ thống tự quay về trang 1.',
            'Các cột sắp xếp được: Mã tiền tệ, Tên tiền tệ, Tỷ giá (VNĐ), Ngày tạo, Ngày cập nhật. Bấm tiêu đề cột để sắp xếp, bấm lần hai để đảo chiều. Thứ tự sắp xếp được giữ nguyên khi chuyển trang.',
        ],
    },

    'loc': {
        'buoc2': 'Bước 2: Nhập chữ vào ô tìm kiếm nhanh hoặc chọn giá trị ở ô Trạng thái.',
        'rows': [
            ['Ô tìm kiếm nhanh', 'Placeholder “Tìm theo mã, tên hoặc tên gọi khác...”. Quét đồng thời Mã tiền tệ, Tên tiền tệ và Tên gọi khác, gõ một phần chuỗi cũng ra (gõ “US” vẫn ra USD), không phân biệt hoa thường. Nhấn Enter hoặc bấm Tìm kiếm để lọc.'],
            ['Trạng thái', 'Hoạt động hoặc Khóa. Bỏ trống thì hiện cả hai trạng thái. Lọc ngay khi chọn.'],
        ],
        'ap_dung': [
            'Các tiêu chí kết hợp với nhau theo kiểu VÀ — chỉ bản ghi thỏa đồng thời tất cả các tiêu chí mới hiện ra. Mỗi lần đổi tiêu chí, danh sách quay về trang 1.',
            'Bấm {icon:btn_lammoi} để xóa toàn bộ tiêu chí; danh sách nạp lại đầy đủ ngay lập tức.',
            'Hệ thống ghi nhớ bộ lọc trong 10 phút: rời màn rồi quay lại trong khoảng đó thì điều kiện lọc cũ vẫn còn.',
        ],
        'anh_ket_qua': 'Kết quả tìm nhanh theo mã tiền tệ (gõ “USD”)',
    },

    'form': {
        'kieu': 'popup',
        'buoc_tao': [
            'Bước 1: Truy cập vào màn hình Danh mục tiền tệ.',
            'Bước 2: Bấm {icon:btn_taomoi}. Hệ thống mở cửa sổ “Tạo tiền tệ”.',
            'Bước 3: Nhập/ chọn thông tin: Mã tiền tệ, Trạng thái, Tên tiền tệ, Tên gọi khác, Tỷ giá (VNĐ).',
            'Bước 4: Bấm {icon:btn_luu} để lưu và đóng cửa sổ, hoặc {icon:btn_luutieptuc} để lưu rồi nhập tiếp tiền tệ khác.',
        ],
        'anh_tao': 'Cửa sổ Tạo tiền tệ',
        'truong': [
            ['Mã tiền tệ', 'Ô nhập giá trị', 'Có', 'Trống', 'Tối đa 255 ký tự, chỉ gồm chữ không dấu, số, dấu - và _ (gõ sai báo ngay “Chỉ gồm chữ không dấu, số, dấu - và _”). Hệ thống tự bỏ khoảng trắng hai đầu và chuyển sang chữ IN HOA khi lưu. Duy nhất trong danh mục; trùng báo “Mã tiền tệ đã tồn tại” (“usd” cũng bị coi là trùng “USD”).'],
            ['Trạng thái', 'Ô chọn giá trị', 'Không', 'Hoạt động', 'Chỉ chọn 1 trong 2 giá trị: Hoạt động / Khóa.'],
            ['Tên tiền tệ', 'Ô nhập giá trị', 'Có', 'Trống', 'Tối đa 255 ký tự, duy nhất trong danh mục. Bỏ trống báo “Bắt buộc phải nhập”; trùng báo “Tên tiền tệ đã tồn tại”.'],
            ['Tên gọi khác', 'Ô nhập giá trị', 'Không', 'Trống', 'Tên thông dụng, ví dụ “Đô la Mỹ”. Tối đa 255 ký tự, được phép trùng.'],
            ['Tỷ giá (VNĐ)', 'Ô nhập số', 'Có', 'Trống', 'Nhập theo chuẩn quốc tế: dấu phẩy ngăn hàng nghìn, dấu chấm thập phân (ví dụ 26,520.00). Phải lớn hơn 0, tối đa 999,999.99.'],
        ],
        'sau_truong': ['Ba trường bắt buộc — Mã tiền tệ, Tên tiền tệ, Tỷ giá (VNĐ) — có dấu sao đỏ bên cạnh nhãn. Tên tiền tệ được kiểm tra ngay khi bấm Lưu; Mã tiền tệ và Tỷ giá bỏ trống sẽ được máy chủ báo lại ngay dưới ô sau khi bấm Lưu.'],
        'nut': [
            ['Lưu', 'Ghi bản ghi rồi đóng cửa sổ, báo “Thêm mới thành công” (hoặc “Cập nhật thành công” khi sửa) và nạp lại danh sách.'],
            ['Lưu và tiếp tục', 'Ghi bản ghi nhưng GIỮ cửa sổ mở và xóa trắng các ô để nhập tiếp. Chỉ có khi Tạo mới.'],
            ['Đóng', 'Đóng cửa sổ, không ghi gì. Nếu đã nhập dở, hệ thống hỏi “Thông tin chưa lưu” — “Bạn có thông tin chưa lưu. Có chắc chắn muốn thoát?” (Thoát / Ở lại).'],
        ],
        'loi': [
            ['Bắt buộc phải nhập', 'Chưa nhập Mã tiền tệ, Tên tiền tệ hoặc Tỷ giá (VNĐ).'],
            ['Chỉ gồm chữ không dấu, số, dấu - và _', 'Mã tiền tệ có dấu tiếng Việt, khoảng trắng hoặc ký tự đặc biệt khác.'],
            ['Mã tiền tệ đã tồn tại', 'Đã có tiền tệ khác cùng mã (không phân biệt hoa thường).'],
            ['Tên tiền tệ đã tồn tại', 'Đã có tiền tệ khác cùng tên.'],
            ['Phải là số', 'Tỷ giá có chữ cái hoặc ký tự không phải số.'],
            ['Phải lớn hơn 0', 'Tỷ giá bằng 0 hoặc âm.'],
            ['Tối đa 999999.99', 'Tỷ giá vượt trần cho phép.'],
            ['Vui lòng nhập tối đa 255 ký tự.', 'Mã, Tên hoặc Tên gọi khác quá dài.'],
            ['Bạn chưa nhập đầy đủ thông tin', 'Thông báo chung khi còn ô bị lỗi; xem các ô báo đỏ trong cửa sổ.'],
        ],
    },

    'sua': {
        'buoc': [
            'Bước 1: Truy cập vào màn hình Danh mục tiền tệ.',
            'Bước 2: Bấm nút {icon:btn_sua} ở cột Hành động của tiền tệ cần sửa.',
            'Bước 3: Hệ thống hiển thị cửa sổ “Sửa tiền tệ” với dữ liệu hiện tại (tỷ giá hiện dạng 26,520.00).',
            'Bước 4: Cập nhật các thông tin cần sửa (quy tắc nhập như Thêm mới).',
            'Bước 5: Bấm {icon:btn_luu} để xác nhận thay đổi hoặc Đóng nếu muốn hủy.',
        ],
        'anh': 'Cửa sổ Sửa tiền tệ',
        'ghi_chu': [
            'Cửa sổ Sửa không có nút “Lưu và tiếp tục”.',
            'Giữ nguyên mã/tên của chính tiền tệ đang sửa thì không bị báo trùng.',
            'Tiền tệ đang Khóa không có nút Sửa. Nếu tiền tệ vừa bị người khác khóa, bấm Lưu sẽ nhận thông báo “Tiền tệ đang bị khoá, vui lòng mở khoá trước khi cập nhật.”',
            'Sửa tỷ giá không làm thay đổi các chứng từ đã lập trước đó.',
        ],
    },
    'xoa': {
        'buoc': [
            'Bước 1: Ở cột Hành động, Người dùng bấm {icon:btn_xoa}. Hệ thống kiểm tra tiền tệ có đang được dùng không.',
            'Bước 2: Chưa được dùng — hệ thống hiện hộp “Xác nhận xóa” — “Bạn có chắc muốn xóa tiền tệ \'…\'?”. Bấm {icon:btn_confirm_xoa} để xác nhận: hệ thống báo “Xóa thành công”, bản ghi biến mất khỏi danh sách.',
            'Bấm {icon:btn_huy} nếu bấm nhầm. Không có gì thay đổi.',
        ],
        'anh': 'Hộp xác nhận xóa tiền tệ',
        'ghi_chu': [
            'Chỉ xóa được tiền tệ CHƯA từng được dùng ở chứng từ nào (báo giá, hợp đồng, hóa đơn, tờ khai hải quan, công nợ, chi tiết tài khoản…). Tiền tệ đang được dùng thì nút Xóa không hiển thị; nếu bấm đúng lúc nút chưa kịp ẩn, hệ thống báo “Tiền tệ đang được sử dụng ở: … Không thể xóa. Hãy chuyển sang trạng thái Khóa.” (nêu tối đa 3 nơi đang dùng).',
            'Xóa là thao tác không lùi lại được. Muốn ngừng dùng một tiền tệ, nên dùng Khóa thay cho Xóa.',
        ],
    },
    'khoa': {
        'y_nghia': [
            'Bản ghi VẪN nằm trong danh sách, cột Trạng thái hiện chữ Khóa; tìm lại được bằng bộ lọc Trạng thái = Khóa.',
            'Vẫn xem được chi tiết và lịch sử thay đổi của bản ghi.',
            'Tiền tệ đã khóa không còn xuất hiện ở ô chọn tiền tệ khi lập chứng từ MỚI; chứng từ đã lập trước đó vẫn hiện đúng tiền tệ này (kèm biểu tượng 🔒 ở ô chọn).',
            'Nút Sửa của dòng đó biến mất.',
            'Khóa luôn thực hiện được, kể cả với tiền tệ đang được dùng ở nhiều chứng từ.',
        ],
        'buoc_khoa': [
            'Bước 1: Ở cột Hành động, Người dùng chọn Khóa (trong nút ba chấm nếu dòng có nhiều nút).',
            'Bước 2: Hệ thống hiện hộp “Xác nhận khóa” — “Bạn có chắc muốn khóa tiền tệ \'…\'?”. Bấm Khóa để xác nhận; hệ thống báo “Khóa thành công”, cột Trạng thái đổi thành Khóa. Bấm Hủy nếu bấm nhầm.',
        ],
        'buoc_mo': [
            'Bước 1: Ở cột Hành động của tiền tệ đang Khóa, Người dùng chọn Mở khóa.',
            'Bước 2: Bấm Mở khóa trong hộp “Xác nhận mở khóa”. Hệ thống báo “Mở khóa thành công”, cột Trạng thái đổi thành Hoạt động. Bấm Hủy nếu bấm nhầm.',
        ],
        'ghi_chu': ['Có thể khóa ngay trong cửa sổ Sửa bằng cách chọn Trạng thái = Khóa rồi Lưu. Nếu bản ghi vừa bị người khác đổi trạng thái, hệ thống báo “Tiền tệ đang bị khóa” hoặc “Tiền tệ đang hoạt động”.'],
    },
    'lich_su': {
        'buoc': [
            'Xem từ màn danh sách: ở cột Hành động, Người dùng chọn Lịch sử.',
            'Xem từ màn chi tiết: bấm vào mã tiền tệ để mở cửa sổ Xem tiền tệ, khối Lịch sử nằm ở cuối cửa sổ.',
        ],
        'ghi_chu': ['Cửa sổ có bộ lọc riêng (loại hành động, người thực hiện, khoảng thời gian) để thu hẹp danh sách khi bản ghi có nhiều lần thay đổi. Tỷ giá do hệ thống tự cập nhật hằng ngày (PHẦN 7) không ghi vào lịch sử.'],
    },
    'chi_tiet': {
        'buoc': ['Bước 1: Truy cập vào màn hình Danh mục tiền tệ.',
                 'Bước 2: Bấm vào mã tiền tệ ở cột Mã tiền tệ. Hệ thống mở cửa sổ “Xem tiền tệ”.'],
        'ghi_chu': ['Cửa sổ hiển thị Mã tiền tệ, Trạng thái, Tên tiền tệ, Tên gọi khác, Tỷ giá (VNĐ) ở chế độ chỉ đọc (không gõ được, không có nút Lưu, chỉ có nút Đóng), kèm khối Lịch sử ở cuối. Người chỉ có quyền Xem và tiền tệ đang Khóa vẫn xem được bình thường.'],
    },
    'phan_rieng': [
        {'tieu_de': 'TỶ GIÁ TỰ CẬP NHẬT HẰNG NGÀY', 'noi_dung': [
            ('p', 'Hệ thống tự cập nhật lại tỷ giá của toàn bộ danh mục vào 03:00 sáng mỗi ngày, lấy theo tỷ giá BÁN của Vietcombank và khớp theo Mã tiền tệ. Riêng đồng Việt Nam (mã VNĐ / VND) được bỏ qua; mã nào Vietcombank không công bố thì giữ nguyên tỷ giá cũ.'),
            ('p', 'Vì vậy tỷ giá sửa tay hôm nay có thể thay đổi vào sáng hôm sau — đây là hành vi đúng theo thiết kế, không phải mất dữ liệu. Cần một tỷ giá cố định cho một chứng từ cụ thể thì khai ngay trên chứng từ đó, không dựa vào danh mục.'),
        ]},
    ],
    'xuat': {
        'buoc': [
            'Bước 1: Lọc danh sách theo đúng dữ liệu cần lấy (xem PHẦN 2). File xuất ra chạy theo đúng bộ lọc và thứ tự sắp xếp đang áp dụng.',
            'Bước 2: Bấm nút {icon:btn_xuatexcel}. Hệ thống mở cửa sổ “Chọn trường xuất file”.',
            'Bước 3: Tích chọn, kéo biểu tượng ☰ để đổi vị trí các trường cần xuất. Mặc định hệ thống tích sẵn đúng những cột đang hiển thị trên bảng.',
            'Bước 4: Bấm {icon:btn_xuatfile}. Hệ thống tải về file danh_muc_tien_te.xlsx và báo “Xuất Excel thành công”.',
        ],
        'truong': 'Chọn nhiều trường: Mã tiền tệ, Tên tiền tệ, Tên gọi khác, Tỷ giá (VNĐ), Trạng thái, Người tạo, Ngày tạo, Người cập nhật, Ngày cập nhật.',
        'ghi_chu': ['Lưu ý: file xuất chứa TOÀN BỘ kết quả của bộ lọc (tối đa 10,000 dòng), không chỉ các dòng của trang đang xem. Kết quả lọc rỗng thì file chỉ có dòng tiêu đề. Người chỉ có quyền Xem vẫn xuất được Excel.'],
    },
    'import': {
        'tieu_de': 'Import tiền tệ',
        'file': 'Mau_import_tien_te.xlsx',
        'cot_text': 'STT, Mã tiền tệ (bắt buộc), Tên tiền tệ (bắt buộc), Tên gọi khác, Tỷ giá (VNĐ) (bắt buộc), Trạng thái (chọn Hoạt động / Khóa trong danh sách sổ xuống)',
        'toast': 'Import thành công N tiền tệ.',
        'loi': [
            ['Mã tiền tệ không được để trống', 'Dòng đó bỏ trống cột Mã tiền tệ.'],
            ['Mã tiền tệ tối đa 255 ký tự', 'Mã quá dài, rút gọn lại.'],
            ['Mã tiền tệ: Chỉ gồm chữ không dấu, số, dấu - và _', 'Mã có dấu tiếng Việt, khoảng trắng hoặc ký tự đặc biệt.'],
            ['Mã tiền tệ bị trùng với dòng N trong file', 'Trong chính file có hai dòng cùng mã (không phân biệt hoa thường). Xoá bớt một dòng.'],
            ['Mã tiền tệ đã tồn tại trong hệ thống', 'Danh mục đã có tiền tệ cùng mã.'],
            ['Tên tiền tệ không được để trống', 'Dòng đó bỏ trống cột Tên tiền tệ.'],
            ['Tên tiền tệ tối đa 255 ký tự', 'Tên quá dài, rút gọn lại.'],
            ['Tên tiền tệ bị trùng với dòng N trong file', 'Trong chính file có hai dòng cùng tên. Xoá bớt một dòng.'],
            ['Tên tiền tệ đã tồn tại trong hệ thống', 'Danh mục đã có tiền tệ cùng tên.'],
            ['Tên gọi khác tối đa 255 ký tự', 'Tên gọi khác quá dài, rút gọn lại.'],
            ['Tỷ giá không được để trống', 'Dòng đó bỏ trống cột Tỷ giá (VNĐ).'],
            ['Tỷ giá không hợp lệ', 'Tỷ giá không phải số, hoặc bằng 0, hoặc âm. Dùng dấu phẩy ngăn hàng nghìn, dấu chấm thập phân.'],
            ['Trạng thái chỉ nhận "Hoạt động" hoặc "Khóa"', 'Cột Trạng thái ghi giá trị khác (để trống = Hoạt động).'],
        ],
        'ghi_chu': [
            'Lưu ý: Mã tiền tệ trong file được tự chuyển sang chữ IN HOA. Cột Trạng thái để trống thì tiền tệ được tạo ở trạng thái Hoạt động; chọn Khóa thì tạo luôn ở trạng thái Khóa. Người tạo là chính người thực hiện nhập, lịch sử có mốc Tạo mới.',
            'Mỗi lần nhập tối đa 500 dòng; file dài hơn hệ thống báo “File có X dòng dữ liệu, vượt quá giới hạn 500 dòng mỗi lần import. Vui lòng tách file và import nhiều lần.”',
        ],
    },
    'tuy_chinh_cot': {'cot_khoa': 'Bốn cột STT, Mã tiền tệ, Tên tiền tệ và Hành động'},

    'shots': {'list': '01_list.png', 'rowmenu': '03_rowmenu.png', 'filter': 'filter.png', 'filter_result': '04_filter_result.png',
              'create': '10_create.png', 'create_error': '11_create_error.png', 'code_error': '11b_code_error.png', 'edit': '12_edit.png',
              'delete': '13_delete.png', 'lock': '14_lock.png', 'unlock': '15_unlock.png', 'history': '16_history.png',
              'detail': '17_detail.png', 'export': '20_export.png', 'import_open': '21_import_open.png',
              'import_loaded': '22_import_loaded.png', 'import_validated': '23_import_validated.png', 'colcfg': '25_colcfg.png'},

    'capture': {'route': '/finance/currencies',
                'menu': {'phanhe': 'TÀI CHÍNH', 'nhom': 'Danh mục', 'muc': 'Danh mục tiền tệ'},
                'search': 'Tìm theo mã, tên', 'searchText': 'USD', 'detailCol': 1,
                'lockName': 'KWR', 'codeInput': 'VD: USD', 'create': True, 'lock': True},

    'import_test': {
        'cols': ['STT', 'Mã tiền tệ', 'Tên tiền tệ', 'Tên gọi khác', 'Tỷ giá (VNĐ)', 'Trạng thái'],
        'rows': [
            [1, 'SGD', 'DOC-Đô la Singapore', 'Singapore Dollar', '19,850.50', 'Hoạt động'],
            [2, 'thb', 'DOC-Baht Thái', 'Thai Baht', '715.20', 'Hoạt động'],
            [3, 'MYR', 'DOC-Ringgit Malaysia', '', '5,610', 'Khóa'],
            [4, '', 'DOC-Thiếu mã', '', '100', 'Hoạt động'],
            [5, 'SGD', 'DOC-Trùng mã trong file', '', '100', 'Hoạt động'],
            [6, 'USD', 'DOC-Trùng mã hệ thống', '', '100', 'Hoạt động'],
            [7, 'VNĐ-2', 'DOC-Mã có dấu', '', '1', 'Hoạt động'],
            [8, 'HKD', 'DOC-Tỷ giá sai', '', 'abc', 'Hoạt động'],
        ],
    },

    'uml': {
        'mains': [('FR-01', 'Xem danh sách tiền tệ', 'view'), ('FR-03', 'Thêm mới tiền tệ', 'crud'),
                  ('FR-04', 'Chỉnh sửa tiền tệ', 'crud'), ('FR-05', 'Xóa tiền tệ', 'action'),
                  ('FR-06', 'Khóa / Mở khóa tiền tệ', 'action'), ('FR-08', 'Import file tiền tệ', 'io'),
                  ('FR-09', 'Xuất danh sách tiền tệ ra Excel', 'io')],
        'subs': [('FR-02', 'Tìm kiếm và lọc tiền tệ', 'view'), ('FR-10', 'Xem chi tiết tiền tệ', 'view'),
                 ('FR-11', 'Tùy chỉnh cột hiển thị', 'view'), ('FR-07', 'Xem lịch sử thay đổi', 'view')],
        'rieng': [('FR-10', 'Xem chi tiết tiền tệ', 'view')],
    },

    'srs': {
        'muc_dich': ['Là căn cứ nghiệm thu chức năng.',
                     'Làm rõ quy tắc Mã tiền tệ (ký tự cho phép, tự in hoa, duy nhất), ràng buộc Xóa khi tiền tệ đã được dùng và cơ chế tự cập nhật tỷ giá hằng ngày.'],
        'quyen_truoc': ['Màn hình dùng hai quyền riêng thuộc nhóm “Danh mục tài chính”. Không có quyền nào thì không vào được màn hình. Máy chủ kiểm tra quyền ở từng chức năng, không chỉ dựa vào việc ẩn nút.'],
        'quyen_rows': [[Q_XEM, 'Xem danh sách, tìm kiếm/lọc, xem chi tiết, xem lịch sử, xuất Excel, tùy chỉnh cột.'],
                       [Q_QL, 'Toàn bộ quyền Xem + Thêm mới, Sửa, Xóa, Khóa/Mở khóa, Import Excel.']],
        'ma_tran': [['Chức năng', Q_QL, Q_XEM]] + [[f, 'Có', x] for f, x in [
            ('FR-01 Xem danh sách tiền tệ', 'Có'), ('FR-02 Tìm kiếm và lọc', 'Có'), ('FR-03 Thêm mới tiền tệ', 'Không'),
            ('FR-04 Chỉnh sửa tiền tệ', 'Không'), ('FR-05 Xóa tiền tệ', 'Không'), ('FR-06 Khóa / Mở khóa tiền tệ', 'Không'),
            ('FR-07 Xem lịch sử thay đổi', 'Có'), ('FR-08 Import file tiền tệ', 'Không'), ('FR-09 Xuất danh sách ra Excel', 'Có'),
            ('FR-10 Xem chi tiết tiền tệ', 'Có'), ('FR-11 Tùy chỉnh cột hiển thị', 'Có')]],
        'ma_tran_widths': [2.4, 1.6, 1.6],
        'quyen_sau': ['Danh mục KHÔNG phân quyền theo công ty / phòng ban / bộ phận.'],
        'fr': [
            {'ten': 'Xem danh sách tiền tệ',
             'qtc': 'Màn Danh sách, Sắp xếp dữ liệu bảng, Phân trang và Cấu hình cột. Chỉ bổ sung các quy tắc riêng của Danh mục tiền tệ tại phần mô tả chi tiết.',
             'gioi_thieu': [['Tên chức năng', 'Xem danh sách tiền tệ'],
                            ['Mô tả', 'Hiển thị toàn bộ tiền tệ trong danh mục, có phân trang và sắp xếp.'],
                            ['Tác nhân', 'Người có quyền “%s” hoặc “%s”' % (Q_QL, Q_XEM)],
                            ['Điều kiện ban đầu', 'Người dùng đã đăng nhập và có một trong hai quyền trên.'],
                            ['Dòng sự kiện chính', '1. Người dùng vào menu Tài chính → Danh mục → Danh mục tiền tệ.\n2. Hệ thống nạp trang đầu tiên của danh sách (10 dòng), xếp theo thứ tự thêm vào danh mục.\n3. Bảng hiển thị dữ liệu kèm tổng số bản ghi.\n4. Hệ thống kiểm tra tình trạng “đang được dùng” của các dòng đang hiện để ẩn nút Xóa.'],
                            ['Dòng sự kiện phụ', '• Không có bản ghi khớp → bảng hiện “Không có dữ liệu phù hợp bộ lọc.”\n• Không có quyền → không vào được màn hình.\n• Phiên đăng nhập hết hạn → điều hướng về màn đăng nhập.']],
             'anh': [('list', 'Màn Danh mục tiền tệ lúc mới truy cập')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Mô tả'],
                    ['1', 'STT', 'Table/Grid', 'Read-only', 'Số thứ tự, chạy liên tục qua các trang. Luôn hiển thị.'],
                    ['2', 'Mã tiền tệ', 'Table/Grid', 'Read-only', 'Luôn hiển thị, sắp xếp được. Bấm vào mã mở cửa sổ Xem (xem 2.10).'],
                    ['3', 'Tên tiền tệ', 'Table/Grid', 'Read-only', 'Luôn hiển thị, sắp xếp được.'],
                    ['4', 'Tỷ giá (VNĐ)', 'Table/Grid', 'Read-only', 'Căn phải, 2 chữ số thập phân, dạng 26,520.00. Sắp xếp được.'],
                    ['5', 'Tên gọi khác', 'Table/Grid', 'Read-only', 'Mặc định ẩn.'],
                    ['6', 'Người cập nhật', 'Table/Grid', 'Read-only', 'Mặc định ẩn.'],
                    ['7', 'Ngày cập nhật', 'Table/Grid', 'Read-only', 'dd/mm/yyyy hh:mm. Mặc định ẩn, sắp xếp được.'],
                    ['8', 'Người tạo', 'Table/Grid', 'Read-only', 'Người đã thêm bản ghi.'],
                    ['9', 'Ngày tạo', 'Table/Grid', 'Read-only', 'dd/mm/yyyy hh:mm, sắp xếp được.'],
                    ['10', 'Trạng thái', 'Badge', 'Read-only', 'Hoạt động hoặc Khóa.'],
                    ['11', 'Hành động', 'Table/Grid', 'Read-only', 'Sửa (có quyền Quản lý, đang Hoạt động), Xóa (có quyền Quản lý, chưa được dùng), Khóa / Mở khóa (có quyền Quản lý), Lịch sử (mọi người). Từ 4 nút trở lên thì 2 nút đầu hiện thẳng, còn lại trong nút ba chấm.'],
                    ['12', 'Nút Tạo mới', 'Button', 'Enable', 'Chỉ hiện với quyền Quản lý. Mở cửa sổ Tạo tiền tệ.'],
                    ['13', 'Nút Xuất Excel', 'Button', 'Enable', 'Mở cửa sổ Chọn trường xuất file (xem 2.9).'],
                    ['14', 'Nút Import Excel', 'Button', 'Enable', 'Chỉ hiện với quyền Quản lý. Mở cửa sổ Import tiền tệ (xem 2.8).'],
                    ['15', 'Biểu tượng Cấu hình cột hiển thị', 'Icon Button', 'Enable', 'Mở cửa sổ Tuỳ chỉnh cột (xem 2.11).'],
                    ['16', 'Phân trang', 'Pagination', 'Enable', 'Số dòng/trang 5 / 10 / 20 / 50 / 100, mặc định 10.']],
             'ui_widths': [0.6, 1.4, 0.9, 0.8, 3],
             'events': [['Mở màn hình', 'System', 'After:\n– Nạp trang đầu, hiển thị tổng số bản ghi.\n– Kiểm tra “đang được dùng” cho các dòng đang hiện (chạy sau, không chặn hiển thị bảng).'],
                        ['Bấm tiêu đề cột sắp xếp được', 'Click', 'After:\n– Đổi chiều sắp xếp và nạp lại danh sách từ trang 1.'],
                        ['Chuyển trang', 'Click', 'Before:\n– Giữ nguyên bộ lọc và thứ tự sắp xếp.\nAfter:\n– Nạp dữ liệu trang mới, số thứ tự tiếp tục liên tục.'],
                        ['Đổi số dòng mỗi trang', 'Change', 'After:\n– Quay về trang 1 và nạp lại theo số dòng mới.']]},
            {'ten': 'Tìm kiếm và lọc',
             'qtc': 'Kịch bản tìm kiếm, Bộ lọc, Dropdown, Phân trang. Chỉ bổ sung các tiêu chí tìm kiếm/lọc riêng của Danh mục tiền tệ.',
             'gioi_thieu': [['Tên chức năng', 'Tìm kiếm và lọc danh sách'],
                            ['Mô tả', 'Thu hẹp danh sách bằng ô tìm kiếm nhanh và ô Trạng thái (bộ lọc gọn một hàng, không có nút Tìm kiếm nâng cao).'],
                            ['Tác nhân', 'Người có quyền Quản lý hoặc Xem danh mục tiền tệ'],
                            ['Điều kiện ban đầu', 'Đang ở màn Danh mục tiền tệ.'],
                            ['Dòng sự kiện chính', '1. Người dùng nhập từ khóa và bấm Tìm kiếm / Enter, hoặc chọn Trạng thái (lọc ngay).\n2. Hệ thống áp đồng thời mọi tiêu chí và nạp lại danh sách từ trang 1.'],
                            ['Dòng sự kiện phụ', '• Không có kết quả → bảng hiện “Không có dữ liệu phù hợp bộ lọc.”\n• Bấm Làm mới → xóa hết tiêu chí VÀ nạp lại danh sách đầy đủ ngay.\n• Bộ lọc được ghi nhớ 10 phút khi rời màn rồi quay lại.']],
             'anh': [('filter', 'Khu vực tìm kiếm và lọc của màn Danh mục tiền tệ')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Phạm vi', 'Mô tả'],
                    ['1', 'Ô tìm kiếm nhanh', 'Textbox', 'Enable', '0–255 ký tự', 'Placeholder “Tìm theo mã, tên hoặc tên gọi khác...”. Khớp một phần, không phân biệt hoa thường.'],
                    ['2', 'Trạng thái', 'Dropdown', 'Enable', 'Hoạt động / Khóa', 'Nhãn nổi. Bỏ trống thì hiện cả hai trạng thái.'],
                    ['3', 'Nút Tìm kiếm', 'Button', 'Enable', '–', 'Áp dụng các tiêu chí.'],
                    ['4', 'Nút Làm mới', 'Button', 'Enable', '–', 'Xóa hết tiêu chí VÀ nạp lại danh sách ngay.']],
             'ui_widths': [0.6, 1.2, 0.8, 0.7, 1.1, 2.6],
             'events': [['Bấm Tìm kiếm / Enter', 'Click', 'After:\n– Áp đồng thời các tiêu chí theo kiểu “và”, nạp lại bảng từ trang 1.'],
                        ['Chọn Trạng thái', 'Change', 'After:\n– Lọc ngay, nạp lại bảng từ trang 1.'],
                        ['Bấm Làm mới', 'Click', 'After:\n– Xóa trắng mọi tiêu chí VÀ nạp lại danh sách đầy đủ.']]},
            {'ten': 'Thêm mới tiền tệ', 'uc': 'uc_fr03',
             'qtc': 'Màn Thêm mới, Validate dữ liệu, Thông báo và UI/UX. Logic ghi lịch sử áp dụng theo SRS Các quy tắc chung - Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Thêm mới tiền tệ'],
                            ['Mô tả', 'Thêm một tiền tệ mới thông qua cửa sổ nhập liệu.'],
                            ['Tác nhân', 'Người có quyền “%s”' % Q_QL],
                            ['Điều kiện ban đầu', 'Đang ở màn Danh mục tiền tệ.'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm Tạo mới.\n2. Hệ thống mở cửa sổ “Tạo tiền tệ”, Trạng thái mặc định Hoạt động.\n3. Người dùng nhập Mã, Tên, Tên gọi khác, Tỷ giá (VNĐ) và bấm Lưu.\n4. Hệ thống bỏ khoảng trắng hai đầu, chuyển Mã sang chữ IN HOA, bỏ dấu phẩy ngăn nghìn của Tỷ giá; kiểm tra dữ liệu, ghi bản ghi mới và ghi lịch sử Tạo mới.\n5. Cửa sổ đóng, danh sách nạp lại, báo “Thêm mới thành công”.'],
                            ['Dòng sự kiện phụ', '• Thiếu trường bắt buộc, sai định dạng hoặc trùng mã/tên → báo lỗi đỏ dưới ô + toast “Bạn chưa nhập đầy đủ thông tin”, cửa sổ KHÔNG đóng.\n• Bấm “Lưu và tiếp tục” → ghi bản ghi rồi giữ cửa sổ mở với các ô trống.\n• Bấm Đóng khi đã nhập dở → hỏi “Thông tin chưa lưu” (Thoát / Ở lại).'],
                            ['Yêu cầu đặc biệt', 'Cửa sổ có ba nút: Lưu, Lưu và tiếp tục, Đóng.']],
             'menu_them': ' => Tạo mới {icon:btn_taomoi}',
             'ghi_chu_layout': 'Cửa sổ Tạo tiền tệ được mở ngay trên màn hình danh sách.',
             'anh': [('create', 'Cửa sổ Tạo tiền tệ'), ('create_error', 'Lỗi đỏ ngay dưới ô còn thiếu'), ('code_error', 'Lỗi định dạng Mã tiền tệ hiện ngay khi gõ')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Phạm vi', 'Bắt buộc', 'Mô tả'],
                    ['1', 'Mã tiền tệ', 'Textbox', 'Enable', '1–255 ký tự: A-Z, a-z, 0-9, - và _', 'Có', 'Tự bỏ khoảng trắng hai đầu, tự IN HOA khi lưu. Duy nhất (không phân biệt hoa thường). Sai ký tự “Chỉ gồm chữ không dấu, số, dấu - và _”; trùng “Mã tiền tệ đã tồn tại”; bỏ trống “Bắt buộc phải nhập”.'],
                    ['2', 'Trạng thái', 'Dropdown', 'Enable', 'Hoạt động / Khóa', 'Không', 'Mặc định Hoạt động.'],
                    ['3', 'Tên tiền tệ', 'Textbox', 'Enable', '1–255 ký tự', 'Có', 'Duy nhất. Bỏ trống “Bắt buộc phải nhập”; trùng “Tên tiền tệ đã tồn tại”.'],
                    ['4', 'Tên gọi khác', 'Textbox', 'Enable', '0–255 ký tự', 'Không', 'Được phép trùng.'],
                    ['5', 'Tỷ giá (VNĐ)', 'Textbox số', 'Enable', '> 0 và ≤ 999,999.99', 'Có', 'Dấu phẩy ngăn nghìn, dấu chấm thập phân. Lỗi: “Phải là số”, “Phải lớn hơn 0”, “Tối đa 999999.99”.'],
                    ['6', 'Nút Lưu', 'Button', 'Enable', '', '', 'Ghi bản ghi rồi đóng cửa sổ.'],
                    ['7', 'Nút Lưu và tiếp tục', 'Button', 'Enable', '', '', 'Ghi bản ghi rồi giữ cửa sổ mở để nhập tiếp.'],
                    ['8', 'Nút Đóng', 'Button', 'Enable', '', '', 'Hủy bỏ, không ghi gì.']],
             'ui_widths': [0.5, 1.1, 0.8, 0.6, 1.3, 0.5, 2.3],
             'events': [['Bấm nút Tạo mới', 'Click', 'After:\n– Mở cửa sổ nhập liệu với các ô trống, Trạng thái = Hoạt động.'],
                        ['Gõ Mã tiền tệ', 'Input', 'During:\n– Có ký tự ngoài chữ không dấu, số, - và _ → báo đỏ ngay dưới ô.'],
                        ['Bấm Lưu', 'Click', 'During:\n– Kiểm tra định dạng, bắt buộc, độ dài, trùng mã/tên.\n– Có lỗi → báo đỏ dưới ô, không thực hiện After.\nAfter:\n– Ghi bản ghi mới (Mã IN HOA), ghi lịch sử Tạo mới.\n– Đóng cửa sổ, nạp lại danh sách, báo “Thêm mới thành công”.'],
                        ['Bấm Lưu và tiếp tục', 'Click', 'During:\n– Như nút Lưu.\nAfter:\n– Ghi bản ghi, xóa trắng các ô, GIỮ cửa sổ mở.'],
                        ['Bấm Đóng', 'Click', 'After:\n– Chưa nhập gì → đóng cửa sổ. Đã nhập → hỏi “Thông tin chưa lưu”.']]},
            {'ten': 'Chỉnh sửa tiền tệ', 'uc': 'uc_fr04',
             'qtc': 'Validate dữ liệu, Thông báo, Quy định chung về danh mục và Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Chỉnh sửa tiền tệ'],
                            ['Mô tả', 'Sửa thông tin một tiền tệ đã có. Dùng chung cửa sổ với Thêm mới.'],
                            ['Tác nhân', 'Người có quyền “%s”' % Q_QL],
                            ['Điều kiện ban đầu', 'Tiền tệ đang ở trạng thái Hoạt động.'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm biểu tượng bút chì ở dòng cần sửa.\n2. Hệ thống mở cửa sổ “Sửa tiền tệ” với dữ liệu hiện tại.\n3. Người dùng sửa và bấm Lưu.\n4. Hệ thống kiểm tra, ghi thay đổi và ghi lịch sử.\n5. Cửa sổ đóng, báo “Cập nhật thành công”.'],
                            ['Dòng sự kiện phụ', '• Giữ nguyên mã/tên của chính bản ghi → không báo trùng.\n• Trùng mã/tên với tiền tệ khác → báo “Mã tiền tệ đã tồn tại” / “Tên tiền tệ đã tồn tại”.\n• Bản ghi vừa bị người khác khóa → báo “Tiền tệ đang bị khoá, vui lòng mở khoá trước khi cập nhật.”\n• Bản ghi vừa bị người khác xóa → báo “Dữ liệu đã thay đổi, vui lòng tải lại”.']],
             'menu_them': ' => Sửa {icon:btn_sua}',
             'anh': [('edit', 'Cửa sổ Sửa tiền tệ')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Phạm vi', 'Bắt buộc', 'Giá trị ban đầu', 'Mô tả'],
                    ['1', 'Tiêu đề cửa sổ', 'Label', 'Hiển thị', '–', '–', 'Sửa tiền tệ', 'Cửa sổ mở ngay trên màn danh sách.'],
                    ['2', 'Mã tiền tệ', 'Textbox', 'Enable', '1–255 ký tự: A-Z, a-z, 0-9, - và _', 'Có', 'Dữ liệu hiện tại', 'Tự bỏ khoảng trắng hai đầu, tự IN HOA khi lưu. Duy nhất (không phân biệt hoa thường, bỏ qua chính bản ghi). Sai ký tự “Chỉ gồm chữ không dấu, số, dấu - và _”; trùng “Mã tiền tệ đã tồn tại”; bỏ trống “Bắt buộc phải nhập”.'],
                    ['3', 'Trạng thái', 'Dropdown', 'Enable', 'Hoạt động / Khóa', 'Không', 'Dữ liệu hiện tại', 'Chọn Khóa rồi Lưu là khóa luôn tiền tệ.'],
                    ['4', 'Tên tiền tệ', 'Textbox', 'Enable', '1–255 ký tự', 'Có', 'Dữ liệu hiện tại', 'Duy nhất (bỏ qua chính bản ghi). Bỏ trống “Bắt buộc phải nhập”; trùng “Tên tiền tệ đã tồn tại”.'],
                    ['5', 'Tên gọi khác', 'Textbox', 'Enable', '0–255 ký tự', 'Không', 'Dữ liệu hiện tại', 'Được phép trùng.'],
                    ['6', 'Tỷ giá (VNĐ)', 'Textbox số', 'Enable', '> 0 và ≤ 999,999.99', 'Có', 'Dữ liệu hiện tại, dạng 26,520.00', 'Dấu phẩy ngăn nghìn, dấu chấm thập phân. Lỗi: “Phải là số”, “Phải lớn hơn 0”, “Tối đa 999999.99”.'],
                    ['7', 'Nút Lưu', 'Button', 'Enable', '–', '–', 'Hiển thị', 'Ghi thay đổi rồi đóng cửa sổ. Cửa sổ Sửa KHÔNG có nút Lưu và tiếp tục.'],
                    ['8', 'Nút Đóng', 'Button', 'Enable', '–', '–', 'Hiển thị', 'Hủy bỏ, không ghi gì; đã sửa dở thì hỏi “Thông tin chưa lưu”.']],
             'ui_widths': [0.5, 1.1, 0.8, 0.6, 1.2, 0.5, 1, 2.1],
             'events': [['Bấm biểu tượng bút chì', 'Click', 'Before:\n– Chỉ hiện với quyền Quản lý; bản ghi đã Khóa thì nút không hiển thị.\nAfter:\n– Nạp dữ liệu mới nhất từ máy chủ rồi mở cửa sổ “Sửa tiền tệ” với dữ liệu hiện tại.\n– Bản ghi vừa bị người khác xóa → báo “Dữ liệu đã thay đổi, vui lòng tải lại”, không mở cửa sổ.'],
                        ['Gõ Mã tiền tệ / Tỷ giá (VNĐ)', 'Input', 'During:\n– Mã có ký tự ngoài chữ không dấu, số, - và _ → báo đỏ ngay dưới ô.\n– Tỷ giá không phải số, ≤ 0 hoặc vượt 999,999.99 → báo đỏ ngay dưới ô.'],
                        ['Bấm Lưu', 'Click', 'Before:\n– Bản ghi vừa bị người khác khóa → máy chủ chặn trước mọi kiểm tra, báo “Tiền tệ đang bị khoá, vui lòng mở khoá trước khi cập nhật.”\nDuring:\n– Kiểm tra như Thêm mới, bỏ qua trùng với chính bản ghi.\n– Có lỗi → báo đỏ dưới ô + “Bạn chưa nhập đầy đủ thông tin”, không thực hiện After.\nAfter:\n– Ghi thay đổi, ghi lịch sử “Thay đổi thông tin” cho từng trường đã đổi (đổi Trạng thái ghi “Khóa”/“Mở khóa”).\n– Đóng cửa sổ, nạp lại danh sách, báo “Cập nhật thành công”.'],
                        ['Bấm Đóng / biểu tượng ×', 'Click', 'After:\n– Chưa sửa gì → đóng cửa sổ.\n– Đã sửa → hỏi “Thông tin chưa lưu” (Thoát / Ở lại).']]},
            {'ten': 'Xóa tiền tệ', 'uc': 'uc_fr05',
             'qtc': 'Quy tắc Xóa, Thông báo, Quy định chung về danh mục và Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Xóa tiền tệ'],
                            ['Mô tả', 'Xóa hẳn một tiền tệ chưa được dùng ở chứng từ nào.'],
                            ['Tác nhân', 'Người có quyền “%s”' % Q_QL],
                            ['Điều kiện ban đầu', 'Tiền tệ chưa được dùng ở bất kỳ nghiệp vụ nào.'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm biểu tượng thùng rác.\n2. Hệ thống kiểm tra lại tình trạng sử dụng; chưa dùng thì hiện hộp “Xác nhận xóa” nêu rõ tên bản ghi.\n3. Người dùng bấm Xóa.\n4. Hệ thống xóa bản ghi, báo “Xóa thành công”, nạp lại danh sách.'],
                            ['Dòng sự kiện phụ', '• Bấm Hủy → đóng hộp, không thay đổi.\n• Tiền tệ đang được dùng → nút Xóa không hiển thị; bấm kịp trước khi nút ẩn → báo “Tiền tệ đang được sử dụng ở: … Không thể xóa. Hãy chuyển sang trạng thái Khóa.”\n• Tiền tệ vừa bị người khác dùng ngay trước khi xác nhận → máy chủ vẫn chặn với thông báo tương tự.']],
             'menu_them': ' => Xóa {icon:btn_xoa}',
             'anh': [('delete', 'Hộp xác nhận xóa tiền tệ')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Mô tả'],
                    ['1', 'Biểu tượng thùng rác (Xóa)', 'Icon Button', 'Nằm ở cột Hành động. Chỉ hiện với quyền Quản lý và khi tiền tệ CHƯA được dùng (cờ “đang được dùng” nạp sau khi bảng hiện).'],
                    ['2', 'Tiêu đề hộp xác nhận', 'Label', '“Xác nhận xóa”.'],
                    ['3', 'Nội dung hộp xác nhận', 'Label', '“Bạn có chắc muốn xóa tiền tệ \'<tên tiền tệ>\'?” — nêu rõ tên bản ghi.'],
                    ['4', 'Nút Xóa', 'Button', 'Xác nhận xóa hẳn bản ghi.'],
                    ['5', 'Nút Hủy', 'Button', 'Đóng hộp, không làm gì.'],
                    ['6', 'Thông báo đang được dùng', 'Toast', '“Tiền tệ đang được sử dụng ở: <tối đa 3 nơi>. Không thể xóa. Hãy chuyển sang trạng thái Khóa.”']],
             'ui_widths': [0.6, 1.8, 1, 3.6],
             'events': [['Bấm biểu tượng thùng rác', 'Click', 'Before:\n– Nút chỉ hiện với quyền Quản lý và tiền tệ chưa được dùng.\nDuring:\n– Hỏi lại máy chủ tiền tệ có đang được dùng không.\nAfter:\n– Chưa dùng → hiện hộp “Xác nhận xóa” kèm tên bản ghi.\n– Đang dùng → báo “Tiền tệ đang được sử dụng ở: … Không thể xóa. Hãy chuyển sang trạng thái Khóa.”, không mở hộp.'],
                        ['Bấm Xóa', 'Click', 'During:\n– Máy chủ chặn nếu tiền tệ đang Khóa: “Tiền tệ đang bị khoá, vui lòng mở khoá trước khi cập nhật.”\n– Máy chủ kiểm tra lại tình trạng sử dụng; đang dùng → báo “Tiền tệ đang được sử dụng ở: … Không thể xóa — hãy chuyển sang trạng thái Khóa.”, không thực hiện After.\nAfter:\n– Xóa hẳn bản ghi, ghi lịch sử Xóa, nạp lại danh sách, báo “Xóa thành công”.'],
                        ['Bấm Hủy', 'Click', 'After:\n– Đóng hộp, không thay đổi.']]},
            {'ten': 'Khóa / Mở khóa tiền tệ', 'uc': 'uc_fr06',
             'qtc': 'Quy tắc Khóa/Mở khóa, Thông báo, Quy định chung về danh mục và Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Khóa / Mở khóa tiền tệ'],
                            ['Mô tả', 'Đổi trạng thái tiền tệ giữa Hoạt động và Khóa. Bản ghi đã Khóa vẫn nằm trong danh mục nhưng không chọn được ở chứng từ mới.'],
                            ['Tác nhân', 'Người có quyền “%s”' % Q_QL],
                            ['Điều kiện ban đầu', 'Bản ghi cần đổi trạng thái đang có trong danh sách. Khóa luôn thực hiện được, kể cả khi tiền tệ đang được dùng.'],
                            ['Dòng sự kiện chính', '1. Người dùng chọn Khóa (hoặc Mở khóa) ở cột Hành động.\n2. Hệ thống hiện hộp “Xác nhận khóa” / “Xác nhận mở khóa” nêu rõ tên bản ghi.\n3. Người dùng xác nhận.\n4. Hệ thống đổi trạng thái, ghi lịch sử, báo “Khóa thành công” / “Mở khóa thành công”.'],
                            ['Dòng sự kiện phụ', '• Bấm Hủy → không thay đổi.\n• Sau khi Khóa, nút Sửa biến mất.\n• Bản ghi đã bị người khác đổi trạng thái → báo “Tiền tệ đang bị khóa” / “Tiền tệ đang hoạt động”.']],
             'menu_them': ' => Khóa / Mở khóa',
             'anh': [('lock', 'Hộp xác nhận khóa tiền tệ'), ('rowmenu', 'Các nút ở cột Hành động')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Mô tả'],
                    ['1', 'Nút ba chấm “Hành động khác”', 'Icon Button', 'Xuất hiện khi dòng có từ 4 nút trở lên; chứa các nút còn lại (Khóa / Mở khóa, Lịch sử).'],
                    ['2', 'Mục Khóa / Mở khóa', 'Button', 'Chỉ hiện với quyền Quản lý. Nhãn đổi theo trạng thái: đang Hoạt động → “Khóa” (biểu tượng ổ khóa), đang Khóa → “Mở khóa”.'],
                    ['3', 'Tiêu đề hộp xác nhận', 'Label', '“Xác nhận khóa” hoặc “Xác nhận mở khóa”.'],
                    ['4', 'Nội dung hộp xác nhận', 'Label', '“Bạn có chắc muốn khóa tiền tệ \'<tên>\'?” / “Bạn có chắc muốn mở khóa tiền tệ \'<tên>\'?”.'],
                    ['5', 'Nút Khóa / Mở khóa', 'Button', 'Xác nhận thực hiện.'],
                    ['6', 'Nút Hủy', 'Button', 'Đóng hộp, không làm gì.'],
                    ['7', 'Cột Trạng thái', 'Badge', 'Hoạt động hoặc Khóa, hai màu khác nhau.']],
             'ui_widths': [0.6, 1.8, 1, 3.6],
             'events': [['Bấm nút ba chấm', 'Click', 'After:\n– Mở menu chứa các nút còn lại của dòng (Khóa / Mở khóa, Lịch sử).'],
                        ['Chọn Khóa / Mở khóa', 'Click', 'After:\n– Hiện hộp “Xác nhận khóa” / “Xác nhận mở khóa” kèm tên bản ghi.'],
                        ['Xác nhận', 'Click', 'During:\n– Bản ghi đã ở trạng thái đích (người khác vừa đổi) → báo “Tiền tệ đang bị khóa” / “Tiền tệ đang hoạt động”, dừng.\nAfter:\n– Đổi trạng thái, KHÔNG xóa dữ liệu, ghi lịch sử trường Trạng thái.\n– Báo “Khóa thành công” / “Mở khóa thành công”, nạp lại danh sách: cột Trạng thái và các nút của dòng đổi theo (Khóa → nút Sửa biến mất).'],
                        ['Bấm Hủy', 'Click', 'After:\n– Đóng hộp, không thay đổi.']]},
            {'ten': 'Xem lịch sử thay đổi',
             'qtc': 'Quy tắc ghi lịch sử và hiển thị lịch sử. Chỉ bổ sung thông tin riêng của Danh mục tiền tệ nếu có.',
             'gioi_thieu': [['Tên chức năng', 'Xem lịch sử thay đổi'],
                            ['Mô tả', 'Liệt kê các lần thay đổi của một tiền tệ, kèm giá trị cũ → mới, người thực hiện và thời điểm.'],
                            ['Tác nhân', 'Người có quyền Quản lý hoặc Xem danh mục tiền tệ'],
                            ['Dòng sự kiện chính', '1. Người dùng chọn Lịch sử ở cột Hành động, hoặc mở cửa sổ Xem tiền tệ.\n2. Hệ thống mở cửa sổ “Lịch sử thay đổi: <mã> - <tên>”, mốc mới nhất ở trên cùng.'],
                            ['Dòng sự kiện phụ', '• Bản ghi chưa từng sửa → chỉ có mốc Tạo mới (bản ghi cũ từ cổng cũ có thể chưa có mốc nào).\n• Có bộ lọc theo loại hành động, người thực hiện, thời gian.\n• Tỷ giá tự cập nhật hằng ngày không ghi vào lịch sử.']],
             'menu_them': ' => Lịch sử',
             'anh': [('history', 'Cửa sổ Lịch sử thay đổi của tiền tệ')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Giá trị ban đầu', 'Mô tả'],
                    ['1', 'Mục Lịch sử', 'Button', 'Hiển thị', 'Ở cột Hành động (hoặc trong nút ba chấm). Mọi người vào được màn hình đều thấy.'],
                    ['2', 'Tiêu đề cửa sổ', 'Label', 'Lịch sử thay đổi: <mã> - <tên>', 'Ghép mã và tên tiền tệ để biết đang xem dòng nào.'],
                    ['3', 'Nút Bộ lọc', 'Button', 'Thu gọn', 'Mở / thu gọn khối lọc. Khối lọc ghim ở đầu, cuộn danh sách vẫn thấy.'],
                    ['4', 'Loại hành động', 'Dropdown', 'Trống — “Tất cả loại hành động”', 'Lọc ngay khi chọn.'],
                    ['5', 'Người thực hiện', 'Dropdown', 'Trống — “Tất cả người thực hiện”', 'Lọc ngay khi chọn.'],
                    ['6', 'Từ ngày / Đến ngày', 'Date', 'Trống', 'dd/mm/yyyy, lọc ngay khi chọn.'],
                    ['7', 'Nút Làm mới (bộ lọc)', 'Button', 'Hiển thị', 'Xóa các tiêu chí lọc.'],
                    ['8', 'Dòng lịch sử', 'Text', 'Theo dữ liệu', 'Mới nhất ở trên cùng. Mỗi dòng: thời điểm dd/mm/yyyy hh:mm; loại hành động (Tạo mới, Thay đổi thông tin, Khóa, Mở khóa…) có màu riêng; “Người thực hiện: <tên> — <phòng ban>”; từng trường đã đổi “Trường: giá trị cũ (đỏ) → giá trị mới (xanh)”.'],
                    ['9', 'Trạng thái rỗng', 'Label', 'Ẩn', '“Chưa có lịch sử thao tác nào.” khi chưa có mốc; “Không có lịch sử phù hợp bộ lọc.” khi lọc không ra.'],
                    ['10', 'Nút Đóng', 'Button', 'Hiển thị', 'Đóng cửa sổ.']],
             'ui_widths': [0.6, 1.4, 0.9, 1.5, 3],
             'events': [['Chọn Lịch sử ở cột Hành động', 'Click', 'After:\n– Mở cửa sổ “Lịch sử thay đổi: <mã> - <tên>” và nạp các mốc thay đổi, mới nhất ở trên cùng.'],
                        ['Bấm Bộ lọc', 'Click', 'After:\n– Mở / thu gọn khối lọc.'],
                        ['Đổi Loại hành động / Người thực hiện / Từ ngày / Đến ngày', 'Change', 'After:\n– Lọc ngay danh sách mốc theo đồng thời các tiêu chí, không cần bấm nút.'],
                        ['Bấm Làm mới (bộ lọc)', 'Click', 'After:\n– Xóa các tiêu chí, hiện lại toàn bộ mốc.'],
                        ['Bấm Đóng / biểu tượng ×', 'Click', 'After:\n– Đóng cửa sổ; danh sách phía sau giữ nguyên bộ lọc và trang.']]},
            {'ten': 'Import file tiền tệ', 'uc': 'uc_fr08',
             'qtc': 'Quy tắc Import file, Validate dữ liệu, Thông báo và Quy định chung về danh mục. Chỉ bổ sung mapping/validation riêng của Danh mục tiền tệ.',
             'gioi_thieu': [['Tên chức năng', 'Import file tiền tệ'],
                            ['Mô tả', 'Thêm nhiều tiền tệ cùng lúc từ file Excel mẫu, có bước Validate trước khi ghi.'],
                            ['Tác nhân', 'Người có quyền “%s”' % Q_QL],
                            ['Điều kiện ban đầu', 'Đang ở màn Danh mục tiền tệ và đã chuẩn bị file theo mẫu.'],
                            ['Dòng sự kiện chính', '1. Bấm Import Excel.\n2. Bấm Tải file mẫu (Mau_import_tien_te.xlsx), điền dữ liệu từ hàng 3 (hàng 1 tiêu đề, hàng 2 mô tả).\n3. Bấm Chọn file Excel rồi Load lên bảng.\n4. Bấm Validate; hệ thống kiểm tra từng dòng như quy tắc Thêm mới (mục 2.3), khóa dòng hợp lệ.\n5. Sửa dòng lỗi rồi Validate lại, hoặc bấm Bỏ dòng lỗi.\n6. Bấm Import; hệ thống ghi các dòng hợp lệ, báo “Import thành công N tiền tệ.”, đóng cửa sổ và nạp lại danh sách.'],
                            ['Dòng sự kiện phụ', '• File không phải .xlsx/.xls → “Vui lòng chọn file .xlsx hoặc .xls”.\n• File không có dòng dữ liệu → “Không có dòng dữ liệu hợp lệ.”\n• Quá 500 dòng → “File có X dòng dữ liệu, vượt quá giới hạn 500 dòng mỗi lần import. Vui lòng tách file và import nhiều lần.”\n• Còn dòng lỗi → nút Import không bấm được.\n• Có dòng ghi thất bại lúc Import → báo “Import thành công a/b tiền tệ. c dòng thất bại.”'],
                            ['Yêu cầu đặc biệt', 'Validate không ghi dữ liệu. Mã tự IN HOA. Trạng thái theo cột Trạng thái (để trống = Hoạt động). Người tạo là người thực hiện; lịch sử có mốc Tạo mới.']],
             'menu_them': ' => Import Excel {icon:btn_import}',
             'ghi_chu_layout': 'Cửa sổ Import được mở ngay trên màn hình danh sách.',
             'anh': [('import_open', 'Cửa sổ Import tiền tệ khi vừa mở'), ('import_loaded', 'Dữ liệu đã được load lên bảng xem trước'),
                     ('import_validated', 'Kết quả Validate — mỗi dòng lỗi nêu rõ lý do')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Bắt buộc', 'Giá trị ban đầu', 'Mô tả'],
                    ['1', 'Nút Import Excel', 'Button', 'Enable', '–', 'Hiển thị', 'Trên thanh công cụ của bảng, chỉ hiện với quyền Quản lý. Mở cửa sổ “Import tiền tệ” (dòng phụ “Import từ Excel • Validate xong dòng hợp lệ sẽ bị khoá”).'],
                    ['2', 'Nút Chọn file Excel', 'Button', 'Enable', 'Có', 'Chưa chọn file', 'Chọn file .xlsx / .xls từ máy; tên file hiện ngay cạnh nút.'],
                    ['3', 'Nút Tải file mẫu', 'Button', 'Enable', '–', 'Hiển thị', 'Tải Mau_import_tien_te.xlsx: STT, Mã tiền tệ *, Tên tiền tệ *, Tên gọi khác, Tỷ giá (VNĐ) *, Trạng thái (ô chọn Hoạt động / Khóa). Hàng 1 tiêu đề, hàng 2 mô tả, dữ liệu từ hàng 3.'],
                    ['4', 'Nút Load lên bảng', 'Button', 'Enable / Disable', '–', 'Mờ khi chưa chọn file', 'Đọc file và đổ dữ liệu lên bảng xem trước.'],
                    ['5', 'Nút Validate', 'Button', 'Enable / Disable', '–', 'Mờ khi bảng chưa có dòng', 'Kiểm tra từng dòng; dòng hợp lệ bị khóa không sửa được.'],
                    ['6', 'Nút Import', 'Button', 'Enable / Disable', '–', 'Mờ', 'Chỉ bấm được khi đã Validate, KHÔNG còn dòng lỗi và có ít nhất 1 dòng hợp lệ.'],
                    ['7', 'Ô Tổng / Hợp lệ / Lỗi', 'Label', 'Read-only', '–', 'Tổng: 0', 'Sau Load hiện Tổng; sau Validate hiện thêm Hợp lệ và Lỗi. Có dòng vừa sửa thì hiện “Có dòng đã sửa (cần validate lại)”.'],
                    ['8', 'Bảng xem trước', 'Table/Grid', 'Enable', '–', 'Ẩn đến khi Load', 'Tiêu đề “Preview (chỉ sửa dòng lỗi)”, các cột như file mẫu. Chỉ sửa trực tiếp được ở dòng lỗi.'],
                    ['9', 'Thông báo lỗi theo dòng', 'Label', 'Hiển thị', '–', 'Ẩn', 'Dòng lỗi viền đỏ, danh sách lý do ghi ngay dưới dòng (xem bảng quy tắc bên dưới).'],
                    ['10', 'Nút Bỏ dòng lỗi', 'Button', 'Enable', '–', 'Hiển thị', 'Loại toàn bộ dòng đang lỗi khỏi bảng xem trước.'],
                    ['11', 'Nút Xoá trạng thái validate', 'Button', 'Enable', '–', 'Hiển thị', 'Bỏ khóa các dòng hợp lệ và bỏ thông báo lỗi để sửa lại.'],
                    ['12', 'Nút Làm mới', 'Button', 'Enable', '–', 'Hiển thị', 'Ở chân cửa sổ. Xóa file đã chọn và toàn bộ bảng xem trước.'],
                    ['13', 'Nút Đóng', 'Button', 'Enable', '–', 'Hiển thị', 'Đóng cửa sổ, không ghi gì.']],
             'ui_widths': [0.5, 1.3, 0.8, 0.8, 0.5, 1.1, 2.6],
             'events': [['Bấm Import Excel', 'Click', 'After:\n– Mở cửa sổ “Import tiền tệ” ở trạng thái rỗng.'],
                        ['Bấm Tải file mẫu', 'Click', 'After:\n– Tải Mau_import_tien_te.xlsx đúng khuôn file mẫu chung (cột bắt buộc có dấu *; cột Trạng thái có ô chọn).'],
                        ['Chọn file / Bấm Load lên bảng', 'Click', 'During:\n– File không phải .xlsx/.xls → “Vui lòng chọn file .xlsx hoặc .xls”.\n– File không có dòng dữ liệu → “Không có dòng dữ liệu hợp lệ.”\nAfter:\n– Đổ dữ liệu lên bảng xem trước, cập nhật ô Tổng.'],
                        ['Bấm Validate', 'Click', 'During:\n– Quá 500 dòng → “File có X dòng dữ liệu, vượt quá giới hạn 500 dòng mỗi lần import. Vui lòng tách file và import nhiều lần.”\n– Máy chủ kiểm tra từng dòng theo quy tắc Thêm mới (mục 2.3) và bảng quy tắc riêng bên dưới, gồm trùng trong file và trùng hệ thống.\nAfter:\n– Dòng lỗi viền đỏ kèm lý do, dòng hợp lệ bị khóa; hiện số Hợp lệ / Lỗi và báo “Validate thành công” hoặc “Validate xong: a hợp lệ, b không hợp lệ”.\n– KHÔNG ghi bản ghi nào ở bước này.'],
                        ['Sửa ô ở dòng lỗi', 'Input', 'After:\n– Dòng được đánh dấu đã sửa, hiện “Có dòng đã sửa (cần validate lại)”; nút Import khóa đến khi Validate lại.'],
                        ['Bấm Bỏ dòng lỗi / Xoá trạng thái validate', 'Click', 'After:\n– Bỏ dòng lỗi: loại các dòng lỗi khỏi bảng.\n– Xoá trạng thái validate: mở khóa mọi dòng, xóa thông báo lỗi.'],
                        ['Bấm Import', 'Click', 'During:\n– Máy chủ kiểm tra lại toàn bộ dòng gửi lên, chỉ ghi dòng hợp lệ; không còn dòng hợp lệ → “Không có dòng nào hợp lệ để import”.\nAfter:\n– Ghi tiền tệ mới: Mã IN HOA, Trạng thái theo cột Trạng thái (trống = Hoạt động), người tạo là người thực hiện, lịch sử có mốc Tạo mới.\n– Báo “Import thành công N tiền tệ.” (có dòng hỏng lúc ghi → “Import thành công a/b tiền tệ. c dòng thất bại.”), đóng cửa sổ, nạp lại danh sách.'],
                        ['Bấm Làm mới / Đóng', 'Click', 'After:\n– Làm mới: xóa file và bảng xem trước, giữ cửa sổ.\n– Đóng: đóng cửa sổ, không ghi gì.']],
             'bang_them': [('Quy tắc kiểm tra riêng của file Import', [['Cột', 'Quy tắc / thông báo lỗi'],
                            ['Mã tiền tệ *', 'Bắt buộc (“Mã tiền tệ không được để trống”), tối đa 255 ký tự, chỉ chữ không dấu/số/-/_ (“Mã tiền tệ: Chỉ gồm chữ không dấu, số, dấu - và _”), không trùng trong file (“Mã tiền tệ bị trùng với dòng N trong file”), không trùng hệ thống (“Mã tiền tệ đã tồn tại trong hệ thống”). Tự IN HOA.'],
                            ['Tên tiền tệ *', 'Bắt buộc, tối đa 255 ký tự, không trùng trong file (“Tên tiền tệ bị trùng với dòng N trong file”), không trùng hệ thống (“Tên tiền tệ đã tồn tại trong hệ thống”).'],
                            ['Tên gọi khác', 'Tối đa 255 ký tự.'],
                            ['Tỷ giá (VNĐ) *', 'Bắt buộc (“Tỷ giá không được để trống”); phải là số lớn hơn 0, dấu phẩy ngăn nghìn (“Tỷ giá không hợp lệ”); tối đa 999,999.99 như khi nhập tay.'],
                            ['Trạng thái', 'Chọn Hoạt động / Khóa; để trống = Hoạt động; giá trị khác báo “Trạng thái chỉ nhận "Hoạt động" hoặc "Khóa"”.']], [1.2, 4])]},
            {'ten': 'Xuất danh sách ra Excel', 'uc': 'uc_fr09',
             'qtc': 'Quy tắc Excel và Cấu hình cột. Chỉ bổ sung danh sách trường được phép xuất riêng của Danh mục tiền tệ.',
             'gioi_thieu': [['Tên chức năng', 'Xuất danh sách tiền tệ ra Excel'],
                            ['Mô tả', 'Xuất kết quả đang lọc ra file Excel, cho phép chọn trường và thứ tự cột.'],
                            ['Tác nhân', 'Người có quyền Quản lý hoặc Xem danh mục tiền tệ'],
                            ['Dòng sự kiện chính', '1. Bấm Xuất Excel.\n2. Hệ thống mở cửa sổ “Chọn trường xuất file”, tích sẵn đúng các cột đang hiển thị trên bảng.\n3. Người dùng tích chọn và kéo ☰ để sắp thứ tự.\n4. Bấm Xuất file; hệ thống tải danh_muc_tien_te.xlsx theo đúng bộ lọc và thứ tự trường, báo “Xuất Excel thành công”.'],
                            ['Dòng sự kiện phụ', '• Bỏ chọn hết trường → nút Xuất file không bấm được.\n• Bấm Đóng → không xuất gì.\n• Lỗi khi xuất → báo “Lỗi khi xuất Excel”.'],
                            ['Yêu cầu đặc biệt', 'File chứa toàn bộ kết quả lọc (tối đa 10,000 dòng), có cột STT ở đầu và tiêu đề “Danh mục tiền tệ”. Cột Tỷ giá (VNĐ) là ô số.']],
             'menu_them': ' => Xuất Excel {icon:btn_xuatexcel}',
             'anh': [('export', 'Cửa sổ Chọn trường xuất file')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
                    ['1', 'Nút Xuất Excel', 'Button', 'Enable', 'Hiển thị', 'Trên thanh công cụ của bảng, hiện với cả quyền Xem. Mở cửa sổ “Chọn trường xuất file”.'],
                    ['2', 'Dòng hướng dẫn', 'Label', 'Hiển thị', '–', '“Tích chọn trường cần xuất, kéo ☰ để đổi thứ tự cột trong file.”'],
                    ['3', 'Danh sách trường', 'Checkbox chọn nhiều', 'Enable', 'Tích sẵn cột đang hiển thị (mặc định: Mã tiền tệ, Tên tiền tệ, Tỷ giá (VNĐ), Người tạo, Ngày tạo, Trạng thái)', 'Chín trường: Mã tiền tệ, Tên tiền tệ, Tên gọi khác, Tỷ giá (VNĐ), Trạng thái, Người tạo, Ngày tạo, Người cập nhật, Ngày cập nhật. Kéo ☰ đổi thứ tự.'],
                    ['4', 'Nút Chọn tất cả / Bỏ chọn hết', 'Button', 'Enable', 'Hiển thị', 'Tích / bỏ tích toàn bộ.'],
                    ['5', 'Dòng đếm', 'Label', 'Read-only', 'Đang chọn a/9 trường', 'Cập nhật theo số trường đang tích.'],
                    ['6', 'Nút Xuất file', 'Button', 'Enable / Disable', 'Mờ khi chưa chọn trường', 'Sinh file danh_muc_tien_te.xlsx và tải về.'],
                    ['7', 'Nút Đóng', 'Button', 'Enable', 'Hiển thị', 'Đóng cửa sổ, không xuất.']],
             'ui_widths': [0.6, 1.5, 1, 0.8, 1.4, 2.4],
             'events': [['Bấm Xuất Excel', 'Click', 'After:\n– Mở cửa sổ “Chọn trường xuất file”, tích sẵn đúng các cột đang hiển thị trên bảng.'],
                        ['Tích / bỏ tích, kéo ☰', 'Change', 'During:\n– Thứ tự trường trong cửa sổ quyết định thứ tự cột trong file.\n– Bỏ chọn hết → nút Xuất file mờ đi.'],
                        ['Bấm Chọn tất cả / Bỏ chọn hết', 'Click', 'After:\n– Tích / bỏ tích toàn bộ chín trường.'],
                        ['Bấm Xuất file', 'Click', 'During:\n– Sinh file theo ĐÚNG bộ lọc và thứ tự sắp xếp đang áp dụng, lấy toàn bộ kết quả (tối đa 10,000 dòng), cột STT ở đầu, tiêu đề “Danh mục tiền tệ”.\nAfter:\n– Đóng cửa sổ, tải danh_muc_tien_te.xlsx về máy, báo “Xuất Excel thành công”.\n– Lỗi → báo “Lỗi khi xuất Excel”.'],
                        ['Bấm Đóng / biểu tượng ×', 'Click', 'After:\n– Đóng cửa sổ, không xuất gì.']]},
            {'ten': 'Xem chi tiết tiền tệ', 'uc': 'uc_fr10',
             'qtc': 'Màn Xem chi tiết và Phân quyền.',
             'gioi_thieu': [['Tên chức năng', 'Xem chi tiết tiền tệ'],
                            ['Mô tả', 'Cửa sổ “Xem tiền tệ” hiển thị Mã, Trạng thái, Tên, Tên gọi khác, Tỷ giá (VNĐ) ở chế độ chỉ đọc, kèm khối Lịch sử.'],
                            ['Tác nhân', 'Người có quyền Quản lý hoặc Xem danh mục tiền tệ'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm mã tiền tệ ở danh sách.\n2. Hệ thống mở cửa sổ Xem, chỉ có nút Đóng.'],
                            ['Dòng sự kiện phụ', '• Bản ghi vừa bị xóa → báo “Dữ liệu đã thay đổi, vui lòng tải lại”, không mở cửa sổ.']],
             'anh': [('detail', 'Cửa sổ Xem tiền tệ ở chế độ chỉ đọc')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
                    ['1', 'Mã tiền tệ (ở danh sách)', 'Link', 'Enable', 'Hiển thị', 'Bấm vào mã ở cột Mã tiền tệ để mở cửa sổ Xem. Màn không có nút “Xem” riêng ở cột Hành động.'],
                    ['2', 'Tiêu đề cửa sổ', 'Label', 'Hiển thị', 'Xem tiền tệ', 'Cửa sổ khổ rộng, mở ngay trên màn danh sách.'],
                    ['3', 'Mã tiền tệ', 'Textbox', 'Read-only', 'Dữ liệu hiện tại', 'Không gõ được.'],
                    ['4', 'Trạng thái', 'Dropdown', 'Read-only', 'Dữ liệu hiện tại', 'Hoạt động hoặc Khóa, không chọn được.'],
                    ['5', 'Tên tiền tệ', 'Textbox', 'Read-only', 'Dữ liệu hiện tại', 'Không gõ được.'],
                    ['6', 'Tên gọi khác', 'Textbox', 'Read-only', 'Dữ liệu hiện tại', 'Không gõ được.'],
                    ['7', 'Tỷ giá (VNĐ)', 'Textbox', 'Read-only', 'Dữ liệu hiện tại, dạng 26,520.00', 'Không gõ được.'],
                    ['8', 'Khối Lịch sử', 'Section', 'Enable', 'Thu gọn', 'Nằm cuối cửa sổ. Bấm “Xem lịch sử” để mở (lần đầu mới nạp dữ liệu), “Thu gọn” để đóng, “Làm mới” để nạp lại. Nội dung và bộ lọc giống cửa sổ Lịch sử thay đổi (mục 2.7).'],
                    ['9', 'Nút Đóng', 'Button', 'Enable', 'Hiển thị', 'Nút duy nhất ở chân cửa sổ (không có Lưu, không có Sửa).']],
             'ui_widths': [0.6, 1.4, 0.8, 0.8, 1.3, 3],
             'events': [['Bấm mã tiền tệ ở danh sách', 'Click', 'During:\n– Nạp dữ liệu mới nhất của bản ghi.\n– Bản ghi vừa bị xóa → báo “Dữ liệu đã thay đổi, vui lòng tải lại”, không mở cửa sổ.\nAfter:\n– Mở cửa sổ “Xem tiền tệ”, mọi trường chỉ đọc. Người chỉ có quyền Xem và tiền tệ đang Khóa vẫn xem được.'],
                        ['Bấm Xem lịch sử / Thu gọn', 'Click', 'After:\n– Mở / đóng khối Lịch sử; lần mở đầu tiên mới nạp dữ liệu lịch sử.'],
                        ['Bấm Làm mới (khối Lịch sử)', 'Click', 'After:\n– Nạp lại danh sách mốc lịch sử.'],
                        ['Bấm Đóng / biểu tượng ×', 'Click', 'After:\n– Đóng cửa sổ, không hỏi xác nhận (không có gì để lưu).']]},
            {'ten': 'Tùy chỉnh cột hiển thị',
             'qtc': 'Tùy chỉnh cột.',
             'gioi_thieu': [['Tên chức năng', 'Tùy chỉnh cột hiển thị'],
                            ['Mô tả', 'Bật/tắt và sắp xếp thứ tự cột của bảng; cấu hình lưu riêng theo người dùng.'],
                            ['Yêu cầu đặc biệt', 'Cột STT, Mã tiền tệ, Tên tiền tệ, Hành động bị khóa. Mặc định ẩn: Tên gọi khác, Người cập nhật, Ngày cập nhật.']],
             'menu_them': ' => Cấu hình cột {icon:btn_cauhinhcot}',
             'anh': [('colcfg', 'Cửa sổ Tuỳ chỉnh cột')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
                    ['1', 'Biểu tượng Cấu hình cột hiển thị', 'Icon Button', 'Enable', 'Hiển thị', 'Cuối thanh công cụ của bảng, rê chuột hiện “Cấu hình cột hiển thị”. Mọi người vào được màn hình đều dùng được.'],
                    ['2', 'Tiêu đề cửa sổ', 'Label', 'Hiển thị', 'Tuỳ chỉnh cột', '–'],
                    ['3', 'Danh sách cột', 'Checkbox chọn nhiều', 'Enable', 'Theo cấu hình đã lưu của người dùng; chưa lưu thì ẩn Tên gọi khác, Người cập nhật, Ngày cập nhật', 'Đủ 11 cột: STT, Mã tiền tệ, Tên tiền tệ, Tỷ giá (VNĐ), Tên gọi khác, Người cập nhật, Ngày cập nhật, Người tạo, Ngày tạo, Trạng thái, Hành động. Kéo ☰ để đổi thứ tự.'],
                    ['4', 'Cột bắt buộc', 'Checkbox', 'Disable', 'Luôn tích', 'STT, Mã tiền tệ, Tên tiền tệ, Hành động: xám, có biểu tượng ổ khóa (“Cột bắt buộc — không thể ẩn hoặc đổi vị trí”), không bỏ tích và không kéo được.'],
                    ['5', 'Nút Lưu', 'Button', 'Enable', 'Hiển thị', 'Áp dụng ngay lên bảng và lưu cấu hình theo tài khoản người dùng (đăng nhập máy khác vẫn giữ).'],
                    ['6', 'Nút Đóng', 'Button', 'Enable', 'Hiển thị', 'Đóng, bỏ các thay đổi chưa lưu.']],
             'ui_widths': [0.6, 1.5, 1, 0.8, 1.5, 2.6],
             'events': [['Bấm biểu tượng Cấu hình cột hiển thị', 'Click', 'After:\n– Mở cửa sổ “Tuỳ chỉnh cột” với cấu hình cột đang áp dụng.'],
                        ['Tích / bỏ tích, kéo ☰', 'Change', 'During:\n– Cột bắt buộc không bỏ tích, không kéo được; các cột khác đổi được thứ tự.'],
                        ['Bấm Lưu', 'Click', 'After:\n– Bảng đổi ngay theo cột và thứ tự đã chọn, lưu cấu hình theo người dùng, báo “Cập nhật thành công”, đóng cửa sổ.\n– Lưu lỗi → báo “Thao tác thất bại”.\n– Cửa sổ Chọn trường xuất file lần sau tích sẵn đúng các cột đang hiển thị này.'],
                        ['Bấm Đóng / biểu tượng ×', 'Click', 'After:\n– Đóng cửa sổ, trả danh sách cột về cấu hình đang áp dụng, bảng không đổi.']]},
        ],
        'quy_tac': [
            ('BR-01', 'Ràng buộc mã tiền tệ',
             ['Mã tiền tệ không được trùng trong danh mục, không phân biệt chữ hoa / chữ thường.',
              'Mã chỉ gồm chữ không dấu, số, dấu - và _; tự bỏ khoảng trắng hai đầu và lưu ở dạng CHỮ IN HOA.',
              'Thông báo khi trùng: “Mã tiền tệ đã tồn tại”.'],
             ['Thêm mới tiền tệ', 'Chỉnh sửa tiền tệ', 'Import file tiền tệ']),
            ('BR-02', 'Ràng buộc trùng tên',
             ['Tên tiền tệ không được trùng trong danh mục.',
              'Thông báo khi trùng: “Tên tiền tệ đã tồn tại”.',
              'Tên gọi khác được phép trùng.'],
             ['Thêm mới tiền tệ', 'Chỉnh sửa tiền tệ', 'Import file tiền tệ']),
            ('BR-03', 'Giới hạn tỷ giá',
             ['Tỷ giá (VNĐ) phải lớn hơn 0 và không vượt 999,999.99.',
              'Nhập và hiển thị theo chuẩn quốc tế: dấu phẩy ngăn cách hàng nghìn, dấu chấm phần thập phân, luôn 2 chữ số thập phân.'],
             ['Thêm mới tiền tệ', 'Chỉnh sửa tiền tệ', 'Import file tiền tệ']),
            ('BR-04', 'Điều kiện xóa tiền tệ',
             ['Chỉ xóa được tiền tệ chưa được dùng ở bất kỳ nghiệp vụ nào (báo giá, hợp đồng, hóa đơn, tờ khai hải quan, công nợ, chi tiết tài khoản…).',
              'Tiền tệ đang được dùng thì ẩn nút Xóa; máy chủ kiểm tra lại lúc xóa và báo: “Tiền tệ đang được sử dụng ở: … Không thể xóa — hãy chuyển sang trạng thái Khóa.”',
              'Tiền tệ đang Khóa không xóa được (máy chủ chặn), phải Mở khóa trước.'],
             ['Xóa tiền tệ']),
            ('BR-05', 'Tiền tệ đang Khóa',
             ['Khóa luôn thực hiện được, không kiểm tra ràng buộc sử dụng.',
              'Tiền tệ đang Khóa không sửa được (máy chủ chặn), phải Mở khóa trước: “Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.”',
              'Không còn chọn được ở chứng từ mới; chứng từ cũ vẫn hiển thị đúng tiền tệ đó kèm 🔒.'],
             ['Khóa / Mở khóa tiền tệ', 'Chỉnh sửa tiền tệ', 'Xóa tiền tệ', 'Các màn chọn tiền tệ. VD: Báo giá, Hợp đồng']),
            ('BR-06', 'Tự động cập nhật tỷ giá',
             ['Tỷ giá tự cập nhật lúc 03:00 hằng ngày theo tỷ giá bán của Vietcombank, khớp theo Mã tiền tệ.',
              'Bỏ qua mã VNĐ / VND; tỷ giá nhận về không nằm trong khoảng lớn hơn 0 đến 999,999.99 thì giữ nguyên tỷ giá cũ.'],
             ['Xem danh sách tiền tệ', 'Xem chi tiết tiền tệ']),
            ('BR-07', 'Giới hạn Import',
             ['Mỗi lần nhập tối đa 500 dòng dữ liệu.',
              'Bước Validate chỉ kiểm tra, không ghi dữ liệu; chỉ các dòng hợp lệ được nhập.',
              'Trạng thái theo cột Trạng thái (“Hoạt động” hoặc “Khóa”); bỏ trống = Hoạt động.'],
             ['Import file tiền tệ']),
            ('BR-08', 'Ghi lịch sử thay đổi',
             ['Mọi thao tác Tạo mới, Thay đổi thông tin, Khóa, Mở khóa, Xóa đều ghi lịch sử kèm người thực hiện.'],
             ['Thêm mới tiền tệ', 'Chỉnh sửa tiền tệ', 'Xóa tiền tệ', 'Khóa / Mở khóa tiền tệ', 'Xem lịch sử thay đổi']),
            ('BR-09', 'Phạm vi dữ liệu',
             ['Danh mục dùng chung với cổng cũ, không phân quyền theo công ty / phòng ban.',
              'Quyền “Xem danh mục tiền tệ” chỉ xem, tìm kiếm, xuất Excel; quyền “Quản lý danh mục tiền tệ” được thêm, sửa, xóa, khóa / mở khóa, import.'],
             ['Tất cả chức năng']),
        ],
    },

    'loi_code': [
        'Quyền trùng lặp: PermissionsTableSeeder khai 2 lần “Quản lý danh mục tiền tệ” (id 1115 và 1117) và “Xem danh mục tiền tệ” (id 1116 và 1118); DB local cũng có đủ 4 dòng → màn phân quyền hiện 2 ô trùng tên, gán nhầm id kia là mất quyền.',
        'Import đánh số dòng lệch: thông báo “… bị trùng với dòng N trong file” lấy N = thứ tự dòng dữ liệu + 1, nhưng file mẫu có thêm hàng mô tả nên dữ liệu bắt đầu từ hàng 3 → N nhỏ hơn số hàng Excel thật 1 đơn vị, và cũng lệch 1 so với cột # trên bảng xem trước (CurrencyService::validateRows dùng $index + 2).',
        'Import không kiểm trần Tỷ giá 999,999.99: validateRows chỉ kiểm “là số > 0”, dòng có tỷ giá 1,000,000 qua được Validate rồi hỏng lúc ghi (cột double(8,2)) → báo “Import thành công a/b tiền tệ. c dòng thất bại.” thay vì báo đỏ ở bước Validate.',
        'Tiền tệ có sẵn mã “VNĐ” (id 1, dữ liệu từ cổng cũ) chứa ký tự Đ → mở Sửa rồi bấm Lưu luôn bị chặn “Chỉ gồm chữ không dấu, số, dấu - và _” (cả FE rule code_chars lẫn BE CodeChars) → không sửa được tỷ giá/tên của VNĐ, kể cả không đổi mã.',
        'Nút Xóa vẫn hiện với tiền tệ đang Khóa (điều kiện chỉ xét quyền + chưa được dùng); bấm Xóa thì máy chủ trả “Tiền tệ đang bị khoá, vui lòng mở khoá trước khi cập nhật.” — trái quy tắc “bản ghi đã khóa thì ẩn nút Xóa”.',
        'Ô Tên tiền tệ có placeholder “VD: USD” trùng placeholder ô Mã tiền tệ (file mẫu Import thì ghi “VD: Đô la Mỹ”) → dễ gây hiểu nhầm, và làm công cụ chụp ảnh tìm ô Mã theo placeholder dễ bắt nhầm.',
        '(Cần kiểm) File Excel xuất ra: cột Tỷ giá được đổ dạng chuỗi số thô (30792.68, 1) qua blade dùng chung, không gắn định dạng #,##0.00 → có thể không có dấu ngăn nghìn/không đủ 2 số lẻ, hoặc bị Excel coi là text.',
    ],
}

# ---- Sửa tab testcase "2. DM tiền tệ" (đọc từ ref/testcase_tab.txt) ----
_PRE = 'Đăng nhập TK "Quản lý". Đang ở màn hình Danh mục tiền tệ.'
CFG['tc'] = {
    'tab': '2. DM tiền tệ',
    'hdr_row': 144,            # "X. LUỒNG XUYÊN SUỐT"
    'blocks': [
        # Quy tắc mã mới — chèn cuối nhóm VIII. RÀNG BUỘC NHẬP LIỆU (TC_08.001 hàng 117 … TC_08.018 hàng 134)
        {'after': 134, 'merge_from': 117, 'cases': [
            ('TC_08.019', 'Mã tiền tệ có ký tự không hợp lệ', 'P1', _PRE,
             '1. Bấm Tạo mới\n2. Lần lượt nhập Mã tiền tệ = "VNĐ2", "US D", "USD/1"\n3. Quan sát ô Mã tiền tệ, bấm Lưu',
             'Mã: VNĐ2; US D; USD/1',
             '- Ô Mã tiền tệ báo đỏ "Chỉ gồm chữ không dấu, số, dấu - và _" ngay khi gõ\n- Bấm Lưu: không lưu, báo "Bạn chưa nhập đầy đủ thông tin"'),
            ('TC_08.020', 'Mã tiền tệ có dấu - và _ vẫn hợp lệ', 'P2', _PRE,
             '1. Bấm Tạo mới\n2. Nhập Mã = "USD-2", Tên, Tỷ giá\n3. Bấm Lưu',
             'Mã: USD-2; Tên: DOC-Đô la thử; Tỷ giá: 100',
             '- Lưu thành công, báo "Thêm mới thành công"\n- Danh sách hiện mã USD-2'),
            ('TC_08.021', 'Mã chữ thường tự chuyển sang IN HOA khi lưu', 'P1', _PRE,
             '1. Bấm Tạo mới\n2. Nhập Mã = "sgd", Tên, Tỷ giá\n3. Bấm Lưu và xem danh sách',
             'Mã: sgd; Tên: DOC-Đô la Singapore; Tỷ giá: 19,850.50',
             '- Lưu thành công\n- Danh sách hiện mã SGD (chữ in hoa)'),
            ('TC_08.022', 'Trùng mã khác kiểu chữ hoa/thường', 'P1', 'Đăng nhập TK "Quản lý". Đã có sẵn mã USD.',
             '1. Bấm Tạo mới\n2. Nhập Mã = "usd", Tên mới, Tỷ giá\n3. Bấm Lưu',
             'Mã: usd; Tên: DOC-Trùng mã; Tỷ giá: 1',
             '- Ô Mã tiền tệ báo "Mã tiền tệ đã tồn tại", không lưu\n- Danh sách không có thêm bản ghi'),
        ]},
        # Nhóm IMPORT mới — tab chưa có; chèn sau case cuối TC_10.004 (hàng 148)
        {'after': 148, 'groups': [('XI', 'IMPORT TỪ FILE EXCEL (bổ sung 25/09/2026)', 11, 'import')]},
    ],
    'import_rows_dung': 'File mẫu điền 3 tiền tệ hợp lệ ở trạng thái Hoạt động (SGD / DOC-Đô la Singapore / 19,850.50; THB / DOC-Baht Thái / 715.20; MYR / DOC-Ringgit Malaysia / 5,610), chưa có trong danh mục',
    'import_loi_data': {
        'Mã tiền tệ không được để trống': 'Mã tiền tệ: (để trống); Tên tiền tệ: DOC-Thiếu mã; Tỷ giá: 100',
        'Mã tiền tệ tối đa 255 ký tự': 'Mã tiền tệ: chuỗi 256 chữ cái',
        'Mã tiền tệ: Chỉ gồm chữ không dấu, số, dấu - và _': 'Mã tiền tệ: VNĐ-2',
        'Mã tiền tệ bị trùng với dòng N trong file': 'Dòng dữ liệu thứ 1 và thứ 5 cùng mã SGD',
        'Mã tiền tệ đã tồn tại trong hệ thống': 'Mã tiền tệ: USD',
        'Tên tiền tệ không được để trống': 'Tên tiền tệ: (để trống)',
        'Tên tiền tệ tối đa 255 ký tự': 'Tên tiền tệ: chuỗi 256 ký tự',
        'Tên tiền tệ bị trùng với dòng N trong file': 'Hai dòng cùng tên “DOC-Baht Thái”',
        'Tên tiền tệ đã tồn tại trong hệ thống': 'Tên tiền tệ: EURO',
        'Tên gọi khác tối đa 255 ký tự': 'Tên gọi khác: chuỗi 256 ký tự',
        'Tỷ giá không được để trống': 'Tỷ giá (VNĐ): (để trống)',
        'Tỷ giá không hợp lệ': 'Tỷ giá (VNĐ): abc; 0; -5',
        'Trạng thái chỉ nhận "Hoạt động" hoặc "Khóa"': 'Trạng thái: Tạm dừng (dán đè vào ô)',
    },
    'import_extra': [
        ('Mã chữ thường trong file tự chuyển IN HOA', 'P1', 'Đã Load file có dòng mã viết thường.',
         '1. Bấm Validate\n2. Bấm Import\n3. Tìm lại tiền tệ vừa nhập', 'Mã tiền tệ: thb',
         '- Dòng hợp lệ, import thành công\n- Danh sách hiện mã THB'),
        ('Import tiền tệ ở trạng thái Khóa', 'P2', 'Đã Load file có dòng Trạng thái = Khóa.',
         '1. Bấm Validate → Import\n2. Xem cột Trạng thái của bản ghi mới', 'Trạng thái: Khóa',
         '- Bản ghi mới ở trạng thái Khóa\n- Dòng để trống Trạng thái thì ở trạng thái Hoạt động'),
        ('Tỷ giá vượt trần 999,999.99', 'P2', 'Đã Load file có dòng tỷ giá quá trần.',
         '1. Bấm Validate', 'Tỷ giá (VNĐ): 1,000,000',
         '- Dòng đó bị báo lỗi ngay ở bước Validate, không cho Import (cùng trần 999,999.99 như khi nhập tay)'),
    ],
    'edits': [
        ('B7', 'Không cộng dồn. Mỗi tiền tệ là một dòng độc lập.\n Quy tắc chống trùng: cả Mã tiền tệ và Tên tiền tệ đều là duy nhất trong danh mục. Trùng mã báo "Mã tiền tệ đã tồn tại" ngay dưới ô Mã tiền tệ; trùng tên báo "Tên tiền tệ đã tồn tại" ngay dưới ô Tên tiền tệ.\n Mã tiền tệ chỉ gồm chữ không dấu, số, dấu - và _; hệ thống tự bỏ khoảng trắng hai đầu và lưu ở dạng CHỮ IN HOA, nên "usd" bị coi là trùng với "USD".\n Tên gọi khác KHÔNG bắt buộc duy nhất  được phép trùng.'),
        ('I129', '- Báo "Vui lòng nhập tối đa 255 ký tự." ngay dưới ô Mã tiền tệ, không lưu'),
        ('G134', '1. Bấm Tạo mới\n2. Nhập Mã = " ABC " (có khoảng trắng hai đầu)\n3. Quan sát ô Mã tiền tệ rồi bấm Lưu\n4. Xoá hai khoảng trắng, bấm Lưu lại'),
        ('I134', '- Bước 3: ô Mã tiền tệ báo đỏ "Chỉ gồm chữ không dấu, số, dấu - và _" (khoảng trắng không phải ký tự hợp lệ), không lưu\n- Bước 4: lưu được, danh sách hiện mã ABC\n- Không tạo được 2 tiền tệ mà mắt thường nhìn thấy mã giống hệt nhau'),
        ('G108', '1. Không lọc gì\n2. Bấm nút Xuất Excel\n3. Trong cửa sổ "Chọn trường xuất file", giữ nguyên các trường đã tích, bấm Xuất file\n4. Mở file tải về'),
        ('I108', '- Hiện thông báo "Xuất Excel thành công"\n- Tải về file danh_muc_tien_te.xlsx, mở được bằng Excel\n- File có tiêu đề "Danh mục tiền tệ", số dòng dữ liệu bằng tổng số tiền tệ ghi ở cuối bảng'),
        ('G109', '1. Bấm Xuất Excel\n2. Đọc danh sách trường trong cửa sổ "Chọn trường xuất file"\n3. Bấm Xuất file, đối chiếu tiêu đề cột trong file với bảng trên màn hình'),
        ('I109', '- Cửa sổ có đủ 9 trường: Mã tiền tệ, Tên tiền tệ, Tên gọi khác, Tỷ giá (VNĐ), Trạng thái, Người tạo, Ngày tạo, Người cập nhật, Ngày cập nhật\n- Tích sẵn đúng các cột đang hiển thị trên bảng (mặc định: Mã tiền tệ, Tên tiền tệ, Tỷ giá (VNĐ), Người tạo, Ngày tạo, Trạng thái); dòng cuối ghi "Đang chọn a/b trường"\n- File có cột STT đầu tiên, tiếp theo đúng các trường đã tích theo thứ tự trong cửa sổ, tiêu đề cột bằng tiếng Việt'),
        ('G110', '1. Lọc Trạng thái = Khóa\n2. Bấm Xuất Excel → Xuất file\n3. Mở file'),
        ('I110', '- File chỉ chứa đúng các tiền tệ đang Khóa\n- Số dòng bằng tổng số bản ghi ở cuối bảng'),
        ('G111', '1. Gõ "USD" vào ô tìm nhanh và bấm Tìm kiếm\n2. Bấm Xuất Excel → Xuất file\n3. Mở file'),
        ('I111', '- File chỉ chứa các dòng khớp từ khóa (theo mã, tên hoặc tên gọi khác), giống danh sách đang lọc'),
        ('G112', '1. Đứng ở trang 1\n2. Bấm Xuất Excel → Xuất file\n3. Đếm số dòng trong file'),
        ('I112', '- File chứa TOÀN BỘ tiền tệ khớp bộ lọc (tối đa 10,000 dòng), không chỉ 10 dòng của trang đang xem'),
        ('G113', '1. Bấm Xuất Excel, bảo đảm trường Tỷ giá (VNĐ) đang được tích\n2. Bấm Xuất file\n3. Nhìn cột Tỷ giá (VNĐ) trong file'),
        ('I113', '- Tỷ giá là ô SỐ (cộng SUM được), đúng giá trị như trên màn hình, không mất phần thập phân\n- Hiển thị theo chuẩn quốc tế: dấu phẩy ngăn hàng nghìn, dấu chấm thập phân (vd 30,792.68)'),
        ('G114', '1. Lọc ra kết quả rỗng\n2. Bấm Xuất Excel → Xuất file'),
        ('I114', '- Hệ thống không lỗi, báo "Xuất Excel thành công"\n- File tải về chỉ có tiêu đề và dòng tên cột, không có dòng dữ liệu'),
        ('G115', '1. Bấm Xuất Excel\n2. Bấm Xuất file'),
        ('I115', '- Nút Xuất Excel vẫn hiện, cửa sổ "Chọn trường xuất file" mở bình thường\n- Tải được file danh_muc_tien_te.xlsx, có thông báo "Xuất Excel thành công"'),
    ],
    'clear_k': [108, 109, 110, 111, 112, 113, 114, 115, 129, 134],
}

CFG['tc_ngoai_pham_vi'] = [
    'B10 + TC_01.006 (hàng 33) + TC_05.00x: còn ghi nút Khóa/Mở khóa nằm TRONG cột Trạng thái — nay đã chuyển về cột Hành động (nút ba chấm).',
    'B10 + TC_08.011 (hàng 127) + H118/H119/H145/H148: còn dùng định dạng số kiểu Việt Nam (100,00 · 999.999,99 · 555,55) — nay chuẩn quốc tế 1,234.56; TC_08.011 "Nhập Tỷ giá dùng dấu phẩy thập phân" không còn đúng (dấu phẩy nay là ngăn nghìn).',
    'TC_04.013 (hàng 81) "Nút Xem" + TC_04.014: màn không còn nút Xem ở cột Hành động — bấm vào Mã tiền tệ để mở cửa sổ Xem.',
    'TC_06.003 (hàng 100) "Nút Xóa bị vô hiệu": nay nút Xóa bị ẨN hẳn chứ không mờ, không có chú thích rê chuột. TC_06.008 (hàng 105) xóa tiền tệ đang Khóa: hiện máy chủ chặn “Tiền tệ đang bị khoá…” (xem loi_code).',
    'TC_08.001 (hàng 117): bấm Lưu khi để trống cả 3 ô — FE chỉ chặn ô Tên (required) và dừng, KHÔNG gọi máy chủ → lần bấm đầu chỉ ô Tên báo "Bắt buộc phải nhập"; Mã và Tỷ giá chỉ báo sau khi đã nhập Tên. Expected "cả 3 ô đỏ cùng lúc" cần xem lại (cần kiểm trên màn hình).',
    'Chưa có case "Nhập trùng Tên tiền tệ" (nay Tên tiền tệ là duy nhất, báo "Tên tiền tệ đã tồn tại"); B3 còn mô tả dòng phụ "Tên gọi khác" dưới tên — nay là cột riêng mặc định ẩn; cột "Cập nhật" nay tách Người cập nhật / Ngày cập nhật.',
    'B10 "Nút Xuất Excel luôn hiện" vẫn đúng; nhưng chưa có case Lịch sử thay đổi (nút Lịch sử ở cột Hành động + khối Lịch sử trong cửa sổ Xem) và Tùy chỉnh cột.',
]

CFG.setdefault('loi_code', []).append('Cửa sổ Tạo/Sửa tiền tệ: ô Tên tiền tệ dùng chung placeholder "VD: USD" với ô Mã (thấy khi chụp 26/09/2026).')
