# -*- coding: utf-8 -*-
# Cấu hình tài liệu màn Danh mục Quận/Huyện — bám khuôn configs/areas.py.
# Nguồn: code gop_db 28/09/2026 (FE pages/human/districts/index.vue, components/DistrictModel.vue;
# BE District / DistrictService / DistrictController / Routes api.php / CreateDistrictRequest /
# DistrictResource/* / ExportColumnRegistry['districts']).
# 28/09/2026: có Khóa/Mở khóa, ô Trạng thái trong cửa sổ Tạo/Sửa, cột + bộ lọc Trạng thái; Xóa = xóa HẲN
# khi đang Hoạt động và chưa được dùng; bản ghi Khóa bị máy chủ chặn sửa/xóa (423).
# Không ghi URL. Chữ UI / message lấy nguyên văn code.

DT = 'quận/huyện'

# Nơi được coi là "đã dùng" (District::USAGE_REFERENCES) — tên nghiệp vụ, không ghi tên bảng.
NOI_DUNG = ('Phường/Xã (có phường/xã trực thuộc), hồ sơ nhân sự (địa chỉ thường trú hoặc tạm trú), '
            'Khách hàng, Công ty, Nhà cung cấp, Địa điểm giao hàng')

CFG = {
    'slug': 'districts',
    'ten': 'Danh mục Quận/Huyện',
    'doi_tuong': DT,
    'file_hdsd': 'HDSD_Danh mục Quận-Huyện.docx',
    'file_srs': 'SRS - Danh mục Quận-Huyện.docx',
    'menu': [('Danh mục', 'menu_phanhe'), ('Địa lý', 'menu_nhom'), ('Quận/Huyện', 'menu_muc')],

    'thuat_ngu': [
        ['Quận/Huyện', 'Đơn vị hành chính cấp huyện, trực thuộc một Tỉnh/TP. Việt Nam đã bỏ cấp huyện nên danh mục chủ yếu dùng cho địa chỉ nước ngoài và dữ liệu cũ.'],
        ['Tỉnh/TP', 'Tỉnh/thành phố mà quận/huyện trực thuộc, chọn từ Danh mục Tỉnh/TP.'],
        ['Trạng thái Hoạt động', 'Quận/huyện dùng được ở các màn nghiệp vụ khác.'],
        ['Trạng thái Khóa', 'Quận/huyện không còn chọn được ở nơi khác nhưng vẫn nằm trong danh mục, vẫn xem được chi tiết và lịch sử. Dữ liệu đang dùng quận/huyện đó vẫn giữ nguyên.'],
        ['Đã được dùng', 'Quận/huyện đã được tham chiếu ở ít nhất một nơi: ' + NOI_DUNG + '. Quận/huyện đã được dùng thì không xóa được, chỉ Khóa được.'],
    ],
    'phien_ban': [
        ['1.0', '17/08/2026', 'Đội phát triển phần mềm', 'Tạo mới cho màn Danh mục Quận/Huyện.'],
        ['1.1', '25/09/2026', 'Đội phát triển phần mềm', 'Cập nhật theo phiên bản hiện tại: bổ sung Xem chi tiết, Xuất Excel, Import Excel, Tùy chỉnh cột; trình bày theo mẫu tài liệu danh mục chung.'],
        ['1.2', '28/09/2026', 'Đội phát triển phần mềm', 'Bổ sung Khóa / Mở khóa, ô Trạng thái trong cửa sổ Tạo/Sửa, cột và bộ lọc Trạng thái trên danh sách, trường Trạng thái khi xuất Excel. Xóa đổi thành xóa hẳn và chỉ áp dụng cho quận/huyện đang Hoạt động, chưa được dùng ở đâu; quận/huyện đang Khóa không sửa, không xóa được.'],
    ],
    'muc_dich': [
        'Danh mục Quận/Huyện là nơi khai báo và quản lý danh sách quận/huyện dùng chung cho toàn hệ thống. Mỗi quận/huyện trực thuộc một Tỉnh/TP; dữ liệu của màn này là nguồn cho ô Quận/Huyện ở các màn địa chỉ (đặc biệt địa chỉ ở nước ngoài và Danh mục Đường/Phố), nên mỗi thay đổi ở đây đều ảnh hưởng tới nhiều nơi.',
    ],
    'quyen': {
        'truoc': ['Phân quyền ai được quyền tạo/ sửa/ xóa/ khóa/ mở khóa sẽ được cập nhật ngay sau khi có tài liệu phân quyền chi tiết của hệ thống.',
                  'Tại thời điểm xây dựng HDSD hiện tại, ai cũng được quyền truy cập màn hình danh mục Quận/Huyện và quyền tạo/sửa/xóa/khóa/mở khóa, import, xuất Excel.'],
        'rows': [],
        'sau': ['Lưu ý: vì ai cũng sửa được, Người dùng hãy cân nhắc kỹ trước khi đổi, khóa hoặc xóa một bản ghi — dữ liệu này đang được nhiều màn khác sử dụng.'],
    },

    'danh_sach': {
        'mo_ta_vao': 'Hệ thống hiển thị danh sách quận/huyện hiện có — gồm cả quận/huyện đang Hoạt động lẫn đang Khóa, mặc định 10 dòng mỗi trang.',
        'bo_cuc': [
            'Khu vực tìm kiếm và lọc — ô tìm kiếm nhanh, ô Quốc gia, ô Tỉnh/TP, ô Trạng thái, nút Tìm kiếm và Làm mới.',
            'Thanh công cụ — nút Tạo mới, nút Xuất Excel, nút Import Excel và biểu tượng Cấu hình cột hiển thị.',
            'Bảng danh sách — các cột thông tin, cột Hành động ở cuối, và phân trang bên dưới.',
        ],
        'cot': [
            ['STT', 'Số thứ tự, chạy liên tục qua các trang. Luôn hiển thị.'],
            ['Tên quận/huyện', 'Tên đầy đủ. Luôn hiển thị, sắp xếp được. Bấm vào tên để mở cửa sổ Xem quận/huyện.'],
            ['Tỉnh/TP', 'Tỉnh/TP mà quận/huyện trực thuộc.'],
            ['Quốc gia', 'Quốc gia của tỉnh/TP. Mặc định ẩn.'],
            ['Người cập nhật', 'Người sửa bản ghi gần nhất. Mặc định ẩn.'],
            ['Ngày cập nhật', 'Thời điểm sửa gần nhất, dạng dd/mm/yyyy hh:mm. Mặc định ẩn, sắp xếp được.'],
            ['Người tạo', 'Người đã thêm bản ghi.'],
            ['Ngày tạo', 'Thời điểm thêm, dạng dd/mm/yyyy hh:mm, sắp xếp được.'],
            ['Trạng thái', 'Nhãn Hoạt động hoặc Khóa.'],
            ['Hành động', 'Các nút thao tác của dòng (xem mục 4).'],
        ],
        'hanh_dong': {
            'intro': 'Trên mỗi dòng, cột Hành động có các nút:',
            'bullets': [
                'Biểu tượng bút chì {icon:btn_sua} — mở cửa sổ Sửa quận/huyện. Chỉ hiện khi quận/huyện đang Hoạt động.',
                'Biểu tượng thùng rác {icon:btn_xoa} — xóa quận/huyện. Chỉ hiện khi quận/huyện đang Hoạt động VÀ CHƯA được dùng ở đâu (' + NOI_DUNG + ').',
                'Khóa / Mở khóa — đổi trạng thái quận/huyện. Dòng đang Hoạt động hiện Khóa, dòng đang Khóa hiện Mở khóa.',
                'Lịch sử — mở cửa sổ Lịch sử thay đổi.',
                'Có từ 4 nút trở lên thì 2 nút đầu hiện thẳng, các nút còn lại nằm trong nút ba chấm {icon:btn_bacham} “Hành động khác”. Dòng có 3 nút trở xuống thì mọi nút hiện thẳng.',
            ],
            'anh': 'Các nút ở cột Hành động của một quận/huyện',
            'luu_y': ['Lưu ý quan trọng: với bản ghi ĐÃ KHÓA, nút Sửa và Xóa sẽ BIẾN MẤT, chỉ còn Mở khóa và Lịch sử. Muốn sửa lại, Người dùng phải Mở khóa trước. Quận/huyện đã được dùng ở nơi khác thì KHÔNG có nút Xóa — dùng Khóa thay cho Xóa.'],
        },
        'phan_trang': [
            'Cuối bảng có dòng “Hiển thị a–b / N”: N là tổng số quận/huyện khớp bộ lọc đang áp dụng (tính cả bản ghi Khóa nếu không lọc Trạng thái), không phải tổng toàn danh mục.',
            'Ô Số dòng/trang có các mức 5, 10, 20, 50, 100 (mặc định 10). Đổi số dòng thì hệ thống tự quay về trang 1.',
            'Các cột sắp xếp được: Tên quận/huyện, Ngày tạo, Ngày cập nhật. Bấm tiêu đề cột để sắp xếp, bấm lần hai để đảo chiều. Thứ tự sắp xếp được giữ nguyên khi chuyển trang. Chưa bấm sắp xếp thì bản ghi tạo gần nhất nằm trên cùng.',
        ],
    },

    'loc': {
        'buoc2': 'Bước 2: Nhập chữ vào ô tìm kiếm nhanh hoặc chọn giá trị ở ô Quốc gia, Tỉnh/TP, Trạng thái.',
        'rows': [
            ['Ô tìm kiếm nhanh', 'Tìm theo TÊN quận/huyện (gõ một phần tên cũng ra). Nhấn Enter hoặc bấm Tìm kiếm để lọc.'],
            ['Quốc gia', 'Chọn một quốc gia để chỉ xem quận/huyện thuộc các tỉnh/TP của quốc gia đó; đồng thời thu hẹp danh sách của ô Tỉnh/TP. Lọc ngay khi chọn.'],
            ['Tỉnh/TP', 'Chọn một tỉnh/TP để chỉ xem quận/huyện của tỉnh/TP đó. Bị xóa trắng khi đổi Quốc gia. Lọc ngay khi chọn.'],
            ['Trạng thái', 'Hoạt động hoặc Khóa. Bỏ trống thì hiện cả hai trạng thái. Lọc ngay khi chọn.'],
        ],
        'ap_dung': [
            'Các tiêu chí kết hợp với nhau theo kiểu VÀ — chỉ bản ghi thỏa đồng thời tất cả các tiêu chí mới hiện ra. Mỗi lần đổi tiêu chí, danh sách quay về trang 1.',
            'Lưu ý: ô Quốc gia và ô Tỉnh/TP phụ thuộc nhau. Đổi Quốc gia thì ô Tỉnh/TP bị xóa trắng và chỉ còn các tỉnh/TP của quốc gia mới.',
            'Bấm {icon:btn_lammoi} để xóa toàn bộ tiêu chí; danh sách nạp lại đầy đủ ngay lập tức.',
        ],
        'anh_ket_qua': 'Kết quả tìm nhanh theo tên quận/huyện (gõ “Quận”)',
    },

    'form': {
        'kieu': 'popup',
        'buoc_tao': [
            'Bước 1: Truy cập vào màn hình Danh mục Quận/Huyện.',
            'Bước 2: Bấm {icon:btn_taomoi}. Hệ thống mở cửa sổ “Tạo quận/huyện”.',
            'Bước 3: Nhập/ chọn đầy đủ thông tin: Tên quận/huyện, Tỉnh/TP, Trạng thái.',
            'Bước 4: Bấm {icon:btn_luu} để lưu và đóng cửa sổ, hoặc {icon:btn_luutieptuc} để lưu rồi nhập tiếp quận/huyện khác.',
        ],
        'anh_tao': 'Cửa sổ Tạo quận/huyện',
        'truong': [
            ['Tên quận/huyện', 'Ô nhập giá trị', 'Có', 'Trống', 'Tối đa 255 ký tự. Không được trùng trong cùng một Tỉnh/TP, kể cả quận/huyện đang Khóa (cùng tên ở tỉnh/TP khác vẫn lưu được). Bỏ trống báo “Bắt buộc phải nhập”; trùng báo “Tên quận/huyện này đã tồn tại trong tỉnh/TP”.'],
            ['Tỉnh/TP', 'Ô chọn giá trị', 'Có', 'Trống', 'Liệt kê tỉnh/TP đang Hoạt động của mọi quốc gia. Quận/huyện đang dùng một tỉnh/TP đã khóa vẫn hiện đúng tên tỉnh/TP đó kèm biểu tượng 🔒. Bỏ trống báo “Bắt buộc phải nhập”.'],
            ['Trạng thái', 'Ô chọn giá trị', 'Không', 'Hoạt động', 'Chỉ chọn 1 trong 2 giá trị: Hoạt động / Khóa. Ô luôn có giá trị, không xóa trống được. Chọn Khóa thì quận/huyện được lưu ở trạng thái Khóa ngay.'],
        ],
        'nut': [
            ['Lưu', 'Ghi bản ghi rồi đóng cửa sổ, báo “Thêm mới thành công” (hoặc “Cập nhật thành công” khi sửa) và nạp lại danh sách.'],
            ['Lưu và tiếp tục', 'Ghi bản ghi nhưng GIỮ cửa sổ mở và xóa trắng các ô (Trạng thái về Hoạt động) để nhập tiếp. Chỉ có khi Tạo mới.'],
            ['Đóng', 'Đóng cửa sổ, không ghi gì. Nếu đã nhập dở, hệ thống hỏi “Thông tin chưa lưu” — “Bạn có thông tin chưa lưu. Có chắc chắn muốn thoát?” (Thoát / Ở lại).'],
        ],
        'loi': [
            ['Bắt buộc phải nhập', 'Chưa nhập Tên quận/huyện hoặc chưa chọn Tỉnh/TP.'],
            ['Tên quận/huyện này đã tồn tại trong tỉnh/TP', 'Đã có quận/huyện khác cùng tên trong cùng một Tỉnh/TP (kể cả quận/huyện đang Khóa). Hãy kiểm tra lại danh sách, bỏ trống ô Trạng thái để thấy cả bản ghi Khóa.'],
            ['Vui lòng nhập tối đa 255 ký tự.', 'Tên quận/huyện quá dài.'],
            ['Vui lòng kiểm tra lại dữ liệu nhập', 'Thông báo chung khi còn ô bị lỗi; xem các ô báo đỏ trong cửa sổ.'],
        ],
    },

    'sua': {
        'buoc': [
            'Bước 1: Truy cập vào màn hình Danh mục Quận/Huyện.',
            'Bước 2: Bấm nút {icon:btn_sua} ở cột Hành động của quận/huyện cần sửa.',
            'Bước 3: Hệ thống hiển thị cửa sổ “Sửa quận/huyện” với dữ liệu hiện tại.',
            'Bước 4: Cập nhật các thông tin cần sửa (quy tắc nhập như Thêm mới).',
            'Bước 5: Bấm {icon:btn_luu} để xác nhận thay đổi hoặc Đóng nếu muốn hủy.',
        ],
        'anh': 'Cửa sổ Sửa quận/huyện',
        'ghi_chu': [
            'Giữ nguyên tên của chính quận/huyện đang sửa thì không bị báo trùng.',
            'Quận/huyện đang Khóa không có nút Sửa. Nếu quận/huyện vừa bị người khác khóa, bấm Lưu sẽ nhận thông báo “Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.”',
            'Đổi Trạng thái sang Khóa ngay trong cửa sổ Sửa rồi Lưu cũng là khóa quận/huyện; lịch sử ghi thành một dòng Thay đổi trạng thái riêng.',
            'Mọi thay đổi đều được ghi vào Lịch sử kèm tên Người dùng và thời điểm.',
            'Đổi tên tỉnh/TP ở Danh mục Tỉnh/TP thì cột Tỉnh/TP của quận/huyện tự hiển thị tên mới.',
        ],
    },
    'xoa': {
        'buoc': [
            'Bước 1: Ở cột Hành động, Người dùng bấm {icon:btn_xoa}.',
            'Bước 2: Hệ thống hiện hộp xác nhận “Xóa Quận/Huyện” — “Bạn có chắc muốn xóa quận/huyện "…"?”. Bấm {icon:btn_confirm_xoa} để xác nhận: hệ thống báo “Xoá quận/huyện thành công”, bản ghi biến mất khỏi danh sách.',
            'Bấm {icon:btn_huy} nếu bấm nhầm. Không có gì thay đổi.',
        ],
        'anh': 'Hộp xác nhận xóa quận/huyện',
        'ghi_chu': [
            'Xóa là xóa HẲN bản ghi khỏi hệ thống: không còn thấy ở danh sách (kể cả khi lọc Trạng thái = Khóa), không khôi phục được. Tên đã xóa có thể dùng lại để tạo quận/huyện mới trong cùng Tỉnh/TP.',
            'Nút Xóa chỉ hiện khi quận/huyện đang Hoạt động VÀ CHƯA được dùng ở đâu. Quận/huyện được coi là đã dùng khi có ở một trong các nơi: ' + NOI_DUNG + '. Quận/huyện đã được dùng thì dùng Khóa thay cho Xóa.',
            'Nếu trong lúc hộp xác nhận đang mở, quận/huyện vừa được dùng ở nơi khác, hệ thống báo “Quận/huyện đang được sử dụng, không thể xóa.”; nếu vừa bị người khác khóa, báo “Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.”; nếu vừa bị người khác xóa, báo “Trạng thái đã bị thay đổi. Vui lòng load lại trang”.',
        ],
    },
    'khoa': {
        'y_nghia': [
            'Bản ghi VẪN nằm trong danh sách, cột Trạng thái hiện chữ Khóa.',
            'Vẫn xem được chi tiết và lịch sử thay đổi của bản ghi.',
            'Quận/huyện đã khóa không còn xuất hiện ở ô chọn quận/huyện của các màn khác (ví dụ Danh mục Đường/Phố, địa chỉ khách hàng, hồ sơ nhân sự); dữ liệu đang dùng quận/huyện đó vẫn giữ nguyên và hiển thị đúng tên kèm biểu tượng 🔒.',
            'Khóa được cả khi quận/huyện đang được dùng ở nơi khác.',
            'Nút Sửa và Xóa của dòng đó biến mất.',
        ],
        'buoc_khoa': [
            'Bước 1: Ở cột Hành động, Người dùng chọn Khóa (trong nút ba chấm {icon:btn_bacham} nếu dòng có nhiều nút).',
            'Bước 2: Hệ thống hiện hộp xác nhận “Khóa Quận/Huyện” — “Bạn có chắc muốn khóa quận/huyện "…"?”. Bấm Khóa để xác nhận; hệ thống báo “Khóa thành công”, cột Trạng thái đổi thành Khóa. Bấm Hủy nếu bấm nhầm.',
        ],
        'buoc_mo': [
            'Bước 1: Ở cột Hành động của quận/huyện đang Khóa, Người dùng chọn {icon:btn_mokhoa} Mở khóa.',
            'Bước 2: Bấm {icon:btn_confirm_mokhoa} trong hộp xác nhận “Mở khóa Quận/Huyện” — “Bạn có chắc muốn mở khóa quận/huyện "…"?”. Hệ thống báo “Mở khóa thành công”, cột Trạng thái đổi thành Hoạt động, nút Sửa hiện lại (nút Xóa hiện lại nếu quận/huyện chưa được dùng). Bấm Hủy nếu bấm nhầm.',
        ],
        'ghi_chu': ['Có thể khóa ngay trong cửa sổ Sửa bằng cách chọn Trạng thái = Khóa rồi Lưu. Nếu bản ghi vừa bị người khác đổi trạng thái (hoặc đã bị xóa), hệ thống báo “Trạng thái đã bị thay đổi. Vui lòng load lại trang” và không thực hiện lại thao tác.'],
    },
    'lich_su': {
        'buoc': [
            'Xem từ màn danh sách: ở cột Hành động, Người dùng chọn Lịch sử (trong nút ba chấm nếu dòng có nhiều nút).',
            'Xem từ màn chi tiết: bấm vào tên quận/huyện để mở cửa sổ Xem quận/huyện, khối Lịch sử nằm ở cuối cửa sổ.',
        ],
        'ghi_chu': ['Khóa / Mở khóa (kể cả đổi Trạng thái trong cửa sổ Sửa) được ghi dưới dạng Thay đổi trạng thái (Hoạt động → Khóa hoặc ngược lại). Trường Tỉnh/TP trong lịch sử hiển thị bằng TÊN. Cửa sổ có bộ lọc riêng (loại hành động, người thực hiện, khoảng thời gian).'],
    },
    'chi_tiet': {
        'buoc': ['Bước 1: Truy cập vào màn hình Danh mục Quận/Huyện.',
                 'Bước 2: Bấm vào tên quận/huyện ở cột Tên quận/huyện. Hệ thống mở cửa sổ “Xem quận/huyện”.'],
        'ghi_chu': ['Cửa sổ hiển thị Tên quận/huyện, Tỉnh/TP và Trạng thái ở chế độ chỉ đọc (không gõ được, không có nút Lưu), kèm khối Lịch sử ở cuối. Quận/huyện đang Khóa vẫn xem được bình thường.'],
    },
    'xuat': {
        'buoc': [
            'Bước 1: Lọc danh sách theo đúng dữ liệu cần lấy (xem PHẦN 2). File xuất ra chạy theo đúng bộ lọc đang áp dụng, kể cả bộ lọc Trạng thái.',
            'Bước 2: Bấm nút {icon:btn_xuatexcel}. Hệ thống mở cửa sổ “Chọn trường xuất file”.',
            'Bước 3: Tích chọn, kéo biểu tượng ☰ để đổi vị trí các trường cần xuất. Mặc định hệ thống tích sẵn đúng những cột đang hiển thị trên bảng.',
            'Bước 4: Bấm {icon:btn_xuatfile}. Hệ thống tải về file danh_muc_quan_huyen.xlsx và báo “Xuất Excel thành công”.',
        ],
        'truong': 'Chọn nhiều trường: Tên quận/huyện, Tỉnh/TP, Quốc gia, Trạng thái, Người tạo, Ngày tạo, Người cập nhật, Ngày cập nhật.',
        'ghi_chu': ['Lưu ý: file xuất chứa TOÀN BỘ kết quả của bộ lọc (tối đa 10,000 dòng), không chỉ các dòng của trang đang xem. Cột Trạng thái trong file ghi chữ “Hoạt động” hoặc “Khóa”.'],
    },
    'import': {
        'tieu_de': 'Import quận/huyện',
        'file': 'Mau_import_quan_huyen.xlsx',
        'cot_text': 'Tên quận/huyện (bắt buộc), Tỉnh/TP (bắt buộc, chọn trong danh sách sổ xuống)',
        'toast': 'Import thành công N quận/huyện.',
        'loi': [
            ['Tên quận/huyện không được để trống', 'Dòng đó bỏ trống cột Tên quận/huyện.'],
            ['Tên quận/huyện tối đa 255 ký tự', 'Tên quá dài, rút gọn lại.'],
            ['Tỉnh/TP không được để trống', 'Dòng đó bỏ trống cột Tỉnh/TP.'],
            ['Không tìm thấy tỉnh/TP: X', 'Tên tỉnh/TP ghi sai, không có trong Danh mục Tỉnh/TP.'],
            ['Tên tỉnh/TP "X" đang có ở nhiều quốc gia, không xác định được', 'Danh mục Tỉnh/TP đang có từ 2 tỉnh/TP trở lên trùng đúng tên này (kể cả tỉnh/TP đã khóa, hoặc cùng quốc gia nhưng khác khu vực) nên hệ thống không biết chọn tỉnh nào.'],
            ['Quận/huyện bị trùng với dòng N trong file', 'Trong chính file có hai dòng cùng tên, cùng tỉnh/TP. Xoá bớt một dòng.'],
            ['Quận/huyện này đã tồn tại trong tỉnh/TP đã chọn', 'Danh mục đã có quận/huyện trùng tên trong cùng tỉnh/TP (kể cả quận/huyện đang Khóa).'],
        ],
        'ghi_chu': ['Lưu ý: quận/huyện nhập từ Excel luôn được tạo ở trạng thái Hoạt động, người tạo là chính người thực hiện nhập. Mỗi lần nhập tối đa 500 dòng; file dài hơn hệ thống báo “File có X dòng dữ liệu, vượt quá giới hạn 500 dòng mỗi lần import. Vui lòng tách file và import nhiều lần.”'],
    },
    'tuy_chinh_cot': {'cot_khoa': 'Ba cột STT, Tên quận/huyện và Hành động'},

    'shots': {'list': '01_list.png', 'rowmenu': '03_rowmenu.png', 'filter': 'filter.png', 'filter_result': '04_filter_result.png',
              'create': '10_create.png', 'create_error': '11_create_error.png', 'edit': '12_edit.png',
              'delete': '13_delete.png', 'lock': '14_lock.png', 'unlock': '15_unlock.png', 'history': '16_history.png',
              'detail': '17_detail.png', 'export': '20_export.png', 'import_open': '21_import_open.png',
              'import_loaded': '22_import_loaded.png', 'import_validated': '23_import_validated.png', 'colcfg': '25_colcfg.png'},

    # lockName: bản ghi thật đang Hoạt động, chưa được dùng ở đâu (tra DB local_hrm_erp 28/09/2026, id 739).
    'capture': {'route': '/human/districts', 'menu': {'phanhe': 'DANH MỤC', 'nhom': 'Địa lý', 'muc': 'Quận/Huyện'},
                'search': 'Tìm theo tên quận/huyện', 'searchText': 'Quận', 'detailCol': 1,
                'lockName': 'DOC-Quận Mẫu Hai',
                'create': True, 'lock': True},

    'import_test': {
        'cols': ['Tên quận/huyện', 'Tỉnh/TP'],
        'rows': [
            ['DOC-Quận Mẫu Một', 'Thành phố Hà Nội'],
            ['DOC-Quận Mẫu Hai', 'Thành phố Hồ Chí Minh'],
            ['DOC-Huyện Mẫu Ba', 'Thành phố Đà Nẵng'],
            ['', 'Thành phố Hà Nội'],
            ['DOC-Quận Mẫu Một', 'Thành phố Hà Nội'],
            ['Quận Tân Bình', 'Thành phố Hồ Chí Minh'],
            ['DOC-Quận Mẫu Bốn', 'Tỉnh không tồn tại'],
            ['DOC-Quận Mẫu Năm', ''],
        ],
    },

    'uml': {
        'mains': [('FR-01', 'Xem danh sách quận/huyện', 'view'), ('FR-03', 'Thêm mới quận/huyện', 'crud'),
                  ('FR-04', 'Chỉnh sửa quận/huyện', 'crud'), ('FR-05', 'Xóa quận/huyện', 'action'),
                  ('FR-06', 'Khóa / Mở khóa quận/huyện', 'action'), ('FR-08', 'Import file quận/huyện', 'io'),
                  ('FR-09', 'Xuất danh sách quận/huyện ra Excel', 'io')],
        'subs': [('FR-02', 'Tìm kiếm và lọc quận/huyện', 'view'), ('FR-10', 'Xem chi tiết quận/huyện', 'view'),
                 ('FR-11', 'Tùy chỉnh cột hiển thị', 'view'), ('FR-07', 'Xem lịch sử thay đổi', 'view')],
        'rieng': [('FR-10', 'Xem chi tiết quận/huyện', 'view')],
    },

    'srs': {
        'muc_dich': ['Là căn cứ nghiệm thu chức năng.',
                     'Làm rõ ràng buộc trùng tên quận/huyện (duy nhất trong cùng Tỉnh/TP), điều kiện Xóa (xóa hẳn, chỉ khi đang Hoạt động và chưa được dùng), ý nghĩa của trạng thái Khóa và quan hệ Tỉnh/TP → Quận/Huyện.'],
        'quyen_truoc': ['Danh sách quyền sẽ được cập nhật sau khi có tài liệu phân quyền chi tiết của hệ thống. Tại thời điểm xây dựng SRS, màn hình chưa gắn quyền; mọi người dùng đã đăng nhập đều thực hiện được các chức năng.'],
        'quyen_rows': [['(chưa khai báo quyền nào)', 'Sẽ cập nhật sau khi có tài liệu phân quyền chi tiết']],
        'ma_tran': [['Chức năng', 'Người dùng đã đăng nhập']] + [[f, 'Chờ cập nhật theo ma trận phân quyền chi tiết'] for f in [
            'FR-01 Xem danh sách quận/huyện', 'FR-02 Tìm kiếm và lọc', 'FR-03 Thêm mới quận/huyện', 'FR-04 Chỉnh sửa quận/huyện',
            'FR-05 Xóa quận/huyện', 'FR-06 Khóa / Mở khóa quận/huyện', 'FR-07 Xem lịch sử thay đổi', 'FR-08 Import file quận/huyện',
            'FR-09 Xuất danh sách ra Excel', 'FR-10 Xem chi tiết quận/huyện', 'FR-11 Tùy chỉnh cột hiển thị']],
        'ma_tran_widths': [2.4, 2.4],
        'fr': [
            {'ten': 'Xem danh sách quận/huyện',
             'qtc': 'Màn Danh sách, Sắp xếp dữ liệu bảng, Phân trang và Cấu hình cột. Chỉ bổ sung các quy tắc riêng của Danh mục Quận/Huyện tại phần mô tả chi tiết.',
             'gioi_thieu': [['Tên chức năng', 'Xem danh sách quận/huyện'],
                            ['Mô tả', 'Hiển thị toàn bộ quận/huyện trong danh mục (cả Hoạt động lẫn Khóa), có phân trang và sắp xếp.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Điều kiện ban đầu', 'Người dùng đã đăng nhập vào hệ thống.'],
                            ['Dòng sự kiện chính', '1. Người dùng vào menu Danh mục → Địa lý → Quận/Huyện.\n2. Hệ thống nạp trang đầu tiên của danh sách (10 dòng), bản ghi tạo gần nhất trên cùng.\n3. Bảng hiển thị dữ liệu kèm tổng số bản ghi.'],
                            ['Dòng sự kiện phụ', '• Không có bản ghi khớp → bảng hiện “Không có dữ liệu phù hợp bộ lọc.”\n• Phiên đăng nhập hết hạn → điều hướng về màn đăng nhập.']],
             'anh': [('list', 'Màn Danh mục Quận/Huyện lúc mới truy cập')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Mô tả'],
                    ['1', 'STT', 'Table/Grid', 'Read-only', 'Số thứ tự, chạy liên tục qua các trang. Luôn hiển thị, không ẩn được.'],
                    ['2', 'Tên quận/huyện', 'Table/Grid', 'Read-only', 'Luôn hiển thị, sắp xếp được. Bấm vào tên mở cửa sổ Xem (xem 2.10).'],
                    ['3', 'Tỉnh/TP', 'Table/Grid', 'Read-only', 'Tỉnh/TP trực thuộc.'],
                    ['4', 'Quốc gia', 'Table/Grid', 'Read-only', 'Mặc định ẩn.'],
                    ['5', 'Người cập nhật', 'Table/Grid', 'Read-only', 'Mặc định ẩn.'],
                    ['6', 'Ngày cập nhật', 'Table/Grid', 'Read-only', 'dd/mm/yyyy hh:mm. Mặc định ẩn, sắp xếp được.'],
                    ['7', 'Người tạo', 'Table/Grid', 'Read-only', 'Người đã thêm bản ghi.'],
                    ['8', 'Ngày tạo', 'Table/Grid', 'Read-only', 'dd/mm/yyyy hh:mm, sắp xếp được.'],
                    ['9', 'Trạng thái', 'Badge', 'Read-only', 'Hoạt động hoặc Khóa.'],
                    ['10', 'Hành động', 'Table/Grid', 'Read-only', 'Sửa (khi Hoạt động), Xóa (khi Hoạt động và chưa được dùng ở đâu), Khóa / Mở khóa, Lịch sử. Từ 4 nút trở lên thì 2 nút đầu hiện thẳng, còn lại trong nút ba chấm “Hành động khác”. Bản ghi Khóa chỉ còn Mở khóa và Lịch sử.'],
                    ['11', 'Nút Tạo mới', 'Button', 'Enable', 'Mở cửa sổ Tạo quận/huyện.'],
                    ['12', 'Nút Xuất Excel', 'Button', 'Enable', 'Mở cửa sổ Chọn trường xuất file (xem 2.9).'],
                    ['13', 'Nút Import Excel', 'Button', 'Enable', 'Mở cửa sổ Import quận/huyện (xem 2.8).'],
                    ['14', 'Biểu tượng Cấu hình cột hiển thị', 'Icon Button', 'Enable', 'Mở cửa sổ Tuỳ chỉnh cột (xem 2.11).'],
                    ['15', 'Phân trang', 'Pagination', 'Enable', 'Số dòng/trang 5 / 10 / 20 / 50 / 100, mặc định 10.']],
             'ui_widths': [0.6, 1.4, 0.9, 0.8, 3],
             'events': [['Mở màn hình', 'System', 'After:\n– Nạp trang đầu (cả bản ghi Hoạt động lẫn Khóa), hiển thị tổng số bản ghi.'],
                        ['Bấm tiêu đề cột sắp xếp được', 'Click', 'After:\n– Đổi chiều sắp xếp và nạp lại danh sách từ trang 1.'],
                        ['Chuyển trang', 'Click', 'Before:\n– Giữ nguyên bộ lọc và thứ tự sắp xếp.\nAfter:\n– Nạp dữ liệu trang mới, số thứ tự tiếp tục liên tục.'],
                        ['Đổi số dòng mỗi trang', 'Change', 'After:\n– Quay về trang 1 và nạp lại theo số dòng mới.']]},
            {'ten': 'Tìm kiếm và lọc',
             'qtc': 'Kịch bản tìm kiếm, Bộ lọc, Dropdown, Phân trang. Chỉ bổ sung các tiêu chí tìm kiếm/lọc riêng của Danh mục Quận/Huyện.',
             'gioi_thieu': [['Tên chức năng', 'Tìm kiếm và lọc danh sách'],
                            ['Mô tả', 'Thu hẹp danh sách bằng ô tìm kiếm nhanh, ô Quốc gia, ô Tỉnh/TP (hai ô lọc phụ thuộc nhau) và ô Trạng thái.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Điều kiện ban đầu', 'Đang ở màn Danh mục Quận/Huyện.'],
                            ['Dòng sự kiện chính', '1. Người dùng nhập từ khóa và bấm Tìm kiếm / Enter, hoặc chọn Quốc gia / Tỉnh/TP / Trạng thái (lọc ngay).\n2. Hệ thống áp đồng thời mọi tiêu chí và nạp lại danh sách từ trang 1.'],
                            ['Dòng sự kiện phụ', '• Đổi Quốc gia → ô Tỉnh/TP bị xóa trắng, chỉ còn tỉnh/TP của quốc gia mới.\n• Bỏ trống Trạng thái → hiện cả Hoạt động lẫn Khóa.\n• Không có kết quả → bảng hiện thông báo không có dữ liệu.\n• Bấm Làm mới → xóa hết tiêu chí VÀ nạp lại danh sách đầy đủ ngay.']],
             'anh': [('filter', 'Khu vực tìm kiếm và lọc của màn Danh mục Quận/Huyện')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Phạm vi', 'Mô tả'],
                    ['1', 'Ô tìm kiếm nhanh', 'Textbox', 'Enable', '0–255 ký tự', 'Placeholder “Tìm theo tên quận/huyện”. Tìm theo TÊN (khớp một phần).'],
                    ['2', 'Quốc gia', 'Dropdown', 'Enable', 'Danh mục quốc gia', 'Nhãn nổi. Bỏ trống thì hiện mọi quốc gia.'],
                    ['3', 'Tỉnh/TP', 'Dropdown', 'Enable', 'Tỉnh/TP của quốc gia đã chọn (hoặc tất cả)', 'Nhãn nổi. Bị xóa trắng khi đổi Quốc gia.'],
                    ['4', 'Trạng thái', 'Dropdown', 'Enable', 'Hoạt động / Khóa', 'Nhãn nổi. Bỏ trống thì hiện cả hai trạng thái.'],
                    ['5', 'Nút Tìm kiếm', 'Button', 'Enable', '–', 'Áp dụng các tiêu chí.'],
                    ['6', 'Nút Làm mới', 'Button', 'Enable', '–', 'Xóa hết tiêu chí VÀ nạp lại danh sách ngay.']],
             'ui_widths': [0.6, 1.2, 0.8, 0.7, 1.1, 2.6],
             'events': [['Bấm Tìm kiếm / Enter', 'Click', 'After:\n– Áp đồng thời các tiêu chí theo kiểu “và”, nạp lại bảng từ trang 1.'],
                        ['Chọn Quốc gia', 'Change', 'After:\n– Xóa trắng ô Tỉnh/TP, lọc lại danh sách chọn Tỉnh/TP, nạp lại bảng từ trang 1.'],
                        ['Chọn Tỉnh/TP / Trạng thái', 'Change', 'After:\n– Lọc ngay, nạp lại bảng từ trang 1.'],
                        ['Bấm Làm mới', 'Click', 'After:\n– Xóa trắng mọi tiêu chí VÀ nạp lại danh sách đầy đủ.']]},
            {'ten': 'Thêm mới quận/huyện', 'uc': 'uc_fr03',
             'qtc': 'Màn Thêm mới, Validate dữ liệu, Thông báo và UI/UX. Logic ghi lịch sử áp dụng theo SRS Các quy tắc chung - Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Thêm mới quận/huyện'],
                            ['Mô tả', 'Thêm một quận/huyện mới thông qua cửa sổ nhập liệu.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập (chờ cập nhật theo phân quyền chi tiết).'],
                            ['Điều kiện ban đầu', 'Đang ở màn Danh mục Quận/Huyện.'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm Tạo mới.\n2. Hệ thống mở cửa sổ “Tạo quận/huyện”, Trạng thái mặc định Hoạt động.\n3. Người dùng nhập Tên quận/huyện, chọn Tỉnh/TP (và Trạng thái nếu cần) rồi bấm Lưu.\n4. Hệ thống kiểm tra dữ liệu, ghi bản ghi mới theo Trạng thái đã chọn và ghi lịch sử Tạo mới.\n5. Cửa sổ đóng, danh sách nạp lại, báo “Thêm mới thành công”.'],
                            ['Dòng sự kiện phụ', '• Thiếu trường bắt buộc hoặc trùng tên → báo lỗi đỏ dưới ô + toast “Vui lòng kiểm tra lại dữ liệu nhập”, cửa sổ KHÔNG đóng.\n• Bấm “Lưu và tiếp tục” → ghi bản ghi rồi giữ cửa sổ mở với các ô trống, Trạng thái về Hoạt động.\n• Bấm Đóng khi đã nhập dở → hỏi “Thông tin chưa lưu” (Thoát / Ở lại).'],
                            ['Yêu cầu đặc biệt', 'Cửa sổ có ba nút: Lưu, Lưu và tiếp tục, Đóng.']],
             'menu_them': ' => Tạo mới {icon:btn_taomoi}',
             'ghi_chu_layout': 'Cửa sổ Tạo quận/huyện được mở ngay trên màn hình danh sách.',
             'anh': [('create', 'Cửa sổ Tạo quận/huyện'), ('create_error', 'Lỗi đỏ ngay dưới ô còn thiếu')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Phạm vi', 'Bắt buộc', 'Mô tả'],
                    ['1', 'Tên quận/huyện', 'Textbox', 'Enable', '1–255 ký tự', 'Có', 'Duy nhất trong cùng Tỉnh/TP, tính cả quận/huyện đang Khóa. Bỏ trống “Bắt buộc phải nhập”; trùng “Tên quận/huyện này đã tồn tại trong tỉnh/TP”; quá dài “Vui lòng nhập tối đa 255 ký tự.”'],
                    ['2', 'Tỉnh/TP', 'Dropdown', 'Enable', 'Tỉnh/TP đang Hoạt động', 'Có', 'Bỏ trống “Bắt buộc phải nhập”.'],
                    ['3', 'Trạng thái', 'Dropdown', 'Enable', 'Hoạt động / Khóa', 'Không', 'Mặc định Hoạt động, luôn có giá trị (không xóa trống được).'],
                    ['4', 'Nút Lưu', 'Button', 'Enable', '', '', 'Ghi bản ghi rồi đóng cửa sổ.'],
                    ['5', 'Nút Lưu và tiếp tục', 'Button', 'Enable', '', '', 'Ghi bản ghi rồi giữ cửa sổ mở để nhập tiếp.'],
                    ['6', 'Nút Đóng', 'Button', 'Enable', '', '', 'Hủy bỏ, không ghi gì.']],
             'ui_widths': [0.6, 1.3, 0.8, 0.6, 1.1, 0.5, 2.3],
             'events': [['Bấm nút Tạo mới', 'Click', 'After:\n– Mở cửa sổ nhập liệu với các ô trống, Trạng thái = Hoạt động.'],
                        ['Bấm Lưu', 'Click', 'During:\n– Kiểm tra bắt buộc, độ dài, trùng tên trong cùng Tỉnh/TP (kể cả bản ghi Khóa).\n– Có lỗi → báo đỏ dưới ô, không thực hiện After.\nAfter:\n– Ghi bản ghi mới theo Trạng thái đã chọn, ghi lịch sử Tạo mới.\n– Đóng cửa sổ, nạp lại danh sách, báo “Thêm mới thành công”.'],
                        ['Bấm Lưu và tiếp tục', 'Click', 'During:\n– Như nút Lưu.\nAfter:\n– Ghi bản ghi, xóa trắng các ô (Trạng thái về Hoạt động), GIỮ cửa sổ mở.'],
                        ['Bấm Đóng', 'Click', 'After:\n– Chưa nhập gì → đóng cửa sổ. Đã nhập → hỏi “Thông tin chưa lưu”.']]},
            {'ten': 'Chỉnh sửa quận/huyện', 'uc': 'uc_fr04',
             'qtc': 'Validate dữ liệu, Thông báo, Quy định chung về danh mục và Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Chỉnh sửa quận/huyện'],
                            ['Mô tả', 'Sửa thông tin một quận/huyện đã có. Dùng chung cửa sổ với Thêm mới.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Điều kiện ban đầu', 'Quận/huyện đang ở trạng thái Hoạt động.'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm biểu tượng bút chì ở dòng cần sửa.\n2. Hệ thống mở cửa sổ “Sửa quận/huyện” với dữ liệu hiện tại.\n3. Người dùng sửa và bấm Lưu.\n4. Hệ thống kiểm tra, ghi thay đổi và ghi lịch sử.\n5. Cửa sổ đóng, báo “Cập nhật thành công”.'],
                            ['Dòng sự kiện phụ', '• Giữ nguyên tên của chính bản ghi → không báo trùng.\n• Trùng tên với quận/huyện khác cùng Tỉnh/TP → báo “Tên quận/huyện này đã tồn tại trong tỉnh/TP”.\n• Đổi Trạng thái sang Khóa rồi Lưu → quận/huyện bị khóa, lịch sử ghi dòng Thay đổi trạng thái riêng.\n• Bản ghi vừa bị người khác khóa → máy chủ từ chối, báo “Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.”']],
             'menu_them': ' => Sửa {icon:btn_sua}',
             'anh': [('edit', 'Cửa sổ Sửa quận/huyện')],
             'events': [['Bấm biểu tượng bút chì', 'Click', 'Before:\n– Bản ghi đã Khóa thì nút không hiển thị.\nAfter:\n– Mở cửa sổ với dữ liệu hiện tại.'],
                        ['Bấm Lưu', 'Click', 'Before:\n– Máy chủ kiểm tra trạng thái trước tiên: bản ghi đang Khóa → từ chối, báo “Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.”\nDuring:\n– Kiểm tra như Thêm mới, bỏ qua trùng với chính bản ghi.\nAfter:\n– Ghi thay đổi, ghi lịch sử “Thay đổi thông tin” (đổi Trạng thái ghi dòng “Thay đổi trạng thái” riêng), báo “Cập nhật thành công”.']]},
            {'ten': 'Xóa quận/huyện', 'uc': 'uc_fr05',
             'qtc': 'Quy tắc Xóa, Thông báo, Quy định chung về danh mục và Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Xóa quận/huyện'],
                            ['Mô tả', 'Xóa hẳn một quận/huyện đang Hoạt động và chưa được dùng ở đâu (' + NOI_DUNG + ').'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Điều kiện ban đầu', 'Quận/huyện đang Hoạt động và chưa được dùng ở đâu.'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm biểu tượng thùng rác.\n2. Hệ thống hiện hộp “Xóa Quận/Huyện” nêu rõ tên bản ghi.\n3. Người dùng bấm Xóa.\n4. Hệ thống xóa hẳn bản ghi, báo “Xoá quận/huyện thành công”, nạp lại danh sách.'],
                            ['Dòng sự kiện phụ', '• Bấm Hủy → đóng hộp, không thay đổi.\n• Quận/huyện đã được dùng hoặc đang Khóa → nút Xóa KHÔNG hiển thị.\n• Vừa được dùng ở nơi khác trong lúc hộp đang mở → báo “Quận/huyện đang được sử dụng, không thể xóa.”\n• Vừa bị người khác khóa → báo “Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.”\n• Vừa bị người khác xóa → báo “Trạng thái đã bị thay đổi. Vui lòng load lại trang”.\n• Lỗi khác → báo “Xoá quận/huyện thất bại”.']],
             'menu_them': ' => Xóa {icon:btn_xoa}',
             'anh': [('delete', 'Hộp xác nhận xóa quận/huyện')],
             'events': [['Bấm biểu tượng thùng rác', 'Click', 'Before:\n– Chỉ hiện khi bản ghi đang Hoạt động và chưa được dùng.\nAfter:\n– Hiện hộp xác nhận kèm tên bản ghi.'],
                        ['Bấm Xóa', 'Click', 'During:\n– Máy chủ kiểm tra lại: bản ghi còn tồn tại, đang Hoạt động, chưa được dùng ở đâu; sai một điều kiện → báo lỗi tương ứng, không xóa.\nAfter:\n– Xóa hẳn bản ghi, nạp lại danh sách, báo thành công.'],
                        ['Bấm Hủy', 'Click', 'After:\n– Đóng hộp, không thay đổi.']]},
            {'ten': 'Khóa / Mở khóa quận/huyện', 'uc': 'uc_fr06',
             'qtc': 'Quy tắc Khóa/Mở khóa, Thông báo, Quy định chung về danh mục và Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Khóa / Mở khóa quận/huyện'],
                            ['Mô tả', 'Đổi trạng thái quận/huyện giữa Hoạt động và Khóa. Bản ghi đã Khóa vẫn nằm trong danh mục nhưng không chọn được ở màn khác; dữ liệu đang dùng vẫn giữ nguyên. Khóa được cả khi quận/huyện đang được dùng.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Điều kiện ban đầu', 'Bản ghi cần đổi trạng thái đang có trong danh sách.'],
                            ['Dòng sự kiện chính', '1. Người dùng chọn Khóa (hoặc Mở khóa) ở cột Hành động.\n2. Hệ thống hiện hộp xác nhận “Khóa Quận/Huyện” (hoặc “Mở khóa Quận/Huyện”) nêu rõ tên bản ghi.\n3. Người dùng xác nhận.\n4. Hệ thống đổi trạng thái, ghi lịch sử, báo “Khóa thành công” / “Mở khóa thành công”.'],
                            ['Dòng sự kiện phụ', '• Bấm Hủy → không thay đổi.\n• Sau khi Khóa, nút Sửa và Xóa biến mất; sau khi Mở khóa, nút Sửa hiện lại (Xóa hiện lại nếu chưa được dùng).\n• Bản ghi đã bị người khác đổi trạng thái hoặc đã bị xóa → báo “Trạng thái đã bị thay đổi. Vui lòng load lại trang”.']],
             'menu_them': ' => Khóa / Mở khóa',
             'anh': [('lock', 'Hộp xác nhận khóa quận/huyện'), ('unlock', 'Hộp xác nhận mở khóa quận/huyện'), ('rowmenu', 'Các nút ở cột Hành động')],
             'events': [['Chọn Khóa / Mở khóa', 'Click', 'After:\n– Hiện hộp xác nhận kèm tên bản ghi.'],
                        ['Xác nhận', 'Click', 'During:\n– Bản ghi không còn hoặc đã ở trạng thái đích → báo dữ liệu đã thay đổi, dừng, không ghi thêm lịch sử.\nAfter:\n– Đổi trạng thái, KHÔNG xóa dữ liệu, ghi lịch sử, cập nhật cột Trạng thái và các nút.'],
                        ['Bấm Hủy', 'Click', 'After:\n– Đóng hộp, không thay đổi.']]},
            {'ten': 'Xem lịch sử thay đổi',
             'qtc': 'Quy tắc ghi lịch sử và hiển thị lịch sử. Chỉ bổ sung thông tin riêng của Danh mục Quận/Huyện nếu có.',
             'gioi_thieu': [['Tên chức năng', 'Xem lịch sử thay đổi'],
                            ['Mô tả', 'Liệt kê các lần thay đổi của một quận/huyện, kèm giá trị cũ → mới, người thực hiện và thời điểm. Tỉnh/TP hiển thị bằng tên; Khóa / Mở khóa hiện là Thay đổi trạng thái.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Dòng sự kiện chính', '1. Người dùng chọn Lịch sử ở cột Hành động, hoặc mở cửa sổ Xem quận/huyện.\n2. Hệ thống mở cửa sổ “Lịch sử thay đổi: <tên>”, mốc mới nhất ở trên cùng.'],
                            ['Dòng sự kiện phụ', '• Bản ghi chưa từng thay đổi → “Chưa có lịch sử thao tác nào.”\n• Có bộ lọc theo loại hành động, người thực hiện, thời gian.']],
             'menu_them': ' => Lịch sử',
             'anh': [('history', 'Cửa sổ Lịch sử thay đổi của quận/huyện')]},
            {'ten': 'Import file quận/huyện', 'uc': 'uc_fr08',
             'qtc': 'Quy tắc Import file, Validate dữ liệu, Thông báo và Quy định chung về danh mục. Chỉ bổ sung mapping/validation riêng của Danh mục Quận/Huyện.',
             'gioi_thieu': [['Tên chức năng', 'Import file quận/huyện'],
                            ['Mô tả', 'Thêm nhiều quận/huyện cùng lúc từ file Excel mẫu, có bước Validate trước khi ghi.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Điều kiện ban đầu', 'Đang ở màn Danh mục Quận/Huyện và đã chuẩn bị file theo mẫu.'],
                            ['Dòng sự kiện chính', '1. Bấm Import Excel.\n2. Bấm Tải file mẫu (Mau_import_quan_huyen.xlsx), điền dữ liệu.\n3. Bấm Chọn file Excel rồi Load lên bảng.\n4. Bấm Validate; hệ thống kiểm tra từng dòng như quy tắc Thêm mới (mục 2.3), khóa dòng hợp lệ.\n5. Sửa dòng lỗi rồi Validate lại, hoặc bấm Bỏ dòng lỗi.\n6. Bấm Import; hệ thống ghi các dòng hợp lệ, báo “Import thành công N quận/huyện.”, đóng cửa sổ và nạp lại danh sách.'],
                            ['Dòng sự kiện phụ', '• File không phải .xlsx/.xls → “Vui lòng chọn file .xlsx hoặc .xls”.\n• Quá 500 dòng → “File có X dòng dữ liệu, vượt quá giới hạn 500 dòng mỗi lần import. Vui lòng tách file và import nhiều lần.”\n• Còn dòng lỗi → nút Import không bấm được.'],
                            ['Yêu cầu đặc biệt', 'Validate không ghi dữ liệu. Bản ghi import luôn ở trạng thái Hoạt động, người tạo là người thực hiện. Tỉnh/TP tra theo TÊN, không tự tạo tỉnh/TP mới.']],
             'menu_them': ' => Import Excel {icon:btn_import}',
             'ghi_chu_layout': 'Cửa sổ Import được mở ngay trên màn hình danh sách.',
             'anh': [('import_open', 'Cửa sổ Import quận/huyện khi vừa mở'), ('import_loaded', 'Dữ liệu đã được load lên bảng xem trước'),
                     ('import_validated', 'Kết quả Validate — mỗi dòng lỗi nêu rõ lý do')],
             'bang_them': [('Quy tắc kiểm tra riêng của file Import', [['Cột', 'Quy tắc / thông báo lỗi'],
                            ['Tên quận/huyện *', 'Bắt buộc (“Tên quận/huyện không được để trống”), tối đa 255 ký tự (“Tên quận/huyện tối đa 255 ký tự”), không trùng trong file (“Quận/huyện bị trùng với dòng N trong file”), không trùng hệ thống trong cùng tỉnh/TP, kể cả quận/huyện đang Khóa (“Quận/huyện này đã tồn tại trong tỉnh/TP đã chọn”).'],
                            ['Tỉnh/TP *', 'Bắt buộc (“Tỉnh/TP không được để trống”), chọn trong danh sách sổ xuống; ghi sai báo “Không tìm thấy tỉnh/TP: X”; tên có ở nhiều quốc gia báo “Tên tỉnh/TP "X" đang có ở nhiều quốc gia, không xác định được”.']], [1.2, 4])]},
            {'ten': 'Xuất danh sách ra Excel', 'uc': 'uc_fr09',
             'qtc': 'Quy tắc Excel và Cấu hình cột. Chỉ bổ sung danh sách trường được phép xuất riêng của Danh mục Quận/Huyện.',
             'gioi_thieu': [['Tên chức năng', 'Xuất danh sách quận/huyện ra Excel'],
                            ['Mô tả', 'Xuất kết quả đang lọc ra file Excel, cho phép chọn trường và thứ tự cột.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Dòng sự kiện chính', '1. Bấm Xuất Excel.\n2. Hệ thống mở cửa sổ “Chọn trường xuất file”, tích sẵn đúng các cột đang hiển thị trên bảng.\n3. Người dùng tích chọn và kéo ☰ để sắp thứ tự.\n4. Bấm Xuất file; hệ thống tải danh_muc_quan_huyen.xlsx theo đúng bộ lọc (kể cả Trạng thái) và thứ tự trường, báo “Xuất Excel thành công”.'],
                            ['Dòng sự kiện phụ', '• Bỏ chọn hết trường → nút Xuất file không bấm được.\n• Bấm Đóng → không xuất gì.'],
                            ['Yêu cầu đặc biệt', 'File chứa toàn bộ kết quả lọc (tối đa 10,000 dòng), không giới hạn ở trang đang xem. Chỉ xuất Excel. Trường Trạng thái ghi chữ “Hoạt động” / “Khóa”.']],
             'menu_them': ' => Xuất Excel {icon:btn_xuatexcel}',
             'anh': [('export', 'Cửa sổ Chọn trường xuất file')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
                    ['1', 'Danh sách trường', 'Checkbox chọn nhiều', 'Enable', 'Tích sẵn cột đang hiển thị', 'Tên quận/huyện, Tỉnh/TP, Quốc gia, Trạng thái, Người tạo, Ngày tạo, Người cập nhật, Ngày cập nhật. Kéo ☰ đổi thứ tự.'],
                    ['2', 'Nút Chọn tất cả / Bỏ chọn hết', 'Button', 'Enable', 'Hiển thị', 'Tích / bỏ tích toàn bộ.'],
                    ['3', 'Nút Xuất file', 'Button', 'Enable/Disable', 'Mờ khi chưa chọn trường', 'Sinh file và tải về.'],
                    ['4', 'Nút Đóng', 'Button', 'Enable', 'Hiển thị', 'Đóng cửa sổ.']],
             'ui_widths': [0.6, 1.5, 1, 0.8, 1.2, 2.6]},
            {'ten': 'Xem chi tiết quận/huyện', 'uc': 'uc_fr10',
             'qtc': 'Màn Xem chi tiết và Phân quyền.',
             'gioi_thieu': [['Tên chức năng', 'Xem chi tiết quận/huyện'],
                            ['Mô tả', 'Cửa sổ “Xem quận/huyện” hiển thị Tên quận/huyện, Tỉnh/TP, Trạng thái ở chế độ chỉ đọc, kèm khối Lịch sử. Quận/huyện đang Khóa vẫn xem được.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm tên quận/huyện ở danh sách.\n2. Hệ thống mở cửa sổ Xem, chỉ có nút Đóng.']],
             'anh': [('detail', 'Cửa sổ Xem quận/huyện ở chế độ chỉ đọc')]},
            {'ten': 'Tùy chỉnh cột hiển thị',
             'qtc': 'Tùy chỉnh cột.',
             'gioi_thieu': [['Tên chức năng', 'Tùy chỉnh cột hiển thị'],
                            ['Mô tả', 'Bật/tắt và sắp xếp thứ tự cột của bảng; cấu hình lưu riêng theo người dùng.'],
                            ['Yêu cầu đặc biệt', 'Cột STT, Tên quận/huyện, Hành động bị khóa. Mặc định ẩn: Quốc gia, Người cập nhật, Ngày cập nhật.']],
             'menu_them': ' => Cấu hình cột {icon:btn_cauhinhcot}',
             'anh': [('colcfg', 'Cửa sổ Tuỳ chỉnh cột')]},
        ],
        'quy_tac': [
            ('BR-01', 'Ràng buộc trùng tên',
             [
              'Tên quận/huyện không được trùng trong cùng một Tỉnh/TP, kể cả quận/huyện đang Khóa; cùng tên ở tỉnh/TP khác vẫn hợp lệ.',
              'Quận/huyện đã bị xóa không còn trong hệ thống nên tên đó dùng lại được.',
              'Thông báo khi trùng: “Tên quận/huyện này đã tồn tại trong tỉnh/TP”; Import Excel báo “Quận/huyện này đã tồn tại trong tỉnh/TP đã chọn” hoặc “Quận/huyện bị trùng với dòng N trong file”.',
             ],
             ['Thêm mới quận/huyện', 'Chỉnh sửa quận/huyện', 'Import file quận/huyện']),
            ('BR-02', 'Mối quan hệ với các cấp địa chỉ khác',
             [
              'Mỗi quận/huyện thuộc đúng một tỉnh/TP; ô chọn chỉ liệt kê tỉnh/TP đang Hoạt động, quận/huyện đang dùng tỉnh/TP đã khóa vẫn giữ và hiển thị đúng tên kèm 🔒.',
              'Việt Nam không dùng cấp Quận/Huyện; cấp này chỉ dùng cho quốc gia khác, làm cấp trung gian để chọn Phường/Xã ở màn Đường/Phố.',
             ],
             ['Thêm mới quận/huyện', 'Chỉnh sửa quận/huyện', 'Thêm mới / Chỉnh sửa đường/phố']),
            ('BR-03', 'Điều kiện xóa',
             [
              'Chỉ xóa được quận/huyện đang Hoạt động và chưa được dùng ở đâu; ngược lại nút Xóa bị ẩn và máy chủ cũng từ chối.',
              'Được coi là đã dùng khi có ở một trong các nơi: ' + NOI_DUNG + '. Máy chủ báo “Quận/huyện đang được sử dụng, không thể xóa.”',
              'Quận/huyện đã được dùng thì dùng Khóa thay cho Xóa.',
              'Xóa là xóa hẳn bản ghi khỏi hệ thống, không khôi phục được.',
             ],
             ['Xóa quận/huyện']),
            ('BR-04', 'Quận/huyện đang Khóa',
             [
              'Không sửa, không xóa được; phải Mở khóa trước. Trên danh sách chỉ còn nút Mở khóa và Lịch sử.',
              'Máy chủ chặn sửa/xóa bản ghi đang Khóa: “Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.”',
              'Khóa được cả khi quận/huyện đang được dùng. Quận/huyện Khóa không còn chọn được ở các màn khác; bản ghi đang dùng vẫn hiển thị đúng tên kèm 🔒.',
             ],
             ['Chỉnh sửa quận/huyện', 'Xóa quận/huyện', 'Khóa / Mở khóa quận/huyện']),
            ('BR-05', 'Thao tác đồng thời',
             [
              'Hai người cùng Khóa / Mở khóa / Xóa một bản ghi: người bấm sau nhận thông báo “Trạng thái đã bị thay đổi. Vui lòng load lại trang”, thao tác không được thực hiện lại và không ghi thêm lịch sử.',
             ],
             ['Xóa quận/huyện', 'Khóa / Mở khóa quận/huyện']),
            ('BR-06', 'Giới hạn Import',
             [
              'Mỗi lần nhập tối đa 500 dòng; phải Validate trước, bước Validate không ghi dữ liệu.',
              'Tỉnh/TP tra theo tên, không tự tạo mới; tên tỉnh/TP có ở nhiều quốc gia thì báo “Tên tỉnh/TP … đang có ở nhiều quốc gia, không xác định được”.',
              'Quận/huyện nhập từ Excel luôn ở trạng thái Hoạt động.',
             ],
             ['Import file quận/huyện']),
            ('BR-07', 'Ghi lịch sử thay đổi',
             [
              'Mọi thao tác Tạo mới, Thay đổi thông tin, Khóa, Mở khóa đều ghi lịch sử kèm người thực hiện.',
              'Đổi Trạng thái ngay trong cửa sổ Sửa được ghi thành dòng “Thay đổi trạng thái” riêng.',
             ],
             ['Xem lịch sử thay đổi']),
        ],
    },
}

# ---- Lỗi code phát hiện khi rà (KHÔNG sửa code, báo user) ----
CFG['loi_code'] = [
    'Import: số dòng trong câu “Quận/huyện bị trùng với dòng N trong file” không khớp chỗ nào người dùng nhìn thấy (DistrictService::validateRows dùng $index + 2): cột # của bảng xem trước đánh $index + 1 (V2BaseImportModal.vue), còn trong file Excel dòng dữ liệu đầu là hàng 3.',
    'Import tra Tỉnh/TP theo tên trên TOÀN BỘ bảng provinces, kể cả tỉnh/TP đã Khóa (DistrictService::importSnapshot) — gõ tay tên một tỉnh/TP đã khóa vào file vẫn Validate hợp lệ và tạo được quận/huyện thuộc tỉnh đã khóa, trong khi cửa sổ Tạo mới chỉ cho chọn tỉnh/TP đang Hoạt động.',
]

# ---- Sửa tab testcase "18. DM quận huyện" (dump ref/testcase_tab.txt 28/09/2026) ----
# Lượt 25/09 (nhóm VII Xuất Excel, VIII Import) ĐÃ chạy lên sheet. Lượt này (28/09): sửa case Xóa / Trạng thái /
# ràng buộc + chèn case mới vào cuối nhóm I, II, III, IV, V, VII + nhóm mới KHÓA / MỞ KHÓA sau nhóm cuối (XXII).
_TC_KHOA = [
    ('Hộp xác nhận Khóa nêu đúng tên bản ghi', 'P0', 'Quận/huyện X đang Hoạt động.',
     '1. Ở cột Hành động dòng X, bấm Khóa (trong nút ba chấm "Hành động khác" nếu dòng có nhiều nút)\n2. Đọc nội dung hộp xác nhận',
     '', '- Hộp có tiêu đề "Khóa Quận/Huyện", câu "Bạn có chắc muốn khóa quận/huyện "X"?"\n- Có hai nút Khóa và Hủy'),
    ('Khóa thành công', 'P0', 'Đang mở hộp xác nhận khóa quận/huyện X.',
     '1. Bấm Khóa\n2. Quan sát dòng X trên bảng', '',
     '- Báo "Khóa thành công"\n- X VẪN nằm trong danh sách, cột Trạng thái đổi thành Khóa\n- Cột Hành động của X chỉ còn Mở khóa và Lịch sử (không còn Sửa, Xóa)'),
    ('Bấm Hủy ở hộp Khóa thì không đổi', 'P1', 'Đang mở hộp xác nhận khóa quận/huyện X.',
     '1. Bấm Hủy\n2. Xem lại dòng X', '', '- Hộp đóng, X vẫn ở trạng thái Hoạt động\n- Không có thông báo thành công nào'),
    ('Khóa được cả quận/huyện đang được dùng', 'P0',
     'Quận/huyện X đang Hoạt động và đang được dùng (vd là địa chỉ của một khách hàng hoặc có phường/xã trực thuộc), không có nút Xóa.',
     '1. Bấm Khóa ở dòng X và xác nhận\n2. Mở lại khách hàng / dữ liệu đang dùng X', '',
     '- Khóa thành công, không bị chặn vì đang được dùng\n- Dữ liệu đang dùng X vẫn hiển thị đúng tên X (kèm biểu tượng ổ khoá ở ô chọn), không bị trống'),
    ('Hộp xác nhận Mở khóa và Mở khóa thành công', 'P0', 'Quận/huyện X đang Khóa, chưa được dùng ở đâu.',
     '1. Bấm Mở khóa ở dòng X\n2. Đọc hộp xác nhận\n3. Bấm Mở khóa', '',
     '- Hộp có tiêu đề "Mở khóa Quận/Huyện", câu "Bạn có chắc muốn mở khóa quận/huyện "X"?", hai nút Mở khóa và Hủy\n- Báo "Mở khóa thành công", cột Trạng thái đổi thành Hoạt động\n- Nút Sửa và Xóa hiện lại'),
    ('Bấm Hủy ở hộp Mở khóa thì không đổi', 'P1', 'Đang mở hộp xác nhận mở khóa quận/huyện X.',
     '1. Bấm Hủy\n2. Xem lại dòng X', '', '- Hộp đóng, X vẫn ở trạng thái Khóa'),
    ('Hai người cùng Khóa một quận/huyện', 'P1', 'Hai tài khoản A, B cùng mở màn Danh mục Quận/Huyện; X đang Hoạt động.',
     '1. A khóa X thành công\n2. B (chưa tải lại trang) bấm Khóa X và xác nhận\n3. Mở Lịch sử của X', '',
     '- B nhận thông báo "Trạng thái đã bị thay đổi. Vui lòng load lại trang"\n- Lịch sử của X chỉ có MỘT dòng khóa (của A), không bị ghi trùng'),
    ('Hai người cùng Mở khóa một quận/huyện', 'P2', 'Hai tài khoản A, B cùng mở màn; X đang Khóa.',
     '1. A mở khóa X thành công\n2. B (chưa tải lại trang) bấm Mở khóa X và xác nhận', '',
     '- B nhận thông báo "Trạng thái đã bị thay đổi. Vui lòng load lại trang"\n- X ở trạng thái Hoạt động'),
    ('Xem chi tiết quận/huyện đang Khóa', 'P2', 'Quận/huyện X đang Khóa.',
     '1. Bấm vào tên X trên danh sách', '',
     '- Mở cửa sổ "Xem quận/huyện", ô Trạng thái hiện Khóa, mọi ô chỉ đọc\n- Khối Lịch sử ở cuối có dòng Thay đổi trạng thái sang Khóa'),
]

CFG['tc'] = {
    'tab': '18. DM quận huyện',
    'hdr_row': 65,            # "VI. LỊCH SỬ THAY ĐỔI"
    'edits': [
        # --- Khối mô tả đầu tab ---
        ('B2', 'Quản lý danh mục quận/huyện dùng chung cho toàn hệ thống. Màn hình cho phép tra cứu, tìm kiếm, thêm mới, chỉnh sửa, xóa, khóa/mở khóa và xem lịch sử thay đổi. Dữ liệu của màn này là nguồn cho ô địa chỉ ở mọi màn nghiệp vụ khác.'),
        ('B3', '- Hiện TOÀN BỘ quận/huyện: cả Hoạt động lẫn Khóa. Cột Trạng thái hiện nhãn Hoạt động / Khóa.\n- Bộ lọc Trạng thái để trống = hiện cả hai trạng thái; chọn Hoạt động hoặc Khóa để thu hẹp.'),
        ('B4', '- Bản ghi đã bị Xóa không còn xuất hiện ở bất kỳ trạng thái nào: xóa là xóa HẲN khỏi hệ thống.\n- Chỉ xóa được quận/huyện đang Hoạt động và chưa được dùng ở đâu (Phường/Xã, hồ sơ nhân sự, Khách hàng, Công ty, Nhà cung cấp, Địa điểm giao hàng); quận/huyện đã được dùng thì chỉ Khóa được.\n- Không có bản ghi nào bị ẩn vì lý do phân quyền, do màn hình chưa gắn quyền.'),
        ('B7', '- Mỗi quận/huyện chỉ hiện MỘT dòng.\n- Tên quận/huyện là duy nhất trong cùng một Tỉnh/TP, tính cả quận/huyện đang Khóa — trùng sẽ bị chặn khi lưu.\n- Khi sửa, bản ghi đang sửa được loại khỏi phép kiểm tra trùng: giữ nguyên tên của chính nó thì lưu bình thường.'),
        ('B8', 'Màn hình này KHÔNG khai báo quyền nào. Mọi người dùng đã đăng nhập đều mở được màn hình và thực hiện được đầy đủ Thêm mới, Chỉnh sửa, Xóa, Khóa, Mở khóa, Import Excel và Xuất Excel.\n Phía máy chủ cũng không kiểm tra quyền, nên gọi thẳng chức năng mà bỏ qua giao diện vẫn ghi được dữ liệu. Đây là hiện trạng của mã nguồn, đã được ghi nhận để bộ phận quản trị cân nhắc bổ sung quyền.'),
        ('B10', 'Các bẫy dễ sai nhất của màn này, QA đọc trước khi test:\n- Màn hình KHÔNG gắn quyền. Mọi tài khoản đăng nhập đều thêm, sửa, xóa, khóa được. Không có trường hợp test "thiếu quyền thì nút bị ẩn" như các màn danh mục khác.\n- Trùng tên xét trong cùng một Tỉnh/TP, không phải toàn hệ thống, và tính cả quận/huyện đang Khóa.\n- Cửa sổ thêm mới có 3 nút: Lưu, Lưu và tiếp tục, Đóng. Nút "Lưu và tiếp tục" GIỮ cửa sổ mở và xóa trắng các ô để nhập tiếp bản ghi kế theo.\n- Nút KHÔNG dùng được thì ẨN hẳn, không phải nút xám: quận/huyện đang Khóa chỉ còn Mở khóa và Lịch sử; quận/huyện đã được dùng ở nơi khác không có nút Xóa.\n- Dòng có từ 4 nút trở lên thì 2 nút đầu hiện thẳng, còn lại nằm trong nút ba chấm "Hành động khác".\n- Cửa sổ Lịch sử hiển thị TÊN Tỉnh/TP ở các trường tham chiếu.'),
        # --- I. Hiển thị: cột Trạng thái ---
        ('I20', '- Có các cột: STT, Tên quận/huyện, Tỉnh/TP, Người tạo, Ngày tạo, Trạng thái, Hành động\n- Các cột Quốc gia, Người cập nhật, Ngày cập nhật mặc định ẩn, bật lại được bằng biểu tượng Cấu hình cột hiển thị'),
        # --- III. Thêm mới: ô Trạng thái ---
        ('I39', '- Cửa sổ mở với tiêu đề "Tạo quận/huyện"\n- Ô Tên quận/huyện và Tỉnh/TP để trống; ô Trạng thái mặc định Hoạt động\n- Có đủ 3 nút: Lưu, Lưu và tiếp tục, Đóng'),
        # --- V. Xóa: xóa hẳn + điều kiện chưa dùng ---
        ('F62', 'Quận/huyện X đang Hoạt động và chưa được dùng ở đâu (không có Phường/Xã trực thuộc, chưa được chọn làm địa chỉ ở hồ sơ nhân sự, Khách hàng, Công ty, Nhà cung cấp, Địa điểm giao hàng).'),
        ('I62', '- Thông báo "Xoá quận/huyện thành công"\n- Bản ghi X biến mất khỏi danh sách'),
        ('D63', 'Quận/huyện đang được dùng thì không có nút Xóa'),
        ('F63', 'Quận/huyện X đang Hoạt động và đang được dùng ở ít nhất một nơi: có Phường/Xã trực thuộc, hoặc là địa chỉ thường trú/tạm trú trong hồ sơ nhân sự, địa chỉ của Khách hàng, Công ty, Nhà cung cấp, Địa điểm giao hàng.'),
        ('G63', '1. Tìm X trên danh sách\n2. Quan sát cột Hành động của dòng X'),
        ('I63', '- KHÔNG có nút Xóa (ẩn hẳn, không phải nút xám)\n- Vẫn còn các nút Sửa, Khóa, Lịch sử\n- Bản ghi X vẫn còn nguyên trong danh sách'),
        ('D64', 'Xóa là xóa hẳn khỏi danh mục'),
        ('F64', 'Vừa xóa thành công quận/huyện X (trước đó chưa được dùng ở đâu).'),
        ('G64', '1. Bỏ trống ô Trạng thái, tìm theo tên X\n2. Lọc Trạng thái = Khóa, tìm lại X\n3. Bấm Tạo mới, nhập lại tên X với đúng Tỉnh/TP cũ, bấm Lưu'),
        ('I64', '- Không tìm thấy X ở cả hai trạng thái (đã xóa hẳn, không phải chuyển sang Khóa)\n- Tạo lại quận/huyện cùng tên X trong cùng Tỉnh/TP thì lưu thành công, không bị báo trùng'),
        # --- VII. Xuất Excel: thêm trường Trạng thái ---
        ('I83', '- Mở cửa sổ “Chọn trường xuất file”\n- Có đủ các trường: Tên quận/huyện, Tỉnh/TP, Quốc gia, Trạng thái, Người tạo, Ngày tạo, Người cập nhật, Ngày cập nhật\n- Tích sẵn đúng các cột đang hiển thị trên bảng\n- Dòng cuối ghi “Đang chọn a/b trường”'),
        # --- XXII. Ràng buộc: nhóm đang chép nhầm từ tab Quốc gia -> viết lại cho quận/huyện (Xóa / Khóa) ---
        ('A114', 'Danh mục Quận/Huyện'),
        ('D114', 'Quận/huyện chưa được dùng ở đâu thì xoá được'),
        ('F114', 'Quận/huyện N vừa tạo, đang Hoạt động, chưa có Phường/Xã trực thuộc và chưa được chọn ở hồ sơ nhân sự, Khách hàng, Công ty, Nhà cung cấp, Địa điểm giao hàng.'),
        ('G114', '1. Quan sát cột Hành động của dòng N.\n2. Bấm Xóa và xác nhận.'),
        ('H114', 'Quận/huyện: N'),
        ('I114', '- Dòng N có nút Xóa.\n- Xoá thành công, bản ghi biến mất khỏi danh sách.'),
        ('D115', 'Chọn quận/huyện làm địa chỉ ở màn khác thì nút Xóa biến mất'),
        ('F115', 'Quận/huyện N (thuộc một Tỉnh/TP ở nước ngoài) chưa được dùng, đang hiện nút Xóa.'),
        ('G115', '1. Sang màn Khách hàng, sửa một khách hàng có địa chỉ ở nước ngoài, chọn Quận/Huyện = N rồi lưu.\n2. Quay lại màn Danh mục Quận/Huyện và tải lại danh sách.\n3. Quan sát dòng N.'),
        ('H115', 'Khách hàng: KH1, địa chỉ Quận/Huyện = N'),
        ('I115', '- Dòng N KHÔNG còn nút Xóa (ẩn hẳn, không phải nút xám).\n- Các nút Sửa, Khóa, Lịch sử vẫn còn.'),
        ('D116', 'Khóa quận/huyện thì các màn khác không chọn được nữa'),
        ('F116', 'Quận/huyện N (thuộc Tỉnh/TP T ở nước ngoài) đang Hoạt động và đang xuất hiện ở ô chọn Quận/Huyện/Thị xã của màn Danh mục Đường/Phố.'),
        ('G116', '1. Khóa quận/huyện N.\n2. Mở màn Danh mục Đường/Phố, bấm Tạo mới, chọn quốc gia và Tỉnh/TP T, mở ô chọn Quận/Huyện/Thị xã.'),
        ('H116', 'Quận/huyện: N (Khóa)'),
        ('I116', '- Danh sách chọn KHÔNG còn quận/huyện N.\n- Không cần tải lại trang vẫn thấy thay đổi.'),
        ('D117', 'Dữ liệu đang gắn quận/huyện đã khóa vẫn giữ nguyên'),
        ('F117', 'Khách hàng KH1 đang có địa chỉ Quận/Huyện = N; quận/huyện N vừa bị Khóa.'),
        ('G117', '1. Mở màn Khách hàng, xem KH1.\n2. Mở màn sửa KH1, xem ô Quận/Huyện, rồi bấm Lưu.'),
        ('H117', 'Khách hàng: KH1'),
        ('I117', '- KH1 vẫn hiện đúng tên quận/huyện N, không bị trống.\n- Trong màn sửa, ô Quận/Huyện vẫn giữ giá trị N và có biểu tượng ổ khoá trước tên.\n- Lưu KH1 lại không làm mất quận/huyện đã gắn.'),
        ('D118', 'Mở khóa quận/huyện thì chọn lại được'),
        ('F118', 'Quận/huyện N đang ở trạng thái Khóa.'),
        ('G118', '1. Mở khóa quận/huyện N.\n2. Mở màn Danh mục Đường/Phố, bấm Tạo mới, chọn Tỉnh/TP của N, mở ô chọn Quận/Huyện/Thị xã.'),
        ('H118', 'Quận/huyện: N (Hoạt động)'),
        ('I118', '- Quận/huyện N xuất hiện lại trong danh sách chọn, không còn biểu tượng ổ khoá.'),
        ('D121', 'Xoá quận/huyện rồi kiểm tra các màn liên quan'),
        ('F121', 'Quận/huyện P đang Hoạt động, chưa được dùng ở đâu.'),
        ('G121', '1. Xoá quận/huyện P.\n2. Mở màn Danh mục Phường/Xã và màn Danh mục Đường/Phố (Tạo mới, chọn Tỉnh/TP của P).'),
        ('H121', 'Quận/huyện: P'),
        ('I121', '- Hai màn mở bình thường, không báo lỗi.\n- Ô chọn Quận/Huyện/Thị xã không còn P.'),
    ],
    'clear_k': [20, 39, 62, 63, 64, 83, 114, 115, 116, 117, 118, 121],
    'blocks': [
        # I. HIỂN THỊ — cuối nhóm (TC_01.009 ở R27)
        {'after': 27, 'merge_from': 19, 'cases': [
            ('TC_01.010', 'Danh sách hiện cả quận/huyện đang Khóa', 'P0', 'Danh mục có ít nhất 1 quận/huyện đang Khóa.',
             '1. Mở màn hình, chưa chọn bộ lọc Trạng thái\n2. Quan sát cột Trạng thái và tổng số bản ghi', '',
             '- Danh sách hiện cả quận/huyện Hoạt động lẫn Khóa\n- Cột Trạng thái hiện nhãn "Hoạt động" hoặc "Khóa"\n- Tổng số bản ghi ở cuối bảng tính cả bản ghi Khóa'),
        ]},
        # II. TÌM KIẾM & LỌC — cuối nhóm (TC_02.009 ở R37)
        {'after': 37, 'merge_from': 29, 'cases': [
            ('TC_02.010', 'Lọc theo Trạng thái = Khóa', 'P0', 'Có cả quận/huyện Hoạt động lẫn Khóa.',
             '1. Chọn ô Trạng thái = Khóa\n2. Quan sát bảng', 'Trạng thái: Khóa',
             '- Lọc ngay khi chọn, bảng về trang 1\n- Mọi dòng đều có Trạng thái Khóa\n- Tổng số bản ghi đổi theo kết quả'),
            ('TC_02.011', 'Lọc theo Trạng thái = Hoạt động', 'P1', 'Có cả quận/huyện Hoạt động lẫn Khóa.',
             '1. Chọn ô Trạng thái = Hoạt động\n2. Quan sát bảng', 'Trạng thái: Hoạt động',
             '- Mọi dòng đều có Trạng thái Hoạt động, không còn dòng Khóa'),
            ('TC_02.012', 'Bỏ chọn Trạng thái thì hiện cả hai', 'P2', 'Đang lọc Trạng thái = Khóa.',
             '1. Bấm dấu x ở ô Trạng thái để xoá lựa chọn\n2. Quan sát bảng', '',
             '- Ô Trạng thái trống\n- Bảng hiện lại cả quận/huyện Hoạt động lẫn Khóa'),
        ]},
        # III. THÊM MỚI — cuối nhóm (TC_03.009 ở R47)
        {'after': 47, 'merge_from': 39, 'cases': [
            ('TC_03.010', 'Tạo mới ở trạng thái Khóa', 'P1', 'Đang ở cửa sổ thêm mới.',
             '1. Nhập Tên quận/huyện, chọn Tỉnh/TP\n2. Đổi ô Trạng thái sang Khóa\n3. Bấm Lưu', 'Trạng thái: Khóa',
             '- Báo "Thêm mới thành công"\n- Bản ghi mới hiện trong danh sách với Trạng thái Khóa\n- Cột Hành động của bản ghi chỉ có Mở khóa và Lịch sử'),
            ('TC_03.011', 'Trùng tên với quận/huyện đang Khóa bị chặn', 'P1', 'Tỉnh/TP T có quận/huyện Y đang ở trạng thái Khóa.',
             '1. Bấm Tạo mới\n2. Nhập tên Y, chọn Tỉnh/TP T\n3. Bấm Lưu', 'Tên: Y; Tỉnh/TP: T',
             '- Báo lỗi đỏ dưới ô Tên quận/huyện: "Tên quận/huyện này đã tồn tại trong tỉnh/TP"\n- Không tạo bản ghi mới'),
            ('TC_03.012', 'Ô Trạng thái chỉ có 2 giá trị, không xoá trống được', 'P2', 'Đang ở cửa sổ thêm mới.',
             '1. Mở ô Trạng thái\n2. Tìm nút x xoá giá trị', '',
             '- Ô chỉ có 2 giá trị: Hoạt động, Khóa\n- Không có nút x, ô luôn có giá trị'),
        ]},
        # IV. CHỈNH SỬA — cuối nhóm (TC_04.010 ở R58)
        {'after': 58, 'merge_from': 49, 'cases': [
            ('TC_04.011', 'Quận/huyện đang Khóa không có nút Sửa', 'P0', 'Quận/huyện X đang Khóa.',
             '1. Tìm X trên danh sách\n2. Quan sát cột Hành động', '',
             '- Không có nút Sửa và nút Xóa (ẩn hẳn, không phải nút xám)\n- Chỉ còn Mở khóa và Lịch sử'),
            ('TC_04.012', 'Khóa ngay trong cửa sổ Sửa', 'P1', 'Quận/huyện X đang Hoạt động.',
             '1. Mở cửa sổ Sửa X\n2. Đổi ô Trạng thái sang Khóa\n3. Bấm Lưu\n4. Mở Lịch sử của X', 'Trạng thái: Khóa',
             '- Báo "Cập nhật thành công", cột Trạng thái của X đổi thành Khóa\n- Lịch sử có dòng "Thay đổi trạng thái" ghi giá trị cũ "Hoạt động", giá trị mới "Khóa"'),
            ('TC_04.013', 'Người khác khóa trong lúc đang sửa', 'P1', 'Hai tài khoản A, B cùng mở màn. A đang mở cửa sổ Sửa quận/huyện X.',
             '1. B khóa X\n2. A đổi tên X và bấm Lưu', '',
             '- A nhận thông báo "Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật."\n- Tên X không đổi'),
        ]},
        # V. XÓA — cuối nhóm (TC_05.005 ở R64)
        {'after': 64, 'merge_from': 60, 'cases': [
            ('TC_05.006', 'Mỗi nơi sử dụng đều làm ẩn nút Xóa', 'P1', 'Chuẩn bị 6 quận/huyện đang Hoạt động, mỗi quận/huyện được dùng ở đúng một nơi như Test data.',
             '1. Tải lại màn Danh mục Quận/Huyện\n2. Quan sát cột Hành động của từng quận/huyện',
             '1. Có phường/xã trực thuộc\n2. Địa chỉ thường trú hoặc tạm trú trong hồ sơ nhân sự\n3. Địa chỉ Khách hàng\n4. Địa chỉ Công ty\n5. Địa chỉ Nhà cung cấp\n6. Địa điểm giao hàng',
             '- Cả 6 quận/huyện đều KHÔNG có nút Xóa\n- Vẫn Khóa được bình thường'),
            ('TC_05.007', 'Quận/huyện được dùng trong lúc đang mở hộp xác nhận Xóa', 'P1', 'Quận/huyện X chưa được dùng, đang hiện nút Xóa.',
             '1. Bấm Xóa ở dòng X, để hộp xác nhận mở\n2. Ở tab khác, chọn X làm địa chỉ cho một khách hàng rồi lưu\n3. Quay lại, bấm Xóa xác nhận', '',
             '- Báo "Quận/huyện đang được sử dụng, không thể xóa."\n- X vẫn còn trong danh sách'),
            ('TC_05.008', 'Quận/huyện bị khóa trong lúc đang mở hộp xác nhận Xóa', 'P1', 'Hai tài khoản A, B. X đang Hoạt động, chưa được dùng.',
             '1. A bấm Xóa ở dòng X, để hộp xác nhận mở\n2. B khóa X\n3. A bấm Xóa xác nhận', '',
             '- A nhận thông báo "Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật."\n- X vẫn còn, ở trạng thái Khóa sau khi tải lại'),
            ('TC_05.009', 'Hai người cùng xóa một quận/huyện', 'P2', 'Hai tài khoản A, B cùng mở màn. X đang Hoạt động, chưa được dùng.',
             '1. A xóa X thành công\n2. B (chưa tải lại trang) bấm Xóa X và xác nhận', '',
             '- B nhận thông báo "Trạng thái đã bị thay đổi. Vui lòng load lại trang"'),
        ]},
        # VII. XUẤT EXCEL — cuối nhóm (TC_07.009 ở R91)
        {'after': 91, 'merge_from': 83, 'cases': [
            ('TC_07.010', 'Xuất theo bộ lọc Trạng thái', 'P1', 'Có ít nhất 1 quận/huyện đang Khóa.',
             '1. Lọc Trạng thái = Khóa\n2. Bấm Xuất Excel, giữ tích trường Trạng thái\n3. Bấm Xuất file, mở file\n4. Bỏ lọc Trạng thái, xuất lại', '',
             '- Lần 1: file chỉ chứa các quận/huyện đang Khóa, cột Trạng thái ghi "Khóa"\n- Lần 2: file có cả hai trạng thái, cột Trạng thái ghi đúng "Hoạt động" / "Khóa" theo từng dòng'),
        ]},
        # Nhóm MỚI sau case cuối của nhóm cuối cùng (XXII — TC_12.009 ở R121)
        {'after': 121, 'groups': [('XXIII', 'KHÓA / MỞ KHÓA (bổ sung 28/09/2026)', 13, _TC_KHOA)]},
    ],
}

CFG['tc_ngoai_pham_vi'] = [
    'R19 (TC_01.001): cột Module ghi “Danh mục Đường/Phố” — sai tên màn (phải là Danh mục Quận/Huyện); bước ghi “Danh mục chung → Địa lý”, menu thật là “Danh mục → Địa lý → Quận/Huyện”.',
    'R25, R27: bước ghi “cột Tên đường/phố” — phải là “Tên quận/huyện”. R26: tên case “Sắp xếp theo Ngày cập nhật” nhưng bước bấm cột Ngày tạo.',
    'R56–R58: tên hộp thoại ghi “Thông tin chưa được lưu”, chữ thật là “Thông tin chưa lưu”.',
    'R80 (TC_06.015): tiền điều kiện ghi “import một quốc gia Z” — phải là quận/huyện Z.',
    'R119 (TC_12.007), R120 (TC_12.008): vẫn là nội dung chép từ tab Quốc gia (đổi tên / đổi MÃ quốc gia). Quận/huyện không có mã → R120 nên bỏ; R119 nên viết lại “Đổi tên quận/huyện thì màn Đường/Phố, Khách hàng hiện tên mới”.',
    'R117: ô N (Ghi chú) còn ghi chú cũ của tab Quốc gia (“chỉ hiện quốc gia ở màn danh mục…”) và L117 = Passed — script chỉ xoá ô K, cần xoá tay ô L/N của hàng này sau khi case được viết lại.',
    'Nhóm XXII đánh số TC_12.xxx (chép từ tab khác), nhóm Khóa/Mở khóa mới nối tiếp thành XXIII / TC_13.xxx cho đúng quy tắc “nối tiếp nhóm cuối”.',
]


# ---- Bổ sung 28/09/2026: “Mô tả chi tiết giao diện” + “Danh sách event và xử lý event” cho SRS ----
# Tester báo thiếu 2 mục này ở các chức năng sau Thêm mới. Nguồn: code gop_db 28/09/2026 (FE pages/human/districts, component
# dùng chung V2BaseImportModal / export-fields-modal / column-customization-modal / CatalogHistoryModal; BE Modules/Human).
_FR = {f['ten']: f for f in CFG['srs']['fr']}
_FR['Chỉnh sửa quận/huyện'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Phạm vi', 'Bắt buộc', 'Giá trị ban đầu', 'Mô tả'],
        ['1', 'Tên quận/huyện', 'Textbox', 'Enable', '1–255 ký tự', 'Có', 'Dữ liệu hiện tại', 'Không trùng trong cùng Tỉnh/TP (tính cả bản ghi Khóa), bỏ qua chính bản ghi đang sửa. Bỏ trống “Bắt buộc phải nhập”; trùng “Tên quận/huyện này đã tồn tại trong tỉnh/TP”; quá dài “Vui lòng nhập tối đa 255 ký tự.”'],
        ['2', 'Tỉnh/TP', 'Dropdown', 'Enable', 'Tỉnh/TP đang Hoạt động', 'Có', 'Dữ liệu hiện tại', 'Tỉnh/TP đã khóa mà bản ghi đang dùng vẫn hiện đúng tên kèm 🔒. Bỏ trống “Bắt buộc phải nhập”.'],
        ['3', 'Trạng thái', 'Dropdown', 'Enable', 'Hoạt động / Khóa', 'Không', 'Dữ liệu hiện tại', 'Luôn có giá trị. Chọn Khóa rồi Lưu cũng là khóa quận/huyện; lịch sử ghi dòng “Thay đổi trạng thái” riêng.'],
        ['4', 'Nút Lưu', 'Button', 'Enable', '–', '–', 'Hiển thị', 'Ghi thay đổi rồi đóng cửa sổ.'],
        ['5', 'Nút Đóng / biểu tượng X', 'Button', 'Enable', '–', '–', 'Hiển thị', 'Đóng cửa sổ, không ghi gì. Đã sửa dở thì hỏi “Thông tin chưa lưu” — “Bạn có thông tin chưa lưu. Có chắc chắn muốn thoát?” (Thoát / Ở lại). Chế độ Sửa không có nút “Lưu và tiếp tục”.'],
        ['6', 'Thông báo lỗi', 'Label', 'Hiển thị khi lỗi', '–', '–', 'Ẩn', 'Chữ đỏ ngay dưới ô bị lỗi, kèm thông báo chung “Vui lòng kiểm tra lại dữ liệu nhập”.'],
    ],
    'ui_widths': [0.5, 1.2, 0.8, 0.6, 1.1, 0.6, 0.8, 1.9],
    'events': [
        ['Bấm biểu tượng bút chì (Sửa)', 'Click', 'Before:\n– Nút chỉ hiển thị khi bản ghi đang Hoạt động; bản ghi Khóa không có nút Sửa.\nAfter:\n– Mở cửa sổ “Sửa quận/huyện” với dữ liệu hiện tại đã điền sẵn.'],
        ['Bấm Lưu', 'Click', 'Before:\n– Máy chủ kiểm tra trạng thái TRƯỚC khi kiểm tra dữ liệu: bản ghi đang Khóa (vừa bị người khác khóa) → từ chối, báo “Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.”\nDuring:\n– Tên quận/huyện, Tỉnh/TP để trống → “Bắt buộc phải nhập”; quá 255 ký tự → “Vui lòng nhập tối đa 255 ký tự.”\n– Trùng tên với quận/huyện khác trong cùng Tỉnh/TP → “Tên quận/huyện này đã tồn tại trong tỉnh/TP”.\n– Bỏ qua kiểm tra trùng đối với chính bản ghi đang sửa.\n– Có lỗi → báo đỏ dưới ô, cửa sổ KHÔNG đóng, không thực hiện bước After.\nAfter:\n– Ghi thay đổi, ghi Người cập nhật và một dòng lịch sử “Thay đổi thông tin” nêu giá trị cũ → mới (đổi Trạng thái ghi dòng “Thay đổi trạng thái” riêng).\n– Đóng cửa sổ, nạp lại danh sách, báo “Cập nhật thành công”.'],
        ['Bấm Đóng / biểu tượng X / bấm ra ngoài cửa sổ', 'Click', 'After:\n– Chưa sửa gì → đóng cửa sổ.\n– Đã sửa → hỏi “Thông tin chưa lưu” — “Bạn có thông tin chưa lưu. Có chắc chắn muốn thoát?” (Thoát / Ở lại); chọn Thoát thì đóng, không ghi; chọn Ở lại thì giữ nguyên dữ liệu đang nhập.'],
    ],
})
_FR['Xóa quận/huyện'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Mô tả'],
        ['1', 'Biểu tượng thùng rác (Xóa)', 'Icon Button', 'Nằm ở cột Hành động của từng dòng. Chỉ hiển thị khi quận/huyện đang Hoạt động và CHƯA được dùng ở Phường/Xã, hồ sơ nhân sự, Khách hàng, Công ty, Nhà cung cấp, Địa điểm giao hàng; ngược lại nút bị ẩn hẳn.'],
        ['2', 'Tiêu đề hộp xác nhận', 'Label', '“Xóa Quận/Huyện”.'],
        ['3', 'Nội dung hộp xác nhận', 'Label', '“Bạn có chắc muốn xóa quận/huyện "<tên>"?” — nêu rõ tên bản ghi để tránh xóa nhầm dòng.'],
        ['4', 'Nút Xóa', 'Button', 'Xác nhận xóa hẳn bản ghi khỏi hệ thống.'],
        ['5', 'Nút Hủy', 'Button', 'Đóng hộp, không thay đổi gì.'],
    ],
    'ui_widths': [0.6, 1.8, 1.0, 3.6],
    'events': [
        ['Bấm biểu tượng thùng rác', 'Click', 'Before:\n– Nút chỉ hiển thị khi quận/huyện đang Hoạt động và CHƯA được dùng ở Phường/Xã, hồ sơ nhân sự, Khách hàng, Công ty, Nhà cung cấp, Địa điểm giao hàng.\nAfter:\n– Hiện hộp xác nhận “Xóa Quận/Huyện” kèm tên bản ghi.'],
        ['Bấm Xóa trong hộp xác nhận', 'Click', 'During:\n– Bản ghi đang Khóa (vừa bị người khác khóa) → “Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.”, không xóa.\n– Bản ghi vừa được dùng ở nơi khác → “Quận/huyện đang được sử dụng, không thể xóa.”, không xóa.\n– Bản ghi không còn tồn tại (người khác vừa xóa) → “Trạng thái đã bị thay đổi. Vui lòng load lại trang”.\nAfter:\n– Xóa hẳn bản ghi (không khôi phục được), đóng hộp, nạp lại danh sách, báo “Xoá quận/huyện thành công”.\n– Lỗi khác → báo câu lỗi của hệ thống hoặc “Xoá quận/huyện thất bại”.'],
        ['Bấm Hủy', 'Click', 'After:\n– Đóng hộp xác nhận, không thay đổi gì.'],
    ],
})
_FR['Khóa / Mở khóa quận/huyện'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Mô tả'],
        ['1', 'Nút Khóa / Mở khóa', 'Button', 'Nằm ở cột Hành động (trong nút ba chấm nếu dòng có từ 4 nút trở lên). Nhãn đổi theo trạng thái. Luôn hiển thị (khóa được cả khi quận/huyện đang được dùng): dòng Hoạt động có Khóa, dòng Khóa có Mở khóa.'],
        ['2', 'Nút ba chấm “Hành động khác”', 'Icon Button', 'Hiện khi dòng có từ 4 nút trở lên: 2 nút đầu hiện thẳng, các nút còn lại (Khóa, Lịch sử) nằm trong menu này.'],
        ['3', 'Tiêu đề hộp xác nhận', 'Label', '“Khóa Quận/Huyện” hoặc “Mở khóa Quận/Huyện” tùy trạng thái hiện tại.'],
        ['4', 'Nội dung hộp xác nhận', 'Label', '“Bạn có chắc muốn khóa quận/huyện "<tên>"?” / “Bạn có chắc muốn mở khóa quận/huyện "<tên>"?”.'],
        ['5', 'Nút Khóa / Mở khóa trong hộp', 'Button', 'Xác nhận thực hiện.'],
        ['6', 'Nút Hủy', 'Button', 'Đóng hộp, không làm gì.'],
        ['7', 'Cột Trạng thái', 'Badge', 'Hoạt động hoặc Khóa, hai màu khác nhau; cập nhật ngay sau thao tác.'],
    ],
    'ui_widths': [0.6, 1.8, 1.0, 3.6],
    'events': [
        ['Bấm nút ba chấm', 'Click', 'After:\n– Mở menu chứa các nút còn lại của dòng (Khóa / Mở khóa, Lịch sử).'],
        ['Chọn Khóa hoặc Mở khóa', 'Click', 'After:\n– Hiện hộp xác nhận kèm tên bản ghi.'],
        ['Bấm Khóa / Mở khóa trong hộp', 'Click', 'During:\n– Bản ghi không còn tồn tại hoặc đã ở trạng thái đích (người khác vừa thao tác) → báo “Trạng thái đã bị thay đổi. Vui lòng load lại trang”, dừng xử lý, không ghi thêm lịch sử.\nAfter:\n– Đổi trạng thái, KHÔNG xóa dữ liệu; ghi Người cập nhật và một dòng lịch sử “Khóa” / “Mở khóa”.\n– Đóng hộp, báo “Khóa thành công” / “Mở khóa thành công”, nạp lại danh sách: sau Khóa ẩn nút Sửa, Xóa; sau Mở khóa hiện lại nút Sửa (Xóa hiện lại nếu đủ điều kiện xóa).\n– Lỗi khác → báo câu lỗi của hệ thống hoặc “Thao tác thất bại”.'],
        ['Bấm Hủy', 'Click', 'After:\n– Đóng hộp xác nhận, trạng thái không đổi.'],
    ],
})
_FR['Xem lịch sử thay đổi'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Giá trị ban đầu', 'Mô tả'],
        ['1', 'Nút Lịch sử', 'Button', 'Hiển thị', 'Nằm ở cột Hành động (trong nút ba chấm nếu dòng có từ 4 nút). Luôn có ở mọi dòng, kể cả bản ghi Khóa.'],
        ['2', 'Tiêu đề cửa sổ', 'Label', 'Lịch sử thay đổi: <tên quận/huyện>', 'Ghép tên bản ghi để biết đang xem dòng nào.'],
        ['3', 'Nút Bộ lọc', 'Button', 'Vùng lọc đang ẩn', 'Bấm để hiện / ẩn vùng lọc; vùng lọc ghim ở đầu khi cuộn danh sách.'],
        ['4', 'Loại hành động', 'Dropdown', 'Trống (“Tất cả loại hành động”)', 'Lọc theo Tạo mới, Thay đổi thông tin, Thay đổi trạng thái, Khóa, Mở khóa… Chọn là lọc ngay.'],
        ['5', 'Người thực hiện', 'Dropdown', 'Trống (“Tất cả người thực hiện”)', 'Chọn là lọc ngay.'],
        ['6', 'Từ ngày / Đến ngày', 'Date picker', 'Trống', 'Định dạng dd/mm/yyyy. Chọn là lọc ngay.'],
        ['7', 'Nút Làm mới (vùng lọc)', 'Button', 'Hiển thị', 'Xóa hết tiêu chí lọc, hiện lại toàn bộ lịch sử.'],
        ['8', 'Danh sách thay đổi', 'Timeline', 'Mới nhất ở trên cùng', 'Mỗi mốc gồm: thời điểm (dd/mm/yyyy hh:mm); loại hành động (Tạo mới, Thay đổi thông tin, Thay đổi trạng thái, Khóa, Mở khóa); “Người thực hiện: …”; từng trường đã đổi dạng “Tên trường: giá trị cũ → giá trị mới”. Trường Tỉnh/TP hiển thị bằng tên.'],
        ['9', 'Trạng thái rỗng', 'Label', 'Ẩn', '“Chưa có lịch sử thao tác nào.” khi bản ghi chưa có lịch sử; “Không có lịch sử phù hợp bộ lọc.” khi lọc không ra kết quả.'],
        ['10', 'Nút Đóng / biểu tượng X', 'Button', 'Hiển thị', 'Đóng cửa sổ.'],
    ],
    'ui_widths': [0.6, 1.5, 0.9, 1.2, 2.8],
    'events': [
        ['Chọn Lịch sử ở cột Hành động', 'Click', 'After:\n– Mở cửa sổ “Lịch sử thay đổi: <tên>”, nạp danh sách thay đổi theo thứ tự mới nhất trước.\n– Không tải được → hiện “Không tải được lịch sử phiếu.” kèm nút Thử lại.'],
        ['Bấm Bộ lọc', 'Click', 'After:\n– Hiện / ẩn vùng lọc.'],
        ['Đổi Loại hành động / Người thực hiện / Từ ngày / Đến ngày', 'Change', 'After:\n– Lọc ngay danh sách theo mọi tiêu chí đã chọn (không có nút Tìm kiếm).'],
        ['Bấm Làm mới trong vùng lọc', 'Click', 'After:\n– Xóa trắng tiêu chí, hiện lại toàn bộ lịch sử.'],
        ['Bấm Đóng / biểu tượng X', 'Click', 'After:\n– Đóng cửa sổ; danh sách phía sau giữ nguyên bộ lọc và trang đang xem.'],
    ],
})
_FR['Import file quận/huyện'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Bắt buộc', 'Giá trị ban đầu', 'Mô tả'],
        ['1', 'Nút Import Excel', 'Button', 'Enable', '–', 'Hiển thị', 'Nằm trên thanh công cụ của bảng danh sách. Mở cửa sổ “Import quận/huyện” (dòng phụ “Import từ Excel • Validate xong dòng hợp lệ sẽ bị khoá”).'],
        ['2', 'Nút Chọn file Excel', 'Button', 'Enable', 'Có', 'Chưa chọn file', 'Chọn file .xlsx hoặc .xls từ máy; tên file hiện ngay cạnh nút.'],
        ['3', 'Nút Tải file mẫu', 'Button', 'Enable', '–', 'Hiển thị', 'Tải file Mau_import_quan_huyen.xlsx gồm cột STT, Tên quận/huyện *, Tỉnh/TP * (ô chọn sẵn danh sách tỉnh/TP). Hàng 1 là tiêu đề, hàng 2 là dòng mô tả, dữ liệu nhập từ hàng 3.'],
        ['4', 'Nút Load lên bảng', 'Button', 'Enable / Disable', '–', 'Mờ khi chưa chọn file', 'Đọc file và đổ dữ liệu lên bảng xem trước.'],
        ['5', 'Nút Validate', 'Button', 'Enable / Disable', '–', 'Mờ khi bảng chưa có dòng nào', 'Gửi dữ liệu lên máy chủ kiểm tra từng dòng; dòng hợp lệ bị khóa lại, không sửa được nữa.'],
        ['6', 'Nút Import', 'Button', 'Enable / Disable', '–', 'Mờ', 'Chỉ bấm được khi đã Validate, không còn dòng lỗi và có ít nhất 1 dòng hợp lệ. Ghi các dòng hợp lệ vào danh mục.'],
        ['7', 'Ô Tổng / Hợp lệ / Lỗi', 'Label', 'Read-only', '–', 'Tổng: 0', 'Sau Load hiện “Tổng”; sau Validate hiện thêm “Hợp lệ”, “Lỗi”. Có dòng vừa sửa hiện “Có dòng đã sửa (cần validate lại)”.'],
        ['8', 'Bảng xem trước', 'Table/Grid', 'Enable', '–', 'Trống', 'Cột #, Tên quận/huyện *, Tỉnh/TP *. Dòng lỗi sửa trực tiếp được (Tên quận/huyện gõ lại; Tỉnh/TP chọn trong danh sách).'],
        ['9', 'Thông báo lỗi theo dòng', 'Label', 'Hiển thị', '–', 'Ẩn', 'Dòng lỗi viền đỏ, lý do ghi ngay dưới dòng: “Tên quận/huyện không được để trống”; “Tên quận/huyện tối đa 255 ký tự”; “Tỉnh/TP không được để trống”; “Không tìm thấy tỉnh/TP: X”; “Tên tỉnh/TP "X" đang có ở nhiều quốc gia, không xác định được”; “Quận/huyện bị trùng với dòng N trong file”; “Quận/huyện này đã tồn tại trong tỉnh/TP đã chọn”.'],
        ['10', 'Nút Bỏ dòng lỗi', 'Button', 'Enable / Disable', '–', 'Mờ khi bảng trống', 'Loại mọi dòng lỗi khỏi bảng, báo “Đã bỏ N dòng lỗi. Còn lại M dòng hợp lệ.”; chưa Validate thì báo “Hãy Validate trước rồi mới bỏ dòng lỗi.”'],
        ['11', 'Nút Xoá trạng thái validate', 'Button', 'Enable / Disable', '–', 'Mờ khi bảng trống', 'Bỏ khóa các dòng hợp lệ và xóa kết quả kiểm tra để sửa lại.'],
        ['12', 'Nút Làm mới', 'Button', 'Enable', '–', 'Hiển thị', 'Bỏ file đã chọn và toàn bộ bảng, đưa cửa sổ về trạng thái ban đầu.'],
        ['13', 'Nút Đóng / biểu tượng X', 'Button', 'Enable', '–', 'Hiển thị', 'Đóng cửa sổ, không ghi gì.'],
    ],
    'ui_widths': [0.5, 1.3, 0.9, 0.8, 0.5, 1.1, 2.4],
    'events': [
        ['Bấm Import Excel', 'Click', 'After:\n– Mở cửa sổ “Import quận/huyện” ở trạng thái rỗng.'],
        ['Bấm Tải file mẫu', 'Click', 'After:\n– Tải file Mau_import_quan_huyen.xlsx về máy.\n– Lỗi → báo “Lỗi khi tạo file mẫu”.'],
        ['Chọn file', 'Change', 'During:\n– File không phải .xlsx / .xls → báo “Vui lòng chọn file .xlsx hoặc .xls”, bỏ file.\nAfter:\n– Hiện tên file, nút Load lên bảng sáng lên.'],
        ['Bấm Load lên bảng', 'Click', 'During:\n– File không có dòng dữ liệu → “Không có dòng dữ liệu hợp lệ.”\n– Quá 500 dòng → “File có X dòng dữ liệu, vượt quá giới hạn 500 dòng mỗi lần import. Vui lòng tách file và import nhiều lần.”\n– File hỏng / không đọc được → “Không đọc được file Excel.”\nAfter:\n– Đổ dữ liệu lên bảng xem trước, cập nhật ô Tổng.'],
        ['Bấm Validate', 'Click', 'During:\n– Máy chủ kiểm tra từng dòng theo đúng quy tắc của chức năng Thêm mới và bảng “Quy tắc kiểm tra riêng của file Import”.\n– KHÔNG ghi bất kỳ bản ghi nào ở bước này.\nAfter:\n– Còn dòng lỗi: tô đỏ dòng lỗi kèm lý do, khóa dòng hợp lệ, báo “Validate xong: X hợp lệ, Y không hợp lệ. (Dòng hợp lệ đã bị khoá, chỉ có thể sửa dòng lỗi)”.\n– Không còn dòng lỗi: báo “Tất cả N dòng đã hợp lệ. Có thể import ngay.”, nút Import sáng lên.\n– Không dòng nào hợp lệ: báo “Không có dòng nào hợp lệ để import. Hãy sửa các dòng lỗi và validate lại.”'],
        ['Sửa ô ở dòng lỗi', 'Input', 'After:\n– Dòng chuyển về chưa kiểm tra, hiện “Có dòng đã sửa (cần validate lại)”; phải Validate lại mới Import được.'],
        ['Bấm Bỏ dòng lỗi / Xoá trạng thái validate', 'Click', 'After:\n– Bỏ dòng lỗi: chỉ giữ dòng hợp lệ, nút Import sáng lên.\n– Xoá trạng thái validate: mở khóa mọi dòng, xóa kết quả kiểm tra.'],
        ['Bấm Import', 'Click', 'During:\n– Chỉ gửi các dòng hợp lệ; máy chủ kiểm tra lại toàn bộ, không tin kết quả Validate trước đó.\n– Không còn dòng hợp lệ → báo “Không có dòng nào hợp lệ để import”, dừng.\nAfter:\n– Tạo quận/huyện mới ở trạng thái Hoạt động, người tạo là người đang thực hiện.\n– Báo “Import thành công N quận/huyện.” (có dòng thất bại: “Import thành công X/Y quận/huyện. Z dòng thất bại.”), đóng cửa sổ, nạp lại danh sách.'],
        ['Bấm Làm mới / Đóng', 'Click', 'After:\n– Làm mới: xóa file và bảng, giữ cửa sổ mở.\n– Đóng: đóng cửa sổ, không ghi gì.'],
    ],
})
_FR['Xuất danh sách ra Excel'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
        ['1', 'Nút Xuất Excel', 'Button', 'Enable', 'Hiển thị', 'Nằm trên thanh công cụ của bảng danh sách. Mở cửa sổ “Chọn trường xuất file”.'],
        ['2', 'Dòng hướng dẫn', 'Label', 'Read-only', 'Hiển thị', '“Tích chọn trường cần xuất, kéo ☰ để đổi thứ tự cột trong file.”'],
        ['3', 'Danh sách trường', 'Checkbox chọn nhiều', 'Enable', 'Tích sẵn đúng các cột đang hiển thị trên bảng, xếp lên đầu theo thứ tự trên bảng', 'Tám trường: Tên quận/huyện, Tỉnh/TP, Quốc gia, Trạng thái, Người tạo, Ngày tạo, Người cập nhật, Ngày cập nhật. Kéo biểu tượng ☰ để đổi vị trí cột trong file.'],
        ['4', 'Nút Chọn tất cả', 'Button', 'Enable', 'Hiển thị', 'Tích toàn bộ trường.'],
        ['5', 'Nút Bỏ chọn hết', 'Button', 'Enable', 'Hiển thị', 'Bỏ tích toàn bộ trường.'],
        ['6', 'Dòng đếm trường', 'Label', 'Read-only', 'Hiển thị', '“Đang chọn a/N trường”.'],
        ['7', 'Nút Xuất file', 'Button', 'Enable / Disable', 'Mờ khi chưa chọn trường nào', 'Đóng cửa sổ, sinh file Excel và tải về máy.'],
        ['8', 'Nút Đóng / biểu tượng X', 'Button', 'Enable', 'Hiển thị', 'Đóng cửa sổ, không xuất.'],
    ],
    'ui_widths': [0.6, 1.5, 1.0, 0.8, 1.3, 2.3],
    'events': [
        ['Bấm Xuất Excel', 'Click', 'After:\n– Mở cửa sổ “Chọn trường xuất file”, tích sẵn đúng các cột đang hiển thị trên bảng (theo cấu hình cột của người dùng), các trường còn lại liệt kê bên dưới chưa tích. Không nhớ lựa chọn của lần xuất trước.'],
        ['Tích / bỏ tích trường, kéo ☰', 'Change', 'During:\n– Thứ tự trong danh sách là thứ tự cột trong file.\n– Bỏ chọn hết → nút Xuất file mờ đi.'],
        ['Bấm Xuất file', 'Click', 'During:\n– Sinh file theo ĐÚNG bộ lọc và thứ tự sắp xếp đang áp dụng (tối đa 10,000 dòng), các cột theo đúng thứ tự trường đã chọn.\nAfter:\n– Tải file danh_muc_quan_huyen.xlsx về máy, báo “Xuất Excel thành công”.\n– Lỗi → báo “Lỗi khi xuất Excel”.'],
        ['Bấm Đóng / biểu tượng X', 'Click', 'After:\n– Đóng cửa sổ, không xuất gì.'],
    ],
})
_FR['Xem chi tiết quận/huyện'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
        ['1', 'Tên quận/huyện ở cột Tên quận/huyện', 'Link', 'Enable', 'Hiển thị', 'Bấm vào tên để mở cửa sổ Xem (thay cho nút “Xem” ở cột Hành động). Bản ghi Khóa vẫn mở được.'],
        ['2', 'Tiêu đề cửa sổ', 'Label', 'Read-only', 'Xem quận/huyện', 'Kèm biểu tượng tròn ở đầu tiêu đề.'],
        ['3', 'Tên quận/huyện', 'Textbox', 'Read-only', 'Dữ liệu hiện tại', 'Chỉ đọc, không sửa được.'],
        ['4', 'Tỉnh/TP', 'Dropdown', 'Read-only', 'Dữ liệu hiện tại', 'Chỉ đọc, không sửa được. Tỉnh/TP đã khóa vẫn hiện đúng tên kèm 🔒.'],
        ['5', 'Trạng thái', 'Dropdown', 'Read-only', 'Dữ liệu hiện tại', 'Chỉ đọc, không sửa được.'],
        ['6', 'Khối Lịch sử', 'Panel thu gọn', 'Enable', 'Thu gọn', 'Tiêu đề “Lịch sử” kèm số lần thay đổi. Nút “Xem lịch sử” mở khối (đổi thành “Thu gọn”), nút “Làm mới” nạp lại. Nội dung, bộ lọc giống cửa sổ Lịch sử thay đổi.'],
        ['7', 'Nút Đóng / biểu tượng X', 'Button', 'Enable', 'Hiển thị', 'Đóng cửa sổ. Cửa sổ Xem KHÔNG có nút Lưu, Lưu và tiếp tục hay Sửa.'],
    ],
    'ui_widths': [0.6, 1.5, 1.0, 0.8, 1.3, 2.3],
    'events': [
        ['Bấm tên quận/huyện ở danh sách', 'Click', 'After:\n– Mở cửa sổ “Xem quận/huyện”, nạp dữ liệu hiện tại của bản ghi ở chế độ chỉ đọc.\n– Không tải được → báo “Lỗi khi tải dữ liệu” và đóng cửa sổ.'],
        ['Bấm Xem lịch sử / Thu gọn', 'Click', 'After:\n– Lần mở đầu tiên mới nạp lịch sử; hiện danh sách thay đổi mới nhất ở trên.\n– Thu gọn: ẩn khối, không nạp lại.'],
        ['Bấm Làm mới trong khối Lịch sử', 'Click', 'After:\n– Nạp lại lịch sử mới nhất của bản ghi.'],
        ['Bấm Đóng / biểu tượng X', 'Click', 'After:\n– Đóng cửa sổ, không hỏi xác nhận (không có gì để lưu).'],
    ],
})
_FR['Tùy chỉnh cột hiển thị'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
        ['1', 'Biểu tượng Cấu hình cột hiển thị', 'Icon Button', 'Enable', 'Hiển thị', 'Nút cuối cùng trên thanh công cụ của bảng. Mở cửa sổ “Tuỳ chỉnh cột”.'],
        ['2', 'Danh sách cột', 'Checkbox', 'Enable', 'Theo cấu hình đã lưu; chưa lưu lần nào thì hiện Tỉnh/TP, Người tạo, Ngày tạo, Trạng thái, ẩn Quốc gia, Người cập nhật, Ngày cập nhật', 'Liệt kê đủ 10 cột theo thứ tự trên bảng: STT, Tên quận/huyện, Tỉnh/TP, Quốc gia, Người cập nhật, Ngày cập nhật, Người tạo, Ngày tạo, Trạng thái, Hành động. Tích = hiện cột, bỏ tích = ẩn cột.'],
        ['3', 'Cột bắt buộc', 'Checkbox', 'Disable', 'Luôn tích', 'STT, Tên quận/huyện, Hành động: xám, có biểu tượng khóa, không bỏ tích và không kéo đổi vị trí được (rê chuột hiện “Cột bắt buộc — không thể ẩn hoặc đổi vị trí”).'],
        ['4', 'Biểu tượng ☰', 'Drag handle', 'Enable', 'Hiển thị', 'Kéo thả để đổi thứ tự các cột không bắt buộc.'],
        ['5', 'Nút Lưu', 'Button', 'Enable', 'Hiển thị', 'Áp dụng ngay cho bảng và lưu cấu hình theo TÀI KHOẢN người dùng trên máy chủ (đăng nhập máy/trình duyệt khác vẫn giữ).'],
        ['6', 'Nút Đóng / biểu tượng X', 'Button', 'Enable', 'Hiển thị', 'Đóng cửa sổ, bỏ các thay đổi chưa Lưu.'],
    ],
    'ui_widths': [0.6, 1.5, 1.0, 0.8, 1.3, 2.3],
    'events': [
        ['Bấm biểu tượng Cấu hình cột hiển thị', 'Click', 'After:\n– Mở cửa sổ “Tuỳ chỉnh cột”, tích đúng theo các cột đang hiển thị.'],
        ['Tích / bỏ tích, kéo ☰', 'Change', 'During:\n– Chỉ thay đổi trong cửa sổ, bảng chưa đổi.\n– Cột bắt buộc không bỏ tích, không kéo được.'],
        ['Bấm Lưu', 'Click', 'After:\n– Bảng hiện/ẩn và sắp cột theo cấu hình mới, lưu cấu hình theo người dùng, báo “Cập nhật thành công”; đóng cửa sổ.\n– Lần Xuất Excel sau tích sẵn đúng các cột đang hiện.\n– Lỗi lưu → báo “Thao tác thất bại”.'],
        ['Bấm Đóng / biểu tượng X', 'Click', 'After:\n– Đóng cửa sổ, trả danh sách về cấu hình đang áp dụng.'],
    ],
})
