# -*- coding: utf-8 -*-
# Cấu hình tài liệu màn Danh mục Đường/Phố — bám khuôn configs/areas.py.
# Nguồn: code gop_db 28/09/2026 (FE pages/human/hamlets/index.vue, pages/human/hamlets/components/HamletModel.vue;
# BE Entities/Hamlet.php, HamletController / HamletService / CreateHamletRequest / HamletListResource,
# Routes/api.php (middleware recordNotLocked), ExportColumnRegistry['hamlets']).
# 28/09/2026: Xóa = xóa HẲN (chỉ khi Hoạt động + chưa dùng), thêm Khóa/Mở khóa, ô Trạng thái, cột + lọc Trạng thái.
# Không ghi URL. Chữ UI / message lấy nguyên văn code.

DT = 'đường/phố'

# Nơi được coi là "đã dùng" (Hamlet::USAGE_REFERENCES) — tên nghiệp vụ
NOI_DUNG = 'Khách hàng, Địa điểm giao hàng, Công ty, Nhà cung cấp'

CFG = {
    'slug': 'hamlets',
    'ten': 'Danh mục Đường/Phố',
    'doi_tuong': DT,
    'file_hdsd': 'HDSD_Danh mục Đường-Phố.docx',
    'file_srs': 'SRS - Danh mục Đường-Phố.docx',
    'menu': [('Danh mục', 'menu_phanhe'), ('Địa lý', 'menu_nhom'), ('Đường/Phố', 'menu_muc')],

    'thuat_ngu': [
        ['Đường/Phố', 'Cấp địa chỉ nhỏ nhất trong hệ thống, trực thuộc một Phường/Xã.'],
        ['Quy tắc Việt Nam', 'Khi Quốc gia là Việt Nam, ô Quận/Huyện/Thị xã bị ẩn và không phải nhập; địa chỉ đi thẳng từ Tỉnh/TP xuống Phường/Xã. Với quốc gia khác, phải chọn Quận/Huyện/Thị xã trước rồi mới chọn Phường/Xã.'],
        ['Trạng thái Hoạt động', 'Đường/phố dùng được ở các màn nghiệp vụ khác.'],
        ['Trạng thái Khóa', 'Đường/phố không còn chọn được ở nơi khác nhưng vẫn nằm trong danh mục, vẫn xem được chi tiết và lịch sử. Muốn sửa phải Mở khóa trước.'],
        ['Đường/phố đã được dùng', 'Đường/phố đang được chọn làm địa chỉ ở ít nhất một nơi: ' + NOI_DUNG + '. Đường/phố đã được dùng thì không xóa được, chỉ Khóa được.'],
    ],
    'phien_ban': [
        ['1.0', '17/08/2026', 'Đội phát triển phần mềm', 'Tạo mới cho màn Danh mục Đường/Phố.'],
        ['1.1', '25/09/2026', 'Đội phát triển phần mềm', 'Cập nhật theo phiên bản hiện tại: bổ sung Xem chi tiết, Xuất Excel, Import Excel, Tùy chỉnh cột; trình bày theo mẫu tài liệu danh mục chung.'],
        ['1.2', '28/09/2026', 'Đội phát triển phần mềm', 'Bổ sung Khóa / Mở khóa, ô Trạng thái trong cửa sổ Tạo/Sửa, cột và bộ lọc Trạng thái trên danh sách (danh sách hiện cả đường/phố đang Khóa), trường Trạng thái khi xuất Excel. Xóa đổi từ “ngừng sử dụng” thành xóa hẳn và chỉ áp dụng cho đường/phố đang Hoạt động, chưa được dùng ở ' + NOI_DUNG + '; đường/phố đang Khóa không sửa, không xóa được. Nút “Lưu và tiếp tục” giữ cửa sổ mở và xóa trắng các ô.'],
    ],
    'muc_dich': [
        'Danh mục Đường/Phố là nơi khai báo và quản lý danh sách đường/phố dùng chung cho toàn hệ thống. Mỗi đường/phố trực thuộc một Phường/Xã (qua đó thuộc một Tỉnh/TP và Quốc gia); dữ liệu của màn này là nguồn cho ô Đường/Phố ở các màn địa chỉ nghiệp vụ, nên mỗi thay đổi ở đây đều ảnh hưởng tới nhiều nơi.',
    ],
    'quyen': {
        'truoc': ['Phân quyền ai được quyền tạo/ sửa/ xóa/ khóa/ mở khóa sẽ được cập nhật ngay sau khi có tài liệu phân quyền chi tiết của hệ thống.',
                  'Tại thời điểm xây dựng HDSD hiện tại, ai cũng được quyền truy cập màn hình danh mục Đường/Phố và quyền tạo/sửa/xóa/khóa/mở khóa, import, xuất Excel.'],
        'rows': [],
        'sau': ['Lưu ý: vì ai cũng sửa được, Người dùng hãy cân nhắc kỹ trước khi đổi, khóa hoặc xóa một bản ghi — dữ liệu này đang được nhiều màn khác sử dụng.'],
    },

    'danh_sach': {
        'mo_ta_vao': 'Hệ thống hiển thị danh sách TẤT CẢ đường/phố, cả đang Hoạt động lẫn đang Khóa, mặc định 10 dòng mỗi trang.',
        'bo_cuc': [
            'Khu vực tìm kiếm và lọc — ô tìm kiếm nhanh, ô Tỉnh/TP, ô Phường/xã, ô Trạng thái, nút Tìm kiếm và Làm mới.',
            'Thanh công cụ — nút Tạo mới, nút Xuất Excel, nút Import Excel và biểu tượng Cấu hình cột hiển thị.',
            'Bảng danh sách — các cột thông tin, cột Hành động ở cuối, và phân trang bên dưới.',
        ],
        'cot': [
            ['STT', 'Số thứ tự, chạy liên tục qua các trang. Luôn hiển thị.'],
            ['Tên đường/phố', 'Tên đầy đủ. Luôn hiển thị, sắp xếp được. Bấm vào tên để mở cửa sổ Xem đường/phố.'],
            ['Phường/xã', 'Phường/xã mà đường/phố trực thuộc.'],
            ['Quận/Huyện/Thị xã', 'Chỉ có giá trị với địa chỉ ngoài Việt Nam (Việt Nam để trống). Mặc định ẩn.'],
            ['Tỉnh/TP', 'Tỉnh/TP của phường/xã.'],
            ['Quốc gia', 'Quốc gia của tỉnh/TP. Mặc định ẩn.'],
            ['Người cập nhật', 'Người sửa bản ghi gần nhất. Mặc định ẩn.'],
            ['Ngày cập nhật', 'Thời điểm sửa gần nhất, dạng dd/mm/yyyy hh:mm. Mặc định ẩn, sắp xếp được.'],
            ['Người tạo', 'Người đã thêm bản ghi.'],
            ['Ngày tạo', 'Thời điểm thêm, dạng dd/mm/yyyy hh:mm, sắp xếp được.'],
            ['Trạng thái', 'Nhãn Hoạt động hoặc Khóa.'],
            ['Hành động', 'Các nút thao tác của dòng (xem mục 4).'],
        ],
        'hanh_dong': {
            'intro': 'Trên mỗi dòng, cột Hành động có các nút:',
            'bullets': [
                'Biểu tượng bút chì {icon:btn_sua} — mở cửa sổ Sửa đường/phố. Chỉ hiện khi đường/phố đang Hoạt động.',
                'Biểu tượng thùng rác {icon:btn_xoa} — xóa hẳn đường/phố. Chỉ hiện khi đường/phố đang Hoạt động và CHƯA được dùng ở ' + NOI_DUNG + '.',
                'Khóa / Mở khóa — đổi trạng thái đường/phố.',
                'Lịch sử — mở cửa sổ Lịch sử thay đổi.',
                'Có từ 4 nút trở lên thì 2 nút đầu hiện thẳng, các nút còn lại nằm trong nút ba chấm {icon:btn_bacham} “Hành động khác”. Dòng có 3 nút trở xuống thì hiện thẳng tất cả.',
            ],
            'anh': 'Các nút ở cột Hành động của một đường/phố',
            'luu_y': ['Lưu ý quan trọng: nút không dùng được sẽ BIẾN MẤT chứ không hiện mờ. Đường/phố ĐÃ KHÓA chỉ còn Mở khóa và Lịch sử — muốn sửa phải Mở khóa trước. Đường/phố đã được dùng ở nơi khác không có nút Xóa, chỉ Khóa được.'],
        },
        'phan_trang': [
            'Cuối bảng có dòng “Hiển thị a–b / N”: N là tổng số đường/phố khớp bộ lọc đang áp dụng (tính cả bản ghi Khóa nếu không lọc Trạng thái), không phải tổng toàn danh mục.',
            'Ô Số dòng/trang có các mức 5, 10, 20, 50, 100 (mặc định 10). Đổi số dòng thì hệ thống tự quay về trang 1.',
            'Các cột sắp xếp được: Tên đường/phố, Ngày tạo, Ngày cập nhật. Bấm tiêu đề cột để sắp xếp, bấm lần hai để đảo chiều. Thứ tự sắp xếp được giữ nguyên khi chuyển trang. Chưa bấm sắp xếp thì bản ghi tạo gần nhất nằm trên cùng.',
        ],
    },

    'loc': {
        'buoc2': 'Bước 2: Nhập chữ vào ô tìm kiếm nhanh hoặc chọn giá trị ở ô Tỉnh/TP, Phường/xã, Trạng thái.',
        'rows': [
            ['Ô tìm kiếm nhanh', 'Tìm theo TÊN đường/phố (gõ một phần tên cũng ra). Nhấn Enter hoặc bấm Tìm kiếm để lọc.'],
            ['Tỉnh/TP', 'Chọn một tỉnh/TP để chỉ xem đường/phố thuộc các phường/xã của tỉnh/TP đó; đồng thời nạp danh sách cho ô Phường/xã. Lọc ngay khi chọn.'],
            ['Phường/xã', 'Chỉ có lựa chọn sau khi đã chọn Tỉnh/TP. Chọn một phường/xã để chỉ xem đường/phố của phường/xã đó. Bị xóa trắng khi đổi Tỉnh/TP. Lọc ngay khi chọn.'],
            ['Trạng thái', 'Hoạt động hoặc Khóa. Bỏ trống thì hiện cả hai trạng thái (bấm dấu x để xoá lựa chọn). Lọc ngay khi chọn.'],
        ],
        'ap_dung': [
            'Các tiêu chí kết hợp với nhau theo kiểu VÀ — chỉ bản ghi thỏa đồng thời tất cả các tiêu chí mới hiện ra. Mỗi lần đổi tiêu chí, danh sách quay về trang 1.',
            'Lưu ý: ô Tỉnh/TP và ô Phường/xã phụ thuộc nhau. Đổi Tỉnh/TP thì ô Phường/xã bị xóa trắng và nạp lại theo tỉnh mới.',
            'Bấm {icon:btn_lammoi} để xóa toàn bộ tiêu chí; danh sách nạp lại đầy đủ ngay lập tức.',
        ],
        'anh_ket_qua': 'Kết quả tìm nhanh theo tên đường/phố (gõ “Đường”)',
    },

    'form': {
        'kieu': 'popup',
        'buoc_tao': [
            'Bước 1: Truy cập vào màn hình Danh mục Đường/Phố.',
            'Bước 2: Bấm {icon:btn_taomoi}. Hệ thống mở cửa sổ “Tạo đường/phố”.',
            'Bước 3: Nhập Tên đường/phố, chọn lần lượt Quốc gia → Tỉnh/TP → (Quận/Huyện/Thị xã nếu quốc gia khác Việt Nam) → Phường/xã; giữ hoặc đổi Trạng thái (mặc định Hoạt động).',
            'Bước 4: Bấm {icon:btn_luu} để lưu và đóng cửa sổ, hoặc {icon:btn_luutieptuc} để lưu rồi nhập tiếp đường/phố khác.',
        ],
        'anh_tao': 'Cửa sổ Tạo đường/phố',
        'truong': [
            ['Tên đường/phố', 'Ô nhập giá trị', 'Có', 'Trống', 'Tối đa 255 ký tự. Không được trùng trong cùng một Phường/xã, tính cả đường/phố đang Khóa (cùng tên ở phường/xã khác vẫn lưu được). Bỏ trống báo “Bắt buộc phải nhập”; trùng báo “Tên đường/phố này đã tồn tại trong phường/xã”.'],
            ['Quốc gia', 'Ô chọn giá trị', 'Có', 'Trống', 'Chỉ liệt kê quốc gia đang Hoạt động. Quyết định ô Quận/Huyện/Thị xã có hiện hay không. Đổi Quốc gia thì Tỉnh/TP, Quận/Huyện, Phường/xã bị xóa trắng.'],
            ['Tỉnh/TP', 'Ô chọn giá trị', 'Có', 'Trống', 'Chỉ liệt kê tỉnh/TP đang Hoạt động của quốc gia đã chọn; chưa chọn quốc gia thì ô hiện “Vui lòng chọn quốc gia trước”. Đổi Tỉnh/TP thì các ô cấp dưới bị xóa trắng.'],
            ['Quận/Huyện/Thị xã', 'Ô chọn giá trị', 'Có khi Quốc gia khác Việt Nam', 'Ẩn', 'ẨN HẲN khi Quốc gia là Việt Nam (hoặc chưa chọn quốc gia); hiện và bắt buộc với mọi quốc gia khác. Chưa chọn Tỉnh/TP thì ô hiện “Vui lòng chọn tỉnh/TP trước”.'],
            ['Phường/xã', 'Ô chọn giá trị', 'Có', 'Trống', 'Việt Nam: liệt kê phường/xã của Tỉnh/TP đã chọn (chưa chọn hiện “Vui lòng chọn tỉnh/TP trước”). Quốc gia khác: liệt kê phường/xã của Quận/Huyện đã chọn (chưa chọn hiện “Vui lòng chọn quận/huyện trước”). Chỉ liệt kê phường/xã đang Hoạt động; bản ghi đang dùng phường/xã đã khóa vẫn hiện kèm 🔒. Bỏ trống báo “Bắt buộc phải nhập”.'],
            ['Trạng thái', 'Ô chọn giá trị', 'Không (luôn có giá trị)', 'Hoạt động', 'Chỉ chọn 1 trong 2 giá trị: Hoạt động / Khóa; không xoá trống được. Chọn Khóa thì đường/phố được lưu ở trạng thái Khóa ngay.'],
        ],
        'sau_truong': [
            'Chọn Việt Nam — ô Quận/Huyện/Thị xã bị ẩn, không phải nhập. Địa chỉ đi thẳng từ Tỉnh/TP xuống Phường/xã.',
            'Chọn quốc gia khác — ô Quận/Huyện/Thị xã hiện ra và bắt buộc phải chọn trước khi chọn Phường/xã.',
            'Hệ thống lưu đường/phố theo Phường/xã đã chọn; Quốc gia, Tỉnh/TP, Quận/Huyện chỉ dùng để thu hẹp danh sách chọn. Bỏ trống các ô cấp trên thì không chọn được Phường/xã và hệ thống báo “Bắt buộc phải nhập” ở ô Phường/xã.',
        ],
        'nut': [
            ['Lưu', 'Ghi bản ghi rồi đóng cửa sổ, báo “Thêm mới thành công” (hoặc “Cập nhật thành công” khi sửa) và nạp lại danh sách.'],
            ['Lưu và tiếp tục', 'Ghi bản ghi, báo “Thêm mới thành công” nhưng GIỮ cửa sổ mở và xóa trắng các ô (Trạng thái trở về Hoạt động) để nhập tiếp. Chỉ có khi Tạo mới.'],
            ['Đóng', 'Đóng cửa sổ, không ghi gì. Nếu đã nhập dở, hệ thống hỏi “Thông tin chưa lưu” — “Bạn có thông tin chưa lưu. Có chắc chắn muốn thoát?” (Thoát / Ở lại).'],
        ],
        'loi': [
            ['Bắt buộc phải nhập', 'Chưa nhập Tên đường/phố hoặc chưa chọn Phường/xã (bao gồm trường hợp chưa chọn Quốc gia / Tỉnh/TP / Quận/Huyện nên không chọn được Phường/xã).'],
            ['Tên đường/phố này đã tồn tại trong phường/xã', 'Đã có đường/phố khác cùng tên trong cùng một Phường/xã (kể cả đường/phố đang Khóa). Hãy kiểm tra lại danh sách, bỏ lọc Trạng thái trước khi thêm.'],
            ['Vui lòng nhập tối đa 255 ký tự.', 'Tên đường/phố quá dài.'],
            ['Vui lòng kiểm tra lại dữ liệu nhập', 'Thông báo chung khi còn ô bị lỗi; xem các ô báo đỏ trong cửa sổ.'],
            ['Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.', 'Đang sửa một đường/phố thì người khác khóa nó. Đóng cửa sổ, Mở khóa rồi sửa lại.'],
        ],
    },

    'sua': {
        'buoc': [
            'Bước 1: Truy cập vào màn hình Danh mục Đường/Phố.',
            'Bước 2: Bấm nút {icon:btn_sua} ở cột Hành động của đường/phố cần sửa (chỉ có ở đường/phố đang Hoạt động).',
            'Bước 3: Hệ thống hiển thị cửa sổ “Sửa đường/phố” với dữ liệu hiện tại (Quốc gia, Tỉnh/TP, Quận/Huyện, Phường/xã được điền sẵn theo phường/xã của bản ghi; Trạng thái theo bản ghi).',
            'Bước 4: Cập nhật các thông tin cần sửa (quy tắc nhập như Thêm mới).',
            'Bước 5: Bấm {icon:btn_luu} để xác nhận thay đổi hoặc Đóng nếu muốn hủy.',
        ],
        'anh': 'Cửa sổ Sửa đường/phố',
        'ghi_chu': [
            'Giữ nguyên tên của chính đường/phố đang sửa thì không bị báo trùng.',
            'Đường/phố đang Khóa không có nút Sửa. Nếu đường/phố vừa bị người khác khóa, bấm Lưu sẽ nhận thông báo “Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.”',
            'Đổi Trạng thái sang Khóa ngay trong cửa sổ Sửa rồi Lưu cũng là một cách khóa; lịch sử ghi thành dòng “Thay đổi trạng thái” riêng.',
            'Mọi thay đổi đều được ghi vào Lịch sử kèm tên Người dùng và thời điểm. Đổi tên phường/xã, tỉnh/TP ở danh mục tương ứng thì các cột của đường/phố tự hiển thị tên mới.',
        ],
    },
    'xoa': {
        'buoc': [
            'Bước 1: Ở cột Hành động, Người dùng bấm {icon:btn_xoa}.',
            'Bước 2: Hệ thống hiện hộp xác nhận “Xóa Đường/Phố” — “Bạn có chắc muốn xóa đường/phố "…"?”. Bấm {icon:btn_confirm_xoa} để xác nhận: hệ thống báo “Xoá đường/phố thành công”, bản ghi bị xóa hẳn và biến mất khỏi danh sách.',
            'Bấm {icon:btn_huy} nếu bấm nhầm. Không có gì thay đổi.',
        ],
        'anh': 'Hộp xác nhận xóa đường/phố',
        'ghi_chu': [
            'Xóa là xóa HẲN bản ghi khỏi hệ thống, không khôi phục lại được. Nút Xóa chỉ hiện khi đường/phố đang Hoạt động và CHƯA được chọn làm địa chỉ ở ' + NOI_DUNG + '. Đường/phố đã được dùng thì dùng Khóa thay cho Xóa.',
            'Nếu trong lúc đang mở hộp xác nhận, đường/phố vừa được chọn làm địa chỉ ở nơi khác, hệ thống báo “Đường/phố đang được sử dụng, không thể xóa.”; vừa bị người khác khóa thì báo “Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.”; vừa bị người khác xóa thì báo “Trạng thái đã bị thay đổi. Vui lòng load lại trang”.',
        ],
    },
    'khoa': {
        'y_nghia': [
            'Bản ghi VẪN nằm trong danh sách, cột Trạng thái hiện chữ Khóa.',
            'Vẫn xem được chi tiết và lịch sử thay đổi của bản ghi.',
            'Đường/phố đã khóa không còn xuất hiện ở ô chọn Đường/Phố của các màn khác (ví dụ địa chỉ Khách hàng); dữ liệu đang dùng đường/phố đó vẫn giữ nguyên và hiển thị đúng tên kèm biểu tượng 🔒.',
            'Khóa được cả khi đường/phố đang được dùng ở nơi khác.',
            'Nút Sửa và Xóa của dòng đó biến mất.',
        ],
        'buoc_khoa': [
            'Bước 1: Ở cột Hành động, Người dùng chọn Khóa (trong nút ba chấm {icon:btn_bacham} nếu dòng có từ 4 nút trở lên).',
            'Bước 2: Hệ thống hiện hộp xác nhận “Khóa Đường/Phố” — “Bạn có chắc muốn khóa đường/phố "…"?”. Bấm Khóa để xác nhận; hệ thống báo “Khóa thành công”, cột Trạng thái đổi thành Khóa. Bấm Hủy nếu bấm nhầm.',
        ],
        'buoc_mo': [
            'Bước 1: Ở cột Hành động của đường/phố đang Khóa, Người dùng chọn {icon:btn_mokhoa} Mở khóa.',
            'Bước 2: Bấm Mở khóa trong hộp xác nhận “Mở khóa Đường/Phố” — “Bạn có chắc muốn mở khóa đường/phố "…"?”. Hệ thống báo “Mở khóa thành công”, cột Trạng thái đổi thành Hoạt động, nút Sửa hiện lại (nút Xóa hiện lại nếu đường/phố chưa được dùng). Bấm Hủy nếu bấm nhầm.',
        ],
        'ghi_chu': ['Có thể khóa ngay trong cửa sổ Sửa (hoặc tạo mới ở trạng thái Khóa) bằng ô Trạng thái. Nếu bản ghi vừa bị người khác đổi trạng thái (hoặc đã bị xóa), hệ thống báo “Trạng thái đã bị thay đổi. Vui lòng load lại trang” và không thực hiện lại thao tác.'],
    },
    'lich_su': {
        'buoc': [
            'Xem từ màn danh sách: ở cột Hành động, Người dùng chọn Lịch sử (trong nút ba chấm nếu dòng có từ 4 nút trở lên).',
            'Xem từ màn chi tiết: bấm vào tên đường/phố để mở cửa sổ Xem đường/phố, khối Lịch sử nằm ở cuối cửa sổ.',
        ],
        'ghi_chu': ['Khóa, Mở khóa (kể cả đổi Trạng thái trong cửa sổ Sửa) được ghi thành dòng Thay đổi trạng thái. Các trường Phường/xã, Tỉnh/TP, Quốc gia trong lịch sử hiển thị bằng TÊN. Đường/phố đã bị xóa hẳn không còn trong danh sách nên không mở được Lịch sử của nó nữa. Cửa sổ có bộ lọc riêng (loại hành động, người thực hiện, khoảng thời gian).'],
    },
    'chi_tiet': {
        'buoc': ['Bước 1: Truy cập vào màn hình Danh mục Đường/Phố.',
                 'Bước 2: Bấm vào tên đường/phố ở cột Tên đường/phố. Hệ thống mở cửa sổ “Xem đường/phố”.'],
        'ghi_chu': ['Cửa sổ hiển thị Tên đường/phố, Quốc gia, Tỉnh/TP, Quận/Huyện/Thị xã (nếu có), Phường/xã và Trạng thái ở chế độ chỉ đọc (không gõ được, không có nút Lưu), kèm khối Lịch sử ở cuối. Đường/phố đang Khóa vẫn xem được bình thường.'],
    },
    'xuat': {
        'buoc': [
            'Bước 1: Lọc danh sách theo đúng dữ liệu cần lấy (xem PHẦN 2). File xuất ra chạy theo đúng bộ lọc đang áp dụng, kể cả bộ lọc Trạng thái.',
            'Bước 2: Bấm nút {icon:btn_xuatexcel}. Hệ thống mở cửa sổ “Chọn trường xuất file”.',
            'Bước 3: Tích chọn, kéo biểu tượng ☰ để đổi vị trí các trường cần xuất. Mặc định hệ thống tích sẵn đúng những cột đang hiển thị trên bảng.',
            'Bước 4: Bấm {icon:btn_xuatfile}. Hệ thống tải về file danh_muc_duong_pho.xlsx và báo “Xuất Excel thành công”.',
        ],
        'truong': 'Chọn nhiều trường: Tên đường/phố, Phường/xã, Quận/Huyện/Thị xã, Tỉnh/TP, Quốc gia, Trạng thái, Người tạo, Ngày tạo, Người cập nhật, Ngày cập nhật.',
        'ghi_chu': ['Lưu ý: file xuất chứa TOÀN BỘ kết quả của bộ lọc (tối đa 10,000 dòng), không chỉ các dòng của trang đang xem. Cột Quận/Huyện/Thị xã để trống với địa chỉ ở Việt Nam. Cột Trạng thái ghi chữ “Hoạt động” hoặc “Khóa”.'],
    },
    'import': {
        'tieu_de': 'Import đường/phố',
        'file': 'Mau_import_duong_pho.xlsx',
        'cot_text': 'Tên đường/phố (bắt buộc), Tỉnh/TP (bắt buộc, chọn trong danh sách sổ xuống), Phường/xã (bắt buộc, gõ đúng tên phường/xã thuộc tỉnh/TP đó)',
        'toast': 'Import thành công N đường/phố.',
        'loi': [
            ['Tên đường/phố không được để trống', 'Dòng đó bỏ trống cột Tên đường/phố.'],
            ['Tên đường/phố tối đa 255 ký tự', 'Tên quá dài, rút gọn lại.'],
            ['Tỉnh/TP không được để trống', 'Dòng đó bỏ trống cột Tỉnh/TP.'],
            ['Không tìm thấy tỉnh/TP: X', 'Tên tỉnh/TP ghi sai, không có trong Danh mục Tỉnh/TP.'],
            ['Tên tỉnh/TP "X" đang có ở nhiều quốc gia, không xác định được', 'Danh mục Tỉnh/TP đang có từ 2 tỉnh/TP trở lên trùng đúng tên này (kể cả tỉnh/TP đã khóa) nên hệ thống không biết chọn tỉnh nào.'],
            ['Phường/xã không được để trống', 'Dòng đó bỏ trống cột Phường/xã.'],
            ['Không tìm thấy phường/xã "Y" thuộc tỉnh/TP X', 'Tên phường/xã gõ sai hoặc không thuộc tỉnh/TP ghi trên cùng dòng.'],
            ['Tên phường/xã "Y" đang có nhiều bản ghi trong X, không xác định được', 'Trong cùng tỉnh/TP có từ 2 phường/xã trở lên trùng đúng tên này (kể cả phường/xã đã khóa) nên hệ thống không biết chọn phường/xã nào.'],
            ['Đường/phố bị trùng với dòng N trong file', 'Trong chính file có hai dòng cùng tên, cùng phường/xã. Xoá bớt một dòng.'],
            ['Đường/phố này đã tồn tại trong phường/xã đã chọn', 'Danh mục đã có đường/phố trùng tên trong cùng phường/xã (kể cả đường/phố đang Khóa).'],
        ],
        'ghi_chu': ['Lưu ý: cột Phường/xã trong file là ô GÕ TAY (danh mục có hơn 13,000 phường/xã nên không làm danh sách sổ xuống); hệ thống tra theo cặp Tỉnh/TP + Phường/xã. Tên tỉnh/TP có ở nhiều quốc gia hoặc tên phường/xã trùng trong cùng tỉnh sẽ báo “…không xác định được”. Đường/phố nhập từ Excel luôn ở trạng thái Hoạt động, người tạo là chính người thực hiện nhập. Mỗi lần nhập tối đa 500 dòng; file dài hơn hệ thống báo “File có X dòng dữ liệu, vượt quá giới hạn 500 dòng mỗi lần import. Vui lòng tách file và import nhiều lần.”'],
    },
    'tuy_chinh_cot': {'cot_khoa': 'Ba cột STT, Tên đường/phố và Hành động'},

    'shots': {'list': '01_list.png', 'rowmenu': '03_rowmenu.png', 'filter': 'filter.png', 'filter_result': '04_filter_result.png',
              'create': '10_create.png', 'create_error': '11_create_error.png', 'edit': '12_edit.png',
              'delete': '13_delete.png', 'lock': '14_lock.png', 'unlock': '15_unlock.png', 'history': '16_history.png',
              'detail': '17_detail.png', 'export': '20_export.png', 'import_open': '21_import_open.png',
              'import_loaded': '22_import_loaded.png', 'import_validated': '23_import_validated.png', 'colcfg': '25_colcfg.png'},

    # lockName: đường/phố thật đang Hoạt động, CHƯA được dùng ở đâu (tra local_hrm_erp 28/09/2026, id 11607)
    # -> dòng có đủ 4 nút (Sửa, Xóa + ba chấm Khóa, Lịch sử).
    'capture': {'route': '/human/hamlets', 'menu': {'phanhe': 'DANH MỤC', 'nhom': 'Địa lý', 'muc': 'Đường/Phố'},
                'search': 'Tìm theo tên đường/phố', 'searchText': 'Đường', 'detailCol': 1,
                'lockName': 'Khuyến Lương',
                'create': True, 'lock': True},

    'import_test': {
        'cols': ['Tên đường/phố', 'Tỉnh/TP', 'Phường/xã'],
        'rows': [
            ['DOC-Phố Mẫu Một', 'Thành phố Hà Nội', 'Phường Cửa Nam'],
            ['DOC-Phố Mẫu Hai', 'Thành phố Hà Nội', 'Phường Hoàn Kiếm'],
            ['', 'Thành phố Hà Nội', 'Phường Cửa Nam'],
            ['DOC-Phố Mẫu Một', 'Thành phố Hà Nội', 'Phường Cửa Nam'],
            ['Đường Đinh Lễ', 'Tỉnh Cà Mau', 'Phường Hòa Thành'],
            ['DOC-Phố Mẫu Ba', 'Thành phố Đà Nẵng', 'Phường Cửa Nam'],
            ['DOC-Phố Mẫu Bốn', 'Tỉnh không tồn tại', 'Phường Cửa Nam'],
            ['DOC-Phố Mẫu Năm', 'Thành phố Hà Nội', ''],
        ],
    },

    'uml': {
        'mains': [('FR-01', 'Xem danh sách đường/phố', 'view'), ('FR-03', 'Thêm mới đường/phố', 'crud'),
                  ('FR-04', 'Chỉnh sửa đường/phố', 'crud'), ('FR-05', 'Xóa đường/phố', 'action'),
                  ('FR-06', 'Khóa / Mở khóa đường/phố', 'action'), ('FR-08', 'Import file đường/phố', 'io'),
                  ('FR-09', 'Xuất danh sách đường/phố ra Excel', 'io')],
        'subs': [('FR-02', 'Tìm kiếm và lọc đường/phố', 'view'), ('FR-10', 'Xem chi tiết đường/phố', 'view'),
                 ('FR-11', 'Tùy chỉnh cột hiển thị', 'view'), ('FR-07', 'Xem lịch sử thay đổi', 'view')],
        'rieng': [('FR-10', 'Xem chi tiết đường/phố', 'view')],
    },

    'srs': {
        'muc_dich': ['Là căn cứ nghiệm thu chức năng.',
                     'Làm rõ ràng buộc trùng tên đường/phố (duy nhất trong cùng Phường/xã, tính cả bản ghi Khóa), quy tắc Việt Nam (ẩn cấp Quận/Huyện), điều kiện Xóa (xóa hẳn, chỉ khi Hoạt động và chưa được dùng), Khóa / Mở khóa và quan hệ Quốc gia → Tỉnh/TP → (Quận/Huyện) → Phường/Xã → Đường/Phố.'],
        'quyen_truoc': ['Danh sách quyền sẽ được cập nhật sau khi có tài liệu phân quyền chi tiết của hệ thống. Tại thời điểm xây dựng SRS, màn hình chưa gắn quyền; mọi người dùng đã đăng nhập đều thực hiện được các chức năng.'],
        'quyen_rows': [['(chưa khai báo quyền nào)', 'Sẽ cập nhật sau khi có tài liệu phân quyền chi tiết']],
        'ma_tran': [['Chức năng', 'Người dùng đã đăng nhập']] + [[f, 'Chờ cập nhật theo ma trận phân quyền chi tiết'] for f in [
            'FR-01 Xem danh sách đường/phố', 'FR-02 Tìm kiếm và lọc', 'FR-03 Thêm mới đường/phố', 'FR-04 Chỉnh sửa đường/phố',
            'FR-05 Xóa đường/phố', 'FR-06 Khóa / Mở khóa đường/phố', 'FR-07 Xem lịch sử thay đổi', 'FR-08 Import file đường/phố',
            'FR-09 Xuất danh sách ra Excel', 'FR-10 Xem chi tiết đường/phố', 'FR-11 Tùy chỉnh cột hiển thị']],
        'ma_tran_widths': [2.4, 2.4],
        'fr': [
            {'ten': 'Xem danh sách đường/phố',
             'qtc': 'Màn Danh sách, Sắp xếp dữ liệu bảng, Phân trang và Cấu hình cột. Chỉ bổ sung các quy tắc riêng của Danh mục Đường/Phố tại phần mô tả chi tiết.',
             'gioi_thieu': [['Tên chức năng', 'Xem danh sách đường/phố'],
                            ['Mô tả', 'Hiển thị toàn bộ đường/phố (cả Hoạt động lẫn Khóa), có phân trang và sắp xếp.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Điều kiện ban đầu', 'Người dùng đã đăng nhập vào hệ thống.'],
                            ['Dòng sự kiện chính', '1. Người dùng vào menu Danh mục → Địa lý → Đường/Phố.\n2. Hệ thống nạp trang đầu tiên của danh sách (10 dòng), bản ghi tạo gần nhất trên cùng.\n3. Bảng hiển thị dữ liệu kèm tổng số bản ghi.'],
                            ['Dòng sự kiện phụ', '• Không có bản ghi khớp → bảng hiện “Không có dữ liệu phù hợp bộ lọc.”\n• Phiên đăng nhập hết hạn → điều hướng về màn đăng nhập.']],
             'anh': [('list', 'Màn Danh mục Đường/Phố lúc mới truy cập')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Mô tả'],
                    ['1', 'STT', 'Table/Grid', 'Read-only', 'Số thứ tự, chạy liên tục qua các trang. Luôn hiển thị, không ẩn được.'],
                    ['2', 'Tên đường/phố', 'Table/Grid', 'Read-only', 'Luôn hiển thị, sắp xếp được. Bấm vào tên mở cửa sổ Xem (xem 2.10).'],
                    ['3', 'Phường/xã', 'Table/Grid', 'Read-only', 'Phường/xã trực thuộc.'],
                    ['4', 'Quận/Huyện/Thị xã', 'Table/Grid', 'Read-only', 'Trống với địa chỉ Việt Nam. Mặc định ẩn.'],
                    ['5', 'Tỉnh/TP', 'Table/Grid', 'Read-only', 'Tỉnh/TP của phường/xã.'],
                    ['6', 'Quốc gia', 'Table/Grid', 'Read-only', 'Mặc định ẩn.'],
                    ['7', 'Người cập nhật', 'Table/Grid', 'Read-only', 'Mặc định ẩn.'],
                    ['8', 'Ngày cập nhật', 'Table/Grid', 'Read-only', 'dd/mm/yyyy hh:mm. Mặc định ẩn, sắp xếp được.'],
                    ['9', 'Người tạo', 'Table/Grid', 'Read-only', 'Người đã thêm bản ghi.'],
                    ['10', 'Ngày tạo', 'Table/Grid', 'Read-only', 'dd/mm/yyyy hh:mm, sắp xếp được.'],
                    ['11', 'Trạng thái', 'Badge', 'Read-only', 'Hoạt động hoặc Khóa.'],
                    ['12', 'Hành động', 'Table/Grid', 'Read-only', 'Sửa (khi Hoạt động), Xóa (khi Hoạt động và chưa được dùng ở ' + NOI_DUNG + '), Khóa / Mở khóa, Lịch sử. Từ 4 nút trở lên thì 2 nút đầu hiện thẳng, còn lại trong nút ba chấm.'],
                    ['13', 'Nút Tạo mới', 'Button', 'Enable', 'Mở cửa sổ Tạo đường/phố.'],
                    ['14', 'Nút Xuất Excel', 'Button', 'Enable', 'Mở cửa sổ Chọn trường xuất file (xem 2.9).'],
                    ['15', 'Nút Import Excel', 'Button', 'Enable', 'Mở cửa sổ Import đường/phố (xem 2.8).'],
                    ['16', 'Biểu tượng Cấu hình cột hiển thị', 'Icon Button', 'Enable', 'Mở cửa sổ Tuỳ chỉnh cột (xem 2.11).'],
                    ['17', 'Phân trang', 'Pagination', 'Enable', 'Số dòng/trang 5 / 10 / 20 / 50 / 100, mặc định 10.']],
             'ui_widths': [0.6, 1.4, 0.9, 0.8, 3],
             'events': [['Mở màn hình', 'System', 'After:\n– Nạp trang đầu (cả Hoạt động lẫn Khóa), hiển thị tổng số bản ghi.'],
                        ['Bấm tiêu đề cột sắp xếp được', 'Click', 'After:\n– Đổi chiều sắp xếp và nạp lại danh sách từ trang 1.'],
                        ['Chuyển trang', 'Click', 'Before:\n– Giữ nguyên bộ lọc và thứ tự sắp xếp.\nAfter:\n– Nạp dữ liệu trang mới, số thứ tự tiếp tục liên tục.'],
                        ['Đổi số dòng mỗi trang', 'Change', 'After:\n– Quay về trang 1 và nạp lại theo số dòng mới.']]},
            {'ten': 'Tìm kiếm và lọc',
             'qtc': 'Kịch bản tìm kiếm, Bộ lọc, Dropdown, Phân trang. Chỉ bổ sung các tiêu chí tìm kiếm/lọc riêng của Danh mục Đường/Phố.',
             'gioi_thieu': [['Tên chức năng', 'Tìm kiếm và lọc danh sách'],
                            ['Mô tả', 'Thu hẹp danh sách bằng ô tìm kiếm nhanh, ô Tỉnh/TP, ô Phường/xã (hai ô lọc phụ thuộc nhau) và ô Trạng thái.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Điều kiện ban đầu', 'Đang ở màn Danh mục Đường/Phố.'],
                            ['Dòng sự kiện chính', '1. Người dùng nhập từ khóa và bấm Tìm kiếm / Enter, hoặc chọn Tỉnh/TP / Phường/xã / Trạng thái (lọc ngay).\n2. Hệ thống áp đồng thời mọi tiêu chí và nạp lại danh sách từ trang 1.'],
                            ['Dòng sự kiện phụ', '• Đổi Tỉnh/TP → ô Phường/xã bị xóa trắng và nạp lại theo tỉnh mới.\n• Chưa chọn Tỉnh/TP → ô Phường/xã không có lựa chọn.\n• Bỏ trống Trạng thái → hiện cả Hoạt động lẫn Khóa.\n• Không có kết quả → bảng hiện thông báo không có dữ liệu.\n• Bấm Làm mới → xóa hết tiêu chí VÀ nạp lại danh sách đầy đủ ngay.']],
             'anh': [('filter', 'Khu vực tìm kiếm và lọc của màn Danh mục Đường/Phố')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Phạm vi', 'Mô tả'],
                    ['1', 'Ô tìm kiếm nhanh', 'Textbox', 'Enable', '0–255 ký tự', 'Placeholder “Tìm theo tên đường/phố”. Tìm theo TÊN (khớp một phần).'],
                    ['2', 'Tỉnh/TP', 'Dropdown', 'Enable', 'Tỉnh/TP đang Hoạt động', 'Nhãn nổi. Bỏ trống thì hiện mọi tỉnh/TP.'],
                    ['3', 'Phường/xã', 'Dropdown', 'Enable', 'Phường/xã của tỉnh/TP đã chọn', 'Nhãn nổi. Bị xóa trắng khi đổi Tỉnh/TP.'],
                    ['4', 'Trạng thái', 'Dropdown', 'Enable', 'Hoạt động / Khóa', 'Nhãn nổi. Bỏ trống thì hiện cả hai trạng thái.'],
                    ['5', 'Nút Tìm kiếm', 'Button', 'Enable', '–', 'Áp dụng các tiêu chí.'],
                    ['6', 'Nút Làm mới', 'Button', 'Enable', '–', 'Xóa hết tiêu chí VÀ nạp lại danh sách ngay.']],
             'ui_widths': [0.6, 1.2, 0.8, 0.7, 1.1, 2.6],
             'events': [['Bấm Tìm kiếm / Enter', 'Click', 'After:\n– Áp đồng thời các tiêu chí theo kiểu “và”, nạp lại bảng từ trang 1.'],
                        ['Chọn Tỉnh/TP', 'Change', 'After:\n– Xóa trắng ô Phường/xã, nạp danh sách phường/xã của tỉnh mới, nạp lại bảng từ trang 1.'],
                        ['Chọn Phường/xã / Trạng thái', 'Change', 'After:\n– Lọc ngay, nạp lại bảng từ trang 1.'],
                        ['Bấm Làm mới', 'Click', 'After:\n– Xóa trắng mọi tiêu chí VÀ nạp lại danh sách đầy đủ.']]},
            {'ten': 'Thêm mới đường/phố', 'uc': 'uc_fr03',
             'qtc': 'Màn Thêm mới, Validate dữ liệu, Thông báo và UI/UX. Logic ghi lịch sử áp dụng theo SRS Các quy tắc chung - Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Thêm mới đường/phố'],
                            ['Mô tả', 'Thêm một đường/phố mới thông qua cửa sổ nhập liệu.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập (chờ cập nhật theo phân quyền chi tiết).'],
                            ['Điều kiện ban đầu', 'Đang ở màn Danh mục Đường/Phố.'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm Tạo mới.\n2. Hệ thống mở cửa sổ “Tạo đường/phố”, Trạng thái mặc định Hoạt động.\n3. Người dùng nhập Tên đường/phố, chọn Quốc gia → Tỉnh/TP → (Quận/Huyện/Thị xã nếu khác Việt Nam) → Phường/xã và bấm Lưu.\n4. Hệ thống kiểm tra dữ liệu, ghi bản ghi mới theo Trạng thái đã chọn và ghi lịch sử Tạo mới.\n5. Cửa sổ đóng, danh sách nạp lại, báo “Thêm mới thành công”.'],
                            ['Dòng sự kiện phụ', '• Thiếu Tên hoặc Phường/xã, hoặc trùng tên → báo lỗi đỏ dưới ô + toast “Vui lòng kiểm tra lại dữ liệu nhập”, cửa sổ KHÔNG đóng.\n• Chọn quốc gia khác Việt Nam → hiện thêm ô Quận/Huyện/Thị xã (bắt buộc).\n• Bấm “Lưu và tiếp tục” → ghi bản ghi rồi giữ cửa sổ mở với các ô trống, Trạng thái về Hoạt động.\n• Bấm Đóng khi đã nhập dở → hỏi “Thông tin chưa lưu” (Thoát / Ở lại).'],
                            ['Yêu cầu đặc biệt', 'Cửa sổ có ba nút: Lưu, Lưu và tiếp tục, Đóng.']],
             'menu_them': ' => Tạo mới {icon:btn_taomoi}',
             'ghi_chu_layout': 'Cửa sổ Tạo đường/phố được mở ngay trên màn hình danh sách.',
             'anh': [('create', 'Cửa sổ Tạo đường/phố'), ('create_error', 'Lỗi đỏ ngay dưới ô còn thiếu')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Phạm vi', 'Bắt buộc', 'Mô tả'],
                    ['1', 'Tên đường/phố', 'Textbox', 'Enable', '1–255 ký tự', 'Có', 'Duy nhất trong cùng Phường/xã (tính cả bản ghi Khóa). Bỏ trống “Bắt buộc phải nhập”; trùng “Tên đường/phố này đã tồn tại trong phường/xã”; quá dài “Vui lòng nhập tối đa 255 ký tự.”'],
                    ['2', 'Quốc gia', 'Dropdown', 'Enable', 'Quốc gia đang Hoạt động', 'Có', 'Việt Nam (hoặc chưa chọn) → ẩn ô Quận/Huyện/Thị xã. Đổi Quốc gia xóa trắng các ô cấp dưới.'],
                    ['3', 'Tỉnh/TP', 'Dropdown', 'Enable', 'Tỉnh/TP Hoạt động của quốc gia đã chọn', 'Có', 'Chưa chọn quốc gia hiện “Vui lòng chọn quốc gia trước”.'],
                    ['4', 'Quận/Huyện/Thị xã', 'Dropdown', 'Ẩn/Enable', 'Quận/huyện của tỉnh/TP đã chọn', 'Có khi khác Việt Nam', 'Chỉ hiện khi Quốc gia khác Việt Nam. Chưa chọn tỉnh hiện “Vui lòng chọn tỉnh/TP trước”.'],
                    ['5', 'Phường/xã', 'Dropdown', 'Enable', 'Phường/xã Hoạt động của tỉnh/TP (VN) hoặc quận/huyện (nước khác)', 'Có', 'Bỏ trống “Bắt buộc phải nhập”.'],
                    ['6', 'Trạng thái', 'Dropdown', 'Enable', 'Hoạt động / Khóa', 'Không', 'Mặc định Hoạt động, không xoá trống được.'],
                    ['7', 'Nút Lưu', 'Button', 'Enable', '', '', 'Ghi bản ghi rồi đóng cửa sổ.'],
                    ['8', 'Nút Lưu và tiếp tục', 'Button', 'Enable', '', '', 'Ghi bản ghi rồi giữ cửa sổ mở, xóa trắng các ô để nhập tiếp.'],
                    ['9', 'Nút Đóng', 'Button', 'Enable', '', '', 'Hủy bỏ, không ghi gì.']],
             'ui_widths': [0.6, 1.3, 0.8, 0.6, 1.1, 0.5, 2.3],
             'events': [['Bấm nút Tạo mới', 'Click', 'After:\n– Mở cửa sổ nhập liệu với các ô trống, Trạng thái = Hoạt động, ô Quận/Huyện/Thị xã đang ẩn.'],
                        ['Chọn Quốc gia', 'Change', 'After:\n– Xóa trắng Tỉnh/TP, Quận/Huyện, Phường/xã.\n– Khác Việt Nam → hiện ô Quận/Huyện/Thị xã.'],
                        ['Chọn Tỉnh/TP', 'Change', 'After:\n– Việt Nam: nạp danh sách Phường/xã của tỉnh.\n– Nước khác: nạp danh sách Quận/Huyện, xóa trắng Phường/xã.'],
                        ['Bấm Lưu', 'Click', 'During:\n– Kiểm tra Tên (bắt buộc, độ dài), Phường/xã (bắt buộc), trùng tên trong cùng Phường/xã.\n– Có lỗi → báo đỏ dưới ô, không thực hiện After.\nAfter:\n– Ghi bản ghi mới, ghi lịch sử Tạo mới.\n– Đóng cửa sổ, nạp lại danh sách, báo “Thêm mới thành công”.'],
                        ['Bấm Lưu và tiếp tục', 'Click', 'During:\n– Như nút Lưu.\nAfter:\n– Ghi bản ghi, nạp lại danh sách, xóa trắng các ô (Trạng thái về Hoạt động), GIỮ cửa sổ mở.'],
                        ['Bấm Đóng', 'Click', 'After:\n– Chưa nhập gì → đóng cửa sổ. Đã nhập → hỏi “Thông tin chưa lưu”.']]},
            {'ten': 'Chỉnh sửa đường/phố', 'uc': 'uc_fr04',
             'qtc': 'Validate dữ liệu, Thông báo, Quy định chung về danh mục và Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Chỉnh sửa đường/phố'],
                            ['Mô tả', 'Sửa thông tin một đường/phố đã có. Dùng chung cửa sổ với Thêm mới.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Điều kiện ban đầu', 'Đường/phố đang ở trạng thái Hoạt động.'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm biểu tượng bút chì ở dòng cần sửa.\n2. Hệ thống mở cửa sổ “Sửa đường/phố” với dữ liệu hiện tại.\n3. Người dùng sửa và bấm Lưu.\n4. Hệ thống kiểm tra, ghi thay đổi và ghi lịch sử.\n5. Cửa sổ đóng, báo “Cập nhật thành công”.'],
                            ['Dòng sự kiện phụ', '• Giữ nguyên tên của chính bản ghi → không báo trùng.\n• Trùng tên với đường/phố khác cùng Phường/xã → báo “Tên đường/phố này đã tồn tại trong phường/xã”.\n• Đổi Trạng thái sang Khóa rồi Lưu → bản ghi chuyển sang Khóa, lịch sử ghi “Thay đổi trạng thái”.\n• Bản ghi vừa bị người khác khóa → báo “Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.”']],
             'menu_them': ' => Sửa {icon:btn_sua}',
             'anh': [('edit', 'Cửa sổ Sửa đường/phố')],
             'events': [['Bấm biểu tượng bút chì', 'Click', 'Before:\n– Bản ghi đã Khóa thì nút không hiển thị.\nAfter:\n– Mở cửa sổ với dữ liệu hiện tại, các ô cấp trên điền sẵn theo phường/xã của bản ghi.'],
                        ['Bấm Lưu', 'Click', 'Before:\n– Bản ghi đang Khóa → máy chủ từ chối, báo “Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.”\nDuring:\n– Kiểm tra như Thêm mới, bỏ qua trùng với chính bản ghi.\nAfter:\n– Ghi thay đổi, ghi lịch sử “Thay đổi thông tin” (đổi Trạng thái ghi dòng “Thay đổi trạng thái” riêng), báo “Cập nhật thành công”.']]},
            {'ten': 'Xóa đường/phố', 'uc': 'uc_fr05',
             'qtc': 'Quy tắc Xóa, Thông báo, Quy định chung về danh mục và Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Xóa đường/phố'],
                            ['Mô tả', 'Xóa hẳn một đường/phố chưa được dùng ở đâu.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Điều kiện ban đầu', 'Đường/phố đang Hoạt động và chưa được chọn làm địa chỉ ở ' + NOI_DUNG + '.'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm biểu tượng thùng rác.\n2. Hệ thống hiện hộp “Xóa Đường/Phố” nêu rõ tên bản ghi.\n3. Người dùng bấm Xóa.\n4. Hệ thống kiểm tra lại điều kiện, xóa hẳn bản ghi, báo “Xoá đường/phố thành công”, nạp lại danh sách.'],
                            ['Dòng sự kiện phụ', '• Bấm Hủy → đóng hộp, không thay đổi.\n• Đường/phố đã được dùng hoặc đang Khóa → nút Xóa KHÔNG hiển thị.\n• Vừa được dùng trong lúc mở hộp → báo “Đường/phố đang được sử dụng, không thể xóa.”\n• Vừa bị người khác khóa → báo “Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.”\n• Vừa bị người khác xóa → báo “Trạng thái đã bị thay đổi. Vui lòng load lại trang”.\n• Lỗi khác → báo “Xoá đường/phố thất bại”.']],
             'menu_them': ' => Xóa {icon:btn_xoa}',
             'anh': [('delete', 'Hộp xác nhận xóa đường/phố'), ('rowmenu', 'Các nút ở cột Hành động')],
             'events': [['Bấm biểu tượng thùng rác', 'Click', 'Before:\n– Chỉ hiển thị khi bản ghi đang Hoạt động và chưa được dùng.\nAfter:\n– Hiện hộp xác nhận kèm tên bản ghi.'],
                        ['Bấm Xóa', 'Click', 'During:\n– Kiểm tra lại: bản ghi còn tồn tại, không bị Khóa, chưa được dùng ở ' + NOI_DUNG + '. Vi phạm → báo lỗi tương ứng, không xóa.\nAfter:\n– Xóa hẳn bản ghi, nạp lại danh sách, báo “Xoá đường/phố thành công”.'],
                        ['Bấm Hủy', 'Click', 'After:\n– Đóng hộp, không thay đổi.']]},
            {'ten': 'Khóa / Mở khóa đường/phố', 'uc': 'uc_fr06',
             'qtc': 'Quy tắc Khóa/Mở khóa, Thông báo, Quy định chung về danh mục và Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Khóa / Mở khóa đường/phố'],
                            ['Mô tả', 'Đổi trạng thái đường/phố giữa Hoạt động và Khóa. Bản ghi đã Khóa vẫn nằm trong danh mục nhưng không chọn được ở màn khác; khóa được cả khi đang được dùng.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Điều kiện ban đầu', 'Bản ghi cần đổi trạng thái đang có trong danh sách.'],
                            ['Dòng sự kiện chính', '1. Người dùng chọn Khóa (hoặc Mở khóa) ở cột Hành động.\n2. Hệ thống hiện hộp xác nhận “Khóa Đường/Phố” / “Mở khóa Đường/Phố” nêu rõ tên bản ghi.\n3. Người dùng xác nhận.\n4. Hệ thống đổi trạng thái, ghi lịch sử, báo “Khóa thành công” / “Mở khóa thành công”.'],
                            ['Dòng sự kiện phụ', '• Bấm Hủy → không thay đổi.\n• Sau khi Khóa, nút Sửa và Xóa biến mất; sau khi Mở khóa, nút Sửa hiện lại (Xóa hiện lại nếu chưa được dùng).\n• Bản ghi đã bị người khác đổi trạng thái hoặc xóa → báo “Trạng thái đã bị thay đổi. Vui lòng load lại trang”.']],
             'menu_them': ' => Khóa / Mở khóa',
             'anh': [('lock', 'Hộp xác nhận khóa đường/phố'), ('unlock', 'Hộp xác nhận mở khóa đường/phố')],
             'events': [['Chọn Khóa / Mở khóa', 'Click', 'After:\n– Hiện hộp xác nhận kèm tên bản ghi.'],
                        ['Xác nhận', 'Click', 'During:\n– Bản ghi đã ở trạng thái đích hoặc không còn tồn tại → báo “Trạng thái đã bị thay đổi. Vui lòng load lại trang”, dừng.\nAfter:\n– Đổi trạng thái, KHÔNG xóa dữ liệu, ghi lịch sử “Thay đổi trạng thái”, cập nhật cột Trạng thái và các nút.'],
                        ['Bấm Hủy', 'Click', 'After:\n– Đóng hộp, không thay đổi.']]},
            {'ten': 'Xem lịch sử thay đổi',
             'qtc': 'Quy tắc ghi lịch sử và hiển thị lịch sử. Chỉ bổ sung thông tin riêng của Danh mục Đường/Phố nếu có.',
             'gioi_thieu': [['Tên chức năng', 'Xem lịch sử thay đổi'],
                            ['Mô tả', 'Liệt kê các lần thay đổi của một đường/phố, kèm giá trị cũ → mới, người thực hiện và thời điểm. Phường/xã, Tỉnh/TP, Quốc gia hiển thị bằng tên; Khóa / Mở khóa hiện là Thay đổi trạng thái.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Dòng sự kiện chính', '1. Người dùng chọn Lịch sử ở cột Hành động, hoặc mở cửa sổ Xem đường/phố.\n2. Hệ thống mở cửa sổ “Lịch sử thay đổi: <tên>”, mốc mới nhất ở trên cùng.'],
                            ['Dòng sự kiện phụ', '• Bản ghi chưa từng thay đổi → “Chưa có lịch sử thao tác nào.”\n• Có bộ lọc theo loại hành động, người thực hiện, thời gian.']],
             'menu_them': ' => Lịch sử',
             'anh': [('history', 'Cửa sổ Lịch sử thay đổi của đường/phố')]},
            {'ten': 'Import file đường/phố', 'uc': 'uc_fr08',
             'qtc': 'Quy tắc Import file, Validate dữ liệu, Thông báo và Quy định chung về danh mục. Chỉ bổ sung mapping/validation riêng của Danh mục Đường/Phố.',
             'gioi_thieu': [['Tên chức năng', 'Import file đường/phố'],
                            ['Mô tả', 'Thêm nhiều đường/phố cùng lúc từ file Excel mẫu, có bước Validate trước khi ghi.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Điều kiện ban đầu', 'Đang ở màn Danh mục Đường/Phố và đã chuẩn bị file theo mẫu.'],
                            ['Dòng sự kiện chính', '1. Bấm Import Excel.\n2. Bấm Tải file mẫu (Mau_import_duong_pho.xlsx), điền dữ liệu.\n3. Bấm Chọn file Excel rồi Load lên bảng.\n4. Bấm Validate; hệ thống kiểm tra từng dòng như quy tắc Thêm mới (mục 2.3), khóa dòng hợp lệ.\n5. Sửa dòng lỗi rồi Validate lại, hoặc bấm Bỏ dòng lỗi.\n6. Bấm Import; hệ thống ghi các dòng hợp lệ, báo “Import thành công N đường/phố.”, đóng cửa sổ và nạp lại danh sách.'],
                            ['Dòng sự kiện phụ', '• File không phải .xlsx/.xls → “Vui lòng chọn file .xlsx hoặc .xls”.\n• Quá 500 dòng → “File có X dòng dữ liệu, vượt quá giới hạn 500 dòng mỗi lần import. Vui lòng tách file và import nhiều lần.”\n• Còn dòng lỗi → nút Import không bấm được.'],
                            ['Yêu cầu đặc biệt', 'Validate không ghi dữ liệu. Bản ghi import luôn ở trạng thái Hoạt động, người tạo là người thực hiện. Phường/xã tra theo cặp TÊN Tỉnh/TP + TÊN Phường/xã; không tự tạo tỉnh/phường mới.']],
             'menu_them': ' => Import Excel {icon:btn_import}',
             'ghi_chu_layout': 'Cửa sổ Import được mở ngay trên màn hình danh sách.',
             'anh': [('import_open', 'Cửa sổ Import đường/phố khi vừa mở'), ('import_loaded', 'Dữ liệu đã được load lên bảng xem trước'),
                     ('import_validated', 'Kết quả Validate — mỗi dòng lỗi nêu rõ lý do')],
             'bang_them': [('Quy tắc kiểm tra riêng của file Import', [['Cột', 'Quy tắc / thông báo lỗi'],
                            ['Tên đường/phố *', 'Bắt buộc (“Tên đường/phố không được để trống”), tối đa 255 ký tự (“Tên đường/phố tối đa 255 ký tự”), không trùng trong file (“Đường/phố bị trùng với dòng N trong file”), không trùng hệ thống trong cùng phường/xã, kể cả bản ghi Khóa (“Đường/phố này đã tồn tại trong phường/xã đã chọn”).'],
                            ['Tỉnh/TP *', 'Bắt buộc (“Tỉnh/TP không được để trống”), chọn trong danh sách sổ xuống; ghi sai báo “Không tìm thấy tỉnh/TP: X”; tên có ở nhiều quốc gia báo “Tên tỉnh/TP "X" đang có ở nhiều quốc gia, không xác định được”.'],
                            ['Phường/xã *', 'Bắt buộc (“Phường/xã không được để trống”), gõ tay đúng tên phường/xã thuộc tỉnh/TP cùng dòng; sai báo “Không tìm thấy phường/xã "Y" thuộc tỉnh/TP X”; tên trùng nhau trong tỉnh báo “Tên phường/xã "Y" đang có nhiều bản ghi trong X, không xác định được”.']], [1.2, 4])]},
            {'ten': 'Xuất danh sách ra Excel', 'uc': 'uc_fr09',
             'qtc': 'Quy tắc Excel và Cấu hình cột. Chỉ bổ sung danh sách trường được phép xuất riêng của Danh mục Đường/Phố.',
             'gioi_thieu': [['Tên chức năng', 'Xuất danh sách đường/phố ra Excel'],
                            ['Mô tả', 'Xuất kết quả đang lọc ra file Excel, cho phép chọn trường và thứ tự cột.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Dòng sự kiện chính', '1. Bấm Xuất Excel.\n2. Hệ thống mở cửa sổ “Chọn trường xuất file”, tích sẵn đúng các cột đang hiển thị trên bảng.\n3. Người dùng tích chọn và kéo ☰ để sắp thứ tự.\n4. Bấm Xuất file; hệ thống tải danh_muc_duong_pho.xlsx theo đúng bộ lọc (kể cả Trạng thái) và thứ tự trường, báo “Xuất Excel thành công”.'],
                            ['Dòng sự kiện phụ', '• Bỏ chọn hết trường → nút Xuất file không bấm được.\n• Bấm Đóng → không xuất gì.'],
                            ['Yêu cầu đặc biệt', 'File chứa toàn bộ kết quả lọc (tối đa 10,000 dòng), không giới hạn ở trang đang xem. Chỉ xuất Excel.']],
             'menu_them': ' => Xuất Excel {icon:btn_xuatexcel}',
             'anh': [('export', 'Cửa sổ Chọn trường xuất file')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
                    ['1', 'Danh sách trường', 'Checkbox chọn nhiều', 'Enable', 'Tích sẵn cột đang hiển thị', 'Tên đường/phố, Phường/xã, Quận/Huyện/Thị xã, Tỉnh/TP, Quốc gia, Trạng thái, Người tạo, Ngày tạo, Người cập nhật, Ngày cập nhật. Kéo ☰ đổi thứ tự.'],
                    ['2', 'Nút Chọn tất cả / Bỏ chọn hết', 'Button', 'Enable', 'Hiển thị', 'Tích / bỏ tích toàn bộ.'],
                    ['3', 'Nút Xuất file', 'Button', 'Enable/Disable', 'Mờ khi chưa chọn trường', 'Sinh file và tải về.'],
                    ['4', 'Nút Đóng', 'Button', 'Enable', 'Hiển thị', 'Đóng cửa sổ.']],
             'ui_widths': [0.6, 1.5, 1, 0.8, 1.2, 2.6]},
            {'ten': 'Xem chi tiết đường/phố', 'uc': 'uc_fr10',
             'qtc': 'Màn Xem chi tiết và Phân quyền.',
             'gioi_thieu': [['Tên chức năng', 'Xem chi tiết đường/phố'],
                            ['Mô tả', 'Cửa sổ “Xem đường/phố” hiển thị Tên đường/phố, Quốc gia, Tỉnh/TP, Quận/Huyện/Thị xã (nếu có), Phường/xã, Trạng thái ở chế độ chỉ đọc, kèm khối Lịch sử.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm tên đường/phố ở danh sách.\n2. Hệ thống mở cửa sổ Xem, chỉ có nút Đóng.']],
             'anh': [('detail', 'Cửa sổ Xem đường/phố ở chế độ chỉ đọc')]},
            {'ten': 'Tùy chỉnh cột hiển thị',
             'qtc': 'Tùy chỉnh cột.',
             'gioi_thieu': [['Tên chức năng', 'Tùy chỉnh cột hiển thị'],
                            ['Mô tả', 'Bật/tắt và sắp xếp thứ tự cột của bảng; cấu hình lưu riêng theo người dùng.'],
                            ['Yêu cầu đặc biệt', 'Cột STT, Tên đường/phố, Hành động bị khóa. Mặc định ẩn: Quận/Huyện/Thị xã, Quốc gia, Người cập nhật, Ngày cập nhật.']],
             'menu_them': ' => Cấu hình cột {icon:btn_cauhinhcot}',
             'anh': [('colcfg', 'Cửa sổ Tuỳ chỉnh cột')]},
        ],
        'quy_tac': [
            ('BR-01', 'Ràng buộc trùng tên',
             [
              'Tên đường/phố không được trùng trong cùng một Phường/xã; cùng tên ở phường/xã khác vẫn hợp lệ.',
              'Việc kiểm tra trùng tính cả đường/phố đang Khóa. Đường/phố đã xóa hẳn không còn tính.',
              'Thông báo khi trùng: “Tên đường/phố này đã tồn tại trong phường/xã”.',
             ],
             ['Thêm mới đường/phố', 'Chỉnh sửa đường/phố', 'Import file đường/phố']),
            ('BR-02', 'Mối quan hệ với các cấp địa chỉ khác',
             [
              'Mỗi đường/phố thuộc đúng một phường/xã; chỉ Phường/xã được lưu, Quốc gia – Tỉnh/TP – Quận/Huyện là ô chọn để lọc.',
              'Quốc gia Việt Nam không dùng cấp Quận/Huyện (ô bị ẩn), phường/xã lọc theo Tỉnh/TP; quốc gia khác phải chọn Quận/Huyện/Thị xã trước rồi mới chọn được Phường/xã.',
              'Đổi cấp trên thì các ô cấp dưới bị xóa trắng.',
             ],
             ['Thêm mới đường/phố', 'Chỉnh sửa đường/phố']),
            ('BR-03', 'Danh mục cấp trên đã khóa',
             [
              'Ô chọn chỉ liệt kê danh mục cấp trên đang Hoạt động.',
              'Đường/phố đang dùng phường/xã (quận/huyện, tỉnh/TP, quốc gia) đã khóa vẫn giữ và hiển thị đúng tên kèm 🔒.',
             ],
             ['Chỉnh sửa đường/phố', 'Xem chi tiết đường/phố']),
            ('BR-04', 'Điều kiện xóa',
             [
              'Chỉ xóa được đường/phố đang Hoạt động và CHƯA được chọn làm địa chỉ ở ' + NOI_DUNG + '; ngược lại nút Xóa bị ẩn.',
              'Máy chủ kiểm tra lại lúc xóa: đã được dùng → “Đường/phố đang được sử dụng, không thể xóa.”; đang Khóa → “Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.”',
              'Xóa là xóa hẳn bản ghi khỏi hệ thống, không có thao tác khôi phục. Đường/phố đã được dùng thì dùng Khóa thay cho Xóa.',
             ],
             ['Xóa đường/phố']),
            ('BR-05', 'Đường/phố đang Khóa',
             [
              'Không sửa, không xóa được; phải Mở khóa trước. Khóa được cả khi đường/phố đang được dùng.',
              'Máy chủ chặn lưu / xóa bản ghi đang Khóa: “Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.”',
              'Đường/phố Khóa không còn chọn được ở các màn khác; bản ghi đang dùng vẫn hiển thị đúng tên kèm 🔒.',
             ],
             ['Chỉnh sửa đường/phố', 'Xóa đường/phố', 'Khóa / Mở khóa đường/phố']),
            ('BR-06', 'Thao tác đồng thời',
             [
              'Hai người cùng Khóa / Mở khóa / Xóa một đường/phố: người bấm sau nhận thông báo “Trạng thái đã bị thay đổi. Vui lòng load lại trang”, thao tác không được thực hiện lại, lịch sử không bị ghi trùng.',
             ],
             ['Xóa đường/phố', 'Khóa / Mở khóa đường/phố']),
            ('BR-07', 'Giới hạn Import',
             [
              'Mỗi lần nhập tối đa 500 dòng; phải Validate trước, bước Validate không ghi dữ liệu.',
              'Phường/xã tra theo cặp tên Tỉnh/TP + Phường/xã, không tự tạo mới; tên trùng nhiều bản ghi thì báo “… không xác định được”.',
              'Đường/phố nhập từ Excel luôn ở trạng thái Hoạt động.',
             ],
             ['Import file đường/phố']),
            ('BR-08', 'Ghi lịch sử thay đổi',
             [
              'Mọi thao tác Tạo mới, Thay đổi thông tin, Khóa, Mở khóa đều ghi lịch sử kèm người thực hiện.',
              'Đổi Trạng thái ngay trong cửa sổ Sửa được ghi thành dòng “Thay đổi trạng thái” riêng.',
             ],
             ['Xem lịch sử thay đổi']),
        ],
    },
}

# ---- Lỗi code phát hiện khi rà (KHÔNG sửa code, báo user) ----
CFG['loi_code'] = [
    'Ô chọn Đường/Phố ở các form địa chỉ khác dùng AddressController (app/Http/Controllers/Api/V1/AddressController.php, level = 4) vẫn trả CẢ đường/phố đang Khóa (không lọc status, không trả is_locked) → đường/phố đã khóa vẫn chọn mới được và không có 🔒.',
    'Form Khách hàng (Modules/Assign/Services/CustomerService::hamlets) chỉ lấy đường/phố Hoạt động và không nhận include_ids → khách hàng đang giữ một đường/phố vừa bị Khóa sẽ MẤT giá trị ở ô Đường/Phố khi mở Sửa (không hiện tên kèm 🔒 như quy tắc danh mục khoá).',
    'Import: số dòng trong câu “Đường/phố bị trùng với dòng N trong file” không khớp chỗ nào người dùng nhìn thấy (HamletService::validateRows dùng $index + 2): cột # của bảng xem trước đánh $index + 1 (V2BaseImportModal.vue), còn trong file Excel dòng dữ liệu đầu là hàng 3.',
    'Import tra Tỉnh/TP và Phường/xã theo tên trên TOÀN BỘ bảng provinces / wards, kể cả bản ghi đã Khóa (HamletService::importSnapshot) — gõ tên một phường/xã đã khóa vẫn Validate hợp lệ và tạo được đường/phố thuộc phường/xã đã khóa, trong khi cửa sổ Tạo mới chỉ cho chọn phường/xã đang Hoạt động.',
    'Cửa sổ Tạo/Sửa: Quốc gia, Tỉnh/TP, Quận/Huyện có dấu * nhưng payload chỉ gửi name + ward_id + status và CreateHamletRequest chỉ bắt buộc name, ward_id — bỏ trống các ô cấp trên thì lỗi “Bắt buộc phải nhập” chỉ hiện dưới ô Phường/xã, không hiện dưới ô đang thiếu.',
    'Thông báo xóa thành công lệch chính tả giữa 2 tầng: FE hiện “Xoá đường/phố thành công” (oa), BE trả “Xóa đường/phố thành công” (óa). Người dùng chỉ thấy câu của FE — tài liệu ghi theo FE.',
]

# ---- Case mới nhóm IX: Khóa / Mở khóa ----
_TC_KHOA = [
    ('Hộp xác nhận Khóa nêu đúng tên bản ghi', 'P0', 'Đường/phố X đang Hoạt động.',
     '1. Ở cột Hành động dòng X, bấm Khóa (trong nút ba chấm "Hành động khác" nếu dòng có 4 nút)\n2. Đọc nội dung hộp xác nhận',
     '', '- Hộp có tiêu đề "Khóa Đường/Phố", câu "Bạn có chắc muốn khóa đường/phố "X"?"\n- Có hai nút Khóa và Hủy'),
    ('Khóa thành công', 'P0', 'Đang mở hộp xác nhận khóa đường/phố X.',
     '1. Bấm Khóa\n2. Quan sát dòng X trên bảng', '',
     '- Báo "Khóa thành công"\n- X VẪN nằm trong danh sách, cột Trạng thái đổi thành Khóa\n- Cột Hành động của X chỉ còn Mở khóa và Lịch sử (không còn Sửa, Xóa)'),
    ('Bấm Hủy ở hộp Khóa thì không đổi', 'P1', 'Đang mở hộp xác nhận khóa đường/phố X.',
     '1. Bấm Hủy\n2. Xem lại dòng X', '', '- Hộp đóng, X vẫn ở trạng thái Hoạt động\n- Không có thông báo thành công nào'),
    ('Khóa được cả đường/phố đang được dùng', 'P0',
     'Đường/phố X đang Hoạt động và đang là địa chỉ của một khách hàng (không có nút Xóa).',
     '1. Bấm Khóa ở dòng X và xác nhận\n2. Mở xem khách hàng đang dùng X', '',
     '- Khóa thành công, không bị chặn vì đang được dùng\n- Khách hàng vẫn hiển thị đúng tên đường/phố X, không bị trống'),
    ('Hộp xác nhận Mở khóa và Mở khóa thành công', 'P0', 'Đường/phố X đang Khóa, chưa được dùng ở đâu.',
     '1. Bấm Mở khóa ở dòng X\n2. Đọc hộp xác nhận\n3. Bấm Mở khóa', '',
     '- Hộp có tiêu đề "Mở khóa Đường/Phố", câu "Bạn có chắc muốn mở khóa đường/phố "X"?", hai nút Mở khóa và Hủy\n- Báo "Mở khóa thành công", cột Trạng thái đổi thành Hoạt động\n- Nút Sửa và Xóa hiện lại'),
    ('Bấm Hủy ở hộp Mở khóa thì không đổi', 'P1', 'Đang mở hộp xác nhận mở khóa đường/phố X.',
     '1. Bấm Hủy\n2. Xem lại dòng X', '', '- Hộp đóng, X vẫn ở trạng thái Khóa'),
    ('Khóa / Mở khóa được ghi vào Lịch sử', 'P1', 'Vừa khóa rồi mở khóa đường/phố X.',
     '1. Mở Lịch sử của X\n2. Đọc 2 dòng trên cùng', '',
     '- Có 2 dòng "Thay đổi trạng thái": Hoạt động → Khóa và Khóa → Hoạt động\n- Mỗi dòng kèm người thực hiện và thời điểm'),
    ('Hai người cùng Khóa một đường/phố', 'P1', 'Hai tài khoản A, B cùng mở màn Danh mục Đường/Phố; X đang Hoạt động.',
     '1. A khóa X thành công\n2. B (chưa tải lại trang) bấm Khóa X và xác nhận\n3. Mở Lịch sử của X', '',
     '- B nhận thông báo "Trạng thái đã bị thay đổi. Vui lòng load lại trang"\n- Lịch sử của X chỉ có MỘT dòng khóa (của A), không bị ghi trùng'),
    ('Hai người cùng Mở khóa một đường/phố', 'P2', 'Hai tài khoản A, B cùng mở màn; X đang Khóa.',
     '1. A mở khóa X thành công\n2. B (chưa tải lại trang) bấm Mở khóa X và xác nhận', '',
     '- B nhận thông báo "Trạng thái đã bị thay đổi. Vui lòng load lại trang"\n- X ở trạng thái Hoạt động'),
    ('Đường/phố Khóa không còn chọn được ở màn khác', 'P0', 'Đường/phố X (thuộc Phường/xã P) vừa bị Khóa.',
     '1. Mở màn Khách hàng, bấm Tạo mới\n2. Chọn đến Phường/xã P, mở ô chọn Đường/Phố', 'Đường/phố: X (Khóa)',
     '- Danh sách chọn KHÔNG có đường/phố X'),
    ('Dữ liệu đang gắn đường/phố đã khóa vẫn giữ nguyên', 'P0', 'Khách hàng KH1 đang có địa chỉ Đường/Phố = X; X vừa bị Khóa.',
     '1. Mở màn sửa KH1, xem ô Đường/Phố\n2. Bấm Lưu', 'Khách hàng: KH1',
     '- Ô Đường/Phố vẫn giữ giá trị X, có biểu tượng ổ khoá trước tên\n- Lưu KH1 lại không làm mất đường/phố đã gắn'),
    ('Mở khóa thì chọn lại được', 'P1', 'Đường/phố X đang Khóa.',
     '1. Mở khóa X\n2. Mở màn Khách hàng, bấm Tạo mới, chọn đến Phường/xã của X, mở ô chọn Đường/Phố', '',
     '- Đường/phố X xuất hiện lại trong danh sách chọn, không còn biểu tượng ổ khoá'),
    ('Xem chi tiết đường/phố đang Khóa', 'P2', 'Đường/phố X đang Khóa.',
     '1. Bấm vào tên X trên danh sách', '',
     '- Mở cửa sổ "Xem đường/phố", ô Trạng thái hiện Khóa, mọi ô chỉ đọc\n- Khối Lịch sử ở cuối có dòng Thay đổi trạng thái sang Khóa'),
]

# ---- Sửa tab testcase "17. DM đườngphố" (dump MỚI NHẤT ref/testcase_tab.txt — 116 hàng) ----
# Nhóm VII (Xuất Excel) / VIII (Import) đã chèn lên sheet ngày 25/09 -> KHÔNG chèn lại.
CFG['tc'] = {
    'tab': '17. DM đườngphố',
    'hdr_row': 70,            # "VI. LỊCH SỬ THAY ĐỔI"
    'import_rows_dung': 'File mẫu điền 2 đường/phố hợp lệ (DOC-Phố Mẫu Một – Thành phố Hà Nội – Phường Cửa Nam, DOC-Phố Mẫu Hai – Thành phố Hà Nội – Phường Hoàn Kiếm), chưa có trong danh mục',
    'import_loi_data': {
        'Tên đường/phố không được để trống': 'Tên đường/phố: (để trống); Tỉnh/TP: Thành phố Hà Nội; Phường/xã: Phường Cửa Nam',
        'Tên đường/phố tối đa 255 ký tự': 'Tên đường/phố: chuỗi 256 ký tự',
        'Tỉnh/TP không được để trống': 'Tỉnh/TP: (để trống)',
        'Không tìm thấy tỉnh/TP: X': 'Tỉnh/TP: Tỉnh không tồn tại',
        'Tên tỉnh/TP "X" đang có ở nhiều quốc gia, không xác định được': 'Tỉnh/TP: (tên tỉnh/TP có từ 2 bản ghi trùng tên trong danh mục, kể cả bản ghi đang Khóa)',
        'Phường/xã không được để trống': 'Phường/xã: (để trống)',
        'Không tìm thấy phường/xã "Y" thuộc tỉnh/TP X': 'Tỉnh/TP: Thành phố Đà Nẵng; Phường/xã: Phường Cửa Nam (không thuộc Đà Nẵng)',
        'Tên phường/xã "Y" đang có nhiều bản ghi trong X, không xác định được': 'Phường/xã: (tên phường/xã có từ 2 bản ghi trùng tên trong cùng tỉnh/TP)',
        'Đường/phố bị trùng với dòng N trong file': 'Hai dòng cùng tên “DOC-Phố Mẫu Một”, cùng Phường Cửa Nam – Thành phố Hà Nội',
        'Đường/phố này đã tồn tại trong phường/xã đã chọn': 'Tên đường/phố: Đường Đinh Lễ; Tỉnh/TP: Tỉnh Cà Mau; Phường/xã: Phường Hòa Thành',
    },
    'edits': [
        # --- Khối mô tả đầu tab ---
        ('B2', 'Quản lý danh mục đường/phố dùng chung cho toàn hệ thống. Màn hình cho phép tra cứu, tìm kiếm, thêm mới, chỉnh sửa, xóa, khóa/mở khóa và xem lịch sử thay đổi. Dữ liệu của màn này là nguồn cho ô địa chỉ ở mọi màn nghiệp vụ khác.'),
        ('B3', '- Hiện TOÀN BỘ đường/phố: cả Hoạt động lẫn Khóa. Cột Trạng thái hiện nhãn Hoạt động / Khóa.\n- Bộ lọc Trạng thái để trống = hiện cả hai trạng thái; chọn Hoạt động hoặc Khóa để thu hẹp.'),
        ('B4', '- Bản ghi đã bị Xóa không còn xuất hiện ở bất kỳ trạng thái nào: xóa là xóa HẲN khỏi hệ thống.\n- Chỉ xóa được đường/phố đang Hoạt động và chưa được dùng ở đâu (Khách hàng, Địa điểm giao hàng, Công ty, Nhà cung cấp); đường/phố đã được dùng thì chỉ Khóa được.\n- Không có bản ghi nào bị ẩn vì lý do phân quyền, do màn hình chưa gắn quyền.'),
        ('B7', '- Mỗi đường/phố chỉ hiện MỘT dòng.\n- Tên đường/phố là duy nhất trong cùng một Phường/Xã, tính cả đường/phố đang Khóa — trùng sẽ bị chặn khi lưu.\n- Khi sửa, bản ghi đang sửa được loại khỏi phép kiểm tra trùng: giữ nguyên tên của chính nó thì lưu bình thường.'),
        ('B8', 'Màn hình này KHÔNG khai báo quyền nào. Mọi người dùng đã đăng nhập đều mở được màn hình và thực hiện được đầy đủ Thêm mới, Chỉnh sửa, Xóa, Khóa, Mở khóa, Import Excel và Xuất Excel.\n Phía máy chủ cũng không kiểm tra quyền, nên gọi thẳng chức năng mà bỏ qua giao diện vẫn ghi được dữ liệu. Đây là hiện trạng của mã nguồn, đã được ghi nhận để bộ phận quản trị cân nhắc bổ sung quyền.'),
        ('B10', 'Các bẫy dễ sai nhất của màn này, QA đọc trước khi test:\n- Màn hình KHÔNG gắn quyền. Mọi tài khoản đăng nhập đều thêm, sửa, xóa, khóa được. Không có trường hợp test "thiếu quyền thì nút bị ẩn" như các màn danh mục khác.\n- Trùng tên xét trong cùng một Phường/Xã, không phải toàn hệ thống, và tính cả đường/phố đang Khóa.\n- Cửa sổ thêm mới có 3 nút: Lưu, Lưu và tiếp tục, Đóng. Nút "Lưu và tiếp tục" GIỮ cửa sổ mở và xóa trắng các ô để nhập tiếp bản ghi kế theo.\n- Nút KHÔNG dùng được thì ẨN hẳn, không phải nút xám: đường/phố đang Khóa chỉ còn Mở khóa và Lịch sử; đường/phố đã được dùng ở nơi khác không có nút Xóa.\n- Dòng có 4 nút (Sửa, Xóa, Khóa, Lịch sử) thì 2 nút đầu hiện thẳng, Khóa và Lịch sử nằm trong nút ba chấm "Hành động khác"; dòng có 3 nút trở xuống thì hiện thẳng tất cả.\n- Cửa sổ Lịch sử hiển thị TÊN Phường/xã, Tỉnh/TP, Quốc gia ở các trường tham chiếu.'),
        # --- I. Hiển thị: cột Trạng thái ---
        ('I20', '- Có các cột: STT, Tên đường/phố, Phường/xã, Tỉnh/TP, Người tạo, Ngày tạo, Trạng thái, Hành động\n- Các cột Quận/Huyện/Thị xã, Quốc gia, Người cập nhật, Ngày cập nhật mặc định ẩn, bật lại được bằng biểu tượng Cấu hình cột hiển thị'),
        ('D28', 'Danh sách hiện cả đường/phố đang Khóa'),
        ('F28', 'Danh mục có ít nhất 1 đường/phố đang Khóa.'),
        ('G28', '1. Mở màn hình, chưa chọn bộ lọc Trạng thái\n2. Quan sát cột Trạng thái và tổng số bản ghi'),
        ('I28', '- Danh sách hiện cả đường/phố Hoạt động lẫn Khóa\n- Cột Trạng thái hiện nhãn "Hoạt động" hoặc "Khóa"\n- Khu vực lọc có ô Trạng thái\n- Tổng số bản ghi ở cuối bảng tính cả bản ghi Khóa'),
        # --- III. Thêm mới: ô Trạng thái ---
        ('I40', '- Cửa sổ mở với tiêu đề "Tạo đường/phố"\n- Các ô Tên đường/phố, Quốc gia, Tỉnh/TP, Phường/xã để trống; ô Trạng thái mặc định Hoạt động\n- Có đủ 3 nút: Lưu, Lưu và tiếp tục, Đóng'),
        ('I52', '- Cửa sổ chỉ có 5 ô: Tên đường/phố, Quốc gia, Tỉnh/TP, Phường/xã, Trạng thái\n- KHÔNG có ô Quận/Huyện/Thị xã'),
        # --- IV. Chỉnh sửa: chỉ bản ghi Hoạt động mới có nút Sửa ---
        ('F55', 'Có bản ghi đang Hoạt động trong danh sách.'),
        ('I55', '- Cửa sổ mở với mọi ô đã điền sẵn dữ liệu hiện tại, ô Trạng thái hiện Hoạt động'),
        # --- V. Xóa: xóa hẳn + điều kiện chưa dùng ---
        ('F65', 'Có bản ghi tên "X" đang Hoạt động, chưa được dùng ở đâu (dòng X có nút Xóa).'),
        ('F67', 'Bản ghi X đang Hoạt động và chưa được dùng ở đâu (chưa được chọn làm địa chỉ ở Khách hàng, Địa điểm giao hàng, Công ty, Nhà cung cấp).'),
        ('I67', '- Thông báo "Xoá đường/phố thành công"\n- Bản ghi X biến mất khỏi danh sách'),
        ('D68', 'Đường/phố đang được dùng thì không có nút Xóa'),
        ('F68', 'Đường/phố X đang Hoạt động và đang được chọn làm địa chỉ ở ít nhất một nơi: Khách hàng, Địa điểm giao hàng, Công ty hoặc Nhà cung cấp.'),
        ('G68', '1. Tìm X trên danh sách\n2. Quan sát cột Hành động của dòng X'),
        ('I68', '- KHÔNG có nút Xóa (ẩn hẳn, không phải nút xám)\n- Vẫn còn các nút Sửa, Khóa, Lịch sử\n- Bản ghi X vẫn còn nguyên trong danh sách'),
        ('D69', 'Xóa là xóa hẳn khỏi danh mục'),
        ('F69', 'Vừa xóa thành công đường/phố X (trước đó chưa được dùng ở đâu).'),
        ('G69', '1. Bỏ trống ô Trạng thái, tìm theo tên X\n2. Lọc Trạng thái = Khóa, tìm lại X\n3. Bấm Tạo mới, nhập lại tên X với đúng Phường/xã cũ, bấm Lưu'),
        ('I69', '- Không tìm thấy X ở cả hai trạng thái (đã xóa hẳn, không phải chuyển sang Khóa)\n- Tạo lại đường/phố cùng tên X trong cùng Phường/xã thì lưu thành công, không bị báo trùng'),
        # --- VII. Xuất Excel: thêm trường Trạng thái ---
        ('I84', '- Mở cửa sổ “Chọn trường xuất file”\n- Có đủ các trường: Tên đường/phố, Phường/xã, Quận/Huyện/Thị xã, Tỉnh/TP, Quốc gia, Trạng thái, Người tạo, Ngày tạo, Người cập nhật, Ngày cập nhật\n- Tích sẵn đúng các cột đang hiển thị trên bảng\n- Dòng cuối ghi “Đang chọn a/b trường”'),
    ],
    'clear_k': [20, 28, 40, 52, 55, 65, 67, 68, 69, 84],
    'blocks': [
        # II. TÌM KIẾM & LỌC — cuối nhóm (TC_02.009 ở R38)
        {'after': 38, 'merge_from': 30, 'cases': [
            ('TC_02.010', 'Lọc theo Trạng thái = Khóa', 'P0', 'Có cả đường/phố Hoạt động lẫn Khóa.',
             '1. Chọn ô Trạng thái = Khóa\n2. Quan sát bảng', 'Trạng thái: Khóa',
             '- Lọc ngay khi chọn, bảng về trang 1\n- Mọi dòng đều có Trạng thái Khóa\n- Tổng số bản ghi đổi theo kết quả'),
            ('TC_02.011', 'Lọc theo Trạng thái = Hoạt động', 'P1', 'Có cả đường/phố Hoạt động lẫn Khóa.',
             '1. Chọn ô Trạng thái = Hoạt động\n2. Quan sát bảng', 'Trạng thái: Hoạt động',
             '- Mọi dòng đều có Trạng thái Hoạt động, không còn dòng Khóa'),
            ('TC_02.012', 'Bỏ chọn Trạng thái thì hiện cả hai', 'P2', 'Đang lọc Trạng thái = Khóa.',
             '1. Bấm dấu x ở ô Trạng thái để xoá lựa chọn\n2. Quan sát bảng', '',
             '- Ô Trạng thái trống\n- Bảng hiện lại cả đường/phố Hoạt động lẫn Khóa'),
        ]},
        # III. THÊM MỚI — cuối nhóm (TC_03.014 ở R53)
        {'after': 53, 'merge_from': 40, 'cases': [
            ('TC_03.015', 'Tạo mới ở trạng thái Khóa', 'P1', 'Đang ở cửa sổ thêm mới.',
             '1. Nhập Tên đường/phố, chọn Quốc gia, Tỉnh/TP, Phường/xã\n2. Đổi ô Trạng thái sang Khóa\n3. Bấm Lưu', 'Trạng thái: Khóa',
             '- Báo "Thêm mới thành công"\n- Bản ghi mới hiện trong danh sách với Trạng thái Khóa\n- Cột Hành động của bản ghi chỉ có Mở khóa và Lịch sử'),
            ('TC_03.016', 'Trùng tên với đường/phố đang Khóa bị chặn', 'P1', 'Phường/xã P có đường/phố Y đang ở trạng thái Khóa.',
             '1. Bấm Tạo mới\n2. Nhập tên Y, chọn đến Phường/xã P\n3. Bấm Lưu', 'Tên: Y; Phường/xã: P',
             '- Báo lỗi đỏ dưới ô Tên đường/phố: "Tên đường/phố này đã tồn tại trong phường/xã"\n- Không tạo bản ghi mới'),
            ('TC_03.017', 'Ô Trạng thái chỉ có 2 giá trị, không xoá trống được', 'P2', 'Đang ở cửa sổ thêm mới.',
             '1. Mở ô Trạng thái\n2. Tìm nút x xoá giá trị', '',
             '- Ô chỉ có 2 giá trị: Hoạt động, Khóa\n- Không có nút x, ô luôn có giá trị'),
        ]},
        # IV. CHỈNH SỬA — cuối nhóm (TC_04.009 ở R63)
        {'after': 63, 'merge_from': 55, 'cases': [
            ('TC_04.010', 'Đường/phố đang Khóa không có nút Sửa', 'P0', 'Đường/phố X đang Khóa.',
             '1. Tìm X trên danh sách\n2. Quan sát cột Hành động', '',
             '- Không có nút Sửa và nút Xóa (ẩn hẳn, không phải nút xám)\n- Chỉ còn Mở khóa và Lịch sử'),
            ('TC_04.011', 'Khóa ngay trong cửa sổ Sửa', 'P1', 'Đường/phố X đang Hoạt động.',
             '1. Mở cửa sổ Sửa X\n2. Đổi ô Trạng thái sang Khóa\n3. Bấm Lưu\n4. Mở Lịch sử của X', 'Trạng thái: Khóa',
             '- Báo "Cập nhật thành công", cột Trạng thái của X đổi thành Khóa\n- Lịch sử có dòng "Thay đổi trạng thái" ghi giá trị cũ "Hoạt động", giá trị mới "Khóa"'),
            ('TC_04.012', 'Người khác khóa trong lúc đang sửa', 'P1', 'Hai tài khoản A, B cùng mở màn. A đang mở cửa sổ Sửa đường/phố X.',
             '1. B khóa X\n2. A đổi tên X và bấm Lưu', '',
             '- A nhận thông báo "Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật."\n- Tên X không đổi'),
        ]},
        # V. XÓA — cuối nhóm (TC_05.005 ở R69)
        {'after': 69, 'merge_from': 65, 'cases': [
            ('TC_05.006', 'Mỗi nơi sử dụng đều làm ẩn nút Xóa', 'P1', 'Chuẩn bị 4 đường/phố đang Hoạt động, mỗi đường/phố được chọn làm địa chỉ ở đúng một nơi như Test data.',
             '1. Tải lại màn Danh mục Đường/Phố\n2. Quan sát cột Hành động của từng đường/phố',
             '1. Địa chỉ Khách hàng\n2. Địa điểm giao hàng\n3. Địa chỉ Công ty\n4. Địa chỉ Nhà cung cấp',
             '- Cả 4 đường/phố đều KHÔNG có nút Xóa\n- Vẫn Khóa được bình thường'),
            ('TC_05.007', 'Đường/phố được dùng trong lúc đang mở hộp xác nhận Xóa', 'P1', 'Đường/phố X chưa được dùng, đang hiện nút Xóa.',
             '1. Bấm Xóa ở dòng X, để hộp xác nhận mở\n2. Ở tab khác, chọn X làm địa chỉ cho một khách hàng rồi lưu\n3. Quay lại, bấm Xóa xác nhận', '',
             '- Báo "Đường/phố đang được sử dụng, không thể xóa."\n- X vẫn còn trong danh sách'),
            ('TC_05.008', 'Đường/phố bị khóa trong lúc đang mở hộp xác nhận Xóa', 'P1', 'Hai tài khoản A, B. X đang Hoạt động, chưa được dùng.',
             '1. A bấm Xóa ở dòng X, để hộp xác nhận mở\n2. B khóa X\n3. A bấm Xóa xác nhận', '',
             '- A nhận thông báo "Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật."\n- X vẫn còn, ở trạng thái Khóa sau khi tải lại'),
            ('TC_05.009', 'Hai người cùng xóa một đường/phố', 'P2', 'Hai tài khoản A, B cùng mở màn. X đang Hoạt động, chưa được dùng.',
             '1. A xóa X thành công\n2. B (chưa tải lại trang) bấm Xóa X và xác nhận', '',
             '- B nhận thông báo "Trạng thái đã bị thay đổi. Vui lòng load lại trang"'),
        ]},
        # VII. XUẤT EXCEL — cuối nhóm (TC_07.009 ở R92)
        {'after': 92, 'merge_from': 84, 'cases': [
            ('TC_07.010', 'Xuất theo bộ lọc Trạng thái', 'P1', 'Có ít nhất 1 đường/phố đang Khóa.',
             '1. Lọc Trạng thái = Khóa\n2. Bấm Xuất Excel, tích trường Trạng thái\n3. Bấm Xuất file, mở file\n4. Bỏ lọc Trạng thái, xuất lại', '',
             '- Lần 1: file chỉ chứa các đường/phố đang Khóa, cột Trạng thái ghi "Khóa"\n- Lần 2: file có cả hai trạng thái, cột Trạng thái ghi đúng "Hoạt động" / "Khóa" theo từng dòng'),
        ]},
        # Nhóm MỚI sau case cuối của nhóm cuối cùng (VIII — TC_08.023 ở R116; tab không có dòng ghi chú review ở cuối)
        {'after': 116, 'groups': [('IX', 'KHÓA / MỞ KHÓA (bổ sung 28/09/2026)', 9, _TC_KHOA)]},
    ],
}

CFG['tc_ngoai_pham_vi'] = [
    'R43 (TC_03.004) “Thiếu Quốc gia → lỗi dưới ô Quốc gia” và R45 (TC_03.006) “Thiếu Quận/Huyện → lỗi dưới ô Quận/Huyện”: thực tế lỗi “Bắt buộc phải nhập” chỉ hiện dưới ô Phường/xã (máy chủ chỉ bắt buộc Tên + Phường/xã).',
    'R61–R63: tên hộp thoại ghi “Thông tin chưa được lưu”, chữ thật là “Thông tin chưa lưu”.',
    'R49 (TC_03.010) “Lưu và tiếp tục giữ cửa sổ mở” — code nay đã đúng như case (giữ cửa sổ, xóa trắng các ô); không cần sửa case, chỉ lưu ý lượt test trước ghi Passed khi code còn đóng cửa sổ.',
]


# ---- Bổ sung 28/09/2026: “Mô tả chi tiết giao diện” + “Danh sách event và xử lý event” cho SRS ----
# Tester báo thiếu 2 mục này ở các chức năng sau Thêm mới. Nguồn: code gop_db 28/09/2026 (FE pages/human/hamlets, component
# dùng chung V2BaseImportModal / export-fields-modal / column-customization-modal / CatalogHistoryModal; BE Modules/Human).
_FR = {f['ten']: f for f in CFG['srs']['fr']}
_FR['Chỉnh sửa đường/phố'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Phạm vi', 'Bắt buộc', 'Giá trị ban đầu', 'Mô tả'],
        ['1', 'Tên đường/phố', 'Textbox', 'Enable', '1–255 ký tự', 'Có', 'Dữ liệu hiện tại', 'Không trùng trong cùng Phường/xã (tính cả bản ghi Khóa), bỏ qua chính bản ghi đang sửa. Bỏ trống “Bắt buộc phải nhập”; trùng “Tên đường/phố này đã tồn tại trong phường/xã”; quá dài “Vui lòng nhập tối đa 255 ký tự.”'],
        ['2', 'Quốc gia', 'Dropdown', 'Enable', 'Quốc gia đang Hoạt động', 'Có', 'Dữ liệu hiện tại', 'Điền sẵn theo phường/xã của bản ghi. Việt Nam → ẩn ô Quận/Huyện/Thị xã. Đổi Quốc gia xóa trắng các ô cấp dưới.'],
        ['3', 'Tỉnh/TP', 'Dropdown', 'Enable', 'Tỉnh/TP Hoạt động của quốc gia đã chọn', 'Có', 'Dữ liệu hiện tại', 'Điền sẵn theo phường/xã của bản ghi. Đổi Tỉnh/TP xóa trắng các ô cấp dưới.'],
        ['4', 'Quận/Huyện/Thị xã', 'Dropdown', 'Ẩn/Enable', 'Quận/huyện của tỉnh/TP đã chọn', 'Có khi khác Việt Nam', 'Dữ liệu hiện tại', 'Chỉ hiện khi Quốc gia khác Việt Nam; điền sẵn theo bản ghi.'],
        ['5', 'Phường/xã', 'Dropdown', 'Enable', 'Phường/xã Hoạt động của tỉnh/TP (VN) hoặc quận/huyện (nước khác)', 'Có', 'Dữ liệu hiện tại', 'Phường/xã đã khóa mà bản ghi đang dùng vẫn hiện đúng tên kèm 🔒. Bỏ trống “Bắt buộc phải nhập”.'],
        ['6', 'Trạng thái', 'Dropdown', 'Enable', 'Hoạt động / Khóa', 'Không', 'Dữ liệu hiện tại', 'Luôn có giá trị. Chọn Khóa rồi Lưu cũng là khóa đường/phố; lịch sử ghi dòng “Thay đổi trạng thái” riêng.'],
        ['7', 'Nút Lưu', 'Button', 'Enable', '–', '–', 'Hiển thị', 'Ghi thay đổi rồi đóng cửa sổ.'],
        ['8', 'Nút Đóng / biểu tượng X', 'Button', 'Enable', '–', '–', 'Hiển thị', 'Đóng cửa sổ, không ghi gì. Đã sửa dở thì hỏi “Thông tin chưa lưu” — “Bạn có thông tin chưa lưu. Có chắc chắn muốn thoát?” (Thoát / Ở lại). Chế độ Sửa không có nút “Lưu và tiếp tục”.'],
        ['9', 'Thông báo lỗi', 'Label', 'Hiển thị khi lỗi', '–', '–', 'Ẩn', 'Chữ đỏ ngay dưới ô bị lỗi, kèm thông báo chung “Vui lòng kiểm tra lại dữ liệu nhập”.'],
    ],
    'ui_widths': [0.5, 1.2, 0.8, 0.6, 1.1, 0.6, 0.8, 1.9],
    'events': [
        ['Bấm biểu tượng bút chì (Sửa)', 'Click', 'Before:\n– Nút chỉ hiển thị khi bản ghi đang Hoạt động; bản ghi Khóa không có nút Sửa.\nAfter:\n– Mở cửa sổ “Sửa đường/phố” với dữ liệu hiện tại đã điền sẵn.'],
        ['Đổi Quốc gia / Tỉnh/TP / Quận/Huyện', 'Change', 'After:\n– Xóa trắng các ô cấp dưới và nạp lại danh sách tương ứng; Quốc gia là Việt Nam thì ẩn ô Quận/Huyện/Thị xã.'],
        ['Bấm Lưu', 'Click', 'Before:\n– Máy chủ kiểm tra trạng thái TRƯỚC khi kiểm tra dữ liệu: bản ghi đang Khóa (vừa bị người khác khóa) → từ chối, báo “Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.”\nDuring:\n– Tên đường/phố, Phường/xã để trống → “Bắt buộc phải nhập”; quá 255 ký tự → “Vui lòng nhập tối đa 255 ký tự.”\n– Trùng tên với đường/phố khác trong cùng Phường/xã → “Tên đường/phố này đã tồn tại trong phường/xã”.\n– Bỏ qua kiểm tra trùng đối với chính bản ghi đang sửa.\n– Có lỗi → báo đỏ dưới ô, cửa sổ KHÔNG đóng, không thực hiện bước After.\nAfter:\n– Ghi thay đổi, ghi Người cập nhật và một dòng lịch sử “Thay đổi thông tin” nêu giá trị cũ → mới (đổi Trạng thái ghi dòng “Thay đổi trạng thái” riêng).\n– Đóng cửa sổ, nạp lại danh sách, báo “Cập nhật thành công”.'],
        ['Bấm Đóng / biểu tượng X / bấm ra ngoài cửa sổ', 'Click', 'After:\n– Chưa sửa gì → đóng cửa sổ.\n– Đã sửa → hỏi “Thông tin chưa lưu” — “Bạn có thông tin chưa lưu. Có chắc chắn muốn thoát?” (Thoát / Ở lại); chọn Thoát thì đóng, không ghi; chọn Ở lại thì giữ nguyên dữ liệu đang nhập.'],
    ],
})
_FR['Xóa đường/phố'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Mô tả'],
        ['1', 'Biểu tượng thùng rác (Xóa)', 'Icon Button', 'Nằm ở cột Hành động của từng dòng. Chỉ hiển thị khi đường/phố đang Hoạt động và CHƯA được chọn làm địa chỉ ở Khách hàng, Địa điểm giao hàng, Công ty, Nhà cung cấp; ngược lại nút bị ẩn hẳn.'],
        ['2', 'Tiêu đề hộp xác nhận', 'Label', '“Xóa Đường/Phố”.'],
        ['3', 'Nội dung hộp xác nhận', 'Label', '“Bạn có chắc muốn xóa đường/phố "<tên>"?” — nêu rõ tên bản ghi để tránh xóa nhầm dòng.'],
        ['4', 'Nút Xóa', 'Button', 'Xác nhận xóa hẳn bản ghi khỏi hệ thống.'],
        ['5', 'Nút Hủy', 'Button', 'Đóng hộp, không thay đổi gì.'],
    ],
    'ui_widths': [0.6, 1.8, 1.0, 3.6],
    'events': [
        ['Bấm biểu tượng thùng rác', 'Click', 'Before:\n– Nút chỉ hiển thị khi đường/phố đang Hoạt động và CHƯA được chọn làm địa chỉ ở Khách hàng, Địa điểm giao hàng, Công ty, Nhà cung cấp.\nAfter:\n– Hiện hộp xác nhận “Xóa Đường/Phố” kèm tên bản ghi.'],
        ['Bấm Xóa trong hộp xác nhận', 'Click', 'During:\n– Bản ghi đang Khóa (vừa bị người khác khóa) → “Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.”, không xóa.\n– Bản ghi vừa được dùng ở nơi khác → “Đường/phố đang được sử dụng, không thể xóa.”, không xóa.\n– Bản ghi không còn tồn tại (người khác vừa xóa) → “Trạng thái đã bị thay đổi. Vui lòng load lại trang”.\nAfter:\n– Xóa hẳn bản ghi (không khôi phục được), đóng hộp, nạp lại danh sách, báo “Xoá đường/phố thành công”.\n– Lỗi khác → báo câu lỗi của hệ thống hoặc “Xoá đường/phố thất bại”.'],
        ['Bấm Hủy', 'Click', 'After:\n– Đóng hộp xác nhận, không thay đổi gì.'],
    ],
})
_FR['Khóa / Mở khóa đường/phố'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Mô tả'],
        ['1', 'Nút Khóa / Mở khóa', 'Button', 'Nằm ở cột Hành động (trong nút ba chấm nếu dòng có từ 4 nút trở lên). Nhãn đổi theo trạng thái. Luôn hiển thị (khóa được cả khi đường/phố đang được dùng): dòng Hoạt động có Khóa, dòng Khóa có Mở khóa.'],
        ['2', 'Nút ba chấm “Hành động khác”', 'Icon Button', 'Hiện khi dòng có từ 4 nút trở lên: 2 nút đầu hiện thẳng, các nút còn lại (Khóa, Lịch sử) nằm trong menu này.'],
        ['3', 'Tiêu đề hộp xác nhận', 'Label', '“Khóa Đường/Phố” hoặc “Mở khóa Đường/Phố” tùy trạng thái hiện tại.'],
        ['4', 'Nội dung hộp xác nhận', 'Label', '“Bạn có chắc muốn khóa đường/phố "<tên>"?” / “Bạn có chắc muốn mở khóa đường/phố "<tên>"?”.'],
        ['5', 'Nút Khóa / Mở khóa trong hộp', 'Button', 'Xác nhận thực hiện.'],
        ['6', 'Nút Hủy', 'Button', 'Đóng hộp, không làm gì.'],
        ['7', 'Cột Trạng thái', 'Badge', 'Hoạt động hoặc Khóa, hai màu khác nhau; cập nhật ngay sau thao tác.'],
    ],
    'ui_widths': [0.6, 1.8, 1.0, 3.6],
    'events': [
        ['Bấm nút ba chấm', 'Click', 'After:\n– Mở menu chứa các nút còn lại của dòng (Khóa / Mở khóa, Lịch sử).'],
        ['Chọn Khóa hoặc Mở khóa', 'Click', 'After:\n– Hiện hộp xác nhận kèm tên bản ghi.'],
        ['Bấm Khóa / Mở khóa trong hộp', 'Click', 'During:\n– Bản ghi không còn tồn tại hoặc đã ở trạng thái đích (người khác vừa thao tác) → báo “Trạng thái đã bị thay đổi. Vui lòng load lại trang”, dừng xử lý, không ghi thêm lịch sử.\nAfter:\n– Đổi trạng thái, KHÔNG xóa dữ liệu; ghi Người cập nhật và một dòng lịch sử “Khóa” / “Mở khóa”.\n– Đóng hộp, báo “Khóa thành công” / “Mở khóa thành công”, nạp lại danh sách: sau Khóa ẩn nút Sửa, Xóa; sau Mở khóa hiện lại nút Sửa (Xóa hiện lại nếu đủ điều kiện xóa).\n– Lỗi khác → báo câu lỗi của hệ thống hoặc “Thao tác thất bại”.'],
        ['Bấm Hủy', 'Click', 'After:\n– Đóng hộp xác nhận, trạng thái không đổi.'],
    ],
})
_FR['Xem lịch sử thay đổi'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Giá trị ban đầu', 'Mô tả'],
        ['1', 'Nút Lịch sử', 'Button', 'Hiển thị', 'Nằm ở cột Hành động (trong nút ba chấm nếu dòng có từ 4 nút). Luôn có ở mọi dòng, kể cả bản ghi Khóa.'],
        ['2', 'Tiêu đề cửa sổ', 'Label', 'Lịch sử thay đổi: <tên đường/phố>', 'Ghép tên bản ghi để biết đang xem dòng nào.'],
        ['3', 'Nút Bộ lọc', 'Button', 'Vùng lọc đang ẩn', 'Bấm để hiện / ẩn vùng lọc; vùng lọc ghim ở đầu khi cuộn danh sách.'],
        ['4', 'Loại hành động', 'Dropdown', 'Trống (“Tất cả loại hành động”)', 'Lọc theo Tạo mới, Thay đổi thông tin, Thay đổi trạng thái, Khóa, Mở khóa… Chọn là lọc ngay.'],
        ['5', 'Người thực hiện', 'Dropdown', 'Trống (“Tất cả người thực hiện”)', 'Chọn là lọc ngay.'],
        ['6', 'Từ ngày / Đến ngày', 'Date picker', 'Trống', 'Định dạng dd/mm/yyyy. Chọn là lọc ngay.'],
        ['7', 'Nút Làm mới (vùng lọc)', 'Button', 'Hiển thị', 'Xóa hết tiêu chí lọc, hiện lại toàn bộ lịch sử.'],
        ['8', 'Danh sách thay đổi', 'Timeline', 'Mới nhất ở trên cùng', 'Mỗi mốc gồm: thời điểm (dd/mm/yyyy hh:mm); loại hành động (Tạo mới, Thay đổi thông tin, Thay đổi trạng thái, Khóa, Mở khóa); “Người thực hiện: …”; từng trường đã đổi dạng “Tên trường: giá trị cũ → giá trị mới”. Trường Phường/xã, Tỉnh/TP, Quốc gia hiển thị bằng tên.'],
        ['9', 'Trạng thái rỗng', 'Label', 'Ẩn', '“Chưa có lịch sử thao tác nào.” khi bản ghi chưa có lịch sử; “Không có lịch sử phù hợp bộ lọc.” khi lọc không ra kết quả.'],
        ['10', 'Nút Đóng / biểu tượng X', 'Button', 'Hiển thị', 'Đóng cửa sổ.'],
    ],
    'ui_widths': [0.6, 1.5, 0.9, 1.2, 2.8],
    'events': [
        ['Chọn Lịch sử ở cột Hành động', 'Click', 'After:\n– Mở cửa sổ “Lịch sử thay đổi: <tên>”, nạp danh sách thay đổi theo thứ tự mới nhất trước.\n– Không tải được → hiện “Không tải được lịch sử phiếu.” kèm nút Thử lại.'],
        ['Bấm Bộ lọc', 'Click', 'After:\n– Hiện / ẩn vùng lọc.'],
        ['Đổi Loại hành động / Người thực hiện / Từ ngày / Đến ngày', 'Change', 'After:\n– Lọc ngay danh sách theo mọi tiêu chí đã chọn (không có nút Tìm kiếm).'],
        ['Bấm Làm mới trong vùng lọc', 'Click', 'After:\n– Xóa trắng tiêu chí, hiện lại toàn bộ lịch sử.'],
        ['Bấm Đóng / biểu tượng X', 'Click', 'After:\n– Đóng cửa sổ; danh sách phía sau giữ nguyên bộ lọc và trang đang xem.'],
    ],
})
_FR['Import file đường/phố'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Bắt buộc', 'Giá trị ban đầu', 'Mô tả'],
        ['1', 'Nút Import Excel', 'Button', 'Enable', '–', 'Hiển thị', 'Nằm trên thanh công cụ của bảng danh sách. Mở cửa sổ “Import đường/phố” (dòng phụ “Import từ Excel • Validate xong dòng hợp lệ sẽ bị khoá”).'],
        ['2', 'Nút Chọn file Excel', 'Button', 'Enable', 'Có', 'Chưa chọn file', 'Chọn file .xlsx hoặc .xls từ máy; tên file hiện ngay cạnh nút.'],
        ['3', 'Nút Tải file mẫu', 'Button', 'Enable', '–', 'Hiển thị', 'Tải file Mau_import_duong_pho.xlsx gồm cột STT, Tên đường/phố *, Tỉnh/TP * (ô chọn sẵn danh sách tỉnh/TP), Phường/xã * (ô gõ tay). Hàng 1 là tiêu đề, hàng 2 là dòng mô tả, dữ liệu nhập từ hàng 3.'],
        ['4', 'Nút Load lên bảng', 'Button', 'Enable / Disable', '–', 'Mờ khi chưa chọn file', 'Đọc file và đổ dữ liệu lên bảng xem trước.'],
        ['5', 'Nút Validate', 'Button', 'Enable / Disable', '–', 'Mờ khi bảng chưa có dòng nào', 'Gửi dữ liệu lên máy chủ kiểm tra từng dòng; dòng hợp lệ bị khóa lại, không sửa được nữa.'],
        ['6', 'Nút Import', 'Button', 'Enable / Disable', '–', 'Mờ', 'Chỉ bấm được khi đã Validate, không còn dòng lỗi và có ít nhất 1 dòng hợp lệ. Ghi các dòng hợp lệ vào danh mục.'],
        ['7', 'Ô Tổng / Hợp lệ / Lỗi', 'Label', 'Read-only', '–', 'Tổng: 0', 'Sau Load hiện “Tổng”; sau Validate hiện thêm “Hợp lệ”, “Lỗi”. Có dòng vừa sửa hiện “Có dòng đã sửa (cần validate lại)”.'],
        ['8', 'Bảng xem trước', 'Table/Grid', 'Enable', '–', 'Trống', 'Cột #, Tên đường/phố *, Tỉnh/TP *, Phường/xã *. Dòng lỗi sửa trực tiếp được (Tên đường/phố, Phường/xã gõ lại; Tỉnh/TP chọn trong danh sách).'],
        ['9', 'Thông báo lỗi theo dòng', 'Label', 'Hiển thị', '–', 'Ẩn', 'Dòng lỗi viền đỏ, lý do ghi ngay dưới dòng: “Tên đường/phố không được để trống”; “Tên đường/phố tối đa 255 ký tự”; “Tỉnh/TP không được để trống”; “Không tìm thấy tỉnh/TP: X”; “Tên tỉnh/TP "X" đang có ở nhiều quốc gia, không xác định được”; “Phường/xã không được để trống”; “Không tìm thấy phường/xã "Y" thuộc tỉnh/TP X”; “Tên phường/xã "Y" đang có nhiều bản ghi trong X, không xác định được”; “Đường/phố bị trùng với dòng N trong file”; “Đường/phố này đã tồn tại trong phường/xã đã chọn”.'],
        ['10', 'Nút Bỏ dòng lỗi', 'Button', 'Enable / Disable', '–', 'Mờ khi bảng trống', 'Loại mọi dòng lỗi khỏi bảng, báo “Đã bỏ N dòng lỗi. Còn lại M dòng hợp lệ.”; chưa Validate thì báo “Hãy Validate trước rồi mới bỏ dòng lỗi.”'],
        ['11', 'Nút Xoá trạng thái validate', 'Button', 'Enable / Disable', '–', 'Mờ khi bảng trống', 'Bỏ khóa các dòng hợp lệ và xóa kết quả kiểm tra để sửa lại.'],
        ['12', 'Nút Làm mới', 'Button', 'Enable', '–', 'Hiển thị', 'Bỏ file đã chọn và toàn bộ bảng, đưa cửa sổ về trạng thái ban đầu.'],
        ['13', 'Nút Đóng / biểu tượng X', 'Button', 'Enable', '–', 'Hiển thị', 'Đóng cửa sổ, không ghi gì.'],
    ],
    'ui_widths': [0.5, 1.3, 0.9, 0.8, 0.5, 1.1, 2.4],
    'events': [
        ['Bấm Import Excel', 'Click', 'After:\n– Mở cửa sổ “Import đường/phố” ở trạng thái rỗng.'],
        ['Bấm Tải file mẫu', 'Click', 'After:\n– Tải file Mau_import_duong_pho.xlsx về máy.\n– Lỗi → báo “Lỗi khi tạo file mẫu”.'],
        ['Chọn file', 'Change', 'During:\n– File không phải .xlsx / .xls → báo “Vui lòng chọn file .xlsx hoặc .xls”, bỏ file.\nAfter:\n– Hiện tên file, nút Load lên bảng sáng lên.'],
        ['Bấm Load lên bảng', 'Click', 'During:\n– File không có dòng dữ liệu → “Không có dòng dữ liệu hợp lệ.”\n– Quá 500 dòng → “File có X dòng dữ liệu, vượt quá giới hạn 500 dòng mỗi lần import. Vui lòng tách file và import nhiều lần.”\n– File hỏng / không đọc được → “Không đọc được file Excel.”\nAfter:\n– Đổ dữ liệu lên bảng xem trước, cập nhật ô Tổng.'],
        ['Bấm Validate', 'Click', 'During:\n– Máy chủ kiểm tra từng dòng theo đúng quy tắc của chức năng Thêm mới và bảng “Quy tắc kiểm tra riêng của file Import”.\n– KHÔNG ghi bất kỳ bản ghi nào ở bước này.\nAfter:\n– Còn dòng lỗi: tô đỏ dòng lỗi kèm lý do, khóa dòng hợp lệ, báo “Validate xong: X hợp lệ, Y không hợp lệ. (Dòng hợp lệ đã bị khoá, chỉ có thể sửa dòng lỗi)”.\n– Không còn dòng lỗi: báo “Tất cả N dòng đã hợp lệ. Có thể import ngay.”, nút Import sáng lên.\n– Không dòng nào hợp lệ: báo “Không có dòng nào hợp lệ để import. Hãy sửa các dòng lỗi và validate lại.”'],
        ['Sửa ô ở dòng lỗi', 'Input', 'After:\n– Dòng chuyển về chưa kiểm tra, hiện “Có dòng đã sửa (cần validate lại)”; phải Validate lại mới Import được.'],
        ['Bấm Bỏ dòng lỗi / Xoá trạng thái validate', 'Click', 'After:\n– Bỏ dòng lỗi: chỉ giữ dòng hợp lệ, nút Import sáng lên.\n– Xoá trạng thái validate: mở khóa mọi dòng, xóa kết quả kiểm tra.'],
        ['Bấm Import', 'Click', 'During:\n– Chỉ gửi các dòng hợp lệ; máy chủ kiểm tra lại toàn bộ, không tin kết quả Validate trước đó.\n– Không còn dòng hợp lệ → báo “Không có dòng nào hợp lệ để import”, dừng.\nAfter:\n– Tạo đường/phố mới ở trạng thái Hoạt động, người tạo là người đang thực hiện.\n– Báo “Import thành công N đường/phố.” (có dòng thất bại: “Import thành công X/Y đường/phố. Z dòng thất bại.”), đóng cửa sổ, nạp lại danh sách.'],
        ['Bấm Làm mới / Đóng', 'Click', 'After:\n– Làm mới: xóa file và bảng, giữ cửa sổ mở.\n– Đóng: đóng cửa sổ, không ghi gì.'],
    ],
})
_FR['Xuất danh sách ra Excel'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
        ['1', 'Nút Xuất Excel', 'Button', 'Enable', 'Hiển thị', 'Nằm trên thanh công cụ của bảng danh sách. Mở cửa sổ “Chọn trường xuất file”.'],
        ['2', 'Dòng hướng dẫn', 'Label', 'Read-only', 'Hiển thị', '“Tích chọn trường cần xuất, kéo ☰ để đổi thứ tự cột trong file.”'],
        ['3', 'Danh sách trường', 'Checkbox chọn nhiều', 'Enable', 'Tích sẵn đúng các cột đang hiển thị trên bảng, xếp lên đầu theo thứ tự trên bảng', 'Mười trường: Tên đường/phố, Phường/xã, Quận/Huyện/Thị xã, Tỉnh/TP, Quốc gia, Trạng thái, Người tạo, Ngày tạo, Người cập nhật, Ngày cập nhật. Kéo biểu tượng ☰ để đổi vị trí cột trong file.'],
        ['4', 'Nút Chọn tất cả', 'Button', 'Enable', 'Hiển thị', 'Tích toàn bộ trường.'],
        ['5', 'Nút Bỏ chọn hết', 'Button', 'Enable', 'Hiển thị', 'Bỏ tích toàn bộ trường.'],
        ['6', 'Dòng đếm trường', 'Label', 'Read-only', 'Hiển thị', '“Đang chọn a/N trường”.'],
        ['7', 'Nút Xuất file', 'Button', 'Enable / Disable', 'Mờ khi chưa chọn trường nào', 'Đóng cửa sổ, sinh file Excel và tải về máy.'],
        ['8', 'Nút Đóng / biểu tượng X', 'Button', 'Enable', 'Hiển thị', 'Đóng cửa sổ, không xuất.'],
    ],
    'ui_widths': [0.6, 1.5, 1.0, 0.8, 1.3, 2.3],
    'events': [
        ['Bấm Xuất Excel', 'Click', 'After:\n– Mở cửa sổ “Chọn trường xuất file”, tích sẵn đúng các cột đang hiển thị trên bảng (theo cấu hình cột của người dùng), các trường còn lại liệt kê bên dưới chưa tích. Không nhớ lựa chọn của lần xuất trước.'],
        ['Tích / bỏ tích trường, kéo ☰', 'Change', 'During:\n– Thứ tự trong danh sách là thứ tự cột trong file.\n– Bỏ chọn hết → nút Xuất file mờ đi.'],
        ['Bấm Xuất file', 'Click', 'During:\n– Sinh file theo ĐÚNG bộ lọc và thứ tự sắp xếp đang áp dụng (tối đa 10,000 dòng), các cột theo đúng thứ tự trường đã chọn.\nAfter:\n– Tải file danh_muc_duong_pho.xlsx về máy, báo “Xuất Excel thành công”.\n– Lỗi → báo “Lỗi khi xuất Excel”.'],
        ['Bấm Đóng / biểu tượng X', 'Click', 'After:\n– Đóng cửa sổ, không xuất gì.'],
    ],
})
_FR['Xem chi tiết đường/phố'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
        ['1', 'Tên đường/phố ở cột Tên đường/phố', 'Link', 'Enable', 'Hiển thị', 'Bấm vào tên để mở cửa sổ Xem (thay cho nút “Xem” ở cột Hành động). Bản ghi Khóa vẫn mở được.'],
        ['2', 'Tiêu đề cửa sổ', 'Label', 'Read-only', 'Xem đường/phố', 'Kèm biểu tượng tròn ở đầu tiêu đề.'],
        ['3', 'Tên đường/phố', 'Textbox', 'Read-only', 'Dữ liệu hiện tại', 'Chỉ đọc, không sửa được.'],
        ['4', 'Quốc gia', 'Dropdown', 'Read-only', 'Dữ liệu hiện tại', 'Chỉ đọc, không sửa được.'],
        ['5', 'Tỉnh/TP', 'Dropdown', 'Read-only', 'Dữ liệu hiện tại', 'Chỉ đọc, không sửa được.'],
        ['6', 'Quận/Huyện/Thị xã', 'Dropdown', 'Read-only', 'Dữ liệu hiện tại', 'Chỉ đọc, không sửa được. Chỉ hiện khi quốc gia khác Việt Nam.'],
        ['7', 'Phường/xã', 'Dropdown', 'Read-only', 'Dữ liệu hiện tại', 'Chỉ đọc, không sửa được. Phường/xã đã khóa vẫn hiện đúng tên kèm 🔒.'],
        ['8', 'Trạng thái', 'Dropdown', 'Read-only', 'Dữ liệu hiện tại', 'Chỉ đọc, không sửa được.'],
        ['9', 'Khối Lịch sử', 'Panel thu gọn', 'Enable', 'Thu gọn', 'Tiêu đề “Lịch sử” kèm số lần thay đổi. Nút “Xem lịch sử” mở khối (đổi thành “Thu gọn”), nút “Làm mới” nạp lại. Nội dung, bộ lọc giống cửa sổ Lịch sử thay đổi.'],
        ['10', 'Nút Đóng / biểu tượng X', 'Button', 'Enable', 'Hiển thị', 'Đóng cửa sổ. Cửa sổ Xem KHÔNG có nút Lưu, Lưu và tiếp tục hay Sửa.'],
    ],
    'ui_widths': [0.6, 1.5, 1.0, 0.8, 1.3, 2.3],
    'events': [
        ['Bấm tên đường/phố ở danh sách', 'Click', 'After:\n– Mở cửa sổ “Xem đường/phố”, nạp dữ liệu hiện tại của bản ghi ở chế độ chỉ đọc.\n– Không tải được → báo “Lỗi khi tải dữ liệu” và đóng cửa sổ.'],
        ['Bấm Xem lịch sử / Thu gọn', 'Click', 'After:\n– Lần mở đầu tiên mới nạp lịch sử; hiện danh sách thay đổi mới nhất ở trên.\n– Thu gọn: ẩn khối, không nạp lại.'],
        ['Bấm Làm mới trong khối Lịch sử', 'Click', 'After:\n– Nạp lại lịch sử mới nhất của bản ghi.'],
        ['Bấm Đóng / biểu tượng X', 'Click', 'After:\n– Đóng cửa sổ, không hỏi xác nhận (không có gì để lưu).'],
    ],
})
_FR['Tùy chỉnh cột hiển thị'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
        ['1', 'Biểu tượng Cấu hình cột hiển thị', 'Icon Button', 'Enable', 'Hiển thị', 'Nút cuối cùng trên thanh công cụ của bảng. Mở cửa sổ “Tuỳ chỉnh cột”.'],
        ['2', 'Danh sách cột', 'Checkbox', 'Enable', 'Theo cấu hình đã lưu; chưa lưu lần nào thì hiện Phường/xã, Tỉnh/TP, Người tạo, Ngày tạo, Trạng thái, ẩn Quận/Huyện/Thị xã, Quốc gia, Người cập nhật, Ngày cập nhật', 'Liệt kê đủ 12 cột theo thứ tự trên bảng: STT, Tên đường/phố, Phường/xã, Quận/Huyện/Thị xã, Tỉnh/TP, Quốc gia, Người cập nhật, Ngày cập nhật, Người tạo, Ngày tạo, Trạng thái, Hành động. Tích = hiện cột, bỏ tích = ẩn cột.'],
        ['3', 'Cột bắt buộc', 'Checkbox', 'Disable', 'Luôn tích', 'STT, Tên đường/phố, Hành động: xám, có biểu tượng khóa, không bỏ tích và không kéo đổi vị trí được (rê chuột hiện “Cột bắt buộc — không thể ẩn hoặc đổi vị trí”).'],
        ['4', 'Biểu tượng ☰', 'Drag handle', 'Enable', 'Hiển thị', 'Kéo thả để đổi thứ tự các cột không bắt buộc.'],
        ['5', 'Nút Lưu', 'Button', 'Enable', 'Hiển thị', 'Áp dụng ngay cho bảng và lưu cấu hình theo TÀI KHOẢN người dùng trên máy chủ (đăng nhập máy/trình duyệt khác vẫn giữ).'],
        ['6', 'Nút Đóng / biểu tượng X', 'Button', 'Enable', 'Hiển thị', 'Đóng cửa sổ, bỏ các thay đổi chưa Lưu.'],
    ],
    'ui_widths': [0.6, 1.5, 1.0, 0.8, 1.3, 2.3],
    'events': [
        ['Bấm biểu tượng Cấu hình cột hiển thị', 'Click', 'After:\n– Mở cửa sổ “Tuỳ chỉnh cột”, tích đúng theo các cột đang hiển thị.'],
        ['Tích / bỏ tích, kéo ☰', 'Change', 'During:\n– Chỉ thay đổi trong cửa sổ, bảng chưa đổi.\n– Cột bắt buộc không bỏ tích, không kéo được.'],
        ['Bấm Lưu', 'Click', 'After:\n– Bảng hiện/ẩn và sắp cột theo cấu hình mới, lưu cấu hình theo người dùng, báo “Cập nhật thành công”; đóng cửa sổ.\n– Lần Xuất Excel sau tích sẵn đúng các cột đang hiện.\n– Lỗi lưu → báo “Thao tác thất bại”.'],
        ['Bấm Đóng / biểu tượng X', 'Click', 'After:\n– Đóng cửa sổ, trả danh sách về cấu hình đang áp dụng.'],
    ],
})
