# -*- coding: utf-8 -*-
# Cấu hình tài liệu màn Danh mục Tỉnh/TP — bám khuôn configs/areas.py.
# Nguồn: code gop_db 25/09/2026 (FE pages/human/provinces/index.vue, components/ProvinceModel.vue;
# BE ProvinceController / ProvinceService / CreateProvinceRequest / ProvinceListResource / ExportColumnRegistry['provinces']).
# Không ghi URL. Chữ UI / message lấy nguyên văn code.

DT = 'tỉnh/TP'

CFG = {
    'slug': 'provinces',
    'ten': 'Danh mục Tỉnh/TP',
    'doi_tuong': DT,
    'file_hdsd': 'HDSD_Danh mục Tỉnh-TP.docx',
    'file_srs': 'SRS - Danh mục Tỉnh-TP.docx',
    'menu': [('Danh mục', 'menu_phanhe'), ('Địa lý', 'menu_nhom'), ('Tỉnh/TP', 'menu_muc')],

    'thuat_ngu': [
        ['Tỉnh/TP', 'Đơn vị hành chính cấp tỉnh, trực thuộc một Quốc gia và một Khu vực. Là cấp cha của Quận/Huyện và Phường/Xã trong cây địa chỉ.'],
        ['Mã số tỉnh', 'Mã tham khảo của tỉnh/TP, không bắt buộc, chỉ nhận chữ số (tối đa 10 chữ số), không yêu cầu duy nhất.'],
        ['Biển số xe', 'Mã biển số xe của tỉnh/TP, bắt buộc nhập, chỉ nhận chữ số (tối đa 50 chữ số).'],
        ['Quốc gia / Khu vực', 'Quốc gia và khu vực mà tỉnh/TP trực thuộc, chọn từ Danh mục quốc gia và Danh mục khu vực. Khu vực phải thuộc đúng quốc gia đã chọn.'],
        ['Trạng thái Hoạt động', 'Tỉnh/TP dùng được ở các màn nghiệp vụ khác.'],
        ['Trạng thái Khóa', 'Tỉnh/TP không còn chọn được ở nơi khác nhưng vẫn nằm trong danh mục và vẫn xem được lịch sử.'],
    ],
    'phien_ban': [
        ['1.0', '17/08/2026', 'Đội phát triển phần mềm', 'Tạo mới cho màn Danh mục Tỉnh/TP.'],
        ['1.1', '25/09/2026', 'Đội phát triển phần mềm', 'Cập nhật theo phiên bản hiện tại: bổ sung Xem chi tiết, Xuất Excel, Import Excel, Tùy chỉnh cột, ô Trạng thái trong cửa sổ Tạo/Sửa, quy tắc ô Mã số tỉnh; trình bày theo mẫu tài liệu danh mục chung.'],
    ],
    'muc_dich': [
        'Danh mục Tỉnh/TP là nơi khai báo và quản lý danh sách tỉnh/thành phố dùng chung cho toàn hệ thống. Mỗi tỉnh/TP trực thuộc một Quốc gia và một Khu vực; dữ liệu của màn này là nguồn cho các ô địa chỉ ở mọi màn nghiệp vụ khác (hồ sơ nhân sự, khách hàng, Phường/Xã, Quận/Huyện, Đường/Phố…), nên mỗi thay đổi ở đây đều ảnh hưởng tới nhiều nơi.',
    ],
    'quyen': {
        'truoc': ['Phân quyền ai được quyền tạo/ sửa/ xóa/ khóa/ mở khóa sẽ được cập nhật ngay sau khi có tài liệu phân quyền chi tiết của hệ thống.',
                  'Tại thời điểm xây dựng HDSD hiện tại, ai cũng được quyền truy cập màn hình danh mục Tỉnh/TP và quyền tạo/sửa/xóa/khóa/mở khóa, import, xuất Excel.'],
        'rows': [],
        'sau': ['Lưu ý: vì ai cũng sửa được, Người dùng hãy cân nhắc kỹ trước khi đổi hoặc xóa một bản ghi — dữ liệu này đang được nhiều màn khác sử dụng.'],
    },

    'danh_sach': {
        'mo_ta_vao': 'Hệ thống hiển thị danh sách tỉnh/TP hiện có (gồm cả bản ghi Hoạt động lẫn bản ghi đã Khóa), mặc định 10 dòng mỗi trang.',
        'bo_cuc': [
            'Khu vực tìm kiếm và lọc — ô tìm kiếm nhanh, ô Quốc gia, ô Trạng thái, nút Tìm kiếm và Làm mới.',
            'Thanh công cụ — nút Tạo mới, nút Xuất Excel, nút Import Excel và biểu tượng Cấu hình cột hiển thị.',
            'Bảng danh sách — các cột thông tin, cột Hành động ở cuối, và phân trang bên dưới.',
        ],
        'cot': [
            ['STT', 'Số thứ tự, chạy liên tục qua các trang. Luôn hiển thị.'],
            ['Tên Tỉnh/TP', 'Tên đầy đủ. Luôn hiển thị, sắp xếp được. Bấm vào tên để mở cửa sổ Xem Tỉnh/TP.'],
            ['Mã Tỉnh/TP', 'Mã số tỉnh, sắp xếp được. Có thể trống với tỉnh/TP chưa khai mã.'],
            ['Biển số xe', 'Biển số xe của tỉnh/TP. Mặc định ẩn.'],
            ['Quốc gia', 'Quốc gia mà tỉnh/TP trực thuộc. Mặc định ẩn.'],
            ['Khu vực', 'Khu vực mà tỉnh/TP trực thuộc. Mặc định ẩn.'],
            ['Người cập nhật', 'Người sửa bản ghi gần nhất. Mặc định ẩn.'],
            ['Ngày cập nhật', 'Thời điểm sửa gần nhất, dạng dd/mm/yyyy hh:mm. Mặc định ẩn, sắp xếp được.'],
            ['Người tạo', 'Người đã thêm bản ghi.'],
            ['Ngày tạo', 'Thời điểm thêm, dạng dd/mm/yyyy hh:mm, sắp xếp được.'],
            ['Trạng thái', 'Nhãn Hoạt động hoặc Khóa.'],
            ['Hành động', 'Các nút thao tác của dòng (xem mục 4).'],
        ],
        'hanh_dong': {
            'intro': 'Trên mỗi dòng, cột Hành động có các nút:',
            'bullets': [
                'Biểu tượng bút chì {icon:btn_sua} — mở cửa sổ Sửa Tỉnh/TP. Chỉ hiện khi tỉnh/TP đang Hoạt động.',
                'Biểu tượng thùng rác {icon:btn_xoa} — xóa tỉnh/TP. Chỉ hiện khi tỉnh/TP đang Hoạt động, CHƯA có Phường/Xã nào trực thuộc và CHƯA có nhân sự nào dùng tỉnh/TP này làm địa chỉ thường trú/tạm trú.',
                'Khóa / Mở khóa — đổi trạng thái tỉnh/TP.',
                'Lịch sử — mở cửa sổ Lịch sử thay đổi.',
                'Có từ 4 nút trở lên thì 2 nút đầu hiện thẳng, các nút còn lại nằm trong nút ba chấm {icon:btn_bacham} “Hành động khác”. Dòng không có nút Xóa (tỉnh/TP đã có dữ liệu bên dưới) thì cả 3 nút Sửa, Khóa, Lịch sử hiện thẳng.',
            ],
            'anh': 'Các nút ở cột Hành động của một tỉnh/TP',
            'luu_y': ['Lưu ý quan trọng: với bản ghi ĐÃ KHÓA, nút Sửa và Xóa sẽ BIẾN MẤT, chỉ còn Mở khóa và Lịch sử. Muốn sửa lại, Người dùng phải Mở khóa trước.'],
        },
        'phan_trang': [
            'Cuối bảng có dòng “Hiển thị a–b / N”: N là tổng số tỉnh/TP khớp bộ lọc đang áp dụng, không phải tổng toàn danh mục.',
            'Ô Số dòng/trang có các mức 5, 10, 20, 50, 100 (mặc định 10). Đổi số dòng thì hệ thống tự quay về trang 1.',
            'Các cột sắp xếp được: Tên Tỉnh/TP, Mã Tỉnh/TP, Ngày tạo, Ngày cập nhật. Bấm tiêu đề cột để sắp xếp, bấm lần hai để đảo chiều. Thứ tự sắp xếp được giữ nguyên khi chuyển trang. Chưa bấm sắp xếp thì bản ghi thêm gần nhất nằm trên cùng.',
        ],
    },

    'loc': {
        'buoc2': 'Bước 2: Nhập chữ vào ô tìm kiếm nhanh hoặc chọn giá trị ở ô Quốc gia, Trạng thái.',
        'rows': [
            ['Ô tìm kiếm nhanh', 'Tìm theo TÊN tỉnh/TP (gõ một phần tên cũng ra). Không tìm theo mã. Nhấn Enter hoặc bấm Tìm kiếm để lọc.'],
            ['Quốc gia', 'Chọn một quốc gia để chỉ xem tỉnh/TP của quốc gia đó. Lọc ngay khi chọn.'],
            ['Trạng thái', 'Hoạt động hoặc Khóa. Bỏ trống thì hiện cả hai trạng thái (mặc định khi vào màn hình). Lọc ngay khi chọn.'],
        ],
        'ap_dung': [
            'Các tiêu chí kết hợp với nhau theo kiểu VÀ — chỉ bản ghi thỏa đồng thời tất cả các tiêu chí mới hiện ra. Mỗi lần đổi tiêu chí, danh sách quay về trang 1.',
            'Bấm {icon:btn_lammoi} để xóa toàn bộ tiêu chí; danh sách nạp lại đầy đủ ngay lập tức.',
        ],
        'anh_ket_qua': 'Kết quả tìm nhanh theo tên tỉnh/TP (gõ “Thành phố”)',
    },

    'form': {
        'kieu': 'popup',
        'buoc_tao': [
            'Bước 1: Truy cập vào màn hình Danh mục Tỉnh/TP.',
            'Bước 2: Bấm {icon:btn_taomoi}. Hệ thống mở cửa sổ “Tạo Tỉnh/TP”.',
            'Bước 3: Nhập/ chọn đầy đủ thông tin: Tên tỉnh/TP, Mã số tỉnh (nếu có), Biển số xe, Quốc gia, Khu vực, Trạng thái.',
            'Bước 4: Bấm {icon:btn_luu} để lưu và đóng cửa sổ, hoặc {icon:btn_luutieptuc} để lưu rồi nhập tiếp tỉnh/TP khác.',
        ],
        'anh_tao': 'Cửa sổ Tạo Tỉnh/TP',
        'truong': [
            ['Tên tỉnh/TP', 'Ô nhập giá trị', 'Có', 'Trống', 'Tối đa 255 ký tự. Không được trùng trong cùng một cặp Quốc gia và Khu vực (cùng tên ở khu vực khác vẫn lưu được). Bỏ trống báo “Bắt buộc phải nhập”; trùng báo “Tên khu vực này đã tồn tại”.'],
            ['Mã số tỉnh', 'Ô nhập giá trị', 'Không', 'Trống', 'Chỉ nhận chữ số, tối đa 10 chữ số, không yêu cầu duy nhất. Kiểm tra ngay khi gõ: có chữ cái/ký tự đặc biệt báo “Phải là số”; quá 10 chữ số hoặc có dấu chấm, dấu phẩy, dấu trừ (vd 1.5, -5) báo “Chỉ được nhập chữ số, từ 0 đến 10 chữ số”.'],
            ['Biển số xe', 'Ô nhập giá trị', 'Có', 'Trống', 'Chỉ nhận chữ số, tối đa 50 chữ số. Nhập sai báo ngay “Chỉ được nhập chữ số, từ 0 đến 50 chữ số”; bỏ trống thì khi Lưu báo “Bắt buộc phải nhập”.'],
            ['Quốc gia', 'Ô chọn giá trị', 'Có', 'Trống', 'Chỉ liệt kê quốc gia đang Hoạt động. Tỉnh/TP đang dùng một quốc gia đã khóa vẫn hiện đúng tên quốc gia đó kèm biểu tượng 🔒. Đổi Quốc gia thì ô Khu vực bị xóa trắng. Bỏ trống báo “Bắt buộc phải nhập”.'],
            ['Khu vực', 'Ô chọn giá trị', 'Có', 'Trống', 'Chỉ liệt kê khu vực đang Hoạt động THUỘC quốc gia đã chọn; chưa chọn quốc gia thì ô hiện “Vui lòng chọn quốc gia trước”. Khu vực đã khóa đang được dùng vẫn hiện kèm 🔒. Bỏ trống báo “Bắt buộc phải nhập”.'],
            ['Trạng thái', 'Ô chọn giá trị', 'Có', 'Hoạt động', 'Chỉ chọn 1 trong 2 giá trị: Hoạt động / Khóa. Không xoá trắng được.'],
        ],
        'nut': [
            ['Lưu', 'Ghi bản ghi rồi đóng cửa sổ, báo “Thêm mới thành công” (hoặc “Cập nhật thành công” khi sửa) và nạp lại danh sách.'],
            ['Lưu và tiếp tục', 'Ghi bản ghi nhưng GIỮ cửa sổ mở và xóa trắng các ô để nhập tiếp. Chỉ có khi Tạo mới.'],
            ['Đóng', 'Đóng cửa sổ, không ghi gì. Nếu đã nhập dở, hệ thống hỏi “Thông tin chưa lưu” — “Bạn có thông tin chưa lưu. Có chắc chắn muốn thoát?” (Thoát / Ở lại).'],
        ],
        'loi': [
            ['Bắt buộc phải nhập', 'Chưa nhập một trong các ô bắt buộc: Tên tỉnh/TP, Biển số xe, Quốc gia, Khu vực.'],
            ['Tên khu vực này đã tồn tại', 'Đã có tỉnh/TP khác cùng tên trong cùng một cặp Quốc gia và Khu vực. Hãy kiểm tra lại danh sách trước khi thêm. (Câu thông báo hiện dùng chữ “khu vực” dù đang ở màn Tỉnh/TP.)'],
            ['Phải là số', 'Ô Mã số tỉnh có chữ cái hoặc ký tự đặc biệt. Chỉ nhập chữ số.'],
            ['Chỉ được nhập chữ số, từ 0 đến 10 chữ số', 'Ô Mã số tỉnh dài quá 10 chữ số hoặc có dấu chấm, dấu phẩy, dấu trừ.'],
            ['Chỉ được nhập chữ số, từ 0 đến 50 chữ số', 'Ô Biển số xe có ký tự không phải chữ số hoặc dài quá 50 chữ số.'],
            ['Vui lòng nhập tối đa 255 ký tự.', 'Tên tỉnh/TP quá dài.'],
            ['Vui lòng kiểm tra lại dữ liệu nhập', 'Thông báo chung khi còn ô bị lỗi; xem các ô báo đỏ trong cửa sổ.'],
        ],
    },

    'sua': {
        'buoc': [
            'Bước 1: Truy cập vào màn hình Danh mục Tỉnh/TP.',
            'Bước 2: Bấm nút {icon:btn_sua} ở cột Hành động của tỉnh/TP cần sửa.',
            'Bước 3: Hệ thống hiển thị cửa sổ “Sửa Tỉnh/TP” với dữ liệu hiện tại.',
            'Bước 4: Cập nhật các thông tin cần sửa (quy tắc nhập như Thêm mới).',
            'Bước 5: Bấm {icon:btn_luu} để xác nhận thay đổi hoặc Đóng nếu muốn hủy.',
        ],
        'anh': 'Cửa sổ Sửa Tỉnh/TP',
        'ghi_chu': [
            'Giữ nguyên tên của chính tỉnh/TP đang sửa thì không bị báo trùng.',
            'Tỉnh/TP đang Khóa không có nút Sửa. Nếu tỉnh/TP vừa bị người khác khóa, bấm Lưu sẽ nhận thông báo “Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.”',
            'Đổi tên quốc gia/khu vực ở danh mục tương ứng thì các cột Quốc gia, Khu vực của tỉnh/TP tự hiển thị tên mới.',
        ],
    },
    'xoa': {
        'buoc': [
            'Bước 1: Ở cột Hành động, Người dùng bấm {icon:btn_xoa}.',
            'Bước 2: Hệ thống hiện hộp xác nhận “Xóa Tỉnh/TP” — “Bạn có chắc muốn xóa tỉnh/TP "…"?”. Bấm {icon:btn_confirm_xoa} để xác nhận: hệ thống báo “Xoá tỉnh/thành phố thành công”, bản ghi biến mất khỏi danh sách.',
            'Bấm {icon:btn_huy} nếu bấm nhầm. Không có gì thay đổi.',
        ],
        'anh': 'Hộp xác nhận xóa tỉnh/TP',
        'ghi_chu': ['Nút Xóa chỉ hiện khi tỉnh/TP đang Hoạt động, chưa có Phường/Xã trực thuộc và chưa có nhân sự nào dùng làm địa chỉ. Tỉnh/TP đã có dữ liệu bên dưới thì dùng Khóa thay cho Xóa. Nếu bản ghi vừa bị người khác xóa trước đó, hệ thống báo “Trạng thái đã bị thay đổi. Vui lòng load lại trang” và không xóa lần hai.'],
    },
    'khoa': {
        'y_nghia': [
            'Bản ghi VẪN nằm trong danh sách, cột Trạng thái hiện chữ Khóa.',
            'Vẫn xem được chi tiết và lịch sử thay đổi của bản ghi.',
            'Tỉnh/TP đã khóa không còn xuất hiện ở ô chọn tỉnh/TP của các màn khác (ví dụ Danh mục Phường/Xã, Quận/Huyện, hồ sơ nhân sự); dữ liệu đang dùng tỉnh/TP đó vẫn giữ nguyên và hiển thị kèm 🔒.',
            'Nút Sửa và Xóa của dòng đó biến mất.',
        ],
        'buoc_khoa': [
            'Bước 1: Ở cột Hành động, Người dùng chọn Khóa (trong nút ba chấm nếu dòng có nhiều nút).',
            'Bước 2: Hệ thống hiện hộp xác nhận “Khóa Tỉnh/TP” — “Bạn có chắc muốn khóa tỉnh/TP "…"?”. Bấm Khóa để xác nhận; hệ thống báo “Khóa thành công”, cột Trạng thái đổi thành Khóa. Bấm Hủy nếu bấm nhầm.',
        ],
        'buoc_mo': [
            'Bước 1: Ở cột Hành động của tỉnh/TP đang Khóa, Người dùng chọn Mở khóa.',
            'Bước 2: Bấm Mở khóa trong hộp xác nhận “Mở khóa Tỉnh/TP”. Hệ thống báo “Mở khóa thành công”, cột Trạng thái đổi thành Hoạt động. Bấm Hủy nếu bấm nhầm.',
        ],
        'ghi_chu': ['Có thể khóa ngay trong cửa sổ Sửa bằng cách chọn Trạng thái = Khóa rồi Lưu. Nếu bản ghi vừa bị người khác đổi trạng thái, hệ thống báo “Trạng thái đã bị thay đổi. Vui lòng load lại trang”.'],
    },
    'lich_su': {
        'buoc': [
            'Xem từ màn danh sách: ở cột Hành động, Người dùng chọn Lịch sử.',
            'Xem từ màn chi tiết: bấm vào tên tỉnh/TP để mở cửa sổ Xem Tỉnh/TP, khối Lịch sử nằm ở cuối cửa sổ.',
        ],
        'ghi_chu': ['Cửa sổ có bộ lọc riêng (loại hành động, người thực hiện, khoảng thời gian) để thu hẹp danh sách khi bản ghi có nhiều lần thay đổi. Trường Quốc gia, Khu vực trong lịch sử hiển thị bằng TÊN.'],
    },
    'chi_tiet': {
        'buoc': ['Bước 1: Truy cập vào màn hình Danh mục Tỉnh/TP.',
                 'Bước 2: Bấm vào tên tỉnh/TP ở cột Tên Tỉnh/TP. Hệ thống mở cửa sổ “Xem Tỉnh/TP”.'],
        'ghi_chu': ['Cửa sổ hiển thị Tên tỉnh/TP, Mã số tỉnh, Biển số xe, Quốc gia, Khu vực và Trạng thái ở chế độ chỉ đọc (không gõ được, không có nút Lưu), kèm khối Lịch sử ở cuối. Tỉnh/TP đang Khóa vẫn xem được bình thường.'],
    },
    'xuat': {
        'buoc': [
            'Bước 1: Lọc danh sách theo đúng dữ liệu cần lấy (xem PHẦN 2). File xuất ra chạy theo đúng bộ lọc đang áp dụng.',
            'Bước 2: Bấm nút {icon:btn_xuatexcel}. Hệ thống mở cửa sổ “Chọn trường xuất file”.',
            'Bước 3: Tích chọn, kéo biểu tượng ☰ để đổi vị trí các trường cần xuất. Mặc định hệ thống tích sẵn đúng những cột đang hiển thị trên bảng.',
            'Bước 4: Bấm {icon:btn_xuatfile}. Hệ thống tải về file danh_muc_tinh_thanh_pho.xlsx và báo “Xuất Excel thành công”.',
        ],
        'truong': 'Chọn nhiều trường: Tên tỉnh/TP, Mã số tỉnh, Biển số xe, Quốc gia, Khu vực, Trạng thái, Người tạo, Ngày tạo, Người cập nhật, Ngày cập nhật.',
        'ghi_chu': ['Lưu ý: file xuất chứa TOÀN BỘ kết quả của bộ lọc (tối đa 10,000 dòng), không chỉ các dòng của trang đang xem.'],
    },
    'import': {
        'tieu_de': 'Import tỉnh/TP',
        'file': 'Mau_import_tinh_thanh_pho.xlsx',
        'cot_text': 'Tên tỉnh/TP (bắt buộc), Mã số tỉnh (không bắt buộc, chỉ chữ số), Biển số xe (bắt buộc, chỉ chữ số), Tên quốc gia (bắt buộc, chọn trong danh sách sổ xuống), Tên khu vực (bắt buộc, chọn trong danh sách sổ xuống)',
        'toast': 'Import thành công N tỉnh/TP.',
        'loi': [
            ['Tên tỉnh/TP không được để trống', 'Dòng đó bỏ trống cột Tên tỉnh/TP.'],
            ['Tên tỉnh/TP tối đa 255 ký tự', 'Tên quá dài, rút gọn lại.'],
            ['Mã số tỉnh phải là số', 'Cột Mã số tỉnh có chữ cái hoặc ký tự đặc biệt.'],
            ['Mã số tỉnh tối đa 10 chữ số', 'Cột Mã số tỉnh dài quá 10 chữ số.'],
            ['Biển số xe không được để trống', 'Dòng đó bỏ trống cột Biển số xe.'],
            ['Biển số xe chỉ gồm chữ số', 'Cột Biển số xe có ký tự không phải chữ số.'],
            ['Biển số xe tối đa 50 chữ số', 'Cột Biển số xe dài quá 50 chữ số.'],
            ['Tên quốc gia không được để trống', 'Dòng đó bỏ trống cột Tên quốc gia.'],
            ['Không tìm thấy quốc gia: X', 'Tên quốc gia ghi sai, không có trong Danh mục quốc gia.'],
            ['Tên khu vực không được để trống', 'Dòng đó bỏ trống cột Tên khu vực.'],
            ['Không tìm thấy khu vực "Y" thuộc quốc gia X', 'Khu vực ghi sai hoặc không thuộc quốc gia đã ghi trên cùng dòng.'],
            ['Tỉnh/TP bị trùng với dòng N trong file', 'Trong chính file có hai dòng cùng tên, cùng quốc gia và khu vực. Xoá bớt một dòng.'],
            ['Tỉnh/TP này đã tồn tại trong khu vực đã chọn', 'Danh mục đã có tỉnh/TP trùng tên trong cùng quốc gia và khu vực.'],
        ],
        'ghi_chu': ['Lưu ý: tỉnh/TP nhập từ Excel luôn được tạo ở trạng thái Hoạt động, người tạo là chính người thực hiện nhập. Mỗi lần nhập tối đa 500 dòng; file dài hơn hệ thống báo “File có X dòng dữ liệu, vượt quá giới hạn 500 dòng mỗi lần import. Vui lòng tách file và import nhiều lần.”'],
    },
    'tuy_chinh_cot': {'cot_khoa': 'Ba cột STT, Tên Tỉnh/TP và Hành động'},

    'shots': {'list': '01_list.png', 'rowmenu': '03_rowmenu.png', 'filter': 'filter.png', 'filter_result': '04_filter_result.png',
              'create': '10_create.png', 'create_error': '11_create_error.png', 'code_error': '11b_code_error.png', 'edit': '12_edit.png',
              'delete': '13_delete.png', 'lock': '14_lock.png', 'unlock': '15_unlock.png', 'history': '16_history.png',
              'detail': '17_detail.png', 'export': '20_export.png', 'import_open': '21_import_open.png',
              'import_loaded': '22_import_loaded.png', 'import_validated': '23_import_validated.png', 'colcfg': '25_colcfg.png'},

    'capture': {'route': '/human/provinces', 'menu': {'phanhe': 'DANH MỤC', 'nhom': 'Địa lý', 'muc': 'Tỉnh/TP'},
                'search': 'Tìm theo tên Tỉnh/TP', 'searchText': 'Thành phố', 'detailCol': 1,
                'lockName': 'Vientiane', 'codeInput': 'Nhập mã số tỉnh', 'create': True, 'lock': True},

    'import_test': {
        'cols': ['Tên tỉnh/TP', 'Mã số tỉnh', 'Biển số xe', 'Tên quốc gia', 'Tên khu vực'],
        'rows': [
            ['DOC-Tỉnh Mẫu Một', '901', '901', 'Việt Nam', 'Miền Bắc'],
            ['DOC-Tỉnh Mẫu Hai', '', '902', 'Việt Nam', 'Miền Nam'],
            ['', '903', '903', 'Việt Nam', 'Miền Bắc'],
            ['DOC-Tỉnh Mẫu Một', '904', '904', 'Việt Nam', 'Miền Bắc'],
            ['DOC-Tỉnh Mẫu Ba', 'AB12', '905', 'Việt Nam', 'Miền Bắc'],
            ['DOC-Tỉnh Mẫu Bốn', '906', '', 'Việt Nam', 'Miền Trung'],
            ['DOC-Tỉnh Mẫu Năm', '907', '907', 'Nước không tồn tại', 'Miền Bắc'],
            ['DOC-Tỉnh Mẫu Sáu', '908', '908', 'Việt Nam', 'Khu vực không tồn tại'],
        ],
    },

    'uml': {
        'mains': [('FR-01', 'Xem danh sách tỉnh/TP', 'view'), ('FR-03', 'Thêm mới tỉnh/TP', 'crud'),
                  ('FR-04', 'Chỉnh sửa tỉnh/TP', 'crud'), ('FR-05', 'Xóa tỉnh/TP', 'action'),
                  ('FR-06', 'Khóa / Mở khóa tỉnh/TP', 'action'), ('FR-08', 'Import file tỉnh/TP', 'io'),
                  ('FR-09', 'Xuất danh sách tỉnh/TP ra Excel', 'io')],
        'subs': [('FR-02', 'Tìm kiếm và lọc tỉnh/TP', 'view'), ('FR-10', 'Xem chi tiết tỉnh/TP', 'view'),
                 ('FR-11', 'Tùy chỉnh cột hiển thị', 'view'), ('FR-07', 'Xem lịch sử thay đổi', 'view')],
        'rieng': [('FR-10', 'Xem chi tiết tỉnh/TP', 'view')],
    },

    'srs': {
        'muc_dich': ['Là căn cứ nghiệm thu chức năng.',
                     'Làm rõ ràng buộc trùng tên tỉnh/TP (duy nhất trong cùng cặp Quốc gia + Khu vực), quy tắc ô Mã số tỉnh / Biển số xe và quan hệ Quốc gia → Khu vực → Tỉnh/TP → Phường/Xã.'],
        'quyen_truoc': ['Danh sách quyền sẽ được cập nhật sau khi có tài liệu phân quyền chi tiết của hệ thống. Tại thời điểm xây dựng SRS, màn hình chưa gắn quyền; mọi người dùng đã đăng nhập đều thực hiện được các chức năng.'],
        'quyen_rows': [['(chưa khai báo quyền nào)', 'Sẽ cập nhật sau khi có tài liệu phân quyền chi tiết']],
        'ma_tran': [['Chức năng', 'Người dùng đã đăng nhập']] + [[f, 'Chờ cập nhật theo ma trận phân quyền chi tiết'] for f in [
            'FR-01 Xem danh sách tỉnh/TP', 'FR-02 Tìm kiếm và lọc', 'FR-03 Thêm mới tỉnh/TP', 'FR-04 Chỉnh sửa tỉnh/TP',
            'FR-05 Xóa tỉnh/TP', 'FR-06 Khóa / Mở khóa tỉnh/TP', 'FR-07 Xem lịch sử thay đổi', 'FR-08 Import file tỉnh/TP',
            'FR-09 Xuất danh sách ra Excel', 'FR-10 Xem chi tiết tỉnh/TP', 'FR-11 Tùy chỉnh cột hiển thị']],
        'ma_tran_widths': [2.4, 2.4],
        'fr': [
            {'ten': 'Xem danh sách tỉnh/TP',
             'qtc': 'Màn Danh sách, Sắp xếp dữ liệu bảng, Phân trang và Cấu hình cột. Chỉ bổ sung các quy tắc riêng của Danh mục Tỉnh/TP tại phần mô tả chi tiết.',
             'gioi_thieu': [['Tên chức năng', 'Xem danh sách tỉnh/TP'],
                            ['Mô tả', 'Hiển thị toàn bộ tỉnh/TP trong danh mục (cả Hoạt động lẫn Khóa), có phân trang và sắp xếp.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Điều kiện ban đầu', 'Người dùng đã đăng nhập vào hệ thống.'],
                            ['Dòng sự kiện chính', '1. Người dùng vào menu Danh mục → Địa lý → Tỉnh/TP.\n2. Hệ thống nạp trang đầu tiên của danh sách (10 dòng), bản ghi mới nhất trên cùng.\n3. Bảng hiển thị dữ liệu kèm tổng số bản ghi.'],
                            ['Dòng sự kiện phụ', '• Không có bản ghi khớp → bảng hiện “Không có dữ liệu phù hợp bộ lọc.”\n• Phiên đăng nhập hết hạn → điều hướng về màn đăng nhập.']],
             'anh': [('list', 'Màn Danh mục Tỉnh/TP lúc mới truy cập')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Mô tả'],
                    ['1', 'STT', 'Table/Grid', 'Read-only', 'Số thứ tự, chạy liên tục qua các trang. Luôn hiển thị, không ẩn được.'],
                    ['2', 'Tên Tỉnh/TP', 'Table/Grid', 'Read-only', 'Luôn hiển thị, sắp xếp được. Bấm vào tên mở cửa sổ Xem (xem 2.10).'],
                    ['3', 'Mã Tỉnh/TP', 'Table/Grid', 'Read-only', 'Mã số tỉnh, sắp xếp được, có thể trống.'],
                    ['4', 'Biển số xe', 'Table/Grid', 'Read-only', 'Mặc định ẩn.'],
                    ['5', 'Quốc gia', 'Table/Grid', 'Read-only', 'Mặc định ẩn.'],
                    ['6', 'Khu vực', 'Table/Grid', 'Read-only', 'Mặc định ẩn.'],
                    ['7', 'Người cập nhật', 'Table/Grid', 'Read-only', 'Mặc định ẩn.'],
                    ['8', 'Ngày cập nhật', 'Table/Grid', 'Read-only', 'dd/mm/yyyy hh:mm. Mặc định ẩn, sắp xếp được.'],
                    ['9', 'Người tạo', 'Table/Grid', 'Read-only', 'Người đã thêm bản ghi.'],
                    ['10', 'Ngày tạo', 'Table/Grid', 'Read-only', 'dd/mm/yyyy hh:mm, sắp xếp được.'],
                    ['11', 'Trạng thái', 'Badge', 'Read-only', 'Hoạt động hoặc Khóa.'],
                    ['12', 'Hành động', 'Table/Grid', 'Read-only', 'Sửa (khi Hoạt động), Xóa (khi Hoạt động, chưa có Phường/Xã trực thuộc và chưa có nhân sự dùng làm địa chỉ), Khóa / Mở khóa, Lịch sử. Từ 4 nút trở lên thì 2 nút đầu hiện thẳng, còn lại trong nút ba chấm.'],
                    ['13', 'Nút Tạo mới', 'Button', 'Enable', 'Mở cửa sổ Tạo Tỉnh/TP.'],
                    ['14', 'Nút Xuất Excel', 'Button', 'Enable', 'Mở cửa sổ Chọn trường xuất file (xem 2.9).'],
                    ['15', 'Nút Import Excel', 'Button', 'Enable', 'Mở cửa sổ Import tỉnh/TP (xem 2.8).'],
                    ['16', 'Biểu tượng Cấu hình cột hiển thị', 'Icon Button', 'Enable', 'Mở cửa sổ Tuỳ chỉnh cột (xem 2.11).'],
                    ['17', 'Phân trang', 'Pagination', 'Enable', 'Số dòng/trang 5 / 10 / 20 / 50 / 100, mặc định 10.']],
             'ui_widths': [0.6, 1.4, 0.9, 0.8, 3],
             'events': [['Mở màn hình', 'System', 'After:\n– Nạp trang đầu, hiển thị tổng số bản ghi.'],
                        ['Bấm tiêu đề cột sắp xếp được', 'Click', 'After:\n– Đổi chiều sắp xếp và nạp lại danh sách từ trang 1.'],
                        ['Chuyển trang', 'Click', 'Before:\n– Giữ nguyên bộ lọc và thứ tự sắp xếp.\nAfter:\n– Nạp dữ liệu trang mới, số thứ tự tiếp tục liên tục.'],
                        ['Đổi số dòng mỗi trang', 'Change', 'After:\n– Quay về trang 1 và nạp lại theo số dòng mới.']]},
            {'ten': 'Tìm kiếm và lọc',
             'qtc': 'Kịch bản tìm kiếm, Bộ lọc, Dropdown, Phân trang. Chỉ bổ sung các tiêu chí tìm kiếm/lọc riêng của Danh mục Tỉnh/TP.',
             'gioi_thieu': [['Tên chức năng', 'Tìm kiếm và lọc danh sách'],
                            ['Mô tả', 'Thu hẹp danh sách bằng ô tìm kiếm nhanh, ô Quốc gia và ô Trạng thái.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Điều kiện ban đầu', 'Đang ở màn Danh mục Tỉnh/TP.'],
                            ['Dòng sự kiện chính', '1. Người dùng nhập từ khóa và bấm Tìm kiếm / Enter, hoặc chọn Quốc gia / Trạng thái (lọc ngay).\n2. Hệ thống áp đồng thời mọi tiêu chí và nạp lại danh sách từ trang 1.'],
                            ['Dòng sự kiện phụ', '• Không có kết quả → bảng hiện thông báo không có dữ liệu.\n• Bấm Làm mới → xóa hết tiêu chí VÀ nạp lại danh sách đầy đủ ngay.']],
             'anh': [('filter', 'Khu vực tìm kiếm và lọc của màn Danh mục Tỉnh/TP')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Phạm vi', 'Mô tả'],
                    ['1', 'Ô tìm kiếm nhanh', 'Textbox', 'Enable', '0–255 ký tự', 'Placeholder “Tìm theo tên Tỉnh/TP”. Tìm theo TÊN (khớp một phần), không tìm theo mã.'],
                    ['2', 'Quốc gia', 'Dropdown', 'Enable', 'Danh mục quốc gia', 'Nhãn nổi. Bỏ trống thì hiện mọi quốc gia.'],
                    ['3', 'Trạng thái', 'Dropdown', 'Enable', 'Hoạt động / Khóa', 'Nhãn nổi. Bỏ trống thì hiện cả hai trạng thái (mặc định).'],
                    ['4', 'Nút Tìm kiếm', 'Button', 'Enable', '–', 'Áp dụng các tiêu chí.'],
                    ['5', 'Nút Làm mới', 'Button', 'Enable', '–', 'Xóa hết tiêu chí VÀ nạp lại danh sách ngay.']],
             'ui_widths': [0.6, 1.2, 0.8, 0.7, 1.1, 2.6],
             'events': [['Bấm Tìm kiếm / Enter', 'Click', 'After:\n– Áp đồng thời các tiêu chí theo kiểu “và”, nạp lại bảng từ trang 1.'],
                        ['Chọn Quốc gia / Trạng thái', 'Change', 'After:\n– Lọc ngay, nạp lại bảng từ trang 1.'],
                        ['Bấm Làm mới', 'Click', 'After:\n– Xóa trắng mọi tiêu chí VÀ nạp lại danh sách đầy đủ.']]},
            {'ten': 'Thêm mới tỉnh/TP', 'uc': 'uc_fr03',
             'qtc': 'Màn Thêm mới, Validate dữ liệu, Thông báo và UI/UX. Logic ghi lịch sử áp dụng theo SRS Các quy tắc chung - Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Thêm mới tỉnh/TP'],
                            ['Mô tả', 'Thêm một tỉnh/TP mới thông qua cửa sổ nhập liệu.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập (chờ cập nhật theo phân quyền chi tiết).'],
                            ['Điều kiện ban đầu', 'Đang ở màn Danh mục Tỉnh/TP.'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm Tạo mới.\n2. Hệ thống mở cửa sổ “Tạo Tỉnh/TP”, Trạng thái mặc định Hoạt động.\n3. Người dùng nhập Tên tỉnh/TP, Mã số tỉnh (nếu có), Biển số xe, chọn Quốc gia, Khu vực và bấm Lưu.\n4. Hệ thống kiểm tra dữ liệu, ghi bản ghi mới và ghi lịch sử Tạo mới.\n5. Cửa sổ đóng, danh sách nạp lại, báo “Thêm mới thành công”.'],
                            ['Dòng sự kiện phụ', '• Mã số tỉnh / Biển số xe sai định dạng → báo đỏ ngay khi gõ.\n• Thiếu trường bắt buộc hoặc trùng tên → báo lỗi đỏ dưới ô + toast “Vui lòng kiểm tra lại dữ liệu nhập”, cửa sổ KHÔNG đóng.\n• Bấm “Lưu và tiếp tục” → ghi bản ghi rồi giữ cửa sổ mở với các ô trống.\n• Bấm Đóng khi đã nhập dở → hỏi “Thông tin chưa lưu” (Thoát / Ở lại).'],
                            ['Yêu cầu đặc biệt', 'Cửa sổ có ba nút: Lưu, Lưu và tiếp tục, Đóng.']],
             'menu_them': ' => Tạo mới {icon:btn_taomoi}',
             'ghi_chu_layout': 'Cửa sổ Tạo Tỉnh/TP được mở ngay trên màn hình danh sách.',
             'anh': [('create', 'Cửa sổ Tạo Tỉnh/TP'), ('create_error', 'Lỗi đỏ ngay dưới ô còn thiếu'), ('code_error', 'Lỗi định dạng Mã số tỉnh hiện ngay khi gõ')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Phạm vi', 'Bắt buộc', 'Mô tả'],
                    ['1', 'Tên tỉnh/TP', 'Textbox', 'Enable', '1–255 ký tự', 'Có', 'Duy nhất trong cùng cặp Quốc gia + Khu vực. Bỏ trống “Bắt buộc phải nhập”; trùng “Tên khu vực này đã tồn tại”; quá dài “Vui lòng nhập tối đa 255 ký tự.”'],
                    ['2', 'Mã số tỉnh', 'Textbox', 'Enable', '0–10 chữ số', 'Không', 'Chỉ chữ số, không yêu cầu duy nhất. Có chữ/ký tự đặc biệt “Phải là số”; quá 10 chữ số “Chỉ được nhập chữ số, từ 0 đến 10 chữ số”.'],
                    ['3', 'Biển số xe', 'Textbox', 'Enable', '1–50 chữ số', 'Có', 'Chỉ chữ số. Sai “Chỉ được nhập chữ số, từ 0 đến 50 chữ số”; bỏ trống “Bắt buộc phải nhập”.'],
                    ['4', 'Quốc gia', 'Dropdown', 'Enable', 'Quốc gia đang Hoạt động', 'Có', 'Đổi Quốc gia thì xóa trắng Khu vực. Bỏ trống “Bắt buộc phải nhập”.'],
                    ['5', 'Khu vực', 'Dropdown', 'Enable', 'Khu vực Hoạt động thuộc quốc gia đã chọn', 'Có', 'Chưa chọn quốc gia hiện “Vui lòng chọn quốc gia trước”. Bỏ trống “Bắt buộc phải nhập”.'],
                    ['6', 'Trạng thái', 'Dropdown', 'Enable', 'Hoạt động / Khóa', 'Có', 'Mặc định Hoạt động.'],
                    ['7', 'Nút Lưu', 'Button', 'Enable', '', '', 'Ghi bản ghi rồi đóng cửa sổ.'],
                    ['8', 'Nút Lưu và tiếp tục', 'Button', 'Enable', '', '', 'Ghi bản ghi rồi giữ cửa sổ mở để nhập tiếp.'],
                    ['9', 'Nút Đóng', 'Button', 'Enable', '', '', 'Hủy bỏ, không ghi gì.']],
             'ui_widths': [0.6, 1.3, 0.8, 0.6, 1.1, 0.5, 2.3],
             'events': [['Bấm nút Tạo mới', 'Click', 'After:\n– Mở cửa sổ nhập liệu với các ô trống, Trạng thái = Hoạt động.'],
                        ['Gõ Mã số tỉnh / Biển số xe', 'Input', 'During:\n– Kiểm tra định dạng chữ số và độ dài, sai thì báo đỏ ngay dưới ô.'],
                        ['Đổi Quốc gia', 'Change', 'After:\n– Xóa trắng ô Khu vực, nạp danh sách khu vực của quốc gia mới.'],
                        ['Bấm Lưu', 'Click', 'During:\n– Kiểm tra bắt buộc, định dạng, độ dài, trùng tên trong cùng Quốc gia + Khu vực.\n– Có lỗi → báo đỏ dưới ô, không thực hiện After.\nAfter:\n– Ghi bản ghi mới, ghi lịch sử Tạo mới.\n– Đóng cửa sổ, nạp lại danh sách, báo “Thêm mới thành công”.'],
                        ['Bấm Lưu và tiếp tục', 'Click', 'During:\n– Như nút Lưu.\nAfter:\n– Ghi bản ghi, xóa trắng các ô, GIỮ cửa sổ mở.'],
                        ['Bấm Đóng', 'Click', 'After:\n– Chưa nhập gì → đóng cửa sổ. Đã nhập → hỏi “Thông tin chưa lưu”.']]},
            {'ten': 'Chỉnh sửa tỉnh/TP', 'uc': 'uc_fr04',
             'qtc': 'Validate dữ liệu, Thông báo, Quy định chung về danh mục và Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Chỉnh sửa tỉnh/TP'],
                            ['Mô tả', 'Sửa thông tin một tỉnh/TP đã có. Dùng chung cửa sổ với Thêm mới.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Điều kiện ban đầu', 'Tỉnh/TP đang ở trạng thái Hoạt động.'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm biểu tượng bút chì ở dòng cần sửa.\n2. Hệ thống mở cửa sổ “Sửa Tỉnh/TP” với dữ liệu hiện tại.\n3. Người dùng sửa và bấm Lưu.\n4. Hệ thống kiểm tra, ghi thay đổi và ghi lịch sử.\n5. Cửa sổ đóng, báo “Cập nhật thành công”.'],
                            ['Dòng sự kiện phụ', '• Giữ nguyên tên của chính bản ghi → không báo trùng.\n• Trùng tên với tỉnh/TP khác cùng Quốc gia + Khu vực → báo “Tên khu vực này đã tồn tại”.\n• Bản ghi vừa bị người khác khóa → báo “Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.”']],
             'menu_them': ' => Sửa {icon:btn_sua}',
             'anh': [('edit', 'Cửa sổ Sửa Tỉnh/TP')],
             'events': [['Bấm biểu tượng bút chì', 'Click', 'Before:\n– Bản ghi đã Khóa thì nút không hiển thị.\nAfter:\n– Mở cửa sổ với dữ liệu hiện tại.'],
                        ['Bấm Lưu', 'Click', 'During:\n– Kiểm tra như Thêm mới, bỏ qua trùng với chính bản ghi.\n– Bản ghi đang Khóa → từ chối, báo “Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.”\nAfter:\n– Ghi thay đổi, ghi lịch sử “Thay đổi thông tin” (đổi Trạng thái ghi “Khóa”/“Mở khóa”), báo “Cập nhật thành công”.']]},
            {'ten': 'Xóa tỉnh/TP', 'uc': 'uc_fr05',
             'qtc': 'Quy tắc Xóa, Thông báo, Quy định chung về danh mục và Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Xóa tỉnh/TP'],
                            ['Mô tả', 'Xóa hẳn một tỉnh/TP chưa có dữ liệu phụ thuộc.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Điều kiện ban đầu', 'Tỉnh/TP đang Hoạt động, chưa có Phường/Xã trực thuộc và chưa có nhân sự nào dùng làm địa chỉ thường trú/tạm trú.'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm biểu tượng thùng rác.\n2. Hệ thống hiện hộp “Xóa Tỉnh/TP” nêu rõ tên bản ghi.\n3. Người dùng bấm Xóa.\n4. Hệ thống xóa bản ghi, báo “Xoá tỉnh/thành phố thành công”, nạp lại danh sách.'],
                            ['Dòng sự kiện phụ', '• Bấm Hủy → đóng hộp, không thay đổi.\n• Tỉnh/TP đã có dữ liệu phụ thuộc hoặc đang Khóa → nút Xóa KHÔNG hiển thị.\n• Lỗi khi xóa → báo “Xoá tỉnh/thành phố thất bại” (hoặc câu lỗi cụ thể từ hệ thống).']],
             'menu_them': ' => Xóa {icon:btn_xoa}',
             'anh': [('delete', 'Hộp xác nhận xóa tỉnh/TP')],
             'events': [['Bấm biểu tượng thùng rác', 'Click', 'After:\n– Hiện hộp xác nhận kèm tên bản ghi.'],
                        ['Bấm Xóa', 'Click', 'After:\n– Xóa bản ghi, ghi lịch sử, nạp lại danh sách, báo thành công.'],
                        ['Bấm Hủy', 'Click', 'After:\n– Đóng hộp, không thay đổi.']]},
            {'ten': 'Khóa / Mở khóa tỉnh/TP', 'uc': 'uc_fr06',
             'qtc': 'Quy tắc Khóa/Mở khóa, Thông báo, Quy định chung về danh mục và Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Khóa / Mở khóa tỉnh/TP'],
                            ['Mô tả', 'Đổi trạng thái tỉnh/TP giữa Hoạt động và Khóa. Bản ghi đã Khóa vẫn nằm trong danh mục nhưng không chọn được ở màn khác.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Điều kiện ban đầu', 'Bản ghi cần đổi trạng thái đang có trong danh sách.'],
                            ['Dòng sự kiện chính', '1. Người dùng chọn Khóa (hoặc Mở khóa) ở cột Hành động.\n2. Hệ thống hiện hộp xác nhận nêu rõ tên bản ghi.\n3. Người dùng xác nhận.\n4. Hệ thống đổi trạng thái, ghi lịch sử, báo “Khóa thành công” / “Mở khóa thành công”.'],
                            ['Dòng sự kiện phụ', '• Bấm Hủy → không thay đổi.\n• Sau khi Khóa, nút Sửa và Xóa biến mất.\n• Bản ghi đã bị người khác đổi trạng thái → báo “Trạng thái đã bị thay đổi. Vui lòng load lại trang”.']],
             'menu_them': ' => Khóa / Mở khóa',
             'anh': [('lock', 'Hộp xác nhận khóa tỉnh/TP'), ('rowmenu', 'Các nút ở cột Hành động')],
             'events': [['Chọn Khóa / Mở khóa', 'Click', 'After:\n– Hiện hộp xác nhận kèm tên bản ghi.'],
                        ['Xác nhận', 'Click', 'During:\n– Bản ghi đã ở trạng thái đích → báo dữ liệu đã thay đổi, dừng.\nAfter:\n– Đổi trạng thái, KHÔNG xóa dữ liệu, ghi lịch sử, cập nhật cột Trạng thái và các nút.'],
                        ['Bấm Hủy', 'Click', 'After:\n– Đóng hộp, không thay đổi.']]},
            {'ten': 'Xem lịch sử thay đổi',
             'qtc': 'Quy tắc ghi lịch sử và hiển thị lịch sử. Chỉ bổ sung thông tin riêng của Danh mục Tỉnh/TP nếu có.',
             'gioi_thieu': [['Tên chức năng', 'Xem lịch sử thay đổi'],
                            ['Mô tả', 'Liệt kê các lần thay đổi của một tỉnh/TP, kèm giá trị cũ → mới, người thực hiện và thời điểm. Quốc gia, Khu vực hiển thị bằng tên.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Dòng sự kiện chính', '1. Người dùng chọn Lịch sử ở cột Hành động, hoặc mở cửa sổ Xem Tỉnh/TP.\n2. Hệ thống mở cửa sổ “Lịch sử thay đổi: <tên>”, mốc mới nhất ở trên cùng.'],
                            ['Dòng sự kiện phụ', '• Bản ghi chưa từng thay đổi → “Chưa có lịch sử thao tác nào.”\n• Có bộ lọc theo loại hành động, người thực hiện, thời gian.']],
             'menu_them': ' => Lịch sử',
             'anh': [('history', 'Cửa sổ Lịch sử thay đổi của tỉnh/TP')]},
            {'ten': 'Import file tỉnh/TP', 'uc': 'uc_fr08',
             'qtc': 'Quy tắc Import file, Validate dữ liệu, Thông báo và Quy định chung về danh mục. Chỉ bổ sung mapping/validation riêng của Danh mục Tỉnh/TP.',
             'gioi_thieu': [['Tên chức năng', 'Import file tỉnh/TP'],
                            ['Mô tả', 'Thêm nhiều tỉnh/TP cùng lúc từ file Excel mẫu, có bước Validate trước khi ghi.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Điều kiện ban đầu', 'Đang ở màn Danh mục Tỉnh/TP và đã chuẩn bị file theo mẫu.'],
                            ['Dòng sự kiện chính', '1. Bấm Import Excel.\n2. Bấm Tải file mẫu (Mau_import_tinh_thanh_pho.xlsx), điền dữ liệu.\n3. Bấm Chọn file Excel rồi Load lên bảng.\n4. Bấm Validate; hệ thống kiểm tra từng dòng như quy tắc Thêm mới (mục 2.3), khóa dòng hợp lệ.\n5. Sửa dòng lỗi rồi Validate lại, hoặc bấm Bỏ dòng lỗi.\n6. Bấm Import; hệ thống ghi các dòng hợp lệ, báo “Import thành công N tỉnh/TP.”, đóng cửa sổ và nạp lại danh sách.'],
                            ['Dòng sự kiện phụ', '• File không phải .xlsx/.xls → “Vui lòng chọn file .xlsx hoặc .xls”.\n• Quá 500 dòng → “File có X dòng dữ liệu, vượt quá giới hạn 500 dòng mỗi lần import. Vui lòng tách file và import nhiều lần.”\n• Còn dòng lỗi → nút Import không bấm được.'],
                            ['Yêu cầu đặc biệt', 'Validate không ghi dữ liệu. Bản ghi import luôn ở trạng thái Hoạt động, người tạo là người thực hiện. Quốc gia và khu vực tra theo TÊN; khu vực phải thuộc đúng quốc gia ghi trên cùng dòng; không tự tạo quốc gia/khu vực mới.']],
             'menu_them': ' => Import Excel {icon:btn_import}',
             'ghi_chu_layout': 'Cửa sổ Import được mở ngay trên màn hình danh sách.',
             'anh': [('import_open', 'Cửa sổ Import tỉnh/TP khi vừa mở'), ('import_loaded', 'Dữ liệu đã được load lên bảng xem trước'),
                     ('import_validated', 'Kết quả Validate — mỗi dòng lỗi nêu rõ lý do')],
             'bang_them': [('Quy tắc kiểm tra riêng của file Import', [['Cột', 'Quy tắc / thông báo lỗi'],
                            ['Tên tỉnh/TP *', 'Bắt buộc (“Tên tỉnh/TP không được để trống”), tối đa 255 ký tự (“Tên tỉnh/TP tối đa 255 ký tự”), không trùng trong file (“Tỉnh/TP bị trùng với dòng N trong file”), không trùng hệ thống trong cùng quốc gia + khu vực (“Tỉnh/TP này đã tồn tại trong khu vực đã chọn”).'],
                            ['Mã số tỉnh', 'Không bắt buộc; có thì chỉ chữ số (“Mã số tỉnh phải là số”), tối đa 10 chữ số (“Mã số tỉnh tối đa 10 chữ số”).'],
                            ['Biển số xe *', 'Bắt buộc (“Biển số xe không được để trống”), chỉ chữ số (“Biển số xe chỉ gồm chữ số”), tối đa 50 chữ số (“Biển số xe tối đa 50 chữ số”).'],
                            ['Tên quốc gia *', 'Bắt buộc (“Tên quốc gia không được để trống”), chọn trong danh sách sổ xuống; ghi sai báo “Không tìm thấy quốc gia: X”.'],
                            ['Tên khu vực *', 'Bắt buộc (“Tên khu vực không được để trống”), phải thuộc quốc gia cùng dòng; sai báo “Không tìm thấy khu vực "Y" thuộc quốc gia X”.']], [1.2, 4])]},
            {'ten': 'Xuất danh sách ra Excel', 'uc': 'uc_fr09',
             'qtc': 'Quy tắc Excel và Cấu hình cột. Chỉ bổ sung danh sách trường được phép xuất riêng của Danh mục Tỉnh/TP.',
             'gioi_thieu': [['Tên chức năng', 'Xuất danh sách tỉnh/TP ra Excel'],
                            ['Mô tả', 'Xuất kết quả đang lọc ra file Excel, cho phép chọn trường và thứ tự cột.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Dòng sự kiện chính', '1. Bấm Xuất Excel.\n2. Hệ thống mở cửa sổ “Chọn trường xuất file”, tích sẵn đúng các cột đang hiển thị trên bảng.\n3. Người dùng tích chọn và kéo ☰ để sắp thứ tự.\n4. Bấm Xuất file; hệ thống tải danh_muc_tinh_thanh_pho.xlsx theo đúng bộ lọc và thứ tự trường, báo “Xuất Excel thành công”.'],
                            ['Dòng sự kiện phụ', '• Bỏ chọn hết trường → nút Xuất file không bấm được.\n• Bấm Đóng → không xuất gì.'],
                            ['Yêu cầu đặc biệt', 'File chứa toàn bộ kết quả lọc (tối đa 10,000 dòng), không giới hạn ở trang đang xem. Chỉ xuất Excel.']],
             'menu_them': ' => Xuất Excel {icon:btn_xuatexcel}',
             'anh': [('export', 'Cửa sổ Chọn trường xuất file')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
                    ['1', 'Danh sách trường', 'Checkbox chọn nhiều', 'Enable', 'Tích sẵn cột đang hiển thị', 'Tên tỉnh/TP, Mã số tỉnh, Biển số xe, Quốc gia, Khu vực, Trạng thái, Người tạo, Ngày tạo, Người cập nhật, Ngày cập nhật. Kéo ☰ đổi thứ tự.'],
                    ['2', 'Nút Chọn tất cả / Bỏ chọn hết', 'Button', 'Enable', 'Hiển thị', 'Tích / bỏ tích toàn bộ.'],
                    ['3', 'Nút Xuất file', 'Button', 'Enable/Disable', 'Mờ khi chưa chọn trường', 'Sinh file và tải về.'],
                    ['4', 'Nút Đóng', 'Button', 'Enable', 'Hiển thị', 'Đóng cửa sổ.']],
             'ui_widths': [0.6, 1.5, 1, 0.8, 1.2, 2.6]},
            {'ten': 'Xem chi tiết tỉnh/TP', 'uc': 'uc_fr10',
             'qtc': 'Màn Xem chi tiết và Phân quyền.',
             'gioi_thieu': [['Tên chức năng', 'Xem chi tiết tỉnh/TP'],
                            ['Mô tả', 'Cửa sổ “Xem Tỉnh/TP” hiển thị Tên tỉnh/TP, Mã số tỉnh, Biển số xe, Quốc gia, Khu vực, Trạng thái ở chế độ chỉ đọc, kèm khối Lịch sử.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm tên tỉnh/TP ở danh sách.\n2. Hệ thống mở cửa sổ Xem, chỉ có nút Đóng.']],
             'anh': [('detail', 'Cửa sổ Xem Tỉnh/TP ở chế độ chỉ đọc')]},
            {'ten': 'Tùy chỉnh cột hiển thị',
             'qtc': 'Tùy chỉnh cột.',
             'gioi_thieu': [['Tên chức năng', 'Tùy chỉnh cột hiển thị'],
                            ['Mô tả', 'Bật/tắt và sắp xếp thứ tự cột của bảng; cấu hình lưu riêng theo người dùng.'],
                            ['Yêu cầu đặc biệt', 'Cột STT, Tên Tỉnh/TP, Hành động bị khóa. Mặc định ẩn: Biển số xe, Quốc gia, Khu vực, Người cập nhật, Ngày cập nhật.']],
             'menu_them': ' => Cấu hình cột {icon:btn_cauhinhcot}',
             'anh': [('colcfg', 'Cửa sổ Tuỳ chỉnh cột')]},
        ],
        'quy_tac': [
            ('BR-01', 'Ràng buộc trùng tên',
             [
              'Tên tỉnh/TP không được trùng trong cùng một cặp Quốc gia + Khu vực; cùng tên ở khu vực khác vẫn hợp lệ.',
              'Thông báo khi trùng: “Tên khu vực này đã tồn tại”.',
              'Import Excel: báo “Tỉnh/TP này đã tồn tại trong khu vực đã chọn” hoặc “Tỉnh/TP bị trùng với dòng N trong file”.',
             ],
             ['Thêm mới tỉnh/TP', 'Chỉnh sửa tỉnh/TP', 'Import file tỉnh/TP']),
            ('BR-02', 'Mã số tỉnh và Biển số xe',
             [
              'Mã số tỉnh không bắt buộc, chỉ gồm chữ số, tối đa 10 chữ số, không yêu cầu duy nhất.',
              'Biển số xe bắt buộc, chỉ gồm chữ số, tối đa 50 chữ số.',
              'Biển số xe là phần đầu của Mã khách hàng tự sinh (tỉnh/TP chưa khai biển số thì mã khách hàng dùng 2 ký tự đầu tên tỉnh).',
             ],
             ['Thêm mới tỉnh/TP', 'Chỉnh sửa tỉnh/TP', 'Import file tỉnh/TP', 'Tạo mới khách hàng']),
            ('BR-03', 'Mối quan hệ với các cấp địa chỉ khác',
             [
              'Mỗi tỉnh/TP thuộc đúng một quốc gia và một khu vực của quốc gia đó; ô Khu vực chỉ hiện sau khi chọn Quốc gia và đổi Quốc gia thì Khu vực bị xóa trắng.',
              'Ô chọn chỉ liệt kê quốc gia / khu vực đang Hoạt động; tỉnh/TP đang dùng quốc gia / khu vực đã khóa vẫn giữ và hiển thị đúng tên kèm 🔒.',
              'Mọi Phường/Xã, Quận/Huyện đều phải trỏ về một tỉnh/TP; khóa tỉnh/TP không tự khóa các cấp bên dưới.',
             ],
             ['Thêm mới tỉnh/TP', 'Chỉnh sửa tỉnh/TP', 'Tạo mới các cấp địa chỉ khác. VD: Phường/Xã, Quận/Huyện']),
            ('BR-04', 'Điều kiện xóa',
             [
              'Chỉ xóa được tỉnh/TP đang Hoạt động, chưa có Phường/Xã trực thuộc và chưa được nhân sự dùng làm địa chỉ thường trú / tạm trú; ngược lại nút Xóa bị ẩn.',
              'Không xóa được thì dùng Khóa.',
              'Xóa là xóa hẳn bản ghi khỏi hệ thống.',
             ],
             ['Xóa tỉnh/TP']),
            ('BR-05', 'Tỉnh/TP đang Khóa',
             [
              'Không sửa, không xóa được; phải Mở khóa trước.',
              'Máy chủ chặn lưu khi sửa bản ghi đang Khóa: “Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.”',
              'Tỉnh/TP Khóa không còn chọn được ở các màn khác; bản ghi đang dùng vẫn hiển thị đúng tên kèm 🔒.',
             ],
             ['Chỉnh sửa tỉnh/TP', 'Xóa tỉnh/TP', 'Khóa / Mở khóa tỉnh/TP']),
            ('BR-06', 'Thao tác đồng thời',
             [
              'Hai người cùng Khóa / Mở khóa / Xóa một bản ghi: người bấm sau nhận thông báo “Trạng thái đã bị thay đổi. Vui lòng load lại trang”, thao tác không được thực hiện lại.',
             ],
             ['Xóa tỉnh/TP', 'Khóa / Mở khóa tỉnh/TP']),
            ('BR-07', 'Giới hạn Import',
             [
              'Mỗi lần nhập tối đa 500 dòng; phải Validate trước, bước Validate không ghi dữ liệu.',
              'Quốc gia tra theo tên, khu vực tra theo tên trong quốc gia đó; không tự tạo mới. Không tìm thấy thì báo “Không tìm thấy khu vực … thuộc quốc gia …”.',
              'Tỉnh/TP nhập từ Excel luôn ở trạng thái Hoạt động.',
             ],
             ['Import file tỉnh/TP']),
            ('BR-08', 'Ghi lịch sử thay đổi',
             [
              'Mọi thao tác Tạo mới, Thay đổi thông tin, Khóa, Mở khóa đều ghi lịch sử kèm người thực hiện.',
             ],
             ['Xem lịch sử thay đổi']),
        ],
    },
}

# ---- Lỗi code phát hiện khi rà (KHÔNG sửa code, báo user) ----
CFG['loi_code'] = [
    'Thông báo trùng tên khi Thêm/Sửa tỉnh/TP ghi “Tên khu vực này đã tồn tại” (CreateProvinceRequest::messages name.unique) — chữ “khu vực” lấy nhầm từ màn Khu vực. Tài liệu đang ghi nguyên văn câu hiện tại; sửa code thì cập nhật lại HDSD/SRS/testcase.',
    'Import: số dòng trong câu “Tỉnh/TP bị trùng với dòng N trong file” không khớp chỗ nào người dùng nhìn thấy (ProvinceService::validateRows dòng 330 dùng $index + 2): cột # của bảng xem trước đánh $index + 1 (V2BaseImportModal.vue dòng 324), còn trong file Excel dòng dữ liệu đầu là hàng 3 (hàng 1 tiêu đề, hàng 2 mô tả).',
    'Import tra quốc gia theo TÊN bằng mapWithKeys(mb_strtolower(name) => id): DB đang có 4 quốc gia cùng tên “Việt Nam” (id 1 Hoạt động, id 2–4 Khóa) nên tên “Việt Nam” khớp vào id cuối cùng (quốc gia đã khóa) — tỉnh/TP nhập từ file có thể gắn nhầm quốc gia đã khóa. Đồng thời các khu vực Miền Bắc/Trung/Nam đang thuộc quốc gia id 4 (đã khóa), nên ở cửa sổ Tạo Tỉnh/TP chọn Việt Nam (id 1) thì ô Khu vực rỗng. Cần kiểm tra dữ liệu/cách tra trùng tên.',
    'Cột license_plate trong DB là kiểu số (int) nên biển số có số 0 ở đầu (vd “09”) bị lưu thành “9”.',
    'Xóa không được chặn ở máy chủ: ProvinceService::deleteProvince (dòng 148-160) không kiểm tra canDelete() lẫn trạng thái Khóa — gọi thẳng API vẫn xóa được tỉnh/TP đã khóa hoặc đang có Phường/Xã, nhân sự dùng. Nút Xóa chỉ bị ẩn ở FE (index.vue dòng 564).',
    'Province::canDelete (Entities/Province.php dòng 58-69) không kiểm tra Quận/Huyện (districts.province_id) — tỉnh/TP chỉ có Quận/Huyện mà chưa có Phường/Xã vẫn hiện nút Xóa, xóa xong Quận/Huyện bị mồ côi. Đồng thời hàm chạy 2 truy vấn cho MỖI dòng danh sách (N+1).',
    'Chặn sửa bản ghi đã Khóa (ProvinceController::store dòng 52-58) đặt SAU CreateProvinceRequest nên payload thiếu/sai trường bị trả 422 trước, không tới được câu 423 “Bản ghi đang bị khoá…” (CLAUDE.md yêu cầu guard ở middleware route).',
    'Import: Mã số tỉnh = “0” bị lưu thành rỗng (ProvinceService::import dòng 404 dùng `?: null`, chuỗi “0” là falsy).',
    'CreateProvinceRequest::messages còn khai code.unique / license_plate.unique nhưng rules() không có unique — câu “Mã tỉnh này đã tồn tại” không bao giờ hiện (code chết, không ảnh hưởng người dùng).',
]

# ---- Sửa tab testcase "16. DM tỉnhTP" (đọc từ ref/testcase_tab.txt) ----
CFG['tc'] = {
    'tab': '16. DM tỉnhTP',
    'hdr_row': 82,            # "VII. LỊCH SỬ THAY ĐỔI"
    'blocks': [
        # Quy tắc ô Mã số tỉnh — chèn cuối nhóm III. THÊM MỚI (R40..R54; R54 đang trùng ID TC_03.014)
        {'after': 54, 'merge_from': 40, 'cases': [
            ('TC_03.015', 'Mã số tỉnh quá 10 chữ số', 'P1', 'Đang ở cửa sổ thêm mới.',
             '1. Nhập 11 chữ số vào ô Mã số tỉnh\n2. Quan sát ô\n3. Xóa bớt còn 10 chữ số, nhập đủ các ô bắt buộc rồi bấm Lưu',
             'Mã số tỉnh: 12345678901 / 1234567890',
             '- Bước 2: báo lỗi đỏ ngay dưới ô “Chỉ được nhập chữ số, từ 0 đến 10 chữ số”\n- Bước 3: hợp lệ, lưu thành công'),
            ('TC_03.016', 'Mã số tỉnh có ký tự đặc biệt', 'P1', 'Đang ở cửa sổ thêm mới.',
             '1. Nhập mã có ký tự đặc biệt vào ô Mã số tỉnh\n2. Bấm Lưu',
             'Mã số tỉnh: 12-3',
             '- Báo lỗi đỏ ngay dưới ô “Phải là số”\n- Cửa sổ KHÔNG đóng, không tạo bản ghi'),
            ('TC_03.017', 'Mã số tỉnh không yêu cầu duy nhất', 'P2', 'Đã có tỉnh/TP A với Mã số tỉnh 31.',
             '1. Thêm mới tỉnh/TP B (tên khác A) với cùng Mã số tỉnh 31\n2. Bấm Lưu',
             'Mã số tỉnh: 31',
             '- Lưu thành công, không báo trùng mã'),
        ]},
        {'after': 94,             # TC_07.012 — case cuối của nhóm VII
         'groups': [('VIII', 'XUẤT EXCEL (bổ sung 25/09/2026)', 8, 'export'),
                    ('IX', 'IMPORT TỪ FILE EXCEL (bổ sung 25/09/2026)', 9, 'import')]},
    ],
    'import_rows_dung': 'File mẫu điền 2 tỉnh/TP hợp lệ (DOC-Tỉnh Mẫu Một, DOC-Tỉnh Mẫu Hai — quốc gia Việt Nam, khu vực Miền Bắc/Miền Nam, biển số chỉ chữ số), chưa có trong danh mục',
    'import_loi_data': {
        'Tên tỉnh/TP không được để trống': 'Tên tỉnh/TP: (để trống); Biển số xe: 903; Tên quốc gia: Việt Nam; Tên khu vực: Miền Bắc',
        'Tên tỉnh/TP tối đa 255 ký tự': 'Tên tỉnh/TP: chuỗi 256 ký tự',
        'Mã số tỉnh phải là số': 'Mã số tỉnh: AB12',
        'Mã số tỉnh tối đa 10 chữ số': 'Mã số tỉnh: 12345678901',
        'Biển số xe không được để trống': 'Biển số xe: (để trống)',
        'Biển số xe chỉ gồm chữ số': 'Biển số xe: 29A',
        'Biển số xe tối đa 50 chữ số': 'Biển số xe: 51 chữ số',
        'Tên quốc gia không được để trống': 'Tên quốc gia: (để trống)',
        'Không tìm thấy quốc gia: X': 'Tên quốc gia: Nước không tồn tại',
        'Tên khu vực không được để trống': 'Tên khu vực: (để trống)',
        'Không tìm thấy khu vực "Y" thuộc quốc gia X': 'Tên quốc gia: Việt Nam; Tên khu vực: Khu vực không tồn tại',
        'Tỉnh/TP bị trùng với dòng N trong file': 'Hai dòng cùng tên “DOC-Tỉnh Mẫu Một”, cùng Việt Nam – Miền Bắc',
        'Tỉnh/TP này đã tồn tại trong khu vực đã chọn': 'Tên tỉnh/TP: (tên đã có trong danh mục, cùng quốc gia + khu vực)',
    },
    'edits': [
        ('B8', 'Màn hình này KHÔNG khai báo quyền nào. Mọi người dùng đã đăng nhập đều mở được màn hình và thực hiện được đầy đủ Thêm mới, Chỉnh sửa, Xóa, Khóa, Mở khóa, Import Excel và Xuất Excel.\n Phía máy chủ cũng không kiểm tra quyền, nên gọi thẳng chức năng mà bỏ qua giao diện vẫn ghi được dữ liệu. Đây là hiện trạng của mã nguồn, đã được ghi nhận để bộ phận quản trị cân nhắc bổ sung quyền.'),
    ],
    'clear_k': [],
}

CFG['tc_ngoai_pham_vi'] = [
    'R20 (TC_01.002): liệt kê cột “Người sửa” — tên thật là “Người cập nhật”; đồng thời Biển số xe, Quốc gia, Khu vực, Người cập nhật, Ngày cập nhật mặc định ẨN nên expected “có đủ các cột” không khớp khi chưa chỉnh cấu hình cột.',
    'R54: trùng TC ID TC_03.014 với R53.',
    'R62–R64: tên hộp thoại ghi “Thông tin chưa được lưu”, chữ thật là “Thông tin chưa lưu”.',
    'R70 (TC_05.004) “Xóa bản ghi đang được dùng → hệ thống từ chối nêu lý do”: thực tế nút Xóa bị ẨN khi tỉnh/TP đã có Phường/Xã hoặc có nhân sự dùng làm địa chỉ, không có bước từ chối.',
    'R73 (TC_06.001) “Menu ba chấm có Khóa và Lịch sử, Sửa và Xóa hiện thẳng”: chỉ đúng với dòng có đủ 4 nút; dòng không có nút Xóa (đa số tỉnh/TP đã có phường/xã) thì 3 nút Sửa, Khóa, Lịch sử hiện thẳng, không có nút ba chấm.',
    'R10 ghi chú: câu “Thông báo trùng tên ghi Tên khu vực này đã tồn tại” vẫn đúng hiện trạng (đã đưa vào loi_code).',
]


# ---- Bổ sung 28/09/2026: “Mô tả chi tiết giao diện” + “Danh sách event và xử lý event” cho SRS ----
# Tester báo thiếu 2 mục này ở các chức năng sau Thêm mới. Nguồn: code gop_db 28/09/2026 (FE pages/human/provinces, component
# dùng chung V2BaseImportModal / export-fields-modal / column-customization-modal / CatalogHistoryModal; BE Modules/Human).
_FR = {f['ten']: f for f in CFG['srs']['fr']}
_FR['Chỉnh sửa tỉnh/TP'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Phạm vi', 'Bắt buộc', 'Giá trị ban đầu', 'Mô tả'],
        ['1', 'Tên tỉnh/TP', 'Textbox', 'Enable', '1–255 ký tự', 'Có', 'Dữ liệu hiện tại', 'Không trùng trong cùng cặp Quốc gia + Khu vực, bỏ qua chính bản ghi đang sửa. Bỏ trống “Bắt buộc phải nhập”; trùng “Tên khu vực này đã tồn tại”; quá dài “Vui lòng nhập tối đa 255 ký tự.”'],
        ['2', 'Mã số tỉnh', 'Textbox', 'Enable', '0–10 chữ số', 'Không', 'Dữ liệu hiện tại', 'Chỉ chữ số, không yêu cầu duy nhất. Có chữ/ký tự đặc biệt “Phải là số”; quá 10 chữ số “Chỉ được nhập chữ số, từ 0 đến 10 chữ số”.'],
        ['3', 'Biển số xe', 'Textbox', 'Enable', '1–50 chữ số', 'Có', 'Dữ liệu hiện tại', 'Chỉ chữ số. Sai “Chỉ được nhập chữ số, từ 0 đến 50 chữ số”; bỏ trống “Bắt buộc phải nhập”.'],
        ['4', 'Quốc gia', 'Dropdown', 'Enable', 'Quốc gia đang Hoạt động', 'Có', 'Dữ liệu hiện tại', 'Quốc gia đã khóa mà bản ghi đang dùng vẫn hiện đúng tên kèm 🔒. Đổi Quốc gia thì xóa trắng Khu vực. Bỏ trống “Bắt buộc phải nhập”.'],
        ['5', 'Khu vực', 'Dropdown', 'Enable', 'Khu vực Hoạt động thuộc quốc gia đã chọn', 'Có', 'Dữ liệu hiện tại', 'Chỉ liệt kê khu vực thuộc quốc gia đã chọn; khu vực đã khóa đang dùng vẫn hiện kèm 🔒. Bỏ trống “Bắt buộc phải nhập”.'],
        ['6', 'Trạng thái', 'Dropdown', 'Enable', 'Hoạt động / Khóa', 'Có', 'Dữ liệu hiện tại', 'Chọn Khóa rồi Lưu cũng là khóa tỉnh/TP; lịch sử ghi dòng “Thay đổi trạng thái” riêng.'],
        ['7', 'Nút Lưu', 'Button', 'Enable', '–', '–', 'Hiển thị', 'Ghi thay đổi rồi đóng cửa sổ.'],
        ['8', 'Nút Đóng / biểu tượng X', 'Button', 'Enable', '–', '–', 'Hiển thị', 'Đóng cửa sổ, không ghi gì. Đã sửa dở thì hỏi “Thông tin chưa lưu” — “Bạn có thông tin chưa lưu. Có chắc chắn muốn thoát?” (Thoát / Ở lại). Chế độ Sửa không có nút “Lưu và tiếp tục”.'],
        ['9', 'Thông báo lỗi', 'Label', 'Hiển thị khi lỗi', '–', '–', 'Ẩn', 'Chữ đỏ ngay dưới ô bị lỗi, kèm thông báo chung “Vui lòng kiểm tra lại dữ liệu nhập”.'],
    ],
    'ui_widths': [0.5, 1.2, 0.8, 0.6, 1.1, 0.6, 0.8, 1.9],
    'events': [
        ['Bấm biểu tượng bút chì (Sửa)', 'Click', 'Before:\n– Nút chỉ hiển thị khi bản ghi đang Hoạt động; bản ghi Khóa không có nút Sửa.\nAfter:\n– Mở cửa sổ “Sửa Tỉnh/TP” với dữ liệu hiện tại đã điền sẵn.'],
        ['Đổi Quốc gia', 'Change', 'After:\n– Xóa trắng ô Khu vực, nạp danh sách khu vực đang Hoạt động của quốc gia mới.'],
        ['Bấm Lưu', 'Click', 'During:\n– Tên tỉnh/TP, Biển số xe, Quốc gia, Khu vực để trống → “Bắt buộc phải nhập”.\n– Mã số tỉnh sai định dạng → “Phải là số” / “Chỉ được nhập chữ số, từ 0 đến 10 chữ số”; Biển số xe sai → “Chỉ được nhập chữ số, từ 0 đến 50 chữ số”.\n– Trùng tên với tỉnh/TP khác trong cùng Quốc gia + Khu vực → “Tên khu vực này đã tồn tại”.\n– Bỏ qua kiểm tra trùng đối với chính bản ghi đang sửa.\n– Bản ghi đang Khóa (vừa bị người khác khóa) → từ chối, báo “Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.”\n– Có lỗi → báo đỏ dưới ô, cửa sổ KHÔNG đóng, không thực hiện bước After.\nAfter:\n– Ghi thay đổi, ghi Người cập nhật và một dòng lịch sử “Thay đổi thông tin” nêu giá trị cũ → mới (đổi Trạng thái ghi dòng “Thay đổi trạng thái” riêng).\n– Đóng cửa sổ, nạp lại danh sách, báo “Cập nhật thành công”.'],
        ['Bấm Đóng / biểu tượng X / bấm ra ngoài cửa sổ', 'Click', 'After:\n– Chưa sửa gì → đóng cửa sổ.\n– Đã sửa → hỏi “Thông tin chưa lưu” — “Bạn có thông tin chưa lưu. Có chắc chắn muốn thoát?” (Thoát / Ở lại); chọn Thoát thì đóng, không ghi; chọn Ở lại thì giữ nguyên dữ liệu đang nhập.'],
    ],
})
_FR['Xóa tỉnh/TP'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Mô tả'],
        ['1', 'Biểu tượng thùng rác (Xóa)', 'Icon Button', 'Nằm ở cột Hành động của từng dòng. Chỉ hiển thị khi tỉnh/TP đang Hoạt động, chưa có Phường/Xã trực thuộc và chưa có nhân sự nào dùng làm địa chỉ; ngược lại nút bị ẩn hẳn.'],
        ['2', 'Tiêu đề hộp xác nhận', 'Label', '“Xóa Tỉnh/TP”.'],
        ['3', 'Nội dung hộp xác nhận', 'Label', '“Bạn có chắc muốn xóa tỉnh/TP "<tên>"?” — nêu rõ tên bản ghi để tránh xóa nhầm dòng.'],
        ['4', 'Nút Xóa', 'Button', 'Xác nhận xóa hẳn bản ghi khỏi hệ thống.'],
        ['5', 'Nút Hủy', 'Button', 'Đóng hộp, không thay đổi gì.'],
    ],
    'ui_widths': [0.6, 1.8, 1.0, 3.6],
    'events': [
        ['Bấm biểu tượng thùng rác', 'Click', 'Before:\n– Nút chỉ hiển thị khi tỉnh/TP đang Hoạt động, chưa có Phường/Xã trực thuộc và chưa có nhân sự nào dùng làm địa chỉ.\nAfter:\n– Hiện hộp xác nhận “Xóa Tỉnh/TP” kèm tên bản ghi.'],
        ['Bấm Xóa trong hộp xác nhận', 'Click', 'During:\n– Bản ghi không còn tồn tại (người khác vừa xóa) → báo “Trạng thái đã bị thay đổi. Vui lòng load lại trang”, dừng xử lý.\nAfter:\n– Xóa hẳn bản ghi (không khôi phục được), đóng hộp, nạp lại danh sách, báo “Xoá tỉnh/thành phố thành công”.\n– Lỗi khác → báo câu lỗi của hệ thống hoặc “Xoá tỉnh/thành phố thất bại”.'],
        ['Bấm Hủy', 'Click', 'After:\n– Đóng hộp xác nhận, không thay đổi gì.'],
    ],
})
_FR['Khóa / Mở khóa tỉnh/TP'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Mô tả'],
        ['1', 'Nút Khóa / Mở khóa', 'Button', 'Nằm ở cột Hành động (trong nút ba chấm nếu dòng có từ 4 nút trở lên). Nhãn đổi theo trạng thái. Luôn hiển thị: dòng Hoạt động có Khóa, dòng Khóa có Mở khóa.'],
        ['2', 'Nút ba chấm “Hành động khác”', 'Icon Button', 'Hiện khi dòng có từ 4 nút trở lên: 2 nút đầu hiện thẳng, các nút còn lại (Khóa, Lịch sử) nằm trong menu này.'],
        ['3', 'Tiêu đề hộp xác nhận', 'Label', '“Khóa Tỉnh/TP” hoặc “Mở khóa Tỉnh/TP” tùy trạng thái hiện tại.'],
        ['4', 'Nội dung hộp xác nhận', 'Label', '“Bạn có chắc muốn khóa tỉnh/TP "<tên>"?” / “Bạn có chắc muốn mở khóa tỉnh/TP "<tên>"?”.'],
        ['5', 'Nút Khóa / Mở khóa trong hộp', 'Button', 'Xác nhận thực hiện.'],
        ['6', 'Nút Hủy', 'Button', 'Đóng hộp, không làm gì.'],
        ['7', 'Cột Trạng thái', 'Badge', 'Hoạt động hoặc Khóa, hai màu khác nhau; cập nhật ngay sau thao tác.'],
    ],
    'ui_widths': [0.6, 1.8, 1.0, 3.6],
    'events': [
        ['Bấm nút ba chấm', 'Click', 'After:\n– Mở menu chứa các nút còn lại của dòng (Khóa / Mở khóa, Lịch sử).'],
        ['Chọn Khóa hoặc Mở khóa', 'Click', 'After:\n– Hiện hộp xác nhận kèm tên bản ghi.'],
        ['Bấm Khóa / Mở khóa trong hộp', 'Click', 'During:\n– Bản ghi không còn tồn tại hoặc đã ở trạng thái đích (người khác vừa thao tác) → báo “Trạng thái đã bị thay đổi. Vui lòng load lại trang”, dừng xử lý, không ghi thêm lịch sử.\nAfter:\n– Đổi trạng thái, KHÔNG xóa dữ liệu; ghi Người cập nhật và một dòng lịch sử “Khóa” / “Mở khóa”.\n– Đóng hộp, báo “Khóa thành công” / “Mở khóa thành công”, nạp lại danh sách: sau Khóa ẩn nút Sửa, Xóa; sau Mở khóa hiện lại nút Sửa (Xóa hiện lại nếu đủ điều kiện xóa).\n– Lỗi khác → báo câu lỗi của hệ thống hoặc “Thao tác thất bại”.'],
        ['Bấm Hủy', 'Click', 'After:\n– Đóng hộp xác nhận, trạng thái không đổi.'],
    ],
})
_FR['Xem lịch sử thay đổi'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Giá trị ban đầu', 'Mô tả'],
        ['1', 'Nút Lịch sử', 'Button', 'Hiển thị', 'Nằm ở cột Hành động (trong nút ba chấm nếu dòng có từ 4 nút). Luôn có ở mọi dòng, kể cả bản ghi Khóa.'],
        ['2', 'Tiêu đề cửa sổ', 'Label', 'Lịch sử thay đổi: <tên tỉnh/TP>', 'Ghép tên bản ghi để biết đang xem dòng nào.'],
        ['3', 'Nút Bộ lọc', 'Button', 'Vùng lọc đang ẩn', 'Bấm để hiện / ẩn vùng lọc; vùng lọc ghim ở đầu khi cuộn danh sách.'],
        ['4', 'Loại hành động', 'Dropdown', 'Trống (“Tất cả loại hành động”)', 'Lọc theo Tạo mới, Thay đổi thông tin, Thay đổi trạng thái, Khóa, Mở khóa… Chọn là lọc ngay.'],
        ['5', 'Người thực hiện', 'Dropdown', 'Trống (“Tất cả người thực hiện”)', 'Chọn là lọc ngay.'],
        ['6', 'Từ ngày / Đến ngày', 'Date picker', 'Trống', 'Định dạng dd/mm/yyyy. Chọn là lọc ngay.'],
        ['7', 'Nút Làm mới (vùng lọc)', 'Button', 'Hiển thị', 'Xóa hết tiêu chí lọc, hiện lại toàn bộ lịch sử.'],
        ['8', 'Danh sách thay đổi', 'Timeline', 'Mới nhất ở trên cùng', 'Mỗi mốc gồm: thời điểm (dd/mm/yyyy hh:mm); loại hành động (Tạo mới, Thay đổi thông tin, Thay đổi trạng thái, Khóa, Mở khóa); “Người thực hiện: …”; từng trường đã đổi dạng “Tên trường: giá trị cũ → giá trị mới”. Trường Quốc gia, Khu vực hiển thị bằng tên.'],
        ['9', 'Trạng thái rỗng', 'Label', 'Ẩn', '“Chưa có lịch sử thao tác nào.” khi bản ghi chưa có lịch sử; “Không có lịch sử phù hợp bộ lọc.” khi lọc không ra kết quả.'],
        ['10', 'Nút Đóng / biểu tượng X', 'Button', 'Hiển thị', 'Đóng cửa sổ.'],
    ],
    'ui_widths': [0.6, 1.5, 0.9, 1.2, 2.8],
    'events': [
        ['Chọn Lịch sử ở cột Hành động', 'Click', 'After:\n– Mở cửa sổ “Lịch sử thay đổi: <tên>”, nạp danh sách thay đổi theo thứ tự mới nhất trước.\n– Không tải được → hiện “Không tải được lịch sử phiếu.” kèm nút Thử lại.'],
        ['Bấm Bộ lọc', 'Click', 'After:\n– Hiện / ẩn vùng lọc.'],
        ['Đổi Loại hành động / Người thực hiện / Từ ngày / Đến ngày', 'Change', 'After:\n– Lọc ngay danh sách theo mọi tiêu chí đã chọn (không có nút Tìm kiếm).'],
        ['Bấm Làm mới trong vùng lọc', 'Click', 'After:\n– Xóa trắng tiêu chí, hiện lại toàn bộ lịch sử.'],
        ['Bấm Đóng / biểu tượng X', 'Click', 'After:\n– Đóng cửa sổ; danh sách phía sau giữ nguyên bộ lọc và trang đang xem.'],
    ],
})
_FR['Import file tỉnh/TP'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Bắt buộc', 'Giá trị ban đầu', 'Mô tả'],
        ['1', 'Nút Import Excel', 'Button', 'Enable', '–', 'Hiển thị', 'Nằm trên thanh công cụ của bảng danh sách. Mở cửa sổ “Import tỉnh/TP” (dòng phụ “Import từ Excel • Validate xong dòng hợp lệ sẽ bị khoá”).'],
        ['2', 'Nút Chọn file Excel', 'Button', 'Enable', 'Có', 'Chưa chọn file', 'Chọn file .xlsx hoặc .xls từ máy; tên file hiện ngay cạnh nút.'],
        ['3', 'Nút Tải file mẫu', 'Button', 'Enable', '–', 'Hiển thị', 'Tải file Mau_import_tinh_thanh_pho.xlsx gồm cột STT, Tên tỉnh/TP *, Mã số tỉnh, Biển số xe *, Tên quốc gia *, Tên khu vực * (hai cột cuối có ô chọn sẵn danh sách). Hàng 1 là tiêu đề, hàng 2 là dòng mô tả, dữ liệu nhập từ hàng 3.'],
        ['4', 'Nút Load lên bảng', 'Button', 'Enable / Disable', '–', 'Mờ khi chưa chọn file', 'Đọc file và đổ dữ liệu lên bảng xem trước.'],
        ['5', 'Nút Validate', 'Button', 'Enable / Disable', '–', 'Mờ khi bảng chưa có dòng nào', 'Gửi dữ liệu lên máy chủ kiểm tra từng dòng; dòng hợp lệ bị khóa lại, không sửa được nữa.'],
        ['6', 'Nút Import', 'Button', 'Enable / Disable', '–', 'Mờ', 'Chỉ bấm được khi đã Validate, không còn dòng lỗi và có ít nhất 1 dòng hợp lệ. Ghi các dòng hợp lệ vào danh mục.'],
        ['7', 'Ô Tổng / Hợp lệ / Lỗi', 'Label', 'Read-only', '–', 'Tổng: 0', 'Sau Load hiện “Tổng”; sau Validate hiện thêm “Hợp lệ”, “Lỗi”. Có dòng vừa sửa hiện “Có dòng đã sửa (cần validate lại)”.'],
        ['8', 'Bảng xem trước', 'Table/Grid', 'Enable', '–', 'Trống', 'Cột #, Tên tỉnh/TP *, Mã số tỉnh, Biển số xe *, Tên quốc gia *, Tên khu vực *. Dòng lỗi sửa trực tiếp được (Tên tỉnh/TP, Mã số tỉnh, Biển số xe gõ lại; Tên quốc gia, Tên khu vực chọn trong danh sách).'],
        ['9', 'Thông báo lỗi theo dòng', 'Label', 'Hiển thị', '–', 'Ẩn', 'Dòng lỗi viền đỏ, lý do ghi ngay dưới dòng: “Tên tỉnh/TP không được để trống”; “Tên tỉnh/TP tối đa 255 ký tự”; “Mã số tỉnh phải là số”; “Mã số tỉnh tối đa 10 chữ số”; “Biển số xe không được để trống”; “Biển số xe chỉ gồm chữ số”; “Biển số xe tối đa 50 chữ số”; “Tên quốc gia không được để trống”; “Không tìm thấy quốc gia: X”; “Tên khu vực không được để trống”; “Không tìm thấy khu vực "Y" thuộc quốc gia X”; “Tỉnh/TP bị trùng với dòng N trong file”; “Tỉnh/TP này đã tồn tại trong khu vực đã chọn”.'],
        ['10', 'Nút Bỏ dòng lỗi', 'Button', 'Enable / Disable', '–', 'Mờ khi bảng trống', 'Loại mọi dòng lỗi khỏi bảng, báo “Đã bỏ N dòng lỗi. Còn lại M dòng hợp lệ.”; chưa Validate thì báo “Hãy Validate trước rồi mới bỏ dòng lỗi.”'],
        ['11', 'Nút Xoá trạng thái validate', 'Button', 'Enable / Disable', '–', 'Mờ khi bảng trống', 'Bỏ khóa các dòng hợp lệ và xóa kết quả kiểm tra để sửa lại.'],
        ['12', 'Nút Làm mới', 'Button', 'Enable', '–', 'Hiển thị', 'Bỏ file đã chọn và toàn bộ bảng, đưa cửa sổ về trạng thái ban đầu.'],
        ['13', 'Nút Đóng / biểu tượng X', 'Button', 'Enable', '–', 'Hiển thị', 'Đóng cửa sổ, không ghi gì.'],
    ],
    'ui_widths': [0.5, 1.3, 0.9, 0.8, 0.5, 1.1, 2.4],
    'events': [
        ['Bấm Import Excel', 'Click', 'After:\n– Mở cửa sổ “Import tỉnh/TP” ở trạng thái rỗng.'],
        ['Bấm Tải file mẫu', 'Click', 'After:\n– Tải file Mau_import_tinh_thanh_pho.xlsx về máy.\n– Lỗi → báo “Lỗi khi tạo file mẫu”.'],
        ['Chọn file', 'Change', 'During:\n– File không phải .xlsx / .xls → báo “Vui lòng chọn file .xlsx hoặc .xls”, bỏ file.\nAfter:\n– Hiện tên file, nút Load lên bảng sáng lên.'],
        ['Bấm Load lên bảng', 'Click', 'During:\n– File không có dòng dữ liệu → “Không có dòng dữ liệu hợp lệ.”\n– Quá 500 dòng → “File có X dòng dữ liệu, vượt quá giới hạn 500 dòng mỗi lần import. Vui lòng tách file và import nhiều lần.”\n– File hỏng / không đọc được → “Không đọc được file Excel.”\nAfter:\n– Đổ dữ liệu lên bảng xem trước, cập nhật ô Tổng.'],
        ['Bấm Validate', 'Click', 'During:\n– Máy chủ kiểm tra từng dòng theo đúng quy tắc của chức năng Thêm mới và bảng “Quy tắc kiểm tra riêng của file Import”.\n– KHÔNG ghi bất kỳ bản ghi nào ở bước này.\nAfter:\n– Còn dòng lỗi: tô đỏ dòng lỗi kèm lý do, khóa dòng hợp lệ, báo “Validate xong: X hợp lệ, Y không hợp lệ. (Dòng hợp lệ đã bị khoá, chỉ có thể sửa dòng lỗi)”.\n– Không còn dòng lỗi: báo “Tất cả N dòng đã hợp lệ. Có thể import ngay.”, nút Import sáng lên.\n– Không dòng nào hợp lệ: báo “Không có dòng nào hợp lệ để import. Hãy sửa các dòng lỗi và validate lại.”'],
        ['Sửa ô ở dòng lỗi', 'Input', 'After:\n– Dòng chuyển về chưa kiểm tra, hiện “Có dòng đã sửa (cần validate lại)”; phải Validate lại mới Import được.'],
        ['Bấm Bỏ dòng lỗi / Xoá trạng thái validate', 'Click', 'After:\n– Bỏ dòng lỗi: chỉ giữ dòng hợp lệ, nút Import sáng lên.\n– Xoá trạng thái validate: mở khóa mọi dòng, xóa kết quả kiểm tra.'],
        ['Bấm Import', 'Click', 'During:\n– Chỉ gửi các dòng hợp lệ; máy chủ kiểm tra lại toàn bộ, không tin kết quả Validate trước đó.\n– Không còn dòng hợp lệ → báo “Không có dòng nào hợp lệ để import”, dừng.\nAfter:\n– Tạo tỉnh/TP mới ở trạng thái Hoạt động, người tạo là người đang thực hiện.\n– Báo “Import thành công N tỉnh/TP.” (có dòng thất bại: “Import thành công X/Y tỉnh/TP. Z dòng thất bại.”), đóng cửa sổ, nạp lại danh sách.'],
        ['Bấm Làm mới / Đóng', 'Click', 'After:\n– Làm mới: xóa file và bảng, giữ cửa sổ mở.\n– Đóng: đóng cửa sổ, không ghi gì.'],
    ],
})
_FR['Xuất danh sách ra Excel'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
        ['1', 'Nút Xuất Excel', 'Button', 'Enable', 'Hiển thị', 'Nằm trên thanh công cụ của bảng danh sách. Mở cửa sổ “Chọn trường xuất file”.'],
        ['2', 'Dòng hướng dẫn', 'Label', 'Read-only', 'Hiển thị', '“Tích chọn trường cần xuất, kéo ☰ để đổi thứ tự cột trong file.”'],
        ['3', 'Danh sách trường', 'Checkbox chọn nhiều', 'Enable', 'Tích sẵn đúng các cột đang hiển thị trên bảng, xếp lên đầu theo thứ tự trên bảng', 'Mười trường: Tên tỉnh/TP, Mã số tỉnh, Biển số xe, Quốc gia, Khu vực, Trạng thái, Người tạo, Ngày tạo, Người cập nhật, Ngày cập nhật. Kéo biểu tượng ☰ để đổi vị trí cột trong file.'],
        ['4', 'Nút Chọn tất cả', 'Button', 'Enable', 'Hiển thị', 'Tích toàn bộ trường.'],
        ['5', 'Nút Bỏ chọn hết', 'Button', 'Enable', 'Hiển thị', 'Bỏ tích toàn bộ trường.'],
        ['6', 'Dòng đếm trường', 'Label', 'Read-only', 'Hiển thị', '“Đang chọn a/N trường”.'],
        ['7', 'Nút Xuất file', 'Button', 'Enable / Disable', 'Mờ khi chưa chọn trường nào', 'Đóng cửa sổ, sinh file Excel và tải về máy.'],
        ['8', 'Nút Đóng / biểu tượng X', 'Button', 'Enable', 'Hiển thị', 'Đóng cửa sổ, không xuất.'],
    ],
    'ui_widths': [0.6, 1.5, 1.0, 0.8, 1.3, 2.3],
    'events': [
        ['Bấm Xuất Excel', 'Click', 'After:\n– Mở cửa sổ “Chọn trường xuất file”, tích sẵn đúng các cột đang hiển thị trên bảng (theo cấu hình cột của người dùng), các trường còn lại liệt kê bên dưới chưa tích. Không nhớ lựa chọn của lần xuất trước.'],
        ['Tích / bỏ tích trường, kéo ☰', 'Change', 'During:\n– Thứ tự trong danh sách là thứ tự cột trong file.\n– Bỏ chọn hết → nút Xuất file mờ đi.'],
        ['Bấm Xuất file', 'Click', 'During:\n– Sinh file theo ĐÚNG bộ lọc và thứ tự sắp xếp đang áp dụng (tối đa 10,000 dòng), các cột theo đúng thứ tự trường đã chọn.\nAfter:\n– Tải file danh_muc_tinh_thanh_pho.xlsx về máy, báo “Xuất Excel thành công”.\n– Lỗi → báo “Lỗi khi xuất Excel”.'],
        ['Bấm Đóng / biểu tượng X', 'Click', 'After:\n– Đóng cửa sổ, không xuất gì.'],
    ],
})
_FR['Xem chi tiết tỉnh/TP'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
        ['1', 'Tên tỉnh/TP ở cột Tên Tỉnh/TP', 'Link', 'Enable', 'Hiển thị', 'Bấm vào tên để mở cửa sổ Xem (thay cho nút “Xem” ở cột Hành động). Bản ghi Khóa vẫn mở được.'],
        ['2', 'Tiêu đề cửa sổ', 'Label', 'Read-only', 'Xem Tỉnh/TP', 'Kèm biểu tượng tròn ở đầu tiêu đề.'],
        ['3', 'Tên tỉnh/TP', 'Textbox', 'Read-only', 'Dữ liệu hiện tại', 'Chỉ đọc, không sửa được.'],
        ['4', 'Mã số tỉnh', 'Textbox', 'Read-only', 'Dữ liệu hiện tại', 'Chỉ đọc, không sửa được. Trống nếu chưa nhập.'],
        ['5', 'Biển số xe', 'Textbox', 'Read-only', 'Dữ liệu hiện tại', 'Chỉ đọc, không sửa được.'],
        ['6', 'Quốc gia', 'Dropdown', 'Read-only', 'Dữ liệu hiện tại', 'Chỉ đọc, không sửa được. Quốc gia đã khóa vẫn hiện đúng tên kèm 🔒.'],
        ['7', 'Khu vực', 'Dropdown', 'Read-only', 'Dữ liệu hiện tại', 'Chỉ đọc, không sửa được. Khu vực đã khóa vẫn hiện đúng tên kèm 🔒.'],
        ['8', 'Trạng thái', 'Dropdown', 'Read-only', 'Dữ liệu hiện tại', 'Chỉ đọc, không sửa được.'],
        ['9', 'Khối Lịch sử', 'Panel thu gọn', 'Enable', 'Thu gọn', 'Tiêu đề “Lịch sử” kèm số lần thay đổi. Nút “Xem lịch sử” mở khối (đổi thành “Thu gọn”), nút “Làm mới” nạp lại. Nội dung, bộ lọc giống cửa sổ Lịch sử thay đổi.'],
        ['10', 'Nút Đóng / biểu tượng X', 'Button', 'Enable', 'Hiển thị', 'Đóng cửa sổ. Cửa sổ Xem KHÔNG có nút Lưu, Lưu và tiếp tục hay Sửa.'],
    ],
    'ui_widths': [0.6, 1.5, 1.0, 0.8, 1.3, 2.3],
    'events': [
        ['Bấm tên tỉnh/TP ở danh sách', 'Click', 'After:\n– Mở cửa sổ “Xem Tỉnh/TP”, nạp dữ liệu hiện tại của bản ghi ở chế độ chỉ đọc.\n– Không tải được → báo “Lỗi khi tải dữ liệu” và đóng cửa sổ.'],
        ['Bấm Xem lịch sử / Thu gọn', 'Click', 'After:\n– Lần mở đầu tiên mới nạp lịch sử; hiện danh sách thay đổi mới nhất ở trên.\n– Thu gọn: ẩn khối, không nạp lại.'],
        ['Bấm Làm mới trong khối Lịch sử', 'Click', 'After:\n– Nạp lại lịch sử mới nhất của bản ghi.'],
        ['Bấm Đóng / biểu tượng X', 'Click', 'After:\n– Đóng cửa sổ, không hỏi xác nhận (không có gì để lưu).'],
    ],
})
_FR['Tùy chỉnh cột hiển thị'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
        ['1', 'Biểu tượng Cấu hình cột hiển thị', 'Icon Button', 'Enable', 'Hiển thị', 'Nút cuối cùng trên thanh công cụ của bảng. Mở cửa sổ “Tuỳ chỉnh cột”.'],
        ['2', 'Danh sách cột', 'Checkbox', 'Enable', 'Theo cấu hình đã lưu; chưa lưu lần nào thì hiện Mã Tỉnh/TP, Người tạo, Ngày tạo, Trạng thái, ẩn Biển số xe, Quốc gia, Khu vực, Người cập nhật, Ngày cập nhật', 'Liệt kê đủ 12 cột theo thứ tự trên bảng: STT, Tên Tỉnh/TP, Mã Tỉnh/TP, Biển số xe, Quốc gia, Khu vực, Người cập nhật, Ngày cập nhật, Người tạo, Ngày tạo, Trạng thái, Hành động. Tích = hiện cột, bỏ tích = ẩn cột.'],
        ['3', 'Cột bắt buộc', 'Checkbox', 'Disable', 'Luôn tích', 'STT, Tên Tỉnh/TP, Hành động: xám, có biểu tượng khóa, không bỏ tích và không kéo đổi vị trí được (rê chuột hiện “Cột bắt buộc — không thể ẩn hoặc đổi vị trí”).'],
        ['4', 'Biểu tượng ☰', 'Drag handle', 'Enable', 'Hiển thị', 'Kéo thả để đổi thứ tự các cột không bắt buộc.'],
        ['5', 'Nút Lưu', 'Button', 'Enable', 'Hiển thị', 'Áp dụng ngay cho bảng và lưu cấu hình theo TÀI KHOẢN người dùng trên máy chủ (đăng nhập máy/trình duyệt khác vẫn giữ).'],
        ['6', 'Nút Đóng / biểu tượng X', 'Button', 'Enable', 'Hiển thị', 'Đóng cửa sổ, bỏ các thay đổi chưa Lưu.'],
    ],
    'ui_widths': [0.6, 1.5, 1.0, 0.8, 1.3, 2.3],
    'events': [
        ['Bấm biểu tượng Cấu hình cột hiển thị', 'Click', 'After:\n– Mở cửa sổ “Tuỳ chỉnh cột”, tích đúng theo các cột đang hiển thị.'],
        ['Tích / bỏ tích, kéo ☰', 'Change', 'During:\n– Chỉ thay đổi trong cửa sổ, bảng chưa đổi.\n– Cột bắt buộc không bỏ tích, không kéo được.'],
        ['Bấm Lưu', 'Click', 'After:\n– Bảng hiện/ẩn và sắp cột theo cấu hình mới, lưu cấu hình theo người dùng, báo “Cập nhật thành công”; đóng cửa sổ.\n– Lần Xuất Excel sau tích sẵn đúng các cột đang hiện.\n– Lỗi lưu → báo “Thao tác thất bại”.'],
        ['Bấm Đóng / biểu tượng X', 'Click', 'After:\n– Đóng cửa sổ, trả danh sách về cấu hình đang áp dụng.'],
    ],
})
