# -*- coding: utf-8 -*-
# Cấu hình tài liệu màn Danh mục serial thiết bị làm dịch vụ (phân hệ CSKH sau bán) — màn CHỈ ĐỌC.
# Nguồn: code gop_db 25/09/2026 — FE pages/customer-care/serials/index.vue (xuất Excel dựng ở FE bằng ExcelJS);
# BE Modules/CustomerCare (SerialController, SerialService, SerialListResource). Không ghi URL.
# Chữ UI / message lấy nguyên văn code. Không có Tạo/Sửa/Xóa/Khóa/Import/Xem chi tiết/Lịch sử.

DT = 'serial'

_TRUONG_XUAT = 'Serial thiết bị làm dịch vụ, Tên hàng, Khách hàng, Người tạo, Ngày tạo, Người cập nhật, Ngày cập nhật, Trạng thái'
_F_XUAT = 'danh_muc_serial_thiet_bi_lam_dich_vu.xlsx'

CFG = {
    'slug': 'serials',
    'ten': 'Danh mục serial thiết bị làm dịch vụ',
    'doi_tuong': DT,
    'file_hdsd': 'HDSD_Danh muc serial thiet bi lam dich vu.docx',
    'file_srs': 'SRS - Danh mục serial thiết bị làm dịch vụ.docx',
    'menu': [('CSKH sau bán', 'menu_phanhe'), ('Danh mục', 'menu_nhom'), ('Serial thiết bị làm dịch vụ', 'menu_muc')],

    'thuat_ngu': [
        ['Serial', 'Số serial in trên thiết bị, dùng để nhận diện thiết bị khi làm dịch vụ.'],
        ['Tên hàng', 'Mặt hàng / thiết bị tương ứng với serial, lấy theo tên hiện tại trong danh mục hàng hóa (thiết bị của nhà cung cấp khác giữ tên do người dùng tự nhập).'],
        ['Khách hàng', 'Khách hàng đang sở hữu thiết bị, hiển thị dạng mã - tên theo danh mục khách hàng hiện tại.'],
        ['Đang sử dụng', 'Thiết bị còn đang được khách hàng sử dụng và còn làm dịch vụ.'],
        ['Ngưng sử dụng', 'Thiết bị đã ngừng sử dụng hoặc không còn làm dịch vụ nữa.'],
        ['Màn Quản lý khách hàng', 'Nơi DUY NHẤT thêm, sửa, đổi trạng thái hoặc xóa serial (tab Trang thiết bị của khách hàng).'],
    ],
    'phien_ban': [
        ['1.0', '13/08/2026', 'Đội phát triển phần mềm', 'Tạo mới cho màn Danh mục serial thiết bị làm dịch vụ.'],
        ['1.1', '25/09/2026', 'Đội phát triển phần mềm', 'Cập nhật theo phiên bản hiện tại: bộ lọc nâng cao có nhãn nổi và Cài đặt bộ lọc, bổ sung cột Ngày tạo, cửa sổ Chọn trường xuất file, Tùy chỉnh cột hiển thị; trình bày theo mẫu tài liệu danh mục chung.'],
    ],
    'muc_dich': [
        'Màn hình Danh mục serial thiết bị làm dịch vụ dùng để TRA CỨU toàn bộ serial thiết bị đang được làm dịch vụ, kèm tên hàng và khách hàng sở hữu thiết bị.',
        'Tình huống dùng thường gặp: khách hàng gọi tới báo hỏng và chỉ đọc được số serial trên máy. Nhân viên tiếp nhận gõ số serial vào màn này để biết ngay đó là thiết bị gì, của khách hàng nào, còn đang sử dụng hay đã ngưng — trước khi lập phiếu yêu cầu dịch vụ.',
        'Đây là màn CHỈ ĐỌC: không có nút Tạo mới, Sửa, Xóa, Import và không có cột Hành động. Mọi thao tác thêm, sửa, đổi trạng thái hay xóa serial thực hiện ở màn Quản lý khách hàng, tab Trang thiết bị.',
    ],
    'quyen': {
        'truoc': ['Màn hình chỉ có MỘT quyền vì không có thao tác ghi dữ liệu nào.'],
        'rows': [['Xem danh mục serial thiết bị làm dịch vụ', 'Vào màn hình, xem danh sách, tìm kiếm, lọc, sắp xếp, tùy chỉnh cột và Xuất Excel.']],
        'sau': ['Không có quyền thì mục menu bị ẩn và máy chủ không trả dữ liệu. Danh mục KHÔNG phân quyền theo công ty / phòng ban: mọi người có quyền đều thấy cùng một tổng số serial.'],
    },

    'danh_sach': {
        'mo_ta_vao': 'Hệ thống hiển thị danh sách serial, mặc định 10 dòng mỗi trang, serial mới khai báo nằm trên cùng. Danh mục có hơn 21,000 dòng nên nên lọc hoặc tìm trước khi làm việc.',
        'bo_cuc': [
            'Khu vực tìm kiếm và lọc — ô tìm kiếm nhanh, nút Tìm kiếm, Làm mới, nút Tìm kiếm nâng cao (mở thêm các ô Khách hàng, Trạng thái, Người tạo, Người cập nhật) và nút Cài đặt bộ lọc.',
            'Thanh công cụ — nút Xuất Excel và biểu tượng Cấu hình cột hiển thị. Không có nút Tạo mới, Import.',
            'Bảng danh sách — các cột thông tin (không có cột Hành động) và phân trang bên dưới.',
        ],
        'cot': [
            ['STT', 'Số thứ tự, chạy liên tục qua các trang. Luôn hiển thị.'],
            ['Serial thiết bị làm dịch vụ', 'Số serial. Luôn hiển thị, sắp xếp được.'],
            ['Tên hàng', 'Tên mặt hàng / thiết bị. Nội dung dài tự xuống dòng trong ô.'],
            ['Khách hàng', 'Khách hàng sở hữu thiết bị, dạng mã - tên.'],
            ['Người cập nhật', 'Người sửa serial gần nhất. Mặc định ẩn. Serial cũ chưa từng sửa thì để trống — bình thường, không phải lỗi.'],
            ['Ngày cập nhật', 'Thời điểm sửa gần nhất, dạng dd/mm/yyyy hh:mm. Mặc định ẩn, sắp xếp được.'],
            ['Người tạo', 'Người đã khai báo serial.'],
            ['Ngày tạo', 'Thời điểm khai báo, dạng dd/mm/yyyy hh:mm, sắp xếp được.'],
            ['Trạng thái', 'Nhãn Đang sử dụng hoặc Ngưng sử dụng.'],
        ],
        'hanh_dong': None,
        'phan_trang': [
            'Cuối bảng có dòng “Hiển thị a–b / N”: N là tổng số serial khớp bộ lọc đang áp dụng, không phải tổng toàn danh mục.',
            'Ô Số dòng/trang có các mức 5, 10, 20, 50, 100 (mặc định 10). Đổi số dòng thì hệ thống tự quay về trang 1.',
            'Các cột sắp xếp được: Serial thiết bị làm dịch vụ, Ngày tạo, Ngày cập nhật. Bấm tiêu đề cột để sắp xếp, bấm lần hai để đảo chiều. Thứ tự sắp xếp được giữ nguyên khi chuyển trang và khi đang lọc.',
        ],
    },

    'loc': {
        'buoc2': 'Bước 2: Nhập chữ vào ô tìm kiếm nhanh; muốn lọc thêm thì bấm Tìm kiếm nâng cao và chọn giá trị ở các ô Khách hàng, Trạng thái, Người tạo, Người cập nhật.',
        'rows': [
            ['Ô tìm kiếm nhanh', 'Placeholder “Tìm theo serial, tên hàng hoặc khách hàng...”. Quét đồng thời Serial, Tên hàng và tên Khách hàng; gõ một phần chuỗi là đủ, không phân biệt hoa thường. Nhấn Enter hoặc bấm Tìm kiếm để lọc.'],
            ['Khách hàng', 'Gõ để tìm rồi chọn một khách hàng — xem toàn bộ thiết bị của khách hàng đó. Lọc ngay khi chọn.'],
            ['Trạng thái', 'Đang sử dụng hoặc Ngưng sử dụng. Bỏ trống thì hiện cả hai. Lọc ngay khi chọn.'],
            ['Người tạo', 'Chỉ liệt kê những người thực sự đã khai báo serial. Lọc ngay khi chọn.'],
            ['Người cập nhật', 'Chỉ liệt kê những người đã từng sửa serial. Lọc ngay khi chọn.'],
        ],
        'ap_dung': [
            'Các tiêu chí kết hợp với nhau theo kiểu VÀ — kể cả từ khóa ở ô tìm nhanh. Mỗi lần đổi tiêu chí, danh sách quay về trang 1.',
            'Bấm {icon:btn_lammoi} để xóa toàn bộ tiêu chí; danh sách nạp lại đầy đủ ngay lập tức.',
            'Bộ lọc được ghi nhớ trong 10 phút khi rời màn rồi quay lại — thấy danh sách thiếu so với mong đợi thì bấm Làm mới trước.',
            'Nút Cài đặt bộ lọc cho phép ẩn / hiện và sắp xếp lại các ô lọc nâng cao; cấu hình lưu riêng theo từng người dùng.',
        ],
        'anh_ket_qua': 'Kết quả tìm nhanh (gõ “máy hàn”)',
    },

    'form': {'co_tao': False},
    'sua': None,
    'xoa': None,
    'khoa': None,
    'lich_su': None,
    'chi_tiet': None,

    'phan_rieng': [
        {'tieu_de': 'QUAN HỆ VỚI MÀN QUẢN LÝ KHÁCH HÀNG', 'noi_dung': [
            ('h2', '1. Nơi khai báo và sửa serial'),
            ('p', 'Toàn bộ dữ liệu của màn này đến từ tab Trang thiết bị trong màn Quản lý khách hàng. Muốn thêm serial mới, sửa thông tin hoặc chuyển serial sang Ngưng sử dụng, Người dùng phải vào đúng khách hàng ở màn đó.'),
            ('h2', '2. Dữ liệu phản ánh ngay lập tức'),
            ('tbl', ([['Thao tác ở màn Quản lý khách hàng', 'Kết quả tại màn này'],
                      ['Thêm serial mới cho một khách hàng', 'Serial xuất hiện trong danh mục với đúng tên hàng, khách hàng; cột Người tạo là người vừa thao tác.'],
                      ['Sửa thông tin serial', 'Danh mục hiện thông tin mới; cột Người cập nhật và Ngày cập nhật đổi theo lần sửa.'],
                      ['Chuyển serial sang Ngưng sử dụng', 'Serial đổi nhãn trạng thái thành Ngưng sử dụng.'],
                      ['Xóa serial', 'Serial biến mất khỏi danh mục, tổng số dưới bảng giảm đi một.'],
                      ['Đổi tên hàng hóa / khách hàng ở danh mục gốc', 'Cột Tên hàng / Khách hàng hiển thị tên mới.']], [2, 3])),
            ('p', 'Lưu ý khi đối chiếu số liệu: dữ liệu cũ có một nhóm nhỏ serial (khoảng hơn chục dòng) mang giá trị trạng thái không theo quy ước. Những dòng này vẫn hiện nhãn Ngưng sử dụng nhưng KHÔNG lọt vào kết quả khi lọc Trạng thái = Ngưng sử dụng, nên tổng hai lần lọc sẽ nhỏ hơn tổng khi không lọc một chút.'),
        ]},
    ],

    'xuat': {
        'buoc': [
            'Bước 1: Lọc danh sách theo đúng dữ liệu cần lấy (xem PHẦN 2). File xuất chạy theo đúng bộ lọc, từ khóa tìm nhanh và thứ tự sắp xếp đang áp dụng. Nên lọc trước để file gọn và chạy nhanh.',
            'Bước 2: Bấm nút {icon:btn_xuatexcel}. Hệ thống mở cửa sổ “Chọn trường xuất file”.',
            'Bước 3: Tích chọn, kéo biểu tượng ☰ để đổi vị trí các trường cần xuất. Mặc định hệ thống tích sẵn đúng những cột đang hiển thị trên bảng.',
            'Bước 4: Bấm {icon:btn_xuatfile}. Nút Xuất Excel đổi thành “Đang xuất... X%” và không bấm lại được; xong hệ thống tải về file ' + _F_XUAT + ' và báo “Xuất Excel thành công (N dòng)”.',
        ],
        'truong': 'Chọn nhiều trường: ' + _TRUONG_XUAT + '.',
        'ghi_chu': [
            'Lưu ý: file xuất chứa TOÀN BỘ kết quả của bộ lọc, không chỉ các dòng của trang đang xem; cột STT luôn có ở đầu file. Dùng số dòng trong thông báo để đối chiếu với tổng ở cuối bảng.',
            'Danh mục lớn nên file được dựng ngay trên trình duyệt, lấy dữ liệu theo từng lượt 5,000 dòng. Xuất toàn bộ hơn 21,000 dòng mất khoảng 10 đến 20 giây — không rời màn hình trong lúc đang xuất.',
            'Kết quả lọc rỗng thì hệ thống báo “Không có dữ liệu để xuất” và không tải file về.',
        ],
    },
    'import': None,
    'tuy_chinh_cot': {'cot_khoa': 'Hai cột STT và Serial thiết bị làm dịch vụ'},

    'shots': {'list': '01_list.png', 'filter': 'filter.png', 'filter_result': '04_filter_result.png',
              'export': '20_export.png', 'colcfg': '25_colcfg.png'},

    'capture': {'route': '/customer-care/serials',
                'menu': {'phanhe': 'CSKH SAU BÁN', 'nhom': 'Danh mục', 'muc': 'Serial thiết bị làm dịch vụ'},
                'search': 'Tìm theo serial', 'searchText': 'máy hàn',
                'create': False, 'lock': False},

    'uml': {
        'mains': [('FR-01', 'Xem danh sách serial', 'view'), ('FR-03', 'Xuất danh sách ra Excel', 'io')],
        'subs': [('FR-02', 'Tìm kiếm và lọc', 'view'), ('FR-04', 'Tùy chỉnh cột hiển thị', 'view')],
    },

    'srs': {
        'muc_dich': ['Là căn cứ nghiệm thu chức năng tra cứu và kết xuất của màn hình.',
                     'Làm rõ màn hình CHỈ ĐỌC, nguồn dữ liệu là màn Quản lý khách hàng, và cách xuất Excel theo lô cho danh mục lớn.'],
        'quyen_truoc': ['Màn hình dùng đúng một quyền. Máy chủ kiểm tra quyền ở cả danh sách lẫn dữ liệu bộ lọc, nên gọi thẳng chức năng mà bỏ qua giao diện cũng bị chặn.'],
        'quyen_rows': [['Xem danh mục serial thiết bị làm dịch vụ', 'Xem danh sách, tìm kiếm, lọc, sắp xếp, tùy chỉnh cột, Xuất Excel.']],
        'ma_tran': [['Chức năng', 'Xem danh mục serial', 'Không có quyền'],
                    ['FR-01 Xem danh sách serial', 'Có', 'Không'],
                    ['FR-02 Tìm kiếm và lọc', 'Có', 'Không'],
                    ['FR-03 Xuất danh sách ra Excel', 'Có', 'Không'],
                    ['FR-04 Tùy chỉnh cột hiển thị', 'Có', 'Không']],
        'ma_tran_widths': [2.4, 1.4, 1.2],
        'fr': [
            {'ten': 'Xem danh sách serial',
             'qtc': 'Màn Danh sách, Sắp xếp dữ liệu bảng, Phân trang và Cấu hình cột. Chỉ bổ sung các quy tắc riêng của Danh mục serial thiết bị làm dịch vụ.',
             'gioi_thieu': [['Tên chức năng', 'Xem danh sách serial'],
                            ['Mô tả', 'Hiển thị toàn bộ serial thiết bị làm dịch vụ, có phân trang và sắp xếp. Màn chỉ đọc, không có cột Hành động.'],
                            ['Tác nhân', 'Người có quyền “Xem danh mục serial thiết bị làm dịch vụ”'],
                            ['Điều kiện ban đầu', 'Người dùng đã đăng nhập và có quyền.'],
                            ['Dòng sự kiện chính', '1. Người dùng vào menu CSKH sau bán → Danh mục → Serial thiết bị làm dịch vụ.\n2. Hệ thống nạp trang đầu tiên (10 dòng), serial mới khai báo trên cùng.\n3. Bảng hiển thị dữ liệu kèm tổng số bản ghi.'],
                            ['Dòng sự kiện phụ', '• Không có bản ghi khớp → bảng hiện “Không có dữ liệu phù hợp bộ lọc.”\n• Không có quyền → mục menu bị ẩn, máy chủ không trả dữ liệu.'],
                            ['Yêu cầu đặc biệt', 'Tên hàng và Khách hàng lấy theo tên hiện tại ở danh mục gốc (đổi tên ở danh mục gốc thì màn này hiện tên mới).']],
             'anh': [('list', 'Màn Danh mục serial thiết bị làm dịch vụ lúc mới truy cập')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Mô tả'],
                    ['1', 'STT', 'Table/Grid', 'Read-only', 'Số thứ tự, chạy liên tục qua các trang. Luôn hiển thị.'],
                    ['2', 'Serial thiết bị làm dịch vụ', 'Table/Grid', 'Read-only', 'Luôn hiển thị, sắp xếp được.'],
                    ['3', 'Tên hàng', 'Table/Grid', 'Read-only', 'Tự xuống dòng khi dài.'],
                    ['4', 'Khách hàng', 'Table/Grid', 'Read-only', 'Dạng mã - tên.'],
                    ['5', 'Người cập nhật', 'Table/Grid', 'Read-only', 'Mặc định ẩn. Có thể trống với serial chưa từng sửa.'],
                    ['6', 'Ngày cập nhật', 'Table/Grid', 'Read-only', 'dd/mm/yyyy hh:mm. Mặc định ẩn, sắp xếp được.'],
                    ['7', 'Người tạo', 'Table/Grid', 'Read-only', 'Người đã khai báo serial.'],
                    ['8', 'Ngày tạo', 'Table/Grid', 'Read-only', 'dd/mm/yyyy hh:mm, sắp xếp được.'],
                    ['9', 'Trạng thái', 'Badge', 'Read-only', 'Đang sử dụng (status = 1); mọi giá trị khác hiện Ngưng sử dụng.'],
                    ['10', 'Nút Xuất Excel', 'Button', 'Enable', 'Mở cửa sổ Chọn trường xuất file (xem 2.3).'],
                    ['11', 'Biểu tượng Cấu hình cột hiển thị', 'Icon Button', 'Enable', 'Mở cửa sổ Tuỳ chỉnh cột (xem 2.4).'],
                    ['12', 'Phân trang', 'Pagination', 'Enable', 'Số dòng/trang 5 / 10 / 20 / 50 / 100, mặc định 10.']],
             'ui_widths': [0.6, 1.4, 0.9, 0.8, 3],
             'events': [['Mở màn hình', 'System', 'Before:\n– Kiểm tra quyền.\nAfter:\n– Nạp trang đầu (ngày tạo giảm dần) và danh sách Người tạo / Người cập nhật cho bộ lọc.'],
                        ['Bấm tiêu đề cột sắp xếp được', 'Click', 'After:\n– Đổi chiều sắp xếp và nạp lại danh sách từ trang 1.'],
                        ['Chuyển trang', 'Click', 'Before:\n– Giữ nguyên bộ lọc và thứ tự sắp xếp.\nAfter:\n– Nạp dữ liệu trang mới, số thứ tự tiếp tục liên tục.'],
                        ['Đổi số dòng mỗi trang', 'Change', 'After:\n– Quay về trang 1 và nạp lại theo số dòng mới.']]},
            {'ten': 'Tìm kiếm và lọc',
             'qtc': 'Kịch bản tìm kiếm, Bộ lọc, Dropdown, Phân trang. Chỉ bổ sung các tiêu chí tìm kiếm/lọc riêng của màn.',
             'gioi_thieu': [['Tên chức năng', 'Tìm kiếm và lọc danh sách'],
                            ['Mô tả', 'Thu hẹp danh sách bằng ô tìm kiếm nhanh và khối Tìm kiếm nâng cao (Khách hàng, Trạng thái, Người tạo, Người cập nhật) có nhãn nổi.'],
                            ['Tác nhân', 'Người có quyền “Xem danh mục serial thiết bị làm dịch vụ”'],
                            ['Điều kiện ban đầu', 'Đang ở màn Danh mục serial thiết bị làm dịch vụ.'],
                            ['Dòng sự kiện chính', '1. Người dùng nhập từ khóa và bấm Tìm kiếm / Enter, hoặc mở Tìm kiếm nâng cao và chọn tiêu chí (lọc ngay).\n2. Hệ thống áp đồng thời mọi tiêu chí và nạp lại danh sách từ trang 1.'],
                            ['Dòng sự kiện phụ', '• Không có kết quả → bảng hiện “Không có dữ liệu phù hợp bộ lọc.”\n• Bấm Làm mới → xóa hết tiêu chí VÀ nạp lại danh sách đầy đủ ngay.\n• Bộ lọc được ghi nhớ 10 phút khi rời màn rồi quay lại.']],
             'anh': [('filter', 'Khu vực tìm kiếm và lọc'), ('filter_result', 'Kết quả tìm nhanh')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Phạm vi', 'Mô tả'],
                    ['1', 'Ô tìm kiếm nhanh', 'Textbox', 'Enable', '0–255 ký tự', 'Placeholder “Tìm theo serial, tên hàng hoặc khách hàng...”. Khớp một phần, không phân biệt hoa thường.'],
                    ['2', 'Khách hàng', 'Dropdown (tìm từ máy chủ)', 'Enable', 'Danh mục khách hàng', 'Nhãn nổi. Gõ để tìm rồi chọn.'],
                    ['3', 'Trạng thái', 'Dropdown', 'Enable', 'Đang sử dụng / Ngưng sử dụng', 'Nhãn nổi. Bỏ trống thì hiện cả hai.'],
                    ['4', 'Người tạo', 'Dropdown', 'Enable', 'Người đã khai báo serial', 'Nhãn nổi.'],
                    ['5', 'Người cập nhật', 'Dropdown', 'Enable', 'Người đã sửa serial', 'Nhãn nổi.'],
                    ['6', 'Nút Tìm kiếm', 'Button', 'Enable', '–', 'Áp dụng các tiêu chí.'],
                    ['7', 'Nút Làm mới', 'Button', 'Enable', '–', 'Xóa hết tiêu chí VÀ nạp lại danh sách ngay.'],
                    ['8', 'Nút Tìm kiếm nâng cao', 'Button', 'Enable', '–', 'Mở / ẩn các ô lọc nâng cao.'],
                    ['9', 'Nút Cài đặt bộ lọc', 'Button', 'Enable', '–', 'Ẩn / hiện, sắp xếp các ô lọc nâng cao; lưu theo người dùng.']],
             'ui_widths': [0.6, 1.2, 0.9, 0.7, 1.2, 2.4],
             'events': [['Bấm Tìm kiếm / Enter', 'Click', 'After:\n– Áp đồng thời các tiêu chí theo kiểu “và”, nạp lại bảng từ trang 1.'],
                        ['Chọn tiêu chí nâng cao', 'Change', 'After:\n– Lọc ngay, nạp lại bảng từ trang 1.'],
                        ['Bấm Làm mới', 'Click', 'After:\n– Xóa trắng mọi tiêu chí VÀ nạp lại danh sách đầy đủ.']]},
            {'ten': 'Xuất danh sách ra Excel', 'uc': 'uc_fr03',
             'qtc': 'Quy tắc Excel và Cấu hình cột. Chỉ bổ sung danh sách trường được phép xuất riêng của màn.',
             'gioi_thieu': [['Tên chức năng', 'Xuất danh sách ra Excel'],
                            ['Mô tả', 'Xuất kết quả đang lọc ra file Excel, cho phép chọn trường và thứ tự cột. File dựng ngay trên trình duyệt, lấy dữ liệu theo lô.'],
                            ['Tác nhân', 'Người có quyền “Xem danh mục serial thiết bị làm dịch vụ”'],
                            ['Dòng sự kiện chính', '1. Bấm Xuất Excel.\n2. Hệ thống mở cửa sổ “Chọn trường xuất file”, tích sẵn đúng các cột đang hiển thị trên bảng.\n3. Người dùng tích chọn và kéo ☰ để sắp thứ tự.\n4. Bấm Xuất file; nút đổi thành “Đang xuất... X%”, hệ thống lấy dữ liệu theo từng lô 5,000 dòng.\n5. Tải file ' + _F_XUAT + ' theo đúng bộ lọc, thứ tự sắp xếp và thứ tự trường, báo “Xuất Excel thành công (N dòng)”.'],
                            ['Dòng sự kiện phụ', '• Kết quả rỗng → báo “Không có dữ liệu để xuất”, không tải file.\n• Bỏ chọn hết trường → nút Xuất file không bấm được.\n• Bấm Đóng → không xuất gì.\n• Lỗi khi xuất → báo “Lỗi khi xuất Excel”.'],
                            ['Yêu cầu đặc biệt', 'File chứa toàn bộ kết quả lọc, cột STT luôn ở đầu, có dòng tiêu đề “Danh mục serial thiết bị làm dịch vụ”. Serial toàn chữ số (không có số 0 ở đầu, ≤ 15 chữ số) được ghi dạng số.']],
             'menu_them': ' => Xuất Excel {icon:btn_xuatexcel}',
             'anh': [('export', 'Cửa sổ Chọn trường xuất file')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
                    ['1', 'Nút Xuất Excel', 'Button', 'Enable / Disable', 'Hiển thị “Xuất Excel”', 'Nằm trên thanh công cụ của bảng. Mở cửa sổ “Chọn trường xuất file”. Trong lúc đang xuất, chữ đổi thành “Đang xuất... X%” và không bấm được.'],
                    ['2', 'Tiêu đề cửa sổ', 'Label', 'Read-only', 'Chọn trường xuất file', 'Kèm dòng hướng dẫn “Tích chọn trường cần xuất, kéo ☰ để đổi thứ tự cột trong file.”'],
                    ['3', 'Danh sách trường', 'Checkbox chọn nhiều', 'Enable', 'Tích sẵn các cột đang hiển thị trên bảng, xếp lên đầu theo thứ tự trên bảng', 'Tám trường: ' + _TRUONG_XUAT + '. Kéo ☰ ở cuối dòng để đổi thứ tự cột trong file.'],
                    ['4', 'Nút Chọn tất cả', 'Button', 'Enable', 'Hiển thị', 'Tích hết toàn bộ trường.'],
                    ['5', 'Nút Bỏ chọn hết', 'Button', 'Enable', 'Hiển thị', 'Bỏ tích toàn bộ trường.'],
                    ['6', 'Dòng đếm trường', 'Label', 'Read-only', 'Theo số trường tích sẵn', '“Đang chọn a/8 trường”.'],
                    ['7', 'Nút Xuất file', 'Button', 'Enable / Disable', 'Mờ khi chưa chọn trường nào', 'Đóng cửa sổ, lấy dữ liệu theo lô và tải file ' + _F_XUAT + ' về máy.'],
                    ['8', 'Nút Đóng / biểu tượng X', 'Button', 'Enable', 'Hiển thị', 'Đóng cửa sổ, không xuất gì.']],
             'ui_widths': [0.6, 1.5, 1, 0.8, 1.2, 2.6],
             'events': [['Bấm Xuất Excel', 'Click', 'Before:\n– Đang có lượt xuất chạy dở thì nút không bấm được.\nAfter:\n– Mở cửa sổ “Chọn trường xuất file”, tích sẵn đúng các cột đang hiển thị trên bảng (theo Tùy chỉnh cột), các trường còn lại liệt kê bên dưới chưa tích.'],
                        ['Tích / bỏ tích trường, kéo ☰', 'Change', 'During:\n– Thứ tự trường đã tích trong danh sách là thứ tự cột trong file.\n– Cập nhật dòng “Đang chọn a/8 trường”; bỏ chọn hết thì nút Xuất file mờ đi.'],
                        ['Bấm Chọn tất cả / Bỏ chọn hết', 'Click', 'After:\n– Tích / bỏ tích toàn bộ 8 trường.'],
                        ['Bấm Xuất file', 'Click', 'Before:\n– Đóng cửa sổ; nút Xuất Excel đổi thành “Đang xuất... X%”.\nDuring:\n– Lấy dữ liệu theo ĐÚNG bộ lọc và thứ tự sắp xếp đang áp dụng, mỗi lô 5,000 dòng, cập nhật phần trăm sau mỗi lô.\n– Không có dòng nào → báo “Không có dữ liệu để xuất”, không tải file.\nAfter:\n– Dựng file trên trình duyệt: dòng tiêu đề “Danh mục serial thiết bị làm dịch vụ”, cột STT ở đầu, tiếp theo các cột đã chọn đúng thứ tự.\n– Tải ' + _F_XUAT + ' về máy, báo “Xuất Excel thành công (N dòng)”.\n– Lỗi giữa chừng → báo “Lỗi khi xuất Excel”; nút trở lại “Xuất Excel”.'],
                        ['Bấm Đóng / X', 'Click', 'After:\n– Đóng cửa sổ, không xuất gì.']]},
            {'ten': 'Tùy chỉnh cột hiển thị',
             'qtc': 'Tùy chỉnh cột.',
             'gioi_thieu': [['Tên chức năng', 'Tùy chỉnh cột hiển thị'],
                            ['Mô tả', 'Bật/tắt và sắp xếp thứ tự cột của bảng; cấu hình lưu riêng theo người dùng.'],
                            ['Yêu cầu đặc biệt', 'Cột STT, Serial thiết bị làm dịch vụ bị khóa. Mặc định ẩn: Người cập nhật, Ngày cập nhật.']],
             'menu_them': ' => Cấu hình cột {icon:btn_cauhinhcot}',
             'anh': [('colcfg', 'Cửa sổ Tuỳ chỉnh cột')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
                    ['1', 'Biểu tượng Cấu hình cột hiển thị', 'Icon Button', 'Enable', 'Hiển thị', 'Nằm cuối thanh công cụ của bảng, cạnh nút Xuất Excel. Mở cửa sổ “Tuỳ chỉnh cột”.'],
                    ['2', 'Tiêu đề cửa sổ', 'Label', 'Read-only', 'Tuỳ chỉnh cột', '–'],
                    ['3', 'Danh sách cột', 'Checkbox chọn nhiều', 'Enable', 'Theo cấu hình đã lưu của người dùng; chưa lưu lần nào thì tích mọi cột trừ Người cập nhật, Ngày cập nhật', 'Chín cột: STT, Serial thiết bị làm dịch vụ, Tên hàng, Khách hàng, Người cập nhật, Ngày cập nhật, Người tạo, Ngày tạo, Trạng thái. Bỏ tích = ẩn cột khỏi bảng. Kéo ☰ ở cuối dòng để đổi vị trí cột.'],
                    ['4', 'Cột bắt buộc (STT, Serial thiết bị làm dịch vụ)', 'Checkbox', 'Disable', 'Luôn tích', 'Hiện xám kèm biểu tượng ổ khóa “Cột bắt buộc — không thể ẩn hoặc đổi vị trí”; không bỏ tích, không kéo được.'],
                    ['5', 'Nút Lưu', 'Button', 'Enable', 'Hiển thị', 'Áp cấu hình lên bảng, lưu theo tài khoản người dùng và đóng cửa sổ.'],
                    ['6', 'Nút Đóng / biểu tượng X', 'Button', 'Enable', 'Hiển thị', 'Đóng cửa sổ, bỏ mọi thay đổi chưa Lưu.']],
             'ui_widths': [0.6, 1.5, 1, 0.8, 1.4, 2.4],
             'events': [['Bấm biểu tượng Cấu hình cột hiển thị', 'Click', 'After:\n– Mở cửa sổ “Tuỳ chỉnh cột” với trạng thái tích và thứ tự cột đang áp dụng.'],
                        ['Tích / bỏ tích, kéo ☰ đổi vị trí', 'Change', 'During:\n– Cột bắt buộc không bỏ tích, không kéo được.\n– Chưa áp lên bảng cho tới khi bấm Lưu.'],
                        ['Bấm Lưu', 'Click', 'After:\n– Bảng hiển thị ngay theo cấu hình mới.\n– Lưu cấu hình theo tài khoản người dùng (đăng nhập máy khác vẫn giữ), báo “Cập nhật thành công”; lỗi thì báo “Thao tác thất bại”.\n– Đóng cửa sổ. Cửa sổ Chọn trường xuất file lần sau tích sẵn theo bộ cột mới.'],
                        ['Bấm Đóng / X', 'Click', 'After:\n– Đóng cửa sổ, trả danh sách về đúng cấu hình đang áp dụng, bảng không đổi.']]},
        ],
        'quy_tac': [
            ('BR-01', 'Danh mục chỉ để tra cứu',
             ['Màn hình chỉ đọc: không có Tạo mới, Chỉnh sửa, Xóa, Khóa / Mở khóa, Import Excel.',
              'Thêm, sửa, đổi trạng thái, xóa serial thực hiện ở màn Quản lý khách hàng, tab Trang thiết bị; dữ liệu cập nhật tại đó hiện ngay ở danh mục này.'],
             ['Xem danh sách serial', 'Quản lý khách hàng – tab Trang thiết bị']),
            ('BR-02', 'Tên hiển thị theo danh mục gốc',
             ['Tên hàng, Mã / Tên khách hàng hiển thị theo tên hiện tại ở danh mục Hàng hóa, Khách hàng; danh mục gốc đổi tên thì danh sách serial đổi theo.',
              'Hàng hóa / khách hàng không còn trong danh mục gốc thì hiển thị tên đã lưu lúc tạo serial.',
              'Thiết bị của nhà cung cấp khác giữ nguyên tên do người dùng nhập ở tab Trang thiết bị.'],
             ['Xem danh sách serial', 'Tìm kiếm và lọc', 'Xuất danh sách ra Excel']),
            ('BR-03', 'Quy ước trạng thái serial',
             ['Chỉ trạng thái 1 hiển thị “Đang sử dụng”; mọi giá trị khác hiển thị “Ngưng sử dụng”.'],
             ['Xem danh sách serial', 'Tìm kiếm và lọc', 'Xuất danh sách ra Excel']),
            ('BR-04', 'Phạm vi Xuất Excel',
             ['File Excel chứa toàn bộ kết quả theo bộ lọc đang áp dụng, không giới hạn ở trang đang xem.',
              'Dữ liệu được lấy theo từng lô 5,000 dòng (danh mục hơn 21,000 dòng); không có dữ liệu thì báo “Không có dữ liệu để xuất”, xong báo “Xuất Excel thành công (N dòng)”.'],
             ['Xuất danh sách ra Excel']),
        ],
    },

    'loi_code': [
        'Lọc Trạng thái = “Ngưng sử dụng” chỉ lấy status = 2 (SerialService: where status = giá trị chọn), trong khi bảng hiển thị “Ngưng sử dụng” cho mọi status ≠ 1 (SerialListResource). DB local hiện có 13 dòng status = 3 và 1 dòng status = 0 hiện nhãn Ngưng sử dụng nhưng không bao giờ lọt vào kết quả lọc. Tài liệu cũ ghi là “chờ nghiệp vụ chốt” — vẫn còn.',
    ],
}

# ---- Sửa tab testcase "6. DM serial thiết bị làm dịch " (đọc từ ref/testcase_tab.txt) ----
CFG['tc'] = {
    'tab': '6. DM serial thiết bị làm dịch ',
    'hdr_row': 70,             # "IV. XUẤT EXCEL"
    'edits': [
        ('G71', '1. Không lọc gì\n2. Bấm nút Xuất Excel\n3. Giữ nguyên các trường được tích sẵn, bấm Xuất file\n4. Chờ đến khi có thông báo\n5. Mở file tải về'),
        ('I71', '- Mở cửa sổ “Chọn trường xuất file”\n- Trong lúc xử lý nút đổi thành “Đang xuất... X%”, không bấm lại được\n- Kết thúc hiện thông báo “Xuất Excel thành công (N dòng)”, N khớp với tổng dưới bảng\n- Tải về file “' + _F_XUAT + '”, mở được bằng Excel'),
        ('G72', '1. Bấm Xuất Excel → Xuất file và bấm giờ'),
        ('D73', 'File Excel có đúng các cột đã chọn'),
        ('G73', '1. Bấm Xuất Excel\n2. Bấm “Chọn tất cả” rồi Xuất file\n3. Đối chiếu tiêu đề cột trong file với danh sách trường của cửa sổ'),
        ('I73', '- Cửa sổ có đủ 8 trường: %s\n- File có dòng tiêu đề “Danh mục serial thiết bị làm dịch vụ”, cột STT đứng đầu, tiếp theo đúng 8 cột theo thứ tự trong cửa sổ\n- Tiêu đề cột bằng tiếng Việt giống trên màn hình' % _TRUONG_XUAT),
        ('G74', '1. Lọc theo một khách hàng (còn khoảng 50 dòng)\n2. Bấm Xuất Excel → Xuất file\n3. Mở file và đếm'),
        ('G75', '1. Gõ từ khóa và bấm Tìm kiếm\n2. Bấm Xuất Excel → Xuất file\n3. Mở file'),
        ('G76', '1. Đứng ở trang 1 với cỡ trang 10\n2. Bấm Xuất Excel → Xuất file\n3. Đếm số dòng trong file'),
        ('G77', '1. Sắp xếp theo Ngày cập nhật giảm dần\n2. Bấm Xuất Excel → Xuất file\n3. Mở file'),
        ('G78', '1. Lọc ra kết quả rỗng\n2. Bấm Xuất Excel → Xuất file'),
        ('G79', '1. Lọc ra dòng không có người cập nhật\n2. Xuất Excel, tích trường “Người cập nhật”, bấm Xuất file\n3. Mở file'),
        ('G80', '1. Bấm Xuất Excel → Xuất file\n2. Ngay lập tức chuyển sang màn khác\n3. Quay lại'),
        ('G81', '1. Bấm Xuất Excel → Xuất file\n2. Trong lúc nút đang hiện “Đang xuất... X%”, bấm Xuất Excel liên tiếp 3 lần'),
        ('I81', '- Nút “Đang xuất... X%” không bấm được, chỉ chạy MỘT lượt xuất\n- Không tải về nhiều file trùng nhau'),
        ('G82', '1. Lọc còn khoảng 10 dòng, bật đủ các cột bằng Cấu hình cột\n2. Chụp lại nội dung bảng\n3. Xuất Excel → Xuất file và đối chiếu từng ô'),
        ('I82', '- Mọi giá trị serial, tên hàng, khách hàng (mã - tên), trạng thái, người tạo, ngày tạo, người cập nhật, ngày cập nhật đều khớp\n- Không lệch dòng, không lệch cột'),
    ],
    'clear_k': [71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82],
    'blocks': [
        {'after': 82, 'merge_from': 71, 'cases': [
            ('TC_04.013', 'Bỏ tích một trường', 'P1', 'Đang mở cửa sổ “Chọn trường xuất file”.',
             '1. Bỏ tích trường “Khách hàng”\n2. Bấm Xuất file\n3. Mở file', '',
             '- File KHÔNG có cột Khách hàng, các cột còn lại giữ nguyên thứ tự'),
            ('TC_04.014', 'Đổi thứ tự cột bằng kéo ☰', 'P2', 'Đang mở cửa sổ “Chọn trường xuất file”.',
             '1. Kéo biểu tượng ☰ của trường “Trạng thái” lên đầu danh sách\n2. Bấm Xuất file', '',
             '- Trong file, cột Trạng thái đứng ngay sau cột STT, đúng thứ tự vừa kéo'),
            ('TC_04.015', 'Chọn tất cả / Bỏ chọn hết', 'P2', 'Đang mở cửa sổ “Chọn trường xuất file”.',
             '1. Bấm Bỏ chọn hết\n2. Quan sát nút Xuất file\n3. Bấm Chọn tất cả', '',
             '- Bỏ chọn hết: không trường nào được tích, dòng cuối ghi “Đang chọn 0/8 trường”, nút Xuất file không bấm được\n- Chọn tất cả: tích đủ 8 trường'),
            ('TC_04.016', 'Trường tích sẵn theo cột đang hiển thị', 'P1', 'Chưa chỉnh Cấu hình cột hiển thị (mặc định ẩn Người cập nhật, Ngày cập nhật).',
             '1. Bấm Xuất Excel\n2. Xem các trường được tích sẵn\n3. Bấm Đóng', '',
             '- Tích sẵn: Serial thiết bị làm dịch vụ, Tên hàng, Khách hàng, Người tạo, Ngày tạo, Trạng thái\n- Người cập nhật, Ngày cập nhật KHÔNG tích sẵn nhưng tích thêm được\n- Bấm Đóng: cửa sổ đóng, không tải file nào'),
        ]},
    ],
}

CFG['tc_ngoai_pham_vi'] = [
    'TC_03.002 – TC_03.006 (sắp xếp theo Tên hàng, Khách hàng, Trạng thái, Người tạo, Người cập nhật): nay chỉ 3 cột sắp xếp được — Serial, Ngày tạo, Ngày cập nhật.',
    'TC_01.001 và mô tả R8–R10: bảng nay có thêm cột Ngày tạo; Người cập nhật, Ngày cập nhật mặc định ẨN (bật lại bằng Cấu hình cột hiển thị). TC_05.007 “hiện thêm 3 cột” cần đếm lại (nay thêm 4: Người tạo, Ngày tạo, Người cập nhật, Ngày cập nhật).',
    'Khối lọc nay có nút Cài đặt bộ lọc (ẩn/hiện, sắp xếp ô lọc) — tab chưa có case.',
    'Tab chưa có case cho Tùy chỉnh cột hiển thị (cột STT, Serial bị khóa).',
    'TC_02.009 / TC_02.010: lọc Ngưng sử dụng bỏ sót dòng status 0/3 — xem loi_code (case hiện ghi nhận đúng hiện trạng).',
]

CFG.setdefault('loi_code', []).append('Màn danh sách: nội dung cột Tên hàng bị cắt mất phần đầu bên trái (chữ tràn khỏi ô) — thấy khi chụp 26/09/2026.')
