# -*- coding: utf-8 -*-
# Cấu hình tài liệu màn Cập nhật nhanh giá dịch vụ (phân hệ CSKH sau bán) — MÀN ĐẶC THÙ, không phải CRUD:
# một trang riêng có 2 ô nhập + nút Lưu, không có bảng / bộ lọc / tạo / sửa / xóa / khóa / import / xuất.
# Nguồn: code gop_db 25/09/2026 — FE pages/customer-care/service-price-config/index.vue;
# BE Modules/CustomerCare (ServicePriceConfigController, ServicePriceConfigService, ServicePriceConfigRequest,
# ServicePriceConfigResource); route gate erpPermission:Cập nhật nhanh giá dịch vụ. Không ghi URL.
#
# ⚠️ Giới hạn engine catalog_v2 (không sửa engine): build_hdsd luôn sinh "PHẦN 2: TÌM KIẾM VÀ LỌC DANH SÁCH",
# mục "3. Các cột của bảng danh sách" và "Phân trang và sắp xếp". Config dưới đây lấp các chỗ đó bằng nội dung
# "không áp dụng" / mô tả thành phần màn hình — cần engine cho phép bỏ các mục này (vd 'loc': None, 'cot_tieu_de').

DT = 'thông số giá dịch vụ'

CFG = {
    'slug': 'service-price-config',
    'ten': 'Cập nhật nhanh giá dịch vụ',
    'doi_tuong': DT,
    'form_type': 'page',
    'file_hdsd': 'HDSD_Cap nhat nhanh gia dich vu.docx',
    'file_srs': 'SRS - Cập nhật nhanh giá dịch vụ.docx',
    # Menu thật chỉ 2 cấp: mục cấp 1 riêng của phân hệ (không nằm trong nhóm "Danh mục")
    'menu': [('CSKH sau bán', 'menu_phanhe'), ('Cập nhật nhanh giá dịch vụ', 'menu_muc')],

    'thuat_ngu': [
        ['Hệ số giá bán dịch vụ', 'Hệ số nhân dùng khi tính giá bán (giá gốc cấp dịch vụ) của gói bảo dưỡng. Bắt buộc, từ 0.01 đến 999.99.'],
        ['Định mức đàm phán giá (%)', 'Tỷ lệ phần trăm tối đa được phép giảm khi thương lượng giá với khách hàng. Không bắt buộc, từ 0 đến 99.'],
        ['Gói bảo dưỡng', 'Gói dịch vụ bán cho khách hàng (màn Danh mục gói bảo dưỡng). Mọi gói đều bị áp lại hệ số và định mức khi lưu.'],
        ['Cấp dịch vụ', 'Mức độ của một lần bảo dưỡng trong gói. Giá gốc của cấp dịch vụ được tính lại khi hệ số thay đổi.'],
        ['Đơn giá công', 'Đơn giá công của công ty quản lý gói bảo dưỡng; dùng để tính giá gốc cấp dịch vụ.'],
        ['Ghi đè hàng loạt', 'Một lần lưu áp giá trị mới cho toàn bộ gói bảo dưỡng, kể cả gói đã chỉnh riêng. Không có chức năng hoàn tác.'],
    ],
    'phien_ban': [
        ['1.0', '13/08/2026', 'Đội phát triển phần mềm', 'Tạo mới cho màn Cập nhật nhanh giá dịch vụ.'],
        ['1.1', '25/09/2026', 'Đội phát triển phần mềm', 'Cập nhật theo phiên bản hiện tại: mục menu cấp 1 riêng trong phân hệ CSKH sau bán, nút Lưu / Quay lại ở chân trang, lỗi hiện ngay khi nhập, nút Xác nhận trong hộp xác nhận; trình bày theo mẫu tài liệu danh mục chung.'],
    ],
    'muc_dich': [
        'Màn hình Cập nhật nhanh giá dịch vụ dùng để đặt hai thông số chung áp cho TOÀN BỘ gói bảo dưỡng trong hệ thống: Hệ số giá bán dịch vụ và Định mức đàm phán giá (%).',
        'Thay vì vào sửa từng gói, người phụ trách chỉ cần nhập hai con số ở đây và bấm Lưu; hệ thống áp ngay cho tất cả gói bảo dưỡng và tính lại giá gốc của các cấp dịch vụ khi hệ số thay đổi.',
        'Đây là màn có sức ảnh hưởng lớn: một lần Lưu thay đổi giá của hàng trăm gói, ghi đè cả giá trị đã chỉnh riêng ở từng gói, không có hoàn tác. Nên ghi lại (hoặc chụp màn hình) giá trị hai thông số hiện tại TRƯỚC khi thay đổi.',
    ],
    'quyen': {
        'truoc': ['Màn hình chỉ có MỘT quyền: có quyền thì vừa xem vừa lưu được; không có quyền thì mục menu bị ẩn và máy chủ không trả dữ liệu.'],
        'rows': [['Cập nhật nhanh giá dịch vụ', 'Vào màn hình, xem hai thông số hiện tại và bấm Lưu để áp cho toàn bộ gói bảo dưỡng.']],
        'sau': ['Quyền được kiểm tra theo TÊN nên tài khoản đã được cấp quyền này ở phần mềm cũ vẫn dùng được màn này mà không cần cấp lại. Toàn hệ thống chỉ có một bộ thông số dùng chung cho mọi công ty.'],
    },

    'danh_sach': {
        'mo_ta_vao': 'Hệ thống mở trang Cập nhật nhanh giá dịch vụ: một khung nhập gọn ở giữa trang, hai ô hiện sẵn giá trị đang lưu của hệ thống. Không có bảng danh sách, không có bộ lọc, không có phân trang.',
        'bo_cuc': [
            'Khung nhập — hai ô Hệ số giá bán dịch vụ (bắt buộc, có dấu (*)) và Định mức đàm phán giá (%).',
            'Dòng ghi chú ngay dưới hai ô — nêu số gói bảo dưỡng sẽ bị áp lại và dòng “Cập nhật gần nhất”.',
            'Chân trang — nút Lưu (chỉ hiện khi có quyền) và nút Quay lại.',
        ],
        # Engine đặt tiêu đề "Các cột của bảng danh sách" — ở màn này là các THÀNH PHẦN của trang
        'cot': [
            ['Hệ số giá bán dịch vụ', 'Ô nhập số, bắt buộc. Khi mở trang hiện giá trị đang lưu.'],
            ['Định mức đàm phán giá (%)', 'Ô nhập số, không bắt buộc. Khi mở trang hiện giá trị đang lưu (để trống nếu chưa từng đặt).'],
            ['Dòng ghi chú', '“Lưu thay đổi sẽ áp hệ số và định mức đàm phán cho N gói bảo dưỡng, ghi đè giá trị đã chỉnh riêng ở từng gói.” — N là tổng số gói bảo dưỡng hiện có.'],
            ['Dòng Cập nhật gần nhất', '“Cập nhật gần nhất: dd/mm/yyyy hh:mm — Họ tên”. Không hiện nếu hệ thống chưa từng lưu.'],
            ['Nút Lưu', 'Kiểm tra dữ liệu rồi mở hộp xác nhận. Chỉ hiện với người có quyền.'],
            ['Nút Quay lại', 'Rời trang, về trang chủ.'],
        ],
        'hanh_dong': None,
        'phan_trang': ['Màn hình không có bảng danh sách nên không có phân trang và sắp xếp.'],
    },

    # Engine luôn sinh PHẦN "TÌM KIẾM VÀ LỌC" — màn này không có ô lọc nào
    'loc': {
        'buoc2': 'Bước 2: Màn hình không có ô tìm kiếm hay ô lọc — toàn hệ thống chỉ có MỘT bộ thông số, mở trang là thấy ngay giá trị đang dùng.',
        'rows': [['(Không có)', 'Không áp dụng: màn hình không có bảng danh sách, không có ô tìm kiếm / lọc.']],
        'ap_dung': ['Muốn kiểm chứng giá của từng gói sau khi lưu, sang màn Danh mục gói bảo dưỡng để tìm và mở gói cần xem.'],
    },

    'form': {'co_tao': False},
    'sua': None,
    'xoa': None,
    'khoa': None,
    'lich_su': None,
    'chi_tiet': None,

    'phan_rieng': [
        {'tieu_de': 'CẬP NHẬT THÔNG SỐ GIÁ DỊCH VỤ', 'noi_dung': [
            ('h2', '1. Các bước'),
            ('s', 'Bước 1: Ghi lại giá trị hiện tại của hai ô để còn quay lại được nếu cần.'),
            ('s', 'Bước 2: Nhập Hệ số giá bán dịch vụ mới. Nếu chỉ muốn đổi định mức thì giữ nguyên ô này.'),
            ('s', 'Bước 3: Nhập Định mức đàm phán giá (%) nếu cần. Để trống ô này thì định mức của các gói được giữ nguyên.'),
            ('s', 'Bước 4: Bấm {icon:btn_luu} ở chân trang. Nếu còn ô báo đỏ, hệ thống báo “Vui lòng kiểm tra lại dữ liệu nhập” và KHÔNG mở hộp xác nhận.'),
            ('s', 'Bước 5: Hộp “Xác nhận cập nhật giá dịch vụ” hiện ra. Đọc kỹ số gói và số cấp dịch vụ bị ảnh hưởng.'),
            ('s', 'Bước 6: Bấm Xác nhận để thực hiện, hoặc {icon:btn_huy} để dừng — bấm Hủy thì hệ thống không ghi gì.'),
            ('img', ('confirm', 'Hộp xác nhận cập nhật giá dịch vụ')),
            ('h2', '2. Các trường cần nhập'),
            ('tbl', ([['Trường', 'Kiểu nhập', 'Bắt buộc', 'Giá trị ban đầu', 'Ghi chú'],
                      ['Hệ số giá bán dịch vụ', 'Ô nhập số', 'Có', 'Giá trị đang lưu', 'Từ 0.01 đến 999.99, số thập phân nhập bằng dấu chấm (vd 1.5).'],
                      ['Định mức đàm phán giá (%)', 'Ô nhập số', 'Không', 'Giá trị đang lưu', 'Từ 0 đến 99. Nhập 0 là hợp lệ và được lưu thật (khác với để trống).']],
                     [1.3, 0.9, 0.7, 1.1, 2.6])),
            ('h2', '3. Hộp xác nhận'),
            ('p', 'Hộp có tiêu đề “Xác nhận cập nhật giá dịch vụ”, nội dung: “Thao tác này sẽ cập nhật hệ số và định mức đàm phán cho tất cả N gói bảo dưỡng, ghi đè giá trị đã chỉnh riêng ở từng gói. Nếu hệ số thay đổi, giá gốc của M cấp dịch vụ sẽ được tính lại. Bạn có chắc muốn tiếp tục?”. Hai con số N, M lấy từ dữ liệu thực tế lúc mở trang.'),
            ('h2', '4. Kết quả sau khi lưu'),
            ('p', 'Hệ thống báo “Cập nhật thành công. Đã áp cho N gói bảo dưỡng, tính lại giá M cấp dịch vụ.”; nếu có gói bị bỏ qua thì thêm “Bỏ qua K gói chưa có công ty hoặc đơn giá công: <danh sách mã gói>.”. Trang nạp lại, hai ô hiện giá trị mới và dòng “Cập nhật gần nhất” đổi sang thời điểm vừa lưu.'),
            ('p', 'Lưu thất bại thì hệ thống báo lỗi do máy chủ trả về, hoặc “Cập nhật thất bại”. Trang vẫn ở lại, giá trị đang gõ còn nguyên.'),
            ('p', 'Màn hình không hiện danh sách gói — muốn kiểm chứng, sang màn Danh mục gói bảo dưỡng, mở vài gói bất kỳ và đối chiếu hệ số, định mức cùng giá gốc của cấp dịch vụ.'),
        ]},
        {'tieu_de': 'QUY TẮC ÁP GIÁ', 'noi_dung': [
            ('b', 'Hệ số LUÔN được ghi đè cho MỌI gói bảo dưỡng mỗi lần Lưu, kể cả gói đã chỉnh riêng và kể cả khi giá trị không đổi.'),
            ('b', 'Định mức đàm phán giá được ghi đè cho mọi gói khi ô có giá trị (kể cả 0). Để trống ô này thì định mức riêng của các gói được giữ nguyên.'),
            ('b', 'Giá gốc của cấp dịch vụ CHỈ được tính lại khi Hệ số giá bán dịch vụ THỰC SỰ thay đổi: giá gốc = đơn giá công của công ty × định mức công của cấp × hệ số (làm tròn xuống). Chỉ đổi định mức thì giá gốc giữ nguyên.'),
            ('b', 'Gói bảo dưỡng chưa có công ty hoặc đơn giá công được BỎ QUA (không bị đưa giá về 0) và được liệt kê mã trong thông báo kết quả.'),
            ('b', 'Thông số chỉ áp cho việc lập chứng từ MỚI. Báo giá và hợp đồng dịch vụ đã lập trước đó giữ nguyên giá.'),
            ('b', 'Không có lịch sử thay đổi và không có hoàn tác: bấm nhầm thì phải nhập lại giá trị cũ bằng tay; giá trị đã chỉnh riêng ở từng gói không lấy lại được.'),
        ]},
        {'tieu_de': 'RÀNG BUỘC NHẬP LIỆU', 'noi_dung': [
            ('p', 'Lỗi hiện ngay khi nhập: ô sai viền đỏ và có chữ đỏ ngay dưới ô. Còn lỗi thì bấm Lưu không mở hộp xác nhận, không ghi gì.'),
            ('img', ('form_error', 'Lỗi đỏ ngay dưới ô nhập sai')),
            ('tbl', ([['Tình huống', 'Hệ thống báo'],
                      ['Bỏ trống Hệ số giá bán dịch vụ', 'Hiện chưa báo lỗi dưới ô: hộp xác nhận vẫn mở, bấm Xác nhận thì hệ thống báo “Cập nhật thất bại” và không lưu (đã ghi nhận lỗi, chờ sửa).'],
                      ['Hệ số nhập chữ', 'Phải là số'],
                      ['Hệ số nhỏ hơn 0.01 (0 hoặc số âm)', 'Không được nhỏ hơn 0.01'],
                      ['Hệ số lớn hơn 999.99', 'Tối đa 999.99'],
                      ['Định mức nhập chữ', 'Phải là số'],
                      ['Định mức là số âm', 'Không được nhỏ hơn 0'],
                      ['Định mức lớn hơn 99', 'Tối đa 99']], [2.4, 2.4])),
            ('p', 'Định mức đàm phán giá bỏ trống là HỢP LỆ. Nhập Định mức bằng 0 cũng hợp lệ: nạp lại trang phải thấy số 0 chứ không phải ô trống.'),
        ]},
        {'tieu_de': 'CẢNH BÁO KHI CHƯA LƯU', 'noi_dung': [
            ('p', 'Nếu đã sửa giá trị trong ô mà chưa Lưu rồi chuyển sang màn khác (kể cả bấm Quay lại), hệ thống hỏi “Thông tin chưa lưu” — “Bạn có thông tin chưa lưu. Có chắc chắn muốn thoát?”.'),
            ('b', 'Ở lại: trang giữ nguyên giá trị đang gõ.'),
            ('b', 'Thoát: rời trang, hệ thống không ghi gì.'),
            ('p', 'Đóng tab / tải lại trình duyệt lúc đang sửa dở thì trình duyệt cũng hỏi xác nhận. Chưa sửa gì hoặc vừa Lưu xong thì rời trang ngay, không hỏi.'),
        ]},
    ],

    'xuat': None,
    'import': None,
    'tuy_chinh_cot': None,

    # 'confirm' / 'form_error' là key RIÊNG của màn này — capture_tpl.js chuẩn không sinh được (nó chờ 'tbody tr'),
    # cần chụp tay: 01_list = toàn trang, 30_confirm = hộp xác nhận, 31_form_error = gõ chữ / 1000 vào ô Hệ số.
    'shots': {'list': '01_list.png', 'confirm': '30_confirm.png', 'form_error': '31_form_error.png'},

    'capture': {'route': '/customer-care/service-price-config',
                'menu': {'phanhe': 'CSKH SAU BÁN', 'nhom': '', 'muc': 'Cập nhật nhanh giá dịch vụ'},
                'create': False, 'lock': False,
                'manual': 'Màn không có bảng: capture_tpl.js chuẩn sẽ treo ở bước chờ tbody tr. Chụp tay 01_list.png, 30_confirm.png (bấm Lưu, KHÔNG bấm Xác nhận), 31_form_error.png. Menu chỉ 2 cấp (không có nhóm).'},

    'uml': {
        'mains': [('FR-01', 'Xem thông số giá dịch vụ hiện tại', 'view'), ('FR-02', 'Cập nhật nhanh giá dịch vụ', 'crud')],
        'subs': [('FR-03', 'Cảnh báo khi rời trang chưa lưu', 'view')],
    },

    'srs': {
        'muc_dich': ['Thống nhất yêu cầu giữa BA / PO / Dev / Test cho màn Cập nhật nhanh giá dịch vụ; là căn cứ nghiệm thu chức năng và phân quyền.',
                     'Làm rõ phạm vi ảnh hưởng của thao tác Lưu: một lần lưu ghi đè hệ số (và định mức nếu có nhập) cho TOÀN BỘ gói bảo dưỡng, kể cả gói đã chỉnh riêng.',
                     'Ghi nhận khác biệt có chủ đích so với màn cũ: có hộp xác nhận nêu số gói bị ảnh hưởng trước khi ghi; gói thiếu đơn giá công được bỏ qua thay vì bị đưa giá về 0.'],
        'quyen_truoc': ['Màn hình chỉ có MỘT quyền, không tách quyền xem và quyền sửa. Máy chủ kiểm tra quyền theo tên ở cả thao tác đọc lẫn thao tác lưu.'],
        'quyen_rows': [['Cập nhật nhanh giá dịch vụ', 'Mở màn hình, xem thông số hiện tại và lưu cấu hình (áp cho toàn bộ gói bảo dưỡng).']],
        'ma_tran': [['Chức năng', 'Cập nhật nhanh giá dịch vụ', 'Không có quyền'],
                    ['FR-01 Xem thông số giá dịch vụ hiện tại', 'Có', 'Không'],
                    ['FR-02 Cập nhật nhanh giá dịch vụ', 'Có', 'Không'],
                    ['FR-03 Cảnh báo khi rời trang chưa lưu', 'Có', '–']],
        'ma_tran_widths': [2.6, 1.6, 1.2],
        'fr': [
            {'ten': 'Xem thông số giá dịch vụ hiện tại',
             'qtc': 'Màn Xem chi tiết, Phân quyền và UI/UX. Chỉ bổ sung thông tin riêng của màn Cập nhật nhanh giá dịch vụ.',
             'gioi_thieu': [['Tên chức năng', 'Xem thông số giá dịch vụ hiện tại'],
                            ['Mô tả', 'Mở trang hiển thị hai thông số đang lưu, số gói bảo dưỡng sẽ bị áp lại và thời điểm cập nhật gần nhất.'],
                            ['Tác nhân', 'Người có quyền “Cập nhật nhanh giá dịch vụ”'],
                            ['Điều kiện ban đầu', 'Người dùng đã đăng nhập và có quyền.'],
                            ['Dòng sự kiện chính', '1. Người dùng vào menu CSKH sau bán → Cập nhật nhanh giá dịch vụ.\n2. Hệ thống nạp thông số đang lưu, số gói bảo dưỡng và số cấp dịch vụ bị ảnh hưởng.\n3. Trang hiển thị hai ô với giá trị hiện tại, dòng ghi chú và dòng Cập nhật gần nhất.'],
                            ['Dòng sự kiện phụ', '• Hệ thống chưa từng lưu thông số → hai ô để trống, không có dòng Cập nhật gần nhất; vẫn nhập và lưu bình thường.\n• Không có quyền → mục menu bị ẩn, máy chủ không trả dữ liệu.\n• Lỗi khi nạp → báo “Lỗi khi tải dữ liệu”.']],
             'ghi_chu_layout': 'Đây là trang riêng (không phải cửa sổ bật lên), không có bảng danh sách.',
             'anh': [('list', 'Trang Cập nhật nhanh giá dịch vụ')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Phạm vi', 'Giá trị ban đầu', 'Mô tả'],
                    ['1', 'Hệ số giá bán dịch vụ', 'Number', 'Enable', '0.01 – 999.99', 'Giá trị đang lưu', 'Bắt buộc, nhãn có dấu (*).'],
                    ['2', 'Định mức đàm phán giá (%)', 'Number', 'Enable', '0 – 99', 'Giá trị đang lưu', 'Không bắt buộc.'],
                    ['3', 'Dòng ghi chú phạm vi', 'Label', 'Read-only', '–', 'Theo dữ liệu', '“Lưu thay đổi sẽ áp hệ số và định mức đàm phán cho N gói bảo dưỡng, ghi đè giá trị đã chỉnh riêng ở từng gói.”'],
                    ['4', 'Dòng Cập nhật gần nhất', 'Label', 'Read-only', '–', 'Theo dữ liệu', '“Cập nhật gần nhất: dd/mm/yyyy hh:mm — Họ tên”; ẩn nếu chưa từng lưu.'],
                    ['5', 'Nút Lưu', 'Button', 'Enable', '–', 'Chỉ hiện khi có quyền', 'Kiểm tra dữ liệu rồi mở hộp xác nhận (xem 2.2).'],
                    ['6', 'Nút Quay lại', 'Button', 'Enable', '–', 'Hiển thị', 'Rời trang, về trang chủ.']],
             'ui_widths': [0.5, 1.3, 0.7, 0.7, 0.9, 1, 2.2],
             'events': [['Mở trang', 'System', 'Before:\n– Kiểm tra quyền “Cập nhật nhanh giá dịch vụ”.\nAfter:\n– Nạp thông số đang lưu, số gói bảo dưỡng, số cấp dịch vụ, thời điểm và người cập nhật gần nhất.'],
                        ['Bấm Quay lại', 'Click', 'Before:\n– Đã sửa mà chưa lưu → hỏi “Thông tin chưa lưu”.\nAfter:\n– Rời trang, không ghi gì.']]},
            {'ten': 'Cập nhật nhanh giá dịch vụ', 'uc': 'uc_fr02',
             'qtc': 'Validate dữ liệu, Thông báo và UI/UX. Thao tác ghi đè hàng loạt, không ghi lịch sử và không có hoàn tác.',
             'gioi_thieu': [['Tên chức năng', 'Cập nhật nhanh giá dịch vụ'],
                            ['Mô tả', 'Ghi hệ số giá bán và định mức đàm phán vào cấu hình chung, đồng thời áp giá trị mới cho TOÀN BỘ gói bảo dưỡng, ghi đè cả gói đã chỉnh riêng.'],
                            ['Tác nhân', 'Người có quyền “Cập nhật nhanh giá dịch vụ”'],
                            ['Điều kiện ban đầu', 'Đang ở trang Cập nhật nhanh giá dịch vụ, có quyền.'],
                            ['Dòng sự kiện chính', '1. Người dùng sửa Hệ số giá bán dịch vụ và / hoặc Định mức đàm phán giá.\n2. Người dùng bấm Lưu.\n3. Hệ thống kiểm tra dữ liệu rồi mở hộp “Xác nhận cập nhật giá dịch vụ”, nêu số gói bảo dưỡng và số cấp dịch vụ bị ảnh hưởng.\n4. Người dùng bấm Xác nhận.\n5. Hệ thống ghi cấu hình, áp lại cho toàn bộ gói, tính lại giá gốc cấp dịch vụ nếu hệ số đổi, báo “Cập nhật thành công. Đã áp cho N gói bảo dưỡng, tính lại giá M cấp dịch vụ.” và nạp lại trang.'],
                            ['Dòng sự kiện phụ', '• Dữ liệu sai → lỗi đỏ dưới ô + “Vui lòng kiểm tra lại dữ liệu nhập”, không mở hộp xác nhận.\n• Bấm Hủy ở hộp xác nhận → không ghi gì, giá trị đang nhập giữ nguyên.\n• Gói chưa có công ty / đơn giá công → bị bỏ qua, thông báo thêm “Bỏ qua K gói chưa có công ty hoặc đơn giá công: <mã gói>.”\n• Lưu thất bại → báo lỗi máy chủ trả về hoặc “Cập nhật thất bại”.'],
                            ['Yêu cầu đặc biệt', 'Ghi đè hàng loạt, không có hoàn tác; toàn bộ thao tác chạy trong một giao dịch — lỗi giữa chừng thì không gói nào bị đổi.']],
             'menu_them': ' => Lưu {icon:btn_luu}',
             'ghi_chu_layout': 'Hộp Xác nhận cập nhật giá dịch vụ được mở ngay trên trang.',
             'anh': [('confirm', 'Hộp Xác nhận cập nhật giá dịch vụ'), ('form_error', 'Lỗi đỏ ngay dưới ô nhập sai')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Phạm vi', 'Bắt buộc', 'Mô tả'],
                    ['1', 'Hệ số giá bán dịch vụ', 'Number', 'Enable', '0.01 – 999.99', 'Có', 'Bỏ trống: hiện chưa báo lỗi dưới ô, lưu sẽ báo “Cập nhật thất bại”; chữ “Phải là số”; < 0.01 “Không được nhỏ hơn 0.01”; > 999.99 “Tối đa 999.99”.'],
                    ['2', 'Định mức đàm phán giá (%)', 'Number', 'Enable', '0 – 99', 'Không', 'Chữ “Phải là số”; âm “Không được nhỏ hơn 0”; > 99 “Tối đa 99”. Để trống → giữ nguyên định mức của các gói.'],
                    ['3', 'Nội dung hộp xác nhận', 'Label', 'Read-only', '–', '–', 'Nêu số gói bảo dưỡng bị ghi đè và số cấp dịch vụ sẽ tính lại giá gốc nếu hệ số đổi.'],
                    ['4', 'Nút Xác nhận', 'Button', 'Enable', '–', '–', 'Thực hiện ghi đè.'],
                    ['5', 'Nút Hủy', 'Button', 'Enable', '–', '–', 'Đóng hộp, không ghi gì.']],
             'ui_widths': [0.5, 1.3, 0.7, 0.7, 0.9, 0.6, 2.6],
             'events': [['Bấm Lưu', 'Click', 'During:\n– Kiểm tra định dạng / giới hạn hai ô (lỗi hiện ngay khi nhập).\n– Còn lỗi → toast “Vui lòng kiểm tra lại dữ liệu nhập”, cuộn tới ô lỗi, không mở hộp xác nhận.\nAfter:\n– Mở hộp “Xác nhận cập nhật giá dịch vụ”.'],
                        ['Bấm Xác nhận', 'Click', 'Before:\n– Máy chủ kiểm tra quyền và validate lại (Hệ số bắt buộc).\nAfter:\n– Ghi cấu hình chung (tự tạo nếu chưa có).\n– Áp hệ số cho mọi gói; áp định mức nếu ô có giá trị.\n– Hệ số đổi → tính lại giá gốc từng cấp dịch vụ = đơn giá công × định mức công × hệ số (làm tròn xuống); gói thiếu đơn giá công bị bỏ qua.\n– Báo kết quả, nạp lại trang, chốt lại mốc “chưa lưu”.'],
                        ['Bấm Hủy', 'Click', 'After:\n– Đóng hộp, không ghi gì.']],
             'bang_them': [('Quy tắc áp giá', [['Tình huống', 'Kết quả trên gói bảo dưỡng / cấp dịch vụ'],
                            ['Đổi Hệ số', 'Mọi gói nhận hệ số mới; giá gốc mọi cấp dịch vụ được tính lại (trừ gói thiếu đơn giá công).'],
                            ['Giữ nguyên Hệ số, đổi Định mức', 'Mọi gói nhận hệ số (không đổi) và định mức mới; giá gốc cấp dịch vụ giữ nguyên.'],
                            ['Để trống Định mức', 'Định mức riêng của từng gói giữ nguyên; cấu hình chung lưu định mức trống.'],
                            ['Định mức = 0', 'Mọi gói nhận định mức 0 (khác với để trống).'],
                            ['Gói chưa có công ty / đơn giá công', 'Không tính lại giá gốc (giữ giá cũ), mã gói được liệt kê trong thông báo kết quả.']], [2, 3.2])]},
            {'ten': 'Cảnh báo khi rời trang chưa lưu',
             'qtc': 'Quy tắc cảnh báo dữ liệu chưa lưu.',
             'gioi_thieu': [['Tên chức năng', 'Cảnh báo khi rời trang chưa lưu'],
                            ['Mô tả', 'Hỏi xác nhận khi người dùng rời trang lúc đã sửa giá trị mà chưa Lưu.'],
                            ['Dòng sự kiện chính', '1. Người dùng sửa một ô rồi chuyển sang màn khác / bấm Quay lại.\n2. Hệ thống hỏi “Thông tin chưa lưu” — “Bạn có thông tin chưa lưu. Có chắc chắn muốn thoát?” (Thoát / Ở lại).'],
                            ['Dòng sự kiện phụ', '• Chưa sửa gì hoặc vừa Lưu xong → rời trang ngay, không hỏi.\n• Sửa rồi gõ trả lại đúng giá trị cũ → coi như chưa sửa, không hỏi.\n• Đóng tab / tải lại trình duyệt → trình duyệt hỏi xác nhận bằng hộp thoại mặc định của trình duyệt.']],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Mô tả'],
                    ['1', 'Tiêu đề hộp xác nhận', 'Label', '“Thông tin chưa lưu”, kèm biểu tượng cảnh báo màu đỏ.'],
                    ['2', 'Nội dung hộp xác nhận', 'Label', '“Bạn có thông tin chưa lưu. Có chắc chắn muốn thoát?”'],
                    ['3', 'Nút Thoát', 'Button', 'Màu đỏ. Bỏ các giá trị đang nhập dở và rời trang.'],
                    ['4', 'Nút Ở lại / biểu tượng X', 'Button', 'Đóng hộp, ở lại trang, giữ nguyên các giá trị đang nhập.'],
                    ['5', 'Hộp thoại của trình duyệt', 'System dialog', 'Chỉ hiện khi đóng tab / tải lại trang lúc đang có thay đổi chưa lưu; nội dung do trình duyệt quyết định, không đổi được.']],
             'ui_widths': [0.6, 1.6, 1, 3.4],
             'events': [['Sửa ô Hệ số giá bán dịch vụ / Định mức đàm phán giá', 'Change', 'After:\n– Ghi nhận trang có thay đổi chưa lưu (so với giá trị nạp lúc mở trang hoặc lần Lưu gần nhất).\n– Giá trị hệ thống tự nạp vào ô khi mở trang KHÔNG tính là thay đổi.'],
                        ['Bấm Quay lại / chọn menu khác', 'Click', 'Before:\n– Chưa có thay đổi, hoặc đã sửa rồi trả lại đúng giá trị cũ → rời trang ngay, không hỏi.\nAfter:\n– Có thay đổi chưa lưu → hiện hộp “Thông tin chưa lưu”.'],
                        ['Bấm Thoát', 'Click', 'After:\n– Rời trang, không ghi gì.'],
                        ['Bấm Ở lại / X', 'Click', 'After:\n– Đóng hộp, ở lại trang, giá trị đang nhập giữ nguyên.'],
                        ['Đóng tab / tải lại trang', 'System', 'Before:\n– Có thay đổi chưa lưu → trình duyệt hiện hộp xác nhận mặc định.\nAfter:\n– Người dùng chọn rời đi thì mất giá trị đang nhập.'],
                        ['Lưu thành công', 'System', 'After:\n– Nạp lại trang và chốt lại mốc so sánh: rời trang ngay sau đó không bị hỏi; sửa tiếp thì lại được cảnh báo.']]},
        ],
        'quy_tac': [
            ('BR-01', 'Một bộ thông số dùng chung',
             ['Toàn hệ thống chỉ có một bộ thông số, không tách theo công ty; lần lưu sau ghi đè lần trước.',
              'Chưa có bộ thông số thì tự tạo ở lần lưu đầu tiên.'],
             ['Xem thông số giá dịch vụ hiện tại', 'Cập nhật nhanh giá dịch vụ']),
            ('BR-02', 'Giới hạn giá trị nhập',
             ['Hệ số giá bán dịch vụ bắt buộc, từ 0.01 đến 999.99.',
              'Định mức đàm phán giá (%) không bắt buộc, từ 0 đến 99.'],
             ['Cập nhật nhanh giá dịch vụ']),
            ('BR-03', 'Ghi đè hàng loạt toàn bộ gói bảo dưỡng',
             ['Lưu là ghi đè thông số cho TOÀN BỘ gói bảo dưỡng, kể cả gói đã chỉnh riêng.',
              'Bắt buộc qua hộp xác nhận nêu số gói và số cấp dịch vụ bị ảnh hưởng.',
              'Không có hoàn tác, không ghi lịch sử — cần ghi lại giá trị hiện tại trước khi Lưu.'],
             ['Cập nhật nhanh giá dịch vụ', 'Danh mục gói bảo dưỡng']),
            ('BR-04', 'Tính lại giá gốc cấp dịch vụ',
             ['Giá gốc cấp dịch vụ chỉ tính lại khi Hệ số giá bán dịch vụ THỰC SỰ đổi so với lần lưu trước.',
              'Công thức: Đơn giá công của công ty gắn với gói × Định mức công của cấp × Hệ số, làm tròn xuống.'],
             ['Cập nhật nhanh giá dịch vụ', 'Danh mục gói bảo dưỡng']),
            ('BR-05', 'Định mức đàm phán giá để trống',
             ['Định mức đàm phán giá chỉ ghi đè vào các gói khi ô có giá trị (kể cả 0).',
              'Để trống thì giữ nguyên định mức riêng của từng gói.'],
             ['Cập nhật nhanh giá dịch vụ', 'Danh mục gói bảo dưỡng']),
            ('BR-06', 'Gói thiếu công ty hoặc đơn giá công',
             ['Gói chưa có công ty hoặc đơn giá công không được tính lại giá gốc (không bị đưa giá về 0); hệ số mới vẫn được ghi vào gói.',
              'Thông báo kết quả nêu các gói bị bỏ qua: “Bỏ qua N gói chưa có công ty hoặc đơn giá công: <mã gói>.”'],
             ['Cập nhật nhanh giá dịch vụ']),
            ('BR-07', 'Không ảnh hưởng chứng từ đã lập',
             ['Thông số mới chỉ áp cho chứng từ lập MỚI; báo giá / hợp đồng dịch vụ đã lập giữ nguyên giá.'],
             ['Báo giá dịch vụ', 'Hợp đồng dịch vụ']),
        ],
    },

    'loi_code': [
        'Bỏ trống Hệ số giá bán dịch vụ KHÔNG hiện “Bắt buộc phải nhập”: FE chỉ gắn number_only|min_value|max_value_decimal (vee-validate bỏ qua rule khi ô rỗng) nên hộp xác nhận vẫn mở; bấm Xác nhận thì gửi Number(\'\') = 0 → BE trả 422 “Không được nhỏ hơn 0.01”.',
        'Lỗi 422 của BE không hiển thị: submit() không gọi applyServerErrors(), BaseRequest 422 không có key message → chỉ hiện toast chung “Cập nhật thất bại”, không có chữ đỏ dưới ô.',
        'Nhập số thập phân bằng dấu phẩy (vd 1,5): rule FE bỏ dấu phẩy nên coi là 15 hợp lệ, nhưng payload Number(\'1,5\') = NaN → JSON null → BE 422 → toast “Cập nhật thất bại”. Hai tầng hiểu khác nhau.',
        'Dòng ghi chú dưới hai ô dùng class .text-muted → hiển thị chữ ĐỎ (hrm-client ép .text-muted = #dc3545), trái quy ước chữ mô tả phải màu xám.',
        'Nhãn bắt buộc dùng <span class="text-danger">(*)</span> tự viết thay cho component <Required /> dùng chung.',
    ],
}

# ---- Tab testcase "5. Cập nhật nhanh giá dịch vụ" ----
# Màn không có quy tắc tạo mã, Import hay Xuất Excel → KHÔNG sửa / thêm case nào (ngoài phạm vi).
CFG['tc'] = {
    'tab': '5. Cập nhật nhanh giá dịch vụ',
    'hdr_row': 57,             # "IV. GHI DỮ LIỆU HÀNG LOẠT"
    'edits': [],
    'clear_k': [],
    'blocks': [],
}

CFG['tc_ngoai_pham_vi'] = [
    'Toàn tab dùng dấu phẩy thập phân (Hệ số 1,2 / 1,5 / 999,99, “Tối đa 999,99”) — theo chuẩn số quốc tế phải nhập 1.5, câu lỗi là “Tối đa 999.99”; nhập 1,5 hiện không lưu được (xem loi_code).',
    'TC_02.001 (R34) Bỏ trống Hệ số: expected “Bắt buộc phải nhập, không mở hộp xác nhận” — code hiện vẫn mở hộp xác nhận, lưu thì chỉ báo “Cập nhật thất bại” (lỗi code, case đúng thiết kế).',
    'TC_02.003, TC_02.004 (R36, R37): câu lỗi nay là “Không được nhỏ hơn 0.01”, không phải “Phải lớn hơn 0”.',
    'TC_02.006 (R39): câu lỗi “Tối đa 999.99” (dấu chấm).',
    'TC_02.014 (R47) “Lỗi chỉ hiện sau lần bấm Lưu đầu tiên”: nay lỗi hiện NGAY khi nhập (vee-validate realtime).',
    'TC_03.001, TC_03.004, TC_04.007, R64 (và các case có bước “Đồng ý”): nút trong hộp xác nhận nay là “Xác nhận” / “Hủy”, không phải “Đồng ý”.',
    'TC_04.011 (R68): nút Lưu ở chân trang không đổi chữ “Đang lưu...”; chống bấm kép bằng cờ saving + hộp xác nhận.',
    'R26 TC_01.001, đường vào G: menu nay là CSKH sau bán → Cập nhật nhanh giá dịch vụ (mục cấp 1, không còn nhóm “Danh mục - Dịch vụ”); chân trang có thêm nút Quay lại (về trang chủ).',
    'TC_04.003 / BR cũ “định mức LUÔN ghi đè”: để trống Định mức thì định mức của các gói được GIỮ NGUYÊN (chỉ ghi đè khi có giá trị, kể cả 0).',
]
