# -*- coding: utf-8 -*-
# Cấu hình tài liệu màn Danh mục nguồn vốn — bám mẫu configs/areas.py.
# Nguồn: code gop_db 25/09/2026, cập nhật 28/09/2026
#   FE: pages/finance/source-capitals/index.vue, pages/finance/source-capitals/SourceCapitalModal.vue,
#       components/subsystem-menu/finance.js
#   BE: Modules/Finance/Http/Controllers/V1/SourceCapitalController.php, Services/SourceCapitalService.php,
#       Http/Requests/SourceCapitalRequest.php, Entities/SourceCapital.php (USAGE_REFERENCES rỗng),
#       ExportColumnRegistry['source_capitals'], middleware recordNotLocked
# Màn KHÔNG có mã. Từ 28/09/2026: Xóa = xóa HẲN (trước là khoá mềm), có Khóa/Mở khóa, ô Trạng thái trong popup,
# danh sách hiện cả bản ghi Khóa + lọc Trạng thái + cột Trạng thái, cột ẩn Người/Ngày cập nhật.
# Không ghi URL. Chữ UI / message lấy nguyên văn code.

DT = 'nguồn vốn'
QUYEN = 'Quản lý danh mục nguồn vốn'
MSG_USED = 'Nguồn vốn đang được sử dụng, không thể xóa.'
MSG_LOCKED = 'Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.'
MSG_CONFLICT = 'Trạng thái đã bị thay đổi. Vui lòng load lại trang'

CFG = {
    'slug': 'source-capitals',
    'ten': 'Danh mục nguồn vốn',
    'doi_tuong': DT,
    'file_hdsd': 'HDSD_Danh mục nguồn vốn.docx',
    'file_srs': 'SRS - Danh mục nguồn vốn.docx',
    'menu': [('Tài chính', 'menu_phanhe'), ('Danh mục', 'menu_nhom'), ('Danh mục nguồn vốn', 'menu_muc')],
    'form_type': 'popup',

    'capture': {'route': '/finance/source-capitals',
                'menu': {'phanhe': 'TÀI CHÍNH', 'nhom': 'Danh mục', 'muc': 'Danh mục nguồn vốn'},
                'search': 'Tìm theo tên nguồn vốn', 'searchText': 'Vốn', 'detailCol': 1,
                'lockName': 'Vốn vay nội bộ', 'create': True, 'lock': True},

    'thuat_ngu': [
        ['Nguồn vốn', 'Nguồn hình thành vốn của khoản chi hoặc tài sản, ví dụ vốn tự có, vốn vay ngân hàng.'],
        ['Tên nguồn vốn', 'Thông tin định danh của một nguồn vốn (màn hình không có mã). Tên là duy nhất trên toàn hệ thống, không phân biệt chữ hoa/chữ thường.'],
        ['Trạng thái Hoạt động', 'Nguồn vốn đang dùng được, sửa / xóa / khóa được.'],
        ['Trạng thái Khóa', 'Nguồn vốn ngừng dùng: vẫn nằm trong danh mục, vẫn xem được chi tiết và lịch sử, nhưng không sửa và không xóa được cho tới khi Mở khóa.'],
        ['Xóa', 'Xóa hẳn nguồn vốn khỏi danh mục. Chỉ xóa được nguồn vốn đang Hoạt động và chưa được sử dụng ở chứng từ nào.'],
    ],
    'phien_ban': [
        ['1.0', '17/08/2026', 'Đội phát triển phần mềm', 'Lập mới cho màn Danh mục nguồn vốn.'],
        ['1.1', '25/09/2026', 'Đội phát triển phần mềm', 'Cập nhật theo phiên bản hiện tại: nút Lưu và tiếp tục, Xem chi tiết, Xuất Excel (cửa sổ Chọn trường xuất file), Import Excel, Tùy chỉnh cột; trình bày theo mẫu tài liệu danh mục chung.'],
        ['1.2', '28/09/2026', 'Đội phát triển phần mềm', 'Xóa đổi thành xóa hẳn (trước đây là chuyển sang ngừng sử dụng), chỉ khi nguồn vốn đang Hoạt động và chưa được sử dụng; bổ sung Khóa / Mở khóa, ô Trạng thái trong cửa sổ Tạo/Sửa, cột Trạng thái và bộ lọc Trạng thái (danh sách hiện cả nguồn vốn Khóa), cột Người cập nhật / Ngày cập nhật (mặc định ẩn); Xuất Excel thêm các trường Trạng thái, Người cập nhật, Ngày cập nhật.'],
    ],
    'muc_dich': [
        'Danh mục nguồn vốn là nơi khai báo danh sách nguồn vốn dùng cho nghiệp vụ kế toán. Dữ liệu của màn này được chọn khi lập chứng từ, nên mỗi thay đổi ở đây đều ảnh hưởng tới sổ sách.',
    ],
    'quyen': {
        'truoc': ['Màn hình dùng đúng MỘT quyền cho cả xem lẫn thao tác, không tách quyền xem riêng:'],
        'rows': [[QUYEN, 'Thấy mục menu, mở màn hình và thực hiện đầy đủ: Thêm mới, Chỉnh sửa, Xóa, Khóa, Mở khóa, Xem lịch sử, Xem chi tiết, Import Excel, Xuất Excel.']],
        'sau': ['Nếu không có quyền này, mục menu Danh mục nguồn vốn sẽ không hiển thị và hệ thống từ chối mọi thao tác trên màn hình.'],
    },

    'danh_sach': {
        'mo_ta_vao': 'Hệ thống hiển thị danh sách nguồn vốn hiện có (gồm cả nguồn vốn Hoạt động lẫn Khóa), mặc định 10 dòng mỗi trang, mới tạo xếp trên cùng.',
        'bo_cuc': [
            'Khu vực tìm kiếm và lọc — ô tìm kiếm nhanh, ô Trạng thái, nút Tìm kiếm và Làm mới (màn hình không có nút Tìm kiếm nâng cao).',
            'Thanh công cụ — nút Tạo mới, nút Xuất Excel, nút Import Excel và biểu tượng Cấu hình cột hiển thị.',
            'Bảng “Danh sách nguồn vốn” — các cột thông tin, cột Hành động ở cuối, và phân trang bên dưới.',
        ],
        'cot': [
            ['STT', 'Số thứ tự, chạy liên tục qua các trang. Luôn hiển thị.'],
            ['Tên nguồn vốn', 'Tên đầy đủ. Luôn hiển thị, sắp xếp được. Bấm vào tên để mở cửa sổ Xem nguồn vốn.'],
            ['Người cập nhật', 'Người sửa bản ghi gần nhất. Mặc định ẩn.'],
            ['Ngày cập nhật', 'Thời điểm sửa gần nhất, dạng dd/mm/yyyy hh:mm. Mặc định ẩn, sắp xếp được.'],
            ['Người tạo', 'Người đã thêm bản ghi.'],
            ['Ngày tạo', 'Thời điểm thêm, dạng dd/mm/yyyy hh:mm, sắp xếp được.'],
            ['Trạng thái', 'Nhãn Hoạt động hoặc Khóa.'],
            ['Hành động', 'Các nút thao tác của dòng (xem mục 4).'],
        ],
        'hanh_dong': {
            'intro': 'Trên mỗi dòng, cột Hành động có các nút:',
            'bullets': [
                'Biểu tượng bút chì {icon:btn_sua} — mở cửa sổ Sửa nguồn vốn. Chỉ hiện khi nguồn vốn đang Hoạt động.',
                'Biểu tượng thùng rác {icon:btn_xoa} — xóa hẳn nguồn vốn. Chỉ hiện khi nguồn vốn đang Hoạt động VÀ chưa được sử dụng (xem mục Xóa).',
                'Khóa (nguồn vốn đang Hoạt động) / Mở khóa (nguồn vốn đang Khóa) — đổi trạng thái nguồn vốn.',
                'Lịch sử — mở cửa sổ Lịch sử thay đổi.',
                'Có từ 4 nút trở lên thì 2 nút đầu hiện thẳng, các nút còn lại nằm trong nút ba chấm {icon:btn_bacham} “Hành động khác”.',
            ],
            'anh': 'Các nút ở cột Hành động của một nguồn vốn',
            'luu_y': ['Lưu ý quan trọng: với nguồn vốn ĐÃ KHÓA, nút Sửa và Xóa sẽ BIẾN MẤT, chỉ còn Mở khóa và Lịch sử. Muốn sửa lại, Người dùng phải Mở khóa trước.'],
        },
        'phan_trang': [
            'Cuối bảng có dòng “Hiển thị a–b / N”: N là tổng số nguồn vốn khớp bộ lọc đang áp dụng, không phải tổng toàn danh mục.',
            'Ô Số dòng/trang có các mức 5, 10, 20, 50, 100 (mặc định 10). Đổi số dòng thì hệ thống tự quay về trang 1.',
            'Các cột sắp xếp được: Tên nguồn vốn, Ngày tạo, Ngày cập nhật. Bấm tiêu đề cột để sắp xếp, bấm lần hai để đảo chiều. Thứ tự sắp xếp được giữ nguyên khi chuyển trang.',
        ],
    },

    'loc': {
        'buoc2': 'Bước 2: Nhập một phần tên nguồn vốn vào ô tìm kiếm nhanh (nhấn Enter hoặc bấm Tìm kiếm), hoặc chọn giá trị ở ô Trạng thái.',
        'rows': [
            ['Ô tìm kiếm nhanh', 'Placeholder “Tìm theo tên nguồn vốn”. Tìm theo TÊN nguồn vốn (gõ một phần tên cũng ra). Nhấn Enter hoặc bấm Tìm kiếm để lọc.'],
            ['Trạng thái', 'Hoạt động hoặc Khóa. Bỏ trống thì hiện cả hai trạng thái. Lọc ngay khi chọn.'],
        ],
        'ap_dung': [
            'Ô Trạng thái có nhãn nổi ở góc trên ô và nằm ngay cạnh ô tìm kiếm nhanh; màn hình không có nút Tìm kiếm nâng cao.',
            'Các tiêu chí kết hợp với nhau theo kiểu VÀ — chỉ bản ghi thỏa đồng thời tất cả các tiêu chí mới hiện ra. Mỗi lần đổi tiêu chí, danh sách quay về trang 1.',
            'Bấm {icon:btn_lammoi} để xóa toàn bộ tiêu chí; danh sách nạp lại đầy đủ ngay lập tức.',
        ],
        'anh_ket_qua': 'Kết quả tìm nhanh theo tên nguồn vốn (gõ “Vốn”)',
    },

    'form': {
        'kieu': 'popup',
        'buoc_tao': [
            'Bước 1: Truy cập vào màn hình Danh mục nguồn vốn.',
            'Bước 2: Bấm {icon:btn_taomoi}. Hệ thống mở cửa sổ “Tạo nguồn vốn”.',
            'Bước 3: Nhập Tên nguồn vốn, chọn Trạng thái (mặc định Hoạt động).',
            'Bước 4: Bấm {icon:btn_luu} để lưu và đóng cửa sổ, hoặc {icon:btn_luutieptuc} để lưu rồi nhập tiếp nguồn vốn khác.',
        ],
        'anh_tao': 'Cửa sổ Tạo nguồn vốn',
        'truong': [
            ['Tên nguồn vốn', 'Ô nhập giá trị', 'Có', 'Trống (gợi ý “Nhập tên nguồn vốn”)', 'Duy nhất toàn hệ thống, không phân biệt chữ hoa/chữ thường. Bỏ trống báo “Bắt buộc phải nhập” ngay dưới ô; trùng báo “Tên nguồn vốn đã tồn tại”.'],
            ['Trạng thái', 'Ô chọn giá trị', 'Không', 'Hoạt động', 'Chọn 1 trong 2 giá trị: Hoạt động / Khóa.'],
        ],
        'sau_truong': ['Màn hình này không có mã và không có ghi chú: cửa sổ chỉ có ô Tên nguồn vốn và ô Trạng thái.'],
        'nut': [
            ['Lưu', 'Ghi bản ghi rồi đóng cửa sổ, báo “Thêm mới thành công” (hoặc “Cập nhật thành công” khi sửa) và nạp lại danh sách.'],
            ['Lưu và tiếp tục', 'Ghi bản ghi nhưng GIỮ cửa sổ mở và xóa trắng ô nhập để nhập tiếp. Chỉ có khi Tạo mới.'],
            ['Đóng', 'Đóng cửa sổ, không ghi gì. Nếu đã nhập dở, hệ thống hỏi “Thông tin chưa lưu” — “Bạn có thông tin chưa lưu. Có chắc chắn muốn thoát?” (Thoát / Ở lại).'],
        ],
        'loi': [
            ['Bắt buộc phải nhập', 'Chưa nhập Tên nguồn vốn.'],
            ['Tên nguồn vốn đã tồn tại', 'Đã có nguồn vốn khác dùng tên này (kể cả khác chữ hoa/chữ thường, kể cả nguồn vốn đang Khóa). Hãy tra lại danh sách trước khi thêm.'],
            ['Vui lòng nhập tối đa 255 ký tự.', 'Tên nguồn vốn quá dài (báo sau khi bấm Lưu).'],
            ['Vui lòng kiểm tra lại dữ liệu nhập', 'Thông báo chung khi còn ô bị lỗi; xem ô báo đỏ trong cửa sổ.'],
        ],
    },

    'sua': {
        'buoc': [
            'Bước 1: Truy cập vào màn hình Danh mục nguồn vốn.',
            'Bước 2: Bấm nút {icon:btn_sua} ở cột Hành động của nguồn vốn cần sửa.',
            'Bước 3: Hệ thống hiển thị cửa sổ “Sửa nguồn vốn” với Tên và Trạng thái hiện tại.',
            'Bước 4: Sửa thông tin cần sửa (quy tắc nhập như Thêm mới).',
            'Bước 5: Bấm {icon:btn_luu} để xác nhận thay đổi hoặc Đóng nếu muốn hủy.',
        ],
        'anh': 'Cửa sổ Sửa nguồn vốn',
        'ghi_chu': [
            'Giữ nguyên tên của chính nguồn vốn đang sửa thì không bị báo trùng.',
            'Cửa sổ Sửa chỉ có nút Lưu và Đóng (không có Lưu và tiếp tục).',
            'Nguồn vốn đang Khóa không có nút Sửa. Nếu nguồn vốn vừa bị người khác khóa trong lúc đang mở cửa sổ Sửa, bấm Lưu sẽ nhận thông báo “%s”' % MSG_LOCKED,
            'Mọi thay đổi đều được ghi vào Lịch sử kèm tên người sửa và thời điểm.',
        ],
    },
    'xoa': {
        'buoc': [
            'Bước 1: Ở cột Hành động, Người dùng bấm {icon:btn_xoa}.',
            'Bước 2: Hệ thống hiện hộp xác nhận “Xóa nguồn vốn” — “Bạn có chắc muốn xóa nguồn vốn "…"?”. Bấm {icon:btn_confirm_xoa} để xác nhận: hệ thống báo “Đã xóa thành công”, bản ghi biến mất khỏi danh sách.',
            'Bấm {icon:btn_huy} nếu bấm nhầm. Không có gì thay đổi.',
        ],
        'anh': 'Hộp xác nhận xóa nguồn vốn',
        'ghi_chu': [
            'Xóa là xóa HẲN nguồn vốn khỏi danh mục (không phải chuyển sang Khóa); sau khi xóa, tên đó có thể dùng lại để tạo nguồn vốn mới.',
            'Nút Xóa chỉ hiện khi nguồn vốn đang Hoạt động VÀ chưa được sử dụng ở chứng từ nào. Hiện hệ thống chưa có chứng từ nào lưu nguồn vốn theo danh mục này, nên mọi nguồn vốn đang Hoạt động đều có nút Xóa. Nguồn vốn đã được sử dụng (khi có chứng từ chọn nguồn vốn) thì dùng Khóa thay cho Xóa.',
            'Nếu nguồn vốn vừa bị người khác khóa trong lúc đang mở màn hình, bấm Xóa sẽ nhận thông báo “%s”; vừa bị người khác xóa thì nhận “%s”.' % (MSG_LOCKED, MSG_CONFLICT),
        ],
    },
    'khoa': {
        'y_nghia': [
            'Nguồn vốn VẪN nằm trong danh sách, cột Trạng thái hiện chữ Khóa; vẫn xem chi tiết và xem lịch sử thay đổi được.',
            'Nút Sửa và Xóa của dòng đó biến mất. Muốn sửa hoặc xóa, Người dùng phải Mở khóa trước.',
        ],
        'buoc_khoa': [
            'Bước 1: Ở cột Hành động của nguồn vốn đang Hoạt động, Người dùng chọn Khóa (trong nút ba chấm {icon:btn_bacham} nếu dòng có nhiều nút).',
            'Bước 2: Hệ thống hiện hộp xác nhận “Khóa nguồn vốn” — “Bạn có chắc muốn khóa nguồn vốn "…"?”. Bấm Khóa để xác nhận; hệ thống báo “Khóa thành công”, cột Trạng thái đổi thành Khóa. Bấm Hủy nếu bấm nhầm.',
        ],
        'buoc_mo': [
            'Bước 1: Ở cột Hành động của nguồn vốn đang Khóa, Người dùng chọn Mở khóa.',
            'Bước 2: Bấm Mở khóa trong hộp xác nhận “Mở khóa nguồn vốn” — “Bạn có chắc muốn mở khóa nguồn vốn "…"?”. Hệ thống báo “Mở khóa thành công”, cột Trạng thái đổi thành Hoạt động, nút Sửa và Xóa hiện lại. Bấm Hủy nếu bấm nhầm.',
        ],
        'ghi_chu': [
            'Có thể khóa ngay trong cửa sổ Sửa bằng cách chọn Trạng thái = Khóa rồi Lưu, hoặc tạo mới nguồn vốn ở trạng thái Khóa.',
            'Nếu nguồn vốn vừa bị người khác đổi trạng thái (hoặc vừa bị xóa), hệ thống báo “%s”.' % MSG_CONFLICT,
        ],
    },
    'lich_su': {
        'buoc': [
            'Xem từ màn danh sách: ở cột Hành động, Người dùng bấm Lịch sử. Hệ thống mở cửa sổ “Lịch sử thay đổi: <tên nguồn vốn>”.',
            'Xem từ màn chi tiết: bấm vào tên nguồn vốn để mở cửa sổ Xem nguồn vốn, khối Lịch sử nằm ở cuối cửa sổ.',
        ],
        'ghi_chu': [
            'Khóa / Mở khóa (từ cột Hành động hoặc đổi Trạng thái trong cửa sổ Sửa) được ghi thành mốc riêng loại Thay đổi trạng thái.',
            'Cửa sổ có bộ lọc riêng (loại hành động, người thực hiện, khoảng thời gian) để thu hẹp danh sách khi bản ghi có nhiều lần thay đổi. Bản ghi chưa có thao tác nào hiện “Chưa có lịch sử thao tác nào.”',
        ],
    },
    'chi_tiet': {
        'buoc': ['Bước 1: Truy cập vào màn hình Danh mục nguồn vốn.',
                 'Bước 2: Bấm vào tên nguồn vốn ở cột Tên nguồn vốn. Hệ thống mở cửa sổ “Xem nguồn vốn”.'],
        'ghi_chu': ['Cửa sổ hiển thị Tên nguồn vốn và Trạng thái ở chế độ chỉ đọc (không gõ được, không có nút Lưu), kèm khối Lịch sử ở cuối. Nguồn vốn đang Khóa vẫn xem được bình thường.'],
    },
    'xuat': {
        'buoc': [
            'Bước 1: Lọc danh sách theo đúng dữ liệu cần lấy (xem PHẦN 2). File xuất ra chạy theo đúng từ khóa, Trạng thái và thứ tự sắp xếp đang áp dụng.',
            'Bước 2: Bấm nút {icon:btn_xuatexcel}. Hệ thống mở cửa sổ “Chọn trường xuất file”.',
            'Bước 3: Tích chọn, kéo biểu tượng ☰ để đổi vị trí các trường cần xuất. Mặc định hệ thống tích sẵn đúng những cột đang hiển thị trên bảng.',
            'Bước 4: Bấm {icon:btn_xuatfile}. Hệ thống tải về file danh_muc_nguon_von.xlsx và báo “Xuất Excel thành công”.',
        ],
        'truong': 'Chọn nhiều trường: Tên nguồn vốn, Trạng thái, Người tạo, Ngày tạo, Người cập nhật, Ngày cập nhật.',
        'ghi_chu': ['Lưu ý: file xuất chứa TOÀN BỘ kết quả của bộ lọc (tối đa 10,000 dòng, gồm cả nguồn vốn Khóa nếu không lọc Trạng thái), không chỉ các dòng của trang đang xem.'],
    },
    'import': {
        'tieu_de': 'Import nguồn vốn',
        'file': 'Mau_import_nguon_von.xlsx',
        'cot_text': 'Tên nguồn vốn (bắt buộc)',
        'toast': 'Import thành công N nguồn vốn.',
        'loi': [
            ['Tên nguồn vốn không được để trống', 'Dòng đó bỏ trống Tên nguồn vốn (xoá trắng ô trên bảng xem trước). Dòng trống hoàn toàn trong file được tự bỏ qua khi Load.'],
            ['Tên nguồn vốn tối đa 255 ký tự', 'Tên quá dài, rút gọn lại.'],
            ['Tên nguồn vốn bị trùng với dòng N trong file', 'Trong chính file có hai dòng cùng tên (không phân biệt hoa/thường). Xoá bớt một dòng.'],
            ['Tên nguồn vốn đã tồn tại trong hệ thống', 'Danh mục đã có nguồn vốn trùng tên (không phân biệt hoa/thường).'],
        ],
        'ghi_chu': ['Lưu ý: file mẫu chỉ có đúng một cột Tên nguồn vốn (không có cột Trạng thái). Nguồn vốn nhập từ Excel luôn ở trạng thái Hoạt động; kiểm tra trùng tên tính cả nguồn vốn đang Khóa; người tạo là chính người thực hiện nhập. Mỗi lần nhập tối đa 500 dòng; file dài hơn hệ thống báo “File có X dòng dữ liệu, vượt quá giới hạn 500 dòng mỗi lần import. Vui lòng tách file và import nhiều lần.”'],
    },
    'tuy_chinh_cot': {'cot_khoa': 'Ba cột STT, Tên nguồn vốn và Hành động'},

    'shots': {'list': '01_list.png', 'rowmenu': '03_rowmenu.png', 'filter': 'filter.png', 'filter_result': '04_filter_result.png',
              'create': '10_create.png', 'create_error': '11_create_error.png',
              'edit': '12_edit.png', 'delete': '13_delete.png', 'lock': '14_lock.png', 'unlock': '15_unlock.png', 'history': '16_history.png',
              'detail': '17_detail.png', 'export': '20_export.png', 'import_open': '21_import_open.png',
              'import_loaded': '22_import_loaded.png', 'import_validated': '23_import_validated.png', 'colcfg': '25_colcfg.png'},

    'import_test': {
        'cols': ['STT', 'Tên nguồn vốn *'],
        'rows': [
            [1, 'DOC-Vốn kiểm thử 1'],
            [2, 'DOC-Vốn kiểm thử 2'],
            [3, 'DOC-Vốn kiểm thử 3'],
            [4, 'doc-vốn kiểm thử 1'],          # trùng dòng 1 trong file (khác hoa/thường)
            [5, 'Vốn test'],                    # trùng hệ thống
            [6, 'VỐN TEST'],                    # trùng hệ thống khác hoa/thường
            [7, 'DOC-' + 'X' * 252],            # 256 ký tự
        ],
    },

    'uml': {
        'mains': [('FR-01', 'Xem danh sách nguồn vốn', 'view'), ('FR-03', 'Thêm mới nguồn vốn', 'crud'),
                  ('FR-04', 'Chỉnh sửa nguồn vốn', 'crud'), ('FR-05', 'Xóa nguồn vốn', 'action'),
                  ('FR-06', 'Khóa / Mở khóa nguồn vốn', 'action'),
                  ('FR-08', 'Import file nguồn vốn', 'io'), ('FR-09', 'Xuất danh sách nguồn vốn ra Excel', 'io')],
        'subs': [('FR-02', 'Tìm kiếm và lọc nguồn vốn', 'view'), ('FR-10', 'Xem chi tiết nguồn vốn', 'view'),
                 ('FR-11', 'Tùy chỉnh cột hiển thị', 'view'), ('FR-07', 'Xem lịch sử thay đổi', 'view')],
        'rieng': [('FR-10', 'Xem chi tiết nguồn vốn', 'view')],
    },

    'srs': {
        'muc_dich': ['Là căn cứ nghiệm thu chức năng và phân quyền.',
                     'Làm rõ ràng buộc trùng Tên nguồn vốn (duy nhất toàn hệ thống, màn hình không có mã).',
                     'Làm rõ điều kiện Xóa (xóa hẳn, chỉ khi đang Hoạt động và chưa được sử dụng) và quy tắc Khóa / Mở khóa (nguồn vốn đang Khóa không sửa, không xóa được).'],
        'quyen_truoc': ['Màn hình chỉ có MỘT quyền duy nhất, không tách riêng quyền xem và quyền sửa. Người không có quyền này không vào được màn hình.'],
        'quyen_rows': [[QUYEN, 'Thấy mục menu, mở màn hình và thực hiện đầy đủ Thêm mới, Chỉnh sửa, Xóa, Khóa, Mở khóa, Xem lịch sử, Xem chi tiết, Import Excel, Xuất Excel. Thiếu quyền này thì mục menu không hiển thị và máy chủ từ chối mọi thao tác.']],
        'ma_tran': [['Chức năng', QUYEN, 'Không có quyền']] + [[f, '✅', '❌'] for f in [
            'FR-01 Xem danh sách nguồn vốn', 'FR-02 Tìm kiếm và lọc', 'FR-03 Thêm mới nguồn vốn', 'FR-04 Chỉnh sửa nguồn vốn',
            'FR-05 Xóa nguồn vốn', 'FR-06 Khóa / Mở khóa nguồn vốn', 'FR-07 Xem lịch sử thay đổi', 'FR-08 Import file nguồn vốn',
            'FR-09 Xuất danh sách ra Excel', 'FR-10 Xem chi tiết nguồn vốn', 'FR-11 Tùy chỉnh cột hiển thị']],
        'ma_tran_widths': [2.4, 1.6, 1.2],
        'fr': [
            {'ten': 'Xem danh sách nguồn vốn',
             'qtc': 'Màn Danh sách, Sắp xếp dữ liệu bảng, Phân trang và Cấu hình cột. Chỉ bổ sung các quy tắc riêng của Danh mục nguồn vốn tại phần mô tả chi tiết.',
             'gioi_thieu': [['Tên chức năng', 'Xem danh sách nguồn vốn'],
                            ['Mô tả', 'Hiển thị toàn bộ nguồn vốn trong danh mục (cả Hoạt động lẫn Khóa), có phân trang và sắp xếp.'],
                            ['Tác nhân', 'Người dùng có quyền “%s”' % QUYEN],
                            ['Điều kiện ban đầu', 'Người dùng đã đăng nhập và có quyền “%s”.' % QUYEN],
                            ['Dòng sự kiện chính', '1. Người dùng vào menu Tài chính → Danh mục → Danh mục nguồn vốn.\n2. Hệ thống nạp trang đầu tiên của danh sách (10 dòng, mới tạo trước).\n3. Bảng hiển thị dữ liệu kèm tổng số bản ghi.'],
                            ['Dòng sự kiện phụ', '• Không có bản ghi khớp → bảng hiện “Không có dữ liệu phù hợp bộ lọc.”\n• Không có quyền → mục menu không hiển thị, máy chủ từ chối truy cập.']],
             'anh': [('list', 'Màn Danh mục nguồn vốn lúc mới truy cập')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Mô tả'],
                    ['1', 'STT', 'Table/Grid', 'Read-only', 'Số thứ tự, chạy liên tục qua các trang. Luôn hiển thị, không ẩn được.'],
                    ['2', 'Tên nguồn vốn', 'Table/Grid', 'Read-only', 'Luôn hiển thị, sắp xếp được. Bấm vào tên mở cửa sổ Xem (xem 2.10).'],
                    ['3', 'Người cập nhật', 'Table/Grid', 'Read-only', 'Mặc định ẩn.'],
                    ['4', 'Ngày cập nhật', 'Table/Grid', 'Read-only', 'dd/mm/yyyy hh:mm. Mặc định ẩn, sắp xếp được.'],
                    ['5', 'Người tạo', 'Table/Grid', 'Read-only', 'Người đã thêm bản ghi.'],
                    ['6', 'Ngày tạo', 'Table/Grid', 'Read-only', 'dd/mm/yyyy hh:mm, sắp xếp được.'],
                    ['7', 'Trạng thái', 'Badge', 'Read-only', 'Hoạt động hoặc Khóa.'],
                    ['8', 'Hành động', 'Table/Grid', 'Read-only', 'Sửa (khi Hoạt động), Xóa (khi Hoạt động và chưa được sử dụng), Khóa / Mở khóa, Lịch sử. Từ 4 nút trở lên thì 2 nút đầu hiện thẳng, còn lại trong nút ba chấm.'],
                    ['9', 'Nút Tạo mới', 'Button', 'Enable', 'Mở cửa sổ Tạo nguồn vốn.'],
                    ['10', 'Nút Xuất Excel', 'Button', 'Enable', 'Mở cửa sổ Chọn trường xuất file (xem 2.9).'],
                    ['11', 'Nút Import Excel', 'Button', 'Enable', 'Mở cửa sổ Import nguồn vốn (xem 2.8).'],
                    ['12', 'Biểu tượng Cấu hình cột hiển thị', 'Icon Button', 'Enable', 'Mở cửa sổ Tuỳ chỉnh cột (xem 2.11).'],
                    ['13', 'Phân trang', 'Pagination', 'Enable', 'Số dòng/trang 5 / 10 / 20 / 50 / 100, mặc định 10.']],
             'ui_widths': [0.6, 1.4, 0.9, 0.8, 3],
             'events': [['Mở màn hình', 'System', 'After:\n– Nạp trang đầu (cả Hoạt động lẫn Khóa), hiển thị tổng số bản ghi.'],
                        ['Bấm tiêu đề cột sắp xếp được', 'Click', 'After:\n– Đổi chiều sắp xếp và nạp lại danh sách từ trang 1.'],
                        ['Chuyển trang', 'Click', 'Before:\n– Giữ nguyên bộ lọc và thứ tự sắp xếp.\nAfter:\n– Nạp dữ liệu trang mới, số thứ tự tiếp tục liên tục.'],
                        ['Đổi số dòng mỗi trang', 'Change', 'After:\n– Quay về trang 1 và nạp lại theo số dòng mới.']]},
            {'ten': 'Tìm kiếm và lọc',
             'qtc': 'Kịch bản tìm kiếm, Bộ lọc, Dropdown, Phân trang. Chỉ bổ sung các tiêu chí tìm kiếm/lọc riêng của Danh mục nguồn vốn.',
             'gioi_thieu': [['Tên chức năng', 'Tìm kiếm và lọc danh sách'],
                            ['Mô tả', 'Thu hẹp danh sách bằng ô tìm kiếm nhanh theo tên và ô Trạng thái. Màn hình không có nút Tìm kiếm nâng cao.'],
                            ['Tác nhân', 'Người dùng có quyền “%s”' % QUYEN],
                            ['Điều kiện ban đầu', 'Đang ở màn Danh mục nguồn vốn.'],
                            ['Dòng sự kiện chính', '1. Người dùng nhập từ khóa và bấm Tìm kiếm / Enter, hoặc chọn Trạng thái (lọc ngay).\n2. Hệ thống áp đồng thời mọi tiêu chí và nạp lại danh sách từ trang 1.'],
                            ['Dòng sự kiện phụ', '• Không có kết quả → bảng hiện “Không có dữ liệu phù hợp bộ lọc.”\n• Bấm Làm mới → xóa hết tiêu chí VÀ nạp lại danh sách đầy đủ ngay.']],
             'anh': [('filter', 'Khu vực tìm kiếm và lọc của màn Danh mục nguồn vốn')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Phạm vi', 'Mô tả'],
                    ['1', 'Ô tìm kiếm nhanh', 'Textbox', 'Enable', '0–255 ký tự', 'Placeholder “Tìm theo tên nguồn vốn”. Tìm theo TÊN (khớp một phần).'],
                    ['2', 'Trạng thái', 'Dropdown', 'Enable', 'Hoạt động / Khóa', 'Nhãn nổi. Bỏ trống thì hiện cả hai trạng thái.'],
                    ['3', 'Nút Tìm kiếm', 'Button', 'Enable', '–', 'Áp dụng các tiêu chí.'],
                    ['4', 'Nút Làm mới', 'Button', 'Enable', '–', 'Xóa hết tiêu chí VÀ nạp lại danh sách ngay.']],
             'ui_widths': [0.6, 1.2, 0.8, 0.7, 1.1, 2.6],
             'events': [['Bấm Tìm kiếm / Enter', 'Click', 'After:\n– Áp đồng thời các tiêu chí theo kiểu “và”, nạp lại bảng từ trang 1.'],
                        ['Chọn Trạng thái', 'Change', 'After:\n– Lọc ngay, nạp lại bảng từ trang 1.'],
                        ['Bấm Làm mới', 'Click', 'After:\n– Xóa trắng mọi tiêu chí VÀ nạp lại danh sách đầy đủ.']]},
            {'ten': 'Thêm mới nguồn vốn', 'uc': 'uc_fr03',
             'qtc': 'Màn Thêm mới, Validate dữ liệu, Thông báo và UI/UX. Logic ghi lịch sử áp dụng theo SRS Các quy tắc chung - Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Thêm mới nguồn vốn'],
                            ['Mô tả', 'Thêm một nguồn vốn mới thông qua cửa sổ nhập liệu gồm ô Tên nguồn vốn và ô Trạng thái.'],
                            ['Tác nhân', 'Người dùng có quyền “%s”' % QUYEN],
                            ['Điều kiện ban đầu', 'Đang ở màn Danh mục nguồn vốn.'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm Tạo mới.\n2. Hệ thống mở cửa sổ “Tạo nguồn vốn”, Trạng thái mặc định Hoạt động.\n3. Người dùng nhập Tên nguồn vốn (tùy chọn Trạng thái) và bấm Lưu.\n4. Hệ thống kiểm tra dữ liệu, ghi bản ghi mới và ghi lịch sử Tạo mới.\n5. Cửa sổ đóng, danh sách nạp lại, báo “Thêm mới thành công”.'],
                            ['Dòng sự kiện phụ', '• Bỏ trống tên → báo ngay “Bắt buộc phải nhập”.\n• Trùng tên → báo lỗi đỏ dưới ô “Tên nguồn vốn đã tồn tại” + toast “Vui lòng kiểm tra lại dữ liệu nhập”, cửa sổ KHÔNG đóng.\n• Bấm “Lưu và tiếp tục” → ghi bản ghi rồi giữ cửa sổ mở với ô trống.\n• Bấm Đóng khi đã nhập dở → hỏi “Thông tin chưa lưu” (Thoát / Ở lại).'],
                            ['Yêu cầu đặc biệt', 'Cửa sổ có ba nút: Lưu, Lưu và tiếp tục, Đóng.']],
             'menu_them': ' => Tạo mới {icon:btn_taomoi}',
             'ghi_chu_layout': 'Cửa sổ Tạo nguồn vốn được mở ngay trên màn hình danh sách.',
             'anh': [('create', 'Cửa sổ Tạo nguồn vốn'), ('create_error', 'Lỗi đỏ ngay dưới ô còn thiếu')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Phạm vi', 'Bắt buộc', 'Mô tả'],
                    ['1', 'Tên nguồn vốn', 'Textbox', 'Enable', 'Chuỗi ký tự', 'Có', 'Placeholder “Nhập tên nguồn vốn”. Duy nhất toàn hệ thống, không phân biệt hoa/thường. Bỏ trống “Bắt buộc phải nhập”; trùng “Tên nguồn vốn đã tồn tại”.'],
                    ['2', 'Trạng thái', 'Dropdown', 'Enable', 'Hoạt động / Khóa', 'Không', 'Mặc định Hoạt động.'],
                    ['3', 'Nút Lưu', 'Button', 'Enable', '', '', 'Ghi bản ghi rồi đóng cửa sổ.'],
                    ['4', 'Nút Lưu và tiếp tục', 'Button', 'Enable', '', '', 'Ghi bản ghi rồi giữ cửa sổ mở để nhập tiếp.'],
                    ['5', 'Nút Đóng', 'Button', 'Enable', '', '', 'Hủy bỏ, không ghi gì.']],
             'ui_widths': [0.6, 1.3, 0.8, 0.6, 1.1, 0.5, 2.3],
             'events': [['Bấm nút Tạo mới', 'Click', 'After:\n– Mở cửa sổ nhập liệu với ô Tên trống, Trạng thái = Hoạt động.'],
                        ['Bấm Lưu', 'Click', 'During:\n– Kiểm tra bắt buộc, trùng tên toàn hệ thống.\n– Có lỗi → báo đỏ dưới ô, không thực hiện After.\nAfter:\n– Ghi bản ghi mới, ghi lịch sử Tạo mới.\n– Đóng cửa sổ, nạp lại danh sách, báo “Thêm mới thành công”.'],
                        ['Bấm Lưu và tiếp tục', 'Click', 'During:\n– Như nút Lưu.\nAfter:\n– Ghi bản ghi, xóa trắng các ô, GIỮ cửa sổ mở.'],
                        ['Bấm Đóng', 'Click', 'After:\n– Chưa nhập gì → đóng cửa sổ. Đã nhập → hỏi “Thông tin chưa lưu”.']]},
            {'ten': 'Chỉnh sửa nguồn vốn', 'uc': 'uc_fr04',
             'qtc': 'Validate dữ liệu, Thông báo, Quy định chung về danh mục và Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Chỉnh sửa nguồn vốn'],
                            ['Mô tả', 'Sửa tên và trạng thái một nguồn vốn đang Hoạt động. Dùng chung cửa sổ với Thêm mới.'],
                            ['Tác nhân', 'Người dùng có quyền “%s”' % QUYEN],
                            ['Điều kiện ban đầu', 'Nguồn vốn đang ở trạng thái Hoạt động.'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm biểu tượng bút chì ở dòng cần sửa.\n2. Hệ thống mở cửa sổ “Sửa nguồn vốn” với dữ liệu hiện tại.\n3. Người dùng sửa và bấm Lưu.\n4. Hệ thống kiểm tra, ghi thay đổi và ghi lịch sử.\n5. Cửa sổ đóng, báo “Cập nhật thành công”.'],
                            ['Dòng sự kiện phụ', '• Giữ nguyên tên của chính bản ghi → không báo trùng.\n• Trùng tên với nguồn vốn khác → báo “Tên nguồn vốn đã tồn tại”.\n• Chọn Trạng thái = Khóa → lưu bình thường, dòng đó chỉ còn Mở khóa và Lịch sử.\n• Nguồn vốn vừa bị người khác khóa → báo “%s”' % MSG_LOCKED]],
             'menu_them': ' => Sửa {icon:btn_sua}',
             'anh': [('edit', 'Cửa sổ Sửa nguồn vốn')],
             'events': [['Bấm biểu tượng bút chì', 'Click', 'Before:\n– Nguồn vốn đã Khóa thì nút không hiển thị.\nAfter:\n– Mở cửa sổ với dữ liệu hiện tại.'],
                        ['Bấm Lưu', 'Click', 'Before:\n– Nguồn vốn đang Khóa → máy chủ từ chối, báo “%s”\nDuring:\n– Kiểm tra như Thêm mới, bỏ qua trùng với chính bản ghi.\nAfter:\n– Ghi thay đổi, ghi lịch sử “Thay đổi thông tin” (đổi Trạng thái ghi mốc Khóa / Mở khóa riêng), báo “Cập nhật thành công”.' % MSG_LOCKED]]},
            {'ten': 'Xóa nguồn vốn', 'uc': 'uc_fr05',
             'qtc': 'Quy tắc Xóa, Thông báo, Quy định chung về danh mục và Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Xóa nguồn vốn'],
                            ['Mô tả', 'Xóa hẳn một nguồn vốn đang Hoạt động và chưa được sử dụng ở chứng từ nào.'],
                            ['Tác nhân', 'Người dùng có quyền “%s”' % QUYEN],
                            ['Điều kiện ban đầu', 'Nguồn vốn đang Hoạt động và chưa được sử dụng. Hiện chưa có chứng từ nào lưu nguồn vốn theo danh mục này nên mọi nguồn vốn đang Hoạt động đều thỏa điều kiện.'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm biểu tượng thùng rác.\n2. Hệ thống hiện hộp “Xóa nguồn vốn” nêu rõ tên bản ghi.\n3. Người dùng bấm Xóa.\n4. Hệ thống xóa hẳn bản ghi, ghi lịch sử, báo “Đã xóa thành công”, nạp lại danh sách.'],
                            ['Dòng sự kiện phụ', '• Bấm Hủy → đóng hộp, không thay đổi.\n• Nguồn vốn đang Khóa (hoặc đã được sử dụng) → nút Xóa KHÔNG hiển thị.\n• Nguồn vốn vừa bị người khác khóa → báo “%s”\n• Nguồn vốn vừa bị người khác xóa → báo “%s”.\n• Máy chủ còn chặn nguồn vốn đã được sử dụng với câu “%s” (áp dụng khi có chứng từ chọn nguồn vốn).' % (MSG_LOCKED, MSG_CONFLICT, MSG_USED)]],
             'menu_them': ' => Xóa {icon:btn_xoa}',
             'anh': [('delete', 'Hộp xác nhận xóa nguồn vốn')],
             'events': [['Bấm biểu tượng thùng rác', 'Click', 'Before:\n– Chỉ hiển thị khi nguồn vốn đang Hoạt động và chưa được sử dụng.\nAfter:\n– Hiện hộp xác nhận kèm tên bản ghi.'],
                        ['Bấm Xóa', 'Click', 'During:\n– Kiểm tra lại: bản ghi còn tồn tại, đang Hoạt động, chưa được sử dụng.\nAfter:\n– Xóa hẳn bản ghi, ghi lịch sử, nạp lại danh sách, báo thành công.'],
                        ['Bấm Hủy', 'Click', 'After:\n– Đóng hộp, không thay đổi.']]},
            {'ten': 'Khóa / Mở khóa nguồn vốn', 'uc': 'uc_fr06',
             'qtc': 'Quy tắc Khóa/Mở khóa, Thông báo, Quy định chung về danh mục và Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Khóa / Mở khóa nguồn vốn'],
                            ['Mô tả', 'Đổi trạng thái nguồn vốn giữa Hoạt động và Khóa. Nguồn vốn đã Khóa vẫn nằm trong danh mục nhưng không sửa và không xóa được.'],
                            ['Tác nhân', 'Người dùng có quyền “%s”' % QUYEN],
                            ['Điều kiện ban đầu', 'Nguồn vốn cần đổi trạng thái đang có trong danh sách.'],
                            ['Dòng sự kiện chính', '1. Người dùng chọn Khóa (hoặc Mở khóa) ở cột Hành động.\n2. Hệ thống hiện hộp xác nhận “Khóa nguồn vốn” / “Mở khóa nguồn vốn” nêu rõ tên bản ghi.\n3. Người dùng xác nhận.\n4. Hệ thống đổi trạng thái, ghi lịch sử, báo “Khóa thành công” / “Mở khóa thành công”.'],
                            ['Dòng sự kiện phụ', '• Bấm Hủy → không thay đổi.\n• Sau khi Khóa, nút Sửa và Xóa biến mất, chỉ còn Mở khóa và Lịch sử.\n• Nguồn vốn đã bị người khác đổi trạng thái hoặc xóa → báo “%s”.' % MSG_CONFLICT]],
             'menu_them': ' => Khóa / Mở khóa',
             'anh': [('lock', 'Hộp xác nhận khóa nguồn vốn'), ('unlock', 'Hộp xác nhận mở khóa nguồn vốn'), ('rowmenu', 'Các nút ở cột Hành động')],
             'events': [['Chọn Khóa / Mở khóa', 'Click', 'After:\n– Hiện hộp xác nhận kèm tên bản ghi.'],
                        ['Xác nhận', 'Click', 'During:\n– Bản ghi đã ở trạng thái đích hoặc không còn tồn tại → báo trạng thái đã thay đổi, dừng.\nAfter:\n– Đổi trạng thái, KHÔNG xóa dữ liệu, ghi lịch sử, cập nhật cột Trạng thái và các nút.'],
                        ['Bấm Hủy', 'Click', 'After:\n– Đóng hộp, không thay đổi.']]},
            {'ten': 'Xem lịch sử thay đổi',
             'qtc': 'Quy tắc ghi lịch sử và hiển thị lịch sử. Chỉ bổ sung thông tin riêng của Danh mục nguồn vốn nếu có.',
             'gioi_thieu': [['Tên chức năng', 'Xem lịch sử thay đổi'],
                            ['Mô tả', 'Liệt kê các lần thay đổi của một nguồn vốn, kèm giá trị cũ → mới, người thực hiện và thời điểm.'],
                            ['Tác nhân', 'Người dùng có quyền “%s”' % QUYEN],
                            ['Dòng sự kiện chính', '1. Người dùng bấm Lịch sử ở cột Hành động, hoặc mở cửa sổ Xem nguồn vốn.\n2. Hệ thống mở cửa sổ “Lịch sử thay đổi: <tên>”, mốc mới nhất ở trên cùng.'],
                            ['Dòng sự kiện phụ', '• Bản ghi chưa có thao tác nào → “Chưa có lịch sử thao tác nào.”\n• Có bộ lọc theo loại hành động, người thực hiện, thời gian.']],
             'menu_them': ' => Lịch sử',
             'anh': [('history', 'Cửa sổ Lịch sử thay đổi của nguồn vốn')]},
            {'ten': 'Import file nguồn vốn', 'uc': 'uc_fr08',
             'qtc': 'Quy tắc Import file, Validate dữ liệu, Thông báo và Quy định chung về danh mục. Chỉ bổ sung mapping/validation riêng của Danh mục nguồn vốn.',
             'gioi_thieu': [['Tên chức năng', 'Import file nguồn vốn'],
                            ['Mô tả', 'Thêm nhiều nguồn vốn cùng lúc từ file Excel mẫu, có bước Validate trước khi ghi.'],
                            ['Tác nhân', 'Người dùng có quyền “%s”' % QUYEN],
                            ['Điều kiện ban đầu', 'Đang ở màn Danh mục nguồn vốn và đã chuẩn bị file theo mẫu.'],
                            ['Dòng sự kiện chính', '1. Bấm Import Excel.\n2. Bấm Tải file mẫu (Mau_import_nguon_von.xlsx), điền dữ liệu.\n3. Bấm Chọn file Excel rồi Load lên bảng.\n4. Bấm Validate; hệ thống kiểm tra từng dòng như quy tắc Thêm mới (mục 2.3), khóa dòng hợp lệ.\n5. Sửa dòng lỗi rồi Validate lại, hoặc bấm Bỏ dòng lỗi.\n6. Bấm Import; hệ thống ghi các dòng hợp lệ, báo “Import thành công N nguồn vốn.”, đóng cửa sổ và nạp lại danh sách.'],
                            ['Dòng sự kiện phụ', '• File không phải .xlsx/.xls → “Vui lòng chọn file .xlsx hoặc .xls”.\n• Quá 500 dòng → “File có X dòng dữ liệu, vượt quá giới hạn 500 dòng mỗi lần import. Vui lòng tách file và import nhiều lần.”\n• Còn dòng lỗi → nút Import không bấm được.'],
                            ['Yêu cầu đặc biệt', 'Validate không ghi dữ liệu. File mẫu chỉ có cột Tên nguồn vốn; bản ghi import luôn ở trạng thái Hoạt động, người tạo là người thực hiện.']],
             'menu_them': ' => Import Excel {icon:btn_import}',
             'ghi_chu_layout': 'Cửa sổ Import được mở ngay trên màn hình danh sách.',
             'anh': [('import_open', 'Cửa sổ Import nguồn vốn khi vừa mở'), ('import_loaded', 'Dữ liệu đã được load lên bảng xem trước'),
                     ('import_validated', 'Kết quả Validate — mỗi dòng lỗi nêu rõ lý do')],
             'bang_them': [('Quy tắc kiểm tra riêng của file Import', [['Cột', 'Quy tắc / thông báo lỗi'],
                            ['Tên nguồn vốn *', 'Bắt buộc (“Tên nguồn vốn không được để trống”), tối đa 255 ký tự (“Tên nguồn vốn tối đa 255 ký tự”), không trùng trong file (“Tên nguồn vốn bị trùng với dòng N trong file”), không trùng hệ thống (“Tên nguồn vốn đã tồn tại trong hệ thống”); so khớp không phân biệt hoa/thường.']], [1.2, 4])]},
            {'ten': 'Xuất danh sách ra Excel', 'uc': 'uc_fr09',
             'qtc': 'Quy tắc Excel và Cấu hình cột. Chỉ bổ sung danh sách trường được phép xuất riêng của Danh mục nguồn vốn.',
             'gioi_thieu': [['Tên chức năng', 'Xuất danh sách nguồn vốn ra Excel'],
                            ['Mô tả', 'Xuất kết quả đang lọc ra file Excel, cho phép chọn trường và thứ tự cột.'],
                            ['Tác nhân', 'Người dùng có quyền “%s”' % QUYEN],
                            ['Dòng sự kiện chính', '1. Bấm Xuất Excel.\n2. Hệ thống mở cửa sổ “Chọn trường xuất file”, tích sẵn đúng các cột đang hiển thị trên bảng.\n3. Người dùng tích chọn và kéo ☰ để sắp thứ tự.\n4. Bấm Xuất file; hệ thống tải danh_muc_nguon_von.xlsx theo đúng bộ lọc (từ khóa, Trạng thái), thứ tự sắp xếp và thứ tự trường, báo “Xuất Excel thành công”.'],
                            ['Dòng sự kiện phụ', '• Bỏ chọn hết trường → nút Xuất file không bấm được.\n• Bấm Đóng → không xuất gì.\n• Lỗi khi xuất → báo “Lỗi khi xuất Excel”.'],
                            ['Yêu cầu đặc biệt', 'File chứa toàn bộ kết quả lọc (tối đa 10,000 dòng), không giới hạn ở trang đang xem. Chỉ xuất Excel.']],
             'menu_them': ' => Xuất Excel {icon:btn_xuatexcel}',
             'anh': [('export', 'Cửa sổ Chọn trường xuất file')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
                    ['1', 'Danh sách trường', 'Checkbox chọn nhiều', 'Enable', 'Tích sẵn cột đang hiển thị', 'Tên nguồn vốn, Trạng thái, Người tạo, Ngày tạo, Người cập nhật, Ngày cập nhật. Kéo ☰ đổi thứ tự.'],
                    ['2', 'Nút Chọn tất cả / Bỏ chọn hết', 'Button', 'Enable', 'Hiển thị', 'Tích / bỏ tích toàn bộ.'],
                    ['3', 'Nút Xuất file', 'Button', 'Enable/Disable', 'Mờ khi chưa chọn trường', 'Sinh file và tải về.'],
                    ['4', 'Nút Đóng', 'Button', 'Enable', 'Hiển thị', 'Đóng cửa sổ.']],
             'ui_widths': [0.6, 1.5, 1, 0.8, 1.2, 2.6]},
            {'ten': 'Xem chi tiết nguồn vốn', 'uc': 'uc_fr10',
             'qtc': 'Màn Xem chi tiết và Phân quyền.',
             'gioi_thieu': [['Tên chức năng', 'Xem chi tiết nguồn vốn'],
                            ['Mô tả', 'Cửa sổ “Xem nguồn vốn” hiển thị Tên nguồn vốn và Trạng thái ở chế độ chỉ đọc, kèm khối Lịch sử.'],
                            ['Tác nhân', 'Người dùng có quyền “%s”' % QUYEN],
                            ['Dòng sự kiện chính', '1. Người dùng bấm tên nguồn vốn ở danh sách.\n2. Hệ thống mở cửa sổ Xem, chỉ có nút Đóng.']],
             'anh': [('detail', 'Cửa sổ Xem nguồn vốn ở chế độ chỉ đọc')]},
            {'ten': 'Tùy chỉnh cột hiển thị',
             'qtc': 'Tùy chỉnh cột.',
             'gioi_thieu': [['Tên chức năng', 'Tùy chỉnh cột hiển thị'],
                            ['Mô tả', 'Bật/tắt và sắp xếp thứ tự cột của bảng; cấu hình lưu riêng theo người dùng.'],
                            ['Yêu cầu đặc biệt', 'Cột STT, Tên nguồn vốn, Hành động bị khóa. Mặc định ẩn: Người cập nhật, Ngày cập nhật.']],
             'menu_them': ' => Cấu hình cột {icon:btn_cauhinhcot}',
             'anh': [('colcfg', 'Cửa sổ Tuỳ chỉnh cột')]},
        ],
        'quy_tac': [
            ('BR-01', 'Một quyền cho cả màn hình',
             ['Màn hình chỉ dùng một quyền “%s” cho cả xem và thao tác.' % QUYEN,
              'Không có quyền thì không thấy menu và máy chủ từ chối truy cập.'],
             ['Tất cả chức năng của màn hình']),
            ('BR-02', 'Ràng buộc trùng tên',
             ['Nguồn vốn không có mã; Tên nguồn vốn là trường định danh duy nhất.',
              'Tên nguồn vốn không được trùng trên toàn hệ thống (kể cả nguồn vốn đang Khóa), không phân biệt chữ hoa/chữ thường; khi sửa, bỏ qua chính bản ghi đang sửa. Thông báo khi trùng: “Tên nguồn vốn đã tồn tại”.',
              'Nguồn vốn đã xóa bị xóa hẳn nên tên đó dùng lại được.'],
             ['Thêm mới nguồn vốn', 'Chỉnh sửa nguồn vốn', 'Import file nguồn vốn']),
            ('BR-03', 'Điều kiện xóa nguồn vốn',
             ['Chỉ xóa được nguồn vốn đang Hoạt động VÀ chưa được sử dụng; ngược lại nút Xóa bị ẩn.',
              'Hiện chưa có chứng từ nào lưu nguồn vốn theo danh mục này, nên mọi nguồn vốn đang Hoạt động đều xóa được. Khi có chứng từ chọn nguồn vốn, nguồn vốn đã được chọn sẽ bị chặn với thông báo “%s”' % MSG_USED,
              'Máy chủ kiểm tra lại khi xóa: nguồn vốn đang Khóa → “%s”' % MSG_LOCKED,
              'Xóa là xóa hẳn bản ghi khỏi danh mục (trước 28/09/2026 là chuyển sang ngừng sử dụng).'],
             ['Xóa nguồn vốn']),
            ('BR-04', 'Khóa / Mở khóa và nguồn vốn đang Khóa',
             ['Nguồn vốn mới mặc định Hoạt động; có thể chọn Khóa ngay khi tạo.',
              'Khóa / Mở khóa bằng nút ở cột Hành động, hoặc đổi ô Trạng thái trong cửa sổ Sửa.',
              'Nguồn vốn đang Khóa vẫn hiện trong danh sách (lọc được bằng ô Trạng thái) nhưng không sửa, không xóa được (nút Sửa, Xóa bị ẩn); máy chủ chặn với thông báo “%s” Muốn sửa phải Mở khóa trước.' % MSG_LOCKED],
             ['Thêm mới nguồn vốn', 'Chỉnh sửa nguồn vốn', 'Xóa nguồn vốn', 'Khóa / Mở khóa nguồn vốn']),
            ('BR-05', 'Thao tác đồng thời',
             ['Hai người cùng Khóa / Mở khóa / Xóa một nguồn vốn: người bấm sau nhận thông báo “%s”, thao tác không được thực hiện lại.' % MSG_CONFLICT],
             ['Xóa nguồn vốn', 'Khóa / Mở khóa nguồn vốn']),
            ('BR-06', 'Giới hạn Import',
             ['Nguồn vốn nhập từ Excel luôn ở trạng thái Hoạt động (file mẫu không có cột Trạng thái).',
              'Mỗi lần nhập tối đa 500 dòng.',
              'Bước Validate chỉ kiểm tra, không ghi dữ liệu; báo trùng tên trong cùng file và trùng tên với hệ thống.'],
             ['Import file nguồn vốn']),
            ('BR-07', 'Ghi lịch sử thay đổi',
             ['Mọi thao tác Tạo mới, Thay đổi thông tin, Khóa, Mở khóa, Xóa đều ghi lịch sử kèm người thực hiện.',
              'Đổi Trạng thái ngay trong cửa sổ Sửa được ghi thành dòng “Thay đổi trạng thái” riêng.',
              'Lịch sử sắp xếp mới nhất ở trên cùng.'],
             ['Thêm mới nguồn vốn', 'Chỉnh sửa nguồn vốn', 'Xóa nguồn vốn', 'Khóa / Mở khóa nguồn vốn', 'Import file nguồn vốn', 'Xem lịch sử thay đổi']),
        ],
    },
}

# ---- Sửa tab testcase "20. DM nguồn vốn" — KẾ HOẠCH 28/09/2026 (đọc từ ref/testcase_tab.txt dump 28/09)
# Lượt 25/09 (Xuất Excel, Import) ĐÃ chạy lên sheet — không lặp lại.
MSG_OK_DEL = 'Đã xóa thành công'
CFG['tc'] = {
    'tab': '20. DM nguồn vốn',
    'hdr_row': 61,            # "VI. LỊCH SỬ THAY ĐỔI"
    'blocks': [
        # Ô Trạng thái khi thêm mới — cuối nhóm III. THÊM MỚI (R39..R44)
        {'after': 44, 'merge_from': 39, 'cases': [
            ('TC_03.007', 'Trạng thái mặc định khi thêm mới', 'P0', 'Đang ở cửa sổ thêm mới.',
             '1. Quan sát ô Trạng thái trước khi nhập gì', '',
             '- Ô Trạng thái đặt sẵn là Hoạt động\n- Chỉ có 2 giá trị: Hoạt động / Khóa'),
            ('TC_03.008', 'Thêm mới với Trạng thái Khóa', 'P1', 'Đang ở cửa sổ thêm mới.',
             '1. Nhập Tên nguồn vốn\n2. Đổi Trạng thái sang Khóa\n3. Bấm Lưu\n4. Xem dòng vừa tạo', 'Trạng thái: Khóa',
             '- Bản ghi được tạo với trạng thái Khóa\n- Dòng đó chỉ có nút Mở khóa và Lịch sử (không có Sửa, Xóa)'),
        ]},
        # Khóa trong cửa sổ Sửa / 423 — cuối nhóm IV. CHỈNH SỬA (R46..R55)
        {'after': 55, 'merge_from': 46, 'cases': [
            ('TC_04.011', 'Chuyển Trạng thái sang Khóa trong cửa sổ Sửa', 'P0', 'Nguồn vốn A đang Hoạt động.',
             '1. Mở cửa sổ sửa A\n2. Chọn Trạng thái = Khóa\n3. Bấm Lưu', 'Trạng thái: Khóa',
             '- Lưu thành công, báo "Cập nhật thành công"\n- Cột Trạng thái của A đổi thành Khóa, dòng A chỉ còn Mở khóa và Lịch sử\n- Lịch sử của A có mốc Thay đổi trạng thái Hoạt động → Khóa'),
            ('TC_04.012', 'Bấm Lưu khi nguồn vốn vừa bị người khác khóa', 'P1',
             'Tài khoản A và B cùng có quyền; nguồn vốn X đang Hoạt động.',
             '1. A mở cửa sổ sửa X, đổi Tên nguồn vốn\n2. B khóa X ở cột Hành động\n3. A bấm Lưu', '',
             '- A nhận thông báo "%s"\n- Thay đổi của A KHÔNG được ghi, X vẫn ở trạng thái Khóa' % MSG_LOCKED),
        ]},
        # Điều kiện xóa mới — cuối nhóm V. XÓA (R57..R60)
        {'after': 60, 'merge_from': 57, 'cases': [
            ('TC_05.005', 'Nguồn vốn đang Hoạt động có nút Xóa', 'P0', 'Nguồn vốn Z đang Hoạt động.',
             '1. Tìm dòng Z\n2. Quan sát cột Hành động', '',
             '- Có đủ 4 nút: Sửa và Xóa hiện thẳng; Khóa và Lịch sử nằm trong nút ba chấm "Hành động khác"\n- Hiện chưa có chứng từ nào dùng nguồn vốn nên mọi nguồn vốn Hoạt động đều có nút Xóa'),
            ('TC_05.006', 'Xóa nguồn vốn đã bị người khác xóa', 'P1',
             'Nguồn vốn X đang Hoạt động. Tài khoản A và B cùng mở danh sách.',
             '1. A và B cùng mở danh sách, thấy nguồn vốn X\n2. A xóa X\n3. B (chưa tải lại trang) xóa X', '',
             '2. A xóa thành công, X biến mất khỏi danh sách\n3. B nhận thông báo "%s"' % MSG_CONFLICT),
            ('TC_05.007', 'Xóa nguồn vốn vừa bị người khác khóa', 'P1',
             'Tài khoản A và B cùng mở danh sách; nguồn vốn X đang Hoạt động.',
             '1. B khóa X\n2. A (chưa tải lại trang) bấm thùng rác ở dòng X, bấm Xóa', '',
             '- A nhận thông báo "%s"\n- X KHÔNG bị xóa, vẫn ở trạng thái Khóa' % MSG_LOCKED),
        ]},
        # Khóa / Mở khóa chưa có case → nhóm MỚI sau case cuối (TC_08.018, R102)
        {'after': 102,
         'groups': [('IX', 'KHÓA / MỞ KHÓA (bổ sung 28/09/2026)', 9, [
             ('Hộp xác nhận Khóa nêu đúng tên nguồn vốn', 'P0', 'Nguồn vốn X đang Hoạt động.',
              '1. Ở cột Hành động của X chọn Khóa (nằm trong nút ba chấm "Hành động khác")\n2. Đọc hộp xác nhận', '',
              '- Hộp tiêu đề "Khóa nguồn vốn", câu "Bạn có chắc muốn khóa nguồn vốn "X"?"\n- Có hai nút Khóa và Hủy'),
             ('Khóa thành công', 'P0', 'Đang mở hộp xác nhận Khóa của nguồn vốn X.',
              '1. Bấm Khóa\n2. Quan sát dòng X', '',
              '- Báo "Khóa thành công"\n- Cột Trạng thái của X đổi thành Khóa, X VẪN nằm trong danh sách\n- Dòng X chỉ còn Mở khóa và Lịch sử (không còn Sửa, Xóa)'),
             ('Bấm Hủy thì không khóa', 'P1', 'Đang mở hộp xác nhận Khóa của nguồn vốn X.',
              '1. Bấm Hủy\n2. Xem lại dòng X', '',
              '- Hộp đóng, X vẫn Hoạt động, các nút giữ nguyên'),
             ('Mở khóa thành công', 'P0', 'Nguồn vốn X đang Khóa.',
              '1. Chọn Mở khóa ở dòng X\n2. Đọc hộp xác nhận rồi bấm Mở khóa', '',
              '- Hộp tiêu đề "Mở khóa nguồn vốn", câu "Bạn có chắc muốn mở khóa nguồn vốn "X"?"\n- Báo "Mở khóa thành công", cột Trạng thái đổi thành Hoạt động\n- Nút Sửa và Xóa hiện lại'),
             ('Nguồn vốn đang Khóa không sửa, không xóa được', 'P0', 'Nguồn vốn K đang Khóa.',
              '1. Tìm dòng K, quan sát cột Hành động\n2. Bấm vào tên của K', '',
              '- Không có bút chì và thùng rác, chỉ có Mở khóa và Lịch sử\n- Cửa sổ "Xem nguồn vốn" vẫn mở được ở chế độ chỉ đọc, hiện Trạng thái Khóa'),
             ('Hai người cùng khóa một nguồn vốn', 'P1', 'Tài khoản A và B cùng mở danh sách; nguồn vốn X đang Hoạt động.',
              '1. A khóa X thành công\n2. B (chưa tải lại trang) chọn Khóa ở dòng X, bấm Khóa', '',
              '- B nhận thông báo "%s"\n- Lịch sử của X chỉ có MỘT mốc Khóa' % MSG_CONFLICT),
             ('Khóa / Mở khóa được ghi lịch sử', 'P0', 'Vừa khóa rồi mở khóa nguồn vốn X.',
              '1. Mở Lịch sử của X\n2. Đọc 2 dòng trên cùng', '',
              '- Có 2 mốc loại Thay đổi trạng thái: Hoạt động → Khóa và Khóa → Hoạt động\n- Kèm tên người thực hiện và thời điểm'),
         ])]},
    ],
    'edits': [
        ('B3', '- Toàn bộ nguồn vốn trong danh mục, gồm CẢ bản ghi Hoạt động lẫn bản ghi đã Khóa.\n- Bộ lọc Trạng thái để trống thì hiện cả hai nhóm.'),
        ('B4', '- Không ẩn bản ghi nào theo mặc định. Nguồn vốn đã Khóa vẫn nằm trong danh mục.\n- Xóa là xóa HẲN: nguồn vốn đã xóa không còn trong hệ thống (trước đây là chuyển sang ngừng sử dụng).'),
        ('B6', '- Danh mục phẳng, không phân cấp cha con.\n- Mỗi nguồn vốn là một bản ghi độc lập.\n- Nguồn vốn đã được chọn ở chứng từ thì coi là "đã sử dụng" và không xóa được (vẫn Khóa được). Hiện chưa có chứng từ nào lưu nguồn vốn theo danh mục này, nên mọi nguồn vốn đang Hoạt động đều xóa được.'),
        ('B8', 'Màn hình dùng đúng MỘT quyền: "Quản lý danh mục nguồn vốn".\n- Có quyền: mở được màn hình và thực hiện đầy đủ Thêm mới, Chỉnh sửa, Xóa, Khóa, Mở khóa, Xem lịch sử.\n- Không có quyền: mục menu không hiển thị; truy cập thẳng đường dẫn thì hệ thống từ chối và báo không có quyền.\n Màn hình KHÔNG tách quyền xem riêng, cũng không phân quyền theo cấp công ty / phòng ban / bộ phận.'),
        ('B10', 'Các bẫy dễ sai nhất của màn này, QA đọc trước khi test:\n- Màn hình chỉ có MỘT quyền "Quản lý danh mục nguồn vốn" cho cả xem lẫn sửa. Không có quyền thì không vào được màn hình, chứ không phải vào được mà nút bị mờ.\n- Cửa sổ nhập liệu chỉ có 2 nút: Lưu và Đóng. Màn này KHÔNG có nút "Lưu và tiếp tục" như nhóm danh mục địa lý.\n- Cửa sổ nhập liệu có 2 ô: Tên nguồn vốn và Trạng thái (mặc định Hoạt động). Không có mã, không có ghi chú.\n- Khu vực lọc gồm ô tìm kiếm nhanh và ô Trạng thái; không có nút Tìm kiếm nâng cao.\n- Xóa là xóa HẲN (không còn là ngừng sử dụng). Nút Xóa chỉ hiện với nguồn vốn đang Hoạt động và chưa được sử dụng — hiện chưa có chứng từ nào dùng nguồn vốn nên mọi nguồn vốn Hoạt động đều có nút Xóa.\n- Có nút Khóa / Mở khóa ngay trên cột Hành động (dòng đủ 4 nút thì Khóa và Lịch sử nằm trong nút ba chấm).\n- Nguồn vốn đang Khóa KHÔNG có nút Sửa, Xóa — chỉ còn Mở khóa và Lịch sử; máy chủ cũng chặn cập nhật với câu "' + MSG_LOCKED + '"\n- Trạng thái mặc định của bản ghi mới là Hoạt động.'),
        ('I25', '- Có đủ các cột: STT, Tên nguồn vốn, Người tạo, Ngày tạo, Trạng thái, Hành động\n- Hai cột Người cập nhật, Ngày cập nhật mặc định ẩn, KHÔNG xuất hiện khi chưa chỉnh cấu hình cột'),
        ('D31', 'Cột Trạng thái phân biệt Hoạt động và Khóa'),
        ('F31', 'Có ít nhất 1 nguồn vốn Hoạt động và 1 nguồn vốn đã Khóa.'),
        ('G31', '1. Mở màn hình\n2. Đọc cột Trạng thái của cả hai bản ghi\n3. Mở cửa sổ Tạo mới'),
        ('I31', '- Hai trạng thái hiện đúng chữ Hoạt động / Khóa và khác màu rõ ràng\n- Cả hai đều nằm trong danh sách\n- Cửa sổ Tạo mới có ô Trạng thái, mặc định Hoạt động'),
        ('D37', 'Lọc theo Trạng thái'),
        ('F37', 'Có nguồn vốn Hoạt động và nguồn vốn Khóa.'),
        ('G37', '1. Chọn ô Trạng thái = Khóa\n2. Quan sát bảng\n3. Bấm x để bỏ chọn Trạng thái'),
        ('H37', 'Trạng thái: Khóa'),
        ('I37', '- Lọc ngay khi chọn, bảng về trang 1, chỉ còn nguồn vốn Khóa\n- Bỏ chọn: hiện lại cả hai trạng thái\n- Khu vực lọc chỉ có ô tìm kiếm nhanh và ô Trạng thái (nhãn nổi), không có nút Tìm kiếm nâng cao'),
        ('I39', '- Cửa sổ mở với tiêu đề "Tạo nguồn vốn"\n- Có 2 ô: Tên nguồn vốn, Trạng thái (mặc định Hoạt động)\n- Chỉ có 2 nút: Lưu và Đóng'),
        ('F46', 'Có nguồn vốn đang Hoạt động trong danh sách (nguồn vốn đang Khóa không có nút Sửa).'),
        ('F59', 'Nguồn vốn X đang Hoạt động (hiện chưa có chứng từ nào dùng nguồn vốn nên X xóa được).'),
        ('I59', '- Thông báo "%s"\n- Bản ghi X biến mất khỏi danh sách\n- Lọc Trạng thái = Khóa cũng KHÔNG thấy X (xóa hẳn, không phải chuyển sang Khóa)' % MSG_OK_DEL),
        ('D60', 'Xóa là xóa hẳn — tên đã xóa dùng lại được'),
        ('F60', 'Vừa xóa nguồn vốn tên X.'),
        ('G60', '1. Tìm X ở ô tìm kiếm nhanh, bỏ trống Trạng thái\n2. Bấm Tạo mới, nhập đúng tên X, bấm Lưu'),
        ('I60', '- Không còn X ở bất kỳ trạng thái nào\n- Tạo mới trùng tên X lưu thành công, KHÔNG báo "Tên nguồn vốn đã tồn tại"'),
        ('I75', '- Mở cửa sổ “Chọn trường xuất file”\n- Có đủ các trường: Tên nguồn vốn, Trạng thái, Người tạo, Ngày tạo, Người cập nhật, Ngày cập nhật\n- Tích sẵn đúng các cột đang hiển thị trên bảng (Người cập nhật, Ngày cập nhật mặc định ẩn nên không tích sẵn)\n- Dòng cuối ghi “Đang chọn a/b trường”'),
        ('F77', 'Đang lọc danh sách còn vài nguồn vốn (theo từ khóa và/hoặc Trạng thái).'),
        ('I77', '- File chỉ chứa các nguồn vốn khớp bộ lọc (kể cả bộ lọc Trạng thái)\n- Cột Trạng thái trong file ghi đúng Hoạt động / Khóa\n- Số dòng bằng tổng số bản ghi ở cuối bảng'),
    ],
    'clear_k': [25, 31, 37, 39, 46, 59, 60, 75, 77],
}

CFG['loi_code'] = [
    'Nguồn vốn: hiện KHÔNG có nơi nào lưu id nguồn vốn (SourceCapital::USAGE_REFERENCES rỗng; các cột source_of_capital ở phân tích dự án / hạch toán hỗ trợ / hợp đồng quyết toán lưu CHỮ) → cờ “đã sử dụng” luôn sai, mọi nguồn vốn Hoạt động đều xóa hẳn được. Khi có chứng từ chọn nguồn vốn theo danh mục phải bổ sung vào USAGE_REFERENCES, nếu không sẽ xóa mất nguồn vốn đang dùng.',
    'Import: số dòng trong câu “Tên nguồn vốn bị trùng với dòng N trong file” lệch 1 — BE tính N = index + 2 (coi dòng 1 là tiêu đề) nhưng file mẫu có thêm dòng mô tả ở hàng 2, dữ liệu bắt đầu từ hàng 3 → N báo nhỏ hơn số hàng thật 1 đơn vị (SourceCapitalService::validateRows). Tài liệu tả chung “dòng N”.',
    'Form Tạo/Sửa: SourceCapitalRequest đã có max:255 nhưng FE không có rule max → chỉ báo lỗi sau khi bấm Lưu (lỗi 422 từ máy chủ), không báo ngay khi gõ. Cần kiểm câu hiển thị trên màn hình.',
]

CFG['tc_ngoai_pham_vi'] = [
    'R10 (bullet giữ nguyên) + R39 TC_03.001 (dòng nút giữ nguyên): ghi “chỉ có 2 nút Lưu và Đóng, KHÔNG có Lưu và tiếp tục” — hiện cửa sổ Tạo có 3 nút Lưu / Lưu và tiếp tục / Đóng.',
    'R48 TC_04.003 “KHÔNG đổi tên, chỉ đổi ô khác” — nay có thêm ô Trạng thái nên chạy được, nhưng đổi Trạng thái sẽ ghi mốc Thay đổi trạng thái; R55 TC_04.010 trùng nội dung R52 TC_04.007.',
    'R21, R22: truy cập thẳng khi không có quyền thì ra trang 404 — chưa đối chiếu lại.',
    'Thiếu case: Xem chi tiết (bấm tên mở cửa sổ Xem nguồn vốn), Lưu và tiếp tục, Tùy chỉnh cột (cột Người cập nhật / Ngày cập nhật mới).',
]

# ---- SRS: "Mô tả chi tiết giao diện" + "Danh sách event và xử lý event" cho các FR sau Thêm mới
# (bổ sung 28/09/2026 theo SRS_UI_EVENTS_BRIEF.md; khuôn cột bám SRS Danh mục quốc gia).
# Nguồn: pages/finance/source-capitals (index + Modal), components/modal/{export-fields-modal, column-customization-modal,
#   CatalogHistoryModal}.vue, components/assign/SystemInfoSection.vue, components/V2BaseImport{Modal,Toolbar,Table}.vue,
#   utils/mixins/CatalogImportMixin.js; BE Controller/Service + middleware recordNotLocked, importRowLimit.
_SRS_UI_EVENTS = {'Chỉnh sửa nguồn vốn': {'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Phạm vi', 'Bắt buộc', 'Giá trị ban đầu', 'Mô tả'],
                                ['1',
                                 'Tên nguồn vốn',
                                 'Textbox',
                                 'Enable',
                                 'Chuỗi ký tự',
                                 'Có',
                                 'Dữ liệu hiện tại',
                                 'Duy nhất toàn hệ thống, không phân biệt hoa/thường. Bỏ trống báo “Bắt buộc phải nhập”; trùng với nguồn vốn khác '
                                 'báo “Tên nguồn vốn đã tồn tại”. Giữ nguyên tên của chính bản ghi thì không báo trùng.'],
                                ['2',
                                 'Trạng thái',
                                 'Dropdown',
                                 'Enable',
                                 'Hoạt động / Khóa',
                                 'Không',
                                 'Dữ liệu hiện tại (Hoạt động)',
                                 'Chọn Khóa rồi Lưu để khóa ngay trong cửa sổ Sửa — chọn được kể cả khi nguồn vốn đã được sử dụng.'],
                                ['3',
                                 'Nút Lưu',
                                 'Button',
                                 'Enable',
                                 '–',
                                 '–',
                                 'Hiển thị',
                                 'Ghi thay đổi rồi đóng cửa sổ, báo “Cập nhật thành công”.'],
                                ['4',
                                 'Nút Đóng',
                                 'Button',
                                 'Enable',
                                 '–',
                                 '–',
                                 'Hiển thị',
                                 'Hủy bỏ, không ghi gì. Đã sửa dở thì hỏi “Thông tin chưa lưu” — “Bạn có thông tin chưa lưu. Có chắc chắn muốn '
                                 'thoát?” (Thoát / Ở lại). Cửa sổ Sửa KHÔNG có nút Lưu và tiếp tục.']],
                         'ui_widths': [0.5, 1.2, 0.8, 0.6, 1.0, 0.6, 0.9, 2.4],
                         'events': [['Bấm biểu tượng bút chì',
                                     'Click',
                                     'Before:\n'
                                     '– Nguồn vốn đang Khóa thì nút không hiển thị.\n'
                                     'After:\n'
                                     '– Mở cửa sổ “Sửa nguồn vốn” với dữ liệu hiện tại đã điền sẵn.'],
                                    ['Bấm Lưu',
                                     'Click',
                                     'Before:\n'
                                     '– Nguồn vốn vừa bị người khác khóa → máy chủ từ chối, báo “Bản ghi đang bị khoá, vui lòng mở khoá trước khi '
                                     'cập nhật.”\n'
                                     'During:\n'
                                     '– Tên nguồn vốn để trống → “Bắt buộc phải nhập”.\n'
                                     '– Tên nguồn vốn trùng với nguồn vốn khác (không phân biệt hoa/thường) → “Tên nguồn vốn đã tồn tại”.\n'
                                     '– Bỏ qua kiểm tra trùng đối với chính bản ghi đang sửa.\n'
                                     '– Có lỗi → báo đỏ dưới ô + “Vui lòng kiểm tra lại dữ liệu nhập”, cửa sổ không đóng, không thực hiện After.\n'
                                     'After:\n'
                                     '– Ghi thay đổi, ghi lịch sử “Thay đổi thông tin” (đổi Trạng thái ghi mốc Khóa / Mở khóa riêng).\n'
                                     '– Đóng cửa sổ, nạp lại danh sách, báo “Cập nhật thành công”.'],
                                    ['Bấm Đóng / biểu tượng X',
                                     'Click',
                                     'After:\n'
                                     '– Chưa sửa gì → đóng cửa sổ.\n'
                                     '– Đã sửa → hỏi “Thông tin chưa lưu” — “Bạn có thông tin chưa lưu. Có chắc chắn muốn thoát?” (Thoát / Ở '
                                     'lại).']]},
 'Xóa nguồn vốn': {'ui': [['STT', 'Tên đối tượng', 'Loại', 'Mô tả'],
                          ['1',
                           'Biểu tượng thùng rác',
                           'Icon Button',
                           'Nằm ở cột Hành động. Chỉ hiển thị khi nguồn vốn đang Hoạt động VÀ chưa được sử dụng ở chứng từ nào.'],
                          ['2', 'Tiêu đề hộp xác nhận', 'Label', '“Xóa nguồn vốn”.'],
                          ['3',
                           'Nội dung hộp xác nhận',
                           'Label',
                           '“Bạn có chắc muốn xóa nguồn vốn "<tên nguồn vốn>"?” — nêu rõ tên bản ghi để tránh xóa nhầm dòng.'],
                          ['4', 'Nút Xóa', 'Button', 'Xác nhận xóa hẳn bản ghi.'],
                          ['5', 'Nút Hủy', 'Button', 'Đóng hộp, không làm gì.']],
                   'ui_widths': [0.6, 1.6, 1.0, 3.8],
                   'events': [['Bấm biểu tượng thùng rác',
                               'Click',
                               'Before:\n'
                               '– Chỉ hiển thị khi nguồn vốn đang Hoạt động và chưa được sử dụng.\n'
                               'After:\n'
                               '– Hiện hộp xác nhận “Xóa nguồn vốn” kèm tên bản ghi.'],
                              ['Bấm Xóa trong hộp xác nhận',
                               'Click',
                               'During:\n'
                               '– Bản ghi không còn tồn tại (vừa bị người khác xóa) → “Trạng thái đã bị thay đổi. Vui lòng load lại trang”.\n'
                               '– Bản ghi đang Khóa → “Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.”\n'
                               '– Bản ghi đã được sử dụng → “Nguồn vốn đang được sử dụng, không thể xóa.”\n'
                               '– Có lỗi → dừng, không xóa.\n'
                               'After:\n'
                               '– Xóa HẲN bản ghi khỏi danh mục, ghi lịch sử Xóa.\n'
                               '– Đóng hộp, nạp lại danh sách, báo “Đã xóa thành công”.'],
                              ['Bấm Hủy / biểu tượng X', 'Click', 'After:\n– Đóng hộp xác nhận, không thay đổi gì.']]},
 'Khóa / Mở khóa nguồn vốn': {'ui': [['STT', 'Tên đối tượng', 'Loại', 'Mô tả'],
                                     ['1',
                                      'Nút ba chấm “Hành động khác”',
                                      'Icon Button',
                                      'Xuất hiện khi dòng có từ 4 nút trở lên: 2 nút đầu hiện thẳng, các nút còn lại (Khóa / Mở khóa, Lịch sử) nằm '
                                      'trong nút này.'],
                                     ['2',
                                      'Mục Khóa / Mở khóa',
                                      'Button',
                                      'Nhãn đổi theo trạng thái: nguồn vốn đang Hoạt động hiện “Khóa”, đang Khóa hiện “Mở khóa”. Có cả khi nguồn vốn '
                                      'đã được sử dụng.'],
                                     ['3', 'Tiêu đề hộp xác nhận', 'Label', '“Khóa nguồn vốn” hoặc “Mở khóa nguồn vốn”.'],
                                     ['4',
                                      'Nội dung hộp xác nhận',
                                      'Label',
                                      '“Bạn có chắc muốn khóa nguồn vốn "<tên>"?” / “Bạn có chắc muốn mở khóa nguồn vốn "<tên>"?”.'],
                                     ['5', 'Nút Khóa / Mở khóa', 'Button', 'Xác nhận thực hiện.'],
                                     ['6', 'Nút Hủy', 'Button', 'Đóng hộp, không làm gì.'],
                                     ['7', 'Cột Trạng thái', 'Badge', 'Hoạt động hoặc Khóa, hai màu khác nhau.']],
                              'ui_widths': [0.6, 1.6, 1.0, 3.8],
                              'events': [['Bấm nút ba chấm', 'Click', 'After:\n– Mở menu các thao tác còn lại của dòng (Khóa / Mở khóa, Lịch sử).'],
                                         ['Chọn Khóa hoặc Mở khóa',
                                          'Click',
                                          'After:\n– Hiện hộp xác nhận “Khóa nguồn vốn” / “Mở khóa nguồn vốn” kèm tên bản ghi.'],
                                         ['Xác nhận trong hộp',
                                          'Click',
                                          'During:\n'
                                          '– Bản ghi đã ở trạng thái đích hoặc không còn tồn tại (người khác vừa thao tác) → “Trạng thái đã bị thay '
                                          'đổi. Vui lòng load lại trang”, dừng xử lý.\n'
                                          'After:\n'
                                          '– Đổi trạng thái, KHÔNG xóa dữ liệu, ghi lịch sử (Khóa / Mở khóa).\n'
                                          '– Báo “Khóa thành công” / “Mở khóa thành công”, nạp lại danh sách.\n'
                                          '– Sau khi Khóa: nút Sửa, Xóa của dòng biến mất, chỉ còn Mở khóa và Lịch sử. Sau khi Mở khóa: nút Sửa hiện '
                                          'lại (Xóa hiện lại nếu nguồn vốn chưa được sử dụng).'],
                                         ['Bấm Hủy / biểu tượng X', 'Click', 'After:\n– Đóng hộp xác nhận, trạng thái không đổi.']]},
 'Xem lịch sử thay đổi': {'ui': [['STT', 'Tên đối tượng', 'Loại', 'Giá trị ban đầu', 'Mô tả'],
                                 ['1',
                                  'Mục Lịch sử',
                                  'Button',
                                  'Hiển thị',
                                  'Ở cột Hành động (trong nút ba chấm khi dòng có nhiều nút). Hiện với mọi nguồn vốn, kể cả đang Khóa.'],
                                 ['2', 'Tiêu đề cửa sổ', 'Label', 'Lịch sử thay đổi', '“Lịch sử thay đổi: <tên nguồn vốn>”.'],
                                 ['3', 'Nút Bộ lọc', 'Button', 'Hiển thị', 'Mở / thu gọn vùng lọc, ghim ở đầu cửa sổ.'],
                                 ['4',
                                  'Loại hành động',
                                  'Dropdown',
                                  'Tất cả loại hành động',
                                  'Tạo mới / Thay đổi thông tin / Thay đổi trạng thái. Chọn là lọc ngay.'],
                                 ['5', 'Người thực hiện', 'Dropdown', 'Tất cả người thực hiện', 'Chọn là lọc ngay.'],
                                 ['6', 'Từ ngày / Đến ngày', 'Datepicker', 'Trống', 'Định dạng dd/mm/yyyy. Chọn là lọc ngay.'],
                                 ['7', 'Nút Làm mới (trong vùng lọc)', 'Button', 'Hiển thị', 'Xóa hết tiêu chí lọc của cửa sổ.'],
                                 ['8',
                                  'Dòng thời gian thay đổi',
                                  'Text',
                                  'Theo dữ liệu',
                                  '- Thời điểm: dd/mm/yyyy hh:mm.\n'
                                  '- Loại thay đổi: Tạo mới, Thay đổi thông tin, Khóa, Mở khóa.\n'
                                  '- Người thực hiện: tên kèm phòng ban.\n'
                                  '- Giá trị cũ → giá trị mới cho từng trường đã đổi.\n'
                                  'Mốc mới nhất ở trên cùng.'],
                                 ['9',
                                  'Trạng thái rỗng',
                                  'Label',
                                  'Ẩn',
                                  '“Chưa có lịch sử thao tác nào.” khi bản ghi chưa có thao tác; “Không có lịch sử phù hợp bộ lọc.” khi lọc không ra '
                                  'kết quả.'],
                                 ['10', 'Nút Đóng', 'Button', 'Hiển thị', 'Đóng cửa sổ.']],
                          'ui_widths': [0.6, 1.5, 0.9, 1.2, 3.0],
                          'events': [['Chọn Lịch sử ở cột Hành động',
                                      'Click',
                                      'After:\n– Mở cửa sổ “Lịch sử thay đổi: <tên nguồn vốn>”, nạp danh sách thay đổi theo thứ tự mới nhất trước.'],
                                     ['Bấm Bộ lọc', 'Click', 'After:\n– Mở / thu gọn vùng lọc.'],
                                     ['Đổi Loại hành động / Người thực hiện / Từ ngày / Đến ngày',
                                      'Change',
                                      'After:\n– Lọc ngay danh sách thay đổi theo đồng thời các tiêu chí.'],
                                     ['Bấm Làm mới trong vùng lọc', 'Click', 'After:\n– Xóa hết tiêu chí, hiện lại toàn bộ lịch sử.'],
                                     ['Bấm Đóng / biểu tượng X', 'Click', 'After:\n– Đóng cửa sổ; danh sách phía sau giữ nguyên bộ lọc và trang.']]},
 'Import file nguồn vốn': {'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Bắt buộc', 'Giá trị ban đầu', 'Mô tả'],
                                  ['1',
                                   'Nút Import Excel',
                                   'Button',
                                   'Enable',
                                   '–',
                                   'Hiển thị',
                                   'Trên thanh công cụ của bảng danh sách. Mở cửa sổ “Import nguồn vốn” (dòng phụ “Import từ Excel • Validate xong '
                                   'dòng hợp lệ sẽ bị khoá”).'],
                                  ['2',
                                   'Nút Chọn file Excel',
                                   'Button',
                                   'Enable',
                                   'Có',
                                   'Chưa chọn file',
                                   'Chọn file .xlsx / .xls từ máy; tên file hiện cạnh nút.'],
                                  ['3',
                                   'Nút Tải file mẫu',
                                   'Button',
                                   'Enable',
                                   '–',
                                   'Hiển thị',
                                   'Tải Mau_import_nguon_von.xlsx, gồm các cột STT, Tên nguồn vốn * (cột có * là bắt buộc).'],
                                  ['4',
                                   'Nút Load lên bảng',
                                   'Button',
                                   'Enable / Disable',
                                   '–',
                                   'Mờ khi chưa chọn file',
                                   'Đọc file và đổ dữ liệu lên bảng xem trước.'],
                                  ['5',
                                   'Nút Validate',
                                   'Button',
                                   'Enable / Disable',
                                   '–',
                                   'Mờ khi bảng chưa có dòng',
                                   'Kiểm tra từng dòng; dòng hợp lệ bị khoá lại không sửa được.'],
                                  ['6',
                                   'Nút Import',
                                   'Button',
                                   'Enable / Disable',
                                   '–',
                                   'Mờ',
                                   'Chỉ bấm được khi đã Validate, KHÔNG còn dòng lỗi và có ít nhất 1 dòng hợp lệ.'],
                                  ['7',
                                   'Ô Tổng / Hợp lệ / Lỗi',
                                   'Label',
                                   'Read-only',
                                   '–',
                                   'Tổng: 0',
                                   'Sau khi Load hiện “Tổng”; sau khi Validate hiện thêm “Hợp lệ” và “Lỗi”. Có dòng đã sửa sau Validate hiện “Có '
                                   'dòng đã sửa (cần validate lại)”.'],
                                  ['8',
                                   'Bảng xem trước',
                                   'Table/Grid',
                                   'Enable',
                                   '–',
                                   'Trống',
                                   'Các cột như file mẫu. Sửa trực tiếp được ở dòng lỗi.'],
                                  ['9',
                                   'Thông báo lỗi theo dòng',
                                   'Label',
                                   'Hiển thị',
                                   '–',
                                   'Ẩn',
                                   'Dòng lỗi viền đỏ, lý do ghi ngay dưới dòng. Hết lỗi khi sửa đúng rồi Validate lại.'],
                                  ['10', 'Nút Bỏ dòng lỗi', 'Button', 'Enable', '–', 'Hiển thị', 'Loại toàn bộ dòng đang lỗi khỏi bảng xem trước.'],
                                  ['11',
                                   'Nút Xoá trạng thái validate',
                                   'Button',
                                   'Enable',
                                   '–',
                                   'Hiển thị',
                                   'Bỏ khoá các dòng hợp lệ và bỏ thông báo lỗi validate.'],
                                  ['12',
                                   'Nút Làm mới',
                                   'Button',
                                   'Enable',
                                   '–',
                                   'Hiển thị',
                                   'Xóa file đã chọn và toàn bộ dữ liệu trên bảng, về trạng thái vừa mở.'],
                                  ['13', 'Nút Đóng', 'Button', 'Enable', '–', 'Hiển thị', 'Đóng cửa sổ, không ghi gì.']],
                           'ui_widths': [0.5, 1.4, 0.8, 0.8, 0.6, 1.0, 2.6],
                           'events': [['Bấm Import Excel', 'Click', 'After:\n– Mở cửa sổ “Import nguồn vốn” ở trạng thái rỗng.'],
                                      ['Bấm Tải file mẫu',
                                       'Click',
                                       'After:\n– Tải file Mau_import_nguon_von.xlsx về máy.\n– Lỗi khi tạo file → “Lỗi khi tạo file mẫu”.'],
                                      ['Bấm Chọn file Excel',
                                       'Click',
                                       'During:\n'
                                       '– File không phải .xlsx / .xls → “Vui lòng chọn file .xlsx hoặc .xls”.\n'
                                       'After:\n'
                                       '– Hiện tên file cạnh nút, nút Load lên bảng sáng lên.'],
                                      ['Bấm Load lên bảng',
                                       'Click',
                                       'During:\n'
                                       '– File không đọc được → “Không đọc được file Excel.”; không có dòng dữ liệu → “Không có dòng dữ liệu hợp '
                                       'lệ.”.\n'
                                       'After:\n'
                                       '– Đổ dữ liệu lên bảng xem trước, cập nhật ô Tổng.'],
                                      ['Bấm Validate',
                                       'Click',
                                       'During:\n'
                                       '– Quá 500 dòng → “File có X dòng dữ liệu, vượt quá giới hạn 500 dòng mỗi lần import. Vui lòng tách file và '
                                       'import nhiều lần.”\n'
                                       '– Kiểm tra từng dòng theo quy tắc Thêm mới (mục 2.3) và bảng quy tắc kiểm tra riêng của file Import.\n'
                                       'After:\n'
                                       '– Dòng lỗi tô đỏ kèm lý do, dòng hợp lệ bị khoá, hiện số Hợp lệ / Lỗi; báo “Validate xong: N hợp lệ, M không '
                                       'hợp lệ” (hoặc “Validate thành công”).\n'
                                       '– KHÔNG ghi bản ghi nào ở bước này.'],
                                      ['Sửa ô ở dòng lỗi',
                                       'Change',
                                       'After:\n– Dòng được đánh dấu đã sửa, cần Validate lại; nút Import mờ cho tới khi Validate lại hết lỗi.'],
                                      ['Bấm Bỏ dòng lỗi',
                                       'Click',
                                       'Before:\n'
                                       '– Chưa Validate → “Hãy Validate trước rồi mới bỏ dòng lỗi.”\n'
                                       'After:\n'
                                       '– Loại các dòng lỗi khỏi bảng; nút Import sáng lên nếu còn dòng hợp lệ.'],
                                      ['Bấm Import',
                                       'Click',
                                       'During:\n'
                                       '– Máy chủ kiểm tra lại toàn bộ dòng gửi lên, bỏ qua dòng lỗi; không còn dòng hợp lệ → “Không có dòng nào hợp '
                                       'lệ để import”.\n'
                                       'After:\n'
                                       '– Ghi các dòng hợp lệ thành nguồn vốn mới, người tạo là người thực hiện, ghi lịch sử Tạo mới.\n'
                                       '– Báo “Import thành công N nguồn vốn.” (có dòng thất bại thì “Import thành công a/b nguồn vốn. c dòng thất '
                                       'bại.”), đóng cửa sổ và nạp lại danh sách.'],
                                      ['Bấm Làm mới', 'Click', 'After:\n– Xóa file và dữ liệu trên bảng, về trạng thái vừa mở.'],
                                      ['Bấm Đóng / biểu tượng X', 'Click', 'After:\n– Đóng cửa sổ, không ghi gì.']]},
 'Xuất danh sách ra Excel': {'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
                                    ['1',
                                     'Nút Xuất Excel',
                                     'Button',
                                     'Enable',
                                     'Hiển thị',
                                     'Trên thanh công cụ của bảng danh sách. Mở cửa sổ “Chọn trường xuất file”.'],
                                    ['2',
                                     'Danh sách trường',
                                     'Checkbox chọn nhiều',
                                     'Enable',
                                     'Tích sẵn đúng các cột đang hiển thị trên bảng, xếp lên đầu theo thứ tự trên bảng',
                                     '6 trường: Tên nguồn vốn, Trạng thái, Người tạo, Ngày tạo, Người cập nhật, Ngày cập nhật. Kéo biểu tượng ☰ để '
                                     'đổi thứ tự cột trong file.'],
                                    ['3', 'Nút Chọn tất cả', 'Button', 'Enable', 'Hiển thị', 'Tích hết toàn bộ trường.'],
                                    ['4', 'Nút Bỏ chọn hết', 'Button', 'Enable', 'Hiển thị', 'Bỏ tích toàn bộ trường.'],
                                    ['5', 'Dòng đếm', 'Label', 'Read-only', 'Đang chọn x/6 trường', 'Cập nhật theo số trường đang tích.'],
                                    ['6',
                                     'Nút Xuất file',
                                     'Button',
                                     'Enable / Disable',
                                     'Mờ khi chưa chọn trường nào',
                                     'Sinh file Excel và tải về máy.'],
                                    ['7', 'Nút Đóng', 'Button', 'Enable', 'Hiển thị', 'Đóng cửa sổ, không xuất.']],
                             'ui_widths': [0.5, 1.4, 1.0, 0.8, 1.6, 2.7],
                             'events': [['Bấm Xuất Excel',
                                         'Click',
                                         'After:\n– Mở cửa sổ “Chọn trường xuất file”, tích sẵn đúng các cột đang hiển thị trên bảng.'],
                                        ['Tích / bỏ tích, kéo ☰ đổi thứ tự trường',
                                         'Change',
                                         'During:\n– Thứ tự trường trong cửa sổ là thứ tự cột trong file.\n– Bỏ chọn hết → nút Xuất file mờ đi.'],
                                        ['Bấm Xuất file',
                                         'Click',
                                         'During:\n'
                                         '– Lấy dữ liệu theo ĐÚNG bộ lọc, từ khóa và thứ tự sắp xếp đang áp dụng; toàn bộ kết quả (tối đa 10,000 '
                                         'dòng), không chỉ trang đang xem.\n'
                                         'After:\n'
                                         '– Tải file danh_muc_nguon_von.xlsx về máy, báo “Xuất Excel thành công”.\n'
                                         '– Lỗi → “Lỗi khi xuất Excel”.'],
                                        ['Bấm Đóng / biểu tượng X',
                                         'Click',
                                         'After:\n– Đóng cửa sổ, không xuất gì. Lần mở sau tích lại theo các cột đang hiển thị.']]},
 'Xem chi tiết nguồn vốn': {'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
                                   ['1',
                                    'Tên nguồn vốn ở cột Tên nguồn vốn',
                                    'Link',
                                    'Enable',
                                    'Hiển thị',
                                    'Bấm vào để mở cửa sổ “Xem nguồn vốn”. Bấm được với mọi nguồn vốn, kể cả đang Khóa.'],
                                   ['2', 'Tiêu đề cửa sổ', 'Label', 'Read-only', 'Xem nguồn vốn', ''],
                                   ['3', 'Tên nguồn vốn', 'Textbox', 'Read-only', 'Dữ liệu hiện tại', 'Không gõ được.'],
                                   ['4', 'Trạng thái', 'Dropdown', 'Read-only', 'Dữ liệu hiện tại', 'Hoạt động hoặc Khóa. Không đổi được.'],
                                   ['5',
                                    'Khối Lịch sử',
                                    'Section',
                                    'Enable',
                                    'Thu gọn',
                                    'Ở cuối cửa sổ. Bấm “Xem lịch sử” mới nạp dữ liệu; nội dung và bộ lọc giống cửa sổ Lịch sử thay đổi (mục 2.7). '
                                    'Có nút “Thu gọn” và “Làm mới”.'],
                                   ['6',
                                    'Nút Đóng',
                                    'Button',
                                    'Enable',
                                    'Hiển thị',
                                    'Nút duy nhất ở chân cửa sổ (KHÔNG có Lưu, Lưu và tiếp tục). Đóng cửa sổ.']],
                            'ui_widths': [0.5, 1.5, 0.9, 0.8, 1.1, 3.2],
                            'events': [['Bấm vào tên nguồn vốn ở cột Tên nguồn vốn',
                                        'Click',
                                        'After:\n'
                                        '– Mở cửa sổ “Xem nguồn vốn”, nạp dữ liệu hiện tại, mọi ô ở chế độ chỉ đọc.\n'
                                        '– Bản ghi không còn tồn tại → báo lỗi và đóng cửa sổ.'],
                                       ['Bấm Xem lịch sử / Thu gọn', 'Click', 'After:\n– Mở khối Lịch sử (lần đầu mới nạp dữ liệu) / thu gọn lại.'],
                                       ['Bấm Làm mới trong khối Lịch sử', 'Click', 'After:\n– Nạp lại danh sách thay đổi.'],
                                       ['Bấm Đóng / biểu tượng X', 'Click', 'After:\n– Đóng cửa sổ, không hỏi xác nhận (không có gì để lưu).']]},
 'Tùy chỉnh cột hiển thị': {'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
                                   ['1',
                                    'Biểu tượng Cấu hình cột hiển thị',
                                    'Icon Button',
                                    'Enable',
                                    'Hiển thị',
                                    'Ở cuối thanh công cụ của bảng. Mở cửa sổ “Tuỳ chỉnh cột”.'],
                                   ['2',
                                    'Danh sách cột',
                                    'Checkbox chọn nhiều',
                                    'Enable',
                                    'Theo cấu hình đã lưu của người dùng; lần đầu ẩn sẵn Người cập nhật, Ngày cập nhật',
                                    'Liệt kê đủ 8 cột theo thứ tự đang hiển thị: STT, Tên nguồn vốn, Người cập nhật, Ngày cập nhật, Người tạo, Ngày '
                                    'tạo, Trạng thái, Hành động. Tích = hiện, bỏ tích = ẩn.'],
                                   ['3',
                                    'Cột bắt buộc',
                                    'Checkbox',
                                    'Disable',
                                    'Tích sẵn',
                                    'STT, Tên nguồn vốn, Hành động: xám, có biểu tượng ổ khóa, không bỏ tích và không kéo đổi vị trí được.'],
                                   ['4',
                                    'Biểu tượng ☰',
                                    'Icon',
                                    'Enable',
                                    'Hiển thị',
                                    'Kéo để đổi vị trí các cột không bắt buộc (Người cập nhật, Ngày cập nhật, Người tạo, Ngày tạo, Trạng thái).'],
                                   ['5',
                                    'Nút Lưu',
                                    'Button',
                                    'Enable',
                                    'Hiển thị',
                                    'Áp dụng ngay lên bảng và lưu cấu hình theo tài khoản người dùng (đăng nhập máy khác vẫn giữ).'],
                                   ['6', 'Nút Đóng', 'Button', 'Enable', 'Hiển thị', 'Đóng cửa sổ, bỏ các thay đổi chưa lưu.']],
                            'ui_widths': [0.5, 1.5, 1.0, 0.7, 1.4, 3.0],
                            'events': [['Bấm biểu tượng Cấu hình cột hiển thị',
                                        'Click',
                                        'After:\n– Mở cửa sổ “Tuỳ chỉnh cột” theo cấu hình đang áp dụng.'],
                                       ['Tích / bỏ tích cột, kéo ☰',
                                        'Change',
                                        'During:\n– Cột bắt buộc không bỏ tích, không kéo được.\n– Chưa áp lên bảng cho tới khi bấm Lưu.'],
                                       ['Bấm Lưu',
                                        'Click',
                                        'After:\n'
                                        '– Bảng hiển thị ngay theo cột và thứ tự mới, lưu cấu hình theo người dùng, báo “Cập nhật thành công”.\n'
                                        '– Lỗi lưu → “Thao tác thất bại”.\n'
                                        '– Cửa sổ Chọn trường xuất file lần sau tích sẵn theo bộ cột mới.'],
                                       ['Bấm Đóng / biểu tượng X',
                                        'Click',
                                        'After:\n– Đóng cửa sổ, trả danh sách cột về cấu hình đang áp dụng, bảng không đổi.']]}}

for _fr in CFG['srs']['fr']:
    if _fr['ten'] in _SRS_UI_EVENTS:
        _fr.update(_SRS_UI_EVENTS[_fr['ten']])
