# -*- coding: utf-8 -*-
# Cấu hình tài liệu màn Danh mục loại tài khoản (Tài chính → Danh mục → Danh mục loại tài khoản).
# Nguồn: code gop_db 25/09/2026 — FE pages/finance/type-accounts/index.vue, components/modal/finance/type-account-modal.vue,
# static/Mau_import_loai_tai_khoan.xlsx; BE Modules/Finance: TypeAccountController, TypeAccountService, TypeAccountRequest,
# Entities/TypeAccount. Không ghi URL. Chữ UI / message lấy nguyên văn code.

DT = 'loại tài khoản'
Q_QL = 'Quản lý danh mục loại tài khoản'
Q_XEM = 'Xem danh mục loại tài khoản'

CFG = {
    'slug': 'type-accounts',
    'ten': 'Danh mục loại tài khoản',
    'doi_tuong': DT,
    'file_hdsd': 'HDSD_Danh muc loai tai khoan.docx',
    'file_srs': 'SRS - Danh mục loại tài khoản.docx',
    'menu': [('Tài chính', 'menu_phanhe'), ('Danh mục', 'menu_nhom'), ('Danh mục loại tài khoản', 'menu_muc')],
    'form_type': 'popup',

    'thuat_ngu': [
        ['Loại tài khoản', 'Nhóm phân loại tài khoản kế toán (tài khoản tài sản, nợ phải trả, vốn chủ sở hữu, doanh thu…). Mỗi tài khoản ở Danh mục tài khoản được gán về một loại.'],
        ['Mã loại tài khoản', 'Mã viết tắt, duy nhất trong danh mục, ví dụ TKTS. Chỉ gồm chữ không dấu, số, dấu - và _; hệ thống tự chuyển sang chữ IN HOA khi lưu.'],
        ['Đang được sử dụng', 'Đã có ít nhất một tài khoản ở Danh mục tài khoản được gán loại này.'],
        ['Trạng thái Hoạt động', 'Loại tài khoản chọn được khi khai báo tài khoản.'],
        ['Trạng thái Khóa', 'Loại tài khoản không còn chọn được khi khai báo tài khoản mới; tài khoản đã gán loại này vẫn giữ nguyên.'],
        ['Cổng cũ', 'Phần mềm quản trị cũ. Hai cổng dùng CHUNG một danh sách loại tài khoản.'],
    ],
    'phien_ban': [
        ['1.0', '13/08/2026', 'Đội phát triển phần mềm', 'Tạo mới cho màn Danh mục loại tài khoản.'],
        ['1.1', '25/09/2026', 'Đội phát triển phần mềm', 'Cập nhật theo phiên bản hiện tại: quy tắc Mã loại tài khoản (ký tự cho phép, tự in hoa), nút Khóa/Mở khóa và Lịch sử chuyển về cột Hành động, bấm Mã để xem chi tiết, bộ lọc nhãn nổi, cửa sổ Chọn trường xuất file, cửa sổ Import có Validate/Bỏ dòng lỗi, Tùy chỉnh cột; trình bày theo mẫu tài liệu danh mục chung.'],
    ],
    'muc_dich': [
        'Danh mục loại tài khoản dùng để khai báo các nhóm phân loại tài khoản kế toán (tài khoản tài sản, nợ phải trả, vốn chủ sở hữu, doanh thu, chi phí…). Mỗi tài khoản trong Danh mục tài khoản đều được gán về một loại lấy từ danh mục này, nhờ đó hệ thống gom nhóm được tài khoản khi lên sổ sách và báo cáo.',
        'Danh mục dùng CHUNG dữ liệu với màn tương ứng bên cổng cũ: sửa ở cổng nào thì cổng còn lại cũng thấy ngay.',
    ],
    'quyen': {
        'truoc': ['Màn hình dùng hai quyền riêng. Mục menu chỉ hiện khi tài khoản có ít nhất một trong hai quyền; không có quyền nào thì không vào được màn hình và máy chủ không trả dữ liệu.'],
        'rows': [
            [Q_XEM, 'Vào màn hình, xem danh sách, tìm kiếm, lọc, bấm Mã để xem chi tiết, xem Lịch sử, Xuất Excel, Tùy chỉnh cột.'],
            [Q_QL, 'Toàn bộ quyền Xem, cộng thêm: Tạo mới, Sửa, Xóa, Khóa, Mở khóa và Import Excel.'],
        ],
        'sau': ['Danh mục KHÔNG phân quyền theo công ty, phòng ban hay bộ phận. Thiếu quyền Quản lý thì các nút Tạo mới, Import Excel, Sửa, Xóa, Khóa/Mở khóa không hiển thị; gọi thẳng chức năng bỏ qua giao diện cũng bị máy chủ từ chối.'],
    },

    'danh_sach': {
        'mo_ta_vao': 'Hệ thống hiển thị danh sách loại tài khoản hiện có, mặc định 10 dòng mỗi trang, bản ghi thêm sau cùng nằm trên cùng.',
        'bo_cuc': [
            'Khu vực tìm kiếm và lọc — ô tìm kiếm nhanh, nút Tìm kiếm, Làm mới và nút Tìm kiếm nâng cao (mở thêm các ô Trạng thái, Người tạo, Người cập nhật, Ngày cập nhật).',
            'Thanh công cụ — nút Tạo mới, Xuất Excel, Import Excel và biểu tượng Cấu hình cột hiển thị.',
            'Bảng danh sách — các cột thông tin, cột Hành động ở cuối, và phân trang bên dưới.',
        ],
        'cot': [
            ['STT', 'Số thứ tự, chạy liên tục qua các trang. Luôn hiển thị.'],
            ['Mã loại tài khoản', 'Luôn hiển thị, sắp xếp được. Bấm vào mã để mở cửa sổ Xem loại tài khoản.'],
            ['Tên loại tài khoản', 'Tên đầy đủ, sắp xếp được.'],
            ['Ghi chú', 'Mô tả thêm, nội dung dài được xuống dòng trong ô. Mặc định ẩn.'],
            ['Người cập nhật', 'Người sửa bản ghi gần nhất. Mặc định ẩn.'],
            ['Ngày cập nhật', 'Thời điểm sửa gần nhất, dạng dd/mm/yyyy hh:mm. Mặc định ẩn, sắp xếp được.'],
            ['Người tạo', 'Người đã thêm bản ghi.'],
            ['Ngày tạo', 'Thời điểm thêm, dạng dd/mm/yyyy hh:mm, sắp xếp được.'],
            ['Trạng thái', 'Nhãn Hoạt động hoặc Khóa.'],
            ['Hành động', 'Các nút thao tác của dòng (xem mục 4).'],
        ],
        'hanh_dong': {
            'intro': 'Trên mỗi dòng, cột Hành động có các nút:',
            'bullets': [
                'Biểu tượng bút chì {icon:btn_sua} — mở cửa sổ Sửa loại tài khoản. Chỉ hiện với người có quyền Quản lý và khi loại tài khoản đang Hoạt động.',
                'Biểu tượng thùng rác {icon:btn_xoa} — xóa loại tài khoản. Chỉ hiện với người có quyền Quản lý và khi CHƯA có tài khoản nào được gán loại này.',
                'Khóa — chỉ hiện với người có quyền Quản lý, khi loại tài khoản đang Hoạt động và CHƯA có tài khoản nào được gán loại này. Mở khóa — hiện khi loại tài khoản đang Khóa.',
                'Lịch sử — mở cửa sổ Lịch sử thay đổi. Mọi người vào được màn hình đều thấy.',
                'Có từ 4 nút trở lên thì 2 nút đầu hiện thẳng, các nút còn lại nằm trong nút ba chấm {icon:btn_bacham} “Hành động khác”.',
            ],
            'anh': 'Các nút ở cột Hành động của một loại tài khoản',
            'luu_y': ['Lưu ý quan trọng: loại tài khoản ĐANG ĐƯỢC SỬ DỤNG thì KHÔNG xóa được VÀ cũng KHÔNG khóa được (nút Xóa và Khóa không hiển thị). Muốn ngừng dùng, phải chuyển các tài khoản đang gán loại này sang loại khác trước.',
                      'Loại tài khoản ĐÃ KHÓA thì nút Sửa biến mất; muốn sửa phải Mở khóa trước. Người chỉ có quyền Xem chỉ thấy nút Lịch sử.'],
        },
        'phan_trang': [
            'Cuối bảng có dòng “Hiển thị a–b / N”: N là tổng số loại tài khoản khớp bộ lọc đang áp dụng, không phải tổng toàn danh mục.',
            'Ô Số dòng/trang có các mức 5, 10, 20, 50, 100 (mặc định 10). Đổi số dòng thì hệ thống tự quay về trang 1.',
            'Các cột sắp xếp được: Mã loại tài khoản, Tên loại tài khoản, Ngày tạo, Ngày cập nhật. Bấm tiêu đề cột để sắp xếp, bấm lần hai để đảo chiều. Thứ tự sắp xếp được giữ nguyên khi chuyển trang.',
        ],
    },

    'loc': {
        'buoc2': 'Bước 2: Nhập chữ vào ô tìm kiếm nhanh; bấm Tìm kiếm nâng cao để chọn thêm Trạng thái, Người tạo, Người cập nhật, Ngày cập nhật.',
        'rows': [
            ['Ô tìm kiếm nhanh', 'Placeholder “Tìm theo mã hoặc tên loại tài khoản...”. Quét Mã và Tên, gõ một phần chuỗi cũng ra, không phân biệt hoa thường. Nhấn Enter hoặc bấm Tìm kiếm để lọc.'],
            ['Trạng thái', 'Hoạt động hoặc Khóa. Bỏ trống thì hiện cả hai. Lọc ngay khi chọn.'],
            ['Người tạo', 'Chọn một nhân viên để chỉ xem loại tài khoản do người đó tạo. Lọc ngay khi chọn.'],
            ['Người cập nhật', 'Chọn một nhân viên để chỉ xem loại tài khoản do người đó sửa gần nhất. Lọc ngay khi chọn.'],
            ['Ngày cập nhật', 'Chọn khoảng ngày (từ – đến) theo ngày sửa gần nhất.'],
        ],
        'ap_dung': [
            'Các tiêu chí kết hợp với nhau theo kiểu VÀ — chỉ bản ghi thỏa đồng thời tất cả các tiêu chí mới hiện ra. Mỗi lần đổi tiêu chí, danh sách quay về trang 1.',
            'Bấm {icon:btn_lammoi} để xóa toàn bộ tiêu chí; danh sách nạp lại đầy đủ ngay lập tức.',
            'Hệ thống ghi nhớ bộ lọc trong 10 phút: rời màn rồi quay lại trong khoảng đó thì điều kiện lọc cũ vẫn còn.',
        ],
        'anh_ket_qua': 'Kết quả tìm nhanh theo tên loại tài khoản (gõ “Tài khoản”)',
    },

    'form': {
        'kieu': 'popup',
        'buoc_tao': [
            'Bước 1: Truy cập vào màn hình Danh mục loại tài khoản.',
            'Bước 2: Bấm {icon:btn_taomoi}. Hệ thống mở cửa sổ “Tạo loại tài khoản”.',
            'Bước 3: Nhập/ chọn thông tin: Mã loại tài khoản, Trạng thái, Tên loại tài khoản, Ghi chú.',
            'Bước 4: Bấm {icon:btn_luu} để lưu và đóng cửa sổ, hoặc {icon:btn_luutieptuc} để lưu rồi nhập tiếp loại khác.',
        ],
        'anh_tao': 'Cửa sổ Tạo loại tài khoản',
        'truong': [
            ['Mã loại tài khoản', 'Ô nhập giá trị', 'Có', 'Trống', 'Tối đa 255 ký tự, chỉ gồm chữ không dấu, số, dấu - và _ (gõ sai báo ngay “Chỉ gồm chữ không dấu, số, dấu - và _”). Hệ thống tự bỏ khoảng trắng hai đầu và chuyển sang chữ IN HOA khi lưu. Duy nhất; trùng báo “Mã loại tài khoản đã tồn tại” (“tkts” cũng bị coi là trùng “TKTS”).'],
            ['Trạng thái', 'Ô chọn giá trị', 'Không', 'Hoạt động', 'Hoạt động / Khóa. Khi sửa loại tài khoản đang được sử dụng, ô này bị khóa ở Hoạt động (không chuyển sang Khóa được).'],
            ['Tên loại tài khoản', 'Ô nhập giá trị', 'Có', 'Trống', 'Tối đa 255 ký tự, duy nhất. Bỏ trống báo “Bắt buộc phải nhập”; trùng báo “Tên loại tài khoản đã tồn tại”.'],
            ['Ghi chú', 'Ô nhập giá trị', 'Không', 'Trống', 'Tối đa 255 ký tự.'],
        ],
        'nut': [
            ['Lưu', 'Ghi bản ghi rồi đóng cửa sổ, báo “Thêm mới thành công” (hoặc “Cập nhật thành công” khi sửa) và nạp lại danh sách.'],
            ['Lưu và tiếp tục', 'Ghi bản ghi nhưng GIỮ cửa sổ mở và xóa trắng các ô để nhập tiếp. Chỉ có khi Tạo mới.'],
            ['Đóng', 'Đóng cửa sổ, không ghi gì. Nếu đã nhập dở, hệ thống hỏi “Thông tin chưa lưu” — “Bạn có thông tin chưa lưu. Có chắc chắn muốn thoát?” (Thoát / Ở lại).'],
        ],
        'loi': [
            ['Bắt buộc phải nhập', 'Chưa nhập Mã hoặc Tên loại tài khoản.'],
            ['Chỉ gồm chữ không dấu, số, dấu - và _', 'Mã có dấu tiếng Việt, khoảng trắng hoặc ký tự đặc biệt khác.'],
            ['Mã loại tài khoản đã tồn tại', 'Đã có loại tài khoản khác cùng mã (không phân biệt hoa thường).'],
            ['Tên loại tài khoản đã tồn tại', 'Đã có loại tài khoản khác cùng tên.'],
            ['Vui lòng nhập tối đa 255 ký tự.', 'Mã, Tên hoặc Ghi chú quá dài.'],
            ['Bạn chưa nhập đầy đủ thông tin', 'Thông báo chung khi còn ô bị lỗi; xem các ô báo đỏ trong cửa sổ.'],
        ],
    },

    'sua': {
        'buoc': [
            'Bước 1: Truy cập vào màn hình Danh mục loại tài khoản.',
            'Bước 2: Bấm nút {icon:btn_sua} ở cột Hành động của loại tài khoản cần sửa.',
            'Bước 3: Hệ thống hiển thị cửa sổ “Sửa loại tài khoản” với dữ liệu hiện tại.',
            'Bước 4: Cập nhật các thông tin cần sửa (quy tắc nhập như Thêm mới).',
            'Bước 5: Bấm {icon:btn_luu} để xác nhận thay đổi hoặc Đóng nếu muốn hủy.',
        ],
        'anh': 'Cửa sổ Sửa loại tài khoản',
        'ghi_chu': [
            'Cửa sổ Sửa không có nút “Lưu và tiếp tục”.',
            'Giữ nguyên mã/tên của chính loại tài khoản đang sửa thì không bị báo trùng.',
            'Loại tài khoản đang được sử dụng: ô Trạng thái bị khóa, không chuyển sang Khóa được (máy chủ cũng chặn với thông báo “Loại tài khoản đang được sử dụng, không thể khóa”).',
            'Loại tài khoản đang Khóa không có nút Sửa. Nếu vừa bị người khác khóa, bấm Lưu sẽ nhận thông báo “Loại tài khoản đang bị khoá, vui lòng mở khoá trước khi cập nhật.”',
            'Đổi tên loại ở đây thì cột Loại tài khoản ở Danh mục tài khoản tự hiển thị tên mới.',
        ],
    },
    'xoa': {
        'buoc': [
            'Bước 1: Ở cột Hành động, Người dùng bấm {icon:btn_xoa}.',
            'Bước 2: Hệ thống hiện hộp “Xác nhận xóa” — “Bạn có chắc muốn xóa loại tài khoản \'…\'?”. Bấm {icon:btn_confirm_xoa} để xác nhận: hệ thống báo “Xóa thành công”, bản ghi biến mất khỏi danh sách.',
            'Bấm {icon:btn_huy} nếu bấm nhầm. Không có gì thay đổi.',
        ],
        'anh': 'Hộp xác nhận xóa loại tài khoản',
        'ghi_chu': ['Nút Xóa chỉ hiện khi CHƯA có tài khoản nào được gán loại này. Nếu vừa có người gán loại này cho một tài khoản ngay trước khi xác nhận, máy chủ chặn với thông báo “Loại tài khoản đang được sử dụng, không thể xóa”. Xóa loại tài khoản xóa luôn lịch sử thay đổi của nó; thao tác không lùi lại được.'],
    },
    'khoa': {
        'y_nghia': [
            'Bản ghi VẪN nằm trong danh sách, cột Trạng thái hiện chữ Khóa.',
            'Vẫn xem được chi tiết và lịch sử thay đổi của bản ghi.',
            'Loại tài khoản đã khóa không còn xuất hiện ở ô Loại tài khoản khi khai báo tài khoản mới; tài khoản đang dùng loại đó vẫn hiện đúng tên loại kèm biểu tượng 🔒.',
            'Nút Sửa của dòng đó biến mất.',
            'Chỉ khóa được loại tài khoản CHƯA được sử dụng — khác Danh mục tiền tệ (ở đó khóa luôn được).',
        ],
        'buoc_khoa': [
            'Bước 1: Ở cột Hành động, Người dùng chọn Khóa (trong nút ba chấm nếu dòng có nhiều nút).',
            'Bước 2: Hệ thống hiện hộp “Xác nhận khóa” — “Bạn có chắc muốn khóa loại tài khoản \'…\'?”. Bấm Khóa để xác nhận; hệ thống báo “Khóa thành công”, cột Trạng thái đổi thành Khóa. Bấm Hủy nếu bấm nhầm.',
        ],
        'buoc_mo': [
            'Bước 1: Ở cột Hành động của loại tài khoản đang Khóa, Người dùng chọn Mở khóa.',
            'Bước 2: Bấm Mở khóa trong hộp “Xác nhận mở khóa”. Hệ thống báo “Mở khóa thành công”, cột Trạng thái đổi thành Hoạt động. Bấm Hủy nếu bấm nhầm.',
        ],
        'ghi_chu': ['Có thể khóa ngay trong cửa sổ Sửa bằng cách chọn Trạng thái = Khóa rồi Lưu (chỉ khi loại chưa được sử dụng). Nếu vừa có người gán loại này cho tài khoản, hệ thống báo “Loại tài khoản đang được sử dụng, không thể khóa”; nếu bản ghi đã được người khác mở khóa, báo “Dữ liệu đã thay đổi, vui lòng tải lại”.'],
    },
    'lich_su': {
        'buoc': [
            'Xem từ màn danh sách: ở cột Hành động, Người dùng chọn Lịch sử.',
            'Xem từ màn chi tiết: bấm vào mã loại tài khoản để mở cửa sổ Xem loại tài khoản, khối Lịch sử nằm ở cuối cửa sổ.',
        ],
        'ghi_chu': ['Với danh mục này, lịch sử ghi các lần Thay đổi thông tin; Khóa / Mở khóa hiện dưới dạng Thay đổi thông tin ở trường Trạng thái (Hoạt động → Khóa). Thao tác Tạo mới và Import chưa sinh mốc lịch sử. Cửa sổ có bộ lọc riêng (loại hành động, người thực hiện, khoảng thời gian).'],
    },
    'chi_tiet': {
        'buoc': ['Bước 1: Truy cập vào màn hình Danh mục loại tài khoản.',
                 'Bước 2: Bấm vào mã ở cột Mã loại tài khoản. Hệ thống mở cửa sổ “Xem loại tài khoản”.'],
        'ghi_chu': ['Cửa sổ hiển thị Mã loại tài khoản, Trạng thái, Tên loại tài khoản, Ghi chú ở chế độ chỉ đọc (không gõ được, không có nút Lưu, chỉ có nút Đóng), kèm khối Lịch sử ở cuối. Loại tài khoản đang Khóa và người chỉ có quyền Xem vẫn xem được bình thường.'],
    },
    'xuat': {
        'buoc': [
            'Bước 1: Lọc danh sách theo đúng dữ liệu cần lấy (xem PHẦN 2). File xuất ra chạy theo đúng bộ lọc và thứ tự sắp xếp đang áp dụng.',
            'Bước 2: Bấm nút {icon:btn_xuatexcel}. Hệ thống mở cửa sổ “Chọn trường xuất file”.',
            'Bước 3: Tích chọn, kéo biểu tượng ☰ để đổi vị trí các trường cần xuất. Mặc định hệ thống tích sẵn đúng những cột đang hiển thị trên bảng.',
            'Bước 4: Bấm {icon:btn_xuatfile}. Hệ thống tải về file danh_muc_loai_tai_khoan.xlsx và báo “Xuất Excel thành công”.',
        ],
        'truong': 'Chọn nhiều trường: Mã loại tài khoản, Tên loại tài khoản, Ghi chú, Trạng thái, Người tạo, Ngày tạo.',
        'ghi_chu': ['Lưu ý: file xuất chứa TOÀN BỘ kết quả của bộ lọc, không chỉ các dòng của trang đang xem. Người chỉ có quyền Xem vẫn xuất được Excel.'],
    },
    'import': {
        'tieu_de': 'Import loại tài khoản',
        'file': 'Mau_import_loai_tai_khoan.xlsx',
        'cot_text': 'Mã loại tài khoản (bắt buộc), Tên loại tài khoản (bắt buộc), Ghi chú, Trạng thái (Hoạt động / Khóa; để trống = Hoạt động). Hàng 1 là tiêu đề, dữ liệu nhập từ hàng 2 (file mẫu có sẵn 2 dòng ví dụ LTK001, LTK002 — xóa đi trước khi nhập)',
        'toast': 'Import thành công N loại tài khoản.',
        'loi': [
            ['Mã loại tài khoản không được để trống', 'Dòng đó bỏ trống cột Mã loại tài khoản.'],
            ['Mã loại tài khoản tối đa 255 ký tự', 'Mã quá dài, rút gọn lại.'],
            ['Mã loại tài khoản: Chỉ gồm chữ không dấu, số, dấu - và _', 'Mã có dấu tiếng Việt, khoảng trắng hoặc ký tự đặc biệt.'],
            ['Mã loại tài khoản bị trùng trong file import (dòng N)', 'Trong chính file có hai dòng cùng mã (không phân biệt hoa thường). Xoá bớt một dòng.'],
            ['Mã loại tài khoản đã tồn tại trong hệ thống', 'Danh mục đã có loại tài khoản cùng mã.'],
            ['Tên loại tài khoản không được để trống', 'Dòng đó bỏ trống cột Tên loại tài khoản.'],
            ['Tên loại tài khoản tối đa 255 ký tự', 'Tên quá dài, rút gọn lại.'],
            ['Ghi chú tối đa 255 ký tự', 'Ghi chú quá dài, rút gọn lại.'],
            ['Trạng thái chỉ nhận "Hoạt động" hoặc "Khóa"', 'Cột Trạng thái ghi giá trị khác (để trống = Hoạt động).'],
        ],
        'ghi_chu': [
            'Lưu ý: Mã loại tài khoản trong file được tự chuyển sang chữ IN HOA. Cột Trạng thái để trống thì loại tài khoản được tạo ở trạng thái Hoạt động; ghi Khóa thì tạo luôn ở trạng thái Khóa. Người tạo là chính người thực hiện nhập.',
            'Mỗi lần nhập tối đa 500 dòng; file dài hơn hệ thống báo “File có X dòng dữ liệu, vượt quá giới hạn 500 dòng mỗi lần import. Vui lòng tách file và import nhiều lần.” File không có dòng dữ liệu báo “Không có dòng dữ liệu hợp lệ.”',
        ],
    },
    'tuy_chinh_cot': {'cot_khoa': 'Ba cột STT, Mã loại tài khoản và Hành động'},

    'shots': {'list': '01_list.png', 'rowmenu': '03_rowmenu.png', 'filter': 'filter.png', 'filter_result': '04_filter_result.png',
              'create': '10_create.png', 'create_error': '11_create_error.png', 'code_error': '11b_code_error.png', 'edit': '12_edit.png',
              'delete': '13_delete.png', 'lock': '14_lock.png', 'unlock': '15_unlock.png', 'history': '16_history.png',
              'detail': '17_detail.png', 'export': '20_export.png', 'import_open': '21_import_open.png',
              'import_loaded': '22_import_loaded.png', 'import_validated': '23_import_validated.png', 'colcfg': '25_colcfg.png'},

    'capture': {'route': '/finance/type-accounts',
                'menu': {'phanhe': 'TÀI CHÍNH', 'nhom': 'Danh mục', 'muc': 'Danh mục loại tài khoản'},
                'search': 'Tìm theo mã hoặc tên', 'searchText': 'Tài khoản', 'detailCol': 1,
                'lockName': 'Tài khoản trang test 001', 'codeInput': 'VD: TKTS', 'create': True, 'lock': True},

    'import_test': {
        'cols': ['Mã loại tài khoản', 'Tên loại tài khoản', 'Ghi chú', 'Trạng thái'],
        'rows': [
            ['DOC01', 'DOC-Tài khoản ngoài bảng', 'Ví dụ tài liệu', 'Hoạt động'],
            ['doc02', 'DOC-Tài khoản thu nhập khác', '', ''],
            ['DOC03', 'DOC-Tài khoản tạm khóa', '', 'Khóa'],
            ['', 'DOC-Thiếu mã', '', 'Hoạt động'],
            ['DOC01', 'DOC-Trùng mã trong file', '', 'Hoạt động'],
            ['TKTS', 'DOC-Trùng mã hệ thống', '', 'Hoạt động'],
            ['LTK Đ1', 'DOC-Mã có dấu', '', 'Hoạt động'],
            ['DOC08', '', '', 'Tạm dừng'],
        ],
    },

    'uml': {
        'mains': [('FR-01', 'Xem danh sách loại tài khoản', 'view'), ('FR-03', 'Thêm mới loại tài khoản', 'crud'),
                  ('FR-04', 'Chỉnh sửa loại tài khoản', 'crud'), ('FR-05', 'Xóa loại tài khoản', 'action'),
                  ('FR-06', 'Khóa / Mở khóa loại tài khoản', 'action'), ('FR-08', 'Import file loại tài khoản', 'io'),
                  ('FR-09', 'Xuất danh sách loại tài khoản ra Excel', 'io')],
        'subs': [('FR-02', 'Tìm kiếm và lọc loại tài khoản', 'view'), ('FR-10', 'Xem chi tiết loại tài khoản', 'view'),
                 ('FR-11', 'Tùy chỉnh cột hiển thị', 'view'), ('FR-07', 'Xem lịch sử thay đổi', 'view')],
        'rieng': [('FR-10', 'Xem chi tiết loại tài khoản', 'view')],
    },

    'srs': {
        'muc_dich': ['Là căn cứ nghiệm thu chức năng.',
                     'Làm rõ quy tắc Mã loại tài khoản, ràng buộc không xóa / không khóa loại đang được Danh mục tài khoản sử dụng.'],
        'quyen_truoc': ['Màn hình dùng hai quyền riêng thuộc nhóm “Danh mục tài chính”. Không có quyền nào thì không vào được màn hình. Máy chủ kiểm tra quyền ở từng chức năng, không chỉ dựa vào việc ẩn nút.'],
        'quyen_rows': [[Q_XEM, 'Xem danh sách, tìm kiếm/lọc, xem chi tiết, xem lịch sử, xuất Excel, tùy chỉnh cột.'],
                       [Q_QL, 'Toàn bộ quyền Xem + Thêm mới, Sửa, Xóa, Khóa/Mở khóa, Import Excel.']],
        'ma_tran': [['Chức năng', Q_QL, Q_XEM]] + [[f, 'Có', x] for f, x in [
            ('FR-01 Xem danh sách loại tài khoản', 'Có'), ('FR-02 Tìm kiếm và lọc', 'Có'), ('FR-03 Thêm mới loại tài khoản', 'Không'),
            ('FR-04 Chỉnh sửa loại tài khoản', 'Không'), ('FR-05 Xóa loại tài khoản', 'Không'), ('FR-06 Khóa / Mở khóa loại tài khoản', 'Không'),
            ('FR-07 Xem lịch sử thay đổi', 'Có'), ('FR-08 Import file loại tài khoản', 'Không'), ('FR-09 Xuất danh sách ra Excel', 'Có'),
            ('FR-10 Xem chi tiết loại tài khoản', 'Có'), ('FR-11 Tùy chỉnh cột hiển thị', 'Có')]],
        'ma_tran_widths': [2.4, 1.6, 1.6],
        'quyen_sau': ['Danh mục KHÔNG phân quyền theo công ty / phòng ban / bộ phận.'],
        'fr': [
            {'ten': 'Xem danh sách loại tài khoản',
             'qtc': 'Màn Danh sách, Sắp xếp dữ liệu bảng, Phân trang và Cấu hình cột. Chỉ bổ sung các quy tắc riêng của Danh mục loại tài khoản tại phần mô tả chi tiết.',
             'gioi_thieu': [['Tên chức năng', 'Xem danh sách loại tài khoản'],
                            ['Mô tả', 'Hiển thị toàn bộ loại tài khoản trong danh mục, có phân trang và sắp xếp.'],
                            ['Tác nhân', 'Người có quyền “%s” hoặc “%s”' % (Q_QL, Q_XEM)],
                            ['Điều kiện ban đầu', 'Người dùng đã đăng nhập và có một trong hai quyền trên.'],
                            ['Dòng sự kiện chính', '1. Người dùng vào menu Tài chính → Danh mục → Danh mục loại tài khoản.\n2. Hệ thống nạp trang đầu tiên (10 dòng), bản ghi mới nhất ở trên cùng.\n3. Bảng hiển thị dữ liệu kèm tổng số bản ghi.'],
                            ['Dòng sự kiện phụ', '• Không có bản ghi khớp → bảng hiện “Không có dữ liệu phù hợp bộ lọc.”\n• Không có quyền → không vào được màn hình.']],
             'anh': [('list', 'Màn Danh mục loại tài khoản lúc mới truy cập')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Mô tả'],
                    ['1', 'STT', 'Table/Grid', 'Read-only', 'Số thứ tự, chạy liên tục qua các trang. Luôn hiển thị.'],
                    ['2', 'Mã loại tài khoản', 'Table/Grid', 'Read-only', 'Luôn hiển thị, sắp xếp được. Bấm vào mã mở cửa sổ Xem (xem 2.10).'],
                    ['3', 'Tên loại tài khoản', 'Table/Grid', 'Read-only', 'Sắp xếp được.'],
                    ['4', 'Ghi chú', 'Table/Grid', 'Read-only', 'Xuống dòng khi dài. Mặc định ẩn.'],
                    ['5', 'Người cập nhật', 'Table/Grid', 'Read-only', 'Mặc định ẩn.'],
                    ['6', 'Ngày cập nhật', 'Table/Grid', 'Read-only', 'dd/mm/yyyy hh:mm. Mặc định ẩn, sắp xếp được.'],
                    ['7', 'Người tạo', 'Table/Grid', 'Read-only', 'Người đã thêm bản ghi.'],
                    ['8', 'Ngày tạo', 'Table/Grid', 'Read-only', 'dd/mm/yyyy hh:mm, sắp xếp được.'],
                    ['9', 'Trạng thái', 'Badge', 'Read-only', 'Hoạt động hoặc Khóa.'],
                    ['10', 'Hành động', 'Table/Grid', 'Read-only', 'Sửa (quyền Quản lý, đang Hoạt động), Xóa (quyền Quản lý, chưa được sử dụng), Khóa (quyền Quản lý, đang Hoạt động, chưa được sử dụng) / Mở khóa (quyền Quản lý, đang Khóa), Lịch sử (mọi người).'],
                    ['11', 'Nút Tạo mới', 'Button', 'Enable', 'Chỉ hiện với quyền Quản lý.'],
                    ['12', 'Nút Xuất Excel', 'Button', 'Enable', 'Mở cửa sổ Chọn trường xuất file (xem 2.9).'],
                    ['13', 'Nút Import Excel', 'Button', 'Enable', 'Chỉ hiện với quyền Quản lý (xem 2.8).'],
                    ['14', 'Biểu tượng Cấu hình cột hiển thị', 'Icon Button', 'Enable', 'Mở cửa sổ Tuỳ chỉnh cột (xem 2.11).'],
                    ['15', 'Phân trang', 'Pagination', 'Enable', 'Số dòng/trang 5 / 10 / 20 / 50 / 100, mặc định 10.']],
             'ui_widths': [0.6, 1.4, 0.9, 0.8, 3],
             'events': [['Mở màn hình', 'System', 'After:\n– Nạp trang đầu, hiển thị tổng số bản ghi.'],
                        ['Bấm tiêu đề cột sắp xếp được', 'Click', 'After:\n– Đổi chiều sắp xếp và nạp lại danh sách từ trang 1.'],
                        ['Chuyển trang', 'Click', 'Before:\n– Giữ nguyên bộ lọc và thứ tự sắp xếp.\nAfter:\n– Nạp dữ liệu trang mới.'],
                        ['Đổi số dòng mỗi trang', 'Change', 'After:\n– Quay về trang 1 và nạp lại theo số dòng mới.']]},
            {'ten': 'Tìm kiếm và lọc',
             'qtc': 'Kịch bản tìm kiếm, Bộ lọc, Dropdown, Phân trang. Chỉ bổ sung các tiêu chí tìm kiếm/lọc riêng của Danh mục loại tài khoản.',
             'gioi_thieu': [['Tên chức năng', 'Tìm kiếm và lọc danh sách'],
                            ['Mô tả', 'Thu hẹp danh sách bằng ô tìm kiếm nhanh và khối Tìm kiếm nâng cao (Trạng thái, Người tạo, Người cập nhật, Ngày cập nhật).'],
                            ['Tác nhân', 'Người có quyền Quản lý hoặc Xem danh mục loại tài khoản'],
                            ['Điều kiện ban đầu', 'Đang ở màn Danh mục loại tài khoản.'],
                            ['Dòng sự kiện chính', '1. Người dùng nhập từ khóa và bấm Tìm kiếm / Enter, hoặc mở Tìm kiếm nâng cao và chọn tiêu chí (lọc ngay).\n2. Hệ thống áp đồng thời mọi tiêu chí và nạp lại danh sách từ trang 1.'],
                            ['Dòng sự kiện phụ', '• Không có kết quả → bảng hiện thông báo không có dữ liệu.\n• Bấm Làm mới → xóa hết tiêu chí VÀ nạp lại danh sách đầy đủ ngay.']],
             'anh': [('filter', 'Khu vực tìm kiếm và lọc của màn Danh mục loại tài khoản')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Phạm vi', 'Mô tả'],
                    ['1', 'Ô tìm kiếm nhanh', 'Textbox', 'Enable', '0–255 ký tự', 'Placeholder “Tìm theo mã hoặc tên loại tài khoản...”. Khớp một phần.'],
                    ['2', 'Trạng thái', 'Dropdown', 'Enable', 'Hoạt động / Khóa', 'Nhãn nổi. Bỏ trống thì hiện cả hai.'],
                    ['3', 'Người tạo', 'Dropdown', 'Enable', 'Danh sách nhân viên', 'Nhãn nổi.'],
                    ['4', 'Người cập nhật', 'Dropdown', 'Enable', 'Danh sách nhân viên', 'Nhãn nổi.'],
                    ['5', 'Ngày cập nhật', 'Date range', 'Enable', 'dd/mm/yyyy', 'Từ ngày – đến ngày, tính cả hai đầu.'],
                    ['6', 'Nút Tìm kiếm', 'Button', 'Enable', '–', 'Áp dụng các tiêu chí.'],
                    ['7', 'Nút Làm mới', 'Button', 'Enable', '–', 'Xóa hết tiêu chí VÀ nạp lại danh sách ngay.'],
                    ['8', 'Nút Tìm kiếm nâng cao', 'Button', 'Enable', '–', 'Mở / thu gọn khối lọc nâng cao.']],
             'ui_widths': [0.6, 1.2, 0.8, 0.7, 1.1, 2.6],
             'events': [['Bấm Tìm kiếm / Enter', 'Click', 'After:\n– Áp đồng thời các tiêu chí, nạp lại bảng từ trang 1.'],
                        ['Chọn một ô lọc', 'Change', 'After:\n– Lọc ngay, nạp lại bảng từ trang 1.'],
                        ['Bấm Làm mới', 'Click', 'After:\n– Xóa trắng mọi tiêu chí VÀ nạp lại danh sách đầy đủ.']]},
            {'ten': 'Thêm mới loại tài khoản', 'uc': 'uc_fr03',
             'qtc': 'Màn Thêm mới, Validate dữ liệu, Thông báo và UI/UX.',
             'gioi_thieu': [['Tên chức năng', 'Thêm mới loại tài khoản'],
                            ['Mô tả', 'Thêm một loại tài khoản mới thông qua cửa sổ nhập liệu.'],
                            ['Tác nhân', 'Người có quyền “%s”' % Q_QL],
                            ['Điều kiện ban đầu', 'Đang ở màn Danh mục loại tài khoản.'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm Tạo mới.\n2. Hệ thống mở cửa sổ “Tạo loại tài khoản”, Trạng thái mặc định Hoạt động.\n3. Người dùng nhập Mã, Tên, Ghi chú và bấm Lưu.\n4. Hệ thống bỏ khoảng trắng hai đầu, chuyển Mã sang chữ IN HOA, kiểm tra dữ liệu và ghi bản ghi mới.\n5. Cửa sổ đóng, danh sách nạp lại, báo “Thêm mới thành công”.'],
                            ['Dòng sự kiện phụ', '• Thiếu trường bắt buộc, sai định dạng hoặc trùng mã/tên → báo lỗi đỏ dưới ô + toast “Bạn chưa nhập đầy đủ thông tin”, cửa sổ KHÔNG đóng.\n• Bấm “Lưu và tiếp tục” → ghi bản ghi rồi giữ cửa sổ mở với các ô trống.\n• Bấm Đóng khi đã nhập dở → hỏi “Thông tin chưa lưu” (Thoát / Ở lại).'],
                            ['Yêu cầu đặc biệt', 'Cửa sổ có ba nút: Lưu, Lưu và tiếp tục, Đóng.']],
             'menu_them': ' => Tạo mới {icon:btn_taomoi}',
             'ghi_chu_layout': 'Cửa sổ Tạo loại tài khoản được mở ngay trên màn hình danh sách.',
             'anh': [('create', 'Cửa sổ Tạo loại tài khoản'), ('create_error', 'Lỗi đỏ ngay dưới ô còn thiếu'), ('code_error', 'Lỗi định dạng Mã loại tài khoản hiện ngay khi gõ')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Phạm vi', 'Bắt buộc', 'Mô tả'],
                    ['1', 'Mã loại tài khoản', 'Textbox', 'Enable', '1–255 ký tự: A-Z, a-z, 0-9, - và _', 'Có', 'Tự bỏ khoảng trắng hai đầu, tự IN HOA khi lưu. Duy nhất (không phân biệt hoa thường). Sai ký tự “Chỉ gồm chữ không dấu, số, dấu - và _”; trùng “Mã loại tài khoản đã tồn tại”; bỏ trống “Bắt buộc phải nhập”.'],
                    ['2', 'Trạng thái', 'Dropdown', 'Enable', 'Hoạt động / Khóa', 'Không', 'Mặc định Hoạt động. Khóa (Disable) khi sửa loại đang được sử dụng.'],
                    ['3', 'Tên loại tài khoản', 'Textbox', 'Enable', '1–255 ký tự', 'Có', 'Duy nhất. Bỏ trống “Bắt buộc phải nhập”; trùng “Tên loại tài khoản đã tồn tại”.'],
                    ['4', 'Ghi chú', 'Textbox', 'Enable', '0–255 ký tự', 'Không', 'Placeholder “Ghi chú thêm (nếu có)”.'],
                    ['5', 'Nút Lưu', 'Button', 'Enable', '', '', 'Ghi bản ghi rồi đóng cửa sổ.'],
                    ['6', 'Nút Lưu và tiếp tục', 'Button', 'Enable', '', '', 'Ghi bản ghi rồi giữ cửa sổ mở để nhập tiếp.'],
                    ['7', 'Nút Đóng', 'Button', 'Enable', '', '', 'Hủy bỏ, không ghi gì.']],
             'ui_widths': [0.5, 1.2, 0.8, 0.6, 1.3, 0.5, 2.2],
             'events': [['Bấm nút Tạo mới', 'Click', 'After:\n– Mở cửa sổ nhập liệu với các ô trống, Trạng thái = Hoạt động.'],
                        ['Gõ Mã loại tài khoản', 'Input', 'During:\n– Có ký tự ngoài chữ không dấu, số, - và _ → báo đỏ ngay dưới ô.'],
                        ['Bấm Lưu', 'Click', 'During:\n– Kiểm tra định dạng, bắt buộc, độ dài, trùng mã/tên.\n– Có lỗi → báo đỏ dưới ô, không thực hiện After.\nAfter:\n– Ghi bản ghi mới (Mã IN HOA).\n– Đóng cửa sổ, nạp lại danh sách, báo “Thêm mới thành công”.'],
                        ['Bấm Lưu và tiếp tục', 'Click', 'During:\n– Như nút Lưu.\nAfter:\n– Ghi bản ghi, xóa trắng các ô, GIỮ cửa sổ mở.'],
                        ['Bấm Đóng', 'Click', 'After:\n– Chưa nhập gì → đóng cửa sổ. Đã nhập → hỏi “Thông tin chưa lưu”.']]},
            {'ten': 'Chỉnh sửa loại tài khoản', 'uc': 'uc_fr04',
             'qtc': 'Validate dữ liệu, Thông báo, Quy định chung về danh mục và Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Chỉnh sửa loại tài khoản'],
                            ['Mô tả', 'Sửa thông tin một loại tài khoản đã có. Dùng chung cửa sổ với Thêm mới.'],
                            ['Tác nhân', 'Người có quyền “%s”' % Q_QL],
                            ['Điều kiện ban đầu', 'Loại tài khoản đang ở trạng thái Hoạt động.'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm biểu tượng bút chì ở dòng cần sửa.\n2. Hệ thống mở cửa sổ “Sửa loại tài khoản” với dữ liệu hiện tại.\n3. Người dùng sửa và bấm Lưu.\n4. Hệ thống kiểm tra, ghi thay đổi và ghi lịch sử các trường đã đổi.\n5. Cửa sổ đóng, báo “Cập nhật thành công”.'],
                            ['Dòng sự kiện phụ', '• Giữ nguyên mã/tên của chính bản ghi → không báo trùng.\n• Loại đang được sử dụng mà chọn Trạng thái = Khóa → báo “Loại tài khoản đang được sử dụng, không thể khóa”.\n• Bản ghi vừa bị người khác khóa → báo “Loại tài khoản đang bị khoá, vui lòng mở khoá trước khi cập nhật.”']],
             'menu_them': ' => Sửa {icon:btn_sua}',
             'anh': [('edit', 'Cửa sổ Sửa loại tài khoản')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Phạm vi', 'Bắt buộc', 'Giá trị ban đầu', 'Mô tả'],
                    ['1', 'Biểu tượng bút chì (Sửa)', 'Icon Button', 'Enable', '–', '–', 'Hiển thị', 'Nằm ở cột Hành động. Chỉ hiện với quyền Quản lý và khi loại tài khoản đang Hoạt động.'],
                    ['2', 'Tiêu đề cửa sổ', 'Label', 'Read-only', '–', '–', 'Sửa loại tài khoản', ''],
                    ['3', 'Mã loại tài khoản', 'Textbox', 'Enable', '1–255 ký tự: A-Z, a-z, 0-9, - và _', 'Có', 'Dữ liệu hiện tại', 'Gõ sai ký tự báo ngay “Chỉ gồm chữ không dấu, số, dấu - và _”. Tự bỏ khoảng trắng hai đầu, tự IN HOA khi lưu. Bỏ trống “Bắt buộc phải nhập”; trùng bản ghi khác “Mã loại tài khoản đã tồn tại”.'],
                    ['4', 'Trạng thái', 'Dropdown', 'Enable / Disable', 'Hoạt động / Khóa', 'Không', 'Dữ liệu hiện tại', 'Không xóa trắng được. Loại đang được sử dụng thì ô bị khóa (Disable) ở Hoạt động.'],
                    ['5', 'Tên loại tài khoản', 'Textbox', 'Enable', '1–255 ký tự', 'Có', 'Dữ liệu hiện tại', 'Bỏ trống “Bắt buộc phải nhập”; trùng bản ghi khác “Tên loại tài khoản đã tồn tại”.'],
                    ['6', 'Ghi chú', 'Textbox', 'Enable', '0–255 ký tự', 'Không', 'Dữ liệu hiện tại', 'Placeholder “Ghi chú thêm (nếu có)”.'],
                    ['7', 'Nút Lưu', 'Button', 'Enable', '–', '–', 'Hiển thị', 'Ghi thay đổi rồi đóng cửa sổ. Không có nút “Lưu và tiếp tục” khi Sửa.'],
                    ['8', 'Nút Đóng / biểu tượng ×', 'Button', 'Enable', '–', '–', 'Hiển thị', 'Hủy bỏ. Đã sửa dở thì hỏi “Thông tin chưa lưu” (Thoát / Ở lại).']],
             'ui_widths': [0.4, 1.1, 0.7, 0.7, 1.1, 0.5, 0.8, 2.0],
             'events': [['Bấm biểu tượng bút chì', 'Click', 'Before:\n– Bản ghi đã Khóa thì nút không hiển thị.\nAfter:\n– Mở cửa sổ “Sửa loại tài khoản” với dữ liệu hiện tại; loại đang được sử dụng thì ô Trạng thái bị khóa.\n– Bản ghi không còn tồn tại → báo “Dữ liệu đã thay đổi, vui lòng tải lại”, không mở cửa sổ.'],
                        ['Bấm Lưu', 'Click', 'Before:\n– Bản ghi vừa bị người khác Khóa → máy chủ chặn “Loại tài khoản đang bị khoá, vui lòng mở khoá trước khi cập nhật.”, không kiểm tra tiếp.\nDuring:\n– Kiểm tra như Thêm mới, bỏ qua trùng với chính bản ghi.\n– Chọn Trạng thái = Khóa khi loại đang được sử dụng → báo “Loại tài khoản đang được sử dụng, không thể khóa”.\n– Có lỗi → báo đỏ dưới ô + toast “Bạn chưa nhập đầy đủ thông tin”, không thực hiện After.\nAfter:\n– Ghi thay đổi, ghi lịch sử “Thay đổi thông tin” cho từng trường đổi.\n– Đóng cửa sổ, nạp lại danh sách, báo “Cập nhật thành công”.'],
                        ['Bấm Đóng / ×', 'Click', 'After:\n– Chưa sửa gì → đóng cửa sổ. Đã sửa → hỏi “Thông tin chưa lưu”: Thoát (đóng, không ghi) / Ở lại (giữ nguyên dữ liệu đang sửa).']]},
            {'ten': 'Xóa loại tài khoản', 'uc': 'uc_fr05',
             'qtc': 'Quy tắc Xóa, Thông báo, Quy định chung về danh mục.',
             'gioi_thieu': [['Tên chức năng', 'Xóa loại tài khoản'],
                            ['Mô tả', 'Xóa hẳn một loại tài khoản chưa được tài khoản nào sử dụng.'],
                            ['Tác nhân', 'Người có quyền “%s”' % Q_QL],
                            ['Điều kiện ban đầu', 'Chưa có tài khoản nào ở Danh mục tài khoản được gán loại này.'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm biểu tượng thùng rác.\n2. Hệ thống hiện hộp “Xác nhận xóa” nêu rõ tên bản ghi.\n3. Người dùng bấm Xóa.\n4. Hệ thống xóa bản ghi cùng lịch sử của nó, báo “Xóa thành công”, nạp lại danh sách.'],
                            ['Dòng sự kiện phụ', '• Bấm Hủy → đóng hộp, không thay đổi.\n• Loại đang được sử dụng → nút Xóa KHÔNG hiển thị; nếu vừa bị gán trước khi xác nhận → báo “Loại tài khoản đang được sử dụng, không thể xóa”.']],
             'menu_them': ' => Xóa {icon:btn_xoa}',
             'anh': [('delete', 'Hộp xác nhận xóa loại tài khoản')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Mô tả'],
                    ['1', 'Biểu tượng thùng rác (Xóa)', 'Icon Button', 'Nằm ở cột Hành động. Chỉ hiện với quyền Quản lý và khi CHƯA có tài khoản nào được gán loại này.'],
                    ['2', 'Tiêu đề hộp xác nhận', 'Label', '“Xác nhận xóa”.'],
                    ['3', 'Nội dung hộp xác nhận', 'Label', '“Bạn có chắc muốn xóa loại tài khoản \'<tên>\'?” — nêu rõ tên bản ghi để tránh xóa nhầm dòng.'],
                    ['4', 'Nút Xóa', 'Button', 'Xác nhận xóa hẳn bản ghi.'],
                    ['5', 'Nút Hủy', 'Button', 'Đóng hộp, không làm gì.']],
             'ui_widths': [0.6, 1.8, 1, 3.6],
             'events': [['Bấm biểu tượng thùng rác', 'Click', 'Before:\n– Loại đang được sử dụng thì nút không hiển thị.\nAfter:\n– Hiện hộp “Xác nhận xóa” kèm tên bản ghi.'],
                        ['Bấm Xóa', 'Click', 'During:\n– Bản ghi đang Khóa → máy chủ chặn “Loại tài khoản đang bị khoá, vui lòng mở khoá trước khi cập nhật.”.\n– Máy chủ kiểm tra lại tình trạng sử dụng; vừa bị gán cho tài khoản → báo “Loại tài khoản đang được sử dụng, không thể xóa”, dừng xử lý.\nAfter:\n– Xóa hẳn bản ghi cùng lịch sử thay đổi của nó.\n– Nạp lại danh sách, báo “Xóa thành công”.'],
                        ['Bấm Hủy', 'Click', 'After:\n– Đóng hộp, không thay đổi.']]},
            {'ten': 'Khóa / Mở khóa loại tài khoản', 'uc': 'uc_fr06',
             'qtc': 'Quy tắc Khóa/Mở khóa, Thông báo, Quy định chung về danh mục và Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Khóa / Mở khóa loại tài khoản'],
                            ['Mô tả', 'Đổi trạng thái loại tài khoản giữa Hoạt động và Khóa.'],
                            ['Tác nhân', 'Người có quyền “%s”' % Q_QL],
                            ['Điều kiện ban đầu', 'Khóa: loại đang Hoạt động VÀ chưa được tài khoản nào sử dụng. Mở khóa: loại đang Khóa.'],
                            ['Dòng sự kiện chính', '1. Người dùng chọn Khóa (hoặc Mở khóa) ở cột Hành động.\n2. Hệ thống hiện hộp xác nhận nêu rõ tên bản ghi.\n3. Người dùng xác nhận.\n4. Hệ thống đổi trạng thái, ghi lịch sử trường Trạng thái, báo “Khóa thành công” / “Mở khóa thành công”.'],
                            ['Dòng sự kiện phụ', '• Bấm Hủy → không thay đổi.\n• Loại vừa bị gán cho tài khoản → báo “Loại tài khoản đang được sử dụng, không thể khóa”.\n• Bản ghi đã được người khác mở khóa → báo “Dữ liệu đã thay đổi, vui lòng tải lại”.']],
             'menu_them': ' => Khóa / Mở khóa',
             'anh': [('lock', 'Hộp xác nhận khóa loại tài khoản'), ('rowmenu', 'Các nút ở cột Hành động')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Mô tả'],
                    ['1', 'Nút ba chấm “Hành động khác”', 'Icon Button', 'Xuất hiện khi dòng có từ 4 nút trở lên: 2 nút đầu hiện thẳng, các nút còn lại (Khóa / Mở khóa, Lịch sử) nằm trong menu này.'],
                    ['2', 'Mục Khóa / Mở khóa', 'Button', 'Nhãn đổi theo trạng thái. Khóa: chỉ hiện với quyền Quản lý, loại đang Hoạt động VÀ chưa được sử dụng. Mở khóa: quyền Quản lý, loại đang Khóa.'],
                    ['3', 'Tiêu đề hộp xác nhận', 'Label', '“Xác nhận khóa” hoặc “Xác nhận mở khóa”.'],
                    ['4', 'Nội dung hộp xác nhận', 'Label', '“Bạn có chắc muốn khóa loại tài khoản \'<tên>\'?” (hoặc “…mở khóa…”).'],
                    ['5', 'Nút Khóa / Mở khóa', 'Button', 'Xác nhận thực hiện.'],
                    ['6', 'Nút Hủy', 'Button', 'Đóng hộp, không làm gì.'],
                    ['7', 'Cột Trạng thái', 'Badge', 'Hoạt động hoặc Khóa, hai màu khác nhau.']],
             'ui_widths': [0.6, 1.8, 1, 3.6],
             'events': [['Bấm nút ba chấm', 'Click', 'After:\n– Mở menu các thao tác còn lại của dòng (Khóa / Mở khóa, Lịch sử).'],
                        ['Chọn Khóa / Mở khóa', 'Click', 'After:\n– Hiện hộp xác nhận kèm tên bản ghi.'],
                        ['Xác nhận', 'Click', 'During:\n– Khóa: loại vừa bị gán cho tài khoản (hoặc không còn ở trạng thái Hoạt động) → báo “Loại tài khoản đang được sử dụng, không thể khóa”, dừng xử lý.\n– Mở khóa: bản ghi đã được người khác mở khóa → báo “Dữ liệu đã thay đổi, vui lòng tải lại”, dừng xử lý.\nAfter:\n– Đổi trạng thái, KHÔNG xóa dữ liệu; ghi lịch sử trường Trạng thái.\n– Báo “Khóa thành công” / “Mở khóa thành công”, nạp lại danh sách, cập nhật cột Trạng thái và các nút của dòng.'],
                        ['Bấm Hủy', 'Click', 'After:\n– Đóng hộp, không thay đổi.']]},
            {'ten': 'Xem lịch sử thay đổi',
             'qtc': 'Quy tắc ghi lịch sử và hiển thị lịch sử. Chỉ bổ sung thông tin riêng của Danh mục loại tài khoản.',
             'gioi_thieu': [['Tên chức năng', 'Xem lịch sử thay đổi'],
                            ['Mô tả', 'Liệt kê các lần thay đổi của một loại tài khoản, kèm giá trị cũ → mới, người thực hiện và thời điểm.'],
                            ['Tác nhân', 'Người có quyền Quản lý hoặc Xem danh mục loại tài khoản'],
                            ['Dòng sự kiện chính', '1. Người dùng chọn Lịch sử ở cột Hành động, hoặc mở cửa sổ Xem loại tài khoản.\n2. Hệ thống mở cửa sổ “Lịch sử thay đổi: <mã> - <tên>”, mốc mới nhất ở trên cùng.'],
                            ['Dòng sự kiện phụ', '• Khóa / Mở khóa hiện là Thay đổi thông tin ở trường Trạng thái.\n• Tạo mới / Import chưa sinh mốc lịch sử; bản ghi chưa từng sửa → “Chưa có lịch sử thao tác nào.”']],
             'menu_them': ' => Lịch sử',
             'anh': [('history', 'Cửa sổ Lịch sử thay đổi của loại tài khoản')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Giá trị ban đầu', 'Mô tả'],
                    ['1', 'Mục Lịch sử', 'Button', 'Hiển thị', 'Nằm ở cột Hành động (trong nút ba chấm nếu dòng có nhiều nút). Mọi người vào được màn hình đều thấy.'],
                    ['2', 'Tiêu đề cửa sổ', 'Label', 'Lịch sử thay đổi: <mã> - <tên>', 'Ghép mã và tên loại tài khoản để biết đang xem dòng nào.'],
                    ['3', 'Nút Bộ lọc', 'Button', 'Hiển thị', 'Mở / thu gọn vùng lọc; vùng lọc ghim ở đầu khi cuộn.'],
                    ['4', 'Loại hành động', 'Dropdown', 'Trống (placeholder “Tất cả loại hành động”)', 'Chọn một loại hành động đã phát sinh của bản ghi. Lọc ngay khi chọn.'],
                    ['5', 'Người thực hiện', 'Dropdown', 'Trống (placeholder “Tất cả người thực hiện”)', 'Chọn một người đã thao tác trên bản ghi. Lọc ngay khi chọn.'],
                    ['6', 'Từ ngày / Đến ngày', 'Datepicker', 'Trống', 'dd/mm/yyyy, tính cả hai đầu. Lọc ngay khi chọn.'],
                    ['7', 'Nút Làm mới (trong vùng lọc)', 'Button', 'Hiển thị', 'Xóa hết tiêu chí lọc.'],
                    ['8', 'Danh sách thay đổi', 'Timeline', 'Theo dữ liệu', 'Mới nhất ở trên cùng. Mỗi mốc gồm: thời điểm; loại hành động (vd Thay đổi thông tin); “Người thực hiện: <tên>” kèm phòng ban; từng trường đã đổi dạng “Trường: giá trị cũ → giá trị mới”.'],
                    ['9', 'Trạng thái rỗng', 'Label', 'Ẩn', '“Chưa có lịch sử thao tác nào.” khi bản ghi chưa từng sửa; “Không có lịch sử phù hợp bộ lọc.” khi lọc không ra mốc nào.'],
                    ['10', 'Nút Đóng / biểu tượng ×', 'Button', 'Hiển thị', 'Đóng cửa sổ.']],
             'ui_widths': [0.5, 1.5, 0.9, 1.5, 3],
             'events': [['Chọn Lịch sử ở cột Hành động', 'Click', 'After:\n– Mở cửa sổ “Lịch sử thay đổi: <mã> - <tên>” và nạp danh sách mốc thay đổi, mới nhất trước.\n– Lỗi tải → hiện thông báo lỗi kèm nút Thử lại.'],
                        ['Bấm Bộ lọc', 'Click', 'After:\n– Mở / thu gọn vùng lọc.'],
                        ['Đổi một ô lọc', 'Change', 'After:\n– Lọc ngay danh sách mốc theo tiêu chí đã chọn (kết hợp kiểu “và”).'],
                        ['Bấm Làm mới trong vùng lọc', 'Click', 'After:\n– Xóa hết tiêu chí, hiện lại toàn bộ mốc.'],
                        ['Bấm Đóng / ×', 'Click', 'After:\n– Đóng cửa sổ; danh sách phía sau giữ nguyên bộ lọc và trang.']]},
            {'ten': 'Import file loại tài khoản', 'uc': 'uc_fr08',
             'qtc': 'Quy tắc Import file, Validate dữ liệu, Thông báo và Quy định chung về danh mục. Chỉ bổ sung mapping/validation riêng.',
             'gioi_thieu': [['Tên chức năng', 'Import file loại tài khoản'],
                            ['Mô tả', 'Thêm nhiều loại tài khoản cùng lúc từ file Excel mẫu, có bước Validate trước khi ghi.'],
                            ['Tác nhân', 'Người có quyền “%s”' % Q_QL],
                            ['Điều kiện ban đầu', 'Đang ở màn Danh mục loại tài khoản và đã chuẩn bị file theo mẫu.'],
                            ['Dòng sự kiện chính', '1. Bấm Import Excel.\n2. Bấm Tải file mẫu (Mau_import_loai_tai_khoan.xlsx), điền dữ liệu từ hàng 2.\n3. Bấm Chọn file Excel rồi Load lên bảng.\n4. Bấm Validate; hệ thống kiểm tra từng dòng, khóa dòng hợp lệ.\n5. Sửa dòng lỗi rồi Validate lại, hoặc bấm Bỏ dòng lỗi.\n6. Bấm Import; hệ thống ghi các dòng hợp lệ, báo “Import thành công N loại tài khoản.”, đóng cửa sổ và nạp lại danh sách.'],
                            ['Dòng sự kiện phụ', '• File không phải .xlsx/.xls → “Vui lòng chọn file .xlsx hoặc .xls”.\n• File không có dòng dữ liệu → “Không có dòng dữ liệu hợp lệ.”\n• Quá 500 dòng → báo vượt giới hạn 500 dòng.\n• Còn dòng lỗi → nút Import không bấm được.'],
                            ['Yêu cầu đặc biệt', 'Validate không ghi dữ liệu. Mã tự IN HOA. Trạng thái theo cột Trạng thái (để trống = Hoạt động). Người tạo là người thực hiện.']],
             'menu_them': ' => Import Excel {icon:btn_import}',
             'ghi_chu_layout': 'Cửa sổ Import được mở ngay trên màn hình danh sách.',
             'anh': [('import_open', 'Cửa sổ Import loại tài khoản khi vừa mở'), ('import_loaded', 'Dữ liệu đã được load lên bảng xem trước'),
                     ('import_validated', 'Kết quả Validate — mỗi dòng lỗi nêu rõ lý do')],
             'bang_them': [('Quy tắc kiểm tra riêng của file Import', [['Cột', 'Quy tắc / thông báo lỗi'],
                            ['Mã loại tài khoản *', 'Bắt buộc (“Mã loại tài khoản không được để trống”), tối đa 255 ký tự, chỉ chữ không dấu/số/-/_ (“Mã loại tài khoản: Chỉ gồm chữ không dấu, số, dấu - và _”), không trùng trong file (“Mã loại tài khoản bị trùng trong file import (dòng N)”), không trùng hệ thống (“Mã loại tài khoản đã tồn tại trong hệ thống”). Tự IN HOA.'],
                            ['Tên loại tài khoản *', 'Bắt buộc (“Tên loại tài khoản không được để trống”), tối đa 255 ký tự; không trùng tên đã có như khi nhập tay.'],
                            ['Ghi chú', 'Tối đa 255 ký tự (“Ghi chú tối đa 255 ký tự”).'],
                            ['Trạng thái', 'Hoạt động / Khóa; để trống = Hoạt động; giá trị khác báo “Trạng thái chỉ nhận "Hoạt động" hoặc "Khóa"”.']], [1.3, 4])],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Bắt buộc', 'Giá trị ban đầu', 'Mô tả'],
                    ['1', 'Nút Import Excel', 'Button', 'Enable', '–', 'Hiển thị', 'Trên thanh công cụ của bảng danh sách, chỉ hiện với quyền Quản lý. Mở cửa sổ Import.'],
                    ['2', 'Tiêu đề cửa sổ', 'Label', 'Read-only', '–', 'Import loại tài khoản', 'Dòng phụ “Import từ Excel • Validate xong dòng hợp lệ sẽ bị khoá”.'],
                    ['3', 'Nút Chọn file Excel', 'Button', 'Enable', 'Có', 'Chưa chọn file', 'Chọn file .xlsx / .xls từ máy; tên file hiện ngay cạnh nút.'],
                    ['4', 'Nút Tải file mẫu', 'Button', 'Enable', '–', 'Hiển thị', 'Tải Mau_import_loai_tai_khoan.xlsx gồm 4 cột: Mã loại tài khoản *, Tên loại tài khoản *, Ghi chú, Trạng thái; có sẵn 2 dòng ví dụ LTK001, LTK002.'],
                    ['5', 'Nút Load lên bảng', 'Button', 'Enable / Disable', '–', 'Mờ khi chưa chọn file', 'Đọc file và đổ dữ liệu lên bảng xem trước (tối đa 500 dòng mỗi lần).'],
                    ['6', 'Nút Validate', 'Button', 'Enable / Disable', '–', 'Mờ khi bảng chưa có dòng nào', 'Gửi dữ liệu lên máy chủ kiểm tra từng dòng; dòng hợp lệ bị khóa lại, không sửa được nữa.'],
                    ['7', 'Nút Import', 'Button', 'Enable / Disable', '–', 'Mờ', 'Chỉ bấm được khi đã Validate, KHÔNG còn dòng lỗi và có ít nhất 1 dòng hợp lệ.'],
                    ['8', 'Ô Tổng / Hợp lệ / Lỗi', 'Label', 'Read-only', '–', 'Tổng: 0', 'Sau khi Load hiện “Tổng” = số dòng đọc được; sau khi Validate hiện thêm “Hợp lệ” và “Lỗi”.'],
                    ['9', 'Bảng xem trước', 'Table/Grid', 'Enable', '–', 'Ẩn', 'Cột STT (đánh 1, 2, 3… theo thứ tự dòng dữ liệu), Mã loại tài khoản *, Tên loại tài khoản *, Ghi chú, Trạng thái. Sửa trực tiếp được ở dòng lỗi / dòng chưa Validate.'],
                    ['10', 'Thông báo lỗi', 'Label', 'Hiển thị', '–', 'Ẩn', 'Lỗi chung hiện ở dải đỏ phía trên bảng; dòng lỗi được tô đỏ, lý do ghi ngay dưới dòng. Sửa một ô của dòng lỗi thì dòng đó trở về trạng thái chưa Validate.'],
                    ['11', 'Nút Bỏ dòng lỗi', 'Button', 'Enable / Disable', '–', 'Hiện khi bảng có dữ liệu', 'Loại toàn bộ dòng đang lỗi khỏi bảng, báo “Đã bỏ N dòng lỗi. Còn lại M dòng hợp lệ.”.'],
                    ['12', 'Nút Xoá trạng thái validate', 'Button', 'Enable / Disable', '–', 'Hiện khi bảng có dữ liệu', 'Bỏ khóa các dòng hợp lệ và xóa kết quả Validate để sửa lại.'],
                    ['13', 'Nút Làm mới', 'Button', 'Enable', '–', 'Hiển thị', 'Xóa file đã chọn và toàn bộ bảng, về trạng thái vừa mở.'],
                    ['14', 'Nút Đóng / biểu tượng ×', 'Button', 'Enable', '–', 'Hiển thị', 'Đóng cửa sổ, không ghi gì.']],
             'ui_widths': [0.4, 1.3, 0.8, 0.8, 0.5, 1.1, 2.4],
             'events': [['Bấm Import Excel', 'Click', 'After:\n– Mở cửa sổ “Import loại tài khoản” ở trạng thái rỗng.'],
                        ['Bấm Tải file mẫu', 'Click', 'After:\n– Tải file Mau_import_loai_tai_khoan.xlsx về máy.'],
                        ['Bấm Chọn file Excel', 'Click', 'During:\n– File không phải .xlsx / .xls → báo “Vui lòng chọn file .xlsx hoặc .xls”.\nAfter:\n– Hiện tên file cạnh nút, nút Load lên bảng sáng lên.'],
                        ['Bấm Load lên bảng', 'Click', 'During:\n– File không có dòng dữ liệu → “Không có dòng dữ liệu hợp lệ.”.\n– Quá 500 dòng → “File có X dòng dữ liệu, vượt quá giới hạn 500 dòng mỗi lần import. Vui lòng tách file và import nhiều lần.”.\n– File hỏng / không đọc được → “Không đọc được file Excel.”.\nAfter:\n– Đổ dữ liệu lên bảng xem trước, cập nhật ô Tổng.'],
                        ['Bấm Validate', 'Click', 'During:\n– Máy chủ kiểm tra từng dòng theo bảng quy tắc riêng của file Import (bắt buộc, độ dài, ký tự Mã, trùng trong file, trùng hệ thống, giá trị Trạng thái).\nAfter:\n– Có dòng lỗi: tô đỏ dòng lỗi kèm lý do, khóa dòng hợp lệ, báo “Validate xong: N hợp lệ, M không hợp lệ. (Dòng hợp lệ đã bị khoá, chỉ có thể sửa dòng lỗi)”.\n– Không có dòng lỗi: khóa toàn bộ dòng, báo “Tất cả N dòng đã hợp lệ. Có thể import ngay.”, nút Import sáng lên.\n– KHÔNG ghi bản ghi nào ở bước này.'],
                        ['Sửa ô ở dòng lỗi', 'Input', 'After:\n– Dòng đó trở về trạng thái chưa Validate; phải bấm Validate lại.'],
                        ['Bấm Bỏ dòng lỗi', 'Click', 'Before:\n– Chưa Validate → báo “Hãy Validate trước rồi mới bỏ dòng lỗi.”.\nAfter:\n– Loại các dòng lỗi khỏi bảng, báo “Đã bỏ N dòng lỗi. Còn lại M dòng hợp lệ.”.'],
                        ['Bấm Import', 'Click', 'During:\n– Máy chủ kiểm tra lại toàn bộ dòng gửi lên, bỏ qua dòng lỗi; không còn dòng hợp lệ → “Không có dòng nào hợp lệ để import”.\nAfter:\n– Ghi các dòng hợp lệ thành loại tài khoản mới (Mã IN HOA, Trạng thái theo cột Trạng thái, người tạo là người thực hiện).\n– Báo “Import thành công N loại tài khoản.” (có dòng thất bại thì “Import thành công S/T loại tài khoản. F dòng thất bại.”), đóng cửa sổ và nạp lại danh sách.'],
                        ['Bấm Làm mới', 'Click', 'After:\n– Xóa file đã chọn, bảng xem trước và kết quả Validate.'],
                        ['Bấm Đóng / ×', 'Click', 'After:\n– Đóng cửa sổ, không ghi dữ liệu.']]},
            {'ten': 'Xuất danh sách ra Excel', 'uc': 'uc_fr09',
             'qtc': 'Quy tắc Excel và Cấu hình cột. Chỉ bổ sung danh sách trường được phép xuất riêng.',
             'gioi_thieu': [['Tên chức năng', 'Xuất danh sách loại tài khoản ra Excel'],
                            ['Mô tả', 'Xuất kết quả đang lọc ra file Excel, cho phép chọn trường và thứ tự cột.'],
                            ['Tác nhân', 'Người có quyền Quản lý hoặc Xem danh mục loại tài khoản'],
                            ['Dòng sự kiện chính', '1. Bấm Xuất Excel.\n2. Hệ thống mở cửa sổ “Chọn trường xuất file”, tích sẵn đúng các cột đang hiển thị trên bảng.\n3. Người dùng tích chọn và kéo ☰ để sắp thứ tự.\n4. Bấm Xuất file; hệ thống tải danh_muc_loai_tai_khoan.xlsx theo đúng bộ lọc và thứ tự trường, báo “Xuất Excel thành công”.'],
                            ['Dòng sự kiện phụ', '• Bỏ chọn hết trường → nút Xuất file không bấm được.\n• Bấm Đóng → không xuất gì.'],
                            ['Yêu cầu đặc biệt', 'File chứa toàn bộ kết quả lọc (không giới hạn ở trang đang xem), có cột STT ở đầu và tiêu đề “Danh mục loại tài khoản”.']],
             'menu_them': ' => Xuất Excel {icon:btn_xuatexcel}',
             'anh': [('export', 'Cửa sổ Chọn trường xuất file')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
                    ['1', 'Danh sách trường', 'Checkbox chọn nhiều', 'Enable', 'Tích sẵn cột đang hiển thị', 'Mã loại tài khoản, Tên loại tài khoản, Ghi chú, Trạng thái, Người tạo, Ngày tạo. Kéo ☰ đổi thứ tự.'],
                    ['2', 'Nút Chọn tất cả / Bỏ chọn hết', 'Button', 'Enable', 'Hiển thị', 'Tích / bỏ tích toàn bộ.'],
                    ['3', 'Nút Xuất file', 'Button', 'Enable/Disable', 'Mờ khi chưa chọn trường', 'Sinh file và tải về.'],
                    ['4', 'Nút Đóng', 'Button', 'Enable', 'Hiển thị', 'Đóng cửa sổ.']],
             'ui_widths': [0.6, 1.5, 1, 0.8, 1.2, 2.6],
             'events': [['Bấm Xuất Excel', 'Click', 'After:\n– Mở cửa sổ “Chọn trường xuất file”: các trường ứng với cột đang hiển thị trên bảng được tích sẵn và xếp lên đầu theo đúng thứ tự trên bảng, các trường còn lại nằm dưới, chưa tích.'],
                        ['Tích / bỏ tích trường, kéo ☰', 'Change', 'During:\n– Thứ tự từ trên xuống của các trường đang tích là thứ tự cột trong file; dòng chân cửa sổ hiện “Đang chọn X/Y trường”.\n– Bỏ tích hết → nút Xuất file mờ đi.'],
                        ['Bấm Chọn tất cả / Bỏ chọn hết', 'Click', 'After:\n– Tích / bỏ tích toàn bộ trường.'],
                        ['Bấm Xuất file', 'Click', 'During:\n– Sinh file theo ĐÚNG bộ lọc và thứ tự sắp xếp đang áp dụng, lấy toàn bộ kết quả (không theo trang), cột theo đúng trường và thứ tự đã chọn.\nAfter:\n– Tải file danh_muc_loai_tai_khoan.xlsx về máy, báo “Xuất Excel thành công”.\n– Lỗi → báo “Lỗi khi xuất Excel”.'],
                        ['Bấm Đóng / ×', 'Click', 'After:\n– Đóng cửa sổ, không xuất gì.']]},
            {'ten': 'Xem chi tiết loại tài khoản', 'uc': 'uc_fr10',
             'qtc': 'Màn Xem chi tiết và Phân quyền.',
             'gioi_thieu': [['Tên chức năng', 'Xem chi tiết loại tài khoản'],
                            ['Mô tả', 'Cửa sổ “Xem loại tài khoản” hiển thị Mã, Trạng thái, Tên, Ghi chú ở chế độ chỉ đọc, kèm khối Lịch sử.'],
                            ['Tác nhân', 'Người có quyền Quản lý hoặc Xem danh mục loại tài khoản'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm mã loại tài khoản ở danh sách.\n2. Hệ thống mở cửa sổ Xem, chỉ có nút Đóng.']],
             'anh': [('detail', 'Cửa sổ Xem loại tài khoản ở chế độ chỉ đọc')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
                    ['1', 'Mã loại tài khoản (ở danh sách)', 'Link', 'Enable', 'Hiển thị', 'Bấm vào mã ở cột Mã loại tài khoản để mở cửa sổ Xem. Mọi người vào được màn hình đều bấm được, kể cả khi loại đang Khóa.'],
                    ['2', 'Tiêu đề cửa sổ', 'Label', 'Read-only', 'Xem loại tài khoản', ''],
                    ['3', 'Mã loại tài khoản', 'Textbox', 'Read-only', 'Dữ liệu hiện tại', 'Không sửa được.'],
                    ['4', 'Trạng thái', 'Dropdown', 'Read-only', 'Dữ liệu hiện tại', 'Hoạt động hoặc Khóa, không đổi được.'],
                    ['5', 'Tên loại tài khoản', 'Textbox', 'Read-only', 'Dữ liệu hiện tại', 'Không sửa được.'],
                    ['6', 'Ghi chú', 'Textbox', 'Read-only', 'Dữ liệu hiện tại', 'Không sửa được.'],
                    ['7', 'Khối Lịch sử', 'Section', 'Enable', 'Thu gọn', 'Nằm cuối cửa sổ. Nút “Xem lịch sử” mở khối (“Thu gọn” để đóng lại); khi đã mở có nút Làm mới. Nội dung, bộ lọc và thông báo rỗng giống cửa sổ Lịch sử thay đổi (xem 2.7).'],
                    ['8', 'Nút Đóng / biểu tượng ×', 'Button', 'Enable', 'Hiển thị', 'Nút duy nhất ở chân cửa sổ. Không có nút Lưu, Sửa hay In.']],
             'ui_widths': [0.5, 1.6, 0.8, 0.8, 1.1, 3],
             'events': [['Bấm mã loại tài khoản', 'Click', 'After:\n– Nạp dữ liệu mới nhất của bản ghi và mở cửa sổ “Xem loại tài khoản” ở chế độ chỉ đọc.\n– Bản ghi không còn tồn tại → báo “Dữ liệu đã thay đổi, vui lòng tải lại”, không mở cửa sổ.'],
                        ['Bấm Xem lịch sử / Thu gọn', 'Click', 'After:\n– Mở khối Lịch sử (lần mở đầu mới nạp dữ liệu, mới nhất trước) / thu gọn lại.'],
                        ['Bấm Làm mới trong khối Lịch sử', 'Click', 'After:\n– Nạp lại danh sách mốc thay đổi.'],
                        ['Bấm Đóng / ×', 'Click', 'After:\n– Đóng cửa sổ, danh sách phía sau giữ nguyên.']]},
            {'ten': 'Tùy chỉnh cột hiển thị',
             'qtc': 'Tùy chỉnh cột.',
             'gioi_thieu': [['Tên chức năng', 'Tùy chỉnh cột hiển thị'],
                            ['Mô tả', 'Bật/tắt và sắp xếp thứ tự cột của bảng; cấu hình lưu riêng theo người dùng.'],
                            ['Yêu cầu đặc biệt', 'Cột STT, Mã loại tài khoản, Hành động bị khóa. Mặc định ẩn: Ghi chú, Người cập nhật, Ngày cập nhật.']],
             'menu_them': ' => Cấu hình cột {icon:btn_cauhinhcot}',
             'anh': [('colcfg', 'Cửa sổ Tuỳ chỉnh cột')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
                    ['1', 'Biểu tượng Cấu hình cột hiển thị', 'Icon Button', 'Enable', 'Hiển thị', 'Nằm cuối thanh công cụ của bảng, mọi người vào được màn hình đều thấy. Mở cửa sổ “Tuỳ chỉnh cột”.'],
                    ['2', 'Danh sách cột', 'Checkbox chọn nhiều', 'Enable', 'Theo cấu hình đang áp dụng', 'Đủ 10 cột theo thứ tự trên bảng: STT, Mã loại tài khoản, Tên loại tài khoản, Ghi chú, Người cập nhật, Ngày cập nhật, Người tạo, Ngày tạo, Trạng thái, Hành động. Lần đầu (chưa lưu cấu hình) bỏ tích sẵn Ghi chú, Người cập nhật, Ngày cập nhật.'],
                    ['3', 'Cột bắt buộc', 'Checkbox', 'Disable', 'Đã tích', 'STT, Mã loại tài khoản, Hành động: hiển thị xám kèm biểu tượng ổ khóa (“Cột bắt buộc — không thể ẩn hoặc đổi vị trí”), không bỏ tích và không kéo được.'],
                    ['4', 'Biểu tượng ☰', 'Drag handle', 'Enable', 'Hiển thị', 'Kéo thả để đổi thứ tự các cột không bắt buộc.'],
                    ['5', 'Nút Lưu', 'Button', 'Enable', 'Hiển thị', 'Áp dụng ngay lên bảng và lưu cấu hình trên máy chủ theo từng người dùng (đổi máy / trình duyệt vẫn giữ).'],
                    ['6', 'Nút Đóng / biểu tượng ×', 'Button', 'Enable', 'Hiển thị', 'Đóng cửa sổ, bỏ các thay đổi chưa Lưu.']],
             'ui_widths': [0.5, 1.5, 1, 0.7, 1.2, 3],
             'events': [['Bấm biểu tượng Cấu hình cột hiển thị', 'Click', 'After:\n– Mở cửa sổ “Tuỳ chỉnh cột” với cấu hình đang áp dụng.'],
                        ['Tích / bỏ tích, kéo ☰', 'Change', 'During:\n– Cột bắt buộc không bỏ tích và không kéo được.'],
                        ['Bấm Lưu', 'Click', 'After:\n– Bảng hiển thị ngay theo cấu hình mới, lưu cấu hình theo người dùng, báo “Cập nhật thành công”, đóng cửa sổ.\n– Lưu lỗi → báo “Thao tác thất bại”.'],
                        ['Bấm Đóng / ×', 'Click', 'After:\n– Đóng cửa sổ, trả danh sách cột về đúng cấu hình đang áp dụng.']]},
        ],
        'quy_tac': [
            ('BR-01', 'Ràng buộc mã loại tài khoản',
             ['Mã chỉ gồm chữ không dấu, số, dấu - và _; tối đa 255 ký tự.',
              'Hệ thống tự bỏ khoảng trắng hai đầu và lưu mã ở dạng CHỮ IN HOA (cả nhập tay lẫn Import).',
              'Mã không được trùng trong danh mục, không phân biệt chữ hoa/chữ thường. Thông báo khi trùng: “Mã loại tài khoản đã tồn tại”.'],
             ['Thêm mới loại tài khoản', 'Chỉnh sửa loại tài khoản', 'Import file loại tài khoản']),
            ('BR-02', 'Ràng buộc trùng tên',
             ['Tên loại tài khoản không được trùng trong danh mục; khi sửa, bỏ qua chính bản ghi đang sửa.',
              'Thông báo khi trùng: “Tên loại tài khoản đã tồn tại”.'],
             ['Thêm mới loại tài khoản', 'Chỉnh sửa loại tài khoản']),
            ('BR-03', 'Điều kiện xóa và khóa',
             ['Loại tài khoản đang được gán cho ít nhất một tài khoản thì KHÔNG xóa và KHÔNG khóa được, kể cả chọn Khóa trong cửa sổ Sửa.',
              'Máy chủ kiểm tra lại lúc thực hiện, thông báo: “Loại tài khoản đang được sử dụng, không thể xóa” / “Loại tài khoản đang được sử dụng, không thể khóa”.'],
             ['Xóa loại tài khoản', 'Khóa / Mở khóa loại tài khoản', 'Chỉnh sửa loại tài khoản']),
            ('BR-04', 'Loại tài khoản đang Khóa',
             ['Loại tài khoản đang Khóa không sửa, không xóa được; máy chủ chặn với thông báo “Loại tài khoản đang bị khoá, vui lòng mở khoá trước khi cập nhật.”',
              'Muốn sửa phải Mở khóa trước.'],
             ['Chỉnh sửa loại tài khoản', 'Xóa loại tài khoản', 'Khóa / Mở khóa loại tài khoản']),
            ('BR-05', 'Mối quan hệ với Danh mục tài khoản',
             ['Khi khai báo tài khoản mới chỉ chọn được loại tài khoản đang Hoạt động.',
              'Tài khoản đang dùng loại đã Khóa vẫn giữ và hiển thị đúng loại đó kèm 🔒.'],
             ['Thêm mới tài khoản, Chỉnh sửa tài khoản (Danh mục tài khoản)']),
            ('BR-06', 'Giới hạn Import',
             ['Mỗi lần nhập tối đa 500 dòng.',
              'Bước Validate chỉ kiểm tra, không ghi dữ liệu; báo trùng mã trong cùng file và trùng mã với hệ thống.',
              'Trạng thái lấy theo cột Trạng thái; bỏ trống = Hoạt động.'],
             ['Import file loại tài khoản']),
            ('BR-07', 'Ghi lịch sử thay đổi',
             ['Mọi thay đổi thông tin và đổi trạng thái đều ghi lịch sử kèm người thực hiện.',
              'Xóa loại tài khoản xóa luôn lịch sử của nó.'],
             ['Chỉnh sửa loại tài khoản', 'Khóa / Mở khóa loại tài khoản', 'Xóa loại tài khoản', 'Xem lịch sử thay đổi']),
            ('BR-08', 'Phạm vi dữ liệu',
             ['Danh mục dùng chung với cổng cũ, không phân quyền theo công ty/phòng ban.'],
             ['Xem danh sách loại tài khoản']),
        ],
    },

    'loi_code': [
        'Import không kiểm trùng Tên loại tài khoản (TypeAccountService::validateImportData chỉ kiểm trùng Mã) → qua Import tạo được loại trùng tên với loại đã có hoặc trùng tên giữa 2 dòng trong file, trong khi nhập tay bị chặn “Tên loại tài khoản đã tồn tại”.',
        'Import đánh số dòng lệch: thông báo “(dòng N)” lấy N = thứ tự dòng dữ liệu + 1 (= số hàng Excel), nhưng cột # trên bảng xem trước đánh từ 1 → lệch 1 so với số dòng người dùng nhìn thấy trong cửa sổ.',
        'Tạo mới và Import không sinh mốc lịch sử (store()/import() không tạo TypeAccountVersion) → cửa sổ Lịch sử không có mốc Tạo mới, khác chuẩn các danh mục khác; Khóa/Mở khóa hiện dạng “Thay đổi thông tin” trường Trạng thái.',
        'Nút Xóa vẫn hiện với loại tài khoản đang Khóa mà chưa được dùng (điều kiện chỉ xét is_can_delete = chưa được dùng); bấm Xóa thì máy chủ trả “Loại tài khoản đang bị khoá, vui lòng mở khoá trước khi cập nhật.”.',
        'File mẫu Import là file tĩnh static/Mau_import_loai_tai_khoan.xlsx (không sinh bằng buildImportTemplate): không có cột STT, không có hàng mô tả in nghiêng, cột bắt buộc chỉ ghi “ *” — lệch khuôn file mẫu dùng chung của hệ thống.',
        'Loại tài khoản có sẵn mã “áD” (id 9, dữ liệu thử) chứa ký tự có dấu → mở Sửa rồi Lưu bị chặn “Chỉ gồm chữ không dấu, số, dấu - và _” dù không đổi mã.',
        'Khóa một loại tài khoản đã bị người khác khóa trước (danh sách chưa nạp lại) → máy chủ báo “Loại tài khoản đang được sử dụng, không thể khóa” (isCanLock gộp 2 điều kiện Hoạt động + chưa dùng vào 1 câu) — sai lý do; đúng ra phải báo “Dữ liệu đã thay đổi, vui lòng tải lại” như nhánh Mở khóa.',
        'Hằng Account::TYPES (dùng cho bộ lọc Loại tài khoản ở màn Danh mục tài khoản) lệch bảng này: id 6 hằng ghi “Tài khoản chi phí khác”, bảng ghi “Tài khoản thu nhập khác”; loại id 8, 9 thêm ở đây không xuất hiện ở bộ lọc bên đó.',
    ],
}

# ---- Sửa tab testcase "4. DM loại tài khoản" (đọc từ ref/testcase_tab.txt) ----
_PRE = 'Đăng nhập bằng tài khoản có quyền "Quản lý danh mục loại tài khoản". Đang ở màn hình Danh mục loại tài khoản.'
CFG['tc'] = {
    'tab': '4. DM loại tài khoản',
    'hdr_row': 128,            # "X. LUỒNG XUYÊN SUỐT"
    'blocks': [
        # Quy tắc mã mới — chèn cuối nhóm IX. RÀNG BUỘC NHẬP LIỆU (TC_09.001 hàng 117 … TC_09.011 hàng 127)
        {'after': 127, 'merge_from': 117, 'cases': [
            ('TC_09.012', 'Mã loại tài khoản có ký tự không hợp lệ', 'P1', _PRE,
             '1. Bấm Tạo mới\n2. Lần lượt nhập Mã = "TKĐB", "TK 01", "TK/01"\n3. Quan sát ô Mã, bấm Lưu',
             'Mã: TKĐB; TK 01; TK/01',
             '- Ô Mã loại tài khoản báo đỏ "Chỉ gồm chữ không dấu, số, dấu - và _" ngay khi gõ\n- Bấm Lưu: không lưu, báo "Bạn chưa nhập đầy đủ thông tin"'),
            ('TC_09.013', 'Mã chữ thường tự chuyển sang IN HOA khi lưu', 'P1', _PRE,
             '1. Bấm Tạo mới\n2. Nhập Mã = "tk-moi_1", Tên mới\n3. Bấm Lưu và xem danh sách',
             'Mã: tk-moi_1; Tên: DOC-Loại thử in hoa',
             '- Lưu thành công\n- Danh sách hiện mã TK-MOI_1 (chữ in hoa, giữ dấu - và _)'),
            ('TC_09.014', 'Trùng mã khác kiểu chữ hoa/thường', 'P1', 'Đăng nhập bằng tài khoản có quyền "Quản lý danh mục loại tài khoản". Đã có mã TKTS.',
             '1. Bấm Tạo mới\n2. Nhập Mã = "tkts", Tên mới\n3. Bấm Lưu',
             'Mã: tkts; Tên: DOC-Trùng mã',
             '- Ô Mã báo "Mã loại tài khoản đã tồn tại", không lưu'),
        ]},
    ],
    'edits': [
        ('I122', '- Báo "Vui lòng nhập tối đa 255 ký tự." ngay dưới ô Mã, không lưu'),
        ('G127', '1. Bấm Tạo mới\n2. Nhập Mã = " ABC " (có khoảng trắng hai đầu)\n3. Quan sát ô Mã rồi bấm Lưu\n4. Xoá hai khoảng trắng, bấm Lưu lại'),
        ('I127', '- Bước 3: ô Mã báo đỏ "Chỉ gồm chữ không dấu, số, dấu - và _" (khoảng trắng không phải ký tự hợp lệ), không lưu\n- Bước 4: lưu được, danh sách hiện mã ABC\n- Không tạo được 2 loại mà mắt thường nhìn thấy mã giống hệt nhau'),
        ('G103', '1. Không lọc gì\n2. Bấm Xuất Excel\n3. Trong cửa sổ "Chọn trường xuất file", giữ nguyên các trường đã tích, bấm Xuất file\n4. Mở file tải về'),
        ('I103', '- Thông báo "Xuất Excel thành công"\n- Tải về file danh_muc_loai_tai_khoan.xlsx, mở được\n- File có tiêu đề "Danh mục loại tài khoản", số dòng dữ liệu bằng tổng số bản ghi ở cuối bảng'),
        ('G104', '1. Bấm Xuất Excel\n2. Đọc danh sách trường trong cửa sổ "Chọn trường xuất file"\n3. Bấm Xuất file, đối chiếu tiêu đề cột với bảng trên màn hình'),
        ('I104', '- Cửa sổ có đủ 6 trường: Mã loại tài khoản, Tên loại tài khoản, Ghi chú, Trạng thái, Người tạo, Ngày tạo\n- Tích sẵn đúng các cột đang hiển thị trên bảng (mặc định: Mã loại tài khoản, Tên loại tài khoản, Người tạo, Ngày tạo, Trạng thái; Ghi chú đang ẩn nên không tích)\n- File có cột STT đầu tiên, tiếp theo đúng các trường đã tích theo thứ tự trong cửa sổ, tiêu đề cột bằng tiếng Việt'),
        ('G105', '1. Lọc Trạng thái = Khóa\n2. Bấm Xuất Excel → Xuất file\n3. Mở file'),
        ('I105', '- File chỉ chứa đúng các loại tài khoản đang Khóa, số dòng bằng tổng ở cuối bảng'),
        ('G106', '1. Đứng ở trang 1\n2. Bấm Xuất Excel → Xuất file\n3. Đếm số dòng trong file'),
        ('I106', '- File chứa TOÀN BỘ kết quả khớp bộ lọc (tối đa 10,000 dòng), không phải 5 dòng của trang đang xem'),
        ('G107', '1. Bấm nút Import Excel\n2. Bấm Tải file mẫu\n3. Mở file mẫu'),
        ('I107', '- Tải về file Mau_import_loai_tai_khoan.xlsx\n- Hàng 1 là tiêu đề 4 cột: Mã loại tài khoản *, Tên loại tài khoản *, Ghi chú, Trạng thái (cột bắt buộc có dấu * sau tên)\n- Từ hàng 2 là 2 dòng ví dụ (LTK001 Hoạt động, LTK002 Khóa)'),
        ('G108', '1. Bấm Import Excel\n2. Bấm Chọn file Excel, chọn file có 3 dòng mã và tên đều mới\n3. Bấm Load lên bảng, kiểm tra bảng xem trước\n4. Bấm Validate\n5. Bấm Import'),
        ('I108', '- Sau Load: bảng xem trước hiện đủ 3 dòng, ô Tổng = 3\n- Sau Validate: báo "Validate thành công", cả 3 dòng hợp lệ và bị khoá\n- Sau Import: báo "Import thành công 3 loại tài khoản.", cửa sổ đóng, danh sách có thêm 3 loại mới đúng dữ liệu trong file (dòng để trống Trạng thái ở trạng thái Hoạt động)'),
        ('G109', '1. Bấm Import Excel\n2. Chọn file có dòng bỏ trống cột Mã loại tài khoản, bấm Load lên bảng\n3. Bấm Validate, đọc thông báo dưới dòng lỗi'),
        ('I109', '- Dòng đó tô nền đỏ, báo "Mã loại tài khoản không được để trống"\n- Nút Import không bấm được cho tới khi sửa dòng lỗi hoặc bấm Bỏ dòng lỗi'),
        ('G110', '1. Chọn file có 1 dòng mang mã đã tồn tại trong danh mục, Load lên bảng\n2. Bấm Validate'),
        ('I110', '- Dòng đó báo "Mã loại tài khoản đã tồn tại trong hệ thống"\n- Không tạo thêm bản ghi trùng mã'),
        ('G111', '1. Chọn file có 2 dòng cùng mã IM9 (hàng 2 và hàng 4 của file), Load lên bảng\n2. Bấm Validate'),
        ('H111', 'Hàng 2 và hàng 4 của file cùng mã IM9'),
        ('I111', '- Dòng sau báo "Mã loại tài khoản bị trùng trong file import (dòng 2)"\n- Danh mục không xuất hiện 2 loại tài khoản cùng mã'),
        ('I112', '- Báo "Vui lòng chọn file .xlsx hoặc .xls", không nạp dữ liệu, không lỗi trắng trang'),
        ('G113', '1. Chọn file Excel chỉ có dòng tiêu đề\n2. Bấm Load lên bảng'),
        ('I113', '- Báo "Không có dòng dữ liệu hợp lệ.", không tạo bản ghi nào'),
        ('G114', '1. Chọn file có cả dòng hợp lệ và dòng lỗi, Load lên bảng\n2. Bấm Validate\n3. Quan sát bảng xem trước'),
        ('I114', '- Báo "Validate xong: 3 hợp lệ, 2 không hợp lệ. (Dòng hợp lệ đã bị khoá, chỉ có thể sửa dòng lỗi)"\n- Dòng hợp lệ bị khoá, không sửa được; dòng lỗi vẫn cho sửa tại chỗ rồi Validate lại\n- Phần mô tả dưới tiêu đề cửa sổ ghi "Import từ Excel • Validate xong dòng hợp lệ sẽ bị khoá"'),
    ],
    'clear_k': [103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 122, 127],
}

CFG['tc_ngoai_pham_vi'] = [
    'B10 + TC_01.006 (hàng 34) + TC_05.00x: còn ghi nút Khóa/Mở khóa nằm TRONG cột Trạng thái và "Rê chuột vào nút để đọc lý do" — nay nút ở cột Hành động và bị ẨN khi không đủ điều kiện (không có nút mờ, không có chú thích).',
    'TC_04.008 (hàng 71) "Nút Sửa bị vô hiệu" + TC_06.003 (hàng 89) "Nút Xóa bị vô hiệu": nay nút bị ẨN hẳn chứ không mờ.',
    'TC_04.009 (hàng 72) "Nút Xem": không còn nút Xem ở cột Hành động — bấm vào Mã loại tài khoản để mở cửa sổ Xem.',
    'TC_06.007 (hàng 93) xóa loại tài khoản đang Khóa: hiện nút Xóa vẫn hiện nhưng máy chủ chặn "Loại tài khoản đang bị khoá…" (xem loi_code) — cần chốt expected.',
    'TC_01.004 (hàng 32) "Cột Cập nhật hiện thời điểm và người cập nhật": nay tách 2 cột Người cập nhật / Ngày cập nhật, mặc định ẩn. B5 ghi hai ô "Cập nhật từ"/"Cập nhật đến" — nay là 1 ô khoảng ngày "Ngày cập nhật" trong Tìm kiếm nâng cao.',
    'TC_07.00x (Lịch sử): chưa phản ánh việc Tạo mới không sinh mốc lịch sử và Khóa/Mở khóa hiện dạng Thay đổi thông tin trường Trạng thái.',
    'TC_09.001 (hàng 117) bỏ trống cả 2 ô: FE chỉ chặn ô Tên rồi dừng (không gọi máy chủ) → lần bấm đầu chỉ ô Tên báo đỏ, ô Mã chỉ báo sau khi đã nhập Tên (cần kiểm trên màn hình).',
    'Chưa có case Import cho lỗi "Tên loại tài khoản không được để trống", "Trạng thái chỉ nhận…", mã sai ký tự, và nút Bỏ dòng lỗi (theo quy tắc không thêm case Import khi tab đã có nhóm Import).',
]


# Đồng bộ chỗ tester sửa tay trên Drive (so bản Drive 28/09/2026) — build_srs áp qua apply_tester_edits
CFG['srs_tester'] = {
 "del": [
  "1. Người dùng vào menu Tài chính → Danh mục → Danh mục loại tài khoản.",
  "Không có bản ghi khớp → bảng hiện “Không có dữ liệu phù hợp bộ lọc.”",
  "Không có kết quả → bảng hiện thông báo không có dữ liệu.",
  "Bấm “Lưu và tiếp tục” → ghi bản ghi rồi giữ cửa sổ mở với các ô trống.",
  "Giữ nguyên mã/tên của chính bản ghi → không báo trùng.",
  "Tạo mới / Import chưa sinh mốc lịch sử; bản ghi chưa từng sửa → “Chưa có lịch sử thao tác nào.”",
  "File không phải .xlsx/.xls → “Vui lòng chọn file .xlsx hoặc .xls”.",
  "File không có dòng dữ liệu → “Không có dòng dữ liệu hợp lệ.”",
  "Quá 500 dòng → báo vượt giới hạn 500 dòng."
 ],
 "br": {
  "BR-01": [
   "BR-01",
   "Ràng buộc mã loại tài khoản",
   [
    "Mã chỉ gồm chữ không dấu, số, dấu - và _; tối đa 255 ký tự.",
    "Hệ thống tự bỏ khoảng trắng hai đầu và lưu mã ở dạng CHỮ IN HOA (cả nhập tay lẫn Import).",
    "Mã không được trùng trong danh mục, không phân biệt chữ hoa/chữ thường. Thông báo khi trùng: “Mã loại tài khoản đã tồn tại”."
   ],
   [
    "Thêm mới ",
    "Chỉnh sửa l",
    "Import file "
   ]
  ],
  "BR-02": [
   "BR-02",
   "Ràng buộc trùng tên",
   [
    "Tên loại tài khoản không được trùng trong danh mục; khi sửa, bỏ qua chính bản ghi đang sửa.",
    "Thông báo khi trùng: “Tên loại tài khoản đã tồn tại”."
   ],
   [
    "Thêm mới ",
    "Chỉnh sửa "
   ]
  ],
  "BR-03": [
   "BR-03",
   "Điều kiện xóa và khóa",
   [
    "Loại tài khoản đang được gán cho ít nhất một tài khoản thì KHÔNG xóa và KHÔNG khóa được, kể cả chọn Khóa trong cửa sổ Sửa.",
    "Máy chủ kiểm tra lại lúc thực hiện, thông báo: “Loại tài khoản đang được sử dụng, không thể xóa” / “Loại tài khoản đang được sử dụng, không thể khóa”."
   ],
   [
    "Xóa ",
    "Khóa / Mở khóa",
    "Chỉnh sửa "
   ]
  ],
  "BR-04": [
   "BR-04",
   "Loại tài khoản đang Khóa",
   [
    "Loại tài khoản đang Khóa không sửa, không xóa đượcMuốn sửa phải Mở khóa trước."
   ],
   [
    "Chỉnh sửa ",
    "Xóa ",
    "Khóa / Mở khóa "
   ]
  ],
  "BR-06": [
   "BR-06",
   "Giới hạn Import",
   [
    "Mỗi lần nhập tối đa 500 dòng.",
    "Bước Validate chỉ kiểm tra, không ghi dữ liệu; báo trùng mã trong cùng file và trùng mã với hệ thống.",
    "Trạng thái lấy theo cột Trạng thái; bỏ trống = Hoạt động."
   ],
   [
    "Import file "
   ]
  ]
 }
}
