# -*- coding: utf-8 -*-
# Cấu hình tài liệu màn Danh mục Phường/Xã — bám khuôn configs/areas.py.
# Nguồn: code gop_db 25/09/2026 (FE pages/human/wards/index.vue, components/WardModel.vue, utils/export/listExportFile.js;
# BE WardController (store/exportRows) / WardService / CreateWardRequest / WardListResource / ExportColumnRegistry['wards']).
# Xuất Excel của màn này dựng file ở trình duyệt theo lô 2.000 dòng (bảng ~13.500 dòng), không giới hạn 10,000 dòng.
# Không ghi URL. Chữ UI / message lấy nguyên văn code.

DT = 'phường/xã'

CFG = {
    'slug': 'wards',
    'ten': 'Danh mục Phường/Xã',
    'doi_tuong': DT,
    'file_hdsd': 'HDSD_Danh mục Phường-Xã.docx',
    'file_srs': 'SRS - Danh mục Phường-Xã.docx',
    'menu': [('Danh mục', 'menu_phanhe'), ('Địa lý', 'menu_nhom'), ('Phường/xã', 'menu_muc')],

    'thuat_ngu': [
        ['Phường/Xã', 'Đơn vị hành chính cấp xã, trực thuộc một Tỉnh/TP. Là cấp cha của Đường/Phố trong cây địa chỉ.'],
        ['Mã số', 'Mã của phường/xã, bắt buộc nhập, chỉ nhận chữ số (tối đa 10 chữ số), không yêu cầu duy nhất. Số 0 ở đầu được giữ nguyên (vd 00082).'],
        ['Phường/xã đang được sử dụng', 'Phường/xã đã được ít nhất một hồ sơ nhân sự dùng làm địa chỉ thường trú hoặc tạm trú. Phường/xã này không Xóa và không Khóa được.'],
        ['Trạng thái Hoạt động', 'Phường/xã dùng được ở các màn nghiệp vụ khác.'],
        ['Trạng thái Khóa', 'Phường/xã không còn chọn được ở nơi khác nhưng vẫn nằm trong danh mục và vẫn xem được lịch sử.'],
    ],
    'phien_ban': [
        ['1.0', '17/08/2026', 'Đội phát triển phần mềm', 'Tạo mới cho màn Danh mục Phường/Xã.'],
        ['1.1', '25/09/2026', 'Đội phát triển phần mềm', 'Cập nhật theo phiên bản hiện tại: bổ sung Xem chi tiết, Xuất Excel, Import Excel, Tùy chỉnh cột, ô Trạng thái trong cửa sổ Tạo/Sửa, quy tắc ô Mã số; trình bày theo mẫu tài liệu danh mục chung.'],
    ],
    'muc_dich': [
        'Danh mục Phường/Xã là nơi khai báo và quản lý danh sách phường/xã dùng chung cho toàn hệ thống. Mỗi phường/xã trực thuộc một Tỉnh/TP; dữ liệu của màn này là nguồn cho các ô địa chỉ ở mọi màn nghiệp vụ khác (hồ sơ nhân sự, khách hàng, Danh mục Đường/Phố…), nên mỗi thay đổi ở đây đều ảnh hưởng tới nhiều nơi.',
    ],
    'quyen': {
        'truoc': ['Phân quyền ai được quyền tạo/ sửa/ xóa/ khóa/ mở khóa sẽ được cập nhật ngay sau khi có tài liệu phân quyền chi tiết của hệ thống.',
                  'Tại thời điểm xây dựng HDSD hiện tại, ai cũng được quyền truy cập màn hình danh mục Phường/Xã và quyền tạo/sửa/xóa/khóa/mở khóa, import, xuất Excel.'],
        'rows': [],
        'sau': ['Lưu ý: vì ai cũng sửa được, Người dùng hãy cân nhắc kỹ trước khi đổi hoặc xóa một bản ghi — dữ liệu này đang được nhiều màn khác sử dụng.'],
    },

    'danh_sach': {
        'mo_ta_vao': 'Hệ thống hiển thị danh sách phường/xã hiện có (gồm cả bản ghi Hoạt động lẫn bản ghi đã Khóa), mặc định 10 dòng mỗi trang.',
        'bo_cuc': [
            'Khu vực tìm kiếm và lọc — ô tìm kiếm nhanh, ô Quốc gia, ô Tỉnh/TP, nút Tìm kiếm và Làm mới.',
            'Thanh công cụ — nút Tạo mới, nút Xuất Excel, nút Import Excel và biểu tượng Cấu hình cột hiển thị.',
            'Bảng danh sách — các cột thông tin, cột Hành động ở cuối, và phân trang bên dưới.',
        ],
        'cot': [
            ['STT', 'Số thứ tự, chạy liên tục qua các trang. Luôn hiển thị.'],
            ['Tên phường/xã', 'Tên đầy đủ. Luôn hiển thị, sắp xếp được. Bấm vào tên để mở cửa sổ Xem phường/xã.'],
            ['Tỉnh/TP', 'Tỉnh/TP mà phường/xã trực thuộc.'],
            ['Quốc gia', 'Quốc gia của tỉnh/TP. Mặc định ẩn.'],
            ['Người cập nhật', 'Người sửa bản ghi gần nhất. Mặc định ẩn.'],
            ['Ngày cập nhật', 'Thời điểm sửa gần nhất, dạng dd/mm/yyyy hh:mm. Mặc định ẩn, sắp xếp được.'],
            ['Người tạo', 'Người đã thêm bản ghi.'],
            ['Ngày tạo', 'Thời điểm thêm, dạng dd/mm/yyyy hh:mm, sắp xếp được.'],
            ['Trạng thái', 'Nhãn Hoạt động hoặc Khóa.'],
            ['Hành động', 'Các nút thao tác của dòng (xem mục 4).'],
        ],
        'hanh_dong': {
            'intro': 'Trên mỗi dòng, cột Hành động có các nút:',
            'bullets': [
                'Biểu tượng bút chì {icon:btn_sua} — mở cửa sổ Sửa phường/xã. Chỉ hiện khi phường/xã đang Hoạt động.',
                'Biểu tượng thùng rác {icon:btn_xoa} — xóa phường/xã. Chỉ hiện khi phường/xã đang Hoạt động và CHƯA được nhân sự nào dùng làm địa chỉ thường trú/tạm trú.',
                'Khóa — chỉ hiện khi phường/xã đang Hoạt động và chưa được nhân sự dùng làm địa chỉ. Mở khóa — luôn hiện với phường/xã đang Khóa.',
                'Lịch sử — mở cửa sổ Lịch sử thay đổi.',
                'Có từ 4 nút trở lên thì 2 nút đầu hiện thẳng, các nút còn lại nằm trong nút ba chấm {icon:btn_bacham} “Hành động khác”.',
            ],
            'anh': 'Các nút ở cột Hành động của một phường/xã',
            'luu_y': ['Lưu ý quan trọng: với bản ghi ĐÃ KHÓA, nút Sửa và Xóa sẽ BIẾN MẤT, chỉ còn Mở khóa và Lịch sử. Muốn sửa lại, Người dùng phải Mở khóa trước. Phường/xã đang được nhân sự sử dụng chỉ còn Sửa và Lịch sử.'],
        },
        'phan_trang': [
            'Cuối bảng có dòng “Hiển thị a–b / N”: N là tổng số phường/xã khớp bộ lọc đang áp dụng, không phải tổng toàn danh mục.',
            'Ô Số dòng/trang có các mức 5, 10, 20, 50, 100 (mặc định 10). Đổi số dòng thì hệ thống tự quay về trang 1.',
            'Các cột sắp xếp được: Tên phường/xã, Ngày tạo, Ngày cập nhật. Bấm tiêu đề cột để sắp xếp, bấm lần hai để đảo chiều. Thứ tự sắp xếp được giữ nguyên khi chuyển trang. Chưa bấm sắp xếp thì bản ghi thêm gần nhất nằm trên cùng.',
            'Bảng KHÔNG có cột Mã số; mã số xem trong cửa sổ Xem/Sửa hoặc lấy ra bằng Xuất Excel.',
        ],
    },

    'loc': {
        'buoc2': 'Bước 2: Nhập chữ vào ô tìm kiếm nhanh hoặc chọn giá trị ở ô Quốc gia, Tỉnh/TP.',
        'rows': [
            ['Ô tìm kiếm nhanh', 'Tìm theo TÊN phường/xã (gõ một phần tên cũng ra). Không tìm theo mã số. Nhấn Enter hoặc bấm Tìm kiếm để lọc.'],
            ['Quốc gia', 'Chọn một quốc gia để chỉ xem phường/xã thuộc các tỉnh/TP của quốc gia đó; đồng thời thu hẹp danh sách của ô Tỉnh/TP. Lọc ngay khi chọn.'],
            ['Tỉnh/TP', 'Chọn một tỉnh/TP để chỉ xem phường/xã của tỉnh/TP đó. Bị xóa trắng khi đổi Quốc gia. Lọc ngay khi chọn.'],
        ],
        'ap_dung': [
            'Các tiêu chí kết hợp với nhau theo kiểu VÀ — chỉ bản ghi thỏa đồng thời tất cả các tiêu chí mới hiện ra. Mỗi lần đổi tiêu chí, danh sách quay về trang 1.',
            'Màn hình không có ô lọc Trạng thái: danh sách luôn hiện cả phường/xã Hoạt động lẫn đã Khóa, phân biệt bằng cột Trạng thái.',
            'Bấm {icon:btn_lammoi} để xóa toàn bộ tiêu chí; danh sách nạp lại đầy đủ ngay lập tức.',
        ],
        'anh_ket_qua': 'Kết quả tìm nhanh theo tên phường/xã (gõ “Phường”)',
    },

    'form': {
        'kieu': 'popup',
        'buoc_tao': [
            'Bước 1: Truy cập vào màn hình Danh mục Phường/Xã.',
            'Bước 2: Bấm {icon:btn_taomoi}. Hệ thống mở cửa sổ “Tạo phường/xã”.',
            'Bước 3: Nhập/ chọn đầy đủ thông tin: Tên phường/xã, Mã số, Tỉnh/TP, Trạng thái.',
            'Bước 4: Bấm {icon:btn_luu} để lưu và đóng cửa sổ, hoặc {icon:btn_luutieptuc} để lưu rồi nhập tiếp phường/xã khác.',
        ],
        'anh_tao': 'Cửa sổ Tạo phường/xã',
        'truong': [
            ['Tên phường/xã', 'Ô nhập giá trị', 'Có', 'Trống', 'Tối đa 255 ký tự. Không được trùng trong cùng một Tỉnh/TP (cùng tên ở tỉnh/TP khác vẫn lưu được). Bỏ trống báo “Bắt buộc phải nhập”; trùng báo “Tên phường/xã này đã tồn tại”.'],
            ['Mã số', 'Ô nhập giá trị', 'Có', 'Trống', 'Chỉ nhận chữ số, tối đa 10 chữ số, giữ nguyên số 0 ở đầu, không yêu cầu duy nhất. Kiểm tra ngay khi gõ: có chữ cái/ký tự đặc biệt báo “Phải là số”; quá 10 chữ số hoặc có dấu chấm, dấu phẩy, dấu trừ (vd 1.5, -5) báo “Chỉ được nhập chữ số, từ 0 đến 10 chữ số”. Bỏ trống thì khi Lưu báo “Bắt buộc phải nhập”.'],
            ['Tỉnh/TP', 'Ô chọn giá trị', 'Có', 'Trống', 'Liệt kê tỉnh/TP đang Hoạt động. Phường/xã đang dùng một tỉnh/TP đã khóa vẫn hiện đúng tên tỉnh/TP đó kèm biểu tượng 🔒. Bỏ trống báo “Bắt buộc phải nhập”.'],
            ['Trạng thái', 'Ô chọn giá trị', 'Có', 'Hoạt động', 'Chỉ chọn 1 trong 2 giá trị: Hoạt động / Khóa. Không xoá trắng được. Khi Sửa một phường/xã đang được nhân sự sử dụng, ô này bị khóa ở Hoạt động (không chọn được Khóa).'],
        ],
        'nut': [
            ['Lưu', 'Ghi bản ghi rồi đóng cửa sổ, báo “Thêm mới thành công” (hoặc “Cập nhật thành công” khi sửa) và nạp lại danh sách.'],
            ['Lưu và tiếp tục', 'Ghi bản ghi nhưng GIỮ cửa sổ mở và xóa trắng các ô để nhập tiếp. Chỉ có khi Tạo mới.'],
            ['Đóng', 'Đóng cửa sổ, không ghi gì. Nếu đã nhập dở, hệ thống hỏi “Thông tin chưa lưu” — “Bạn có thông tin chưa lưu. Có chắc chắn muốn thoát?” (Thoát / Ở lại).'],
        ],
        'loi': [
            ['Bắt buộc phải nhập', 'Chưa nhập một trong các ô bắt buộc: Tên phường/xã, Mã số, Tỉnh/TP.'],
            ['Tên phường/xã này đã tồn tại', 'Đã có phường/xã khác cùng tên trong cùng một Tỉnh/TP. Hãy kiểm tra lại danh sách trước khi thêm.'],
            ['Phải là số', 'Ô Mã số có chữ cái hoặc ký tự đặc biệt. Chỉ nhập chữ số.'],
            ['Chỉ được nhập chữ số, từ 0 đến 10 chữ số', 'Ô Mã số dài quá 10 chữ số hoặc có dấu chấm, dấu phẩy, dấu trừ.'],
            ['Vui lòng nhập tối đa 255 ký tự.', 'Tên phường/xã quá dài.'],
            ['Không thể khóa phường/xã đang được sử dụng.', 'Chọn Trạng thái = Khóa khi sửa một phường/xã mà nhân sự đang dùng làm địa chỉ (chỉ gặp khi dữ liệu vừa thay đổi lúc đang mở cửa sổ).'],
            ['Vui lòng kiểm tra lại dữ liệu nhập', 'Thông báo chung khi còn ô bị lỗi; xem các ô báo đỏ trong cửa sổ.'],
        ],
    },

    'sua': {
        'buoc': [
            'Bước 1: Truy cập vào màn hình Danh mục Phường/Xã.',
            'Bước 2: Bấm nút {icon:btn_sua} ở cột Hành động của phường/xã cần sửa.',
            'Bước 3: Hệ thống hiển thị cửa sổ “Sửa phường/xã” với dữ liệu hiện tại.',
            'Bước 4: Cập nhật các thông tin cần sửa (quy tắc nhập như Thêm mới).',
            'Bước 5: Bấm {icon:btn_luu} để xác nhận thay đổi hoặc Đóng nếu muốn hủy.',
        ],
        'anh': 'Cửa sổ Sửa phường/xã',
        'ghi_chu': [
            'Giữ nguyên tên của chính phường/xã đang sửa thì không bị báo trùng.',
            'Mã số là trường bắt buộc: phường/xã cũ chưa có mã số thì phải nhập mã số mới lưu được.',
            'Phường/xã đang Khóa không có nút Sửa. Nếu phường/xã vừa bị người khác khóa, bấm Lưu sẽ nhận thông báo “Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.”',
            'Đổi tên tỉnh/TP ở Danh mục Tỉnh/TP thì cột Tỉnh/TP của phường/xã tự hiển thị tên mới.',
        ],
    },
    'xoa': {
        'buoc': [
            'Bước 1: Ở cột Hành động, Người dùng bấm {icon:btn_xoa}.',
            'Bước 2: Hệ thống hiện hộp xác nhận “Xóa Phường/Xã” — “Bạn có chắc muốn xóa phường/xã "…"?”. Bấm {icon:btn_confirm_xoa} để xác nhận: hệ thống báo “Xoá phường/xã thành công”, bản ghi biến mất khỏi danh sách.',
            'Bấm {icon:btn_huy} nếu bấm nhầm. Không có gì thay đổi.',
        ],
        'anh': 'Hộp xác nhận xóa phường/xã',
        'ghi_chu': ['Nút Xóa chỉ hiện khi phường/xã đang Hoạt động và chưa được nhân sự nào dùng làm địa chỉ thường trú/tạm trú. Phường/xã đang được sử dụng thì không xóa được. Nếu bản ghi vừa bị người khác xóa trước đó, hệ thống báo “Trạng thái đã bị thay đổi. Vui lòng load lại trang” và không xóa lần hai.'],
    },
    'khoa': {
        'y_nghia': [
            'Bản ghi VẪN nằm trong danh sách, cột Trạng thái hiện chữ Khóa.',
            'Vẫn xem được chi tiết và lịch sử thay đổi của bản ghi.',
            'Phường/xã đã khóa không còn xuất hiện ở ô chọn phường/xã của các màn khác (ví dụ Danh mục Đường/Phố, hồ sơ nhân sự).',
            'Nút Sửa và Xóa của dòng đó biến mất.',
            'Chỉ khóa được phường/xã CHƯA được nhân sự dùng làm địa chỉ; phường/xã đang được sử dụng không có nút Khóa.',
        ],
        'buoc_khoa': [
            'Bước 1: Ở cột Hành động, Người dùng chọn Khóa (trong nút ba chấm nếu dòng có nhiều nút).',
            'Bước 2: Hệ thống hiện hộp xác nhận “Khóa Phường/Xã” — “Bạn có chắc muốn khóa phường/xã "…"?”. Bấm Khóa để xác nhận; hệ thống báo “Khóa thành công”, cột Trạng thái đổi thành Khóa. Bấm Hủy nếu bấm nhầm.',
        ],
        'buoc_mo': [
            'Bước 1: Ở cột Hành động của phường/xã đang Khóa, Người dùng chọn Mở khóa.',
            'Bước 2: Bấm Mở khóa trong hộp xác nhận “Mở khóa Phường/Xã”. Hệ thống báo “Mở khóa thành công”, cột Trạng thái đổi thành Hoạt động. Bấm Hủy nếu bấm nhầm.',
        ],
        'ghi_chu': ['Có thể khóa ngay trong cửa sổ Sửa bằng cách chọn Trạng thái = Khóa rồi Lưu (chỉ với phường/xã chưa được sử dụng). Nếu bản ghi vừa bị người khác đổi trạng thái, hệ thống báo “Trạng thái đã bị thay đổi. Vui lòng load lại trang”.'],
    },
    'lich_su': {
        'buoc': [
            'Xem từ màn danh sách: ở cột Hành động, Người dùng chọn Lịch sử.',
            'Xem từ màn chi tiết: bấm vào tên phường/xã để mở cửa sổ Xem phường/xã, khối Lịch sử nằm ở cuối cửa sổ.',
        ],
        'ghi_chu': ['Cửa sổ có bộ lọc riêng (loại hành động, người thực hiện, khoảng thời gian) để thu hẹp danh sách khi bản ghi có nhiều lần thay đổi. Trường Tỉnh/TP trong lịch sử hiển thị bằng TÊN.'],
    },
    'chi_tiet': {
        'buoc': ['Bước 1: Truy cập vào màn hình Danh mục Phường/Xã.',
                 'Bước 2: Bấm vào tên phường/xã ở cột Tên phường/xã. Hệ thống mở cửa sổ “Xem phường/xã”.'],
        'ghi_chu': ['Cửa sổ hiển thị Tên phường/xã, Mã số, Tỉnh/TP và Trạng thái ở chế độ chỉ đọc (không gõ được, không có nút Lưu), kèm khối Lịch sử ở cuối. Phường/xã đang Khóa vẫn xem được bình thường.'],
    },
    'xuat': {
        'buoc': [
            'Bước 1: Lọc danh sách theo đúng dữ liệu cần lấy (xem PHẦN 2). File xuất ra chạy theo đúng bộ lọc đang áp dụng.',
            'Bước 2: Bấm nút {icon:btn_xuatexcel}. Hệ thống mở cửa sổ “Chọn trường xuất file”.',
            'Bước 3: Tích chọn, kéo biểu tượng ☰ để đổi vị trí các trường cần xuất. Mặc định hệ thống tích sẵn đúng những cột đang hiển thị trên bảng (trường Mã số không có cột trên bảng nên phải tự tích).',
            'Bước 4: Bấm {icon:btn_xuatfile}. Hệ thống tải dữ liệu theo từng lô, dựng file rồi tải về file danh_muc_phuong_xa.xlsx và báo “Xuất Excel thành công (N dòng)”.',
        ],
        'truong': 'Chọn nhiều trường: Tên phường/xã, Mã số, Tỉnh/TP, Quốc gia, Trạng thái, Người tạo, Ngày tạo, Người cập nhật, Ngày cập nhật.',
        'ghi_chu': ['Lưu ý: file xuất chứa TOÀN BỘ kết quả của bộ lọc (không giới hạn số dòng, danh mục có hơn 13,000 phường/xã nên xuất toàn bộ có thể mất vài giây), không chỉ các dòng của trang đang xem. Bộ lọc không ra dòng nào thì hệ thống báo “Không có dữ liệu để xuất” và không tải file.'],
    },
    'import': {
        'tieu_de': 'Import phường/xã',
        'file': 'Mau_import_phuong_xa.xlsx',
        'cot_text': 'Tên phường/xã (bắt buộc), Mã số (bắt buộc, chỉ chữ số), Tỉnh/TP (bắt buộc, chọn trong danh sách sổ xuống)',
        'toast': 'Import thành công N phường/xã.',
        'loi': [
            ['Tên phường/xã không được để trống', 'Dòng đó bỏ trống cột Tên phường/xã.'],
            ['Tên phường/xã tối đa 255 ký tự', 'Tên quá dài, rút gọn lại.'],
            ['Mã số không được để trống', 'Dòng đó bỏ trống cột Mã số.'],
            ['Mã số phải là số', 'Cột Mã số có chữ cái hoặc ký tự đặc biệt.'],
            ['Mã số tối đa 10 chữ số', 'Cột Mã số dài quá 10 chữ số.'],
            ['Tỉnh/TP không được để trống', 'Dòng đó bỏ trống cột Tỉnh/TP.'],
            ['Không tìm thấy tỉnh/TP: X', 'Tên tỉnh/TP ghi sai, không có trong Danh mục Tỉnh/TP.'],
            ['Phường/xã bị trùng với dòng N trong file', 'Trong chính file có hai dòng cùng tên, cùng tỉnh/TP. Xoá bớt một dòng.'],
            ['Phường/xã này đã tồn tại trong tỉnh/TP đã chọn', 'Danh mục đã có phường/xã trùng tên trong cùng tỉnh/TP.'],
        ],
        'ghi_chu': ['Lưu ý: phường/xã nhập từ Excel luôn được tạo ở trạng thái Hoạt động, người tạo là chính người thực hiện nhập. Mã số trong file nên để dạng chữ (Text) để giữ số 0 ở đầu. Mỗi lần nhập tối đa 500 dòng; file dài hơn hệ thống báo “File có X dòng dữ liệu, vượt quá giới hạn 500 dòng mỗi lần import. Vui lòng tách file và import nhiều lần.”'],
    },
    'tuy_chinh_cot': {'cot_khoa': 'Ba cột STT, Tên phường/xã và Hành động'},

    'shots': {'list': '01_list.png', 'rowmenu': '03_rowmenu.png', 'filter': 'filter.png', 'filter_result': '04_filter_result.png',
              'create': '10_create.png', 'create_error': '11_create_error.png', 'code_error': '11b_code_error.png', 'edit': '12_edit.png',
              'delete': '13_delete.png', 'lock': '14_lock.png', 'unlock': '15_unlock.png', 'history': '16_history.png',
              'detail': '17_detail.png', 'export': '20_export.png', 'import_open': '21_import_open.png',
              'import_loaded': '22_import_loaded.png', 'import_validated': '23_import_validated.png', 'colcfg': '25_colcfg.png'},

    'capture': {'route': '/human/wards', 'menu': {'phanhe': 'DANH MỤC', 'nhom': 'Địa lý', 'muc': 'Phường/xã'},
                'search': 'Tìm theo tên phường/xã', 'searchText': 'Phường', 'detailCol': 1,
                'lockName': 'Hạnh Thông123', 'codeInput': 'Nhập mã số', 'create': True, 'lock': True},

    'import_test': {
        'cols': ['Tên phường/xã', 'Mã số', 'Tỉnh/TP'],
        'rows': [
            ['DOC-Phường Mẫu Một', '90001', 'Thành phố Hà Nội'],
            ['DOC-Phường Mẫu Hai', '00902', 'Thành phố Hồ Chí Minh'],
            ['', '90003', 'Thành phố Hà Nội'],
            ['DOC-Phường Mẫu Một', '90004', 'Thành phố Hà Nội'],
            ['Phường Cửa Nam', '00082', 'Thành phố Hà Nội'],
            ['DOC-Phường Mẫu Ba', 'AB12', 'Thành phố Hà Nội'],
            ['DOC-Phường Mẫu Bốn', '', 'Thành phố Đà Nẵng'],
            ['DOC-Phường Mẫu Năm', '90008', 'Tỉnh không tồn tại'],
        ],
    },

    'uml': {
        'mains': [('FR-01', 'Xem danh sách phường/xã', 'view'), ('FR-03', 'Thêm mới phường/xã', 'crud'),
                  ('FR-04', 'Chỉnh sửa phường/xã', 'crud'), ('FR-05', 'Xóa phường/xã', 'action'),
                  ('FR-06', 'Khóa / Mở khóa phường/xã', 'action'), ('FR-08', 'Import file phường/xã', 'io'),
                  ('FR-09', 'Xuất danh sách phường/xã ra Excel', 'io')],
        'subs': [('FR-02', 'Tìm kiếm và lọc phường/xã', 'view'), ('FR-10', 'Xem chi tiết phường/xã', 'view'),
                 ('FR-11', 'Tùy chỉnh cột hiển thị', 'view'), ('FR-07', 'Xem lịch sử thay đổi', 'view')],
        'rieng': [('FR-10', 'Xem chi tiết phường/xã', 'view')],
    },

    'srs': {
        'muc_dich': ['Là căn cứ nghiệm thu chức năng.',
                     'Làm rõ ràng buộc trùng tên phường/xã (duy nhất trong cùng Tỉnh/TP), quy tắc ô Mã số, điều kiện Xóa/Khóa (phường/xã đang được nhân sự sử dụng) và quan hệ Tỉnh/TP → Phường/Xã → Đường/Phố.'],
        'quyen_truoc': ['Danh sách quyền sẽ được cập nhật sau khi có tài liệu phân quyền chi tiết của hệ thống. Tại thời điểm xây dựng SRS, màn hình chưa gắn quyền; mọi người dùng đã đăng nhập đều thực hiện được các chức năng.'],
        'quyen_rows': [['(chưa khai báo quyền nào)', 'Sẽ cập nhật sau khi có tài liệu phân quyền chi tiết']],
        'ma_tran': [['Chức năng', 'Người dùng đã đăng nhập']] + [[f, 'Chờ cập nhật theo ma trận phân quyền chi tiết'] for f in [
            'FR-01 Xem danh sách phường/xã', 'FR-02 Tìm kiếm và lọc', 'FR-03 Thêm mới phường/xã', 'FR-04 Chỉnh sửa phường/xã',
            'FR-05 Xóa phường/xã', 'FR-06 Khóa / Mở khóa phường/xã', 'FR-07 Xem lịch sử thay đổi', 'FR-08 Import file phường/xã',
            'FR-09 Xuất danh sách ra Excel', 'FR-10 Xem chi tiết phường/xã', 'FR-11 Tùy chỉnh cột hiển thị']],
        'ma_tran_widths': [2.4, 2.4],
        'fr': [
            {'ten': 'Xem danh sách phường/xã',
             'qtc': 'Màn Danh sách, Sắp xếp dữ liệu bảng, Phân trang và Cấu hình cột. Chỉ bổ sung các quy tắc riêng của Danh mục Phường/Xã tại phần mô tả chi tiết.',
             'gioi_thieu': [['Tên chức năng', 'Xem danh sách phường/xã'],
                            ['Mô tả', 'Hiển thị toàn bộ phường/xã trong danh mục (cả Hoạt động lẫn Khóa), có phân trang và sắp xếp.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Điều kiện ban đầu', 'Người dùng đã đăng nhập vào hệ thống.'],
                            ['Dòng sự kiện chính', '1. Người dùng vào menu Danh mục → Địa lý → Phường/xã.\n2. Hệ thống nạp trang đầu tiên của danh sách (10 dòng), bản ghi mới nhất trên cùng.\n3. Bảng hiển thị dữ liệu kèm tổng số bản ghi.'],
                            ['Dòng sự kiện phụ', '• Không có bản ghi khớp → bảng hiện “Không có dữ liệu phù hợp bộ lọc.”\n• Phiên đăng nhập hết hạn → điều hướng về màn đăng nhập.']],
             'anh': [('list', 'Màn Danh mục Phường/Xã lúc mới truy cập')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Mô tả'],
                    ['1', 'STT', 'Table/Grid', 'Read-only', 'Số thứ tự, chạy liên tục qua các trang. Luôn hiển thị, không ẩn được.'],
                    ['2', 'Tên phường/xã', 'Table/Grid', 'Read-only', 'Luôn hiển thị, sắp xếp được. Bấm vào tên mở cửa sổ Xem (xem 2.10).'],
                    ['3', 'Tỉnh/TP', 'Table/Grid', 'Read-only', 'Tỉnh/TP trực thuộc.'],
                    ['4', 'Quốc gia', 'Table/Grid', 'Read-only', 'Mặc định ẩn.'],
                    ['5', 'Người cập nhật', 'Table/Grid', 'Read-only', 'Mặc định ẩn.'],
                    ['6', 'Ngày cập nhật', 'Table/Grid', 'Read-only', 'dd/mm/yyyy hh:mm. Mặc định ẩn, sắp xếp được.'],
                    ['7', 'Người tạo', 'Table/Grid', 'Read-only', 'Người đã thêm bản ghi.'],
                    ['8', 'Ngày tạo', 'Table/Grid', 'Read-only', 'dd/mm/yyyy hh:mm, sắp xếp được.'],
                    ['9', 'Trạng thái', 'Badge', 'Read-only', 'Hoạt động hoặc Khóa.'],
                    ['10', 'Hành động', 'Table/Grid', 'Read-only', 'Sửa (khi Hoạt động), Xóa và Khóa (khi Hoạt động và chưa được nhân sự sử dụng), Mở khóa (khi Khóa), Lịch sử. Từ 4 nút trở lên thì 2 nút đầu hiện thẳng, còn lại trong nút ba chấm.'],
                    ['11', 'Nút Tạo mới', 'Button', 'Enable', 'Mở cửa sổ Tạo phường/xã.'],
                    ['12', 'Nút Xuất Excel', 'Button', 'Enable', 'Mở cửa sổ Chọn trường xuất file (xem 2.9). Không bấm được khi đang xuất.'],
                    ['13', 'Nút Import Excel', 'Button', 'Enable', 'Mở cửa sổ Import phường/xã (xem 2.8).'],
                    ['14', 'Biểu tượng Cấu hình cột hiển thị', 'Icon Button', 'Enable', 'Mở cửa sổ Tuỳ chỉnh cột (xem 2.11).'],
                    ['15', 'Phân trang', 'Pagination', 'Enable', 'Số dòng/trang 5 / 10 / 20 / 50 / 100, mặc định 10.']],
             'ui_widths': [0.6, 1.4, 0.9, 0.8, 3],
             'events': [['Mở màn hình', 'System', 'After:\n– Nạp trang đầu, hiển thị tổng số bản ghi.'],
                        ['Bấm tiêu đề cột sắp xếp được', 'Click', 'After:\n– Đổi chiều sắp xếp và nạp lại danh sách từ trang 1.'],
                        ['Chuyển trang', 'Click', 'Before:\n– Giữ nguyên bộ lọc và thứ tự sắp xếp.\nAfter:\n– Nạp dữ liệu trang mới, số thứ tự tiếp tục liên tục.'],
                        ['Đổi số dòng mỗi trang', 'Change', 'After:\n– Quay về trang 1 và nạp lại theo số dòng mới.']]},
            {'ten': 'Tìm kiếm và lọc',
             'qtc': 'Kịch bản tìm kiếm, Bộ lọc, Dropdown, Phân trang. Chỉ bổ sung các tiêu chí tìm kiếm/lọc riêng của Danh mục Phường/Xã.',
             'gioi_thieu': [['Tên chức năng', 'Tìm kiếm và lọc danh sách'],
                            ['Mô tả', 'Thu hẹp danh sách bằng ô tìm kiếm nhanh, ô Quốc gia và ô Tỉnh/TP (hai ô lọc phụ thuộc nhau). Không có ô lọc Trạng thái.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Điều kiện ban đầu', 'Đang ở màn Danh mục Phường/Xã.'],
                            ['Dòng sự kiện chính', '1. Người dùng nhập từ khóa và bấm Tìm kiếm / Enter, hoặc chọn Quốc gia / Tỉnh/TP (lọc ngay).\n2. Hệ thống áp đồng thời mọi tiêu chí và nạp lại danh sách từ trang 1.'],
                            ['Dòng sự kiện phụ', '• Đổi Quốc gia → ô Tỉnh/TP bị xóa trắng, chỉ còn tỉnh/TP của quốc gia mới.\n• Không có kết quả → bảng hiện thông báo không có dữ liệu.\n• Bấm Làm mới → xóa hết tiêu chí VÀ nạp lại danh sách đầy đủ ngay.']],
             'anh': [('filter', 'Khu vực tìm kiếm và lọc của màn Danh mục Phường/Xã')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Phạm vi', 'Mô tả'],
                    ['1', 'Ô tìm kiếm nhanh', 'Textbox', 'Enable', '0–255 ký tự', 'Placeholder “Tìm theo tên phường/xã”. Tìm theo TÊN (khớp một phần), không tìm theo mã số.'],
                    ['2', 'Quốc gia', 'Dropdown', 'Enable', 'Danh mục quốc gia', 'Nhãn nổi. Bỏ trống thì hiện mọi quốc gia.'],
                    ['3', 'Tỉnh/TP', 'Dropdown', 'Enable', 'Tỉnh/TP của quốc gia đã chọn (hoặc tất cả)', 'Nhãn nổi. Bị xóa trắng khi đổi Quốc gia.'],
                    ['4', 'Nút Tìm kiếm', 'Button', 'Enable', '–', 'Áp dụng các tiêu chí.'],
                    ['5', 'Nút Làm mới', 'Button', 'Enable', '–', 'Xóa hết tiêu chí VÀ nạp lại danh sách ngay.']],
             'ui_widths': [0.6, 1.2, 0.8, 0.7, 1.1, 2.6],
             'events': [['Bấm Tìm kiếm / Enter', 'Click', 'After:\n– Áp đồng thời các tiêu chí theo kiểu “và”, nạp lại bảng từ trang 1.'],
                        ['Chọn Quốc gia', 'Change', 'After:\n– Xóa trắng ô Tỉnh/TP, lọc lại danh sách chọn Tỉnh/TP, nạp lại bảng từ trang 1.'],
                        ['Chọn Tỉnh/TP', 'Change', 'After:\n– Lọc ngay, nạp lại bảng từ trang 1.'],
                        ['Bấm Làm mới', 'Click', 'After:\n– Xóa trắng mọi tiêu chí VÀ nạp lại danh sách đầy đủ.']]},
            {'ten': 'Thêm mới phường/xã', 'uc': 'uc_fr03',
             'qtc': 'Màn Thêm mới, Validate dữ liệu, Thông báo và UI/UX. Logic ghi lịch sử áp dụng theo SRS Các quy tắc chung - Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Thêm mới phường/xã'],
                            ['Mô tả', 'Thêm một phường/xã mới thông qua cửa sổ nhập liệu.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập (chờ cập nhật theo phân quyền chi tiết).'],
                            ['Điều kiện ban đầu', 'Đang ở màn Danh mục Phường/Xã.'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm Tạo mới.\n2. Hệ thống mở cửa sổ “Tạo phường/xã”, Trạng thái mặc định Hoạt động.\n3. Người dùng nhập Tên phường/xã, Mã số, chọn Tỉnh/TP và bấm Lưu.\n4. Hệ thống kiểm tra dữ liệu, ghi bản ghi mới và ghi lịch sử Tạo mới.\n5. Cửa sổ đóng, danh sách nạp lại, báo “Thêm mới thành công”.'],
                            ['Dòng sự kiện phụ', '• Mã số sai định dạng → báo đỏ ngay khi gõ.\n• Thiếu trường bắt buộc hoặc trùng tên → báo lỗi đỏ dưới ô + toast “Vui lòng kiểm tra lại dữ liệu nhập”, cửa sổ KHÔNG đóng.\n• Bấm “Lưu và tiếp tục” → ghi bản ghi rồi giữ cửa sổ mở với các ô trống.\n• Bấm Đóng khi đã nhập dở → hỏi “Thông tin chưa lưu” (Thoát / Ở lại).'],
                            ['Yêu cầu đặc biệt', 'Cửa sổ có ba nút: Lưu, Lưu và tiếp tục, Đóng.']],
             'menu_them': ' => Tạo mới {icon:btn_taomoi}',
             'ghi_chu_layout': 'Cửa sổ Tạo phường/xã được mở ngay trên màn hình danh sách.',
             'anh': [('create', 'Cửa sổ Tạo phường/xã'), ('create_error', 'Lỗi đỏ ngay dưới ô còn thiếu'), ('code_error', 'Lỗi định dạng Mã số hiện ngay khi gõ')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Phạm vi', 'Bắt buộc', 'Mô tả'],
                    ['1', 'Tên phường/xã', 'Textbox', 'Enable', '1–255 ký tự', 'Có', 'Duy nhất trong cùng Tỉnh/TP. Bỏ trống “Bắt buộc phải nhập”; trùng “Tên phường/xã này đã tồn tại”; quá dài “Vui lòng nhập tối đa 255 ký tự.”'],
                    ['2', 'Mã số', 'Textbox', 'Enable', '1–10 chữ số', 'Có', 'Chỉ chữ số, giữ số 0 ở đầu, không yêu cầu duy nhất. Có chữ/ký tự đặc biệt “Phải là số”; quá 10 chữ số “Chỉ được nhập chữ số, từ 0 đến 10 chữ số”; bỏ trống “Bắt buộc phải nhập”.'],
                    ['3', 'Tỉnh/TP', 'Dropdown', 'Enable', 'Tỉnh/TP đang Hoạt động', 'Có', 'Bỏ trống “Bắt buộc phải nhập”.'],
                    ['4', 'Trạng thái', 'Dropdown', 'Enable', 'Hoạt động / Khóa', 'Có', 'Mặc định Hoạt động.'],
                    ['5', 'Nút Lưu', 'Button', 'Enable', '', '', 'Ghi bản ghi rồi đóng cửa sổ.'],
                    ['6', 'Nút Lưu và tiếp tục', 'Button', 'Enable', '', '', 'Ghi bản ghi rồi giữ cửa sổ mở để nhập tiếp.'],
                    ['7', 'Nút Đóng', 'Button', 'Enable', '', '', 'Hủy bỏ, không ghi gì.']],
             'ui_widths': [0.6, 1.3, 0.8, 0.6, 1.1, 0.5, 2.3],
             'events': [['Bấm nút Tạo mới', 'Click', 'After:\n– Mở cửa sổ nhập liệu với các ô trống, Trạng thái = Hoạt động.'],
                        ['Gõ Mã số', 'Input', 'During:\n– Kiểm tra chỉ chữ số và tối đa 10 chữ số, sai thì báo đỏ ngay dưới ô.'],
                        ['Bấm Lưu', 'Click', 'During:\n– Kiểm tra bắt buộc, định dạng, độ dài, trùng tên trong cùng Tỉnh/TP.\n– Có lỗi → báo đỏ dưới ô, không thực hiện After.\nAfter:\n– Ghi bản ghi mới, ghi lịch sử Tạo mới.\n– Đóng cửa sổ, nạp lại danh sách, báo “Thêm mới thành công”.'],
                        ['Bấm Lưu và tiếp tục', 'Click', 'During:\n– Như nút Lưu.\nAfter:\n– Ghi bản ghi, xóa trắng các ô, GIỮ cửa sổ mở.'],
                        ['Bấm Đóng', 'Click', 'After:\n– Chưa nhập gì → đóng cửa sổ. Đã nhập → hỏi “Thông tin chưa lưu”.']]},
            {'ten': 'Chỉnh sửa phường/xã', 'uc': 'uc_fr04',
             'qtc': 'Validate dữ liệu, Thông báo, Quy định chung về danh mục và Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Chỉnh sửa phường/xã'],
                            ['Mô tả', 'Sửa thông tin một phường/xã đã có. Dùng chung cửa sổ với Thêm mới.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Điều kiện ban đầu', 'Phường/xã đang ở trạng thái Hoạt động.'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm biểu tượng bút chì ở dòng cần sửa.\n2. Hệ thống mở cửa sổ “Sửa phường/xã” với dữ liệu hiện tại.\n3. Người dùng sửa và bấm Lưu.\n4. Hệ thống kiểm tra, ghi thay đổi và ghi lịch sử.\n5. Cửa sổ đóng, báo “Cập nhật thành công”.'],
                            ['Dòng sự kiện phụ', '• Giữ nguyên tên của chính bản ghi → không báo trùng.\n• Trùng tên với phường/xã khác cùng Tỉnh/TP → báo “Tên phường/xã này đã tồn tại”.\n• Phường/xã cũ chưa có Mã số → phải nhập Mã số mới lưu được.\n• Phường/xã đang được nhân sự sử dụng → ô Trạng thái bị khóa ở Hoạt động.\n• Bản ghi vừa bị người khác khóa → báo “Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.”']],
             'menu_them': ' => Sửa {icon:btn_sua}',
             'anh': [('edit', 'Cửa sổ Sửa phường/xã')],
             'events': [['Bấm biểu tượng bút chì', 'Click', 'Before:\n– Bản ghi đã Khóa thì nút không hiển thị.\nAfter:\n– Mở cửa sổ với dữ liệu hiện tại.'],
                        ['Bấm Lưu', 'Click', 'During:\n– Kiểm tra như Thêm mới, bỏ qua trùng với chính bản ghi.\n– Bản ghi đang Khóa → từ chối, báo “Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.”\n– Chọn Khóa cho phường/xã đang được sử dụng → báo “Không thể khóa phường/xã đang được sử dụng.”\nAfter:\n– Ghi thay đổi, ghi lịch sử “Thay đổi thông tin” (đổi Trạng thái ghi “Khóa”/“Mở khóa”), báo “Cập nhật thành công”.']]},
            {'ten': 'Xóa phường/xã', 'uc': 'uc_fr05',
             'qtc': 'Quy tắc Xóa, Thông báo, Quy định chung về danh mục và Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Xóa phường/xã'],
                            ['Mô tả', 'Xóa hẳn một phường/xã chưa được nhân sự sử dụng.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Điều kiện ban đầu', 'Phường/xã đang Hoạt động và chưa được nhân sự nào dùng làm địa chỉ thường trú/tạm trú.'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm biểu tượng thùng rác.\n2. Hệ thống hiện hộp “Xóa Phường/Xã” nêu rõ tên bản ghi.\n3. Người dùng bấm Xóa.\n4. Hệ thống xóa bản ghi, báo “Xoá phường/xã thành công”, nạp lại danh sách.'],
                            ['Dòng sự kiện phụ', '• Bấm Hủy → đóng hộp, không thay đổi.\n• Phường/xã đang được sử dụng hoặc đang Khóa → nút Xóa KHÔNG hiển thị.\n• Lỗi khi xóa → báo “Xoá phường/xã thất bại” (hoặc câu lỗi cụ thể từ hệ thống).']],
             'menu_them': ' => Xóa {icon:btn_xoa}',
             'anh': [('delete', 'Hộp xác nhận xóa phường/xã')],
             'events': [['Bấm biểu tượng thùng rác', 'Click', 'After:\n– Hiện hộp xác nhận kèm tên bản ghi.'],
                        ['Bấm Xóa', 'Click', 'After:\n– Xóa bản ghi, ghi lịch sử, nạp lại danh sách, báo thành công.'],
                        ['Bấm Hủy', 'Click', 'After:\n– Đóng hộp, không thay đổi.']]},
            {'ten': 'Khóa / Mở khóa phường/xã', 'uc': 'uc_fr06',
             'qtc': 'Quy tắc Khóa/Mở khóa, Thông báo, Quy định chung về danh mục và Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Khóa / Mở khóa phường/xã'],
                            ['Mô tả', 'Đổi trạng thái phường/xã giữa Hoạt động và Khóa. Bản ghi đã Khóa vẫn nằm trong danh mục nhưng không chọn được ở màn khác.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Điều kiện ban đầu', 'Khóa: phường/xã đang Hoạt động và chưa được nhân sự sử dụng. Mở khóa: phường/xã đang Khóa.'],
                            ['Dòng sự kiện chính', '1. Người dùng chọn Khóa (hoặc Mở khóa) ở cột Hành động.\n2. Hệ thống hiện hộp xác nhận nêu rõ tên bản ghi.\n3. Người dùng xác nhận.\n4. Hệ thống đổi trạng thái, ghi lịch sử, báo “Khóa thành công” / “Mở khóa thành công”.'],
                            ['Dòng sự kiện phụ', '• Bấm Hủy → không thay đổi.\n• Phường/xã đang được sử dụng → không có nút Khóa.\n• Sau khi Khóa, nút Sửa và Xóa biến mất.\n• Bản ghi đã bị người khác đổi trạng thái → báo “Trạng thái đã bị thay đổi. Vui lòng load lại trang”.']],
             'menu_them': ' => Khóa / Mở khóa',
             'anh': [('lock', 'Hộp xác nhận khóa phường/xã'), ('rowmenu', 'Các nút ở cột Hành động')],
             'events': [['Chọn Khóa / Mở khóa', 'Click', 'After:\n– Hiện hộp xác nhận kèm tên bản ghi.'],
                        ['Xác nhận', 'Click', 'During:\n– Bản ghi đã ở trạng thái đích → báo dữ liệu đã thay đổi, dừng.\nAfter:\n– Đổi trạng thái, KHÔNG xóa dữ liệu, ghi lịch sử, cập nhật cột Trạng thái và các nút.'],
                        ['Bấm Hủy', 'Click', 'After:\n– Đóng hộp, không thay đổi.']]},
            {'ten': 'Xem lịch sử thay đổi',
             'qtc': 'Quy tắc ghi lịch sử và hiển thị lịch sử. Chỉ bổ sung thông tin riêng của Danh mục Phường/Xã nếu có.',
             'gioi_thieu': [['Tên chức năng', 'Xem lịch sử thay đổi'],
                            ['Mô tả', 'Liệt kê các lần thay đổi của một phường/xã, kèm giá trị cũ → mới, người thực hiện và thời điểm. Tỉnh/TP hiển thị bằng tên.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Dòng sự kiện chính', '1. Người dùng chọn Lịch sử ở cột Hành động, hoặc mở cửa sổ Xem phường/xã.\n2. Hệ thống mở cửa sổ “Lịch sử thay đổi: <tên>”, mốc mới nhất ở trên cùng.'],
                            ['Dòng sự kiện phụ', '• Bản ghi chưa từng thay đổi → “Chưa có lịch sử thao tác nào.”\n• Có bộ lọc theo loại hành động, người thực hiện, thời gian.']],
             'menu_them': ' => Lịch sử',
             'anh': [('history', 'Cửa sổ Lịch sử thay đổi của phường/xã')]},
            {'ten': 'Import file phường/xã', 'uc': 'uc_fr08',
             'qtc': 'Quy tắc Import file, Validate dữ liệu, Thông báo và Quy định chung về danh mục. Chỉ bổ sung mapping/validation riêng của Danh mục Phường/Xã.',
             'gioi_thieu': [['Tên chức năng', 'Import file phường/xã'],
                            ['Mô tả', 'Thêm nhiều phường/xã cùng lúc từ file Excel mẫu, có bước Validate trước khi ghi.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Điều kiện ban đầu', 'Đang ở màn Danh mục Phường/Xã và đã chuẩn bị file theo mẫu.'],
                            ['Dòng sự kiện chính', '1. Bấm Import Excel.\n2. Bấm Tải file mẫu (Mau_import_phuong_xa.xlsx), điền dữ liệu.\n3. Bấm Chọn file Excel rồi Load lên bảng.\n4. Bấm Validate; hệ thống kiểm tra từng dòng như quy tắc Thêm mới (mục 2.3), khóa dòng hợp lệ.\n5. Sửa dòng lỗi rồi Validate lại, hoặc bấm Bỏ dòng lỗi.\n6. Bấm Import; hệ thống ghi các dòng hợp lệ, báo “Import thành công N phường/xã.”, đóng cửa sổ và nạp lại danh sách.'],
                            ['Dòng sự kiện phụ', '• File không phải .xlsx/.xls → “Vui lòng chọn file .xlsx hoặc .xls”.\n• Quá 500 dòng → “File có X dòng dữ liệu, vượt quá giới hạn 500 dòng mỗi lần import. Vui lòng tách file và import nhiều lần.”\n• Còn dòng lỗi → nút Import không bấm được.'],
                            ['Yêu cầu đặc biệt', 'Validate không ghi dữ liệu. Bản ghi import luôn ở trạng thái Hoạt động, người tạo là người thực hiện. Tỉnh/TP tra theo TÊN, không tự tạo tỉnh/TP mới.']],
             'menu_them': ' => Import Excel {icon:btn_import}',
             'ghi_chu_layout': 'Cửa sổ Import được mở ngay trên màn hình danh sách.',
             'anh': [('import_open', 'Cửa sổ Import phường/xã khi vừa mở'), ('import_loaded', 'Dữ liệu đã được load lên bảng xem trước'),
                     ('import_validated', 'Kết quả Validate — mỗi dòng lỗi nêu rõ lý do')],
             'bang_them': [('Quy tắc kiểm tra riêng của file Import', [['Cột', 'Quy tắc / thông báo lỗi'],
                            ['Tên phường/xã *', 'Bắt buộc (“Tên phường/xã không được để trống”), tối đa 255 ký tự (“Tên phường/xã tối đa 255 ký tự”), không trùng trong file (“Phường/xã bị trùng với dòng N trong file”), không trùng hệ thống trong cùng tỉnh/TP (“Phường/xã này đã tồn tại trong tỉnh/TP đã chọn”).'],
                            ['Mã số *', 'Bắt buộc (“Mã số không được để trống”), chỉ chữ số (“Mã số phải là số”), tối đa 10 chữ số (“Mã số tối đa 10 chữ số”). Không yêu cầu duy nhất.'],
                            ['Tỉnh/TP *', 'Bắt buộc (“Tỉnh/TP không được để trống”), chọn trong danh sách sổ xuống; ghi sai báo “Không tìm thấy tỉnh/TP: X”.']], [1.2, 4])]},
            {'ten': 'Xuất danh sách ra Excel', 'uc': 'uc_fr09',
             'qtc': 'Quy tắc Excel và Cấu hình cột. Chỉ bổ sung danh sách trường được phép xuất riêng của Danh mục Phường/Xã.',
             'gioi_thieu': [['Tên chức năng', 'Xuất danh sách phường/xã ra Excel'],
                            ['Mô tả', 'Xuất kết quả đang lọc ra file Excel, cho phép chọn trường và thứ tự cột.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Dòng sự kiện chính', '1. Bấm Xuất Excel.\n2. Hệ thống mở cửa sổ “Chọn trường xuất file”, tích sẵn đúng các cột đang hiển thị trên bảng.\n3. Người dùng tích chọn (kể cả Mã số) và kéo ☰ để sắp thứ tự.\n4. Bấm Xuất file; hệ thống tải dữ liệu theo từng lô 2,000 dòng, dựng file danh_muc_phuong_xa.xlsx theo đúng bộ lọc và thứ tự trường, báo “Xuất Excel thành công (N dòng)”.'],
                            ['Dòng sự kiện phụ', '• Bỏ chọn hết trường → nút Xuất file không bấm được.\n• Bộ lọc không có dòng nào → báo “Không có dữ liệu để xuất”, không tải file.\n• Đang xuất → nút Xuất Excel không bấm được lần hai.\n• Bấm Đóng → không xuất gì.'],
                            ['Yêu cầu đặc biệt', 'File chứa toàn bộ kết quả lọc (không giới hạn số dòng), không giới hạn ở trang đang xem. File có tiêu đề “DANH MỤC PHƯỜNG/XÃ” và cột STT ở đầu. Chỉ xuất Excel.']],
             'menu_them': ' => Xuất Excel {icon:btn_xuatexcel}',
             'anh': [('export', 'Cửa sổ Chọn trường xuất file')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
                    ['1', 'Danh sách trường', 'Checkbox chọn nhiều', 'Enable', 'Tích sẵn cột đang hiển thị', 'Tên phường/xã, Mã số, Tỉnh/TP, Quốc gia, Trạng thái, Người tạo, Ngày tạo, Người cập nhật, Ngày cập nhật. Kéo ☰ đổi thứ tự.'],
                    ['2', 'Nút Chọn tất cả / Bỏ chọn hết', 'Button', 'Enable', 'Hiển thị', 'Tích / bỏ tích toàn bộ.'],
                    ['3', 'Nút Xuất file', 'Button', 'Enable/Disable', 'Mờ khi chưa chọn trường', 'Tải dữ liệu theo lô, dựng file và tải về.'],
                    ['4', 'Nút Đóng', 'Button', 'Enable', 'Hiển thị', 'Đóng cửa sổ.']],
             'ui_widths': [0.6, 1.5, 1, 0.8, 1.2, 2.6]},
            {'ten': 'Xem chi tiết phường/xã', 'uc': 'uc_fr10',
             'qtc': 'Màn Xem chi tiết và Phân quyền.',
             'gioi_thieu': [['Tên chức năng', 'Xem chi tiết phường/xã'],
                            ['Mô tả', 'Cửa sổ “Xem phường/xã” hiển thị Tên phường/xã, Mã số, Tỉnh/TP, Trạng thái ở chế độ chỉ đọc, kèm khối Lịch sử.'],
                            ['Tác nhân', 'Người dùng đã đăng nhập'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm tên phường/xã ở danh sách.\n2. Hệ thống mở cửa sổ Xem, chỉ có nút Đóng.']],
             'anh': [('detail', 'Cửa sổ Xem phường/xã ở chế độ chỉ đọc')]},
            {'ten': 'Tùy chỉnh cột hiển thị',
             'qtc': 'Tùy chỉnh cột.',
             'gioi_thieu': [['Tên chức năng', 'Tùy chỉnh cột hiển thị'],
                            ['Mô tả', 'Bật/tắt và sắp xếp thứ tự cột của bảng; cấu hình lưu riêng theo người dùng.'],
                            ['Yêu cầu đặc biệt', 'Cột STT, Tên phường/xã, Hành động bị khóa. Mặc định ẩn: Quốc gia, Người cập nhật, Ngày cập nhật.']],
             'menu_them': ' => Cấu hình cột {icon:btn_cauhinhcot}',
             'anh': [('colcfg', 'Cửa sổ Tuỳ chỉnh cột')]},
        ],
        'quy_tac': [
            ('BR-01', 'Ràng buộc trùng tên',
             [
              'Tên phường/xã không được trùng trong cùng một Tỉnh/TP; cùng tên ở tỉnh/TP khác vẫn hợp lệ.',
              'Thông báo khi trùng: “Tên phường/xã này đã tồn tại”.',
              'Import Excel: báo “Phường/xã này đã tồn tại trong tỉnh/TP đã chọn” hoặc “Phường/xã bị trùng với dòng N trong file”.',
             ],
             ['Thêm mới phường/xã', 'Chỉnh sửa phường/xã', 'Import file phường/xã']),
            ('BR-02', 'Quy tắc Mã số',
             [
              'Mã số bắt buộc, chỉ gồm chữ số, tối đa 10 chữ số, giữ nguyên số 0 ở đầu.',
              'Mã số không yêu cầu duy nhất.',
             ],
             ['Thêm mới phường/xã', 'Chỉnh sửa phường/xã', 'Import file phường/xã']),
            ('BR-03', 'Mối quan hệ với các cấp địa chỉ khác',
             [
              'Mỗi phường/xã thuộc đúng một tỉnh/TP; ô chọn chỉ liệt kê tỉnh/TP đang Hoạt động, phường/xã đang dùng tỉnh/TP đã khóa vẫn giữ và hiển thị đúng tên kèm 🔒.',
              'Mọi Đường/Phố đều phải trỏ về một phường/xã; phường/xã còn được dùng làm địa chỉ thường trú / tạm trú trong hồ sơ nhân sự.',
             ],
             ['Thêm mới phường/xã', 'Chỉnh sửa phường/xã', 'Tạo mới các cấp địa chỉ khác. VD: Đường/Phố']),
            ('BR-04', 'Điều kiện xóa và khóa',
             [
              'Phường/xã đang được nhân sự dùng làm địa chỉ thường trú / tạm trú thì không Xóa, không Khóa được; nút Xóa và Khóa bị ẩn.',
              'Chọn Khóa ngay trong cửa sổ Sửa cũng bị máy chủ chặn: “Không thể khóa phường/xã đang được sử dụng.”',
              'Xóa là xóa hẳn bản ghi khỏi hệ thống.',
             ],
             ['Xóa phường/xã', 'Khóa / Mở khóa phường/xã', 'Chỉnh sửa phường/xã']),
            ('BR-05', 'Phường/xã đang Khóa',
             [
              'Không sửa, không xóa được; phải Mở khóa trước.',
              'Máy chủ chặn lưu khi sửa bản ghi đang Khóa: “Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.”',
              'Phường/xã Khóa không còn chọn được ở các màn khác; bản ghi đang dùng vẫn hiển thị đúng tên kèm 🔒.',
             ],
             ['Chỉnh sửa phường/xã', 'Xóa phường/xã', 'Khóa / Mở khóa phường/xã']),
            ('BR-06', 'Thao tác đồng thời',
             [
              'Hai người cùng Khóa / Mở khóa / Xóa một bản ghi: người bấm sau nhận thông báo “Trạng thái đã bị thay đổi. Vui lòng load lại trang”, thao tác không được thực hiện lại.',
             ],
             ['Xóa phường/xã', 'Khóa / Mở khóa phường/xã']),
            ('BR-07', 'Giới hạn Import',
             [
              'Mỗi lần nhập tối đa 500 dòng; phải Validate trước, bước Validate không ghi dữ liệu.',
              'Tỉnh/TP tra theo tên, không tự tạo mới.',
              'Phường/xã nhập từ Excel luôn ở trạng thái Hoạt động.',
             ],
             ['Import file phường/xã']),
            ('BR-08', 'Ghi lịch sử thay đổi',
             [
              'Mọi thao tác Tạo mới, Thay đổi thông tin (kể cả Mã số), Khóa, Mở khóa đều ghi lịch sử kèm người thực hiện.',
             ],
             ['Xem lịch sử thay đổi']),
        ],
    },
}

# ---- Lỗi code phát hiện khi rà (KHÔNG sửa code, báo user) ----
CFG['loi_code'] = [
    'File xuất Excel: cột “Mã số” luôn RỖNG — WardListResource::toArray() không trả key `code`, trong khi WardService::exportRows đọc $item[\'code\'] theo ExportColumnRegistry[\'wards\']. Tài liệu/testcase ghi theo thiết kế (cột Mã số có dữ liệu).',
    'Import: số dòng trong câu “Phường/xã bị trùng với dòng N trong file” không khớp chỗ nào người dùng nhìn thấy (WardService::validateRows dùng $index + 2): cột # của bảng xem trước đánh $index + 1 (V2BaseImportModal.vue dòng 324), còn trong file Excel dòng dữ liệu đầu là hàng 3.',
    'Ward::canDelete (Entities/Ward.php dòng 48-54) chỉ kiểm tra hồ sơ nhân sự (ward_id_residence / ward_id_address), không kiểm tra Đường/Phố (hamlets.ward_id) — phường/xã đã có đường/phố vẫn hiện nút Xóa, xóa xong đường/phố bị mồ côi. Xóa là xóa cứng (WardService::deleteWards gọi ->delete()).',
    'Import tra Tỉnh/TP theo tên bằng mapWithKeys trên TOÀN BỘ bảng provinces (WardService::importSnapshot): tên tỉnh/TP trùng nhau (kể cả tỉnh đã khóa) thì khớp vào bản ghi cuối cùng, không báo nhập nhằng như màn Quận/Huyện — phường/xã có thể bị gắn nhầm tỉnh/TP đã khóa.',
    'Xóa / Khóa từ danh sách: điều kiện “phường/xã đang được nhân sự sử dụng” chỉ chặn ở FE (ẩn nút); endpoint DELETE /{id} và PUT /{id}/lock không kiểm tra canDelete() — gọi thẳng API vẫn xóa/khóa được phường/xã đang dùng (chỉ đường Lưu trong cửa sổ Sửa có chặn “Không thể khóa phường/xã đang được sử dụng.”).',
    'Dữ liệu: 8,939/13,465 phường/xã chưa có Mã số nhưng Mã số là bắt buộc — sửa bất kỳ phường/xã cũ nào cũng phải nhập mã số mới lưu được.',
]

# ---- Nhóm testcase Xuất Excel riêng cho màn này (file dựng ở trình duyệt, không giới hạn 10,000 dòng) ----
_TRUONG = 'Tên phường/xã, Mã số, Tỉnh/TP, Quốc gia, Trạng thái, Người tạo, Ngày tạo, Người cập nhật, Ngày cập nhật'
_EXPORT_CASES = [
    ('Mở cửa sổ Chọn trường xuất file', 'P0', 'Đang ở màn danh sách, chưa chỉnh cấu hình cột.',
     '1. Bấm nút Xuất Excel\n2. Đọc danh sách trường trong cửa sổ',
     '', '- Mở cửa sổ “Chọn trường xuất file”\n- Có đủ các trường: %s\n- Tích sẵn đúng các cột đang hiển thị trên bảng (Tên phường/xã, Tỉnh/TP, Người tạo, Ngày tạo, Trạng thái); Mã số KHÔNG được tích sẵn vì bảng không có cột này\n- Dòng cuối ghi “Đang chọn a/b trường”' % _TRUONG),
    ('Xuất file với các trường mặc định', 'P0', 'Đang mở cửa sổ Chọn trường xuất file.',
     '1. Giữ nguyên các trường đã tích\n2. Bấm Xuất file\n3. Mở file vừa tải',
     '', '- Tải về file danh_muc_phuong_xa.xlsx, báo “Xuất Excel thành công (N dòng)” với N là số dòng xuất ra\n- File có tiêu đề “DANH MỤC PHƯỜNG/XÃ”, cột STT ở đầu, đúng các cột đã tích, dữ liệu khớp với bảng trên màn hình'),
    ('Cột Mã số trong file có dữ liệu', 'P0', 'Có phường/xã đã khai Mã số (vd Phường Cửa Nam – 00082).',
     '1. Lọc Tỉnh/TP = Thành phố Hà Nội\n2. Bấm Xuất Excel, tích thêm Mã số\n3. Bấm Xuất file, mở file',
     'Phường Cửa Nam – Mã số 00082', '- Cột Mã số hiện đúng mã của từng phường/xã, giữ số 0 ở đầu (00082)\n- Phường/xã chưa khai mã thì ô để trống'),
    ('File xuất chạy theo bộ lọc đang áp dụng', 'P0', 'Đang lọc danh sách còn vài phường/xã.',
     '1. Áp dụng bộ lọc (Quốc gia / Tỉnh/TP / từ khóa)\n2. Bấm Xuất Excel → Xuất file\n3. Đếm số dòng trong file',
     '', '- File chỉ chứa các phường/xã khớp bộ lọc\n- Số dòng bằng tổng số bản ghi ở cuối bảng và bằng N trong thông báo'),
    ('Xuất toàn bộ kết quả, không chỉ trang đang xem', 'P1', 'Không áp bộ lọc nào (toàn danh mục, hơn 13,000 dòng).',
     '1. Đứng ở trang 1\n2. Bấm Xuất Excel → Xuất file\n3. Chờ tải xong',
     '', '- File chứa TOÀN BỘ phường/xã (không giới hạn 10,000 dòng), không chỉ 10 dòng của trang 1\n- Trong lúc xuất, nút Xuất Excel không bấm được lần hai'),
    ('Bộ lọc không có kết quả', 'P2', 'Đang lọc ra 0 dòng (vd từ khóa zzzkhongtontai999).',
     '1. Bấm Xuất Excel → Xuất file',
     'Từ khóa: zzzkhongtontai999', '- Báo “Không có dữ liệu để xuất”\n- Không tải file nào'),
    ('Bỏ tích một trường', 'P1', 'Đang mở cửa sổ Chọn trường xuất file.',
     '1. Bỏ tích một trường bất kỳ\n2. Bấm Xuất file',
     '', '- File KHÔNG có cột vừa bỏ tích, các cột còn lại giữ nguyên'),
    ('Đổi thứ tự cột bằng kéo ☰', 'P2', 'Đang mở cửa sổ Chọn trường xuất file.',
     '1. Kéo biểu tượng ☰ của trường cuối lên đầu danh sách\n2. Bấm Xuất file',
     '', '- Trong file, cột đó đứng đầu (ngay sau STT), đúng thứ tự vừa kéo'),
    ('Chọn tất cả / Bỏ chọn hết', 'P2', 'Đang mở cửa sổ Chọn trường xuất file.',
     '1. Bấm Bỏ chọn hết\n2. Quan sát nút Xuất file\n3. Bấm Chọn tất cả',
     '', '- Bỏ chọn hết: không trường nào được tích, nút Xuất file không bấm được\n- Chọn tất cả: tích đủ mọi trường'),
    ('Bấm Đóng thì không xuất', 'P2', 'Đang mở cửa sổ Chọn trường xuất file.',
     '1. Bấm Đóng', '', '- Cửa sổ đóng, không tải file nào'),
]

# ---- Sửa tab testcase "15. DM phườngxã" (đọc từ ref/testcase_tab.txt) ----
CFG['tc'] = {
    'tab': '15. DM phườngxã',
    'hdr_row': 78,            # "VII. LỊCH SỬ THAY ĐỔI"
    'blocks': [
        # Quy tắc ô Mã số khi Thêm mới — chèn cuối nhóm III (R40..R50), theo ghi chú review R92
        {'after': 50, 'merge_from': 40, 'cases': [
            ('TC_03.012', 'Mã số đúng 10 chữ số', 'P1', 'Đang ở cửa sổ thêm mới, các ô khác đã nhập hợp lệ.',
             '1. Nhập đúng 10 chữ số vào ô Mã số\n2. Bấm Lưu',
             'Mã số: 1234567890',
             '- Không báo lỗi ô Mã số\n- Lưu thành công'),
            ('TC_03.013', 'Mã số vượt quá 10 chữ số', 'P1', 'Đang ở cửa sổ thêm mới.',
             '1. Nhập 11 chữ số vào ô Mã số\n2. Quan sát ô\n3. Bấm Lưu',
             'Mã số: 12345678901',
             '- Báo lỗi đỏ ngay dưới ô “Chỉ được nhập chữ số, từ 0 đến 10 chữ số”\n- Bấm Lưu không tạo bản ghi, cửa sổ KHÔNG đóng'),
            ('TC_03.014', 'Mã số có ký tự đặc biệt', 'P1', 'Đang ở cửa sổ thêm mới.',
             '1. Nhập mã có ký tự đặc biệt vào ô Mã số\n2. Bấm Lưu',
             'Mã số: 12-3 / 12@3',
             '- Báo lỗi đỏ ngay dưới ô “Phải là số”\n- Cửa sổ KHÔNG đóng, không tạo bản ghi'),
            ('TC_03.015', 'Mã số giữ số 0 ở đầu', 'P1', 'Đang ở cửa sổ thêm mới.',
             '1. Nhập đủ các ô, Mã số bắt đầu bằng số 0\n2. Bấm Lưu\n3. Mở cửa sổ Xem phường/xã vừa tạo',
             'Mã số: 00109',
             '- Lưu thành công\n- Cửa sổ Xem hiện Mã số đúng “00109”, không mất số 0 ở đầu'),
            ('TC_03.016', 'Mã số không yêu cầu duy nhất', 'P2', 'Đã có phường/xã A với Mã số 00082.',
             '1. Thêm mới phường/xã B (tên khác A) với cùng Mã số 00082\n2. Bấm Lưu',
             'Mã số: 00082',
             '- Lưu thành công, không báo trùng mã'),
        ]},
        # Quy tắc ô Mã số khi Sửa — chèn cuối nhóm IV (R52..R61), theo ghi chú review R93
        {'after': 61, 'merge_from': 52, 'cases': [
            ('TC_04.012', 'Bỏ trống Mã số khi sửa', 'P1', 'Đang mở cửa sổ sửa một phường/xã có Mã số.',
             '1. Xóa trắng ô Mã số\n2. Bấm Lưu',
             'Mã số: (để trống)',
             '- Báo lỗi đỏ dưới ô Mã số “Bắt buộc phải nhập”, không lưu'),
            ('TC_04.013', 'Mã số không hợp lệ khi sửa', 'P1', 'Đang mở cửa sổ sửa một phường/xã.',
             '1. Nhập chữ cái vào ô Mã số, quan sát\n2. Đổi thành 11 chữ số, quan sát\n3. Bấm Lưu',
             'Mã số: abc / 12345678901',
             '- Bước 1: báo “Phải là số”\n- Bước 2: báo “Chỉ được nhập chữ số, từ 0 đến 10 chữ số”\n- Bước 3: không lưu, cửa sổ KHÔNG đóng'),
            ('TC_04.014', 'Sửa phường/xã cũ chưa có Mã số', 'P1', 'Có phường/xã cũ chưa khai Mã số.',
             '1. Mở cửa sổ sửa phường/xã đó\n2. Chỉ đổi tên, để trống Mã số, bấm Lưu\n3. Nhập Mã số hợp lệ, bấm Lưu',
             'Mã số: (trống) / 00123',
             '- Bước 2: báo “Bắt buộc phải nhập” dưới ô Mã số, không lưu\n- Bước 3: lưu thành công'),
        ]},
        {'after': 90,             # TC_07.012 — case cuối của nhóm VII (trước các dòng ghi chú review R91–R95)
         'groups': [('VIII', 'XUẤT EXCEL (bổ sung 25/09/2026)', 8, _EXPORT_CASES),
                    ('IX', 'IMPORT TỪ FILE EXCEL (bổ sung 25/09/2026)', 9, 'import')]},
    ],
    'import_rows_dung': 'File mẫu điền 2 phường/xã hợp lệ (DOC-Phường Mẫu Một – 90001 – Thành phố Hà Nội, DOC-Phường Mẫu Hai – 00902 – Thành phố Hồ Chí Minh), chưa có trong danh mục',
    'import_loi_data': {
        'Tên phường/xã không được để trống': 'Tên phường/xã: (để trống); Mã số: 90003; Tỉnh/TP: Thành phố Hà Nội',
        'Tên phường/xã tối đa 255 ký tự': 'Tên phường/xã: chuỗi 256 ký tự',
        'Mã số không được để trống': 'Mã số: (để trống)',
        'Mã số phải là số': 'Mã số: AB12',
        'Mã số tối đa 10 chữ số': 'Mã số: 12345678901',
        'Tỉnh/TP không được để trống': 'Tỉnh/TP: (để trống)',
        'Không tìm thấy tỉnh/TP: X': 'Tỉnh/TP: Tỉnh không tồn tại',
        'Phường/xã bị trùng với dòng N trong file': 'Hai dòng cùng tên “DOC-Phường Mẫu Một”, cùng Thành phố Hà Nội',
        'Phường/xã này đã tồn tại trong tỉnh/TP đã chọn': 'Tên phường/xã: Phường Cửa Nam; Tỉnh/TP: Thành phố Hà Nội',
    },
    'edits': [
        ('B8', 'Màn hình này KHÔNG khai báo quyền nào. Mọi người dùng đã đăng nhập đều mở được màn hình và thực hiện được đầy đủ Thêm mới, Chỉnh sửa, Xóa, Khóa, Mở khóa, Import Excel và Xuất Excel.\n Phía máy chủ cũng không kiểm tra quyền, nên gọi thẳng chức năng mà bỏ qua giao diện vẫn ghi được dữ liệu. Đây là hiện trạng của mã nguồn, đã được ghi nhận để bộ phận quản trị cân nhắc bổ sung quyền.'),
    ],
    'clear_k': [],
}

CFG['tc_ngoai_pham_vi'] = [
    'R20 (TC_01.002): liệt kê cột “Người sửa” (TP đã ghi “không có cột người sửa”) — tên thật là “Người cập nhật”, mặc định ẩn cùng Quốc gia, Ngày cập nhật.',
    'R66 (TC_05.004) “Xóa bản ghi đang được dùng → hệ thống từ chối nêu lý do”: thực tế nút Xóa bị ẨN khi phường/xã đang được nhân sự dùng làm địa chỉ.',
    'R69 (TC_06.001) “Menu ba chấm có Khóa và Lịch sử”: chỉ đúng khi dòng có đủ 4 nút; phường/xã đang được sử dụng chỉ có Sửa + Lịch sử (không có Khóa, không có ba chấm). Nên thêm case “phường/xã đang được sử dụng không có nút Xóa/Khóa, ô Trạng thái trong cửa sổ Sửa bị khóa”.',
    'R75 (TC_06.007) lọc theo Trạng thái = Khóa: màn hình KHÔNG có ô lọc Trạng thái (TP đã đánh F) — case cần bỏ hoặc sửa.',
    'R89 (TC_07.011) “Bản ghi chưa từng sửa → Chưa có lịch sử thao tác nào”: hệ thống có ghi mốc Tạo mới nên cửa sổ hiện mốc Tạo mới (TP đã đánh F) — expected cần sửa.',
    'R54: TC ID nhảy từ TC_04.002 sang TC_04.004 (thiếu 04.003).',
    'R58–R60: tên hộp thoại ghi “Thông tin chưa được lưu”, chữ thật là “Thông tin chưa lưu”.',
    'Ghi chú review R91, R93 (phần ngoài mã số), R94, R95 chưa xử lý: phân trang, sắp xếp Ngày cập nhật, giữ nguyên tên khi sửa, bỏ trống Tỉnh/TP khi sửa, chuyển phường/xã sang tỉnh khác, mở khóa bản ghi đã bị người khác đổi trạng thái, lịch sử khi mở khóa / sửa nhiều trường / bấm Lưu không đổi gì. Phần mã số của R92, R93 đã bổ sung thành TC_03.012–016 và TC_04.012–014.',
]


# ---- Bổ sung 28/09/2026: “Mô tả chi tiết giao diện” + “Danh sách event và xử lý event” cho SRS ----
# Tester báo thiếu 2 mục này ở các chức năng sau Thêm mới. Nguồn: code gop_db 28/09/2026 (FE pages/human/wards, component
# dùng chung V2BaseImportModal / export-fields-modal / column-customization-modal / CatalogHistoryModal; BE Modules/Human).
_FR = {f['ten']: f for f in CFG['srs']['fr']}
_FR['Chỉnh sửa phường/xã'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Phạm vi', 'Bắt buộc', 'Giá trị ban đầu', 'Mô tả'],
        ['1', 'Tên phường/xã', 'Textbox', 'Enable', '1–255 ký tự', 'Có', 'Dữ liệu hiện tại', 'Không trùng trong cùng Tỉnh/TP, bỏ qua chính bản ghi đang sửa. Bỏ trống “Bắt buộc phải nhập”; trùng “Tên phường/xã này đã tồn tại”; quá dài “Vui lòng nhập tối đa 255 ký tự.”'],
        ['2', 'Mã số', 'Textbox', 'Enable', '1–10 chữ số', 'Có', 'Dữ liệu hiện tại', 'Chỉ chữ số, giữ số 0 ở đầu. Phường/xã cũ chưa có mã số thì phải nhập mới lưu được. Sai “Phải là số” / “Chỉ được nhập chữ số, từ 0 đến 10 chữ số”; bỏ trống “Bắt buộc phải nhập”.'],
        ['3', 'Tỉnh/TP', 'Dropdown', 'Enable', 'Tỉnh/TP đang Hoạt động', 'Có', 'Dữ liệu hiện tại', 'Tỉnh/TP đã khóa mà bản ghi đang dùng vẫn hiện đúng tên kèm 🔒. Bỏ trống “Bắt buộc phải nhập”.'],
        ['4', 'Trạng thái', 'Dropdown', 'Enable / Disable', 'Hoạt động / Khóa', 'Có', 'Dữ liệu hiện tại', 'Phường/xã đang được nhân sự dùng làm địa chỉ → ô bị khóa ở Hoạt động (không chọn được Khóa). Chọn Khóa rồi Lưu cũng là khóa phường/xã.'],
        ['5', 'Nút Lưu', 'Button', 'Enable', '–', '–', 'Hiển thị', 'Ghi thay đổi rồi đóng cửa sổ.'],
        ['6', 'Nút Đóng / biểu tượng X', 'Button', 'Enable', '–', '–', 'Hiển thị', 'Đóng cửa sổ, không ghi gì. Đã sửa dở thì hỏi “Thông tin chưa lưu” — “Bạn có thông tin chưa lưu. Có chắc chắn muốn thoát?” (Thoát / Ở lại). Chế độ Sửa không có nút “Lưu và tiếp tục”.'],
        ['7', 'Thông báo lỗi', 'Label', 'Hiển thị khi lỗi', '–', '–', 'Ẩn', 'Chữ đỏ ngay dưới ô bị lỗi, kèm thông báo chung “Vui lòng kiểm tra lại dữ liệu nhập”.'],
    ],
    'ui_widths': [0.5, 1.2, 0.8, 0.6, 1.1, 0.6, 0.8, 1.9],
    'events': [
        ['Bấm biểu tượng bút chì (Sửa)', 'Click', 'Before:\n– Nút chỉ hiển thị khi bản ghi đang Hoạt động; bản ghi Khóa không có nút Sửa.\nAfter:\n– Mở cửa sổ “Sửa phường/xã” với dữ liệu hiện tại đã điền sẵn.'],
        ['Bấm Lưu', 'Click', 'During:\n– Tên phường/xã, Mã số, Tỉnh/TP để trống → “Bắt buộc phải nhập”.\n– Mã số sai định dạng → “Phải là số” / “Chỉ được nhập chữ số, từ 0 đến 10 chữ số”.\n– Trùng tên với phường/xã khác trong cùng Tỉnh/TP → “Tên phường/xã này đã tồn tại”.\n– Chọn Khóa cho phường/xã đang được sử dụng → “Không thể khóa phường/xã đang được sử dụng.”\n– Bỏ qua kiểm tra trùng đối với chính bản ghi đang sửa.\n– Bản ghi đang Khóa (vừa bị người khác khóa) → từ chối, báo “Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.”\n– Có lỗi → báo đỏ dưới ô, cửa sổ KHÔNG đóng, không thực hiện bước After.\nAfter:\n– Ghi thay đổi, ghi Người cập nhật và một dòng lịch sử “Thay đổi thông tin” nêu giá trị cũ → mới (đổi Trạng thái ghi dòng “Thay đổi trạng thái” riêng).\n– Đóng cửa sổ, nạp lại danh sách, báo “Cập nhật thành công”.'],
        ['Bấm Đóng / biểu tượng X / bấm ra ngoài cửa sổ', 'Click', 'After:\n– Chưa sửa gì → đóng cửa sổ.\n– Đã sửa → hỏi “Thông tin chưa lưu” — “Bạn có thông tin chưa lưu. Có chắc chắn muốn thoát?” (Thoát / Ở lại); chọn Thoát thì đóng, không ghi; chọn Ở lại thì giữ nguyên dữ liệu đang nhập.'],
    ],
})
_FR['Xóa phường/xã'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Mô tả'],
        ['1', 'Biểu tượng thùng rác (Xóa)', 'Icon Button', 'Nằm ở cột Hành động của từng dòng. Chỉ hiển thị khi phường/xã đang Hoạt động và chưa được nhân sự nào dùng làm địa chỉ thường trú/tạm trú; ngược lại nút bị ẩn hẳn.'],
        ['2', 'Tiêu đề hộp xác nhận', 'Label', '“Xóa Phường/Xã”.'],
        ['3', 'Nội dung hộp xác nhận', 'Label', '“Bạn có chắc muốn xóa phường/xã "<tên>"?” — nêu rõ tên bản ghi để tránh xóa nhầm dòng.'],
        ['4', 'Nút Xóa', 'Button', 'Xác nhận xóa hẳn bản ghi khỏi hệ thống.'],
        ['5', 'Nút Hủy', 'Button', 'Đóng hộp, không thay đổi gì.'],
    ],
    'ui_widths': [0.6, 1.8, 1.0, 3.6],
    'events': [
        ['Bấm biểu tượng thùng rác', 'Click', 'Before:\n– Nút chỉ hiển thị khi phường/xã đang Hoạt động và chưa được nhân sự nào dùng làm địa chỉ thường trú/tạm trú.\nAfter:\n– Hiện hộp xác nhận “Xóa Phường/Xã” kèm tên bản ghi.'],
        ['Bấm Xóa trong hộp xác nhận', 'Click', 'During:\n– Bản ghi không còn tồn tại (người khác vừa xóa) → báo “Trạng thái đã bị thay đổi. Vui lòng load lại trang”, dừng xử lý.\nAfter:\n– Xóa hẳn bản ghi (không khôi phục được), đóng hộp, nạp lại danh sách, báo “Xoá phường/xã thành công”.\n– Lỗi khác → báo câu lỗi của hệ thống hoặc “Xoá phường/xã thất bại”.'],
        ['Bấm Hủy', 'Click', 'After:\n– Đóng hộp xác nhận, không thay đổi gì.'],
    ],
})
_FR['Khóa / Mở khóa phường/xã'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Mô tả'],
        ['1', 'Nút Khóa / Mở khóa', 'Button', 'Nằm ở cột Hành động (trong nút ba chấm nếu dòng có từ 4 nút trở lên). Nhãn đổi theo trạng thái. Dòng Hoạt động: nút Khóa CHỈ hiện khi phường/xã chưa được nhân sự dùng làm địa chỉ. Dòng Khóa: luôn có Mở khóa.'],
        ['2', 'Nút ba chấm “Hành động khác”', 'Icon Button', 'Hiện khi dòng có từ 4 nút trở lên: 2 nút đầu hiện thẳng, các nút còn lại (Khóa, Lịch sử) nằm trong menu này.'],
        ['3', 'Tiêu đề hộp xác nhận', 'Label', '“Khóa Phường/Xã” hoặc “Mở khóa Phường/Xã” tùy trạng thái hiện tại.'],
        ['4', 'Nội dung hộp xác nhận', 'Label', '“Bạn có chắc muốn khóa phường/xã "<tên>"?” / “Bạn có chắc muốn mở khóa phường/xã "<tên>"?”.'],
        ['5', 'Nút Khóa / Mở khóa trong hộp', 'Button', 'Xác nhận thực hiện.'],
        ['6', 'Nút Hủy', 'Button', 'Đóng hộp, không làm gì.'],
        ['7', 'Cột Trạng thái', 'Badge', 'Hoạt động hoặc Khóa, hai màu khác nhau; cập nhật ngay sau thao tác.'],
    ],
    'ui_widths': [0.6, 1.8, 1.0, 3.6],
    'events': [
        ['Bấm nút ba chấm', 'Click', 'After:\n– Mở menu chứa các nút còn lại của dòng (Khóa / Mở khóa, Lịch sử).'],
        ['Chọn Khóa hoặc Mở khóa', 'Click', 'After:\n– Hiện hộp xác nhận kèm tên bản ghi.'],
        ['Bấm Khóa / Mở khóa trong hộp', 'Click', 'During:\n– Bản ghi không còn tồn tại hoặc đã ở trạng thái đích (người khác vừa thao tác) → báo “Trạng thái đã bị thay đổi. Vui lòng load lại trang”, dừng xử lý, không ghi thêm lịch sử.\nAfter:\n– Đổi trạng thái, KHÔNG xóa dữ liệu; ghi Người cập nhật và một dòng lịch sử “Khóa” / “Mở khóa”.\n– Đóng hộp, báo “Khóa thành công” / “Mở khóa thành công”, nạp lại danh sách: sau Khóa ẩn nút Sửa, Xóa; sau Mở khóa hiện lại nút Sửa (Xóa hiện lại nếu đủ điều kiện xóa).\n– Lỗi khác → báo câu lỗi của hệ thống hoặc “Thao tác thất bại”.'],
        ['Bấm Hủy', 'Click', 'After:\n– Đóng hộp xác nhận, trạng thái không đổi.'],
    ],
})
_FR['Xem lịch sử thay đổi'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Giá trị ban đầu', 'Mô tả'],
        ['1', 'Nút Lịch sử', 'Button', 'Hiển thị', 'Nằm ở cột Hành động (trong nút ba chấm nếu dòng có từ 4 nút). Luôn có ở mọi dòng, kể cả bản ghi Khóa.'],
        ['2', 'Tiêu đề cửa sổ', 'Label', 'Lịch sử thay đổi: <tên phường/xã>', 'Ghép tên bản ghi để biết đang xem dòng nào.'],
        ['3', 'Nút Bộ lọc', 'Button', 'Vùng lọc đang ẩn', 'Bấm để hiện / ẩn vùng lọc; vùng lọc ghim ở đầu khi cuộn danh sách.'],
        ['4', 'Loại hành động', 'Dropdown', 'Trống (“Tất cả loại hành động”)', 'Lọc theo Tạo mới, Thay đổi thông tin, Thay đổi trạng thái, Khóa, Mở khóa… Chọn là lọc ngay.'],
        ['5', 'Người thực hiện', 'Dropdown', 'Trống (“Tất cả người thực hiện”)', 'Chọn là lọc ngay.'],
        ['6', 'Từ ngày / Đến ngày', 'Date picker', 'Trống', 'Định dạng dd/mm/yyyy. Chọn là lọc ngay.'],
        ['7', 'Nút Làm mới (vùng lọc)', 'Button', 'Hiển thị', 'Xóa hết tiêu chí lọc, hiện lại toàn bộ lịch sử.'],
        ['8', 'Danh sách thay đổi', 'Timeline', 'Mới nhất ở trên cùng', 'Mỗi mốc gồm: thời điểm (dd/mm/yyyy hh:mm); loại hành động (Tạo mới, Thay đổi thông tin, Thay đổi trạng thái, Khóa, Mở khóa); “Người thực hiện: …”; từng trường đã đổi dạng “Tên trường: giá trị cũ → giá trị mới”. Trường Tỉnh/TP hiển thị bằng tên.'],
        ['9', 'Trạng thái rỗng', 'Label', 'Ẩn', '“Chưa có lịch sử thao tác nào.” khi bản ghi chưa có lịch sử; “Không có lịch sử phù hợp bộ lọc.” khi lọc không ra kết quả.'],
        ['10', 'Nút Đóng / biểu tượng X', 'Button', 'Hiển thị', 'Đóng cửa sổ.'],
    ],
    'ui_widths': [0.6, 1.5, 0.9, 1.2, 2.8],
    'events': [
        ['Chọn Lịch sử ở cột Hành động', 'Click', 'After:\n– Mở cửa sổ “Lịch sử thay đổi: <tên>”, nạp danh sách thay đổi theo thứ tự mới nhất trước.\n– Không tải được → hiện “Không tải được lịch sử phiếu.” kèm nút Thử lại.'],
        ['Bấm Bộ lọc', 'Click', 'After:\n– Hiện / ẩn vùng lọc.'],
        ['Đổi Loại hành động / Người thực hiện / Từ ngày / Đến ngày', 'Change', 'After:\n– Lọc ngay danh sách theo mọi tiêu chí đã chọn (không có nút Tìm kiếm).'],
        ['Bấm Làm mới trong vùng lọc', 'Click', 'After:\n– Xóa trắng tiêu chí, hiện lại toàn bộ lịch sử.'],
        ['Bấm Đóng / biểu tượng X', 'Click', 'After:\n– Đóng cửa sổ; danh sách phía sau giữ nguyên bộ lọc và trang đang xem.'],
    ],
})
_FR['Import file phường/xã'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Bắt buộc', 'Giá trị ban đầu', 'Mô tả'],
        ['1', 'Nút Import Excel', 'Button', 'Enable', '–', 'Hiển thị', 'Nằm trên thanh công cụ của bảng danh sách. Mở cửa sổ “Import phường/xã” (dòng phụ “Import từ Excel • Validate xong dòng hợp lệ sẽ bị khoá”).'],
        ['2', 'Nút Chọn file Excel', 'Button', 'Enable', 'Có', 'Chưa chọn file', 'Chọn file .xlsx hoặc .xls từ máy; tên file hiện ngay cạnh nút.'],
        ['3', 'Nút Tải file mẫu', 'Button', 'Enable', '–', 'Hiển thị', 'Tải file Mau_import_phuong_xa.xlsx gồm cột STT, Tên phường/xã *, Mã số *, Tỉnh/TP * (ô chọn sẵn danh sách tỉnh/TP). Hàng 1 là tiêu đề, hàng 2 là dòng mô tả, dữ liệu nhập từ hàng 3.'],
        ['4', 'Nút Load lên bảng', 'Button', 'Enable / Disable', '–', 'Mờ khi chưa chọn file', 'Đọc file và đổ dữ liệu lên bảng xem trước.'],
        ['5', 'Nút Validate', 'Button', 'Enable / Disable', '–', 'Mờ khi bảng chưa có dòng nào', 'Gửi dữ liệu lên máy chủ kiểm tra từng dòng; dòng hợp lệ bị khóa lại, không sửa được nữa.'],
        ['6', 'Nút Import', 'Button', 'Enable / Disable', '–', 'Mờ', 'Chỉ bấm được khi đã Validate, không còn dòng lỗi và có ít nhất 1 dòng hợp lệ. Ghi các dòng hợp lệ vào danh mục.'],
        ['7', 'Ô Tổng / Hợp lệ / Lỗi', 'Label', 'Read-only', '–', 'Tổng: 0', 'Sau Load hiện “Tổng”; sau Validate hiện thêm “Hợp lệ”, “Lỗi”. Có dòng vừa sửa hiện “Có dòng đã sửa (cần validate lại)”.'],
        ['8', 'Bảng xem trước', 'Table/Grid', 'Enable', '–', 'Trống', 'Cột #, Tên phường/xã *, Mã số *, Tỉnh/TP *. Dòng lỗi sửa trực tiếp được (Tên phường/xã, Mã số gõ lại; Tỉnh/TP chọn trong danh sách).'],
        ['9', 'Thông báo lỗi theo dòng', 'Label', 'Hiển thị', '–', 'Ẩn', 'Dòng lỗi viền đỏ, lý do ghi ngay dưới dòng: “Tên phường/xã không được để trống”; “Tên phường/xã tối đa 255 ký tự”; “Mã số không được để trống”; “Mã số phải là số”; “Mã số tối đa 10 chữ số”; “Tỉnh/TP không được để trống”; “Không tìm thấy tỉnh/TP: X”; “Phường/xã bị trùng với dòng N trong file”; “Phường/xã này đã tồn tại trong tỉnh/TP đã chọn”.'],
        ['10', 'Nút Bỏ dòng lỗi', 'Button', 'Enable / Disable', '–', 'Mờ khi bảng trống', 'Loại mọi dòng lỗi khỏi bảng, báo “Đã bỏ N dòng lỗi. Còn lại M dòng hợp lệ.”; chưa Validate thì báo “Hãy Validate trước rồi mới bỏ dòng lỗi.”'],
        ['11', 'Nút Xoá trạng thái validate', 'Button', 'Enable / Disable', '–', 'Mờ khi bảng trống', 'Bỏ khóa các dòng hợp lệ và xóa kết quả kiểm tra để sửa lại.'],
        ['12', 'Nút Làm mới', 'Button', 'Enable', '–', 'Hiển thị', 'Bỏ file đã chọn và toàn bộ bảng, đưa cửa sổ về trạng thái ban đầu.'],
        ['13', 'Nút Đóng / biểu tượng X', 'Button', 'Enable', '–', 'Hiển thị', 'Đóng cửa sổ, không ghi gì.'],
    ],
    'ui_widths': [0.5, 1.3, 0.9, 0.8, 0.5, 1.1, 2.4],
    'events': [
        ['Bấm Import Excel', 'Click', 'After:\n– Mở cửa sổ “Import phường/xã” ở trạng thái rỗng.'],
        ['Bấm Tải file mẫu', 'Click', 'After:\n– Tải file Mau_import_phuong_xa.xlsx về máy.\n– Lỗi → báo “Lỗi khi tạo file mẫu”.'],
        ['Chọn file', 'Change', 'During:\n– File không phải .xlsx / .xls → báo “Vui lòng chọn file .xlsx hoặc .xls”, bỏ file.\nAfter:\n– Hiện tên file, nút Load lên bảng sáng lên.'],
        ['Bấm Load lên bảng', 'Click', 'During:\n– File không có dòng dữ liệu → “Không có dòng dữ liệu hợp lệ.”\n– Quá 500 dòng → “File có X dòng dữ liệu, vượt quá giới hạn 500 dòng mỗi lần import. Vui lòng tách file và import nhiều lần.”\n– File hỏng / không đọc được → “Không đọc được file Excel.”\nAfter:\n– Đổ dữ liệu lên bảng xem trước, cập nhật ô Tổng.'],
        ['Bấm Validate', 'Click', 'During:\n– Máy chủ kiểm tra từng dòng theo đúng quy tắc của chức năng Thêm mới và bảng “Quy tắc kiểm tra riêng của file Import”.\n– KHÔNG ghi bất kỳ bản ghi nào ở bước này.\nAfter:\n– Còn dòng lỗi: tô đỏ dòng lỗi kèm lý do, khóa dòng hợp lệ, báo “Validate xong: X hợp lệ, Y không hợp lệ. (Dòng hợp lệ đã bị khoá, chỉ có thể sửa dòng lỗi)”.\n– Không còn dòng lỗi: báo “Tất cả N dòng đã hợp lệ. Có thể import ngay.”, nút Import sáng lên.\n– Không dòng nào hợp lệ: báo “Không có dòng nào hợp lệ để import. Hãy sửa các dòng lỗi và validate lại.”'],
        ['Sửa ô ở dòng lỗi', 'Input', 'After:\n– Dòng chuyển về chưa kiểm tra, hiện “Có dòng đã sửa (cần validate lại)”; phải Validate lại mới Import được.'],
        ['Bấm Bỏ dòng lỗi / Xoá trạng thái validate', 'Click', 'After:\n– Bỏ dòng lỗi: chỉ giữ dòng hợp lệ, nút Import sáng lên.\n– Xoá trạng thái validate: mở khóa mọi dòng, xóa kết quả kiểm tra.'],
        ['Bấm Import', 'Click', 'During:\n– Chỉ gửi các dòng hợp lệ; máy chủ kiểm tra lại toàn bộ, không tin kết quả Validate trước đó.\n– Không còn dòng hợp lệ → báo “Không có dòng nào hợp lệ để import”, dừng.\nAfter:\n– Tạo phường/xã mới ở trạng thái Hoạt động, người tạo là người đang thực hiện.\n– Báo “Import thành công N phường/xã.” (có dòng thất bại: “Import thành công X/Y phường/xã. Z dòng thất bại.”), đóng cửa sổ, nạp lại danh sách.'],
        ['Bấm Làm mới / Đóng', 'Click', 'After:\n– Làm mới: xóa file và bảng, giữ cửa sổ mở.\n– Đóng: đóng cửa sổ, không ghi gì.'],
    ],
})
_FR['Xuất danh sách ra Excel'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
        ['1', 'Nút Xuất Excel', 'Button', 'Enable / Disable', 'Hiển thị', 'Nằm trên thanh công cụ của bảng danh sách. Mở cửa sổ “Chọn trường xuất file”. Mờ trong lúc đang xuất.'],
        ['2', 'Dòng hướng dẫn', 'Label', 'Read-only', 'Hiển thị', '“Tích chọn trường cần xuất, kéo ☰ để đổi thứ tự cột trong file.”'],
        ['3', 'Danh sách trường', 'Checkbox chọn nhiều', 'Enable', 'Tích sẵn đúng các cột đang hiển thị trên bảng, xếp lên đầu theo thứ tự trên bảng', 'Chín trường: Tên phường/xã, Mã số, Tỉnh/TP, Quốc gia, Trạng thái, Người tạo, Ngày tạo, Người cập nhật, Ngày cập nhật. Kéo biểu tượng ☰ để đổi vị trí cột trong file.'],
        ['4', 'Nút Chọn tất cả', 'Button', 'Enable', 'Hiển thị', 'Tích toàn bộ trường.'],
        ['5', 'Nút Bỏ chọn hết', 'Button', 'Enable', 'Hiển thị', 'Bỏ tích toàn bộ trường.'],
        ['6', 'Dòng đếm trường', 'Label', 'Read-only', 'Hiển thị', '“Đang chọn a/N trường”.'],
        ['7', 'Nút Xuất file', 'Button', 'Enable / Disable', 'Mờ khi chưa chọn trường nào', 'Đóng cửa sổ, sinh file Excel và tải về máy.'],
        ['8', 'Nút Đóng / biểu tượng X', 'Button', 'Enable', 'Hiển thị', 'Đóng cửa sổ, không xuất.'],
    ],
    'ui_widths': [0.6, 1.5, 1.0, 0.8, 1.3, 2.3],
    'events': [
        ['Bấm Xuất Excel', 'Click', 'After:\n– Mở cửa sổ “Chọn trường xuất file”, tích sẵn đúng các cột đang hiển thị trên bảng (theo cấu hình cột của người dùng), các trường còn lại liệt kê bên dưới chưa tích. Không nhớ lựa chọn của lần xuất trước.'],
        ['Tích / bỏ tích trường, kéo ☰', 'Change', 'During:\n– Thứ tự trong danh sách là thứ tự cột trong file.\n– Bỏ chọn hết → nút Xuất file mờ đi.'],
        ['Bấm Xuất file', 'Click', 'During:\n– Tải dữ liệu theo ĐÚNG bộ lọc và thứ tự sắp xếp đang áp dụng, lần lượt từng lô 2,000 dòng cho tới hết (không giới hạn tổng số dòng), rồi dựng file có tiêu đề “DANH MỤC PHƯỜNG/XÃ” và cột STT ở đầu, các cột theo đúng thứ tự trường đã chọn.\n– Trong lúc đang xuất, nút Xuất Excel không bấm được lần hai.\nAfter:\n– Tải file danh_muc_phuong_xa.xlsx về máy, báo “Xuất Excel thành công (N dòng)”.\n– Bộ lọc không ra dòng nào → báo “Không có dữ liệu để xuất”, không tải file.\n– Lỗi → báo “Lỗi khi xuất Excel”.'],
        ['Bấm Đóng / biểu tượng X', 'Click', 'After:\n– Đóng cửa sổ, không xuất gì.'],
    ],
})
_FR['Xem chi tiết phường/xã'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
        ['1', 'Tên phường/xã ở cột Tên phường/xã', 'Link', 'Enable', 'Hiển thị', 'Bấm vào tên để mở cửa sổ Xem (thay cho nút “Xem” ở cột Hành động). Bản ghi Khóa vẫn mở được.'],
        ['2', 'Tiêu đề cửa sổ', 'Label', 'Read-only', 'Xem phường/xã', 'Kèm biểu tượng tròn ở đầu tiêu đề.'],
        ['3', 'Tên phường/xã', 'Textbox', 'Read-only', 'Dữ liệu hiện tại', 'Chỉ đọc, không sửa được.'],
        ['4', 'Mã số', 'Textbox', 'Read-only', 'Dữ liệu hiện tại', 'Chỉ đọc, không sửa được. Trống với phường/xã cũ chưa có mã số.'],
        ['5', 'Tỉnh/TP', 'Dropdown', 'Read-only', 'Dữ liệu hiện tại', 'Chỉ đọc, không sửa được. Tỉnh/TP đã khóa vẫn hiện đúng tên kèm 🔒.'],
        ['6', 'Trạng thái', 'Dropdown', 'Read-only', 'Dữ liệu hiện tại', 'Chỉ đọc, không sửa được.'],
        ['7', 'Khối Lịch sử', 'Panel thu gọn', 'Enable', 'Thu gọn', 'Tiêu đề “Lịch sử” kèm số lần thay đổi. Nút “Xem lịch sử” mở khối (đổi thành “Thu gọn”), nút “Làm mới” nạp lại. Nội dung, bộ lọc giống cửa sổ Lịch sử thay đổi.'],
        ['8', 'Nút Đóng / biểu tượng X', 'Button', 'Enable', 'Hiển thị', 'Đóng cửa sổ. Cửa sổ Xem KHÔNG có nút Lưu, Lưu và tiếp tục hay Sửa.'],
    ],
    'ui_widths': [0.6, 1.5, 1.0, 0.8, 1.3, 2.3],
    'events': [
        ['Bấm tên phường/xã ở danh sách', 'Click', 'After:\n– Mở cửa sổ “Xem phường/xã”, nạp dữ liệu hiện tại của bản ghi ở chế độ chỉ đọc.\n– Không tải được → báo “Lỗi khi tải dữ liệu” và đóng cửa sổ.'],
        ['Bấm Xem lịch sử / Thu gọn', 'Click', 'After:\n– Lần mở đầu tiên mới nạp lịch sử; hiện danh sách thay đổi mới nhất ở trên.\n– Thu gọn: ẩn khối, không nạp lại.'],
        ['Bấm Làm mới trong khối Lịch sử', 'Click', 'After:\n– Nạp lại lịch sử mới nhất của bản ghi.'],
        ['Bấm Đóng / biểu tượng X', 'Click', 'After:\n– Đóng cửa sổ, không hỏi xác nhận (không có gì để lưu).'],
    ],
})
_FR['Tùy chỉnh cột hiển thị'].update({
    'ui': [
        ['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
        ['1', 'Biểu tượng Cấu hình cột hiển thị', 'Icon Button', 'Enable', 'Hiển thị', 'Nút cuối cùng trên thanh công cụ của bảng. Mở cửa sổ “Tuỳ chỉnh cột”.'],
        ['2', 'Danh sách cột', 'Checkbox', 'Enable', 'Theo cấu hình đã lưu; chưa lưu lần nào thì hiện Tỉnh/TP, Người tạo, Ngày tạo, Trạng thái, ẩn Quốc gia, Người cập nhật, Ngày cập nhật', 'Liệt kê đủ 10 cột theo thứ tự trên bảng: STT, Tên phường/xã, Tỉnh/TP, Quốc gia, Người cập nhật, Ngày cập nhật, Người tạo, Ngày tạo, Trạng thái, Hành động. Tích = hiện cột, bỏ tích = ẩn cột.'],
        ['3', 'Cột bắt buộc', 'Checkbox', 'Disable', 'Luôn tích', 'STT, Tên phường/xã, Hành động: xám, có biểu tượng khóa, không bỏ tích và không kéo đổi vị trí được (rê chuột hiện “Cột bắt buộc — không thể ẩn hoặc đổi vị trí”).'],
        ['4', 'Biểu tượng ☰', 'Drag handle', 'Enable', 'Hiển thị', 'Kéo thả để đổi thứ tự các cột không bắt buộc.'],
        ['5', 'Nút Lưu', 'Button', 'Enable', 'Hiển thị', 'Áp dụng ngay cho bảng và lưu cấu hình theo TÀI KHOẢN người dùng trên máy chủ (đăng nhập máy/trình duyệt khác vẫn giữ).'],
        ['6', 'Nút Đóng / biểu tượng X', 'Button', 'Enable', 'Hiển thị', 'Đóng cửa sổ, bỏ các thay đổi chưa Lưu.'],
    ],
    'ui_widths': [0.6, 1.5, 1.0, 0.8, 1.3, 2.3],
    'events': [
        ['Bấm biểu tượng Cấu hình cột hiển thị', 'Click', 'After:\n– Mở cửa sổ “Tuỳ chỉnh cột”, tích đúng theo các cột đang hiển thị.'],
        ['Tích / bỏ tích, kéo ☰', 'Change', 'During:\n– Chỉ thay đổi trong cửa sổ, bảng chưa đổi.\n– Cột bắt buộc không bỏ tích, không kéo được.'],
        ['Bấm Lưu', 'Click', 'After:\n– Bảng hiện/ẩn và sắp cột theo cấu hình mới, lưu cấu hình theo người dùng, báo “Cập nhật thành công”; đóng cửa sổ.\n– Lần Xuất Excel sau tích sẵn đúng các cột đang hiện.\n– Lỗi lưu → báo “Thao tác thất bại”.'],
        ['Bấm Đóng / biểu tượng X', 'Click', 'After:\n– Đóng cửa sổ, trả danh sách về cấu hình đang áp dụng.'],
    ],
})


# Đồng bộ chỗ tester sửa tay trên Drive (so bản Drive 28/09/2026) — build_srs áp qua apply_tester_edits
CFG['srs_tester'] = {
 "del": [
  "Không có bản ghi khớp → bảng hiện “Không có dữ liệu phù hợp bộ lọc.”",
  "Không có kết quả → bảng hiện thông báo không có dữ liệu.",
  "Bấm “Lưu và tiếp tục” → ghi bản ghi rồi giữ cửa sổ mở với các ô trống.",
  "Giữ nguyên tên của chính bản ghi → không báo trùng.",
  "Lỗi khi xóa → báo “Xoá phường/xã thất bại” (hoặc câu lỗi cụ thể từ hệ thống).",
  "File không phải .xlsx/.xls → “Vui lòng chọn file .xlsx hoặc .xls”.",
  "Quá 500 dòng → “File có X dòng dữ liệu, vượt quá giới hạn 500 dòng mỗi lần import. Vui lòng tách file và import nhiều lần.”"
 ],
 "br": {}
}
