# -*- coding: utf-8 -*-
# Cấu hình tài liệu màn Danh mục vụ việc — bám mẫu configs/areas.py.
# Nguồn: code gop_db 25/09/2026, cập nhật 28/09/2026 (xoá hẳn khi chưa dùng + Khoá/Mở khoá ở danh sách,
#   bỏ luật cấm khoá khi đã hạch toán; Entities/Work.php USAGE_REFERENCES, middleware recordNotLocked)
#   FE: pages/finance/works/index.vue, pages/finance/works/WorkModal.vue, components/subsystem-menu/finance.js
#   BE: Modules/Finance/Http/Controllers/V1/WorkController.php, Services/WorkService.php,
#       Http/Requests/WorkRequest.php, Entities/Work.php, app/Rules/CodeChars.php, ExportColumnRegistry['works']
# Không ghi URL. Chữ UI / message lấy nguyên văn code.

DT = 'vụ việc'
QUYEN = 'Quản lý danh mục vụ việc'
MSG_MA = 'Chỉ gồm chữ không dấu, số, dấu - và _'
MSG_USED = 'Vụ việc đang được sử dụng, không thể xóa.'
MSG_LOCKED = 'Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.'
MSG_CONFLICT = 'Trạng thái đã bị thay đổi. Vui lòng load lại trang'
# Nơi được coi là "đã sử dụng" (Work::USAGE_REFERENCES, đọc bằng tên nghiệp vụ)
USED_W = ('bút toán kế toán, phiếu điều chỉnh công nợ, phiếu nhập kho, phiếu xuất kho, đề nghị thanh toán, phiếu chi, '
          'đề nghị tạm ứng, hạch toán chuyến giao hàng, kết chuyển, đề nghị bổ sung hạch toán, hạch toán mua dịch vụ, '
          'hạch toán bảo hiểm, thanh toán bảo hành, sắp xếp giao hàng nhập/xuất kho')

CFG = {
    'slug': 'works',
    'ten': 'Danh mục vụ việc',
    'doi_tuong': DT,
    'file_hdsd': 'HDSD_Danh mục vụ việc.docx',
    'file_srs': 'SRS - Danh mục vụ việc.docx',
    'menu': [('Tài chính', 'menu_phanhe'), ('Danh mục', 'menu_nhom'), ('Danh mục vụ việc', 'menu_muc')],
    'form_type': 'popup',

    'capture': {'route': '/finance/works',
                'menu': {'phanhe': 'TÀI CHÍNH', 'nhom': 'Danh mục', 'muc': 'Danh mục vụ việc'},
                'search': 'Tìm theo mã, tên vụ việc', 'searchText': 'Tách hàng', 'detailCol': 1,
                'codeInput': 'VD: VV001', 'lockName': 'Vé cầu đường', 'create': True, 'lock': True},

    'thuat_ngu': [
        ['Vụ việc', 'Đối tượng tập hợp chi phí và doanh thu trong kế toán, dùng để theo dõi hiệu quả của từng công việc hoặc từng hợp đồng.'],
        ['Mã vụ việc', 'Mã do người dùng tự đặt (hệ thống không tự sinh), chỉ gồm chữ không dấu, số, dấu - và _; duy nhất trên toàn hệ thống, dùng để chọn nhanh khi lập bút toán.'],
        ['Trạng thái Hoạt động', 'Vụ việc còn chọn được khi lập bút toán mới.'],
        ['Trạng thái Khóa', 'Vụ việc ngừng dùng: không còn chọn được khi lập chứng từ mới, không sửa và không xóa được cho tới khi Mở khóa; vẫn nằm trong danh mục và các chứng từ cũ giữ nguyên.'],
        ['Vụ việc đã được sử dụng', 'Vụ việc đã được chọn ở ít nhất một chứng từ: ' + USED_W + '. Vụ việc đã được sử dụng thì không xóa được (vẫn Khóa được).'],
    ],
    'phien_ban': [
        ['1.0', '17/08/2026', 'Đội phát triển phần mềm', 'Lập mới cho màn Danh mục vụ việc.'],
        ['1.1', '25/09/2026', 'Đội phát triển phần mềm', 'Cập nhật theo phiên bản hiện tại: quy tắc nhập Mã vụ việc, nút Lưu và tiếp tục, Xem chi tiết, Xuất Excel (cửa sổ Chọn trường xuất file), Import Excel, Tùy chỉnh cột, bộ lọc nhãn nổi; trình bày theo mẫu tài liệu danh mục chung.'],
        ['1.2', '28/09/2026', 'Đội phát triển phần mềm', 'Bổ sung Khóa / Mở khóa ngay ở cột Hành động; bỏ quy tắc cấm khóa vụ việc đã phát sinh hạch toán; vụ việc đang Khóa ẩn nút Sửa, Xóa và bị máy chủ chặn cập nhật; Xóa là xóa hẳn, chỉ khi vụ việc đang Hoạt động và chưa được sử dụng ở chứng từ nào (liệt kê đầy đủ các chứng từ được tính).'],
    ],
    'muc_dich': [
        'Danh mục vụ việc là nơi khai báo danh sách vụ việc dùng cho nghiệp vụ kế toán. Dữ liệu của màn này được chọn khi lập bút toán, nên mỗi thay đổi ở đây đều ảnh hưởng tới sổ sách.',
    ],
    'quyen': {
        'truoc': ['Màn hình dùng đúng MỘT quyền cho cả xem lẫn thao tác, không tách quyền xem riêng:'],
        'rows': [[QUYEN, 'Thấy mục menu, mở màn hình và thực hiện đầy đủ: Thêm mới, Chỉnh sửa, Xóa, Khóa, Mở khóa, Xem lịch sử, Xem chi tiết, Import Excel, Xuất Excel.']],
        'sau': ['Nếu không có quyền này, mục menu Danh mục vụ việc sẽ không hiển thị và hệ thống từ chối mọi thao tác trên màn hình.'],
    },

    'danh_sach': {
        'mo_ta_vao': 'Hệ thống hiển thị danh sách vụ việc hiện có (gồm cả vụ việc Hoạt động lẫn Khóa), mặc định 10 dòng mỗi trang, mới tạo xếp trên cùng.',
        'bo_cuc': [
            'Khu vực tìm kiếm và lọc — ô tìm kiếm nhanh, nút Tìm kiếm nâng cao (mở các ô Trạng thái, Người tạo, Người cập nhật), nút Tìm kiếm và Làm mới.',
            'Thanh công cụ — nút Tạo mới, nút Xuất Excel, nút Import Excel và biểu tượng Cấu hình cột hiển thị.',
            'Bảng “Danh sách vụ việc” — các cột thông tin, cột Hành động ở cuối, và phân trang bên dưới.',
        ],
        'cot': [
            ['STT', 'Số thứ tự, chạy liên tục qua các trang. Luôn hiển thị.'],
            ['Mã vụ việc', 'Mã do người dùng đặt. Luôn hiển thị, sắp xếp được. Bấm vào mã để mở cửa sổ Xem vụ việc.'],
            ['Tên vụ việc', 'Tên đầy đủ, sắp xếp được.'],
            ['Ghi chú', 'Ghi chú tự do. Mặc định ẩn.'],
            ['Người cập nhật', 'Người sửa bản ghi gần nhất. Mặc định ẩn.'],
            ['Ngày cập nhật', 'Thời điểm sửa gần nhất, dạng dd/mm/yyyy hh:mm. Mặc định ẩn, sắp xếp được.'],
            ['Người tạo', 'Người đã thêm bản ghi.'],
            ['Ngày tạo', 'Thời điểm thêm, dạng dd/mm/yyyy hh:mm, sắp xếp được.'],
            ['Trạng thái', 'Nhãn Hoạt động hoặc Khóa.'],
            ['Hành động', 'Các nút thao tác của dòng (xem mục 4).'],
        ],
        'hanh_dong': {
            'intro': 'Trên mỗi dòng, cột Hành động có các nút:',
            'bullets': [
                'Biểu tượng bút chì {icon:btn_sua} — mở cửa sổ Sửa vụ việc. Chỉ hiện khi vụ việc đang Hoạt động.',
                'Biểu tượng thùng rác {icon:btn_xoa} — xóa hẳn vụ việc. Chỉ hiện khi vụ việc đang Hoạt động VÀ chưa được sử dụng ở chứng từ nào (xem mục Xóa).',
                'Khóa (vụ việc đang Hoạt động) / Mở khóa (vụ việc đang Khóa) — đổi trạng thái vụ việc.',
                'Lịch sử — mở cửa sổ Lịch sử thay đổi.',
                'Có từ 4 nút trở lên thì 2 nút đầu hiện thẳng, các nút còn lại nằm trong nút ba chấm {icon:btn_bacham} “Hành động khác”.',
            ],
            'anh': 'Các nút ở cột Hành động của một vụ việc',
            'luu_y': ['Lưu ý quan trọng: với vụ việc ĐÃ KHÓA, nút Sửa và Xóa sẽ BIẾN MẤT, chỉ còn Mở khóa và Lịch sử. Muốn sửa lại, Người dùng phải Mở khóa trước. Vụ việc đang Hoạt động nhưng đã được sử dụng thì có Sửa, Khóa, Lịch sử (không có Xóa).'],
        },
        'phan_trang': [
            'Cuối bảng có dòng “Hiển thị a–b / N”: N là tổng số vụ việc khớp bộ lọc đang áp dụng, không phải tổng toàn danh mục.',
            'Ô Số dòng/trang có các mức 5, 10, 20, 50, 100 (mặc định 10). Đổi số dòng thì hệ thống tự quay về trang 1.',
            'Các cột sắp xếp được: Mã vụ việc, Tên vụ việc, Ngày tạo, Ngày cập nhật. Bấm tiêu đề cột để sắp xếp, bấm lần hai để đảo chiều. Thứ tự sắp xếp được giữ nguyên khi chuyển trang.',
        ],
    },

    'loc': {
        'buoc2': 'Bước 2: Nhập chữ vào ô tìm kiếm nhanh, hoặc bấm Tìm kiếm nâng cao rồi chọn giá trị ở ô Trạng thái, Người tạo, Người cập nhật.',
        'rows': [
            ['Ô tìm kiếm nhanh', 'Placeholder “Tìm theo mã, tên vụ việc”. Tìm theo MÃ hoặc TÊN vụ việc (gõ một phần cũng ra). Nhấn Enter hoặc bấm Tìm kiếm để lọc.'],
            ['Trạng thái', 'Hoạt động hoặc Khóa. Bỏ trống thì hiện cả hai trạng thái. Lọc ngay khi chọn.'],
            ['Người tạo', 'Chọn một nhân viên để chỉ xem vụ việc do người đó tạo. Lọc ngay khi chọn.'],
            ['Người cập nhật', 'Chọn một nhân viên để chỉ xem vụ việc do người đó sửa gần nhất. Lọc ngay khi chọn.'],
        ],
        'ap_dung': [
            'Ba ô Trạng thái, Người tạo, Người cập nhật nằm trong khối Tìm kiếm nâng cao, có nhãn nổi ở góc trên mỗi ô. Bấm nút Tìm kiếm nâng cao để mở / thu gọn khối này.',
            'Các tiêu chí kết hợp với nhau theo kiểu VÀ — chỉ bản ghi thỏa đồng thời tất cả các tiêu chí mới hiện ra. Mỗi lần đổi tiêu chí, danh sách quay về trang 1.',
            'Bấm {icon:btn_lammoi} để xóa toàn bộ tiêu chí; danh sách nạp lại đầy đủ ngay lập tức.',
        ],
        'anh_ket_qua': 'Kết quả tìm nhanh theo tên vụ việc (gõ “Tách hàng”)',
    },

    'form': {
        'kieu': 'popup',
        'buoc_tao': [
            'Bước 1: Truy cập vào màn hình Danh mục vụ việc.',
            'Bước 2: Bấm {icon:btn_taomoi}. Hệ thống mở cửa sổ “Tạo vụ việc”.',
            'Bước 3: Nhập/ chọn thông tin: Mã vụ việc, Tên vụ việc, Trạng thái, Ghi chú.',
            'Bước 4: Bấm {icon:btn_luu} để lưu và đóng cửa sổ, hoặc {icon:btn_luutieptuc} để lưu rồi nhập tiếp vụ việc khác.',
        ],
        'anh_tao': 'Cửa sổ Tạo vụ việc',
        'truong': [
            ['Mã vụ việc', 'Ô nhập giá trị', 'Có', 'Trống (gợi ý “VD: VV001”)', 'Người dùng TỰ NHẬP, hệ thống không tự sinh mã. Chỉ gồm chữ không dấu, số, dấu - và _ — gõ sai hệ thống báo ngay dưới ô “%s”. Duy nhất toàn hệ thống, không phân biệt chữ hoa/chữ thường (VV001 và vv001 coi là trùng); trùng báo “Mã vụ việc đã tồn tại”. Bỏ trống báo “Bắt buộc phải nhập”. Mã được lưu đúng như người dùng gõ.' % MSG_MA],
            ['Tên vụ việc', 'Ô nhập giá trị', 'Có', 'Trống', 'Bỏ trống báo “Bắt buộc phải nhập”. KHÔNG bắt buộc duy nhất — hai vụ việc khác mã được phép trùng tên.'],
            ['Trạng thái', 'Ô chọn giá trị', 'Không', 'Hoạt động', 'Chọn 1 trong 2 giá trị: Hoạt động / Khóa. Chọn Khóa để ngừng dùng vụ việc ở chứng từ mới — chọn được kể cả khi vụ việc đã được sử dụng.'],
            ['Ghi chú', 'Ô nhập nhiều dòng', 'Không', 'Trống', 'Ghi chú tự do, 3 dòng.'],
        ],
        'sau_truong': [
            'Lưu ý: ô Mã vụ việc được kiểm tra bắt buộc ở bước lưu. Nếu để trống cả Mã lẫn Tên rồi bấm Lưu, lần đầu hệ thống chỉ báo đỏ ô Tên vụ việc; nhập Tên xong bấm Lưu lại thì mới báo “Bắt buộc phải nhập” ở ô Mã vụ việc.',
        ],
        'nut': [
            ['Lưu', 'Ghi bản ghi rồi đóng cửa sổ, báo “Thêm mới thành công” (hoặc “Cập nhật thành công” khi sửa) và nạp lại danh sách.'],
            ['Lưu và tiếp tục', 'Ghi bản ghi nhưng GIỮ cửa sổ mở và xóa trắng các ô để nhập tiếp. Chỉ có khi Tạo mới.'],
            ['Đóng', 'Đóng cửa sổ, không ghi gì. Nếu đã nhập dở, hệ thống hỏi “Thông tin chưa lưu” — “Bạn có thông tin chưa lưu. Có chắc chắn muốn thoát?” (Thoát / Ở lại).'],
        ],
        'loi': [
            ['Bắt buộc phải nhập', 'Chưa nhập Mã vụ việc hoặc Tên vụ việc.'],
            [MSG_MA, 'Mã vụ việc có dấu cách, chữ tiếng Việt có dấu hoặc ký tự đặc biệt (ví dụ “VV 001”, “VVĐ01”, “VV@01”). Báo ngay khi gõ.'],
            ['Mã vụ việc đã tồn tại', 'Đã có vụ việc khác dùng mã này (kể cả khác chữ hoa/chữ thường). Hãy tra lại danh sách trước khi thêm.'],
            ['Vui lòng kiểm tra lại dữ liệu nhập', 'Thông báo chung khi còn ô bị lỗi; xem các ô báo đỏ trong cửa sổ.'],
        ],
    },

    'sua': {
        'buoc': [
            'Bước 1: Truy cập vào màn hình Danh mục vụ việc.',
            'Bước 2: Bấm nút {icon:btn_sua} ở cột Hành động của vụ việc cần sửa.',
            'Bước 3: Hệ thống hiển thị cửa sổ “Sửa vụ việc” với dữ liệu hiện tại.',
            'Bước 4: Cập nhật các thông tin cần sửa (quy tắc nhập như Thêm mới, kể cả quy tắc Mã vụ việc).',
            'Bước 5: Bấm {icon:btn_luu} để xác nhận thay đổi hoặc Đóng nếu muốn hủy.',
        ],
        'anh': 'Cửa sổ Sửa vụ việc',
        'ghi_chu': [
            'Giữ nguyên mã của chính vụ việc đang sửa thì không bị báo trùng.',
            'Cửa sổ Sửa chỉ có nút Lưu và Đóng (không có Lưu và tiếp tục).',
            'Vụ việc đang Khóa không có nút Sửa. Nếu vụ việc vừa bị người khác khóa trong lúc đang mở cửa sổ Sửa, bấm Lưu sẽ nhận thông báo “%s”' % MSG_LOCKED,
            'Có thể khóa ngay trong cửa sổ Sửa bằng cách chọn Trạng thái = Khóa rồi Lưu (kể cả khi vụ việc đã được sử dụng).',
            'Mọi thay đổi đều được ghi vào Lịch sử kèm tên người sửa và thời điểm.',
        ],
    },
    'xoa': {
        'buoc': [
            'Bước 1: Ở cột Hành động, Người dùng bấm {icon:btn_xoa}.',
            'Bước 2: Hệ thống hiện hộp xác nhận “Xóa vụ việc” — “Bạn có chắc muốn xóa vụ việc "…"?”. Bấm {icon:btn_confirm_xoa} để xác nhận: hệ thống báo “Đã xóa thành công”, bản ghi biến mất khỏi danh sách.',
            'Bấm {icon:btn_huy} nếu bấm nhầm. Không có gì thay đổi.',
        ],
        'anh': 'Hộp xác nhận xóa vụ việc',
        'ghi_chu': [
            'Xóa là xóa HẲN vụ việc khỏi danh mục (không phải chuyển sang Khóa). Nút Xóa chỉ hiện khi vụ việc đang Hoạt động VÀ chưa được sử dụng ở chứng từ nào.',
            'Vụ việc được coi là “đã sử dụng” khi đã được chọn ở ít nhất một trong các chứng từ: ' + USED_W + '. Vụ việc đã được sử dụng thì dùng Khóa thay cho Xóa.',
            'Nếu vụ việc vừa được sử dụng trong lúc đang mở màn hình, bấm Xóa sẽ nhận thông báo “%s”; vừa bị người khác khóa thì nhận “%s”; vừa bị người khác xóa thì nhận “%s”.' % (MSG_USED, MSG_LOCKED, MSG_CONFLICT),
        ],
    },
    'lich_su': {
        'buoc': [
            'Xem từ màn danh sách: ở cột Hành động, Người dùng bấm Lịch sử. Hệ thống mở cửa sổ “Lịch sử thay đổi: <mã> - <tên vụ việc>”.',
            'Xem từ màn chi tiết: bấm vào mã vụ việc để mở cửa sổ Xem vụ việc, khối Lịch sử nằm ở cuối cửa sổ.',
        ],
        'ghi_chu': [
            'Khóa / Mở khóa (từ cột Hành động hoặc đổi Trạng thái trong cửa sổ Sửa) được ghi thành mốc riêng loại Thay đổi trạng thái.',
            'Cửa sổ có bộ lọc riêng (loại hành động, người thực hiện, khoảng thời gian) để thu hẹp danh sách khi bản ghi có nhiều lần thay đổi. Bản ghi chưa có thao tác nào hiện “Chưa có lịch sử thao tác nào.”',
        ],
    },
    'chi_tiet': {
        'buoc': ['Bước 1: Truy cập vào màn hình Danh mục vụ việc.',
                 'Bước 2: Bấm vào mã vụ việc ở cột Mã vụ việc. Hệ thống mở cửa sổ “Xem vụ việc”.'],
        'ghi_chu': ['Cửa sổ hiển thị Mã vụ việc, Tên vụ việc, Trạng thái và Ghi chú ở chế độ chỉ đọc (không gõ được, không có nút Lưu), kèm khối Lịch sử ở cuối. Vụ việc đang Khóa vẫn xem được bình thường.'],
    },
    'khoa': {
        'y_nghia': [
            'Vụ việc VẪN nằm trong danh sách, cột Trạng thái hiện chữ Khóa; vẫn xem chi tiết và xem lịch sử thay đổi được.',
            'Vụ việc đã khóa không còn chọn được khi lập chứng từ mới; các chứng từ cũ đang dùng vụ việc đó giữ nguyên.',
            'Nút Sửa và Xóa của dòng đó biến mất. Muốn sửa hoặc xóa, Người dùng phải Mở khóa trước.',
            'Khóa được cả vụ việc đã được sử dụng ở chứng từ — đây là cách ngừng dùng vụ việc không xóa được.',
        ],
        'buoc_khoa': [
            'Bước 1: Ở cột Hành động của vụ việc đang Hoạt động, Người dùng chọn Khóa (trong nút ba chấm {icon:btn_bacham} nếu dòng có nhiều nút).',
            'Bước 2: Hệ thống hiện hộp xác nhận “Khóa vụ việc” — “Bạn có chắc muốn khóa vụ việc "…"?”. Bấm Khóa để xác nhận; hệ thống báo “Khóa thành công”, cột Trạng thái đổi thành Khóa. Bấm Hủy nếu bấm nhầm.',
        ],
        'buoc_mo': [
            'Bước 1: Ở cột Hành động của vụ việc đang Khóa, Người dùng chọn Mở khóa.',
            'Bước 2: Bấm Mở khóa trong hộp xác nhận “Mở khóa vụ việc” — “Bạn có chắc muốn mở khóa vụ việc "…"?”. Hệ thống báo “Mở khóa thành công”, cột Trạng thái đổi thành Hoạt động, nút Sửa (và Xóa nếu vụ việc chưa được sử dụng) hiện lại. Bấm Hủy nếu bấm nhầm.',
        ],
        'ghi_chu': [
            'Có thể khóa ngay trong cửa sổ Sửa bằng cách chọn Trạng thái = Khóa rồi Lưu.',
            'Nếu vụ việc vừa bị người khác đổi trạng thái (hoặc vừa bị xóa), hệ thống báo “%s”.' % MSG_CONFLICT,
        ],
    },
    'xuat': {
        'buoc': [
            'Bước 1: Lọc danh sách theo đúng dữ liệu cần lấy (xem PHẦN 2). File xuất ra chạy theo đúng bộ lọc và thứ tự sắp xếp đang áp dụng.',
            'Bước 2: Bấm nút {icon:btn_xuatexcel}. Hệ thống mở cửa sổ “Chọn trường xuất file”.',
            'Bước 3: Tích chọn, kéo biểu tượng ☰ để đổi vị trí các trường cần xuất. Mặc định hệ thống tích sẵn đúng những cột đang hiển thị trên bảng.',
            'Bước 4: Bấm {icon:btn_xuatfile}. Hệ thống tải về file danh_muc_vu_viec.xlsx và báo “Xuất Excel thành công”.',
        ],
        'truong': 'Chọn nhiều trường: Mã vụ việc, Tên vụ việc, Ghi chú, Trạng thái, Người tạo, Ngày tạo, Người cập nhật, Ngày cập nhật.',
        'ghi_chu': ['Lưu ý: file xuất chứa TOÀN BỘ kết quả của bộ lọc (tối đa 10,000 dòng), không chỉ các dòng của trang đang xem.'],
    },
    'import': {
        'tieu_de': 'Import vụ việc',
        'file': 'Mau_import_vu_viec.xlsx',
        'cot_text': 'Mã vụ việc (bắt buộc), Tên vụ việc (bắt buộc), Ghi chú, Trạng thái (chọn Hoạt động / Khóa trong danh sách sổ xuống, bỏ trống = Hoạt động)',
        'toast': 'Import thành công N vụ việc.',
        'loi': [
            ['Mã vụ việc không được để trống', 'Dòng đó bỏ trống cột Mã vụ việc.'],
            ['Mã vụ việc tối đa 255 ký tự', 'Mã quá dài, rút gọn lại.'],
            ['Mã vụ việc: ' + MSG_MA, 'Mã có dấu cách, chữ có dấu hoặc ký tự đặc biệt.'],
            ['Mã vụ việc bị trùng với dòng N trong file', 'Trong chính file có hai dòng cùng mã (không phân biệt hoa/thường). Xoá bớt một dòng.'],
            ['Mã vụ việc đã tồn tại trong hệ thống', 'Danh mục đã có vụ việc trùng mã.'],
            ['Tên vụ việc không được để trống', 'Dòng đó bỏ trống cột Tên vụ việc.'],
            ['Tên vụ việc tối đa 255 ký tự', 'Tên quá dài, rút gọn lại.'],
            ['Ghi chú tối đa 255 ký tự', 'Ghi chú quá dài, rút gọn lại.'],
            ['Trạng thái chỉ nhận "Hoạt động" hoặc "Khóa"', 'Cột Trạng thái ghi giá trị khác hai giá trị trong danh sách sổ xuống.'],
        ],
        'ghi_chu': ['Lưu ý: mã vụ việc trong file được tự chuyển sang chữ IN HOA trước khi kiểm tra và ghi (gõ “vv001” sẽ lưu thành “VV001”). Trạng thái lấy theo cột Trạng thái (bỏ trống = Hoạt động); người tạo là chính người thực hiện nhập. Mỗi lần nhập tối đa 500 dòng; file dài hơn hệ thống báo “File có X dòng dữ liệu, vượt quá giới hạn 500 dòng mỗi lần import. Vui lòng tách file và import nhiều lần.”'],
    },
    'tuy_chinh_cot': {'cot_khoa': 'Ba cột STT, Mã vụ việc và Hành động'},

    'shots': {'list': '01_list.png', 'rowmenu': '03_rowmenu.png', 'filter': 'filter.png', 'filter_result': '04_filter_result.png',
              'create': '10_create.png', 'create_error': '11_create_error.png', 'code_error': '11b_code_error.png',
              'edit': '12_edit.png', 'delete': '13_delete.png', 'lock': '14_lock.png', 'unlock': '15_unlock.png', 'history': '16_history.png',
              'detail': '17_detail.png', 'export': '20_export.png', 'import_open': '21_import_open.png',
              'import_loaded': '22_import_loaded.png', 'import_validated': '23_import_validated.png', 'colcfg': '25_colcfg.png'},

    'import_test': {
        'cols': ['STT', 'Mã vụ việc *', 'Tên vụ việc *', 'Ghi chú', 'Trạng thái'],
        'rows': [
            [1, 'DOC-VV01', 'DOC-Vụ việc kiểm thử 1', '', 'Hoạt động'],
            [2, 'doc-vv02', 'DOC-Vụ việc kiểm thử 2 (mã chữ thường)', 'Ghi chú mẫu', 'Khóa'],
            [3, '', 'DOC-Thiếu mã', '', 'Hoạt động'],
            [4, 'DOC-VV01', 'DOC-Trùng mã trong file', '', ''],
            [5, 'TACHHANG', 'DOC-Trùng mã hệ thống', '', ''],
            [6, 'DOC VV 06', 'DOC-Mã sai định dạng', '', ''],
            [7, 'DOC-VV07', '', '', ''],
            [8, 'DOC-VV08', 'DOC-Trạng thái sai', '', 'Tạm dừng'],
        ],
    },

    'uml': {
        'mains': [('FR-01', 'Xem danh sách vụ việc', 'view'), ('FR-03', 'Thêm mới vụ việc', 'crud'),
                  ('FR-04', 'Chỉnh sửa vụ việc', 'crud'), ('FR-05', 'Xóa vụ việc', 'action'),
                  ('FR-06', 'Khóa / Mở khóa vụ việc', 'action'),
                  ('FR-08', 'Import file vụ việc', 'io'), ('FR-09', 'Xuất danh sách vụ việc ra Excel', 'io')],
        'subs': [('FR-02', 'Tìm kiếm và lọc vụ việc', 'view'), ('FR-10', 'Xem chi tiết vụ việc', 'view'),
                 ('FR-11', 'Tùy chỉnh cột hiển thị', 'view'), ('FR-07', 'Xem lịch sử thay đổi', 'view')],
        'rieng': [('FR-10', 'Xem chi tiết vụ việc', 'view')],
    },

    'srs': {
        'muc_dich': ['Là căn cứ nghiệm thu chức năng và phân quyền.',
                     'Làm rõ quy tắc nhập Mã vụ việc (người dùng tự đặt, chỉ gồm chữ không dấu, số, dấu - và _, duy nhất toàn hệ thống).',
                     'Làm rõ điều kiện được phép xóa (xóa hẳn, chỉ khi đang Hoạt động và chưa được sử dụng) và quy tắc Khóa / Mở khóa (khóa được cả khi đã được sử dụng; vụ việc đang Khóa không sửa, không xóa được).'],
        'quyen_truoc': ['Màn hình chỉ có MỘT quyền duy nhất, không tách riêng quyền xem và quyền sửa. Người không có quyền này không vào được màn hình.'],
        'quyen_rows': [[QUYEN, 'Thấy mục menu, mở màn hình và thực hiện đầy đủ Thêm mới, Chỉnh sửa, Xóa, Khóa, Mở khóa, Xem lịch sử, Xem chi tiết, Import Excel, Xuất Excel. Thiếu quyền này thì mục menu không hiển thị và máy chủ từ chối mọi thao tác.']],
        'ma_tran': [['Chức năng', QUYEN, 'Không có quyền']] + [[f, '✅', '❌'] for f in [
            'FR-01 Xem danh sách vụ việc', 'FR-02 Tìm kiếm và lọc', 'FR-03 Thêm mới vụ việc', 'FR-04 Chỉnh sửa vụ việc',
            'FR-05 Xóa vụ việc', 'FR-06 Khóa / Mở khóa vụ việc', 'FR-07 Xem lịch sử thay đổi', 'FR-08 Import file vụ việc',
            'FR-09 Xuất danh sách ra Excel', 'FR-10 Xem chi tiết vụ việc', 'FR-11 Tùy chỉnh cột hiển thị']],
        'ma_tran_widths': [2.4, 1.6, 1.2],
        'fr': [
            {'ten': 'Xem danh sách vụ việc',
             'qtc': 'Màn Danh sách, Sắp xếp dữ liệu bảng, Phân trang và Cấu hình cột. Chỉ bổ sung các quy tắc riêng của Danh mục vụ việc tại phần mô tả chi tiết.',
             'gioi_thieu': [['Tên chức năng', 'Xem danh sách vụ việc'],
                            ['Mô tả', 'Hiển thị toàn bộ vụ việc trong danh mục (cả Hoạt động lẫn Khóa), có phân trang và sắp xếp.'],
                            ['Tác nhân', 'Người dùng có quyền “%s”' % QUYEN],
                            ['Điều kiện ban đầu', 'Người dùng đã đăng nhập và có quyền “%s”.' % QUYEN],
                            ['Dòng sự kiện chính', '1. Người dùng vào menu Tài chính → Danh mục → Danh mục vụ việc.\n2. Hệ thống nạp trang đầu tiên của danh sách (10 dòng, mới tạo trước).\n3. Bảng hiển thị dữ liệu kèm tổng số bản ghi.'],
                            ['Dòng sự kiện phụ', '• Không có bản ghi khớp → bảng hiện “Không có dữ liệu phù hợp bộ lọc.”\n• Không có quyền → mục menu không hiển thị, máy chủ từ chối truy cập.']],
             'anh': [('list', 'Màn Danh mục vụ việc lúc mới truy cập')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Mô tả'],
                    ['1', 'STT', 'Table/Grid', 'Read-only', 'Số thứ tự, chạy liên tục qua các trang. Luôn hiển thị, không ẩn được.'],
                    ['2', 'Mã vụ việc', 'Table/Grid', 'Read-only', 'Luôn hiển thị, sắp xếp được. Bấm vào mã mở cửa sổ Xem (xem 2.10).'],
                    ['3', 'Tên vụ việc', 'Table/Grid', 'Read-only', 'Sắp xếp được.'],
                    ['4', 'Ghi chú', 'Table/Grid', 'Read-only', 'Mặc định ẩn.'],
                    ['5', 'Người cập nhật', 'Table/Grid', 'Read-only', 'Mặc định ẩn.'],
                    ['6', 'Ngày cập nhật', 'Table/Grid', 'Read-only', 'dd/mm/yyyy hh:mm. Mặc định ẩn, sắp xếp được.'],
                    ['7', 'Người tạo', 'Table/Grid', 'Read-only', 'Người đã thêm bản ghi.'],
                    ['8', 'Ngày tạo', 'Table/Grid', 'Read-only', 'dd/mm/yyyy hh:mm, sắp xếp được.'],
                    ['9', 'Trạng thái', 'Badge', 'Read-only', 'Hoạt động hoặc Khóa.'],
                    ['10', 'Hành động', 'Table/Grid', 'Read-only', 'Sửa (khi Hoạt động), Xóa (khi Hoạt động và chưa được sử dụng), Khóa / Mở khóa, Lịch sử. Từ 4 nút trở lên thì 2 nút đầu hiện thẳng, còn lại trong nút ba chấm.'],
                    ['11', 'Nút Tạo mới', 'Button', 'Enable', 'Mở cửa sổ Tạo vụ việc.'],
                    ['12', 'Nút Xuất Excel', 'Button', 'Enable', 'Mở cửa sổ Chọn trường xuất file (xem 2.9).'],
                    ['13', 'Nút Import Excel', 'Button', 'Enable', 'Mở cửa sổ Import vụ việc (xem 2.8).'],
                    ['14', 'Biểu tượng Cấu hình cột hiển thị', 'Icon Button', 'Enable', 'Mở cửa sổ Tuỳ chỉnh cột (xem 2.11).'],
                    ['15', 'Phân trang', 'Pagination', 'Enable', 'Số dòng/trang 5 / 10 / 20 / 50 / 100, mặc định 10.']],
             'ui_widths': [0.6, 1.4, 0.9, 0.8, 3],
             'events': [['Mở màn hình', 'System', 'After:\n– Nạp trang đầu, hiển thị tổng số bản ghi.'],
                        ['Bấm tiêu đề cột sắp xếp được', 'Click', 'After:\n– Đổi chiều sắp xếp và nạp lại danh sách từ trang 1.'],
                        ['Chuyển trang', 'Click', 'Before:\n– Giữ nguyên bộ lọc và thứ tự sắp xếp.\nAfter:\n– Nạp dữ liệu trang mới, số thứ tự tiếp tục liên tục.'],
                        ['Đổi số dòng mỗi trang', 'Change', 'After:\n– Quay về trang 1 và nạp lại theo số dòng mới.']]},
            {'ten': 'Tìm kiếm và lọc',
             'qtc': 'Kịch bản tìm kiếm, Bộ lọc, Dropdown, Phân trang. Chỉ bổ sung các tiêu chí tìm kiếm/lọc riêng của Danh mục vụ việc.',
             'gioi_thieu': [['Tên chức năng', 'Tìm kiếm và lọc danh sách'],
                            ['Mô tả', 'Thu hẹp danh sách bằng ô tìm kiếm nhanh và khối Tìm kiếm nâng cao (Trạng thái, Người tạo, Người cập nhật).'],
                            ['Tác nhân', 'Người dùng có quyền “%s”' % QUYEN],
                            ['Điều kiện ban đầu', 'Đang ở màn Danh mục vụ việc.'],
                            ['Dòng sự kiện chính', '1. Người dùng nhập từ khóa và bấm Tìm kiếm / Enter, hoặc mở Tìm kiếm nâng cao và chọn Trạng thái / Người tạo / Người cập nhật (lọc ngay).\n2. Hệ thống áp đồng thời mọi tiêu chí và nạp lại danh sách từ trang 1.'],
                            ['Dòng sự kiện phụ', '• Không có kết quả → bảng hiện “Không có dữ liệu phù hợp bộ lọc.”\n• Bấm Làm mới → xóa hết tiêu chí VÀ nạp lại danh sách đầy đủ ngay.']],
             'anh': [('filter', 'Khu vực tìm kiếm và lọc của màn Danh mục vụ việc')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Phạm vi', 'Mô tả'],
                    ['1', 'Ô tìm kiếm nhanh', 'Textbox', 'Enable', '0–255 ký tự', 'Placeholder “Tìm theo mã, tên vụ việc”. Tìm theo MÃ hoặc TÊN (khớp một phần).'],
                    ['2', 'Nút Tìm kiếm nâng cao', 'Button', 'Enable', '–', 'Mở / thu gọn khối ô lọc.'],
                    ['3', 'Trạng thái', 'Dropdown', 'Enable', 'Hoạt động / Khóa', 'Nhãn nổi. Bỏ trống thì hiện cả hai trạng thái.'],
                    ['4', 'Người tạo', 'Dropdown', 'Enable', 'Danh sách nhân viên', 'Nhãn nổi. Lọc theo người đã tạo bản ghi.'],
                    ['5', 'Người cập nhật', 'Dropdown', 'Enable', 'Danh sách nhân viên', 'Nhãn nổi. Lọc theo người sửa gần nhất.'],
                    ['6', 'Nút Tìm kiếm', 'Button', 'Enable', '–', 'Áp dụng các tiêu chí.'],
                    ['7', 'Nút Làm mới', 'Button', 'Enable', '–', 'Xóa hết tiêu chí VÀ nạp lại danh sách ngay.']],
             'ui_widths': [0.6, 1.2, 0.8, 0.7, 1.1, 2.6],
             'events': [['Bấm Tìm kiếm / Enter', 'Click', 'After:\n– Áp đồng thời các tiêu chí theo kiểu “và”, nạp lại bảng từ trang 1.'],
                        ['Chọn Trạng thái / Người tạo / Người cập nhật', 'Change', 'After:\n– Lọc ngay, nạp lại bảng từ trang 1.'],
                        ['Bấm Làm mới', 'Click', 'After:\n– Xóa trắng mọi tiêu chí VÀ nạp lại danh sách đầy đủ.']]},
            {'ten': 'Thêm mới vụ việc', 'uc': 'uc_fr03',
             'qtc': 'Màn Thêm mới, Validate dữ liệu, Thông báo và UI/UX. Logic ghi lịch sử áp dụng theo SRS Các quy tắc chung - Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Thêm mới vụ việc'],
                            ['Mô tả', 'Thêm một vụ việc mới thông qua cửa sổ nhập liệu. Mã vụ việc do người dùng tự nhập.'],
                            ['Tác nhân', 'Người dùng có quyền “%s”' % QUYEN],
                            ['Điều kiện ban đầu', 'Đang ở màn Danh mục vụ việc.'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm Tạo mới.\n2. Hệ thống mở cửa sổ “Tạo vụ việc”, Trạng thái mặc định Hoạt động.\n3. Người dùng nhập Mã vụ việc, Tên vụ việc (tùy chọn Trạng thái, Ghi chú) và bấm Lưu.\n4. Hệ thống kiểm tra dữ liệu, ghi bản ghi mới và ghi lịch sử Tạo mới.\n5. Cửa sổ đóng, danh sách nạp lại, báo “Thêm mới thành công”.'],
                            ['Dòng sự kiện phụ', '• Mã có ký tự không hợp lệ → báo ngay khi gõ “%s”.\n• Thiếu trường bắt buộc hoặc trùng mã → báo lỗi đỏ dưới ô + toast “Vui lòng kiểm tra lại dữ liệu nhập”, cửa sổ KHÔNG đóng.\n• Bấm “Lưu và tiếp tục” → ghi bản ghi rồi giữ cửa sổ mở với các ô trống.\n• Bấm Đóng khi đã nhập dở → hỏi “Thông tin chưa lưu” (Thoát / Ở lại).' % MSG_MA],
                            ['Yêu cầu đặc biệt', 'Cửa sổ có ba nút: Lưu, Lưu và tiếp tục, Đóng. Mã không tự sinh.']],
             'menu_them': ' => Tạo mới {icon:btn_taomoi}',
             'ghi_chu_layout': 'Cửa sổ Tạo vụ việc được mở ngay trên màn hình danh sách.',
             'anh': [('create', 'Cửa sổ Tạo vụ việc'), ('create_error', 'Lỗi đỏ ngay dưới ô còn thiếu'),
                     ('code_error', 'Lỗi định dạng Mã vụ việc hiện ngay khi gõ')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Phạm vi', 'Bắt buộc', 'Mô tả'],
                    ['1', 'Mã vụ việc', 'Textbox', 'Enable', 'Chữ không dấu, số, - và _', 'Có', 'Placeholder “VD: VV001”. Người dùng tự nhập. Duy nhất toàn hệ thống, không phân biệt hoa/thường. Sai ký tự “%s” (báo ngay khi gõ); bỏ trống “Bắt buộc phải nhập”; trùng “Mã vụ việc đã tồn tại”.' % MSG_MA],
                    ['2', 'Tên vụ việc', 'Textbox', 'Enable', 'Chuỗi ký tự', 'Có', 'Không bắt buộc duy nhất. Bỏ trống “Bắt buộc phải nhập”.'],
                    ['3', 'Trạng thái', 'Dropdown', 'Enable', 'Hoạt động / Khóa', 'Không', 'Mặc định Hoạt động.'],
                    ['4', 'Ghi chú', 'Textarea', 'Enable', 'Chuỗi ký tự', 'Không', 'Ô 3 dòng.'],
                    ['5', 'Nút Lưu', 'Button', 'Enable', '', '', 'Ghi bản ghi rồi đóng cửa sổ.'],
                    ['6', 'Nút Lưu và tiếp tục', 'Button', 'Enable', '', '', 'Ghi bản ghi rồi giữ cửa sổ mở để nhập tiếp.'],
                    ['7', 'Nút Đóng', 'Button', 'Enable', '', '', 'Hủy bỏ, không ghi gì.']],
             'ui_widths': [0.6, 1.3, 0.8, 0.6, 1.1, 0.5, 2.3],
             'events': [['Bấm nút Tạo mới', 'Click', 'After:\n– Mở cửa sổ nhập liệu với các ô trống, Trạng thái = Hoạt động.'],
                        ['Gõ Mã vụ việc', 'Change', 'After:\n– Có ký tự ngoài chữ không dấu, số, - và _ → báo đỏ ngay dưới ô.'],
                        ['Bấm Lưu', 'Click', 'During:\n– Kiểm tra bắt buộc, định dạng mã, trùng mã toàn hệ thống (không phân biệt hoa/thường).\n– Có lỗi → báo đỏ dưới ô, không thực hiện After.\nAfter:\n– Ghi bản ghi mới (mã lưu đúng như người dùng gõ), ghi lịch sử Tạo mới.\n– Đóng cửa sổ, nạp lại danh sách, báo “Thêm mới thành công”.'],
                        ['Bấm Lưu và tiếp tục', 'Click', 'During:\n– Như nút Lưu.\nAfter:\n– Ghi bản ghi, xóa trắng các ô, GIỮ cửa sổ mở.'],
                        ['Bấm Đóng', 'Click', 'After:\n– Chưa nhập gì → đóng cửa sổ. Đã nhập → hỏi “Thông tin chưa lưu”.']]},
            {'ten': 'Chỉnh sửa vụ việc', 'uc': 'uc_fr04',
             'qtc': 'Validate dữ liệu, Thông báo, Quy định chung về danh mục và Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Chỉnh sửa vụ việc'],
                            ['Mô tả', 'Sửa thông tin một vụ việc đang Hoạt động (có thể chuyển Trạng thái sang Khóa ngay trong cửa sổ). Dùng chung cửa sổ với Thêm mới.'],
                            ['Tác nhân', 'Người dùng có quyền “%s”' % QUYEN],
                            ['Điều kiện ban đầu', 'Vụ việc đang ở trạng thái Hoạt động.'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm biểu tượng bút chì ở dòng cần sửa.\n2. Hệ thống mở cửa sổ “Sửa vụ việc” với dữ liệu hiện tại.\n3. Người dùng sửa và bấm Lưu.\n4. Hệ thống kiểm tra, ghi thay đổi và ghi lịch sử.\n5. Cửa sổ đóng, báo “Cập nhật thành công”.'],
                            ['Dòng sự kiện phụ', '• Giữ nguyên mã của chính bản ghi → không báo trùng.\n• Trùng mã với vụ việc khác → báo “Mã vụ việc đã tồn tại”.\n• Chọn Trạng thái = Khóa → lưu bình thường, kể cả khi vụ việc đã được sử dụng.\n• Vụ việc vừa bị người khác khóa → báo “%s”' % MSG_LOCKED]],
             'menu_them': ' => Sửa {icon:btn_sua}',
             'anh': [('edit', 'Cửa sổ Sửa vụ việc')],
             'events': [['Bấm biểu tượng bút chì', 'Click', 'Before:\n– Vụ việc đã Khóa thì nút không hiển thị.\nAfter:\n– Mở cửa sổ với dữ liệu hiện tại.'],
                        ['Bấm Lưu', 'Click', 'Before:\n– Vụ việc đang Khóa → máy chủ từ chối, báo “%s”\nDuring:\n– Kiểm tra như Thêm mới, bỏ qua trùng với chính bản ghi.\nAfter:' % MSG_LOCKED + '\n– Ghi thay đổi, ghi lịch sử “Thay đổi thông tin” (đổi Trạng thái ghi mốc Khóa / Mở khóa riêng), báo “Cập nhật thành công”.']]},
            {'ten': 'Xóa vụ việc', 'uc': 'uc_fr05',
             'qtc': 'Quy tắc Xóa, Thông báo, Quy định chung về danh mục và Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Xóa vụ việc'],
                            ['Mô tả', 'Xóa hẳn một vụ việc đang Hoạt động và chưa được sử dụng ở chứng từ nào.'],
                            ['Tác nhân', 'Người dùng có quyền “%s”' % QUYEN],
                            ['Điều kiện ban đầu', 'Vụ việc đang Hoạt động và chưa được chọn ở chứng từ nào (' + USED_W + ').'],
                            ['Dòng sự kiện chính', '1. Người dùng bấm biểu tượng thùng rác.\n2. Hệ thống hiện hộp “Xóa vụ việc” nêu rõ tên bản ghi.\n3. Người dùng bấm Xóa.\n4. Hệ thống xóa hẳn bản ghi, ghi lịch sử, báo “Đã xóa thành công”, nạp lại danh sách.'],
                            ['Dòng sự kiện phụ', '• Bấm Hủy → đóng hộp, không thay đổi.\n• Vụ việc đã được sử dụng hoặc đang Khóa → nút Xóa KHÔNG hiển thị.\n• Vụ việc vừa được sử dụng trong lúc đang mở màn hình → báo “%s”\n• Vụ việc vừa bị người khác khóa → báo “%s”\n• Vụ việc vừa bị người khác xóa → báo “%s”.' % (MSG_USED, MSG_LOCKED, MSG_CONFLICT)]],
             'menu_them': ' => Xóa {icon:btn_xoa}',
             'anh': [('delete', 'Hộp xác nhận xóa vụ việc')],
             'events': [['Bấm biểu tượng thùng rác', 'Click', 'Before:\n– Chỉ hiển thị khi vụ việc đang Hoạt động và chưa được sử dụng.\nAfter:\n– Hiện hộp xác nhận kèm tên bản ghi.'],
                        ['Bấm Xóa', 'Click', 'During:\n– Kiểm tra lại: bản ghi còn tồn tại, đang Hoạt động, chưa được sử dụng.\nAfter:\n– Xóa hẳn bản ghi, ghi lịch sử, nạp lại danh sách, báo thành công.'],
                        ['Bấm Hủy', 'Click', 'After:\n– Đóng hộp, không thay đổi.']]},
            {'ten': 'Khóa / Mở khóa vụ việc', 'uc': 'uc_fr06',
             'qtc': 'Quy tắc Khóa/Mở khóa, Thông báo, Quy định chung về danh mục và Quy tắc ghi lịch sử.',
             'gioi_thieu': [['Tên chức năng', 'Khóa / Mở khóa vụ việc'],
                            ['Mô tả', 'Đổi trạng thái vụ việc giữa Hoạt động và Khóa. Vụ việc đã Khóa vẫn nằm trong danh mục nhưng không chọn được ở chứng từ mới, không sửa và không xóa được.'],
                            ['Tác nhân', 'Người dùng có quyền “%s”' % QUYEN],
                            ['Điều kiện ban đầu', 'Vụ việc cần đổi trạng thái đang có trong danh sách. Khóa được cả vụ việc đã được sử dụng.'],
                            ['Dòng sự kiện chính', '1. Người dùng chọn Khóa (hoặc Mở khóa) ở cột Hành động.\n2. Hệ thống hiện hộp xác nhận “Khóa vụ việc” / “Mở khóa vụ việc” nêu rõ tên bản ghi.\n3. Người dùng xác nhận.\n4. Hệ thống đổi trạng thái, ghi lịch sử, báo “Khóa thành công” / “Mở khóa thành công”.'],
                            ['Dòng sự kiện phụ', '• Bấm Hủy → không thay đổi.\n• Sau khi Khóa, nút Sửa và Xóa biến mất, chỉ còn Mở khóa và Lịch sử.\n• Vụ việc đã bị người khác đổi trạng thái hoặc xóa → báo “%s”.' % MSG_CONFLICT]],
             'menu_them': ' => Khóa / Mở khóa',
             'anh': [('lock', 'Hộp xác nhận khóa vụ việc'), ('unlock', 'Hộp xác nhận mở khóa vụ việc'), ('rowmenu', 'Các nút ở cột Hành động')],
             'events': [['Chọn Khóa / Mở khóa', 'Click', 'After:\n– Hiện hộp xác nhận kèm tên bản ghi.'],
                        ['Xác nhận', 'Click', 'During:\n– Bản ghi đã ở trạng thái đích hoặc không còn tồn tại → báo trạng thái đã thay đổi, dừng.\nAfter:\n– Đổi trạng thái, KHÔNG xóa dữ liệu, ghi lịch sử, cập nhật cột Trạng thái và các nút.'],
                        ['Bấm Hủy', 'Click', 'After:\n– Đóng hộp, không thay đổi.']]},
            {'ten': 'Xem lịch sử thay đổi',
             'qtc': 'Quy tắc ghi lịch sử và hiển thị lịch sử. Chỉ bổ sung thông tin riêng của Danh mục vụ việc nếu có.',
             'gioi_thieu': [['Tên chức năng', 'Xem lịch sử thay đổi'],
                            ['Mô tả', 'Liệt kê các lần thay đổi của một vụ việc, kèm giá trị cũ → mới, người thực hiện và thời điểm.'],
                            ['Tác nhân', 'Người dùng có quyền “%s”' % QUYEN],
                            ['Dòng sự kiện chính', '1. Người dùng bấm Lịch sử ở cột Hành động, hoặc mở cửa sổ Xem vụ việc.\n2. Hệ thống mở cửa sổ “Lịch sử thay đổi: <mã> - <tên>”, mốc mới nhất ở trên cùng.'],
                            ['Dòng sự kiện phụ', '• Bản ghi chưa có thao tác nào → “Chưa có lịch sử thao tác nào.”\n• Có bộ lọc theo loại hành động, người thực hiện, thời gian.']],
             'menu_them': ' => Lịch sử',
             'anh': [('history', 'Cửa sổ Lịch sử thay đổi của vụ việc')]},
            {'ten': 'Import file vụ việc', 'uc': 'uc_fr08',
             'qtc': 'Quy tắc Import file, Validate dữ liệu, Thông báo và Quy định chung về danh mục. Chỉ bổ sung mapping/validation riêng của Danh mục vụ việc.',
             'gioi_thieu': [['Tên chức năng', 'Import file vụ việc'],
                            ['Mô tả', 'Thêm nhiều vụ việc cùng lúc từ file Excel mẫu, có bước Validate trước khi ghi.'],
                            ['Tác nhân', 'Người dùng có quyền “%s”' % QUYEN],
                            ['Điều kiện ban đầu', 'Đang ở màn Danh mục vụ việc và đã chuẩn bị file theo mẫu.'],
                            ['Dòng sự kiện chính', '1. Bấm Import Excel.\n2. Bấm Tải file mẫu (Mau_import_vu_viec.xlsx), điền dữ liệu.\n3. Bấm Chọn file Excel rồi Load lên bảng.\n4. Bấm Validate; hệ thống kiểm tra từng dòng như quy tắc Thêm mới (mục 2.3), khóa dòng hợp lệ.\n5. Sửa dòng lỗi rồi Validate lại, hoặc bấm Bỏ dòng lỗi.\n6. Bấm Import; hệ thống ghi các dòng hợp lệ, báo “Import thành công N vụ việc.”, đóng cửa sổ và nạp lại danh sách.'],
                            ['Dòng sự kiện phụ', '• File không phải .xlsx/.xls → “Vui lòng chọn file .xlsx hoặc .xls”.\n• Quá 500 dòng → “File có X dòng dữ liệu, vượt quá giới hạn 500 dòng mỗi lần import. Vui lòng tách file và import nhiều lần.”\n• Còn dòng lỗi → nút Import không bấm được.'],
                            ['Yêu cầu đặc biệt', 'Validate không ghi dữ liệu. Mã trong file được chuyển sang chữ IN HOA. Trạng thái lấy theo cột Trạng thái (bỏ trống = Hoạt động); người tạo là người thực hiện.']],
             'menu_them': ' => Import Excel {icon:btn_import}',
             'ghi_chu_layout': 'Cửa sổ Import được mở ngay trên màn hình danh sách.',
             'anh': [('import_open', 'Cửa sổ Import vụ việc khi vừa mở'), ('import_loaded', 'Dữ liệu đã được load lên bảng xem trước'),
                     ('import_validated', 'Kết quả Validate — mỗi dòng lỗi nêu rõ lý do')],
             'bang_them': [('Quy tắc kiểm tra riêng của file Import', [['Cột', 'Quy tắc / thông báo lỗi'],
                            ['Mã vụ việc *', 'Tự chuyển IN HOA. Bắt buộc (“Mã vụ việc không được để trống”), tối đa 255 ký tự (“Mã vụ việc tối đa 255 ký tự”), chỉ gồm chữ không dấu, số, - và _ (“Mã vụ việc: %s”), không trùng trong file (“Mã vụ việc bị trùng với dòng N trong file”), không trùng hệ thống (“Mã vụ việc đã tồn tại trong hệ thống”).' % MSG_MA],
                            ['Tên vụ việc *', 'Bắt buộc (“Tên vụ việc không được để trống”), tối đa 255 ký tự (“Tên vụ việc tối đa 255 ký tự”).'],
                            ['Ghi chú', 'Không bắt buộc, tối đa 255 ký tự (“Ghi chú tối đa 255 ký tự”).'],
                            ['Trạng thái', 'Chọn trong danh sách sổ xuống Hoạt động / Khóa; bỏ trống = Hoạt động; giá trị khác báo “Trạng thái chỉ nhận "Hoạt động" hoặc "Khóa"”.']], [1.2, 4])]},
            {'ten': 'Xuất danh sách ra Excel', 'uc': 'uc_fr09',
             'qtc': 'Quy tắc Excel và Cấu hình cột. Chỉ bổ sung danh sách trường được phép xuất riêng của Danh mục vụ việc.',
             'gioi_thieu': [['Tên chức năng', 'Xuất danh sách vụ việc ra Excel'],
                            ['Mô tả', 'Xuất kết quả đang lọc ra file Excel, cho phép chọn trường và thứ tự cột.'],
                            ['Tác nhân', 'Người dùng có quyền “%s”' % QUYEN],
                            ['Dòng sự kiện chính', '1. Bấm Xuất Excel.\n2. Hệ thống mở cửa sổ “Chọn trường xuất file”, tích sẵn đúng các cột đang hiển thị trên bảng.\n3. Người dùng tích chọn và kéo ☰ để sắp thứ tự.\n4. Bấm Xuất file; hệ thống tải danh_muc_vu_viec.xlsx theo đúng bộ lọc, thứ tự sắp xếp và thứ tự trường, báo “Xuất Excel thành công”.'],
                            ['Dòng sự kiện phụ', '• Bỏ chọn hết trường → nút Xuất file không bấm được.\n• Bấm Đóng → không xuất gì.\n• Lỗi khi xuất → báo “Lỗi khi xuất Excel”.'],
                            ['Yêu cầu đặc biệt', 'File chứa toàn bộ kết quả lọc (tối đa 10,000 dòng), không giới hạn ở trang đang xem. Chỉ xuất Excel.']],
             'menu_them': ' => Xuất Excel {icon:btn_xuatexcel}',
             'anh': [('export', 'Cửa sổ Chọn trường xuất file')],
             'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
                    ['1', 'Danh sách trường', 'Checkbox chọn nhiều', 'Enable', 'Tích sẵn cột đang hiển thị', 'Mã vụ việc, Tên vụ việc, Ghi chú, Trạng thái, Người tạo, Ngày tạo, Người cập nhật, Ngày cập nhật. Kéo ☰ đổi thứ tự.'],
                    ['2', 'Nút Chọn tất cả / Bỏ chọn hết', 'Button', 'Enable', 'Hiển thị', 'Tích / bỏ tích toàn bộ.'],
                    ['3', 'Nút Xuất file', 'Button', 'Enable/Disable', 'Mờ khi chưa chọn trường', 'Sinh file và tải về.'],
                    ['4', 'Nút Đóng', 'Button', 'Enable', 'Hiển thị', 'Đóng cửa sổ.']],
             'ui_widths': [0.6, 1.5, 1, 0.8, 1.2, 2.6]},
            {'ten': 'Xem chi tiết vụ việc', 'uc': 'uc_fr10',
             'qtc': 'Màn Xem chi tiết và Phân quyền.',
             'gioi_thieu': [['Tên chức năng', 'Xem chi tiết vụ việc'],
                            ['Mô tả', 'Cửa sổ “Xem vụ việc” hiển thị Mã vụ việc, Tên vụ việc, Trạng thái, Ghi chú ở chế độ chỉ đọc, kèm khối Lịch sử.'],
                            ['Tác nhân', 'Người dùng có quyền “%s”' % QUYEN],
                            ['Dòng sự kiện chính', '1. Người dùng bấm mã vụ việc ở danh sách.\n2. Hệ thống mở cửa sổ Xem, chỉ có nút Đóng.']],
             'anh': [('detail', 'Cửa sổ Xem vụ việc ở chế độ chỉ đọc')]},
            {'ten': 'Tùy chỉnh cột hiển thị',
             'qtc': 'Tùy chỉnh cột.',
             'gioi_thieu': [['Tên chức năng', 'Tùy chỉnh cột hiển thị'],
                            ['Mô tả', 'Bật/tắt và sắp xếp thứ tự cột của bảng; cấu hình lưu riêng theo người dùng.'],
                            ['Yêu cầu đặc biệt', 'Cột STT, Mã vụ việc, Hành động bị khóa. Mặc định ẩn: Ghi chú, Người cập nhật, Ngày cập nhật.']],
             'menu_them': ' => Cấu hình cột {icon:btn_cauhinhcot}',
             'anh': [('colcfg', 'Cửa sổ Tuỳ chỉnh cột')]},
        ],
        'quy_tac': [
            ('BR-01', 'Một quyền cho cả màn hình',
             ['Màn hình chỉ dùng một quyền “%s” cho cả xem và thao tác.' % QUYEN,
              'Không có quyền thì không thấy menu và máy chủ từ chối truy cập.'],
             ['Tất cả chức năng của màn hình']),
            ('BR-02', 'Ràng buộc mã vụ việc',
             ['Mã vụ việc do người dùng tự nhập, hệ thống không tự sinh.',
              'Mã chỉ gồm chữ không dấu, số, dấu - và _. Thông báo khi sai: “Chỉ gồm chữ không dấu, số, dấu - và _”.',
              'Mã không được trùng trên toàn hệ thống, không phân biệt chữ hoa/chữ thường; khi sửa, bỏ qua chính bản ghi đang sửa. Thông báo khi trùng: “Mã vụ việc đã tồn tại”.',
              'Form lưu nguyên chữ người dùng gõ; Import tự chuyển mã sang CHỮ IN HOA.',
              'Tên vụ việc được phép trùng.'],
             ['Thêm mới vụ việc', 'Chỉnh sửa vụ việc', 'Import file vụ việc']),
            ('BR-03', 'Điều kiện xóa vụ việc',
             ['Chỉ xóa được vụ việc đang Hoạt động VÀ chưa được sử dụng; ngược lại nút Xóa bị ẩn.',
              'Vụ việc được coi là đã sử dụng khi đã được chọn ở ít nhất một trong các chứng từ: ' + USED_W + '.',
              'Máy chủ kiểm tra lại khi xóa: đã được sử dụng → “%s”; đang Khóa → “%s”.' % (MSG_USED, MSG_LOCKED),
              'Xóa là xóa hẳn bản ghi khỏi danh mục. Vụ việc đã được sử dụng thì dùng Khóa thay cho Xóa.'],
             ['Xóa vụ việc']),
            ('BR-04', 'Khóa / Mở khóa và vụ việc đang Khóa',
             ['Vụ việc mới mặc định Hoạt động.',
              'Khóa / Mở khóa bằng nút ở cột Hành động, hoặc đổi ô Trạng thái trong cửa sổ Sửa.',
              'Khóa được cả vụ việc đã được sử dụng ở chứng từ; chứng từ cũ giữ nguyên, vụ việc không còn chọn được ở chứng từ mới.',
              'Vụ việc đang Khóa không sửa, không xóa được (nút Sửa, Xóa bị ẩn); máy chủ chặn với thông báo “%s” Muốn sửa phải Mở khóa trước.' % MSG_LOCKED],
             ['Thêm mới vụ việc', 'Chỉnh sửa vụ việc', 'Xóa vụ việc', 'Khóa / Mở khóa vụ việc']),
            ('BR-05', 'Vụ việc dùng cho hạch toán tự động',
             ['Một số nghiệp vụ tra vụ việc theo mã cố định, VD mã “TTHHD” (Thưởng thực hiện hợp đồng) ở Đề nghị thanh toán, Phiếu chi và Phiếu ủy nhiệm chi.',
              'Màn hình không chặn đổi mã, cũng không chặn Khóa các vụ việc này; đổi mã hoặc khóa có thể làm các bút toán tự động không tìm thấy / không dùng được vụ việc tương ứng.'],
             ['Chỉnh sửa vụ việc', 'Khóa / Mở khóa vụ việc', 'Đề nghị thanh toán', 'Phiếu chi', 'Phiếu ủy nhiệm chi']),
            ('BR-06', 'Giới hạn Import',
             ['Mỗi lần nhập tối đa 500 dòng.',
              'Bước Validate chỉ kiểm tra, không ghi dữ liệu; báo trùng mã trong cùng file và trùng mã với hệ thống.',
              'Trạng thái lấy theo cột Trạng thái, chỉ nhận “Hoạt động” hoặc “Khóa”; bỏ trống = Hoạt động.'],
             ['Import file vụ việc']),
            ('BR-07', 'Ghi lịch sử thay đổi',
             ['Mọi thao tác Tạo mới, Thay đổi thông tin, Khóa, Mở khóa, Xóa đều ghi lịch sử kèm người thực hiện.',
              'Lịch sử sắp xếp mới nhất ở trên cùng.'],
             ['Thêm mới vụ việc', 'Chỉnh sửa vụ việc', 'Xóa vụ việc', 'Khóa / Mở khóa vụ việc', 'Import file vụ việc', 'Xem lịch sử thay đổi']),
        ],
    },
}

# ---- Sửa tab testcase "19. DM vụ việc " — KẾ HOẠCH 28/09/2026 (đọc từ ref/testcase_tab.txt dump 28/09)
# Lượt 25/09 (quy tắc mã, Xuất Excel, Import) ĐÃ chạy lên sheet — không lặp lại.
MSG_OK_DEL = 'Đã xóa thành công'
USED_NGAN = 'bút toán kế toán, phiếu điều chỉnh công nợ, phiếu nhập/xuất kho, đề nghị thanh toán, phiếu chi, đề nghị tạm ứng…'
CFG['tc'] = {
    'tab': '19. DM vụ việc ',
    'hdr_row': 81,            # "VI. LỊCH SỬ THAY ĐỔI"
    'blocks': [
        # Case mới về Khóa trong cửa sổ Sửa / 423 — cuối nhóm IV. CHỈNH SỬA (R62..R73)
        {'after': 73, 'merge_from': 62, 'cases': [
            ('TC_04.013', 'Chuyển Trạng thái sang Khóa trong cửa sổ Sửa, kể cả vụ việc đã được sử dụng', 'P0',
             'Vụ việc Y đang Hoạt động và đã được chọn ở ít nhất một bút toán kế toán.',
             '1. Mở cửa sổ sửa Y\n2. Chọn Trạng thái = Khóa\n3. Bấm Lưu', 'Trạng thái: Khóa',
             '- Ô Trạng thái chọn được bình thường (không bị khóa lại)\n- Lưu thành công, báo "Cập nhật thành công"\n- Cột Trạng thái của Y đổi thành Khóa, dòng Y chỉ còn Mở khóa và Lịch sử'),
            ('TC_04.014', 'Bấm Lưu khi vụ việc vừa bị người khác khóa', 'P1',
             'Tài khoản A và B cùng có quyền; vụ việc X đang Hoạt động.',
             '1. A mở cửa sổ sửa X, đổi Tên vụ việc\n2. B khóa X ở cột Hành động\n3. A bấm Lưu', '',
             '- A nhận thông báo "%s"\n- Thay đổi của A KHÔNG được ghi, X vẫn ở trạng thái Khóa' % MSG_LOCKED),
        ]},
        # Case mới về điều kiện xóa — cuối nhóm V. XÓA (R75..R80)
        {'after': 80, 'merge_from': 75, 'cases': [
            ('TC_05.007', 'Xóa vụ việc vừa được sử dụng', 'P1',
             'Vụ việc X đang Hoạt động, chưa được sử dụng, đang hiện nút Xóa trên danh sách.',
             '1. Giữ nguyên màn danh sách, không tải lại trang\n2. Ở tab khác, lập một chứng từ (VD bút toán kế toán) có chọn vụ việc X và lưu\n3. Quay lại, bấm thùng rác ở dòng X, bấm Xóa', '',
             '- Báo "%s"\n- X vẫn còn trong danh sách\n- Tải lại trang: dòng X không còn nút Xóa' % MSG_USED),
            ('TC_05.008', 'Xóa vụ việc vừa bị người khác khóa', 'P1',
             'Tài khoản A và B cùng mở danh sách; vụ việc X đang Hoạt động, chưa được sử dụng.',
             '1. B khóa X\n2. A (chưa tải lại trang) bấm thùng rác ở dòng X, bấm Xóa', '',
             '- A nhận thông báo "%s"\n- X KHÔNG bị xóa, vẫn ở trạng thái Khóa' % MSG_LOCKED),
        ]},
        # Chức năng Khóa / Mở khóa ở cột Hành động chưa có case → nhóm MỚI sau case cuối (TC_08.024, R128)
        {'after': 128,
         'groups': [('IX', 'KHÓA / MỞ KHÓA (bổ sung 28/09/2026)', 9, [
             ('Hộp xác nhận Khóa nêu đúng tên vụ việc', 'P0', 'Vụ việc X đang Hoạt động.',
              '1. Ở cột Hành động của X chọn Khóa (nằm trong nút ba chấm "Hành động khác" nếu dòng có 4 nút)\n2. Đọc hộp xác nhận', '',
              '- Hộp tiêu đề "Khóa vụ việc", câu "Bạn có chắc muốn khóa vụ việc "X"?"\n- Có hai nút Khóa và Hủy'),
             ('Khóa thành công', 'P0', 'Đang mở hộp xác nhận Khóa của vụ việc X.',
              '1. Bấm Khóa\n2. Quan sát dòng X', '',
              '- Báo "Khóa thành công"\n- Cột Trạng thái của X đổi thành Khóa\n- Dòng X chỉ còn Mở khóa và Lịch sử (không còn Sửa, Xóa)'),
             ('Bấm Hủy thì không khóa', 'P1', 'Đang mở hộp xác nhận Khóa của vụ việc X.',
              '1. Bấm Hủy\n2. Xem lại dòng X', '',
              '- Hộp đóng, X vẫn Hoạt động, các nút giữ nguyên'),
             ('Khóa được vụ việc đã được sử dụng', 'P0',
              'Vụ việc Y đang Hoạt động, đã được chọn ở ít nhất một chứng từ (%s); dòng Y không có nút Xóa.' % USED_NGAN,
              '1. Chọn Khóa ở dòng Y\n2. Bấm Khóa', '',
              '- Khóa thành công, KHÔNG bị chặn vì đã phát sinh hạch toán\n- Các chứng từ cũ đang dùng Y giữ nguyên vụ việc Y'),
             ('Mở khóa thành công', 'P0', 'Vụ việc X đang Khóa, chưa được sử dụng.',
              '1. Chọn Mở khóa ở dòng X\n2. Đọc hộp xác nhận rồi bấm Mở khóa', '',
              '- Hộp tiêu đề "Mở khóa vụ việc", câu "Bạn có chắc muốn mở khóa vụ việc "X"?"\n- Báo "Mở khóa thành công", cột Trạng thái đổi thành Hoạt động\n- Nút Sửa và Xóa hiện lại'),
             ('Mở khóa vụ việc đã được sử dụng', 'P1', 'Vụ việc Y đang Khóa và đã được chọn ở ít nhất một chứng từ.',
              '1. Mở khóa Y\n2. Quan sát cột Hành động của Y', '',
              '- Y về Hoạt động\n- Có Sửa, Khóa và Lịch sử, KHÔNG có nút Xóa'),
             ('Vụ việc đang Khóa không sửa, không xóa được', 'P0', 'Vụ việc K đang Khóa.',
              '1. Tìm dòng K, quan sát cột Hành động\n2. Bấm vào mã của K', '',
              '- Không có bút chì và thùng rác, chỉ có Mở khóa và Lịch sử\n- Cửa sổ "Xem vụ việc" vẫn mở được ở chế độ chỉ đọc'),
             ('Hai người cùng khóa một vụ việc', 'P1', 'Tài khoản A và B cùng mở danh sách; vụ việc X đang Hoạt động.',
              '1. A khóa X thành công\n2. B (chưa tải lại trang) chọn Khóa ở dòng X, bấm Khóa', '',
              '- B nhận thông báo "%s"\n- Lịch sử của X chỉ có MỘT mốc Khóa' % MSG_CONFLICT),
             ('Khóa / Mở khóa được ghi lịch sử', 'P0', 'Vừa khóa rồi mở khóa vụ việc X.',
              '1. Mở Lịch sử của X\n2. Đọc 2 dòng trên cùng', '',
              '- Có 2 mốc loại Thay đổi trạng thái: Hoạt động → Khóa và Khóa → Hoạt động\n- Kèm tên người thực hiện và thời điểm'),
             ('Lọc danh sách theo Trạng thái sau khi khóa', 'P1', 'Vừa khóa vụ việc X.',
              '1. Mở Tìm kiếm nâng cao, chọn Trạng thái = Khóa\n2. Đổi sang Trạng thái = Hoạt động', 'Trạng thái: Khóa; Hoạt động',
              '- Chọn Khóa: X có trong kết quả\n- Chọn Hoạt động: X không có trong kết quả'),
         ])]},
    ],
    'edits': [
        ('B6', '- Danh mục phẳng, không phân cấp cha con.\n- Mỗi vụ việc là một bản ghi độc lập.\n- Vụ việc được chọn ở các chứng từ: ' + USED_W + '. Đã được chọn ở ít nhất một chứng từ thì coi là "đã sử dụng" — đây là căn cứ quyết định có xóa được hay không (Khóa thì vẫn được).'),
        ('B8', 'Màn hình dùng đúng MỘT quyền: "Quản lý danh mục vụ việc".\n- Có quyền: mở được màn hình và thực hiện đầy đủ Thêm mới, Chỉnh sửa, Xóa, Khóa, Mở khóa, Xem lịch sử.\n- Không có quyền: mục menu không hiển thị; truy cập thẳng đường dẫn thì hệ thống từ chối và báo không có quyền.\n Màn hình KHÔNG tách quyền xem riêng, cũng không phân quyền theo cấp công ty / phòng ban / bộ phận.'),
        ('B10', 'Các bẫy dễ sai nhất của màn này, QA đọc trước khi test:\n- Màn hình chỉ có MỘT quyền "Quản lý danh mục vụ việc" cho cả xem lẫn sửa. Không có quyền thì không vào được màn hình, chứ không phải vào được mà nút bị mờ.\n- Cửa sổ nhập liệu chỉ có 2 nút: Lưu và Đóng. Màn này KHÔNG có nút "Lưu và tiếp tục" như nhóm danh mục địa lý.\n- Ràng buộc duy nhất áp cho mã, KHÔNG áp cho tên. Hai bản ghi khác mã được phép trùng tên — đừng báo lỗi nhầm.\n- Xóa là xóa HẲN. Nút Xóa CHỈ hiện với vụ việc đang Hoạt động VÀ chưa được sử dụng ở chứng từ nào (' + USED_NGAN + '). Vụ việc đã sử dụng thì KHÔNG có nút Xóa; muốn ngừng dùng thì Khóa.\n- Có nút Khóa / Mở khóa ngay trên cột Hành động (dòng đủ 4 nút thì Khóa và Lịch sử nằm trong nút ba chấm). Khóa được CẢ vụ việc đã sử dụng.\n- Vụ việc đang Khóa KHÔNG có nút Sửa, Xóa — chỉ còn Mở khóa và Lịch sử; máy chủ cũng chặn cập nhật với câu "' + MSG_LOCKED + '"\n- Trạng thái mặc định của bản ghi mới là Hoạt động.'),
        ('I49', '- Bản ghi được tạo với trạng thái Khóa\n- Dòng đó chỉ có nút Mở khóa và Lịch sử (không có Sửa, Xóa)\n- Không chọn được bản ghi này khi tạo bút toán mới'),
        ('F62', 'Có bản ghi đang Hoạt động trong danh sách (bản ghi đang Khóa không có nút Sửa).'),
        ('F77', 'Bản ghi X đang Hoạt động, chưa được sử dụng ở chứng từ nào.'),
        ('I77', '- Thông báo "%s"\n- Bản ghi X biến mất khỏi danh sách\n- Lọc Trạng thái = Khóa cũng KHÔNG thấy X (xóa hẳn, không phải chuyển sang Khóa)' % MSG_OK_DEL),
        ('F78', 'Vụ việc X đang Hoạt động, chưa được sử dụng. Tài khoản A và B cùng mở danh sách.'),
        ('G78', '1. A và B cùng mở danh sách, thấy vụ việc X\n2. A xóa X\n3. B (chưa tải lại trang) xóa X'),
        ('D79', 'Vụ việc đã được sử dụng thì KHÔNG có nút Xóa'),
        ('F79', 'Vụ việc Y đang Hoạt động và đã được chọn ở ít nhất một chứng từ (' + USED_NGAN + ').'),
        ('I79', '- Có Sửa, Khóa và Lịch sử, KHÔNG có biểu tượng thùng rác'),
        ('D80', 'Vụ việc chưa được sử dụng thì CÓ nút Xóa'),
        ('F80', 'Vụ việc Z đang Hoạt động, vừa được tạo, chưa dùng ở chứng từ nào.'),
        ('I80', '- Có đủ 4 nút: Sửa và Xóa hiện thẳng; Khóa và Lịch sử nằm trong nút ba chấm "Hành động khác"'),
    ],
    'clear_k': [49, 62, 77, 78, 79, 80],
}

CFG['loi_code'] = [
    'Vụ việc đang Khóa vẫn chọn được ở màn Phiếu điều chỉnh công nợ: BillAdjustDeptController::formOptions lấy Work::query() không lọc trạng thái → tài liệu (và TC_04.011) tả “vụ việc Khóa không chọn được ở chứng từ mới” chưa đúng ở màn này. Rủi ro còn lại, chưa sửa.',
    'Các vụ việc được code gọi cứng — theo mã: TTHHD (Thưởng thực hiện hợp đồng), TT, TVC, TNST, TNSQ, CPK ở Đề nghị thanh toán / Phiếu chi / Phiếu ủy nhiệm chi; theo id: 16 GGHH (Giảm giá hàng hóa), 17 HBTL (Hàng bán trả lại) ở hạch toán phiếu xuất kho, nhập hàng trả lại, mượn–bán — vẫn Khóa được (và vẫn đổi mã được) → hạch toán tự động có thể dùng vụ việc đã khóa hoặc không tìm thấy vụ việc. Rủi ro còn lại, chưa sửa.',
    'Import: số dòng trong câu “Mã vụ việc bị trùng với dòng N trong file” lệch 1 — BE tính N = index + 2 (coi dòng 1 là tiêu đề) nhưng file mẫu có thêm dòng mô tả ở hàng 2, dữ liệu bắt đầu từ hàng 3 → N báo nhỏ hơn số hàng thật 1 đơn vị (WorkService::validateRows). Tài liệu tả chung “dòng N”.',
    'Form Tạo/Sửa không giới hạn độ dài Mã / Tên / Ghi chú (FE không có rule max, WorkRequest không có max:255) trong khi cột DB là varchar(255) và config database strict=false → chuỗi dài hơn 255 ký tự có thể bị cắt im lặng thay vì báo lỗi (Import thì có chặn 255). Cần kiểm trên màn hình.',
    'Mã nhập ở form KHÔNG tự chuyển IN HOA (lưu đúng như gõ) nhưng Import lại chuyển IN HOA → cùng danh mục có mã “vv001” (form) và “VV001” (import) cách viết khác nhau; trùng vẫn bị chặn vì so khớp không phân biệt hoa/thường.',
]

CFG['tc_ngoai_pham_vi'] = [
    'R10 (bullet giữ nguyên) + R42 TC_03.001: ghi “chỉ có 2 nút Lưu và Đóng, KHÔNG có Lưu và tiếp tục”, “Có đúng 4 ô nhập” — hiện cửa sổ Tạo có 3 nút Lưu / Lưu và tiếp tục / Đóng.',
    'R25 TC_01.002: tên cột “Người sửa” nay là “Người cập nhật”; các cột Ghi chú, Người cập nhật, Ngày cập nhật mặc định ẩn nên không thấy khi chưa chỉnh cấu hình cột.',
    'R21, R22: ghi truy cập thẳng khi không có quyền thì ra trang 404 — chưa đối chiếu lại; R22 còn ghi đường dẫn trong bước (quy ước tài liệu không ghi URL).',
    'R72 TC_04.011 (vụ việc Khóa không chọn được khi tạo bút toán) đúng với bút toán kế toán nhưng SAI ở Phiếu điều chỉnh công nợ (xem loi_code) — giữ nguyên case, chưa thêm case cho màn đó.',
    'Chưa có case Xem chi tiết (bấm mã mở cửa sổ Xem vụ việc có khối Lịch sử), Lưu và tiếp tục, Tùy chỉnh cột.',
]

# ---- SRS: "Mô tả chi tiết giao diện" + "Danh sách event và xử lý event" cho các FR sau Thêm mới
# (bổ sung 28/09/2026 theo SRS_UI_EVENTS_BRIEF.md; khuôn cột bám SRS Danh mục quốc gia).
# Nguồn: pages/finance/works (index + Modal), components/modal/{export-fields-modal, column-customization-modal,
#   CatalogHistoryModal}.vue, components/assign/SystemInfoSection.vue, components/V2BaseImport{Modal,Toolbar,Table}.vue,
#   utils/mixins/CatalogImportMixin.js; BE Controller/Service + middleware recordNotLocked, importRowLimit.
_SRS_UI_EVENTS = {'Chỉnh sửa vụ việc': {'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Phạm vi', 'Bắt buộc', 'Giá trị ban đầu', 'Mô tả'],
                              ['1',
                               'Mã vụ việc',
                               'Textbox',
                               'Enable',
                               'Chữ không dấu, số, - và _',
                               'Có',
                               'Dữ liệu hiện tại',
                               'Quy tắc như Thêm mới. Sai ký tự báo “Chỉ gồm chữ không dấu, số, dấu - và _” ngay khi gõ; bỏ trống “Bắt buộc phải '
                               'nhập”; trùng với vụ việc khác (không phân biệt hoa/thường) báo “Mã vụ việc đã tồn tại”. Giữ nguyên mã của chính bản '
                               'ghi thì không báo trùng.'],
                              ['2',
                               'Tên vụ việc',
                               'Textbox',
                               'Enable',
                               'Chuỗi ký tự',
                               'Có',
                               'Dữ liệu hiện tại',
                               'Bỏ trống báo “Bắt buộc phải nhập”. Được phép trùng tên.'],
                              ['3',
                               'Trạng thái',
                               'Dropdown',
                               'Enable',
                               'Hoạt động / Khóa',
                               'Không',
                               'Dữ liệu hiện tại (Hoạt động)',
                               'Chọn Khóa rồi Lưu để khóa ngay trong cửa sổ Sửa — chọn được kể cả khi vụ việc đã được sử dụng.'],
                              ['4', 'Ghi chú', 'Textarea', 'Enable', 'Chuỗi ký tự', 'Không', 'Dữ liệu hiện tại', 'Ô 3 dòng.'],
                              ['5', 'Nút Lưu', 'Button', 'Enable', '–', '–', 'Hiển thị', 'Ghi thay đổi rồi đóng cửa sổ, báo “Cập nhật thành công”.'],
                              ['6',
                               'Nút Đóng',
                               'Button',
                               'Enable',
                               '–',
                               '–',
                               'Hiển thị',
                               'Hủy bỏ, không ghi gì. Đã sửa dở thì hỏi “Thông tin chưa lưu” — “Bạn có thông tin chưa lưu. Có chắc chắn muốn thoát?” '
                               '(Thoát / Ở lại). Cửa sổ Sửa KHÔNG có nút Lưu và tiếp tục.']],
                       'ui_widths': [0.5, 1.2, 0.8, 0.6, 1.0, 0.6, 0.9, 2.4],
                       'events': [['Bấm biểu tượng bút chì',
                                   'Click',
                                   'Before:\n'
                                   '– Vụ việc đang Khóa thì nút không hiển thị.\n'
                                   'After:\n'
                                   '– Mở cửa sổ “Sửa vụ việc” với dữ liệu hiện tại đã điền sẵn.'],
                                  ['Bấm Lưu',
                                   'Click',
                                   'Before:\n'
                                   '– Vụ việc vừa bị người khác khóa → máy chủ từ chối, báo “Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập '
                                   'nhật.”\n'
                                   'During:\n'
                                   '– Mã vụ việc hoặc Tên vụ việc để trống → “Bắt buộc phải nhập”.\n'
                                   '– Mã vụ việc có ký tự ngoài chữ không dấu, số, - và _ → “Chỉ gồm chữ không dấu, số, dấu - và _”.\n'
                                   '– Mã vụ việc trùng với vụ việc khác (không phân biệt hoa/thường) → “Mã vụ việc đã tồn tại”.\n'
                                   '– Bỏ qua kiểm tra trùng đối với chính bản ghi đang sửa.\n'
                                   '– Có lỗi → báo đỏ dưới ô + “Vui lòng kiểm tra lại dữ liệu nhập”, cửa sổ không đóng, không thực hiện After.\n'
                                   'After:\n'
                                   '– Ghi thay đổi, ghi lịch sử “Thay đổi thông tin” (đổi Trạng thái ghi mốc Khóa / Mở khóa riêng).\n'
                                   '– Đóng cửa sổ, nạp lại danh sách, báo “Cập nhật thành công”.'],
                                  ['Bấm Đóng / biểu tượng X',
                                   'Click',
                                   'After:\n'
                                   '– Chưa sửa gì → đóng cửa sổ.\n'
                                   '– Đã sửa → hỏi “Thông tin chưa lưu” — “Bạn có thông tin chưa lưu. Có chắc chắn muốn thoát?” (Thoát / Ở lại).']]},
 'Xóa vụ việc': {'ui': [['STT', 'Tên đối tượng', 'Loại', 'Mô tả'],
                        ['1',
                         'Biểu tượng thùng rác',
                         'Icon Button',
                         'Nằm ở cột Hành động. Chỉ hiển thị khi vụ việc đang Hoạt động VÀ chưa được sử dụng ở chứng từ nào.'],
                        ['2', 'Tiêu đề hộp xác nhận', 'Label', '“Xóa vụ việc”.'],
                        ['3',
                         'Nội dung hộp xác nhận',
                         'Label',
                         '“Bạn có chắc muốn xóa vụ việc "<tên vụ việc>"?” — nêu rõ tên bản ghi để tránh xóa nhầm dòng.'],
                        ['4', 'Nút Xóa', 'Button', 'Xác nhận xóa hẳn bản ghi.'],
                        ['5', 'Nút Hủy', 'Button', 'Đóng hộp, không làm gì.']],
                 'ui_widths': [0.6, 1.6, 1.0, 3.8],
                 'events': [['Bấm biểu tượng thùng rác',
                             'Click',
                             'Before:\n'
                             '– Chỉ hiển thị khi vụ việc đang Hoạt động và chưa được sử dụng.\n'
                             'After:\n'
                             '– Hiện hộp xác nhận “Xóa vụ việc” kèm tên bản ghi.'],
                            ['Bấm Xóa trong hộp xác nhận',
                             'Click',
                             'During:\n'
                             '– Bản ghi không còn tồn tại (vừa bị người khác xóa) → “Trạng thái đã bị thay đổi. Vui lòng load lại trang”.\n'
                             '– Bản ghi đang Khóa → “Bản ghi đang bị khoá, vui lòng mở khoá trước khi cập nhật.”\n'
                             '– Bản ghi đã được sử dụng → “Vụ việc đang được sử dụng, không thể xóa.”\n'
                             '– Có lỗi → dừng, không xóa.\n'
                             'After:\n'
                             '– Xóa HẲN bản ghi khỏi danh mục, ghi lịch sử Xóa.\n'
                             '– Đóng hộp, nạp lại danh sách, báo “Đã xóa thành công”.'],
                            ['Bấm Hủy / biểu tượng X', 'Click', 'After:\n– Đóng hộp xác nhận, không thay đổi gì.']]},
 'Khóa / Mở khóa vụ việc': {'ui': [['STT', 'Tên đối tượng', 'Loại', 'Mô tả'],
                                   ['1',
                                    'Nút ba chấm “Hành động khác”',
                                    'Icon Button',
                                    'Xuất hiện khi dòng có từ 4 nút trở lên: 2 nút đầu hiện thẳng, các nút còn lại (Khóa / Mở khóa, Lịch sử) nằm '
                                    'trong nút này.'],
                                   ['2',
                                    'Mục Khóa / Mở khóa',
                                    'Button',
                                    'Nhãn đổi theo trạng thái: vụ việc đang Hoạt động hiện “Khóa”, đang Khóa hiện “Mở khóa”. Có cả khi vụ việc đã '
                                    'được sử dụng.'],
                                   ['3', 'Tiêu đề hộp xác nhận', 'Label', '“Khóa vụ việc” hoặc “Mở khóa vụ việc”.'],
                                   ['4',
                                    'Nội dung hộp xác nhận',
                                    'Label',
                                    '“Bạn có chắc muốn khóa vụ việc "<tên>"?” / “Bạn có chắc muốn mở khóa vụ việc "<tên>"?”.'],
                                   ['5', 'Nút Khóa / Mở khóa', 'Button', 'Xác nhận thực hiện.'],
                                   ['6', 'Nút Hủy', 'Button', 'Đóng hộp, không làm gì.'],
                                   ['7', 'Cột Trạng thái', 'Badge', 'Hoạt động hoặc Khóa, hai màu khác nhau.']],
                            'ui_widths': [0.6, 1.6, 1.0, 3.8],
                            'events': [['Bấm nút ba chấm', 'Click', 'After:\n– Mở menu các thao tác còn lại của dòng (Khóa / Mở khóa, Lịch sử).'],
                                       ['Chọn Khóa hoặc Mở khóa',
                                        'Click',
                                        'After:\n– Hiện hộp xác nhận “Khóa vụ việc” / “Mở khóa vụ việc” kèm tên bản ghi.'],
                                       ['Xác nhận trong hộp',
                                        'Click',
                                        'During:\n'
                                        '– Bản ghi đã ở trạng thái đích hoặc không còn tồn tại (người khác vừa thao tác) → “Trạng thái đã bị thay '
                                        'đổi. Vui lòng load lại trang”, dừng xử lý.\n'
                                        'After:\n'
                                        '– Đổi trạng thái, KHÔNG xóa dữ liệu, ghi lịch sử (Khóa / Mở khóa).\n'
                                        '– Báo “Khóa thành công” / “Mở khóa thành công”, nạp lại danh sách.\n'
                                        '– Sau khi Khóa: nút Sửa, Xóa của dòng biến mất, chỉ còn Mở khóa và Lịch sử. Sau khi Mở khóa: nút Sửa hiện '
                                        'lại (Xóa hiện lại nếu vụ việc chưa được sử dụng).'],
                                       ['Bấm Hủy / biểu tượng X', 'Click', 'After:\n– Đóng hộp xác nhận, trạng thái không đổi.']]},
 'Xem lịch sử thay đổi': {'ui': [['STT', 'Tên đối tượng', 'Loại', 'Giá trị ban đầu', 'Mô tả'],
                                 ['1',
                                  'Mục Lịch sử',
                                  'Button',
                                  'Hiển thị',
                                  'Ở cột Hành động (trong nút ba chấm khi dòng có nhiều nút). Hiện với mọi vụ việc, kể cả đang Khóa.'],
                                 ['2', 'Tiêu đề cửa sổ', 'Label', 'Lịch sử thay đổi', '“Lịch sử thay đổi: <mã vụ việc> - <tên vụ việc>”.'],
                                 ['3', 'Nút Bộ lọc', 'Button', 'Hiển thị', 'Mở / thu gọn vùng lọc, ghim ở đầu cửa sổ.'],
                                 ['4',
                                  'Loại hành động',
                                  'Dropdown',
                                  'Tất cả loại hành động',
                                  'Tạo mới / Thay đổi thông tin / Thay đổi trạng thái. Chọn là lọc ngay.'],
                                 ['5', 'Người thực hiện', 'Dropdown', 'Tất cả người thực hiện', 'Chọn là lọc ngay.'],
                                 ['6', 'Từ ngày / Đến ngày', 'Datepicker', 'Trống', 'Định dạng dd/mm/yyyy. Chọn là lọc ngay.'],
                                 ['7', 'Nút Làm mới (trong vùng lọc)', 'Button', 'Hiển thị', 'Xóa hết tiêu chí lọc của cửa sổ.'],
                                 ['8',
                                  'Dòng thời gian thay đổi',
                                  'Text',
                                  'Theo dữ liệu',
                                  '- Thời điểm: dd/mm/yyyy hh:mm.\n'
                                  '- Loại thay đổi: Tạo mới, Thay đổi thông tin, Khóa, Mở khóa.\n'
                                  '- Người thực hiện: tên kèm phòng ban.\n'
                                  '- Giá trị cũ → giá trị mới cho từng trường đã đổi.\n'
                                  'Mốc mới nhất ở trên cùng.'],
                                 ['9',
                                  'Trạng thái rỗng',
                                  'Label',
                                  'Ẩn',
                                  '“Chưa có lịch sử thao tác nào.” khi bản ghi chưa có thao tác; “Không có lịch sử phù hợp bộ lọc.” khi lọc không ra '
                                  'kết quả.'],
                                 ['10', 'Nút Đóng', 'Button', 'Hiển thị', 'Đóng cửa sổ.']],
                          'ui_widths': [0.6, 1.5, 0.9, 1.2, 3.0],
                          'events': [['Chọn Lịch sử ở cột Hành động',
                                      'Click',
                                      'After:\n'
                                      '– Mở cửa sổ “Lịch sử thay đổi: <mã vụ việc> - <tên vụ việc>”, nạp danh sách thay đổi theo thứ tự mới nhất '
                                      'trước.'],
                                     ['Bấm Bộ lọc', 'Click', 'After:\n– Mở / thu gọn vùng lọc.'],
                                     ['Đổi Loại hành động / Người thực hiện / Từ ngày / Đến ngày',
                                      'Change',
                                      'After:\n– Lọc ngay danh sách thay đổi theo đồng thời các tiêu chí.'],
                                     ['Bấm Làm mới trong vùng lọc', 'Click', 'After:\n– Xóa hết tiêu chí, hiện lại toàn bộ lịch sử.'],
                                     ['Bấm Đóng / biểu tượng X', 'Click', 'After:\n– Đóng cửa sổ; danh sách phía sau giữ nguyên bộ lọc và trang.']]},
 'Import file vụ việc': {'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Bắt buộc', 'Giá trị ban đầu', 'Mô tả'],
                                ['1',
                                 'Nút Import Excel',
                                 'Button',
                                 'Enable',
                                 '–',
                                 'Hiển thị',
                                 'Trên thanh công cụ của bảng danh sách. Mở cửa sổ “Import vụ việc” (dòng phụ “Import từ Excel • Validate xong dòng '
                                 'hợp lệ sẽ bị khoá”).'],
                                ['2',
                                 'Nút Chọn file Excel',
                                 'Button',
                                 'Enable',
                                 'Có',
                                 'Chưa chọn file',
                                 'Chọn file .xlsx / .xls từ máy; tên file hiện cạnh nút.'],
                                ['3',
                                 'Nút Tải file mẫu',
                                 'Button',
                                 'Enable',
                                 '–',
                                 'Hiển thị',
                                 'Tải Mau_import_vu_viec.xlsx, gồm các cột STT, Mã vụ việc *, Tên vụ việc *, Ghi chú, Trạng thái (cột có * là bắt '
                                 'buộc).'],
                                ['4',
                                 'Nút Load lên bảng',
                                 'Button',
                                 'Enable / Disable',
                                 '–',
                                 'Mờ khi chưa chọn file',
                                 'Đọc file và đổ dữ liệu lên bảng xem trước.'],
                                ['5',
                                 'Nút Validate',
                                 'Button',
                                 'Enable / Disable',
                                 '–',
                                 'Mờ khi bảng chưa có dòng',
                                 'Kiểm tra từng dòng; dòng hợp lệ bị khoá lại không sửa được.'],
                                ['6',
                                 'Nút Import',
                                 'Button',
                                 'Enable / Disable',
                                 '–',
                                 'Mờ',
                                 'Chỉ bấm được khi đã Validate, KHÔNG còn dòng lỗi và có ít nhất 1 dòng hợp lệ.'],
                                ['7',
                                 'Ô Tổng / Hợp lệ / Lỗi',
                                 'Label',
                                 'Read-only',
                                 '–',
                                 'Tổng: 0',
                                 'Sau khi Load hiện “Tổng”; sau khi Validate hiện thêm “Hợp lệ” và “Lỗi”. Có dòng đã sửa sau Validate hiện “Có dòng '
                                 'đã sửa (cần validate lại)”.'],
                                ['8', 'Bảng xem trước', 'Table/Grid', 'Enable', '–', 'Trống', 'Các cột như file mẫu. Sửa trực tiếp được ở dòng lỗi.'],
                                ['9',
                                 'Thông báo lỗi theo dòng',
                                 'Label',
                                 'Hiển thị',
                                 '–',
                                 'Ẩn',
                                 'Dòng lỗi viền đỏ, lý do ghi ngay dưới dòng. Hết lỗi khi sửa đúng rồi Validate lại.'],
                                ['10', 'Nút Bỏ dòng lỗi', 'Button', 'Enable', '–', 'Hiển thị', 'Loại toàn bộ dòng đang lỗi khỏi bảng xem trước.'],
                                ['11',
                                 'Nút Xoá trạng thái validate',
                                 'Button',
                                 'Enable',
                                 '–',
                                 'Hiển thị',
                                 'Bỏ khoá các dòng hợp lệ và bỏ thông báo lỗi validate.'],
                                ['12',
                                 'Nút Làm mới',
                                 'Button',
                                 'Enable',
                                 '–',
                                 'Hiển thị',
                                 'Xóa file đã chọn và toàn bộ dữ liệu trên bảng, về trạng thái vừa mở.'],
                                ['13', 'Nút Đóng', 'Button', 'Enable', '–', 'Hiển thị', 'Đóng cửa sổ, không ghi gì.']],
                         'ui_widths': [0.5, 1.4, 0.8, 0.8, 0.6, 1.0, 2.6],
                         'events': [['Bấm Import Excel', 'Click', 'After:\n– Mở cửa sổ “Import vụ việc” ở trạng thái rỗng.'],
                                    ['Bấm Tải file mẫu',
                                     'Click',
                                     'After:\n– Tải file Mau_import_vu_viec.xlsx về máy.\n– Lỗi khi tạo file → “Lỗi khi tạo file mẫu”.'],
                                    ['Bấm Chọn file Excel',
                                     'Click',
                                     'During:\n'
                                     '– File không phải .xlsx / .xls → “Vui lòng chọn file .xlsx hoặc .xls”.\n'
                                     'After:\n'
                                     '– Hiện tên file cạnh nút, nút Load lên bảng sáng lên.'],
                                    ['Bấm Load lên bảng',
                                     'Click',
                                     'During:\n'
                                     '– File không đọc được → “Không đọc được file Excel.”; không có dòng dữ liệu → “Không có dòng dữ liệu hợp '
                                     'lệ.”.\n'
                                     'After:\n'
                                     '– Đổ dữ liệu lên bảng xem trước, cập nhật ô Tổng.'],
                                    ['Bấm Validate',
                                     'Click',
                                     'During:\n'
                                     '– Quá 500 dòng → “File có X dòng dữ liệu, vượt quá giới hạn 500 dòng mỗi lần import. Vui lòng tách file và '
                                     'import nhiều lần.”\n'
                                     '– Kiểm tra từng dòng theo quy tắc Thêm mới (mục 2.3) và bảng quy tắc kiểm tra riêng của file Import.\n'
                                     'After:\n'
                                     '– Dòng lỗi tô đỏ kèm lý do, dòng hợp lệ bị khoá, hiện số Hợp lệ / Lỗi; báo “Validate xong: N hợp lệ, M không '
                                     'hợp lệ” (hoặc “Validate thành công”).\n'
                                     '– KHÔNG ghi bản ghi nào ở bước này.'],
                                    ['Sửa ô ở dòng lỗi',
                                     'Change',
                                     'After:\n– Dòng được đánh dấu đã sửa, cần Validate lại; nút Import mờ cho tới khi Validate lại hết lỗi.'],
                                    ['Bấm Bỏ dòng lỗi',
                                     'Click',
                                     'Before:\n'
                                     '– Chưa Validate → “Hãy Validate trước rồi mới bỏ dòng lỗi.”\n'
                                     'After:\n'
                                     '– Loại các dòng lỗi khỏi bảng; nút Import sáng lên nếu còn dòng hợp lệ.'],
                                    ['Bấm Import',
                                     'Click',
                                     'During:\n'
                                     '– Máy chủ kiểm tra lại toàn bộ dòng gửi lên, bỏ qua dòng lỗi; không còn dòng hợp lệ → “Không có dòng nào hợp '
                                     'lệ để import”.\n'
                                     'After:\n'
                                     '– Ghi các dòng hợp lệ thành vụ việc mới, người tạo là người thực hiện, ghi lịch sử Tạo mới.\n'
                                     '– Báo “Import thành công N vụ việc.” (có dòng thất bại thì “Import thành công a/b vụ việc. c dòng thất bại.”), '
                                     'đóng cửa sổ và nạp lại danh sách.'],
                                    ['Bấm Làm mới', 'Click', 'After:\n– Xóa file và dữ liệu trên bảng, về trạng thái vừa mở.'],
                                    ['Bấm Đóng / biểu tượng X', 'Click', 'After:\n– Đóng cửa sổ, không ghi gì.']]},
 'Xuất danh sách ra Excel': {'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
                                    ['1',
                                     'Nút Xuất Excel',
                                     'Button',
                                     'Enable',
                                     'Hiển thị',
                                     'Trên thanh công cụ của bảng danh sách. Mở cửa sổ “Chọn trường xuất file”.'],
                                    ['2',
                                     'Danh sách trường',
                                     'Checkbox chọn nhiều',
                                     'Enable',
                                     'Tích sẵn đúng các cột đang hiển thị trên bảng, xếp lên đầu theo thứ tự trên bảng',
                                     '8 trường: Mã vụ việc, Tên vụ việc, Ghi chú, Trạng thái, Người tạo, Ngày tạo, Người cập nhật, Ngày cập nhật. '
                                     'Kéo biểu tượng ☰ để đổi thứ tự cột trong file.'],
                                    ['3', 'Nút Chọn tất cả', 'Button', 'Enable', 'Hiển thị', 'Tích hết toàn bộ trường.'],
                                    ['4', 'Nút Bỏ chọn hết', 'Button', 'Enable', 'Hiển thị', 'Bỏ tích toàn bộ trường.'],
                                    ['5', 'Dòng đếm', 'Label', 'Read-only', 'Đang chọn x/8 trường', 'Cập nhật theo số trường đang tích.'],
                                    ['6',
                                     'Nút Xuất file',
                                     'Button',
                                     'Enable / Disable',
                                     'Mờ khi chưa chọn trường nào',
                                     'Sinh file Excel và tải về máy.'],
                                    ['7', 'Nút Đóng', 'Button', 'Enable', 'Hiển thị', 'Đóng cửa sổ, không xuất.']],
                             'ui_widths': [0.5, 1.4, 1.0, 0.8, 1.6, 2.7],
                             'events': [['Bấm Xuất Excel',
                                         'Click',
                                         'After:\n– Mở cửa sổ “Chọn trường xuất file”, tích sẵn đúng các cột đang hiển thị trên bảng.'],
                                        ['Tích / bỏ tích, kéo ☰ đổi thứ tự trường',
                                         'Change',
                                         'During:\n– Thứ tự trường trong cửa sổ là thứ tự cột trong file.\n– Bỏ chọn hết → nút Xuất file mờ đi.'],
                                        ['Bấm Xuất file',
                                         'Click',
                                         'During:\n'
                                         '– Lấy dữ liệu theo ĐÚNG bộ lọc, từ khóa và thứ tự sắp xếp đang áp dụng; toàn bộ kết quả (tối đa 10,000 '
                                         'dòng), không chỉ trang đang xem.\n'
                                         'After:\n'
                                         '– Tải file danh_muc_vu_viec.xlsx về máy, báo “Xuất Excel thành công”.\n'
                                         '– Lỗi → “Lỗi khi xuất Excel”.'],
                                        ['Bấm Đóng / biểu tượng X',
                                         'Click',
                                         'After:\n– Đóng cửa sổ, không xuất gì. Lần mở sau tích lại theo các cột đang hiển thị.']]},
 'Xem chi tiết vụ việc': {'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
                                 ['1',
                                  'Mã vụ việc ở cột Mã vụ việc',
                                  'Link',
                                  'Enable',
                                  'Hiển thị',
                                  'Bấm vào để mở cửa sổ “Xem vụ việc”. Bấm được với mọi vụ việc, kể cả đang Khóa.'],
                                 ['2', 'Tiêu đề cửa sổ', 'Label', 'Read-only', 'Xem vụ việc', ''],
                                 ['3', 'Mã vụ việc', 'Textbox', 'Read-only', 'Dữ liệu hiện tại', 'Không gõ được.'],
                                 ['4', 'Tên vụ việc', 'Textbox', 'Read-only', 'Dữ liệu hiện tại', 'Không gõ được.'],
                                 ['5', 'Trạng thái', 'Dropdown', 'Read-only', 'Dữ liệu hiện tại', 'Hoạt động hoặc Khóa. Không đổi được.'],
                                 ['6', 'Ghi chú', 'Textarea', 'Read-only', 'Dữ liệu hiện tại', 'Không gõ được.'],
                                 ['7',
                                  'Khối Lịch sử',
                                  'Section',
                                  'Enable',
                                  'Thu gọn',
                                  'Ở cuối cửa sổ. Bấm “Xem lịch sử” mới nạp dữ liệu; nội dung và bộ lọc giống cửa sổ Lịch sử thay đổi (mục 2.7). Có '
                                  'nút “Thu gọn” và “Làm mới”.'],
                                 ['8',
                                  'Nút Đóng',
                                  'Button',
                                  'Enable',
                                  'Hiển thị',
                                  'Nút duy nhất ở chân cửa sổ (KHÔNG có Lưu, Lưu và tiếp tục). Đóng cửa sổ.']],
                          'ui_widths': [0.5, 1.5, 0.9, 0.8, 1.1, 3.2],
                          'events': [['Bấm vào mã vụ việc ở cột Mã vụ việc',
                                      'Click',
                                      'After:\n'
                                      '– Mở cửa sổ “Xem vụ việc”, nạp dữ liệu hiện tại, mọi ô ở chế độ chỉ đọc.\n'
                                      '– Bản ghi không còn tồn tại → báo lỗi và đóng cửa sổ.'],
                                     ['Bấm Xem lịch sử / Thu gọn', 'Click', 'After:\n– Mở khối Lịch sử (lần đầu mới nạp dữ liệu) / thu gọn lại.'],
                                     ['Bấm Làm mới trong khối Lịch sử', 'Click', 'After:\n– Nạp lại danh sách thay đổi.'],
                                     ['Bấm Đóng / biểu tượng X', 'Click', 'After:\n– Đóng cửa sổ, không hỏi xác nhận (không có gì để lưu).']]},
 'Tùy chỉnh cột hiển thị': {'ui': [['STT', 'Tên đối tượng', 'Loại', 'Trạng thái', 'Giá trị ban đầu', 'Mô tả'],
                                   ['1',
                                    'Biểu tượng Cấu hình cột hiển thị',
                                    'Icon Button',
                                    'Enable',
                                    'Hiển thị',
                                    'Ở cuối thanh công cụ của bảng. Mở cửa sổ “Tuỳ chỉnh cột”.'],
                                   ['2',
                                    'Danh sách cột',
                                    'Checkbox chọn nhiều',
                                    'Enable',
                                    'Theo cấu hình đã lưu của người dùng; lần đầu ẩn sẵn Ghi chú, Người cập nhật, Ngày cập nhật',
                                    'Liệt kê đủ 10 cột theo thứ tự đang hiển thị: STT, Mã vụ việc, Tên vụ việc, Ghi chú, Người cập nhật, Ngày cập '
                                    'nhật, Người tạo, Ngày tạo, Trạng thái, Hành động. Tích = hiện, bỏ tích = ẩn.'],
                                   ['3',
                                    'Cột bắt buộc',
                                    'Checkbox',
                                    'Disable',
                                    'Tích sẵn',
                                    'STT, Mã vụ việc, Hành động: xám, có biểu tượng ổ khóa, không bỏ tích và không kéo đổi vị trí được.'],
                                   ['4',
                                    'Biểu tượng ☰',
                                    'Icon',
                                    'Enable',
                                    'Hiển thị',
                                    'Kéo để đổi vị trí các cột không bắt buộc (Tên vụ việc, Ghi chú, Người cập nhật, Ngày cập nhật, Người tạo, Ngày '
                                    'tạo, Trạng thái).'],
                                   ['5',
                                    'Nút Lưu',
                                    'Button',
                                    'Enable',
                                    'Hiển thị',
                                    'Áp dụng ngay lên bảng và lưu cấu hình theo tài khoản người dùng (đăng nhập máy khác vẫn giữ).'],
                                   ['6', 'Nút Đóng', 'Button', 'Enable', 'Hiển thị', 'Đóng cửa sổ, bỏ các thay đổi chưa lưu.']],
                            'ui_widths': [0.5, 1.5, 1.0, 0.7, 1.4, 3.0],
                            'events': [['Bấm biểu tượng Cấu hình cột hiển thị',
                                        'Click',
                                        'After:\n– Mở cửa sổ “Tuỳ chỉnh cột” theo cấu hình đang áp dụng.'],
                                       ['Tích / bỏ tích cột, kéo ☰',
                                        'Change',
                                        'During:\n– Cột bắt buộc không bỏ tích, không kéo được.\n– Chưa áp lên bảng cho tới khi bấm Lưu.'],
                                       ['Bấm Lưu',
                                        'Click',
                                        'After:\n'
                                        '– Bảng hiển thị ngay theo cột và thứ tự mới, lưu cấu hình theo người dùng, báo “Cập nhật thành công”.\n'
                                        '– Lỗi lưu → “Thao tác thất bại”.\n'
                                        '– Cửa sổ Chọn trường xuất file lần sau tích sẵn theo bộ cột mới.'],
                                       ['Bấm Đóng / biểu tượng X',
                                        'Click',
                                        'After:\n– Đóng cửa sổ, trả danh sách cột về cấu hình đang áp dụng, bảng không đổi.']]}}

for _fr in CFG['srs']['fr']:
    if _fr['ten'] in _SRS_UI_EVENTS:
        _fr.update(_SRS_UI_EVENTS[_fr['ten']])
