# -*- coding: utf-8 -*-
"""Testcase Báo cáo học tập Học viên ngoài — viết theo ngôn ngữ UI thật cho tester."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from _tc_builder import build

DESCRIPTION_BLOCK = [
    ("1. Mục đích tính năng",
     "Màn 'Báo cáo học tập — Học viên ngoài công ty' tổng hợp tình hình học của học viên ngoài: số Đăng ký, Đang học, Hoàn thành, Đã đạt, Tỷ lệ HT. Có thẻ KPI tổng và click từng dòng để xem chi tiết khóa/lộ trình đã học."),
    ("2. Đối tượng được tính / hiển thị",
     "► Học viên ngoài thỏa bộ lọc.\n► Cột: Đăng ký, Đang học, Hoàn thành, Đã đạt, Tỷ lệ HT.\n► Trạng thái học trong chi tiết: 'Hoàn thành' / 'Đang học' / 'Đã đăng ký'. Kết quả: 'Đạt' / 'Không đạt' / '—'."),
    ("3. Đối tượng bị ẩn / không tính",
     "► CHỈ tính học viên NGOÀI. Nhân viên nội bộ HRM KHÔNG có trong báo cáo này.\n► 'Trạng thái học' = 'Có đăng ký khoá' → ẩn học viên chưa đăng ký; = 'Chưa đăng ký khoá nào' → chỉ hiện học viên chưa đăng ký."),
    ("4. Bộ lọc thời gian áp dụng cho",
     "'ĐK tài khoản từ ngày' ... 'Đến ngày' lọc theo ngày đăng ký tài khoản."),
    ("5. Cấu trúc dữ liệu / cây phân cấp",
     "Mỗi dòng = 1 học viên. Click mở popup chi tiết gồm cả Khoá học và Lộ trình đã đăng ký."),
    ("6. Quy tắc cộng dồn / deduplicate",
     "Số liệu mỗi học viên = gộp khóa học + lộ trình. Tiến độ lộ trình = trung bình % các khóa trong lộ trình. 'Đã đạt' = số đã hoàn thành."),
    ("7. Phân quyền cấp",
     "• Truy cập qua menu Đào tạo (đăng nhập). Read-only. Không phân quyền theo công ty/phòng ban."),
    ("8. Cách tính các ô thống kê",
     "Thẻ KPI trên thanh: 'Học viên' = số học viên sau lọc; 'Đăng ký' = tổng đăng ký; 'Đang học' = tổng đang học; 'Hoàn thành' = tổng hoàn thành; 'Đạt' = tổng đã đạt. Cột 'Tỷ lệ HT' = Hoàn thành / Đăng ký (%)."),
    ("9. Ghi chú đọc bảng",
     "Nút 'Xuất Excel' hiện chỉ là demo (toast 'Xuất Excel (demo)', chưa tải file). Nút 'In báo cáo' in bảng hiện tại. Thẻ KPI + bảng tính lại theo bộ lọc."),
]

SECTIONS = [
    ("I", "HIỂN THỊ & KPI", [
        ("001", "Xem báo cáo mặc định", "P0",
         "Có 20 học viên có ghi danh đa dạng",
         "1. Vào menu Đào tạo > Báo cáo học tập — Học viên ngoài công ty",
         "—",
         "- Thanh KPI: 'Học viên', 'Đăng ký', 'Đang học', 'Hoàn thành', 'Đạt'\n- Bảng 'Danh sách học viên ngoài — Thống kê học tập' cột: STT, Họ tên • Email, Công ty, Nguồn ĐK, Ngày tham gia, Đăng ký, Đang học, Hoàn thành, Đã đạt, Tỷ lệ HT",
         "—"),
        ("002", "KPI = tổng trên bảng", "P0",
         "3 học viên: Đăng ký [5,3,0], Đang học [2,1,0], Hoàn thành [1,2,0]",
         "1. Không lọc trạng thái học\n2. Đọc thẻ KPI",
         "—",
         "- Học viên = 3, Đăng ký = 8, Đang học = 3, Hoàn thành = 3, Đạt = 3",
         "KPI = tổng các dòng"),
        ("003", "Tỷ lệ HT đúng công thức", "P0",
         "Học viên có Đăng ký = 4, Hoàn thành = 1",
         "1. Đọc cột 'Tỷ lệ HT' dòng đó",
         "—",
         "- Tỷ lệ HT = 25% (1/4)",
         "Tỷ lệ HT = Hoàn thành/Đăng ký"),
        ("004", "Tỷ lệ HT khi chưa đăng ký", "P1",
         "Học viên Đăng ký = 0",
         "1. Đọc cột 'Tỷ lệ HT'",
         "—",
         "- Tỷ lệ HT = 0% (không chia cho 0)",
         "—"),
    ]),
    ("II", "BỘ LỌC", [
        ("001", "Tìm theo tên/email", "P0",
         "Có học viên 'Trần B', email b@x.com",
         "1. Gõ 'Trần' vào ô 'Tìm theo tên, email...'",
         "Từ khóa: Trần",
         "- Bảng chỉ còn học viên khớp; KPI tính lại theo kết quả lọc",
         "—"),
        ("002", "Lọc Nguồn đăng ký", "P1",
         "Có học viên Form/Google",
         "1. 'Nguồn đăng ký' chọn 'Form'",
         "Nguồn: Form",
         "- Bảng chỉ còn học viên nguồn Form",
         "—"),
        ("003", "Lọc ĐK tài khoản theo ngày", "P1",
         "Học viên đăng ký 01/06 và 20/06",
         "1. 'ĐK tài khoản từ ngày' = 05/06\n2. 'Đến ngày' = 25/06",
         "05/06 → 25/06",
         "- Bảng chỉ còn học viên đăng ký trong khoảng",
         "—"),
        ("004", "Trạng thái học = Có đăng ký khoá", "P0",
         "Có học viên đã đăng ký và chưa đăng ký",
         "1. 'Trạng thái học' chọn 'Có đăng ký khoá'",
         "Có đăng ký khoá",
         "- Bảng chỉ còn học viên có Đăng ký > 0; KPI tính lại",
         "—"),
        ("005", "Trạng thái học = Chưa đăng ký khoá nào", "P1",
         "Có học viên chưa đăng ký",
         "1. 'Trạng thái học' chọn 'Chưa đăng ký khoá nào'",
         "Chưa đăng ký khoá nào",
         "- Bảng chỉ còn học viên Đăng ký = 0",
         "—"),
    ]),
    ("III", "TÍNH TOÁN GỘP & CHI TIẾT (DRILL-DOWN)", [
        ("001", "Đăng ký gộp khóa + lộ trình", "P0",
         "Học viên có 2 khóa + 1 lộ trình",
         "1. Đọc cột 'Đăng ký' dòng đó",
         "—",
         "- Đăng ký = 3 (2 khóa + 1 lộ trình)",
         "Gộp 2 nguồn"),
        ("002", "Mở chi tiết học viên", "P0",
         "Học viên có 2 khóa + 1 lộ trình",
         "1. Click vào dòng học viên\n2. Xem popup chi tiết",
         "—",
         "- Popup hiện KPI (Đăng ký/Đang học/Hoàn thành/Đạt) + bảng cột: Tên khoá / lộ trình, Loại, Trạng thái, Tiến độ, Kết quả, Ngày ĐK, Ngày HT\n- Cột Loại hiện 'Khoá học'/'Lộ trình'",
         "—"),
        ("003", "Trạng thái & Kết quả trong chi tiết", "P1",
         "Học viên có 1 khóa hoàn thành đạt, 1 đang học",
         "1. Mở chi tiết\n2. Xem cột Trạng thái + Kết quả",
         "—",
         "- Khóa xong: Trạng thái 'Hoàn thành', Kết quả 'Đạt'\n- Khóa đang học: Trạng thái 'Đang học', Kết quả '—'",
         "—"),
        ("004", "% lộ trình = trung bình khóa", "P1",
         "Lộ trình gồm 2 khóa tiến độ 100% và 0%",
         "1. Mở chi tiết, xem Tiến độ dòng lộ trình",
         "—",
         "- Tiến độ lộ trình = 50% (trung bình 100% và 0%)",
         "TB tiến độ các khóa"),
        ("005", "Tìm trong chi tiết", "P2",
         "Chi tiết có nhiều khóa/lộ trình",
         "1. Gõ vào ô 'Tìm khoá/lộ trình...'",
         "—",
         "- Danh sách chi tiết lọc theo từ khóa",
         "—"),
    ]),
    ("IV", "XUẤT EXCEL / IN", [
        ("001", "Xuất Excel (demo)", "P2",
         "Đang xem báo cáo",
         "1. Bấm 'Xuất Excel'",
         "—",
         "- Hiện toast 'Xuất Excel (demo)' (chưa tải file thật — ghi nhận chức năng chưa hoàn thiện)",
         "Xuất Excel đang demo"),
        ("002", "In báo cáo", "P2",
         "Đang xem báo cáo",
         "1. Bấm 'In báo cáo'",
         "—",
         "- Mở chế độ in bảng hiện tại",
         "—"),
    ]),
    ("V", "LUỒNG XUYÊN SUỐT (E2E)", [
        ("001", "Lọc → xem KPI → chi tiết", "P0",
         "Có ≥5 học viên có ghi danh",
         "1. 'Trạng thái học' = Có đăng ký khoá\n2. Đọc KPI\n3. Click 1 học viên xem chi tiết",
         "—",
         "- B1: bảng chỉ học viên có đăng ký\n- B2: KPI khớp tổng bảng\n- B3: popup chi tiết khóa/lộ trình học viên",
         "—"),
    ]),
]

build(
    output_file=r"d:\CompanyProject\hrm-cursor\.plans\elearning-quan-ly\bao-cao-hoc-vien-ngoai\testcase.xlsx",
    sheet_name="BaoCaoHVNgoai",
    feature_name="Báo cáo học tập - Học viên ngoài công ty",
    module_name="Báo cáo HV ngoài",
    description_block=DESCRIPTION_BLOCK,
    sections=SECTIONS,
    role_tcs=None,
)
