from _sc import *
with browser_page() as page:
    go(page, '/assign/solutions')
    page.wait_for_selector('text=GP39', timeout=180000); page.wait_for_timeout(2000)
    snap(page, '01-danh-sach.png')
    page.evaluate("x => document.querySelectorAll('.table-wrapper').forEach(e => e.scrollLeft = x)", 6000); page.wait_for_timeout(800)
    snap(page, '01b-danh-sach-phai.png')
    page.evaluate("x => document.querySelectorAll('.table-wrapper').forEach(e => e.scrollLeft = x)", 0); page.wait_for_timeout(500)
    clip(page, page.get_by_role('button', name='Tạo mới'), S + 'icon_taomoi.png')
    clip(page, page.get_by_role('button', name='Xuất Excel'), S + 'icon_xuat.png')
    clip(page, page.locator('button[title="Cấu hình cột hiển thị"]'), S + 'icon_cot.png')
    clip(page, page.get_by_role('button', name='Tìm kiếm nâng cao'), S + 'icon_timkiem.png')
    clip(page, page.get_by_role('button', name='Cài đặt bộ lọc'), S + 'icon_caidat.png')
    # menu
    page.mouse.click(1160, 30); page.wait_for_timeout(1500)
    page.screenshot(path=S + 'x-switcher.png')
    clip(page, page.locator('.switcher-item', has_text='Công việc').first, S + 'icon_phanhe_cv.png')
    clip(page, page.locator('.switcher-item', has_text='CSKH trước bán').first, S + 'icon_phanhe_presale.png')
    page.keyboard.press('Escape'); page.mouse.click(700, 700); page.wait_for_timeout(800)
    rail = page.locator('.left-side-menu .cats-list a.cat', has_text='Làm giải pháp').first
    clip(page, rail, S + 'icon_nhom_lgp.png'); crop_w(S + 'icon_nhom_lgp.png', 150)
    rail.click(); page.wait_for_timeout(1500)
    page.screenshot(path=S + 'x-flyout.png')
    try:
        clip(page, page.locator('a[href="/assign/solutions"]').last, S + 'icon_man_qlgp.png'); crop_w(S + 'icon_man_qlgp.png', 170)
    except Exception as e: print('item clip fail', e)
    page.keyboard.press('Escape'); page.wait_for_timeout(500)
    go(page, '/assign/solutions'); page.wait_for_selector('text=GP39', timeout=180000)
    page.get_by_role('button', name='Tìm kiếm nâng cao').click(); page.wait_for_timeout(1500); idle(page)
    snap(page, '02-loc.png')
    page.get_by_role('button', name='Cài đặt bộ lọc').click(); page.wait_for_timeout(1800)
    snap(page, '03-cai-dat-loc.png')
    page.keyboard.press('Escape'); page.wait_for_timeout(1200)
    page.locator('button[title="Cấu hình cột hiển thị"]').click(); page.wait_for_timeout(1800)
    snap(page, '04-tuy-chinh-cot.png')
    page.keyboard.press('Escape'); page.wait_for_timeout(1200)
    page.get_by_role('button', name='Xuất Excel').click(); page.wait_for_timeout(1800)
    snap(page, '05-xuat.png')
    page.keyboard.press('Escape'); page.wait_for_timeout(800)
