import sys; sys.path.insert(0, '/Users/manhcuong/Desktop/dns/HRM/.plans/gop-db/bao-cao-docs')
from _shoot import browser_page, clip, BASE
from PIL import Image
exec(open('shoot_common.py').read())
def goto_detail(page, qid):
    page.goto(BASE + '/assign/quotations/%d' % qid, wait_until='domcontentloaded')
    page.locator('.footer-bar').first.wait_for(timeout=180000); page.wait_for_timeout(5000)
with browser_page() as page:
    goto_detail(page, 93)
    page.screenshot(path=S + '15-xem-chi-tiet.png')
    page.screenshot(path=S + '15-xem-chi-tiet-full.png', full_page=True)
    T(lambda: clip(page, page.locator('.footer-bar').get_by_role('button', name='Sửa / Làm giá'), S + 'icon_sua_ct.png'), 'sua')
    T(lambda: clip(page, page.locator('.footer-bar').get_by_role('button', name='Xoá'), S + 'icon_xoa_ct.png'), 'xoa')
    T(lambda: clip(page, page.locator('.footer-bar').get_by_role('button', name='In'), S + 'icon_in_ct.png'), 'in')
    T(lambda: clip(page, page.locator('.footer-bar').get_by_role('button', name='Sao chép'), S + 'icon_saochep_ct.png'), 'sc')
    T(lambda: clip(page, page.locator('.footer-bar').get_by_role('button', name='Xuất Excel'), S + 'icon_xuat_ct2.png'), 'xx')
    def ls():
        b = page.get_by_role('button', name='Xem lịch sử'); b.scroll_into_view_if_needed(); clip(page, b, S + 'icon_xemlichsu.png'); b.click(); page.wait_for_timeout(5000)
        page.evaluate("() => window.scrollBy(0, 250)"); page.wait_for_timeout(800)
        page.screenshot(path=S + '20b-lich-su-chi-tiet.png')
    T(ls, 'ls')
    goto_detail(page, 98)
    page.screenshot(path=S + '21-duyet-tp.png')
    T(lambda: clip(page, page.locator('.footer-bar').get_by_role('button', name='Duyệt'), S + 'icon_duyet.png'), 'd')
    T(lambda: clip(page, page.locator('.footer-bar').get_by_role('button', name='Từ chối'), S + 'icon_tuchoi.png'), 'tc')
    def cf():
        page.locator('.footer-bar').get_by_role('button', name='Duyệt').click(); page.wait_for_timeout(1500)
        page.screenshot(path=S + '21b-xac-nhan-duyet.png'); page.get_by_role('button', name='Huỷ').click(); page.wait_for_timeout(1000)
        page.locator('.footer-bar').get_by_role('button', name='Từ chối').click(); page.wait_for_timeout(1500)
        page.screenshot(path=S + '22-tu-choi.png'); page.locator('.modal.show').get_by_role('button', name='Xác nhận từ chối').click(); page.wait_for_timeout(1000)
        page.screenshot(path=S + '22b-tu-choi-loi.png'); page.locator('.modal.show').get_by_role('button', name='Huỷ').click(); page.wait_for_timeout(1000)
    T(cf, 'cf')
    goto_detail(page, 94)
    page.screenshot(path=S + '21c-duyet-chuyen-bgd.png')
    T(lambda: clip(page, page.locator('.footer-bar').get_by_role('button', name='Duyệt & chuyển BGĐ'), S + 'icon_duyet_bgd.png'), 'db')
    goto_detail(page, 95)
    page.screenshot(path=S + '21d-bgd-duyet.png')
    T(lambda: clip(page, page.locator('.footer-bar').get_by_role('button', name='BGĐ duyệt'), S + 'icon_bgd_duyet.png'), 'bg')
    def bgdcf():
        page.locator('.footer-bar').get_by_role('button', name='BGĐ duyệt').click(); page.wait_for_timeout(1500)
        page.screenshot(path=S + '21e-xac-nhan-bgd.png'); page.get_by_role('button', name='Huỷ').click(); page.wait_for_timeout(800)
    T(bgdcf, 'bgdcf')
    goto_detail(page, 96)
    def note():
        page.get_by_text('Ghi chú Kinh doanh').first.scroll_into_view_if_needed(); page.evaluate("() => window.scrollBy(0, 200)"); page.wait_for_timeout(800)
        page.screenshot(path=S + '23-ghi-chu-kd.png')
        clip(page, page.get_by_role('button', name='Lưu ghi chú'), S + 'icon_luughichu.png')
    T(note, 'note')
    goto_detail(page, 97)
    page.screenshot(path=S + '24-lap-hop-dong.png')
    T(lambda: clip(page, page.locator('.footer-bar').get_by_role('button', name='Lập hợp đồng'), S + 'icon_laphd.png'), 'hd')
