# -*- coding: utf-8 -*-
"""Testcase Bài học — viết theo ngôn ngữ UI thật cho tester."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from _tc_builder import build

DESCRIPTION_BLOCK = [
    ("1. Mục đích tính năng",
     "Màn 'Danh sách bài học' để tạo/sửa nội dung học nhỏ nhất theo 4 loại: Video, Bài viết (Text/HTML), Tài liệu (Upload & Preview), SCORM. Mỗi bài có tiêu chí hoàn thành riêng và có thể gắn câu hỏi. Bài học được lắp vào Khóa học."),
    ("2. Đối tượng được tính / hiển thị",
     "► Bài học 'Hoạt động': có nút Xem/Sửa/Sao chép/Xoá + nút Khoá.\n► Bài học 'Khoá': hiển thị nhưng không sửa được.\n► Loại bài học: Video / Bài viết / Tài liệu / SCORM.\n► Hình thức học: Tự học / Online / Offline."),
    ("3. Đối tượng bị ẩn / không tính",
     "► Người dùng không có quyền quản lý bài học → không thao tác được (Thêm/Sửa/Xóa báo lỗi quyền).\n► Bài 'Khoá' → không sửa được.\n► Chọn loại bài nhưng thiếu nội dung tương ứng → chặn lưu."),
    ("4. Bộ lọc thời gian áp dụng cho",
     "Bộ lọc 'Cập nhật từ' ... 'Đến' áp theo ngày cập nhật gần nhất (định dạng DD/MM/YYYY)."),
    ("5. Cấu trúc dữ liệu / cây phân cấp",
     "Bài học là đơn vị độc lập; có thể gắn nhiều tài liệu đính kèm + nhiều câu hỏi (tab '2. Câu hỏi'). Được lắp vào Khóa học qua builder."),
    ("6. Quy tắc cộng dồn / deduplicate",
     "Mã bài học tự sinh, không trùng. Thời lượng nhập bằng 3 ô Giờ/Phút/Giây, hệ thống quy về giây (mặc định 0 giờ 10 phút 0 giây = 600s)."),
    ("7. Phân quyền cấp",
     "• Quản lý bài học — quyền DUY NHẤT cho xem, thêm, sửa, khóa/mở, xóa, xuất Excel. Không phân quyền theo công ty/phòng ban."),
    ("8. Cách tính các ô thống kê",
     "Không có ô thống kê. Cột Thời lượng hiển thị quy đổi từ tổng giây. Cột Trạng thái hiển thị 'Hoạt động'/'Khoá'."),
    ("9. Ghi chú đọc bảng",
     "Nhãn có dấu (*) là bắt buộc. Video: dán link YouTube → tự lấy thời lượng (không có nút bấm). Panel 'Xem trước' bên phải cập nhật theo dữ liệu đang nhập."),
]

ROLE_TCS = [
    ("01", "Vào màn khi CÓ quyền", "P0",
     "Đăng nhập tài khoản có quyền quản lý bài học; có ≥3 bài học",
     "1. Vào menu Đào tạo > Bài học",
     "Tài khoản: có quyền",
     "- Hiển thị bảng 'Danh sách bài học' + nút 'Tạo mới', 'Xuất Excel'\n- Mỗi dòng có nút Xem/Sửa/Sao chép/Xoá/Khoá",
     "Quyền: Quản lý bài học"),
    ("02", "Thao tác khi KHÔNG có quyền", "P0",
     "Tài khoản không có quyền quản lý bài học",
     "1. Thử mở form Sửa hoặc bấm Lưu bài học",
     "Tài khoản: không quyền",
     "- Toast 'Không có quyền', không lưu được",
     "—"),
]

SECTIONS = [
    ("I", "HIỂN THỊ & LỌC", [
        ("001", "Xem danh sách mặc định", "P0",
         "Có 30 bài học",
         "1. Vào màn Bài học\n2. Quan sát bảng",
         "—",
         "- Cột: STT, Mã bài học - Tên bài học, Loại bài học, Loại đào tạo, Hình thức học, Thời lượng, Cập nhật, Trạng thái\n- Phân trang tổng 30",
         "—"),
        ("002", "Lọc theo Loại bài học = SCORM", "P1",
         "Có bài Video, Bài viết, SCORM",
         "1. Bấm 'Tìm kiếm nâng cao'\n2. Ở 'Loại bài học' chọn 'SCORM'",
         "Loại bài học: SCORM",
         "- Bảng chỉ còn bài loại SCORM",
         "—"),
        ("003", "Lọc theo Hình thức học = Online", "P2",
         "Có bài Tự học/Online/Offline",
         "1. Ở 'Hình thức học' chọn 'Online'",
         "Hình thức học: Online",
         "- Bảng chỉ còn bài Online",
         "—"),
        ("004", "Lọc theo Trạng thái = Khoá", "P1",
         "Có bài Hoạt động và Khoá",
         "1. Ở 'Trạng thái' chọn 'Khoá'",
         "Trạng thái: Khoá",
         "- Bảng chỉ còn bài đang Khoá",
         "—"),
        ("005", "Tìm nhanh theo mã/tên", "P0",
         "Có bài tên 'Bài 1 Laravel'",
         "1. Gõ 'Laravel' vào ô 'Tìm theo mã bài học, tên bài học'",
         "Từ khóa: Laravel",
         "- Bảng chỉ còn bài chứa 'Laravel'",
         "—"),
    ]),
    ("II", "TẠO BÀI THEO LOẠI NỘI DUNG", [
        ("001", "Tạo bài Video hợp lệ", "P0",
         "Có quyền; có link YouTube hợp lệ",
         "1. Bấm 'Tạo mới'\n2. Chọn 'Loại đào tạo'\n3. Nhập 'Tên bài học'\n4. 'Loại bài học' = Video\n5. Dán link vào 'Link YouTube / Video ID'\n6. Chờ tự điền thời lượng\n7. Nhập 'Xem tối thiểu (%)' = 80\n8. Bấm 'Lưu'",
         "Loại: Video; % xem: 80",
         "- Sau khi dán link, thời lượng tự điền\n- Toast 'Thêm bài học thành công'\n- Bài mới trong danh sách",
         "Video bắt buộc có link"),
        ("002", "Tạo bài Video sai/thiếu link", "P0",
         "Form đang chọn Loại = Video",
         "1. Để trống 'Link YouTube / Video ID' (hoặc nhập link sai)\n2. Bấm 'Lưu'",
         "Link: (trống/sai)",
         "- Báo lỗi 'Link/ID YouTube không hợp lệ'\n- Không lưu",
         "—"),
        ("003", "Tạo bài Bài viết hợp lệ", "P0",
         "Có quyền",
         "1. 'Loại bài học' = Bài viết (Text/HTML)\n2. Soạn nội dung ở ô 'Nội dung'\n3. Bấm 'Lưu'",
         "Loại: Bài viết",
         "- Toast 'Thêm bài học thành công'",
         "—"),
        ("004", "Tạo bài Bài viết thiếu nội dung", "P1",
         "Loại = Bài viết",
         "1. Để trống 'Nội dung'\n2. Bấm 'Lưu'",
         "Nội dung: (trống)",
         "- Báo lỗi 'Vui lòng nhập nội dung bài viết'",
         "—"),
        ("005", "Tạo bài Tài liệu (upload file)", "P0",
         "Có file PDF hợp lệ",
         "1. 'Loại bài học' = Tài liệu (Upload & Preview)\n2. 'Định dạng' = PDF\n3. Bấm 'Tải file lên' và chọn file\n4. Bấm 'Lưu'",
         "Loại: Tài liệu; file PDF",
         "- Upload thành công, có preview\n- Toast 'Thêm bài học thành công'",
         "—"),
        ("006", "Tạo bài Tài liệu thiếu file", "P1",
         "Loại = Tài liệu",
         "1. Không upload file\n2. Bấm 'Lưu'",
         "File: (chưa upload)",
         "- Báo lỗi 'Vui lòng upload file tài liệu'",
         "—"),
        ("007", "Tạo bài SCORM (upload gói)", "P0",
         "Có gói SCORM .zip hợp lệ (<1GB)",
         "1. 'Loại bài học' = SCORM\n2. 'Chuẩn SCORM' = SCORM 1.2\n3. Upload gói .zip → chờ 'Đang upload & giải nén gói SCORM...'\n4. 'URL launch' tự điền\n5. 'Hoàn thành khi SCORM báo' = passed, 'Điểm tối thiểu' = 70\n6. Bấm 'Lưu'",
         "Loại: SCORM; passed; điểm 70",
         "- Upload xong, URL launch có sẵn\n- Toast 'Thêm bài học thành công'",
         "—"),
        ("008", "Tạo bài SCORM thiếu URL launch", "P1",
         "Loại = SCORM, chưa upload/URL trống",
         "1. Để trống 'URL launch'\n2. Bấm 'Lưu'",
         "URL launch: (trống)",
         "- Báo lỗi 'Vui lòng nhập URL launch của SCORM'",
         "—"),
    ]),
    ("III", "VALIDATE THÔNG TIN CHUNG", [
        ("001", "Thiếu Tên bài học", "P0",
         "Form Thêm mới",
         "1. Để trống 'Tên bài học'\n2. Bấm 'Lưu'",
         "Tên: (trống)",
         "- Báo lỗi 'Vui lòng nhập tên bài học'",
         "—"),
        ("002", "Thiếu Loại đào tạo", "P0",
         "Form Thêm mới",
         "1. Không chọn 'Loại đào tạo'\n2. Bấm 'Lưu'",
         "Loại đào tạo: (trống)",
         "- Báo lỗi 'Vui lòng chọn loại đào tạo'",
         "—"),
        ("003", "Thời lượng = 0", "P1",
         "Form Thêm mới",
         "1. Đặt Giờ=0, Phút=0, Giây=0\n2. Bấm 'Lưu'",
         "Giờ/Phút/Giây = 0/0/0",
         "- Báo lỗi 'Thời lượng học là bắt buộc (tối thiểu 1 giây)'",
         "Thời lượng tối thiểu 1 giây"),
        ("004", "Kiểm tra giá trị mặc định form", "P2",
         "Form Thêm mới vừa mở",
         "1. Quan sát các giá trị mặc định",
         "—",
         "- Trạng thái = Hoạt động; Hình thức học = Tự học; Loại bài học = Video\n- Thời lượng = 0 giờ 10 phút 0 giây; Xem tối thiểu (%) = 80",
         "Giá trị mặc định"),
        ("005", "Tiêu chí hoàn thành Bài viết mặc định", "P2",
         "Loại = Bài viết",
         "1. Xem khối 'Tiêu chí hoàn thành'",
         "—",
         "- 'Đọc tối thiểu (%)' mặc định 70; 'Min thời gian đọc (giây)' để trống = 30s",
         "—"),
    ]),
    ("IV", "CÂU HỎI & ĐÍNH KÈM", [
        ("001", "Gắn câu hỏi vào bài", "P1",
         "Ngân hàng câu hỏi có sẵn dữ liệu",
         "1. Sang tab '2. Câu hỏi'\n2. Bấm 'Chọn câu hỏi'\n3. Ở popup 'Ngân hàng câu hỏi' tick 2 câu\n4. Bấm 'Thêm vào bài học'\n5. Lưu bài",
         "Chọn 2 câu hỏi",
         "- Tab hiện '2. Câu hỏi (2)', footer 'Đã chọn: 2 câu'\n- Lưu thành công",
         "—"),
        ("002", "Thêm tài liệu đính kèm", "P2",
         "Tab '2. Câu hỏi'",
         "1. Ở bảng 'Tài liệu đính kèm' bấm 'Thêm dòng'\n2. Nhập 'Tên tài liệu' + bấm 'Chọn tệp'\n3. Lưu",
         "1 tài liệu đính kèm",
         "- Đính kèm được lưu kèm bài",
         "—"),
        ("003", "Đính kèm thiếu tên", "P2",
         "Đã thêm 1 dòng đính kèm có file, chưa nhập tên",
         "1. Bấm 'Lưu'",
         "Tên tài liệu: (trống)",
         "- Báo lỗi 'Tên tài liệu đính kèm là bắt buộc'",
         "—"),
    ]),
    ("V", "SỬA / KHÓA / XÓA / SAO CHÉP / EXPORT", [
        ("001", "Sửa bài học", "P0",
         "Bài 'Hoạt động'",
         "1. Bấm nút Sửa\n2. Đổi Tên bài học\n3. Bấm 'Lưu'",
         "—",
         "- Toast 'Cập nhật bài học thành công'\n- Danh sách cập nhật",
         "—"),
        ("002", "Sao chép bài học", "P2",
         "Bài đã có đầy đủ nội dung",
         "1. Bấm nút 'Sao chép bài học'",
         "—",
         "- Mở form 'Sao chép bài học' điền sẵn nội dung để tạo bản mới",
         "—"),
        ("003", "Khoá bài học", "P0",
         "Bài 'Hoạt động'",
         "1. Bấm nút Khoá\n2. Popup 'Xác nhận khoá' → bấm 'Khoá'",
         "—",
         "- Toast 'Khoá thành công', trạng thái → 'Khoá'",
         "—"),
        ("004", "Mở khoá bài học", "P1",
         "Bài 'Khoá'",
         "1. Bấm nút mở khoá\n2. Popup 'Xác nhận mở khoá' → bấm 'Mở khoá'",
         "—",
         "- Toast 'Mở khoá thành công', trạng thái → 'Hoạt động'",
         "—"),
        ("005", "Xóa bài học", "P0",
         "Bài không dùng trong khóa nào",
         "1. Bấm nút Xoá\n2. Popup: Bạn có chắc muốn xóa bài học '<tên>'? → bấm 'Xóa'",
         "—",
         "- Toast 'Xoá thành công', bài biến mất",
         "—"),
        ("006", "Xuất Excel", "P2",
         "Đang lọc Loại bài học = SCORM",
         "1. Bấm 'Xuất Excel'",
         "Loại: SCORM",
         "- Tải file bài học đúng bộ lọc, toast 'Xuất Excel thành công'",
         "—"),
    ]),
    ("VI", "LUỒNG XUYÊN SUỐT (E2E)", [
        ("001", "Tạo bài Video → gắn câu hỏi → khóa", "P0",
         "Có quyền, có link YouTube, có câu hỏi",
         "1. Tạo bài Video (link + % xem 80)\n2. Tab Câu hỏi chọn 2 câu\n3. Lưu\n4. Sửa đổi tên\n5. Khóa bài",
         "—",
         "- B1-3: 'Thêm bài học thành công'\n- B4: 'Cập nhật bài học thành công'\n- B5: 'Khoá thành công'",
         "—"),
    ]),
]

build(
    output_file=r"d:\CompanyProject\hrm-cursor\.plans\elearning-quan-ly\bai-hoc\testcase.xlsx",
    sheet_name="BaiHoc",
    feature_name="Bài học",
    module_name="Bài học",
    description_block=DESCRIPTION_BLOCK,
    sections=SECTIONS,
    role_tcs=ROLE_TCS,
)
