"""Generate testcase Excel cho feature Bắt buộc đổi mật khẩu (Force Change Password)."""
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from _tc_builder import build

OUTPUT_FILE = os.path.join(os.path.dirname(__file__), "testcase.xlsx")
SHEET_NAME = "ForceChangePassword"
FEATURE_NAME = "Bắt buộc đổi mật khẩu"
MODULE_NAME = "Bắt buộc đổi mật khẩu"

DESCRIPTION_BLOCK = [
    ("1. Mục đích tính năng",
     "Buộc người dùng đổi mật khẩu mặc định ngay từ lần đăng nhập ĐẦU TIÊN nếu tài khoản chưa từng đổi mật khẩu, "
     "nhằm bảo vệ tài khoản. Chặn cứng cả ở giao diện (route guard) lẫn API (BE 403) tới khi đổi xong."),
    ("2. Đối tượng được tính / hiển thị (BỊ bắt buộc đổi)",
     "► Tài khoản tạo mới sau khi deploy tính năng.\n"
     "► Chưa từng đổi mật khẩu (password_changed_at = null).\n"
     "► Đã đăng nhập thành công ≥ 1 lần (login_count ≥ 1)."),
    ("3. Đối tượng bị ẩn / không tính (ĐƯỢC miễn)",
     "► Tài khoản cũ tồn tại trước deploy → đã backfill password_changed_at = now() khi migrate → không bao giờ bị bắt.\n"
     "► Tài khoản đã từng đổi mật khẩu (password_changed_at khác null)."),
    ("4. Bộ lọc thời gian áp dụng cho",
     "Không áp dụng (tính năng không có bộ lọc thời gian)."),
    ("5. Cấu trúc dữ liệu / cây phân cấp",
     "Bảng employees thêm 2 cột: login_count (unsignedInteger, +1 mỗi lần login) và "
     "password_changed_at (timestamp nullable; null = chưa từng đổi)."),
    ("6. Quy tắc cộng dồn / deduplicate",
     "Không áp dụng. login_count tăng đơn thuần mỗi lần đăng nhập thành công."),
    ("7. Phân quyền cấp",
     "Không áp dụng — mọi tài khoản đều chịu cùng một rule, không phân quyền theo cấp.\n"
     "Whitelist API (không bị middleware MustChangePassword chặn): users/auth/* (updatePass, logout, user-profile) "
     "và master-settings* (bootstrap)."),
    ("8. Cách tính điều kiện bắt buộc",
     "require_change_password = (login_count >= 1) && (password_changed_at IS NULL).\n"
     "► Khi true: FE đẩy sang /change_password + BE trả 403 mọi API khác.\n"
     "► Khi đổi mật khẩu thành công: set password_changed_at = now() → vĩnh viễn không bị bắt nữa."),
    ("9. Ghi chú đọc bảng",
     "Rule mật khẩu mới (áp cho MỌI lần đổi, kể cả đổi tự nguyện từ menu): 7–20 ký tự, đủ 4 yếu tố "
     "(số, chữ hoa, chữ thường, ký tự đặc biệt @$!%*#?&), KHÁC mật khẩu mặc định 123456@. "
     "Lỗi inline chỉ hiện sau lần bấm submit đầu (flag touched). Nút 'Đóng' ở chế độ bắt buộc = logout về /login."),
]

SECTIONS = [
    ("I", "HIỂN THỊ TRANG & TRUY CẬP", [
        ("001", "Tài khoản mới đăng nhập lần đầu → bị ép sang màn đổi mật khẩu", "P0",
         "Tài khoản A mới tạo sau deploy: login_count=0, password_changed_at=null, đang ở màn /login",
         "1. Nhập đúng tài khoản A + mật khẩu mặc định\n2. Bấm Đăng nhập\n3. Quan sát điều hướng",
         "TK A: mật khẩu 123456@",
         "- Đăng nhập thành công nhưng KHÔNG vào dashboard\n- Tự động chuyển sang màn /change_password (chế độ bắt buộc)",
         "Công thức: login_count(=1) >= 1 && password_changed_at IS NULL → require_change_password = true"),
        ("002", "Màn đổi mật khẩu hiển thị banner cảnh báo bắt buộc", "P0",
         "Đang ở /change_password do bị ép (TK A)",
         "1. Quan sát đầu card",
         "—",
         "- Hiện banner đỏ nội dung 'Bạn cần đổi mật khẩu mới để bảo vệ tài khoản'\n- Có icon khóa + khối mô tả điều kiện mật khẩu",
         "Chế độ forced = localStorage require_change_password === '1'"),
        ("003", "Hiển thị checklist điều kiện mật khẩu live", "P1",
         "Đang ở /change_password chế độ bắt buộc",
         "1. Nhập dần mật khẩu mới vào ô 'Mật khẩu mới'\n2. Quan sát checklist điều kiện",
         "Gõ: 'Abc123@'",
         "- Mỗi điều kiện đạt (độ dài 7–20, có hoa, có thường, có số, có ký tự đặc biệt, khác 123456@) tự chuyển xanh ngay khi thỏa",
         "Checklist phản ánh đúng từng yếu tố của rule mật khẩu"),
        ("004", "Hiển thị nút 'Đóng' ở chế độ bắt buộc", "P1",
         "Đang ở /change_password chế độ bắt buộc",
         "1. Quan sát khu vực nút",
         "—",
         "- Có nút 'Đổi mật khẩu' (primary) và nút 'Đóng' (phụ)",
         "Nút Đóng chỉ xuất hiện ở chế độ bắt buộc"),
        ("005", "Tài khoản cũ (đã backfill) đăng nhập → vào thẳng hệ thống", "P0",
         "Tài khoản B tồn tại trước deploy: password_changed_at đã backfill = now()",
         "1. Đăng nhập tài khoản B\n2. Quan sát điều hướng",
         "TK B: tài khoản cũ",
         "- Vào thẳng dashboard, KHÔNG bị ép sang /change_password\n- Không có banner bắt buộc",
         "password_changed_at IS NOT NULL → require_change_password = false"),
        ("006", "Tài khoản đã từng đổi mật khẩu → đăng nhập không bị ép", "P0",
         "Tài khoản A đã đổi mật khẩu thành công ở phiên trước",
         "1. Đăng nhập tài khoản A bằng mật khẩu mới\n2. Quan sát điều hướng",
         "TK A: mật khẩu mới",
         "- Vào thẳng dashboard, không bị ép đổi",
         "Sau đổi: password_changed_at = now() → các lần login sau không bị bắt"),
        ("007", "Reload trang khi đang bị ép → vẫn giữ ở màn đổi mật khẩu", "P1",
         "TK A đang bị ép, đứng ở /change_password",
         "1. Nhấn F5 / reload trình duyệt\n2. Quan sát",
         "—",
         "- Sau reload vẫn ở /change_password, không lọt vào hệ thống",
         "Cờ require_change_password lưu localStorage → route guard giữ chặn"),
        ("008", "Cố điều hướng sang menu khác khi đang bị ép → bị chặn", "P0",
         "TK A đang bị ép, đứng ở /change_password",
         "1. Gõ trực tiếp URL màn khác (vd /human/employee)\n2. Quan sát",
         "URL: /human/employee",
         "- Bị redirect trả lại /change_password, không xem được màn đích",
         "Route guard force-change-password.js chặn mọi route ≠ /change_password"),
    ]),
    ("V", "CHỨC NĂNG CHÍNH — ĐỔI MẬT KHẨU", [
        ("001", "Đổi mật khẩu hợp lệ trong chế độ bắt buộc → vào hệ thống", "P0",
         "TK A đang bị ép ở /change_password",
         "1. Nhập mật khẩu cũ đúng = 123456@\n2. Nhập mật khẩu mới hợp lệ\n3. Nhập lại khớp\n4. Bấm 'Đổi mật khẩu'",
         "Mật khẩu mới: Abcd123@",
         "- Toast 'Đổi mật khẩu thành công'\n- Tự vào trang chủ (/)\n- Không còn bị ép đổi ở các lần sau",
         "Đổi thành công → set password_changed_at = now(), xóa cờ localStorage"),
        ("002", "Đổi tự nguyện từ menu (tài khoản đã đổi) vẫn áp rule mới", "P1",
         "TK A đã đổi mật khẩu, vào menu Đổi mật khẩu (chế độ tự nguyện)",
         "1. Mở màn /change_password từ menu\n2. Nhập mật khẩu mới KHÔNG đủ 4 yếu tố\n3. Bấm Đổi mật khẩu",
         "Mật khẩu mới: 'abcdef1' (thiếu hoa + đặc biệt)",
         "- Báo lỗi inline rule 4 yếu tố, không cho đổi\n- Không hiện banner bắt buộc (chế độ tự nguyện)",
         "Rule mật khẩu áp cho mọi lần đổi, kể cả tự nguyện"),
    ]),
    ("VI", "EDGE CASES & VALIDATION", [
        ("001", "Bỏ trống mật khẩu cũ", "P0",
         "Đang ở /change_password",
         "1. Để trống ô mật khẩu cũ\n2. Nhập mật khẩu mới hợp lệ\n3. Bấm Đổi mật khẩu",
         "old_password: rỗng",
         "- Viền đỏ ô mật khẩu cũ + text 'Bắt buộc nhập mật khẩu cũ'",
         "Rule old_password.required"),
        ("002", "Mật khẩu cũ sai", "P0",
         "Đang ở /change_password",
         "1. Nhập mật khẩu cũ SAI\n2. Nhập mật khẩu mới hợp lệ\n3. Bấm Đổi mật khẩu",
         "old_password: 'saimatkhau'",
         "- BE trả 422 → báo inline 'Mật khẩu hiện tại không đúng' tại ô mật khẩu cũ",
         "Rule MatchOldPassword"),
        ("003", "Mật khẩu mới quá ngắn (< 7 ký tự)", "P1",
         "Đang ở /change_password",
         "1. Nhập mật khẩu mới 6 ký tự\n2. Bấm Đổi mật khẩu",
         "password: 'Ab1@x'",
         "- Báo inline 'Mật khẩu mới phải dài từ 7 đến 20 ký tự'",
         "Rule min:7"),
        ("004", "Mật khẩu mới quá dài (> 20 ký tự)", "P1",
         "Đang ở /change_password",
         "1. Nhập mật khẩu mới 21 ký tự\n2. Bấm Đổi mật khẩu",
         "password: 'Abcdefgh12345678@xyzz'",
         "- Báo inline 'Mật khẩu mới phải dài từ 7 đến 20 ký tự'",
         "Rule max:20"),
        ("005", "Mật khẩu mới thiếu yếu tố (không đủ 4 loại)", "P0",
         "Đang ở /change_password",
         "1. Nhập mật khẩu mới thiếu ký tự đặc biệt và chữ hoa\n2. Bấm Đổi mật khẩu",
         "password: 'abcdef123'",
         "- Báo inline 'Mật khẩu phải gồm đủ chữ hoa, chữ thường, số và ký tự đặc biệt (@$!%*#?&)'",
         "Rule regex 4 yếu tố"),
        ("006", "Mật khẩu mới trùng mật khẩu mặc định 123456@", "P0",
         "Đang ở /change_password",
         "1. Nhập mật khẩu mới = 123456@\n2. Bấm Đổi mật khẩu",
         "password: '123456@'",
         "- Báo inline 'Không được dùng mật khẩu mặc định của hệ thống'",
         "Rule not_in:123456@"),
        ("007", "Nhập lại mật khẩu không khớp", "P0",
         "Đang ở /change_password",
         "1. Nhập mật khẩu mới hợp lệ\n2. Nhập lại KHÁC\n3. Bấm Đổi mật khẩu",
         "password: 'Abcd123@', confirm: 'Abcd123#'",
         "- Báo inline 'Mật khẩu nhập lại không trùng khớp' tại ô nhập lại",
         "Rule confirmed"),
        ("008", "Lỗi chỉ hiện sau lần submit đầu (touched)", "P2",
         "Vừa mở màn /change_password, chưa bấm submit",
         "1. Quan sát các ô input khi chưa bấm Đổi mật khẩu",
         "—",
         "- Chưa có viền đỏ / text lỗi nào dù ô đang trống\n- Lỗi chỉ xuất hiện sau lần bấm submit đầu",
         "Flag touched chỉ bật sau submit"),
    ]),
    ("VII", "CÔ LẬP DỮ LIỆU & BẢO MẬT", [
        ("001", "Bấm 'Đóng' → logout → đăng nhập lại vẫn bị ép", "P0",
         "TK A đang bị ép ở /change_password (chưa đổi)",
         "1. Bấm nút 'Đóng'\n2. Quan sát\n3. Đăng nhập lại tài khoản A",
         "TK A: chưa đổi mật khẩu",
         "- Bị logout, về /login\n- Đăng nhập lại vẫn bị ép sang /change_password",
         "Đóng = logout; chưa đổi nên password_changed_at vẫn null → vẫn bị bắt"),
        ("002", "Gọi API màn khác khi đang bị chặn → bị ép quay lại đổi mật khẩu", "P0",
         "TK A đang bị ép, thử thao tác gọi API nghiệp vụ khác",
         "1. Trong lúc bị ép, kích hoạt 1 thao tác gọi API (vd mở list)\n2. Quan sát phản hồi",
         "—",
         "- BE trả 403 kèm require_change_password=true\n- FE interceptor ép về /change_password",
         "Middleware MustChangePassword chặn mọi API trừ whitelist"),
    ]),
    ("VIII", "E2E FLOW", [
        ("001", "Luồng đầy đủ tài khoản mới: login đầu → ép đổi → đổi xong → dùng bình thường", "P0",
         "Tài khoản A mới tạo, chưa đăng nhập lần nào",
         "1. Đăng nhập lần đầu bằng 123456@\n2. Bị ép sang /change_password\n3. Đổi mật khẩu hợp lệ\n"
         "4. Vào hệ thống dùng bình thường\n5. Logout\n6. Đăng nhập lại bằng mật khẩu mới",
         "Mật khẩu mới: Abcd123@",
         "- B1–2: bị ép đổi ngay lần đầu\n- B3–4: đổi thành công, vào được hệ thống\n- B6: đăng nhập lại KHÔNG còn bị ép",
         "End-to-end xác nhận điều kiện login_count>=1 và set password_changed_at sau đổi"),
    ]),
]

build(OUTPUT_FILE, SHEET_NAME, FEATURE_NAME, MODULE_NAME, DESCRIPTION_BLOCK, SECTIONS)
