"""Generate testcase Excel cho feature Quên mật khẩu (Forgot Password)."""
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from _tc_builder import build

OUTPUT_FILE = os.path.join(os.path.dirname(__file__), "testcase.xlsx")
SHEET_NAME = "ForgotPassword"
FEATURE_NAME = "Quên mật khẩu"
MODULE_NAME = "Quên mật khẩu"

DESCRIPTION_BLOCK = [
    ("1. Mục đích tính năng",
     "Cho phép nhân viên tự đặt lại mật khẩu từ màn đăng nhập khi quên, thông qua link reset gửi về email nội bộ "
     "(token hết hạn sau 30 phút). Gồm 2 màn: /forgot_password (nhập email + captcha) và /reset_password (đặt mật khẩu mới)."),
    ("2. Đối tượng được xử lý (gửi link reset)",
     "► Email khớp tài khoản TỒN TẠI và đang hoạt động (status = 1).\n"
     "► Hệ thống sinh token 30 phút, gửi mail kèm link đặt lại."),
    ("3. Đối tượng không xử lý (báo không tìm thấy)",
     "► Email KHÔNG tồn tại trong hệ thống.\n"
     "► Email thuộc tài khoản đã khóa (status = 0).\n"
     "→ Cả 2 trả thông báo 'Không tìm thấy tài khoản' (chấp nhận lộ tồn tại email — hệ thống nội bộ)."),
    ("4. Bộ lọc thời gian áp dụng cho",
     "Token reset hết hạn sau 30 phút kể từ created_at trong bảng password_resets. "
     "Quá 30 phút → link vô hiệu, phải gửi lại."),
    ("5. Cấu trúc dữ liệu / cây phân cấp",
     "Tái dùng bảng password_resets (email, token đã hash, created_at). Không tạo bảng/migration mới. "
     "Captcha dùng mews/captcha API mode (key + ảnh base64)."),
    ("6. Quy tắc cộng dồn / deduplicate",
     "Mỗi email chỉ giữ 1 token hợp lệ: khi gửi mới sẽ XÓA token cũ trước khi insert token mới. "
     "Token dùng 1 lần — xóa ngay sau khi đặt lại mật khẩu thành công."),
    ("7. Phân quyền cấp",
     "Không áp dụng — toàn bộ luồng là public, không yêu cầu đăng nhập (route nằm trong whitelist auth). "
     "Bảo vệ bằng captcha ảnh ở bước gửi yêu cầu."),
    ("8. Cách tính / kiểm tra token",
     "► Hợp lệ = Hash::check(token gửi lên, token lưu) đúng VÀ created_at >= now()-30 phút.\n"
     "► Hết hạn = created_at < now()-30 phút → trả lỗi + xóa token.\n"
     "► Sai/không có token → 'Link đặt lại không hợp lệ'."),
    ("9. Ghi chú đọc bảng",
     "Rule mật khẩu mới khi reset: 7–20 ký tự, đủ 4 yếu tố (số, hoa, thường, đặc biệt @$!%*#?&), khác 123456@. "
     "Reset thành công set password_changed_at = now() → tài khoản không bị tính năng Bắt-buộc-đổi-mật-khẩu chặn. "
     "Lỗi inline chỉ hiện sau lần submit đầu (touched). Captcha sai → tự tải lại ảnh mới."),
]

SECTIONS = [
    ("I", "HIỂN THỊ TRANG & TRUY CẬP", [
        ("001", "Link 'Quên mật khẩu?' hiển thị ở màn đăng nhập", "P0",
         "Đang ở màn /login",
         "1. Quan sát khu vực dưới nút Đăng nhập",
         "—",
         "- Có link 'Quên mật khẩu?'\n- Bấm vào → chuyển sang màn /forgot_password",
         "Link điều hướng /forgot_password"),
        ("002", "Màn Quên mật khẩu hiển thị đầy đủ thành phần", "P0",
         "Đang ở /forgot_password",
         "1. Quan sát toàn bộ card",
         "—",
         "- Tiêu đề 'Quên mật khẩu'\n- Ô Email nội bộ\n- Ảnh captcha + nút tải lại (icon refresh)\n"
         "- Ô nhập captcha\n- Nút 'Gửi'\n- Link quay lại đăng nhập",
         "Layout màn forgot_password"),
        ("003", "Tải lại ảnh captcha", "P1",
         "Đang ở /forgot_password, đã có 1 ảnh captcha",
         "1. Bấm nút refresh cạnh ảnh captcha\n2. Quan sát ảnh",
         "—",
         "- Ảnh captcha đổi sang ảnh mới khác ảnh cũ",
         "loadCaptcha() lấy key + ảnh mới"),
        ("004", "Mở màn Đặt lại mật khẩu từ link mail hợp lệ", "P0",
         "Có mail reset, link dạng /reset_password?token=...&email=...",
         "1. Bấm link trong mail\n2. Quan sát màn",
         "Link mail còn hạn",
         "- Mở màn /reset_password\n- Hiện ô Mật khẩu mới, ô Nhập lại, checklist điều kiện, nút 'Đặt lại mật khẩu'",
         "Đọc token + email từ query"),
        ("005", "Mở /reset_password thiếu token hoặc email", "P1",
         "Truy cập /reset_password không kèm query đầy đủ",
         "1. Mở URL /reset_password (không token/email)\n2. Quan sát",
         "URL: /reset_password",
         "- Báo link không hợp lệ, không cho đặt lại mật khẩu",
         "Thiếu token/email → chặn ngay ở FE"),
    ]),
    ("V", "CHỨC NĂNG CHÍNH — GỬI YÊU CẦU & ĐẶT LẠI", [
        ("001", "Gửi yêu cầu với email hợp lệ + captcha đúng → thông báo đã gửi mail (TH1)", "P0",
         "Tài khoản X tồn tại, status=1; đang ở /forgot_password",
         "1. Nhập email của X\n2. Nhập đúng captcha\n3. Bấm Gửi",
         "Email: x@congty.vn (tồn tại, hoạt động)",
         "- Thông báo (xanh) 'Hướng dẫn đặt lại mật khẩu đã được gửi tới email nội bộ.'\n- Email X nhận được mail reset",
         "TH1: tài khoản tồn tại + status=1 → tạo token 30p + gửi mail"),
        ("002", "Nội dung mail reset đúng định dạng", "P1",
         "Đã gửi yêu cầu TH1 thành công",
         "1. Mở hộp thư email nội bộ\n2. Mở mail 'Đặt lại mật khẩu - HRM'",
         "—",
         "- Có lời chào + nút 'Đặt lại mật khẩu' trỏ đúng link\n- Ghi chú link hết hạn sau 30 phút",
         "ResetPasswordMail + blade reset-password"),
        ("003", "Đặt lại mật khẩu hợp lệ → thành công, về màn đăng nhập", "P0",
         "Đang ở /reset_password với link còn hạn",
         "1. Nhập mật khẩu mới hợp lệ\n2. Nhập lại khớp\n3. Bấm 'Đặt lại mật khẩu'",
         "Mật khẩu mới: Abcd123@",
         "- Toast 'Đặt lại mật khẩu thành công'\n- Chuyển về màn /login",
         "Token hợp lệ → đổi mật khẩu, set password_changed_at, xóa token"),
        ("004", "Đăng nhập bằng mật khẩu vừa đặt lại", "P0",
         "Vừa đặt lại mật khẩu thành công cho tài khoản X",
         "1. Ở /login nhập email X + mật khẩu mới\n2. Bấm Đăng nhập",
         "Mật khẩu: Abcd123@",
         "- Đăng nhập thành công bằng mật khẩu mới",
         "Mật khẩu đã được cập nhật trong DB"),
    ]),
    ("VI", "EDGE CASES & VALIDATION", [
        ("001", "Email không tồn tại → báo không tìm thấy (TH2)", "P0",
         "Đang ở /forgot_password",
         "1. Nhập email KHÔNG tồn tại\n2. Nhập đúng captcha\n3. Bấm Gửi",
         "Email: khongton@tai.vn",
         "- Thông báo (đỏ) 'Không tìm thấy tài khoản'\n- Không gửi mail",
         "TH2: email không khớp tài khoản"),
        ("002", "Email của tài khoản đã khóa (status=0) → báo không tìm thấy", "P0",
         "Tài khoản Y tồn tại nhưng status=0",
         "1. Nhập email Y\n2. Nhập đúng captcha\n3. Bấm Gửi",
         "Email Y: status=0",
         "- Thông báo 'Không tìm thấy tài khoản'\n- Không gửi mail",
         "Điều kiện where status=1 loại tài khoản khóa"),
        ("003", "Bỏ trống email", "P1",
         "Đang ở /forgot_password",
         "1. Để trống email\n2. Nhập captcha\n3. Bấm Gửi",
         "email: rỗng",
         "- Viền đỏ ô email + text báo bắt buộc nhập email",
         "Rule email.required"),
        ("004", "Email sai định dạng", "P1",
         "Đang ở /forgot_password",
         "1. Nhập email sai định dạng\n2. Bấm Gửi",
         "email: 'abc@@'",
         "- Báo inline email không đúng định dạng",
         "Rule email"),
        ("005", "Bỏ trống captcha", "P1",
         "Đang ở /forgot_password, đã nhập email",
         "1. Để trống ô captcha\n2. Bấm Gửi",
         "captcha: rỗng",
         "- Viền đỏ ô captcha + text bắt buộc nhập captcha",
         "Rule captcha.required"),
        ("006", "Nhập sai captcha", "P0",
         "Đang ở /forgot_password, email hợp lệ",
         "1. Nhập email\n2. Nhập SAI captcha\n3. Bấm Gửi",
         "captcha: sai mã",
         "- BE trả 422 'Mã captcha không đúng'\n- FE tự tải lại ảnh captcha mới",
         "captcha_api_check sai → 422 + refresh"),
        ("007", "Token sai / giả mạo khi đặt lại", "P0",
         "Mở /reset_password với token bịa",
         "1. Truy cập link token sai\n2. Nhập mật khẩu mới hợp lệ\n3. Bấm Đặt lại",
         "token: chuỗi giả",
         "- Báo 'Link đặt lại không hợp lệ'",
         "Hash::check token thất bại"),
        ("008", "Token quá hạn 30 phút", "P0",
         "Có link reset đã tạo > 30 phút trước",
         "1. Mở link cũ\n2. Nhập mật khẩu mới hợp lệ\n3. Bấm Đặt lại",
         "Token tạo > 30 phút",
         "- Báo 'Link đặt lại đã hết hạn'\n- Token bị xóa",
         "created_at < now()-30p → hết hạn"),
        ("009", "Token đã dùng (đặt lại lần 2)", "P0",
         "Đã đặt lại mật khẩu thành công 1 lần với link này",
         "1. Mở lại đúng link cũ\n2. Thử đặt lại lần nữa",
         "Token đã dùng",
         "- Báo link không hợp lệ (token đã bị xóa sau lần đặt đầu)",
         "Token dùng 1 lần → xóa sau reset"),
        ("010", "Gửi yêu cầu nhiều lần → chỉ link mới nhất hợp lệ", "P1",
         "Tài khoản X gửi yêu cầu 2 lần liên tiếp",
         "1. Gửi yêu cầu lần 1 (nhận link A)\n2. Gửi yêu cầu lần 2 (nhận link B)\n3. Thử đặt lại bằng link A",
         "Link A (cũ), Link B (mới)",
         "- Link A báo không hợp lệ\n- Chỉ link B đặt lại được",
         "Gửi mới xóa token cũ, giữ token mới nhất"),
        ("011", "Mật khẩu reset thiếu yếu tố (không đủ 4 loại)", "P0",
         "Đang ở /reset_password link hợp lệ",
         "1. Nhập mật khẩu mới thiếu hoa + đặc biệt\n2. Bấm Đặt lại",
         "password: 'abcdef123'",
         "- Báo inline rule 4 yếu tố, không cho đặt lại",
         "Rule regex 4 yếu tố (giống đổi mật khẩu)"),
        ("012", "Mật khẩu reset = mật khẩu mặc định 123456@", "P0",
         "Đang ở /reset_password link hợp lệ",
         "1. Nhập mật khẩu mới = 123456@\n2. Bấm Đặt lại",
         "password: '123456@'",
         "- Báo inline 'Không được dùng mật khẩu mặc định của hệ thống'",
         "Rule not_in:123456@"),
        ("013", "Nhập lại mật khẩu không khớp khi reset", "P1",
         "Đang ở /reset_password link hợp lệ",
         "1. Nhập mật khẩu mới hợp lệ\n2. Nhập lại KHÁC\n3. Bấm Đặt lại",
         "password: 'Abcd123@', confirm: 'Abcd123#'",
         "- Báo inline 'Mật khẩu nhập lại không trùng khớp'",
         "Rule confirmed"),
    ]),
    ("VII", "CÔ LẬP DỮ LIỆU & BẢO MẬT", [
        ("001", "Reset thành công → không bị tính năng Bắt-buộc-đổi-mật-khẩu chặn", "P1",
         "Tài khoản X (thuộc diện có thể bị force-change) vừa reset mật khẩu thành công",
         "1. Đặt lại mật khẩu thành công\n2. Đăng nhập bằng mật khẩu mới\n3. Quan sát điều hướng",
         "TK X",
         "- Vào thẳng hệ thống, KHÔNG bị ép sang /change_password",
         "Reset set password_changed_at=now() → require_change_password=false"),
    ]),
    ("VIII", "E2E FLOW", [
        ("001", "Luồng đầy đủ quên → reset → đăng nhập", "P0",
         "Tài khoản X tồn tại, status=1, quên mật khẩu",
         "1. Màn login bấm 'Quên mật khẩu?'\n2. Nhập email X + captcha đúng → Gửi\n"
         "3. Mở mail, bấm link đặt lại\n4. Nhập mật khẩu mới hợp lệ → Đặt lại\n5. Đăng nhập bằng mật khẩu mới",
         "Email X, mật khẩu mới Abcd123@",
         "- B2: báo đã gửi mail (TH1)\n- B4: toast thành công, về /login\n- B5: đăng nhập thành công bằng mật khẩu mới",
         "End-to-end toàn luồng quên mật khẩu"),
    ]),
]

build(OUTPUT_FILE, SHEET_NAME, FEATURE_NAME, MODULE_NAME, DESCRIPTION_BLOCK, SECTIONS)
