# -*- coding: utf-8 -*-
"""Testcase Màn học (Player) elearning — theo ngôn ngữ UI thật cho tester."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from _tc_builder import build

DESCRIPTION_BLOCK = [
    ("1. Mục đích tính năng",
     "Màn học bài (Player) để học viên xem/học nội dung 4 loại (Video/YouTube, Bài viết, Tài liệu, SCORM), tự động theo dõi tiến độ và tính hoàn thành, mở khóa bài kế tiếp, thảo luận; hoàn thành khóa → modal chúc mừng / nhắc thi / học khóa tiếp theo."),
    ("2. Đối tượng được tính / hiển thị",
     "► Bài trạng thái: Chưa học / Đang học / Đã xong / Bị khoá (badge + tooltip ở sidebar).\n► 4 loại nội dung: Video/YouTube, Bài viết, Tài liệu, SCORM.\n► Học viên nội bộ (SSO) và học viên ngoài đều học được (phải đăng nhập + đã ghi danh)."),
    ("3. Đối tượng bị ẩn / không tính",
     "► Chưa đăng nhập → bị điều hướng SSO, không vào được màn học.\n► Bài Bị khoá → không mở được (chặn click + toast).\n► Nút Chứng chỉ chỉ hiện khi đã hoàn thành khóa và khóa bật chứng chỉ."),
    ("4. Bộ lọc thời gian áp dụng cho",
     "Không áp dụng — màn học không có bộ lọc thời gian."),
    ("5. Cấu trúc dữ liệu / cây phân cấp",
     "Sidebar: Môn → Chương → Bài. Thanh tiến độ theo % bài Đã xong. Bài có thể có tiền điều kiện (nhãn 'tiền ĐK')."),
    ("6. Quy tắc cộng dồn / deduplicate",
     "Quyết định 'Đã xong' do Backend trả về (qua heartbeat / scorm-commit). FE chỉ đo tiến độ + optimistic 'Đang học'. Ngưỡng hiển thị mặc định: video 80%, bài viết/tài liệu 30s."),
    ("7. Phân quyền cấp",
     "Không phân quyền cấp. Yêu cầu: đã đăng nhập + đã ghi danh (enroll) khóa. Học viên nội bộ lưu employee_id, học viên ngoài lưu learner_id."),
    ("8. Cách tính các ô thống kê",
     "Thống kê: 'Tổng bài' = tổng số bài; 'Đã xong' = số bài done; 'Đang học' = số bài learning; 'Tiến độ' % = bài done / tổng bài. Heartbeat gửi % xem + giây đọc mỗi ~30s."),
    ("9. Ghi chú đọc bảng",
     "Điều kiện hoàn thành từng bài hiển thị ở dòng 'YC: ...' cạnh trạng thái. Rời tab khi đọc bài viết/tài liệu → dừng đếm giờ (overlay 'Bạn đã tạm rời khỏi bài học'). Bài thi làm trên hệ thống HRM (deep-link)."),
]

SECTIONS = [
    ("I", "TRUY CẬP & CHỌN BÀI", [
        ("001", "Vào màn học khi CHƯA đăng nhập", "P0",
         "Chưa đăng nhập; có link màn học",
         "1. Mở /khoa-hoc/:slug/hoc/",
         "—",
         "- Bị điều hướng sang đăng nhập/SSO (không xem được nội dung)",
         "Route học không public"),
        ("002", "Vào màn học đã đăng nhập, chưa chọn bài", "P0",
         "Đã đăng nhập, đã ghi danh khóa",
         "1. Mở màn học không kèm lessonId\n2. Quan sát vùng nội dung",
         "—",
         "- Hiện 'Chọn 1 bài ở sidebar để bắt đầu' + 'Nhấn vào bài học bên phải để xem nội dung.'\n- Sidebar hiển thị cây Môn → Chương → Bài",
         "—"),
        ("003", "Khóa học không tồn tại", "P1",
         "slug sai/không tồn tại",
         "1. Mở màn học với slug sai",
         "slug: khong-ton-tai",
         "- Hiện 'Không tìm thấy khoá học' + nút 'Về trang chủ'",
         "—"),
        ("004", "Chọn 1 bài (không khóa) ở sidebar", "P0",
         "Khóa có bài A đang mở",
         "1. Bấm bài A ở sidebar",
         "—",
         "- Mở nội dung bài A; header hiện tên bài + pill loại + trạng thái + 'YC: ...'",
         "—"),
    ]),
    ("II", "HỌC BÀI VIDEO / YOUTUBE", [
        ("001", "Xem video → chuyển Đang học", "P0",
         "Bài Video (YC: xem ≥ 80%), đang Chưa học",
         "1. Bấm play, xem một đoạn\n2. Quan sát trạng thái + sidebar",
         "Xem ~20%",
         "- Trạng thái bài đổi sang 'Đang học' (badge play vàng ở sidebar)\n- Thống kê 'Đang học' tăng",
         "Optimistic learning khi có tiến độ đầu"),
        ("002", "Xem đủ ngưỡng → Đã xong", "P0",
         "Bài Video YC xem ≥ 80%",
         "1. Xem đến ≥ 80% (hoặc xem hết)",
         "Xem ≥ 80%",
         "- Toast 'Hoàn thành bài học!'\n- Trạng thái → 'Đã xong', bài kế tiếp được mở khóa",
         "Done do BE quyết định (heartbeat)"),
        ("003", "Chặn tua khi không cho tua", "P1",
         "Bài Video cấu hình không cho tua",
         "1. Kéo thanh video vượt quá mốc đã xem",
         "—",
         "- Video bị kéo về mốc đã xem gần nhất (không cho nhảy tới)",
         "video_allow_seek = false"),
        ("004", "Rời tab khi yêu cầu tab active", "P2",
         "Bài Video yêu cầu tab đang mở",
         "1. Đang xem, chuyển sang tab khác\n2. Quay lại",
         "—",
         "- Rời tab → video pause; quay lại → tự phát tiếp",
         "video_require_active_tab = true"),
    ]),
    ("III", "HỌC BÀI VIẾT / TÀI LIỆU", [
        ("001", "Đọc bài viết đủ giờ → Đã xong", "P0",
         "Bài viết YC đọc ≥ 30s (+ cuộn nếu có)",
         "1. Mở bài viết, đọc + cuộn đến cuối, ở lại đủ 30s",
         "Đọc ≥ 30s",
         "- Trạng thái → 'Đang học' rồi 'Đã xong', toast 'Hoàn thành bài học!'",
         "text_min_read_seconds"),
        ("002", "Rời tab khi đọc → overlay dừng giờ", "P1",
         "Đang đọc bài viết",
         "1. Chuyển sang tab khác vài giây\n2. Quay lại tab bài học",
         "—",
         "- Hiện overlay 'Bạn đã tạm rời khỏi bài học' + 'Thời gian học đã tạm dừng...'\n- Bấm 'Tiếp tục học' mới đếm giờ tiếp",
         "Reading gate — chỉ đếm khi tab hiển thị"),
        ("003", "Học bài Tài liệu (PDF)", "P0",
         "Bài Tài liệu, cho phép xem",
         "1. Mở bài, xem tài liệu (iframe) đủ 30s",
         "Xem ≥ 30s",
         "- Info bar hiện tên file + loại (PDF/Word/...) + dung lượng\n- Đạt giờ → 'Đã xong'",
         "file_min_read_seconds"),
        ("004", "Tài liệu không cho tải", "P2",
         "Bài Tài liệu cấu hình không cho tải",
         "1. Quan sát nút tải/mở tab mới",
         "—",
         "- Ẩn nút 'Mở tab mới'; nếu không xem trước được: 'Tài liệu này không cho phép tải xuống.'",
         "file_allow_download = false"),
    ]),
    ("IV", "HỌC BÀI SCORM", [
        ("001", "Học SCORM đạt hoàn thành", "P0",
         "Bài SCORM YC completed_or_passed",
         "1. Mở bài, học hết gói SCORM\n2. Kết thúc (Thoát/Terminate)",
         "—",
         "- Toast 'Đã lưu tiến độ học'\n- Đạt điều kiện → 'Đã xong'",
         "scorm_completion"),
        ("002", "Tiếp tục bài SCORM đang dở", "P1",
         "Đã học dở bài SCORM lần trước",
         "1. Mở lại bài\n2. Popup 'Tiếp tục bài học?' → bấm 'Học tiếp'",
         "—",
         "- Học tiếp từ vị trí lần trước (hoặc 'Học lại từ đầu' để reset)",
         "resume"),
        ("003", "SCORM chưa đạt điểm tối thiểu", "P1",
         "Bài SCORM YC điểm tối thiểu, học viên điểm thấp",
         "1. Hoàn thành nhưng điểm < ngưỡng",
         "Điểm < min",
         "- Banner 'Chưa đạt điểm tối thiểu' + 'Điểm: {score}/{minScore}...' + nút 'Làm lại bài'\n- Bài chưa được tính 'Đã xong'",
         "scorm_min_score"),
        ("004", "Nút điều hướng gói SCORM", "P2",
         "Bài SCORM nhiều trang",
         "1. Quan sát nút điều hướng trong gói",
         "—",
         "- Nút '← Trang trước', 'Trang sau →', 'Thoát' (đã Việt hoá)",
         "—"),
    ]),
    ("V", "ĐIỀU HƯỚNG & THẢO LUẬN", [
        ("001", "Bài trước / Bài sau", "P0",
         "Đang ở bài giữa, có bài trước và sau mở",
         "1. Bấm 'Sau'\n2. Bấm 'Trước'",
         "—",
         "- Chuyển sang bài kế/bài trước (bỏ qua bài đang khóa)",
         "—"),
        ("002", "Bấm Sau ở bài cuối", "P2",
         "Đang ở bài cuối cùng mở được",
         "1. Bấm 'Sau'",
         "—",
         "- Toast 'Đây là bài cuối'",
         "—"),
        ("003", "Chế độ tập trung", "P2",
         "Đang học 1 bài (không khóa)",
         "1. Bấm 'Mở rộng layout'\n2. Bấm 'Thu gọn layout'",
         "—",
         "- Mở rộng: ẩn header/footer tập trung nội dung; Thu gọn: về bình thường",
         "focus mode"),
        ("004", "Gửi bình luận", "P1",
         "Tab 'Thảo luận'",
         "1. Nhập vào ô 'Nhập nội dung thảo luận...'\n2. Bấm 'Gửi'",
         "Nội dung: 'Bài hay'",
         "- Toast 'Đã gửi bình luận', bình luận xuất hiện",
         "—"),
        ("005", "Gửi bình luận trống", "P2",
         "Tab Thảo luận",
         "1. Để trống\n2. Bấm 'Gửi'",
         "(trống)",
         "- Toast cảnh báo 'Nhập nội dung trước khi gửi'",
         "—"),
        ("006", "Xem Mô tả / Tài liệu đính kèm", "P2",
         "Bài có mô tả + đính kèm",
         "1. Mở tab 'Mô tả bài học'\n2. Mở tab 'Tài liệu đính kèm', bấm 'Tải xuống'",
         "—",
         "- Mô tả hiển thị (rỗng: 'Chưa có mô tả cho bài học này.')\n- Tải được file đính kèm",
         "—"),
    ]),
    ("VI", "KHÓA BÀI & TIỀN ĐIỀU KIỆN", [
        ("001", "Bài bị khóa hiển thị đúng", "P0",
         "Có bài C bị khóa do chưa xong tiền ĐK",
         "1. Quan sát bài C ở sidebar",
         "—",
         "- Bài C có icon khóa (tooltip 'Bị khoá'), mờ, có nhãn 'tiền ĐK'",
         "BR-07 prerequisite"),
        ("002", "Bấm vào bài đang khóa", "P0",
         "Bài C đang khóa",
         "1. Bấm bài C ở sidebar",
         "—",
         "- Không mở; toast 'Bài đang bị khoá – cần hoàn thành bài tiền điều kiện'",
         "—"),
        ("003", "Overlay bài khóa + về tiền ĐK", "P1",
         "Truy cập trực tiếp bài khóa qua URL",
         "1. Mở URL bài khóa\n2. Bấm 'Về bài tiền điều kiện'",
         "—",
         "- Vùng nội dung hiện 'Bài đang bị khoá' + 'Cần hoàn thành bài tiền điều kiện để mở.'\n- Bấm nút → mở bài tiền điều kiện đầu tiên",
         "—"),
        ("004", "Học tuần tự mở dần", "P1",
         "Khóa bật học tuần tự (linear)",
         "1. Hoàn thành bài đang mở",
         "—",
         "- Bài kế tiếp tự mở khóa ngay sau khi bài trước 'Đã xong'",
         "linear_required"),
    ]),
    ("VII", "HOÀN THÀNH KHÓA & BÀI THI", [
        ("001", "Hoàn thành khóa (khóa lẻ)", "P0",
         "Học viên hoàn thành bài cuối để đủ điều kiện đạt khóa",
         "1. Hoàn thành bài cuối",
         "—",
         "- Mở modal 🎉 'Chúc mừng hoàn thành khoá học!'\n- Nút 'Khám phá khoá học khác' (hoặc 'Xem chứng chỉ' nếu khóa có chứng chỉ) + 'Đóng'",
         "enrollment done"),
        ("002", "Nút Chứng chỉ ở sidebar", "P1",
         "Đã hoàn thành khóa, khóa bật chứng chỉ",
         "1. Quan sát sidebar",
         "—",
         "- Hiện nút 'Chứng chỉ' → mở màn chứng chỉ",
         "certificate_enabled"),
        ("003", "Nhắc làm bài thi (exam-mode)", "P0",
         "Khóa đánh giá bằng bài thi, đủ điều kiện thi",
         "1. Hoàn thành đủ nội dung học",
         "—",
         "- Modal 📝 'Sẵn sàng làm bài thi!' + 'Làm đề thi' / 'Để sau'",
         "BR-08 exam prompt"),
        ("004", "Làm đề thi deep-link HRM", "P1",
         "Đang mở modal nhắc thi",
         "1. Bấm 'Làm đề thi'",
         "—",
         "- Chuyển sang hệ thống HRM để làm bài thi (kèm link quay lại)",
         "deep-link exam_link"),
    ]),
    ("VIII", "HỌC TRONG LỘ TRÌNH (?lp=)", [
        ("001", "Hoàn thành khóa còn khóa tiếp theo", "P0",
         "Đang học 1 khóa trong lộ trình còn khóa sau chưa xong",
         "1. Hoàn thành khóa hiện tại",
         "—",
         "- Modal 'Hoàn thành khoá học!' + nút 'Học khoá tiếp theo: {tên}' + 'Quay lại lộ trình'",
         "?lp mode"),
        ("002", "Học sang khóa tiếp theo giữ ngữ cảnh", "P1",
         "Đang mở modal có nút 'Học khoá tiếp theo'",
         "1. Bấm 'Học khoá tiếp theo: {tên}'",
         "—",
         "- Chuyển sang màn học khóa kế, vẫn giữ ngữ cảnh lộ trình (nút quay lại là 'Lộ trình')",
         "giữ query ?lp"),
        ("003", "Hoàn thành cả lộ trình", "P0",
         "Hoàn thành khóa cuối trong lộ trình",
         "1. Hoàn thành khóa cuối",
         "—",
         "- Modal 'Chúc mừng! Bạn đã hoàn thành lộ trình' + 'Xem chứng chỉ lộ trình' (nếu bật) + 'Khám phá lộ trình khác'",
         "lpComplete"),
    ]),
]

build(
    output_file=r"d:\CompanyProject\hrm-cursor\.plans\elearning-hoc-vien\man-hoc-player\testcase.xlsx",
    sheet_name="ManHocPlayer",
    feature_name="Màn học (Player)",
    module_name="Màn học",
    description_block=DESCRIPTION_BLOCK,
    sections=SECTIONS,
    role_tcs=None,
)
