# -*- coding: utf-8 -*-
"""Testcase Học viên ngoài công ty — viết theo ngôn ngữ UI thật cho tester."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from _tc_builder import build

DESCRIPTION_BLOCK = [
    ("1. Mục đích tính năng",
     "Màn 'Quản lý học viên ngoài công ty' để xem/tìm kiếm/xem nhanh/khoá-mở khoá tài khoản học viên tự đăng ký (qua Form hoặc Google Auth) và xuất Excel. Read-only về hồ sơ, chỉ đổi trạng thái tài khoản."),
    ("2. Đối tượng được tính / hiển thị",
     "► Tất cả học viên ngoài.\n► Trạng thái: 'Đang hoạt động' / 'Đã khoá'.\n► Nguồn đăng ký hiển thị pill: 'Form' / 'Google'.\n► Modal xem nhanh có tóm tắt: Đã đăng ký / Đang học / Hoàn thành / Tổng cộng."),
    ("3. Đối tượng bị ẩn / không tính",
     "► Nhân viên nội bộ HRM KHÔNG hiển thị ở màn này (màn chỉ quản lý học viên tự đăng ký).\n► Không có tạo/sửa hồ sơ học viên."),
    ("4. Bộ lọc thời gian áp dụng cho",
     "'Ngày đăng ký từ' ... 'đến' lọc theo ngày đăng ký tài khoản."),
    ("5. Cấu trúc dữ liệu / cây phân cấp",
     "Danh sách phẳng. Mỗi học viên có tóm tắt học tập (xem qua nút 'Xem nhanh')."),
    ("6. Quy tắc cộng dồn / deduplicate",
     "Tìm kiếm khớp Họ tên HOẶC Email HOẶC Số điện thoại. Tóm tắt học tập đếm theo trạng thái khóa đã đăng ký."),
    ("7. Phân quyền cấp",
     "• Truy cập qua menu Đào tạo (đăng nhập). Không phân quyền theo công ty/phòng ban. Chỉ read-only + khoá/mở tài khoản."),
    ("8. Cách tính các ô thống kê",
     "Modal xem nhanh: 'Đã đăng ký' = số khóa trạng thái đăng ký; 'Đang học' = đang học; 'Hoàn thành' = hoàn thành; 'Tổng cộng' = tổng khóa đã đăng ký."),
    ("9. Ghi chú đọc bảng",
     "Trạng thái tài khoản dùng chữ 'Đang hoạt động'/'Đã khoá'. Nút 'Xem báo cáo chi tiết' trong modal hiện đang bị vô hiệu. File Excel tải về: danh-sach-hoc-vien-ngoai.xls."),
]

SECTIONS = [
    ("I", "HIỂN THỊ & LỌC", [
        ("001", "Xem danh sách mặc định", "P0",
         "Có 40 học viên ngoài",
         "1. Vào menu Đào tạo > Quản lý học viên ngoài công ty\n2. Quan sát bảng 'Danh sách học viên ngoài công ty'",
         "—",
         "- Cột: STT, Họ tên • Email, Số điện thoại, Công ty, Chức vụ, Nguồn đăng ký, Ngày đăng ký, Trạng thái, Hành động\n- Phân trang tổng 40",
         "—"),
        ("002", "Tìm theo tên/email/SĐT", "P0",
         "Có học viên 'Nguyễn An', email an@x.com, SĐT 0900",
         "1. Gõ 'an' vào ô 'Tìm theo tên, email, số điện thoại...'",
         "Từ khóa: an",
         "- Bảng hiện học viên khớp tên/email/SĐT chứa 'an'",
         "Khớp tên/email/SĐT"),
        ("003", "Lọc Nguồn đăng ký = Google Auth", "P1",
         "Có học viên Form và Google",
         "1. Bấm 'Tìm kiếm nâng cao'\n2. 'Nguồn đăng ký' chọn 'Google Auth'",
         "Nguồn: Google Auth",
         "- Bảng chỉ còn học viên đăng ký qua Google (pill 'Google')",
         "—"),
        ("004", "Lọc Trạng thái = Đã khoá", "P1",
         "Có học viên Đang hoạt động và Đã khoá",
         "1. 'Trạng thái' chọn 'Đã khoá'",
         "Trạng thái: Đã khoá",
         "- Bảng chỉ còn học viên 'Đã khoá'",
         "—"),
        ("005", "Lọc khoảng ngày đăng ký", "P1",
         "Học viên đăng ký 01/06 và 20/06",
         "1. 'Ngày đăng ký từ' = 05/06\n2. 'đến' = 25/06",
         "05/06 → 25/06",
         "- Bảng chỉ còn học viên đăng ký trong khoảng",
         "—"),
        ("006", "Danh sách rỗng", "P2",
         "Không có học viên khớp 'zzz'",
         "1. Gõ 'zzz'",
         "Từ khóa: zzz",
         "- Hiện 'Không có dữ liệu phù hợp bộ lọc.'",
         "—"),
    ]),
    ("II", "XEM NHANH HỒ SƠ", [
        ("001", "Xem nhanh + tóm tắt học tập", "P0",
         "Học viên có 5 ghi danh (2 hoàn thành, 1 đang học, 2 đã đăng ký)",
         "1. Bấm nút 'Xem nhanh' 1 dòng\n2. Xem popup 'Xem thông tin học viên'",
         "—",
         "- Popup hiện: SĐT, Công ty, Chức vụ, Lĩnh vực quan tâm\n- Mục 'Tóm tắt học tập': Đã đăng ký = 2, Đang học = 1, Hoàn thành = 2, Tổng cộng = 5",
         "—"),
        ("002", "Học viên chưa đăng ký khóa nào", "P1",
         "Học viên chưa ghi danh khóa nào",
         "1. Bấm 'Xem nhanh'",
         "—",
         "- Popup hiện 'Học viên chưa đăng ký khoá học nào.'",
         "—"),
        ("003", "Nút Xem báo cáo chi tiết vô hiệu", "P2",
         "Đang mở popup xem nhanh",
         "1. Quan sát nút 'Xem báo cáo chi tiết'",
         "—",
         "- Nút 'Xem báo cáo chi tiết' bị vô hiệu (disabled)",
         "—"),
    ]),
    ("III", "KHÓA / MỞ KHÓA TÀI KHOẢN", [
        ("001", "Khoá tài khoản đang hoạt động", "P0",
         "Học viên 'Đang hoạt động'",
         "1. Bấm nút khoá dòng đó\n2. Popup 'Xác nhận khoá tài khoản': Bạn có chắc muốn khoá tài khoản \"{Họ tên}\"? → bấm 'Khoá'",
         "—",
         "- Toast 'Khoá tài khoản thành công'\n- Trạng thái → 'Đã khoá'",
         "—"),
        ("002", "Mở khoá tài khoản đã khoá", "P1",
         "Học viên 'Đã khoá'",
         "1. Bấm nút mở khoá\n2. Popup 'Xác nhận mở khoá': Bạn có chắc muốn mở khoá tài khoản \"{Họ tên}\"? → bấm 'Mở khoá'",
         "—",
         "- Toast 'Mở khoá tài khoản thành công'\n- Trạng thái → 'Đang hoạt động'",
         "—"),
        ("003", "Hủy hộp thoại khoá", "P2",
         "Đang mở popup 'Xác nhận khoá tài khoản'",
         "1. Bấm 'Hủy'",
         "—",
         "- Popup đóng, trạng thái tài khoản không đổi",
         "—"),
    ]),
    ("IV", "XUẤT EXCEL", [
        ("001", "Xuất Excel theo bộ lọc", "P1",
         "Đang lọc Nguồn = Form",
         "1. Bấm 'Xuất Excel'",
         "Nguồn: Form",
         "- Tải file danh-sach-hoc-vien-ngoai.xls đúng bộ lọc",
         "—"),
        ("002", "Xuất Excel toàn bộ", "P2",
         "Không áp bộ lọc",
         "1. Bấm 'Xuất Excel'",
         "—",
         "- Tải file chứa toàn bộ học viên",
         "—"),
    ]),
    ("V", "LUỒNG XUYÊN SUỐT (E2E)", [
        ("001", "Tìm → xem nhanh → khoá", "P0",
         "Học viên có ghi danh",
         "1. Tìm học viên theo tên\n2. Bấm 'Xem nhanh' xem tóm tắt\n3. Khoá tài khoản",
         "—",
         "- B2: tóm tắt hiển thị đúng số\n- B3: toast 'Khoá tài khoản thành công', trạng thái 'Đã khoá'",
         "—"),
    ]),
]

build(
    output_file=r"d:\CompanyProject\hrm-cursor\.plans\elearning-quan-ly\hoc-vien-ngoai\testcase.xlsx",
    sheet_name="HocVienNgoai",
    feature_name="Học viên ngoài công ty",
    module_name="Học viên ngoài",
    description_block=DESCRIPTION_BLOCK,
    sections=SECTIONS,
    role_tcs=None,
)
