# -*- coding: utf-8 -*-
"""Testcase Danh mục Kỹ năng — viết theo ngôn ngữ UI thật cho tester."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from _tc_builder import build

DESCRIPTION_BLOCK = [
    ("1. Mục đích tính năng",
     "Màn 'Quản lý kỹ năng' để tạo/sửa/khóa/xóa danh mục kỹ năng dùng cho đào tạo & e-learning. Kỹ năng được gắn vào Khóa học và Lộ trình, dùng lọc 'Học theo kỹ năng' ở trang học viên."),
    ("2. Đối tượng được tính / hiển thị",
     "► Kỹ năng trạng thái 'Hoạt động': có nút Sửa, Lịch sử, Xóa.\n► Kỹ năng trạng thái 'Khóa': vẫn hiện trong bảng nhưng KHÔNG có nút Sửa/Lịch sử/Xóa, chỉ còn nút mở khóa.\n► Chỉ hiển thị dữ liệu khi người dùng có quyền 'Quản lý kỹ năng'."),
    ("3. Đối tượng bị ẩn / không tính",
     "► Người dùng KHÔNG có quyền 'Quản lý kỹ năng' → mở màn thấy trang lỗi (không có dữ liệu).\n► Nút Sửa/Lịch sử ẩn khi kỹ năng đang 'Khóa'."),
    ("4. Bộ lọc thời gian áp dụng cho",
     "Không có bộ lọc theo khoảng thời gian ở màn này."),
    ("5. Cấu trúc dữ liệu / cây phân cấp",
     "Danh sách phẳng, không phân cấp. Mỗi kỹ năng có lịch sử thay đổi riêng (xem qua nút Lịch sử)."),
    ("6. Quy tắc cộng dồn / deduplicate",
     "Tên kỹ năng không được trùng (kể cả khi sửa). Không cộng dồn."),
    ("7. Phân quyền cấp",
     "• Quản lý kỹ năng — quyền DUY NHẤT kiểm soát toàn màn (xem, thêm, sửa, khóa/mở, xóa, lịch sử, xuất Excel, in). Không phân quyền theo công ty/phòng ban."),
    ("8. Cách tính các ô thống kê",
     "Không có ô thống kê. Cột Trạng thái hiển thị 'Hoạt động' (nền xanh) hoặc 'Khóa' (nền đỏ)."),
    ("9. Ghi chú đọc bảng",
     "Mặc định 10 dòng/trang, sắp xếp theo Cập nhật mới nhất. Cột Cập nhật hiện ngày + tên người cập nhật. Xuất Excel/In theo đúng bộ lọc đang áp."),
]

ROLE_TCS = [
    ("01", "Vào màn khi CÓ quyền 'Quản lý kỹ năng'", "P0",
     "Đăng nhập tài khoản có quyền 'Quản lý kỹ năng'; đã có sẵn ≥3 kỹ năng",
     "1. Vào menu Đào tạo > Quản lý kỹ năng",
     "Tài khoản: có quyền",
     "- Hiển thị bộ lọc + bảng 'Danh sách kỹ năng'\n- Có nút 'Xuất Excel', 'In', 'Thêm mới'\n- Mỗi dòng có nút Sửa/Lịch sử/Xóa theo trạng thái",
     "Quyền: Quản lý kỹ năng"),
    ("02", "Vào màn khi KHÔNG có quyền", "P0",
     "Đăng nhập tài khoản không có quyền 'Quản lý kỹ năng'",
     "1. Mở đường dẫn màn Quản lý kỹ năng",
     "Tài khoản: không quyền",
     "- Hiển thị trang báo lỗi, không thấy danh sách kỹ năng",
     "FE chặn toàn màn theo quyền"),
]

SECTIONS = [
    ("I", "HIỂN THỊ & LỌC DANH SÁCH", [
        ("001", "Xem danh sách mặc định", "P0",
         "Đã có 25 kỹ năng",
         "1. Vào màn Quản lý kỹ năng\n2. Quan sát bảng",
         "—",
         "- Bảng hiện 10 dòng đầu, cột: STT, Kỹ năng (tên + Ngày tạo), Trạng thái, Cập nhật\n- Phân trang hiện tổng 25 (3 trang)",
         "Mặc định 10 dòng/trang"),
        ("002", "Nhãn trạng thái đúng màu", "P1",
         "Có 1 kỹ năng 'Hoạt động' và 1 kỹ năng 'Khóa'",
         "1. Nhìn cột Trạng thái 2 dòng",
         "—",
         "- Kỹ năng hoạt động: chữ 'Hoạt động' nền xanh\n- Kỹ năng khóa: chữ 'Khóa' nền đỏ",
         "—"),
        ("003", "Nút thao tác theo trạng thái", "P0",
         "1 kỹ năng 'Hoạt động', 1 kỹ năng 'Khóa'",
         "1. Rê chuột vào cụm nút cuối mỗi dòng",
         "—",
         "- Dòng 'Hoạt động': có nút Sửa, Lịch sử thay đổi, Xóa\n- Dòng 'Khóa': không có Sửa/Lịch sử/Xóa; chỉ còn nút mở khóa ở cột Trạng thái",
         "Chỉ 'Hoạt động' mới sửa/xóa được"),
        ("004", "Tìm nhanh theo tên kỹ năng", "P0",
         "Có kỹ năng 'Lập trình PHP', 'Lập trình Java', 'Kế toán'",
         "1. Gõ 'Lập trình' vào ô 'Tìm theo tên kỹ năng...'",
         "Từ khóa: Lập trình",
         "- Bảng còn 2 dòng chứa 'Lập trình'\n- 'Kế toán' bị ẩn",
         "—"),
        ("005", "Lọc theo Trạng thái = Khóa", "P1",
         "Có 3 kỹ năng Hoạt động, 2 Khóa",
         "1. Bấm 'Tìm kiếm nâng cao'\n2. Ở ô Trạng thái chọn 'Khóa'",
         "Trạng thái: Khóa",
         "- Bảng chỉ còn 2 kỹ năng đang Khóa",
         "—"),
        ("006", "Danh sách rỗng theo bộ lọc", "P2",
         "Không có kỹ năng nào tên chứa 'zzz'",
         "1. Gõ 'zzz' vào ô tìm nhanh",
         "Từ khóa: zzz",
         "- Bảng hiện dòng 'Không có dữ liệu phù hợp bộ lọc.'",
         "Empty state"),
    ]),
    ("II", "THÊM MỚI / SỬA", [
        ("001", "Thêm mới kỹ năng hợp lệ", "P0",
         "Có quyền; chưa tồn tại kỹ năng 'Kỹ năng mềm'",
         "1. Bấm 'Thêm mới'\n2. Ở popup 'Thêm mới kỹ năng', nhập ô 'Tên kỹ năng' = Kỹ năng mềm\n3. Bấm 'Lưu'",
         "Tên kỹ năng: Kỹ năng mềm",
         "- Toast 'Lưu thành công', popup đóng\n- Kỹ năng mới xuất hiện đầu danh sách, trạng thái 'Hoạt động'",
         "Tên bắt buộc + không trùng"),
        ("002", "Thêm mới bỏ trống tên", "P0",
         "Popup 'Thêm mới kỹ năng' đang mở",
         "1. Để trống ô 'Tên kỹ năng'\n2. Bấm 'Lưu'",
         "Tên kỹ năng: (trống)",
         "- Ô Tên viền đỏ + báo lỗi 'Vui lòng nhập tên kỹ năng'\n- Không lưu, popup vẫn mở",
         "Tên bắt buộc"),
        ("003", "Thêm mới tên đã tồn tại", "P0",
         "Đã có kỹ năng 'Lập trình PHP'",
         "1. Bấm 'Thêm mới', nhập Tên = Lập trình PHP\n2. Bấm 'Lưu'",
         "Tên kỹ năng: Lập trình PHP",
         "- Báo lỗi 'Tên đã tồn tại' tại ô Tên\n- Không tạo bản ghi",
         "Tên không được trùng"),
        ("004", "Sửa tên kỹ năng", "P0",
         "Kỹ năng 'Kế toán' đang Hoạt động",
         "1. Bấm nút Sửa ở dòng 'Kế toán'\n2. Popup 'Sửa kỹ năng' hiện sẵn tên\n3. Đổi thành 'Kế toán tổng hợp'\n4. Bấm 'Lưu'",
         "Tên mới: Kế toán tổng hợp",
         "- Toast 'Lưu thành công'\n- Danh sách cập nhật tên mới\n- Nút Lịch sử ghi lại thay đổi tên",
         "Ghi lịch sử khi sửa"),
        ("005", "Sửa trùng tên kỹ năng khác", "P1",
         "Có 'Kế toán' và 'Nhân sự'",
         "1. Sửa 'Kế toán', đổi tên thành 'Nhân sự'\n2. Bấm 'Lưu'",
         "Tên mới: Nhân sự",
         "- Báo lỗi 'Tên đã tồn tại'",
         "Tên không được trùng"),
        ("006", "Đóng popup không lưu", "P2",
         "Đang mở popup Thêm mới, đã gõ dở tên",
         "1. Bấm 'Đóng'",
         "—",
         "- Popup đóng, không tạo kỹ năng mới",
         "—"),
    ]),
    ("III", "KHÓA / MỞ KHÓA / XÓA / LỊCH SỬ", [
        ("001", "Khóa kỹ năng đang Hoạt động", "P0",
         "Kỹ năng 'Nhân sự' đang Hoạt động",
         "1. Bấm nút khóa ở cột Trạng thái dòng 'Nhân sự'\n2. Ở popup 'Xác nhận khóa' bấm 'Khóa'",
         "—",
         "- Toast 'Thao tác thành công'\n- Trạng thái chuyển 'Khóa'\n- Dòng đó mất nút Sửa/Lịch sử/Xóa",
         "—"),
        ("002", "Mở khóa kỹ năng đang Khóa", "P1",
         "Kỹ năng 'Nhân sự' đang Khóa",
         "1. Bấm nút mở khóa\n2. Ở popup 'Xác nhận mở khóa' bấm 'Mở khóa'",
         "—",
         "- Trạng thái về 'Hoạt động'\n- Nút Sửa/Lịch sử/Xóa hiện lại",
         "—"),
        ("003", "Xóa kỹ năng", "P0",
         "Kỹ năng 'Kỹ năng mềm' đang Hoạt động",
         "1. Bấm nút Xóa\n2. Popup 'Xác nhận xóa' hiện: Bạn có chắc muốn xóa kỹ năng \"Kỹ năng mềm\"?\n3. Bấm 'Xóa'",
         "—",
         "- Toast 'Xóa thành công'\n- Kỹ năng biến mất khỏi danh sách",
         "—"),
        ("004", "Hủy hộp thoại xóa", "P2",
         "Đang mở popup 'Xác nhận xóa'",
         "1. Bấm 'Hủy'",
         "—",
         "- Popup đóng, kỹ năng vẫn còn trong danh sách",
         "—"),
        ("005", "Xem lịch sử thay đổi", "P1",
         "Kỹ năng đã từng sửa tên ≥1 lần",
         "1. Bấm nút Lịch sử thay đổi\n2. Xem popup 'Lịch sử thay đổi'",
         "—",
         "- Bảng hiện: STT, Người cập nhật, Ngày cập nhật, Tên trường cập nhật, Giá trị cũ, Giá trị mới",
         "—"),
        ("006", "Lịch sử khi chưa sửa lần nào", "P2",
         "Kỹ năng vừa tạo, chưa sửa",
         "1. Bấm nút Lịch sử thay đổi",
         "—",
         "- Popup hiện 'Chưa có lịch sử'",
         "—"),
    ]),
    ("IV", "XUẤT EXCEL / IN", [
        ("001", "Xuất Excel theo bộ lọc", "P1",
         "Đang lọc từ khóa 'Lập trình'",
         "1. Bấm 'Xuất Excel'",
         "Từ khóa: Lập trình",
         "- Tải file danh_sach_ky_nang.xls chứa đúng kỹ năng đang lọc",
         "Xuất theo bộ lọc hiện tại"),
        ("002", "In danh sách", "P2",
         "Đang lọc Trạng thái = Hoạt động",
         "1. Bấm 'In'",
         "Trạng thái: Hoạt động",
         "- Mở tab mới hiển thị bản in danh sách đúng bộ lọc",
         "—"),
    ]),
    ("V", "LUỒNG XUYÊN SUỐT (E2E)", [
        ("001", "Vòng đời 1 kỹ năng", "P0",
         "Có quyền Quản lý kỹ năng",
         "1. Thêm mới 'Kỹ năng test'\n2. Sửa tên thành 'Kỹ năng test 2'\n3. Xem Lịch sử\n4. Khóa\n5. Mở khóa\n6. Xóa",
         "—",
         "- B1: tạo thành công, trạng thái Hoạt động\n- B2: đổi tên OK\n- B3: lịch sử hiện tên cũ→mới\n- B4: trạng thái Khóa, ẩn nút\n- B5: trạng thái Hoạt động\n- B6: xóa khỏi danh sách",
         "—"),
    ]),
]

build(
    output_file=r"d:\CompanyProject\hrm-cursor\.plans\elearning-quan-ly\danh-muc-ky-nang\testcase.xlsx",
    sheet_name="DanhMucKyNang",
    feature_name="Danh mục Kỹ năng",
    module_name="Kỹ năng",
    description_block=DESCRIPTION_BLOCK,
    sections=SECTIONS,
    role_tcs=ROLE_TCS,
)
