# -*- coding: utf-8 -*-
"""Testcase Luồng làm bài thi (elearning) — theo nhãn UI thật, cả 2 loại học viên."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from _tc_builder import build

DESCRIPTION_BLOCK = [
    ("1. Mục đích tính năng",
     "Luồng làm bài thi cho khóa đánh giá bằng bài thi. Học viên NGOÀI làm bài NGAY trong elearning (màn /khoa-hoc/:slug/thi → kết quả). Nhân viên NỘI BỘ bấm 'Làm đề thi' → chuyển sang HRM làm bài (deep-link, có link quay lại)."),
    ("2. Đối tượng được tính / hiển thị",
     "► Khối 'Đánh giá bằng bài thi' chỉ hiện khi khóa exam-mode + đã tham gia.\n► Học viên ngoài: chỉ áp dụng khi khóa CÔNG KHAI.\n► Kết quả: Đạt (1) / Chờ chấm (2) / Không đạt (3)."),
    ("3. Đối tượng bị ẩn / không tính",
     "► Khóa exam-mode KHÔNG công khai + học viên ngoài → bị chặn (banner 'chỉ dành cho nhân viên').\n► Hết lượt thi → ẩn nút 'Làm đề thi'.\n► Còn bài chờ chấm → không thi lượt mới."),
    ("4. Bộ lọc thời gian áp dụng cho",
     "Đề thi có thể có giới hạn thời gian (đồng hồ đếm ngược MM:SS); hết giờ tự nộp bài."),
    ("5. Cấu trúc dữ liệu / cây phân cấp",
     "Khối bài thi (chi tiết khóa) → nút 'Làm đề thi' → (HV ngoài: màn thi native → kết quả) / (nhân viên: deep-link HRM). Lịch sử thi = nhiều lượt."),
    ("6. Quy tắc cộng dồn / deduplicate",
     "Quy tắc điểm: highest (cao nhất) / last (lần cuối) / average (trung bình — phải thi đủ số lượt mới chốt). Đề chọn ngẫu nhiên 1 đề của khóa mỗi lượt."),
    ("7. Phân quyền cấp",
     "Không phân quyền cấp. Phân biệt học viên ngoài (thi native) vs nhân viên (thi HRM)."),
    ("8. Cách tính các ô thống kê",
     "'Lượt thi: {đã dùng}/{tối đa}'. eligible = đã tham gia && không chờ chấm && (không bắt buộc học trước HOẶC đã đạt ≥ % bài học yêu cầu). Đạt khi điểm ≥ ngưỡng."),
    ("9. Ghi chú đọc bảng",
     "Nút 'Làm đề thi' đi ĐÂU tùy vai trò: học viên ngoài → màn thi trong elearning; nhân viên → sang HRM. Khối bài thi mô tả nơi thi khác nhau theo vai trò."),
]

SECTIONS = [
    ("I", "KHỐI BÀI THI (CHI TIẾT KHÓA)", [
        ("001", "Hiện khối khi đã tham gia", "P0", "Khóa exam-mode, học viên đã tham gia",
         "1. Mở chi tiết khóa exam-mode", "—",
         "- Hiện khối 'Đánh giá bằng bài thi' + 'Lượt thi: {x}/{y}' + nút 'Làm đề thi'", "UC-01"),
        ("002", "Text nơi thi — học viên ngoài", "P1", "Học viên ngoài, khóa exam-mode công khai, đã tham gia",
         "1. Xem khối bài thi", "—",
         "- Dòng 'Bạn làm bài thi trực tiếp trên hệ thống học trực tuyến.'", "Phân biệt vai trò"),
        ("003", "Text nơi thi — nhân viên", "P1", "Nhân viên, khóa exam-mode, đã tham gia",
         "1. Xem khối bài thi", "—",
         "- Dòng 'Bài thi sẽ thực hiện ở phân hệ Đào tạo (HRM).'", "Phân biệt vai trò"),
        ("004", "Học viên ngoài + khóa KHÔNG công khai → chặn", "P0", "Học viên ngoài, khóa exam-mode không công khai",
         "1. Mở chi tiết khóa", "—",
         "- Banner 'Khoá học này hoàn thành bằng bài thi trên hệ thống nội bộ — chỉ dành cho nhân viên, không áp dụng cho học viên ngoài.'\n- Không có nút hành động", "BR-02"),
        ("005", "Chưa đủ % bài học để thi", "P0", "participation bắt buộc, chưa đạt % bài học",
         "1. Xem nút 'Làm đề thi'", "—",
         "- Nút 'Làm đề thi' mờ/vô hiệu + 'Cần hoàn thành ≥ {X}% bài học để được thi.'", "BR-03"),
        ("006", "Còn bài chờ chấm → không thi tiếp", "P1", "Có lượt tự luận đang chờ chấm",
         "1. Xem khối bài thi", "—",
         "- 'Đang chờ chấm bài thi — chờ có kết quả mới thi tiếp được.'; nút thi vô hiệu", "BR-04"),
        ("007", "Hết lượt → ẩn nút", "P1", "attempts_used = attempt_limit",
         "1. Xem khối bài thi", "—",
         "- KHÔNG còn nút 'Làm đề thi' (đã hết lượt)", "BR-05"),
        ("008", "Rule average — điểm tạm tính", "P2", "score_rule=average, còn lượt",
         "1. Xem khối bài thi", "—",
         "- 'Điểm TB tạm tính: {X}% • Còn {n} lượt (cần ≥ {pass_percent}% để đạt)' + 'Phải thi đủ {y} lượt mới chốt kết quả.'", "BR-08"),
    ]),
    ("II", "HỌC VIÊN NGOÀI — THI NATIVE", [
        ("001", "Vào màn thi", "P0", "Học viên ngoài đủ điều kiện",
         "1. Bấm 'Làm đề thi'", "—",
         "- Mở màn thi /khoa-hoc/:slug/thi (KHÔNG chuyển sang HRM)\n- Loading 'Đang tải đề thi…' rồi hiện đề", "BR-06"),
        ("002", "Đồng hồ đếm ngược", "P1", "Đề có giới hạn thời gian",
         "1. Quan sát header màn thi", "—",
         "- Có đồng hồ MM:SS đếm ngược", "BR-07"),
        ("003", "Trả lời các loại câu hỏi", "P0", "Đề có nhiều loại câu",
         "1. Chọn 1 (radio) / chọn nhiều (checkbox) / gõ tự luận / điền từ vào 'Chỗ trống {i}'", "—",
         "- Ghi nhận đáp án theo từng loại", "—"),
        ("004", "Nộp bài", "P0", "Đang làm bài",
         "1. Bấm 'Nộp bài'\n2. Modal 'Bạn chắc chắn nộp bài thi?' → bấm 'Nộp'", "—",
         "- Nộp thành công → mở màn kết quả", "—"),
        ("005", "Hết giờ tự nộp", "P1", "Đề có giới hạn thời gian, để chạy hết giờ",
         "1. Không nộp, chờ đồng hồ về 0", "—",
         "- Bài tự động nộp, chuyển màn kết quả", "BR-07"),
        ("006", "Cảnh báo rời trang chưa nộp", "P2", "Đang làm bài",
         "1. Bấm Back / đóng tab", "—",
         "- Cảnh báo 'Bạn đang làm bài thi. Rời trang sẽ mất bài chưa nộp. Tiếp tục?'", "BR-07"),
        ("007", "Vào màn thi khi không đủ điều kiện", "P2", "Chưa đủ điều kiện (mở URL trực tiếp)",
         "1. Mở /khoa-hoc/:slug/thi", "—",
         "- Toast lỗi (VD 'Không đủ điều kiện thi') + quay lại màn học", "—"),
    ]),
    ("III", "NHÂN VIÊN — THI TRÊN HRM", [
        ("001", "Làm đề thi deep-link HRM", "P0", "Nhân viên đủ điều kiện",
         "1. Bấm 'Làm đề thi'", "—",
         "- Chuyển sang HRM (/training/subjects/{id}/exams/{examId}/todo) kèm link quay lại elearning", "BR-06"),
        ("002", "Quay lại elearning sau thi", "P1", "Nhân viên vừa làm bài trên HRM",
         "1. Hoàn tất trên HRM → theo link quay lại", "—",
         "- Về đúng trang khóa học elearning; khối bài thi cập nhật điểm/kết quả/lượt", "—"),
    ]),
    ("IV", "KẾT QUẢ THI", [
        ("001", "Kết quả ĐẠT", "P0", "Điểm ≥ ngưỡng",
         "1. Nộp bài đạt", "—",
         "- 'Chúc mừng, bạn đã ĐẠT!' + 'Điểm: {score}' + nút 'Về khoá học' + 'Xem chứng chỉ'", "BR-09"),
        ("002", "Kết quả KHÔNG ĐẠT", "P0", "Điểm < ngưỡng",
         "1. Nộp bài không đạt", "—",
         "- 'Chưa đạt' + 'Điểm: {score}' + nút 'Về khoá học'", "BR-09"),
        ("003", "Chờ chấm tự luận", "P0", "Bài có câu tự luận",
         "1. Nộp bài có tự luận", "—",
         "- 'Bài thi đang chờ chấm' + 'Bài có câu tự luận, giảng viên sẽ chấm và cập nhật kết quả sau.'", "BR-04,BR-09"),
        ("004", "Đã nộp (average còn lượt)", "P1", "score_rule=average, chưa hết lượt",
         "1. Nộp 1 lượt", "—",
         "- 'Đã nộp bài' + 'Điểm bài này: {score}. Kết quả cuối cùng tính khi bạn dùng hết số lượt thi.'", "BR-08"),
    ]),
    ("V", "LỊCH SỬ THI & NHẮC THI", [
        ("001", "Xem lịch sử thi", "P1", "Đã thi ≥1 lượt",
         "1. Bấm 'Lịch sử thi ({n})'", "—",
         "- Popup 'Lịch sử thi' cột Lần/Thời gian/Đề thi/Điểm/Kết quả (Đạt/Không đạt/Chờ chấm)", "UC-05"),
        ("002", "Nhắc thi ở màn học", "P0", "Đủ điều kiện, đang học trong khóa exam-mode",
         "1. Hoàn thành đủ nội dung học", "—",
         "- Modal 'Sẵn sàng làm bài thi!'; học viên ngoài 'Bạn đã đủ điều kiện làm bài thi.' / nhân viên '…trên hệ thống Đào tạo (HRM).'; nút 'Làm đề thi'/'Để sau'", "UC-06"),
        ("003", "Bấm Làm đề thi từ nhắc thi (HV ngoài)", "P1", "Học viên ngoài, modal nhắc thi",
         "1. Bấm 'Làm đề thi' trên modal", "—",
         "- Mở màn thi native trong elearning", "BR-06"),
    ]),
    ("VI", "LUỒNG XUYÊN SUỐT (E2E)", [
        ("001", "HV ngoài: học → đủ điều kiện → thi → đạt → chứng chỉ", "P0", "Học viên ngoài, khóa exam-mode công khai có chứng chỉ",
         "1. Học đủ % bài học yêu cầu\n2. Bấm 'Làm đề thi' → làm → nộp\n3. Đạt → 'Xem chứng chỉ'", "—",
         "- Đủ điều kiện thi; nộp đạt; khóa hoàn thành; xem được chứng chỉ", "—"),
        ("002", "Nhân viên: học → thi HRM → quay lại", "P0", "Nhân viên, khóa exam-mode",
         "1. Học đủ % bài\n2. 'Làm đề thi' → sang HRM làm\n3. Quay lại elearning", "—",
         "- Sang HRM đúng đề; quay lại cập nhật kết quả", "—"),
    ]),
]

build(
    output_file=r"d:\CompanyProject\hrm-cursor\.plans\elearning-hoc-vien\lam-bai-thi\testcase.xlsx",
    sheet_name="LamBaiThi", feature_name="Luồng làm bài thi khóa học", module_name="Làm bài thi",
    description_block=DESCRIPTION_BLOCK, sections=SECTIONS, role_tcs=None,
)
