import sys; sys.path.insert(0, '/Users/manhcuong/Desktop/dns/HRM/.plans/gop-db/bao-cao-docs')
from _shoot import browser_page, clip, BASE
S = 'shots/'
STEP = sys.argv[1] if len(sys.argv) > 1 else 'all'
def goto_list(page):
    page.goto(BASE + '/assign/tasks', wait_until='domcontentloaded')
    page.wait_for_selector('text=TPE.TASK.NB.26.0986', timeout=180000)
    page.wait_for_timeout(2000)
def scroll_table(page, x):
    page.evaluate("x => document.querySelectorAll('.table-wrapper').forEach(e => e.scrollLeft = x)", x)
    page.wait_for_timeout(500)
def row_action(page, code, title):
    scroll_table(page, 5000)
    page.locator('tr', has_text=code).first.locator('span[title="%s"] button' % title).first.click()
    page.wait_for_timeout(4500)
def modal_scroll(page, y):
    page.evaluate("y => document.querySelectorAll('.modal.show .modal-scrollable-content, .modal.show .modal-content-wrapper, .modal.show .modal-body').forEach(e => e.scrollTop = y)", y)
    page.wait_for_timeout(700)
def picker(page, label):
    fs = page.locator('.modal.show fieldset').filter(has=page.locator('legend', has_text=label)).first
    fs.locator('.sp-input').first.click(); page.wait_for_timeout(1000)
def esc(page):
    page.keyboard.press('Escape'); page.wait_for_timeout(1500)

with browser_page() as page:
    goto_list(page)
    if STEP in ('all', 'create'):
        page.get_by_role('button', name='Tạo mới').click(); page.wait_for_timeout(4000)
        page.screenshot(path=S + '05-tao-moi-trong.png')
        page.locator('.modal.show button', has_text='Lưu').first.click(); page.wait_for_timeout(3000)
        page.screenshot(path=S + '05c-tao-moi-loi.png')
        page.get_by_placeholder('VD: Thiết kế popup tạo nhiệm vụ').fill('Lập kế hoạch bảo trì thiết bị xưởng 3S Hyundai An Khánh')
        page.get_by_placeholder('Mô tả ngắn gọn yêu cầu…').fill('Lập kế hoạch bảo trì định kỳ quý IV cho cầu nâng, máy nén khí.')
        page.get_by_placeholder('VD: 8.0').fill('4')
        page.wait_for_timeout(500)
        page.screenshot(path=S + '05-tao-moi.png')
        clip(page, page.locator('.modal.show button', has_text='Chế độ nâng cao').first, S + 'icon_nangcao.png')
        clip(page, page.locator('.modal.show button', has_text='Lưu & Tiếp tục').first, S + 'icon_luutieptuc.png')
        clip(page, page.locator('.modal.show button', has_text='Xóa trắng').first, S + 'icon_xoatrang.png')
        page.locator('.modal.show button', has_text='Chế độ nâng cao').first.click(); page.wait_for_timeout(1500)
        page.get_by_placeholder('Nhập mục checklist và Enter').fill('Kiểm tra dầu thuỷ lực cầu nâng')
        page.keyboard.press('Enter'); page.wait_for_timeout(300)
        page.get_by_placeholder('Nhập mục checklist và Enter').fill('Vệ sinh lọc gió máy nén khí')
        page.keyboard.press('Enter'); page.wait_for_timeout(300)
        page.get_by_placeholder('Nhập thẻ và Enter').fill('Bảo trì'); page.keyboard.press('Enter')
        page.wait_for_timeout(500)
        page.screenshot(path=S + '06-nang-cao-1.png')
        page.locator('.modal.show button', has_text='Thêm tài liệu').first.click(); page.wait_for_timeout(500)
        modal_scroll(page, 700); page.screenshot(path=S + '06-nang-cao-2.png')
        modal_scroll(page, 0)
        page.locator('.modal.show label', has_text='Lặp lại').first.click(); page.wait_for_timeout(400)
        page.locator('.modal.show label', has_text='Yêu cầu báo cáo tiến độ?').first.click(); page.wait_for_timeout(800)
        modal_scroll(page, 300); page.screenshot(path=S + '06-nang-cao-3.png')
        modal_scroll(page, 0)
        page.locator('.modal.show button', has_text='Liên kết & KPI').first.click(); page.wait_for_timeout(800)
        page.screenshot(path=S + '06-nang-cao-4.png')
        esc(page)
    if STEP in ('all', 'edit'):
        row_action(page, 'TPE.TASK.NB.26.0977', 'Sửa')
        page.screenshot(path=S + '07-sua.png')
        picker(page, 'Trạng thái'); page.screenshot(path=S + '07b-sua-trang-thai.png')
        esc(page); esc(page)
    if STEP in ('all', 'view'):
        goto_list(page)
        page.locator('button.v2-cell-link', has_text='TPE.TASK.NB.26.0977').first.click(); page.wait_for_timeout(5000)
        page.screenshot(path=S + '08-xem.png')
        modal_scroll(page, 5000); page.screenshot(path=S + '08b-xem-cuoi.png')
        esc(page)
        page.locator('button.v2-cell-link', has_text='TPE.TASK.NB.26.0978').first.click(); page.wait_for_timeout(5000)
        page.screenshot(path=S + '08c-xem-ket-qua.png')
        esc(page)
    if STEP in ('all', 'delete'):
        goto_list(page)
        row_action(page, 'TPE.TASK.NB.26.0977', 'Xóa')
        page.screenshot(path=S + '09-xoa.png')
        page.locator('.modal.show button', has_text='Hủy').first.click(); page.wait_for_timeout(1000)
    if STEP in ('all', 'approve_start'):
        goto_list(page)
        row_action(page, 'TPE.TASK.NB.26.0981', 'Duyệt')
        page.screenshot(path=S + '10-duyet-trien-khai.png')
        picker(page, 'Trạng thái'); page.screenshot(path=S + '10b-duyet-trien-khai-tt.png')
        esc(page); esc(page)
    if STEP in ('all', 'result'):
        goto_list(page)
        row_action(page, 'TPE.TASK.NB.26.0978', 'Nhập kết quả')
        picker(page, 'Trạng thái'); page.screenshot(path=S + '11b-nhap-kq-tt.png')
        page.locator('#import-result-modal h5').first.click(); page.wait_for_timeout(600)
        page.get_by_placeholder('VD: 6.5').fill('6')
        page.get_by_placeholder('0..100').first.fill('60')
        page.get_by_placeholder('Nhập kết quả thực hiện…').fill('Đã hoàn thành phần quy trình vận hành an toàn, đang bổ sung ảnh minh hoạ.')
        page.screenshot(path=S + '11-nhap-kq.png')
        modal_scroll(page, 520); page.screenshot(path=S + '11c-nhap-kq-checklist.png')
        page.locator('#import-result-modal button', has_text='File kết quả thực hiện').first.click(); page.wait_for_timeout(500)
        page.locator('#import-result-modal button', has_text='Thêm dòng').first.click(); page.wait_for_timeout(500)
        modal_scroll(page, 900); page.screenshot(path=S + '11e-nhap-kq-file.png')
        esc(page)
        goto_list(page)
        row_action(page, 'TPE.TASK.NB.26.0980', 'Nhập kết quả')
        modal_scroll(page, 250); page.screenshot(path=S + '11d-nhat-ky.png')
        esc(page)
    if STEP in ('all', 'approve_result'):
        goto_list(page)
        row_action(page, 'TPE.TASK.NB.26.0979', 'Duyệt')
        page.screenshot(path=S + '12-duyet-kq.png')
        picker(page, 'Trạng thái'); page.screenshot(path=S + '12b-duyet-kq-tt.png')
        page.locator('#import-result-modal h5').first.click(); page.wait_for_timeout(600)
        modal_scroll(page, 5000); page.screenshot(path=S + '12c-duyet-kq-cuoi.png')
        esc(page)
    if STEP in ('all', 'history'):
        goto_list(page)
        row_action(page, 'TPE.TASK.NB.26.0980', 'Lịch sử')
        page.wait_for_timeout(2000)
        page.screenshot(path=S + '15-lich-su.png')
        esc(page)

    if STEP == 'comment':
        goto_list(page)
        page.locator('button.v2-cell-link', has_text='TPE.TASK.NB.26.0978').first.click(); page.wait_for_timeout(5000)
        modal_scroll(page, 5000)
        ed = page.locator('#import-result-modal .cmt-compose [contenteditable="true"]').first
        ed.click(); page.keyboard.type('Anh Sơn gửi giúp em catalogue cầu nâng bản tiếng Việt để đưa vào tài liệu nhé.')
        page.wait_for_timeout(500)
        page.locator('#import-result-modal .cmt-compose button', has_text='Gửi').first.click(); page.wait_for_timeout(3000)
        modal_scroll(page, 5000); page.screenshot(path=S + '13-binh-luan.png')
        esc(page)
