"""Generate testcase Excel TỔNG THỂ cho màn Quản lý báo giá (/assign/quotations)."""
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
import _tc_builder
from _tc_builder import build

_tc_builder.ROMAN = ["I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X",
                     "XI", "XII", "XIII", "XIV", "XV", "XVI", "XVII", "XVIII"]


def load_eic_sections():
    """Nạp lại các section Export / Import / Sao chép đã viết ở
    `.plans/baogia-copy-export-import/testcase-export-import-copy-generate.py`
    để 2 file testcase tổng thể chứa TRỌN VẸN nội dung đó (không phải trỏ sang file khác).
    Tạm vô hiệu build() để import module không ghi file."""
    import importlib.util
    real_build = _tc_builder.build
    _tc_builder.build = lambda *a, **k: None
    try:
        path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..',
                            'baogia-copy-export-import', 'testcase-export-import-copy-generate.py')
        spec = importlib.util.spec_from_file_location('eic_src', path)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        return mod
    finally:
        _tc_builder.build = real_build


EIC = load_eic_sections()
# Module nguồn cũng gán lại ROMAN khi import → đặt lại cho đủ số section của file này
_tc_builder.ROMAN = ["I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X",
                     "XI", "XII", "XIII", "XIV", "XV", "XVI", "XVII", "XVIII"]


def pick(section, idx_1based):
    """Lấy đúng các TC theo số thứ tự khai báo trong section nguồn."""
    return [section[2][i - 1] for i in idx_1based]

OUTPUT_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "testcase-bao-gia.xlsx")
SHEET_NAME = "BaoGia"
FEATURE_NAME = "Quản lý báo giá (QLDA TKT) — toàn bộ chức năng"
MODULE_NAME = "Báo giá"

DESCRIPTION_BLOCK = [
    ("1. Mục đích tính năng",
     "Kiểm thử TOÀN BỘ chức năng màn Quản lý báo giá `/assign/quotations`: danh sách + bộ lọc, 3 luồng tạo báo giá "
     "(từ Yêu cầu xây dựng giá / tự lập / từ BOM tổng hợp đã duyệt), form thông tin chung, lưới hàng hoá (nhóm 2 cấp, cha-con, hàng ERP, hàng tạm), "
     "dịch vụ & chi phí khác, chi phí vận chuyển, giá - VAT - giảm giá (3 loại), tổng hợp giá trị, gửi duyệt & luồng phê duyệt (tự duyệt / TP / BGĐ / từ chối), "
     "chốt trúng thầu - hủy chốt, ghi chú kinh doanh, đồng bộ ERP, đồng bộ hàng tạm, in ấn, xoá, lịch sử, "
     "nhóm hàng 2 cấp + kéo-thả, và TRỌN BỘ Export / Import / Sao chép báo giá (section XI–XVI).\n"
     "► File này là bộ testcase ĐẦY ĐỦ của màn Báo giá — không cần tham chiếu file nào khác. Phần BOM Giải pháp nằm ở `testcase-bom-list.xlsx`."),

    ("2. Đối tượng được tính / hiển thị",
     "► Màn danh sách mặc định hiển thị 'Báo giá của tôi' (do người đăng nhập tạo), lọc thêm theo Dự án / Giải pháp / Version / Khách hàng / Trạng thái / Cấp duyệt / Người duyệt / Khoảng ngày tạo.\n"
     "► 7 trạng thái báo giá: 1 Đang tạo · 2 Chờ TP duyệt · 3 Chờ BGĐ duyệt · 4 Đã duyệt · 5 Đóng · 6 Dừng · 7 Trúng thầu.\n"
     "► 3 cấp duyệt: Cấp 1 (tự duyệt) · Cấp 2 (TP duyệt) · Cấp 3 (TP duyệt & chuyển BGĐ → BGĐ duyệt).\n"
     "► 2 loại báo giá: kế thừa BOM (type = 1, cấu trúc khoá) và tự lập/độc lập (type = 2, tự dựng cấu trúc).\n"
     "► Màn 'Chờ duyệt' `/assign/quotations/pending-approval`: chỉ người có quyền TP hoặc BGĐ duyệt giá mới vào được."),

    ("3. Đối tượng bị ẩn / không tính",
     "► Cột giá vốn (Đơn giá nhập / Thành tiền nhập / Tỷ suất lợi nhuận) ẩn theo TỪNG DÒNG: canSee = có quyền 'Xem giá vốn hàng hoá' HOẶC (dòng là hàng tạm VÀ người xem là người tạo báo giá).\n"
     "► Nút Sửa / Xoá / Import chỉ hiện khi: trạng thái Đang tạo VÀ người đăng nhập là người tạo báo giá.\n"
     "► Nút Duyệt/Từ chối chỉ hiện đúng cấp đang chờ (TP thấy khi Chờ TP duyệt, BGĐ thấy khi Chờ BGĐ duyệt).\n"
     "► Báo giá kế thừa BOM: KHÔNG có nút 'Thêm nhóm' / 'Thêm mới' / cột Thao tác trên lưới hàng hoá — cấu trúc kế thừa từ BOM, chỉ sửa giá.\n"
     "► Cột 'Bảng giá' và 'Loại tiền tệ' chỉ đổi được ở trạng thái Đang tạo."),

    ("4. Bộ lọc thời gian áp dụng cho",
     "► Danh sách: bộ lọc 'Ngày tạo từ' / 'đến' áp lên cột created_at của báo giá (bao gồm cả 2 đầu mút).\n"
     "► Hiệu lực báo giá (validity_date): TÍNH LẠI tại thời điểm Gửi duyệt (và khi sao chép), theo ngày hiệu lực giá ERP của hàng hoá và cấu hình dự án — lấy mốc đến TRƯỚC.\n"
     "► Tỷ giá ngoại tệ: lấy theo ERP tại thời điểm tạo/sao chép báo giá."),

    ("5. Cấu trúc dữ liệu / cây phân cấp",
     "► NHÓM HÀNG 2 CẤP: Cấp 1 đánh số La Mã (I, II); Cấp 2 nhãn I.1 / I.2, thụt lề. Nhóm Cấp 2 không tạo được nhóm cấp 3. Sản phẩm gắn vào nhóm LÁ.\n"
     "► HÀNG HOÁ 2 CẤP: dòng cha (cụm thiết bị) — dòng con (vật tư thành phần). Dòng cha có con thì tiền của cha roll-up từ con.\n"
     "► Kéo-thả đổi thứ tự: nhóm chỉ đổi trong cùng cấp cùng cha; hàng hoá đổi trong cùng nhóm. Handle nhóm và handle hàng hoá tách riêng.\n"
     "► Dịch vụ & chi phí khác lưu riêng (quotation_service_items), không có cấp con.\n"
     "► Chi phí vận chuyển KHÔNG phải dòng hàng hoá — là 5 trường ở cấp phiếu (giá bán / giá nhập / VAT / giảm giá / phân bổ GG)."),

    ("6. Quy tắc cộng dồn / deduplicate",
     "► Dòng CHA CÓ CON: giá trị của cha = tổng roll-up từ các con (không cộng trùng cả cha lẫn con). Dòng cha KHÔNG có con thì tính theo chính nó.\n"
     "► Tổng giá nhập (giá vốn) = Σ(giá nhập × SL) các dòng tính tiền + Σ dịch vụ + giá nhập vận chuyển.\n"
     "► Ràng buộc giá cha-con: Đơn giá bán của cha ≥ Σ giá bán các con; giá nhập của cha ≥ Σ giá nhập các con (chỉ áp cho hàng tự xây).\n"
     "► Mã hàng tạm tự sinh HHBG+id: mã đã tồn tại trong 'Hàng hoá dự án' CỦA CHÍNH DỰ ÁN đó → giữ; khác dự án → sinh mã mới.\n"
     "► Giảm giá tổng phân bổ về từng dòng theo tỷ trọng thành tiền (allocate-discount); tổng phân bổ = tổng giảm giá."),

    ("7. Phân quyền cấp",
     "• 'Xây dựng giá bán theo công ty' — tạo/sao chép báo giá từ YCBG khi dự án KHÔNG triển khai theo phòng.\n"
     "• 'Xây dựng giá bán theo phòng' — tạo/sao chép báo giá từ YCBG khi dự án triển khai theo phòng (phải cùng phòng).\n"
     "• 'Trưởng phòng duyệt giá Bom giải pháp' — vào màn Chờ duyệt, Duyệt cấp TP, Từ chối.\n"
     "• 'Ban giám đốc duyệt giá Bom giải pháp' — vào màn Chờ duyệt, BGĐ duyệt, Từ chối.\n"
     "• 'Xem giá vốn hàng hoá' — xem giá nhập / thành tiền nhập / tỷ suất lợi nhuận; bắt buộc khi chọn hàng ERP làm hàng con.\n"
     "• Vai trò dữ liệu (không phải permission): người TẠO báo giá (sửa/xoá/import/gửi duyệt), Sale phụ trách dự án (tạo báo giá tự lập, sửa ghi chú kinh doanh).\n"
     "⚠️ Quyền được kiểm tra qua ROLE (role_has_permissions), không qua quyền gán trực tiếp cho nhân viên."),

    ("8. Cách tính các ô thống kê",
     "► Ô 'Thành tiền bán' (1 dòng) = Đơn giá sau GG × Số lượng.\n"
     "► Ô 'Đơn giá sau GG' = Đơn giá bán − GG(đ) [nếu GG(đ) > 0] hoặc Đơn giá bán × (1 − GG(%)/100) [GG mặt hàng]; = Đơn giá bán − Phân bổ GG/SL [GG tổng]; = Đơn giá bán [không GG].\n"
     "► Ô 'Giá trị VAT' = Thành tiền bán × VAT%/100 · Ô 'Thành tiền sau VAT' = Thành tiền bán + Giá trị VAT.\n"
     "► Ô 'Tổng giá trị sau VAT' (danh sách + tổng hợp) = Σ thành tiền sau VAT của hàng hoá + dịch vụ + chi phí vận chuyển.\n"
     "► Ô 'Tỷ suất lợi nhuận' = (Tổng giá bán sau giảm giá − Tổng giá vốn) / Tổng giá bán sau giảm giá × 100%.\n"
     "► 'Cấp duyệt' = mức cao hơn giữa (cấp theo GIÁ TRỊ đơn hàng) và (cấp theo TỶ SUẤT LỢI NHUẬN) — tra bảng Cấu hình duyệt giá BOM."),

    ("9. Ghi chú đọc bảng",
     "► Mọi thao tác trên lưới hàng hoá chỉ ghi xuống DB khi bấm 'Lưu nháp' / 'Lưu báo giá'. TC nào sửa lưới đều phải kiểm tra lại sau khi Lưu + tải lại trang.\n"
     "► Gửi duyệt Cấp 1 → hệ thống cho TỰ DUYỆT (không qua TP); Cấp 2 → Chờ TP duyệt; Cấp 3 → TP duyệt rồi chuyển BGĐ.\n"
     "► Từ chối → báo giá quay lại Đang tạo, xoá cấp duyệt, lưu lý do từ chối.\n"
     "► Testcase viết theo LOGIC CODE MỚI NHẤT; chỗ nào code lệch tài liệu đã ghi rõ ở cột 'Giải thích nghiệp vụ'.\n"
     "► Section XI–XVI (nhóm 2 cấp, export, import, sao chép, round-trip) là phần ĐÃ GỘP vào file này — không cần mở file testcase nào khác."),
]

S1 = ("I", "PHÂN QUYỀN & PHẠM VI DỮ LIỆU", [
 ("", "Truy cập màn danh sách báo giá", "P0",
  "User A đã đăng nhập, đã tạo 3 báo giá; user B đã tạo 2 báo giá khác",
  "1. Đăng nhập A → vào menu QLDA TKT → Quản lý báo giá\n2. Đếm số dòng và người tạo từng dòng",
  "A có 3 BG, B có 2 BG",
  "- Vào được màn hình, tiêu đề 'Danh sách báo giá', mô tả 'Báo giá do tôi tạo'\n- Chỉ thấy 3 báo giá của A, không thấy báo giá của B",
  "Danh sách mặc định lọc theo người tạo"),
 ("", "Tạo báo giá từ Yêu cầu xây dựng giá — dự án theo PHÒNG", "P0",
  "YCBG-01 thuộc dự án triển khai theo phòng = Phòng Kỹ thuật, trạng thái chờ xây dựng giá",
  "1. Đăng nhập user P1 (Phòng Kỹ thuật, có quyền 'Xây dựng giá bán theo phòng') → tiếp nhận YCBG-01 → tạo báo giá\n"
  "2. Đăng nhập user P2 (phòng khác, cùng quyền) → thử tiếp nhận YCBG-01",
  "P1 đúng phòng, P2 khác phòng",
  "- P1: tạo được báo giá\n- P2: bị chặn với thông báo 'Yêu cầu xây dựng giá này không thuộc phòng ban của bạn.'",
  "Gate BY_DEPT: quyền theo phòng + cùng phòng"),
 ("", "Tạo báo giá từ YCBG — dự án KHÔNG theo phòng cần quyền theo công ty", "P0",
  "YCBG-02 thuộc dự án implementation_type ≠ theo phòng",
  "1. User có quyền 'Xây dựng giá bán theo công ty' → tạo báo giá từ YCBG-02\n2. User KHÔNG có quyền đó → thử tạo",
  "—",
  "- Có quyền: tạo được\n- Không quyền: chặn với 'Bạn không có quyền xây dựng giá bán theo công ty.'",
  "Gate theo công ty"),
 ("", "Tạo báo giá TỰ LẬP — chỉ Sale phụ trách dự án", "P0",
  "Dự án DA-01 có Sale phụ trách = nhân viên X",
  "1. Đăng nhập X → Tạo báo giá → chọn dự án DA-01 → Lưu nháp\n2. Đăng nhập Y (không phải Sale phụ trách) → làm tương tự",
  "—",
  "- X: lưu được\n- Y: bị chặn 'Bạn không phải Sale phụ trách dự án này'",
  "BG tự lập gate theo main_sale_employee_id"),
 ("", "Chỉ người tạo mới sửa được báo giá", "P0",
  "BG-01 trạng thái Đang tạo, người tạo = X",
  "1. Đăng nhập Y → mở BG-01 → quan sát nút Sửa\n2. Gọi thẳng URL màn Sửa / API cập nhật",
  "—",
  "- Không có nút 'Sửa / Làm giá' và 'Xoá'\n- Gọi thẳng API bị chặn 'Chỉ người tạo báo giá mới có thể sửa.'",
  "ensureEditableByCreator"),
 ("", "Không sửa được báo giá khác trạng thái Đang tạo", "P0",
  "BG-02 trạng thái Chờ TP duyệt, người đăng nhập là người tạo",
  "1. Mở BG-02 → quan sát nút Sửa\n2. Gọi thẳng API cập nhật",
  "—",
  "- Không có nút Sửa/Xoá\n- API trả lỗi 'Báo giá không ở trạng thái Đang tạo, không thể sửa.'",
  "Khoá sửa sau khi gửi duyệt"),
 ("", "Màn 'Chờ duyệt' chặn user không có quyền duyệt", "P0",
  "User Z không có quyền TP/BGĐ duyệt giá",
  "1. Đăng nhập Z → mở URL /assign/quotations/pending-approval",
  "—",
  "- Bị chặn (403 / không có menu), không thấy dữ liệu báo giá chờ duyệt",
  "Route gắn checkPermission TP|BGĐ"),
 ("", "TP chỉ duyệt báo giá thuộc phòng mình quản lý", "P0",
  "BG-03 (Chờ TP duyệt) thuộc phòng Kỹ thuật. TP1 quản lý phòng Kỹ thuật; TP2 quản lý phòng khác",
  "1. TP1 mở màn Chờ duyệt → tìm BG-03 → Duyệt\n2. TP2 mở màn Chờ duyệt → tìm BG-03",
  "—",
  "- TP1: thấy và duyệt được\n- TP2: không thấy BG-03 trong danh sách; nếu gọi API thì bị chặn 'Bạn không quản lý phòng ban của báo giá này.'",
  "Phạm vi duyệt của TP theo phòng quản lý"),
 ("", "BGĐ duyệt theo phạm vi công ty", "P1",
  "BG-04 (Chờ BGĐ duyệt) thuộc công ty C1. BGĐ1 thuộc C1; BGĐ2 thuộc công ty C2",
  "1. BGĐ1 mở màn Chờ duyệt → duyệt BG-04\n2. BGĐ2 thử duyệt BG-04",
  "—",
  "- BGĐ1: duyệt được\n- BGĐ2: bị chặn 'Bạn không thuộc công ty của báo giá này.'",
  "Phạm vi duyệt BGĐ theo công ty"),
 ("", "Không có quyền 'Xem giá vốn hàng hoá' — ẩn cột giá vốn trên màn xem/sửa", "P0",
  "BG-05 có 1 hàng ERP (giá nhập 500.000) và 1 hàng tạm (giá nhập 300.000). User = người tạo, KHÔNG có quyền giá vốn",
  "1. Mở BG-05 màn Xem → xem cột Đơn giá nhập / TSLN của 2 dòng\n2. Mở màn Sửa → xem tương tự",
  "—",
  "- Dòng ERP: cột giá vốn hiển thị '—' / bị ẩn\n- Dòng hàng tạm: hiện đủ 300.000 (vì là người tạo)\n- Ô Tổng giá vốn / TSLN ẩn tương ứng",
  "canSeePrice = canViewCost || (!isErp && isCreator)"),
 ("", "Không có quyền giá vốn — không được chọn hàng ERP làm hàng con", "P1",
  "BG-05 (tự lập, Đang tạo). User = người tạo, không có quyền 'Xem giá vốn hàng hoá'",
  "1. Trên 1 dòng cha, bấm 'Thêm con' → chọn 1 hàng hoá ERP → Lưu",
  "—",
  "- Bị chặn với thông báo 'Bạn không có quyền \"Xem giá vốn hàng hoá\" nên không thể chọn hàng ERP làm hàng con.'",
  "Chặn rò giá vốn ERP qua đường hàng con"),
 ("", "Ghi chú kinh doanh chỉ Sale phụ trách dự án được sửa", "P1",
  "BG-06 trạng thái Đã duyệt, dự án có Sale phụ trách = X",
  "1. Đăng nhập X → mở BG-06 → nhập 'Ghi chú kinh doanh' → Lưu ghi chú\n2. Đăng nhập Y → thử sửa ghi chú",
  "—",
  "- X: lưu được, nội dung hiện lại sau khi tải lại\n- Y: bị chặn 'Chỉ NV Kinh doanh phụ trách dự án mới có thể cập nhật ghi chú.'",
  "updateSalesNote gate theo Sale phụ trách"),
 ("", "Ghi chú kinh doanh chỉ sửa được khi báo giá ĐÃ DUYỆT", "P1",
  "BG-07 trạng thái Đang tạo, user là Sale phụ trách",
  "1. Mở BG-07 → thử nhập và lưu ghi chú kinh doanh",
  "—",
  "- Bị chặn 'Chỉ có thể sửa ghi chú khi báo giá đã duyệt.'",
  "Ràng buộc trạng thái của ghi chú KD"),
])

S2 = ("II", "DANH SÁCH — HIỂN THỊ, LỌC, TÌM KIẾM, CẤU HÌNH CỘT", [
 ("", "Hiển thị đủ cột mặc định của bảng danh sách", "P0",
  "User có ít nhất 3 báo giá ở các trạng thái khác nhau",
  "1. Mở /assign/quotations\n2. Đọc header bảng",
  "—",
  "- Có các cột: STT, Mã BG • BOM, Loại, Dự án TKT, Khách hàng, Tiền tệ, Tổng giá trị sau VAT, Người tạo, Ngày tạo, Cấp duyệt, Người duyệt, Ngày duyệt, Trạng thái, ERP, Thao tác",
  "Bộ cột chuẩn màn danh sách"),
 ("", "Badge trạng thái đúng màu và đúng tên", "P0",
  "Có báo giá ở đủ 7 trạng thái",
  "1. Mở danh sách, bỏ lọc trạng thái\n2. Đối chiếu badge từng dòng",
  "7 trạng thái",
  "- Hiển thị đúng nhãn: Đang tạo / Chờ TP duyệt / Chờ BGĐ duyệt / Đã duyệt / Đóng / Dừng / Trúng thầu\n- Mỗi trạng thái 1 màu badge riêng, không dòng nào trống trạng thái",
  "7 trạng thái báo giá"),
 ("", "Tìm kiếm nhanh theo mã báo giá / tên", "P0",
  "Có báo giá mã BG-2026-00021",
  "1. Gõ 'BG-2026-00021' vào ô tìm kiếm nhanh\n2. Gõ tiếp 1 chuỗi không tồn tại",
  "—",
  "- Lần 1: danh sách còn đúng báo giá đó\n- Lần 2: hiện trạng thái rỗng, không lỗi",
  "Quick search"),
 ("", "Lọc theo Dự án + Giải pháp + Version (lọc bậc thang)", "P0",
  "Dự án DA-01 có 2 giải pháp, giải pháp S1 có 2 version",
  "1. Chọn Dự án = DA-01 → mở dropdown Giải pháp\n2. Chọn Giải pháp = S1 → mở dropdown Version\n3. Đổi Dự án sang DA-02",
  "—",
  "- Dropdown Giải pháp chỉ liệt kê giải pháp của DA-01 (trước khi chọn dự án thì bị khoá)\n"
  "- Dropdown Version chỉ liệt kê version của S1 (bị khoá khi chưa chọn giải pháp)\n"
  "- Đổi dự án → Giải pháp và Version tự reset",
  "Lọc bậc thang, watcher reset cấp dưới"),
 ("", "Lọc theo Trạng thái", "P0",
  "Có 2 báo giá Đang tạo, 1 Đã duyệt",
  "1. Chọn Trạng thái = Đã duyệt\n2. Bỏ chọn (clear)",
  "—",
  "- Danh sách còn 1 dòng Đã duyệt\n- Sau khi clear: hiện lại đủ 3 dòng",
  "Filter status + allowClear"),
 ("", "Lọc theo Cấp duyệt và Người duyệt", "P1",
  "Có báo giá cấp 1, cấp 2 (do TP1 duyệt), cấp 3",
  "1. Chọn Cấp duyệt = Cấp 2\n2. Bỏ lọc cấp, chọn Người duyệt = TP1",
  "—",
  "- Lần 1: chỉ còn báo giá cấp 2\n- Lần 2: chỉ còn báo giá do TP1 duyệt",
  "Filter price_approval_level + approver_id"),
 ("", "Lọc theo khoảng Ngày tạo", "P0",
  "BG-A tạo 01/07/2026, BG-B tạo 15/07/2026, BG-C tạo 31/07/2026",
  "1. Chọn Ngày tạo từ = 01/07/2026, đến = 15/07/2026\n2. Đổi từ = 16/07/2026, đến = 31/07/2026",
  "3 báo giá 3 ngày",
  "- Lần 1: hiện BG-A và BG-B (bao gồm 2 đầu mút)\n- Lần 2: chỉ hiện BG-C",
  "Lọc theo created_at, inclusive 2 đầu"),
 ("", "Lọc theo Khách hàng", "P1",
  "Có báo giá của KH 'Công ty A' và 'Công ty B'",
  "1. Gõ tìm 'Công ty A' ở ô Khách hàng → chọn",
  "—",
  "- Chỉ còn báo giá của Công ty A",
  "Filter customer_id"),
 ("", "Kết hợp nhiều bộ lọc cùng lúc", "P1",
  "Dữ liệu như các TC trên",
  "1. Chọn đồng thời: Dự án = DA-01, Trạng thái = Đã duyệt, Ngày tạo trong tháng 7/2026",
  "—",
  "- Danh sách chỉ còn báo giá thoả CẢ 3 điều kiện\n- Số bản ghi ở phân trang khớp số dòng hiển thị",
  "Bộ lọc là điều kiện AND"),
 ("", "Sắp xếp theo cột", "P1",
  "Có ≥ 5 báo giá",
  "1. Bấm sắp xếp cột 'Ngày tạo' tăng dần → giảm dần\n2. Bấm sắp xếp cột 'Tổng giá trị sau VAT'",
  "—",
  "- Thứ tự dòng đổi đúng theo chiều sắp xếp\n- Icon chiều sắp xếp hiển thị đúng trên cột đang sort",
  "sort_field + sort_dir"),
 ("", "Phân trang và đổi số dòng/trang", "P1",
  "Có ≥ 25 báo giá",
  "1. Chuyển sang trang 2\n2. Đổi số dòng/trang từ 10 → 50",
  "—",
  "- Trang 2 hiện đúng nhóm bản ghi tiếp theo, không lặp dòng của trang 1\n- Đổi page size → quay về trang 1, hiện đủ 50 dòng/trang",
  "Phân trang chuẩn"),
 ("", "Cấu hình cột hiển thị", "P1",
  "Đang ở danh sách báo giá",
  "1. Bấm nút 'Cấu hình cột hiển thị'\n2. Bỏ tích cột 'Tiền tệ' và 'Người duyệt' → áp dụng\n3. Tải lại trang",
  "—",
  "- 2 cột biến mất khỏi bảng, các cột còn lại không vỡ layout\n- Sau khi tải lại trang, cấu hình cột được ghi nhớ",
  "Column customization modal"),
 ("", "Cột ERP hiển thị trạng thái đồng bộ + nút thử lại", "P0",
  "BG-D đồng bộ ERP thành công; BG-E đồng bộ lỗi",
  "1. Xem cột ERP của 2 dòng\n2. Rê chuột vào icon lỗi\n3. Bấm nút 'Thử lại đồng bộ' ở dòng BG-E",
  "—",
  "- BG-D: icon xanh, tooltip 'Đã đồng bộ ERP'\n- BG-E: icon đỏ, tooltip hiện nội dung lỗi, có nút thử lại\n"
  "- Bấm thử lại: chạy đồng bộ, trạng thái cập nhật (thành công → icon xanh; vẫn lỗi → giữ icon đỏ + lỗi mới)",
  "retrySync"),
 ("", "Bộ nút thao tác trên từng dòng", "P0",
  "BG-01 Đang tạo do chính user tạo; BG-02 Đã duyệt do người khác tạo",
  "1. Xem các nút ở cột Thao tác của 2 dòng",
  "—",
  "- BG-01 (của mình, Đang tạo): Xem chi tiết, Sửa / Làm giá, Sao chép, In báo giá, Lịch sử phê duyệt, Xoá\n"
  "- BG-02: KHÔNG có Sửa và Xoá; vẫn có Xem, In, Lịch sử (Sao chép tuỳ quyền)",
  "Row action gate theo trạng thái + người tạo"),
 ("", "Mở xem chi tiết / màn sửa bằng tab mới", "P2",
  "BG-01 trong danh sách",
  "1. Ctrl+Click (hoặc chuột giữa) vào nút Xem chi tiết",
  "—",
  "- Mở đúng báo giá ở TAB MỚI, không mất trang danh sách đang lọc",
  "Nút row-action dùng nuxt-link"),
 ("", "Nút Tạo mới báo giá", "P0",
  "User có quyền tạo",
  "1. Bấm nút tạo mới ở góc phải danh sách",
  "—",
  "- Điều hướng sang /assign/quotations/create, form trống ở chế độ Tạo mới",
  "Vào luồng tạo báo giá tự lập"),
 ("", "Danh sách rỗng", "P2",
  "User mới chưa tạo báo giá nào",
  "1. Mở danh sách báo giá",
  "—",
  "- Hiện trạng thái rỗng rõ ràng, không lỗi, không bảng trắng",
  "Empty state"),
])

S3 = ("III", "TẠO BÁO GIÁ — 3 LUỒNG", [
 ("", "Tạo báo giá TỰ LẬP từ màn danh sách", "P0",
  "User là Sale phụ trách dự án DA-01",
  "1. Bấm Tạo mới → chọn Dự án DA-01\n2. Điền Giao hàng (ngày) = 30, Loại tiền tệ = VND, Bảng giá = Bảng giá bán lẻ\n3. Bấm 'Lưu nháp'",
  "DA-01, VND",
  "- Thông tin khách hàng tự điền từ dự án (tên, MST, địa chỉ, người liên hệ)\n"
  "- Lưu thành công, sinh mã BG-2026-NNNNN, trạng thái Đang tạo, loại = tự lập\n- Chuyển sang màn Sửa của báo giá vừa tạo",
  "Luồng tự lập"),
 ("", "Tạo báo giá từ Yêu cầu xây dựng giá (YCBG)", "P0",
  "YCBG-01 ở trạng thái chờ xây dựng giá, user đủ quyền",
  "1. Vào màn Yêu cầu xây dựng giá → tiếp nhận YCBG-01 → tạo báo giá\n2. Quan sát form",
  "—",
  "- Báo giá mới gắn đúng YCBG, dự án, giải pháp/hạng mục, khách hàng của yêu cầu\n"
  "- Trường YCBG hiển thị trên thông tin chung\n- Trạng thái Đang tạo",
  "Luồng từ YCBG"),
 ("", "Tiếp nhận lại YCBG đã được tiếp nhận → chặn", "P1",
  "YCBG-01 đã được tiếp nhận và tạo báo giá",
  "1. User khác thử tiếp nhận lại YCBG-01",
  "—",
  "- Bị chặn 'Yêu cầu này đã được tiếp nhận hoặc không ở trạng thái chờ xây dựng giá.'",
  "Chống tạo trùng báo giá từ 1 yêu cầu"),
 ("", "Tạo báo giá TỪ BOM tổng hợp đã duyệt", "P0",
  "BOM BM-50: loại Tổng hợp, trạng thái Đã duyệt, thuộc dự án Tự triển khai, có 8 dòng + 2 nhóm",
  "1. Mở BM-50 → bấm tạo báo giá từ BOM\n2. Quan sát báo giá sinh ra",
  "BOM 8 dòng",
  "- Báo giá mới kế thừa đủ 8 dòng, giữ nguyên nhóm (kể cả nhóm 2 cấp) và quan hệ cha-con\n"
  "- Loại báo giá = kế thừa BOM; lưới KHÔNG có nút Thêm nhóm/Thêm mới và cột Thao tác\n- Trạng thái Đang tạo",
  "createFromBom"),
 ("", "Tạo báo giá từ BOM chưa duyệt → chặn", "P0",
  "BOM BM-51 loại Tổng hợp, trạng thái Hoàn thành (chưa duyệt)",
  "1. Thử tạo báo giá từ BM-51",
  "—",
  "- Bị chặn 'BOM phải ở trạng thái Đã duyệt.'",
  "Chỉ BOM đã duyệt mới ra báo giá"),
 ("", "Tạo báo giá từ BOM THÀNH PHẦN → chặn", "P0",
  "BOM BM-52 loại Thành phần, Đã duyệt",
  "1. Thử tạo báo giá từ BM-52",
  "—",
  "- Bị chặn 'Chỉ tạo báo giá từ BOM tổng hợp.'",
  "Chỉ BOM tổng hợp"),
 ("", "Tạo báo giá từ BOM ở dự án KHÔNG phải Tự triển khai → chặn", "P1",
  "BOM BM-53 tổng hợp, Đã duyệt, dự án implementation_type ≠ Tự triển khai",
  "1. Thử tạo báo giá trực tiếp từ BM-53",
  "—",
  "- Bị chặn 'Chỉ dự án Tự triển khai mới được tạo báo giá trực tiếp.'",
  "Luồng trực tiếp chỉ cho dự án tự triển khai"),
 ("", "Bảng giá là trường bắt buộc khi tạo", "P0",
  "Đang ở màn Tạo báo giá tự lập",
  "1. Điền dự án nhưng để trống 'Bảng giá' → bấm Lưu nháp",
  "—",
  "- Bị chặn, ô Bảng giá viền đỏ + thông báo lỗi inline\n- Không tạo bản ghi nào",
  "price_type_id required (in:1..6)"),
 ("", "Đổi Bảng giá → giá bán hàng ERP tính lại", "P0",
  "BG-08 (Đang tạo) có 3 hàng ERP theo Bảng giá bán lẻ",
  "1. Đổi 'Bảng giá' sang bảng giá khác\n2. Quan sát cột Đơn giá bán 3 dòng ERP\n3. Lưu nháp → mở lại",
  "—",
  "- Đơn giá bán hàng ERP tự cập nhật theo bảng giá mới\n- Hàng tạm KHÔNG bị đổi giá\n- Sau Lưu, giá mới được ghi nhận",
  "erp-reprice khi đổi bảng giá"),
 ("", "Bảng giá và Loại tiền tệ bị khoá sau khi rời trạng thái Đang tạo", "P1",
  "BG-09 trạng thái Chờ TP duyệt",
  "1. Mở BG-09 → quan sát 2 trường Bảng giá, Loại tiền tệ",
  "—",
  "- Cả 2 trường chỉ đọc, không đổi được",
  "Chốt giá theo bảng giá tại thời điểm lập"),
 ("", "Báo giá ngoại tệ — tỷ giá lấy theo ERP", "P1",
  "Tỷ giá USD trên ERP hiện tại = 25.400",
  "1. Tạo báo giá mới, chọn Loại tiền tệ = USD → Lưu nháp\n2. Xem tỷ giá hiển thị và đơn giá hàng ERP",
  "USD",
  "- Tỷ giá = 25.400 (không phải nhập tay)\n- Giá hàng ERP quy đổi theo tỷ giá này",
  "Tỷ giá ERP tại thời điểm lập"),
])

S4 = ("IV", "THÔNG TIN CHUNG & VALIDATE FORM", [
 ("", "Các trường bắt buộc được đánh dấu * và chặn khi để trống", "P0",
  "Màn Tạo báo giá tự lập",
  "1. Để trống Dự án, Giao hàng (ngày), Loại tiền tệ, Bảng giá → bấm Lưu nháp\n2. Quan sát từng ô",
  "—",
  "- Mỗi ô bắt buộc bị bỏ trống đều viền đỏ + có dòng lỗi ngay dưới ô\n- Không gọi lưu / không tạo bản ghi\n- Lỗi chỉ hiện sau lần submit đầu, không hiện ngay khi mới mở form",
  "Validate inline theo chuẩn dự án (cờ touched)"),
 ("", "Email khách hàng sai định dạng", "P0",
  "BG-10 màn Sửa",
  "1. Nhập Email khách hàng = 'abc@' → Lưu",
  "abc@",
  "- Báo lỗi định dạng email tại ô đó, không lưu",
  "customer_email: nullable|email|max:255"),
 ("", "Thông tin khách hàng tự nạp theo dự án", "P0",
  "Dự án DA-01 gắn KH 'Công ty A' có MST, địa chỉ, người liên hệ, SĐT",
  "1. Ở màn Tạo, chọn Dự án DA-01\n2. Quan sát khối thông tin khách hàng",
  "—",
  "- Tên KH, MST, địa chỉ, người liên hệ, SĐT tự điền đúng theo dữ liệu khách hàng của dự án",
  "Nạp thông tin hành chính KH từ dự án"),
 ("", "Điều khoản báo giá — điền nhanh từ mẫu", "P1",
  "Có ≥ 1 mẫu điều khoản báo giá trong danh mục ERP",
  "1. Ở trường Điều khoản/thanh toán, chọn 1 mẫu từ danh sách\n2. Sửa lại nội dung → Lưu nháp → mở lại",
  "—",
  "- Nội dung mẫu được điền vào ô soạn thảo\n- Sửa được và nội dung sau sửa được lưu đúng",
  "term-templates"),
 ("", "Bảo hành / Giao hàng chỉ nhận số", "P1",
  "Màn Sửa BG-10",
  "1. Nhập Giao hàng (ngày) = 'abc'; Bảo hành (tháng) = -5 → Lưu",
  "—",
  "- Không nhập được chữ vào ô số / hoặc báo lỗi\n- Giá trị âm bị chặn hoặc không được lưu",
  "Kiểu số cho 2 trường thời gian"),
 ("", "Hiệu lực báo giá tự tính khi gửi duyệt", "P0",
  "BG-11 có hàng ERP có ngày hiệu lực giá 15/08/2026; cấu hình hiệu lực của dự án là 30 ngày kể từ ngày gửi",
  "1. Bấm 'Gửi duyệt' ngày 31/07/2026\n2. Xem trường Hiệu lực báo giá",
  "Hôm nay 31/07/2026",
  "- Hiệu lực = mốc ĐẾN TRƯỚC giữa 15/08/2026 (hiệu lực giá ERP) và 30/08/2026 (theo cấu hình dự án) → 15/08/2026",
  "calculateValidityDate — lấy mốc sớm hơn"),
 ("", "Làm tròn số tiền", "P1",
  "BG-12 có dòng ra số lẻ (ví dụ 1.234.567,89)",
  "1. Chọn kiểu Làm tròn → bấm 'Áp dụng'\n2. Quan sát các ô tiền và tổng\n3. Lưu → mở lại",
  "—",
  "- Số tiền được làm tròn theo kiểu đã chọn ở cả dòng lẫn tổng\n- Sau Lưu, giá trị làm tròn được giữ",
  "rounding_mode"),
 ("", "Lưu nháp giữ nguyên trạng thái Đang tạo", "P0",
  "BG-13 Đang tạo, đã sửa vài trường",
  "1. Bấm 'Lưu nháp'\n2. Tải lại trang",
  "—",
  "- Toast lưu thành công, trạng thái vẫn Đang tạo\n- Các thay đổi được giữ sau khi tải lại",
  "Lưu nháp = update, không đổi trạng thái"),
 ("", "Thoát màn Sửa khi chưa lưu", "P1",
  "BG-13 vừa sửa 1 trường, chưa lưu",
  "1. Bấm Quay lại / rời màn hình\n2. Mở lại báo giá",
  "—",
  "- Thay đổi chưa lưu KHÔNG được ghi nhận (dữ liệu như cũ)\n- Không mất dữ liệu đã lưu trước đó",
  "Chỉ ghi DB khi bấm Lưu"),
])

S5 = ("V", "LƯỚI HÀNG HOÁ — NHÓM, THÊM/SỬA/XOÁ, CHA-CON, HÀNG TẠM", [
 ("", "Thêm hàng hoá ERP từ popup 'Thêm mới'", "P0",
  "BG-20 tự lập, Đang tạo, đã có 1 nhóm",
  "1. Bấm 'Thêm mới' trong nhóm → tab Hàng hoá ERP → tìm theo mã/tên → chọn 1 sản phẩm → Thêm\n2. Quan sát dòng mới",
  "Mã ERP thật",
  "- Dòng mới có đủ Tên, Mã, Model, Thương hiệu, Xuất xứ, ĐVT, TSKT lấy từ ERP và bị KHOÁ\n"
  "- Đơn giá bán tự lấy theo Bảng giá đang chọn; VAT lấy theo ERP\n- Số lượng mặc định 1, sửa được",
  "Popup 2 tab dùng chung BOM + báo giá"),
 ("", "Tìm hàng hoá ERP theo danh mục / từ khoá", "P1",
  "Popup Thêm mới đang mở",
  "1. Chọn 1 danh mục ERP → xem danh sách\n2. Gõ từ khoá không tồn tại",
  "—",
  "- Lọc đúng theo danh mục\n- Từ khoá không có kết quả → hiện trạng thái rỗng, không lỗi",
  "erp-product-search / erp-product-catalogs"),
 ("", "Thêm HÀNG TẠM (nhập tay) qua tab 'Thêm mới thủ công'", "P0",
  "BG-20 Đang tạo",
  "1. Mở popup Thêm mới → tab Thêm mới thủ công\n2. Nhập Tên, ĐVT, Model/Thương hiệu/Xuất xứ, TSKT, Số lượng, Giá nhập, Giá bán, VAT → Thêm\n3. Lưu báo giá → mở lại",
  "Hàng tạm mới",
  "- Dòng hàng tạm được thêm vào lưới, các ô sửa được (không khoá như hàng ERP)\n"
  "- Sau khi Lưu: mã hàng tự sinh dạng HHBG + số (mã user gõ nếu có sẽ bị thay bằng mã tự sinh, trừ khi trùng mã hàng hoá dự án của CÙNG dự án)",
  "Hàng tạm mã tự sinh HHBG+id"),
 ("", "Chuyển tab trong popup Thêm hàng tạm không nhân bản ô soạn thảo TSKT", "P1",
  "Popup Thêm mới đang mở",
  "1. Chuyển qua lại giữa 2 tab 3 lần\n2. Đếm số ô soạn thảo Thông số kỹ thuật",
  "3 lần chuyển tab",
  "- Luôn chỉ có ĐÚNG 1 ô soạn thảo TSKT (không tăng 2, 3, 4 lần)",
  "Bug cũ đã fix — cần chống tái phát"),
 ("", "Dùng lại hàng tạm của dự án (picker 'Hàng hoá dự án')", "P1",
  "Dự án 38 đã có hàng tạm HHBG000701 (tên, ĐVT, TSKT, giá đầy đủ)",
  "1. Trong popup, chọn nguồn 'Hàng hoá dự án' → chọn HHBG000701 → Thêm\n2. Kiểm tra dữ liệu dòng vừa thêm\n3. Lưu → xem mã",
  "Cùng dự án 38",
  "- Dòng mới mang đủ tên/ĐVT/Model/TH/XX/TSKT/giá/VAT/ghi chú của hàng cũ\n- Sau Lưu: GIỮ nguyên mã HHBG000701 (vì cùng dự án)",
  "Rule 1 — cùng dự án được dùng lại mã"),
 ("", "Thêm dòng CON cho 1 dòng cha", "P0",
  "BG-20 có dòng cha 'Cụm bơm' (hàng tự xây)",
  "1. Bấm 'Thêm con' trên dòng cha → chọn/nhập 2 hàng con\n2. Quan sát hiển thị và ô tiền của dòng cha\n3. Lưu → mở lại",
  "2 dòng con",
  "- 2 dòng con hiển thị thụt vào dưới dòng cha\n- Tiền của dòng cha roll-up từ các con (không cộng trùng)\n"
  "- Sau Lưu, quan hệ cha-con giữ đúng",
  "Cây hàng hoá 2 cấp"),
 ("", "Nhân bản dòng hàng hoá", "P1",
  "BG-20 có dòng X (hàng tạm, có 2 con)",
  "1. Bấm 'Nhân bản' trên dòng X\n2. Quan sát dòng mới\n3. Lưu → mở lại",
  "—",
  "- Sinh 1 dòng giống hệt X (kèm các dòng con nếu có), nằm ngay dưới X\n"
  "- Sau Lưu: dòng nhân bản là bản ghi riêng, sửa dòng này không ảnh hưởng dòng gốc",
  "Nút Nhân bản trên lưới"),
 ("", "Sửa dòng hàng hoá qua popup Sửa", "P0",
  "BG-20 có dòng hàng tạm",
  "1. Mở popup sửa dòng → đổi Tên, Số lượng, TSKT, Ghi chú → Lưu\n2. Lưu báo giá → mở lại",
  "—",
  "- Thay đổi hiển thị ngay trên lưới\n- Ô Ghi chú có mặt trong popup và lưu được\n- Sau Lưu báo giá, dữ liệu đúng",
  "QuotationProductEditModal có trường Ghi chú"),
 ("", "Hàng ERP không sửa được thông tin master", "P0",
  "BG-20 có dòng hàng ERP",
  "1. Thử sửa Tên / Model / Thương hiệu / Xuất xứ / ĐVT / Mã hàng của dòng ERP",
  "—",
  "- Các ô này bị khoá (chỉ đọc)\n- Vẫn sửa được Số lượng, Đơn giá bán (theo quyền), Ghi chú",
  "Dữ liệu master lấy chuẩn từ ERP"),
 ("", "Không sửa được MÃ hàng tạm ở màn Sửa", "P1",
  "BG-20 có hàng tạm đã lưu mã HHBG000701",
  "1. Thử sửa ô Mã hàng của dòng đó",
  "—",
  "- Ô mã bị khoá, không sửa được",
  "Khoá sửa mã hàng tạm (tránh vỡ liên kết hàng hoá dự án)"),
 ("", "Xoá dòng hàng hoá (cha có con)", "P0",
  "BG-20 có dòng cha + 2 con",
  "1. Xoá dòng cha → xác nhận\n2. Quan sát lưới\n3. Lưu → mở lại",
  "—",
  "- Có xác nhận trước khi xoá\n- Xoá cha thì các con cũng bị xoá theo (không để con mồ côi)\n- Sau Lưu, DB không còn 3 dòng đó",
  "Xoá cascade dòng con"),
 ("", "Thêm / sửa / xoá nhóm hàng và nhóm con", "P0",
  "BG-20 tự lập, Đang tạo",
  "1. Thêm nhóm Cấp 1 'Dây chuyền sơn'\n2. Bấm 'Thêm nhóm con' → 'Vật tư điện'\n3. Sửa tên nhóm con → Xoá nhóm cha → xác nhận",
  "—",
  "- Nhóm Cấp 1 đánh số La Mã, nhóm con nhãn I.1 và thụt lề\n- Nhóm Cấp 2 không có nút 'Thêm nhóm con'\n"
  "- Xoá nhóm cha → nhóm con bị xoá theo, hàng hoá KHÔNG bị mất",
  "Nhóm 2 cấp (chi tiết ở testcase riêng)"),
 ("", "Kéo-thả đổi thứ tự nhóm và thứ tự hàng hoá", "P0",
  "BG-20 có 3 nhóm và 4 dòng hàng trong 1 nhóm",
  "1. Kéo nhóm thứ 3 lên vị trí 1 → Lưu → tải lại\n2. Kéo 1 dòng hàng hoá lên đầu nhóm → Lưu → tải lại",
  "—",
  "- Thứ tự đổi ngay trên UI và được giữ sau khi Lưu + tải lại\n- Kéo nhóm không làm xáo thứ tự hàng hoá bên trong và ngược lại",
  "2 handle kéo độc lập"),
 ("", "Báo giá kế thừa BOM — khoá cấu trúc", "P0",
  "BG-21 kế thừa BOM BM-50",
  "1. Mở màn Sửa BG-21\n2. Tìm nút Thêm nhóm / Thêm mới / cột Thao tác / nút xoá dòng\n3. Thử sửa Số lượng của 1 dòng BOM",
  "—",
  "- KHÔNG có nút Thêm nhóm, Thêm mới, không có cột Thao tác trên lưới hàng hoá\n"
  "- Số lượng dòng kế thừa BOM không sửa được\n- Vẫn sửa được Đơn giá bán, GG, Ghi chú, VAT",
  "Cấu trúc BOM khoá cứng — chỉ làm giá"),
 ("", "Hiển thị / ẩn các cột phụ trên lưới", "P2",
  "BG-20 màn Sửa",
  "1. Bật/tắt các cột Model / Thương hiệu / Xuất xứ / TSKT / Ghi chú",
  "—",
  "- Cột ẩn/hiện đúng theo lựa chọn, bảng không vỡ layout, tổng tiền không đổi",
  "showQuotationExtraCols"),
 ("", "Cảnh báo dòng có giá bán = 0", "P0",
  "BG-20 có 1 dòng để giá bán = 0",
  "1. Quan sát ô giá bán dòng đó sau khi bấm Gửi duyệt",
  "Giá bán = 0",
  "- Ô giá bán được đánh dấu lỗi (viền đỏ)\n- Không gửi duyệt được cho tới khi nhập giá > 0",
  "ensureAllPricesPositive"),
])

S6 = ("VI", "DỊCH VỤ & CHI PHÍ KHÁC + CHI PHÍ VẬN CHUYỂN", [
 ("", "Thêm dòng Dịch vụ từ danh mục ERP", "P0",
  "BG-30 Đang tạo; danh mục chi phí ERP có 'Phí lắp đặt' (VAT 8%, có % giá vốn)",
  "1. Ở khối 'Dịch vụ & Chi phí khác' bấm Thêm mới → tab Dịch vụ & Chi phí → chọn 'Phí lắp đặt' → Thêm\n2. Nhập Đơn giá bán → Lưu → mở lại",
  "Phí lắp đặt, VAT 8%",
  "- Dòng dịch vụ được thêm với VAT 8% (không phải 0)\n- Giá vốn tự tính theo % giá vốn ERP = giá bán × %\n- Sau Lưu dữ liệu đúng",
  "VAT dịch vụ lấy từ ERP; giá vốn theo tỷ lệ"),
 ("", "Thêm dịch vụ TỰ DO (không có trong danh mục)", "P1",
  "BG-30",
  "1. Tạo nhanh 1 chi phí tên 'Phí khảo sát hiện trường' → nhập giá bán + giá vốn → Thêm\n2. Lưu → mở lại",
  "—",
  "- Dòng được thêm, cho nhập giá vốn tay\n- Sau khi Lưu, tỷ lệ giá vốn thực tế được cập nhật ngược về danh mục ERP",
  "Dịch vụ chưa có % giá vốn: lấy user nhập rồi cập nhật rate"),
 ("", "Sửa / xoá dòng dịch vụ", "P0",
  "BG-30 có 2 dòng dịch vụ",
  "1. Sửa đơn giá + ghi chú 1 dòng → Lưu\n2. Xoá 1 dòng → xác nhận → Lưu → mở lại",
  "—",
  "- Sửa và xoá đều phản ánh đúng trên lưới và sau khi Lưu\n- Tổng hợp giá trị cập nhật theo",
  "CRUD service items"),
 ("", "Dịch vụ bắt buộc có tên và giá bán > 0", "P0",
  "BG-30",
  "1. Thêm dịch vụ để trống tên → Lưu\n2. Thêm dịch vụ có tên nhưng giá bán = 0 → Gửi duyệt",
  "—",
  "- Trống tên: báo lỗi bắt buộc, không lưu\n- Giá bán = 0: chặn khi gửi duyệt",
  "service_items.*.name required_with; giá bán > 0"),
 ("", "Nhập Chi phí vận chuyển ở cấp phiếu", "P0",
  "BG-31 Đang tạo",
  "1. Nhập Chi phí vận chuyển = 5.000.000, VAT 8%, giảm giá 500.000, giá vốn vận chuyển 4.000.000\n2. Lưu → mở lại\n3. Xem bảng Tổng hợp giá trị",
  "5.000.000 / 8%",
  "- 5 giá trị được lưu đúng\n- Vận chuyển KHÔNG xuất hiện như 1 dòng trong bảng hàng hoá\n"
  "- Vận chuyển được cộng vào dòng Tổng của bảng Tổng hợp và vào tỷ suất lợi nhuận",
  "Vận chuyển ở cấp phiếu, tính vào TSLN"),
 ("", "Chi phí vận chuyển = 0 — không ảnh hưởng tổng", "P1",
  "BG-32 để trống/0 chi phí vận chuyển",
  "1. Xem bảng Tổng hợp giá trị và bản in",
  "—",
  "- Không có dòng vận chuyển; tổng tiền không cộng thêm gì",
  "Chỉ tính khi > 0"),
])

S7 = ("VII", "GIÁ, VAT, GIẢM GIÁ & TỔNG HỢP GIÁ TRỊ", [
 ("", "Tính tiền 1 dòng: thành tiền, VAT, thành tiền sau VAT", "P0",
  "BG-40 (Không GG) có dòng: SL 2, Đơn giá bán 1.000.000, VAT 10%",
  "1. Nhập số liệu trên → quan sát các ô tiền của dòng",
  "SL 2 × 1.000.000, VAT 10%",
  "- Thành tiền bán = 2.000.000\n- Giá trị VAT = 200.000\n- Thành tiền sau VAT = 2.200.000",
  "Công thức tính tiền dòng"),
 ("", "Dòng CHA có CON — tiền roll-up từ con, không cộng trùng", "P0",
  "BG-40 có cha P (SL 1) với 2 con: C1 (SL 2 × 500.000), C2 (SL 1 × 1.000.000)",
  "1. Xem ô tiền dòng cha và tổng bảng",
  "—",
  "- Tiền dòng cha = 2.000.000 (tổng từ con), không cộng thêm giá riêng của cha\n"
  "- Tổng bảng chỉ tính 1 lần (không cộng cả cha lẫn con)",
  "computeTotals roll-up cha-có-con"),
 ("", "Ràng buộc: đơn giá bán CHA ≥ tổng giá bán CON", "P0",
  "BG-40 có cha P giá bán 1.000.000, 2 con tổng giá bán 1.500.000 (hàng tự xây)",
  "1. Bấm 'Gửi duyệt'",
  "—",
  "- Bị chặn, thông báo nêu rõ đơn giá bán của dòng cha phải ≥ tổng giá bán hàng con (kèm tên/mã dòng)",
  "assertParentSalePriceFloor"),
 ("", "Ràng buộc: giá nhập CHA ≥ tổng giá nhập CON", "P0",
  "BG-40 có cha giá nhập 500.000, tổng giá nhập con 800.000",
  "1. Bấm 'Gửi duyệt'",
  "—",
  "- Bị chặn với thông báo về mức sàn giá nhập cha-con",
  "assertParentImportFloor"),
 ("", "Áp VAT hàng loạt", "P0",
  "BG-41 Đang tạo có 10 dòng VAT khác nhau",
  "1. Nhập VAT(%) = 10 ở ô áp hàng loạt → chọn phạm vi áp → Áp dụng\n2. Kiểm tra các dòng\n3. Lưu → mở lại",
  "VAT = 10",
  "- Tất cả dòng trong phạm vi đã chọn đổi VAT = 10%\n- Tổng VAT tính lại đúng\n- Sau Lưu giữ nguyên",
  "applyVatBulk"),
 ("", "Áp VAT hàng loạt ngoài khoảng 0–100", "P1",
  "BG-41",
  "1. Nhập VAT = 150 → Áp dụng",
  "VAT = 150",
  "- Bị chặn 'VAT phải trong khoảng 0-100%'",
  "Validate VAT bulk"),
 ("", "Áp VAT hàng loạt khi báo giá đã gửi duyệt → chặn", "P1",
  "BG-42 trạng thái Chờ TP duyệt",
  "1. Thử áp VAT hàng loạt",
  "—",
  "- Bị chặn 'Báo giá đã gửi, không thể sửa VAT'",
  "Khoá sau khi gửi duyệt"),
 ("", "Loại GG = Giảm giá mặt hàng — nhập GG(%) và GG(đ)", "P0",
  "BG-43 Loại GG = Giảm giá mặt hàng; dòng đơn giá 1.000.000",
  "1. Nhập GG(%) = 10 ở dòng 1 → xem đơn giá sau GG\n2. Ở dòng 2 nhập GG(đ) = 300.000 → xem đơn giá sau GG\n3. Lưu → mở lại",
  "10% và 300.000đ",
  "- Dòng 1: đơn giá sau GG = 900.000\n- Dòng 2: đơn giá sau GG = 700.000\n- Tổng tiền và VAT tính trên giá SAU giảm",
  "2 kiểu nhập giảm giá dòng"),
 ("", "GG(đ) lớn hơn đơn giá bán → chặn", "P0",
  "BG-43 dòng đơn giá 1.000.000",
  "1. Nhập GG(đ) = 1.500.000 → Lưu / Gửi duyệt",
  "—",
  "- Bị chặn, báo giảm giá không được vượt đơn giá bán; không cho giá sau GG âm",
  "Validate chiết khấu ≤ đơn giá bán"),
 ("", "Loại GG = Giảm giá tổng — thêm khoản giảm giá", "P0",
  "BG-44 Loại GG = Giảm giá tổng, tổng tiền hàng 100.000.000",
  "1. Bấm 'Thêm khoản GG' → chọn Loại GG từ danh mục, Kiểu %, Giá trị 10 → xem thành tiền\n2. Thêm khoản thứ 2 kiểu đ = 2.000.000\n3. Lưu → mở lại",
  "10% + 2.000.000đ",
  "- Khoản 1 thành tiền = 10.000.000; khoản 2 = 2.000.000\n- Tổng giảm giá = 12.000.000, tổng sau giảm cập nhật đúng\n- Sau Lưu giữ nguyên",
  "quotation_discounts: percent → tự tính tiền"),
 ("", "Phân bổ giảm giá tổng về từng dòng", "P0",
  "BG-44 có tổng giảm 12.000.000, 5 dòng hàng hoá",
  "1. Bấm 'Phân bổ GG' (hoặc bật GG phân bổ tự động)\n2. Xem cột Phân bổ GG từng dòng và tổng cột đó",
  "Tổng giảm 12.000.000",
  "- Mỗi dòng có số phân bổ theo tỷ trọng thành tiền\n- Tổng cột Phân bổ GG = 12.000.000 (không lệch do làm tròn)\n"
  "- Đơn giá sau GG mỗi dòng = đơn giá bán − phân bổ/SL",
  "allocateDiscount"),
 ("", "Phân bổ GG khi tổng giá bán = 0 → chặn", "P1",
  "BG-45 Loại GG = Giảm giá tổng nhưng chưa nhập giá bán dòng nào",
  "1. Bấm Phân bổ GG",
  "—",
  "- Bị chặn 'Tổng giá bán = 0, không thể phân bổ giảm giá. Vui lòng nhập giá bán trước.'",
  "Chống chia 0"),
 ("", "Phân bổ GG trên báo giá không dùng GG tổng → chặn", "P2",
  "BG-43 Loại GG = Giảm giá mặt hàng",
  "1. Gọi chức năng phân bổ GG",
  "—",
  "- Bị chặn 'Báo giá không áp dụng giảm giá theo tổng.'",
  "Gate theo discount_method"),
 ("", "Bảng 'Tổng hợp giá trị báo giá' đúng số", "P0",
  "BG-46: hàng hoá 100.000.000 (VAT 10%), dịch vụ 10.000.000 (VAT 8%), vận chuyển 5.000.000 (VAT 8%), giảm giá tổng 12.000.000",
  "1. Xem bảng Tổng hợp giá trị + footer",
  "—",
  "- Có dòng riêng cho nhóm Hàng hoá / Dịch vụ / (Vận chuyển ở dòng Tổng)\n"
  "- Tổng trước giảm, tổng giảm giá, tổng sau giảm, tổng VAT, tổng sau VAT khớp số liệu\n- Vận chuyển KHÔNG nằm trong bảng hàng hoá/dịch vụ phía trên",
  "Mô hình tổng hợp sau redesign chi phí vận chuyển"),
 ("", "Tỷ suất lợi nhuận tính đúng (có vận chuyển)", "P0",
  "BG-46: tổng giá vốn 70.000.000 (gồm giá vốn vận chuyển 4.000.000), tổng bán sau giảm 103.000.000",
  "1. Xem ô Tỷ suất lợi nhuận",
  "—",
  "- TSLN = (103.000.000 − 70.000.000)/103.000.000 ≈ 32,04%\n- Giá vốn vận chuyển ĐƯỢC tính vào công thức",
  "TSLN quyết định cấp duyệt"),
 ("", "Người không có quyền giá vốn không thấy TSLN và tổng giá vốn", "P0",
  "BG-46, user không có quyền 'Xem giá vốn hàng hoá' và không phải người tạo",
  "1. Mở màn Xem → xem bảng tổng hợp",
  "—",
  "- Ô Tổng giá vốn và Tỷ suất lợi nhuận ẩn / hiện '—'\n- Các ô doanh thu vẫn hiển thị",
  "Gate giá vốn ở tầng hiển thị tổng"),
 ("", "Báo giá ngoại tệ — hiển thị tiền tệ và tỷ giá", "P1",
  "BG-47 tiền tệ USD, tỷ giá 25.400",
  "1. Xem lưới + tổng hợp + toolbar",
  "—",
  "- Số tiền hiển thị theo USD; toolbar hiện tỷ giá 25.400 và ngày tạo\n- Tổng quy đổi VND (nếu có) tính đúng theo tỷ giá",
  "Hiển thị tỷ giá ở màn sửa"),
])

S8 = ("VIII", "GỬI DUYỆT & LUỒNG PHÊ DUYỆT", [
 ("", "Gửi duyệt thiếu điều khoản thanh toán → chặn", "P0",
  "BG-50 đầy đủ hàng hoá nhưng bỏ trống Điều khoản thanh toán",
  "1. Bấm 'Gửi duyệt'",
  "—",
  "- Bị chặn 'Vui lòng nhập điều khoản thanh toán trước khi gửi duyệt.'\n- Trạng thái vẫn Đang tạo",
  "Điều kiện bắt buộc trước khi gửi"),
 ("", "Gửi duyệt khi còn dòng giá bán = 0 → chặn", "P0",
  "BG-50 có 1 dòng giá bán = 0",
  "1. Bấm 'Gửi duyệt'",
  "—",
  "- Bị chặn, chỉ rõ dòng chưa có giá\n- Trạng thái vẫn Đang tạo",
  "ensureAllPricesPositive"),
 ("", "Gửi duyệt khi hàng tự nhập chưa có giá vốn → chặn", "P1",
  "BG-50 có 1 dòng hàng tạm (không có con) để giá nhập = 0",
  "1. Bấm 'Gửi duyệt'",
  "—",
  "- Bị chặn, yêu cầu nhập giá vốn cho hàng tự nhập\n- Riêng hàng ERP giá nhập = 0 KHÔNG bị chặn (giá lấy từ ERP)",
  "Giá nhập chỉ bắt buộc với hàng tự nhập"),
 ("", "Gửi duyệt ra CẤP 1 → cho tự duyệt", "P0",
  "BG-51 có giá trị nhỏ và TSLN cao, theo Cấu hình duyệt giá ra Cấp 1",
  "1. Bấm 'Gửi duyệt'\n2. Quan sát thông báo/màn hình\n3. Xác nhận tự duyệt",
  "Cấp 1",
  "- Hệ thống báo báo giá thuộc cấp tự duyệt (Cấp 1)\n- Sau khi tự duyệt: trạng thái chuyển Đã duyệt, ghi nhận người duyệt là chính người tạo\n"
  "- KHÔNG xuất hiện trong hàng đợi chờ duyệt của TP",
  "LEVEL_1 → selfApprove"),
 ("", "Tự duyệt báo giá không thuộc cấp 1 → chặn", "P1",
  "BG-52 cấp duyệt = 2",
  "1. Gọi chức năng tự duyệt",
  "—",
  "- Bị chặn 'Báo giá này không thuộc cấp tự duyệt.'",
  "Chặn lách cấp duyệt"),
 ("", "Gửi duyệt ra CẤP 2 → Chờ TP duyệt", "P0",
  "BG-52 giá trị/TSLN rơi vào Cấp 2",
  "1. Bấm 'Gửi duyệt'\n2. Xem trạng thái + hàng đợi của TP",
  "Cấp 2",
  "- Trạng thái = Chờ TP duyệt, ghi nhận thời điểm gửi\n- Báo giá xuất hiện ở màn Chờ duyệt của TP đúng phòng\n- TP nhận được thông báo",
  "submit → STATUS_CHO_TP_DUYET"),
 ("", "Gửi duyệt ra CẤP 3 → TP duyệt & chuyển BGĐ", "P0",
  "BG-53 giá trị lớn / TSLN thấp → Cấp 3",
  "1. Gửi duyệt\n2. TP mở phiếu → nút duyệt hiển thị gì → bấm duyệt\n3. Xem trạng thái + hàng đợi BGĐ",
  "Cấp 3",
  "- Sau gửi: Chờ TP duyệt, cấp duyệt = 3\n- Nút của TP ghi 'Duyệt & chuyển BGĐ'\n"
  "- Sau khi TP duyệt: trạng thái = Chờ BGĐ duyệt, phiếu vào hàng đợi BGĐ",
  "Cấp 3 = 2 chặng TP → BGĐ"),
 ("", "Cấp duyệt = mức CAO HƠN giữa cấp theo giá trị và cấp theo TSLN", "P0",
  "Cấu hình: giá trị đơn hàng của BG-54 rơi vào Cấp 1 nhưng TSLN thấp rơi vào Cấp 3",
  "1. Bấm 'Tính cấp duyệt' (hoặc Gửi duyệt) → xem cấp\n",
  "Giá trị → C1; TSLN → C3",
  "- Cấp duyệt kết quả = Cấp 3 (lấy mức cao hơn)\n- Màn hình hiển thị rõ cấp duyệt và lý do (giá trị / TSLN)",
  "calculateApprovalLevel = max(2 chiều)"),
 ("", "TP duyệt báo giá cấp 2 → Đã duyệt", "P0",
  "BG-52 đang Chờ TP duyệt, TP đúng phòng",
  "1. TP mở màn Chờ duyệt → mở phiếu → xem TSLN và mức sàn\n2. Bấm 'Duyệt'",
  "Cấp 2",
  "- Trạng thái chuyển Đã duyệt, ghi nhận người duyệt + ngày duyệt\n- Người tạo nhận thông báo\n- Phiếu biến khỏi hàng đợi chờ duyệt",
  "tpApprove cấp 2 kết thúc luồng"),
 ("", "BGĐ duyệt báo giá cấp 3", "P0",
  "BG-53 đang Chờ BGĐ duyệt",
  "1. BGĐ mở phiếu → bấm 'BGĐ duyệt'",
  "—",
  "- Trạng thái = Đã duyệt, ghi nhận người duyệt BGĐ + ngày duyệt",
  "bgdApprove"),
 ("", "Duyệt sai trạng thái → chặn", "P1",
  "BG-52 đang Chờ TP duyệt",
  "1. BGĐ gọi chức năng 'BGĐ duyệt' cho BG-52\n2. TP gọi 'Duyệt' cho 1 báo giá đang ở Đang tạo",
  "—",
  "- Lần 1: chặn 'Báo giá không ở trạng thái Chờ BGĐ duyệt.'\n- Lần 2: chặn 'Báo giá không ở trạng thái Chờ TP duyệt.'",
  "Gate trạng thái từng chặng duyệt"),
 ("", "Từ chối báo giá — bắt buộc nhập lý do", "P0",
  "BG-52 đang Chờ TP duyệt",
  "1. TP bấm 'Từ chối' → để trống lý do → xác nhận\n2. Nhập lý do 'Giá vốn chưa cập nhật' → xác nhận",
  "—",
  "- Bỏ trống: chặn 'Vui lòng nhập lý do từ chối.' + ô lý do viền đỏ\n"
  "- Có lý do: báo giá quay lại Đang tạo, xoá cấp duyệt, lưu lý do từ chối, người tạo nhận thông báo",
  "reject → về Đang tạo"),
 ("", "Sau khi bị từ chối, người tạo sửa và gửi duyệt lại", "P0",
  "BG-52 vừa bị từ chối",
  "1. Người tạo mở báo giá → thấy lý do từ chối\n2. Sửa giá → 'Gửi duyệt' lại",
  "—",
  "- Sửa được (đã về Đang tạo)\n- Gửi duyệt lại tính LẠI cấp duyệt theo số liệu mới\n- Lý do từ chối cũ được xoá khỏi trạng thái hiện tại nhưng còn trong Lịch sử",
  "rejected_reason reset khi submit lại"),
 ("", "Màn 'Chờ duyệt' — danh sách và nhãn hạn", "P1",
  "TP có 3 báo giá chờ duyệt",
  "1. Mở /assign/quotations/pending-approval\n2. Quan sát danh sách + bộ lọc",
  "—",
  "- Chỉ hiện báo giá thuộc phạm vi duyệt của người đăng nhập\n- Hiển thị đủ mã, dự án, khách hàng, giá trị, cấp duyệt, ngày gửi\n- Lọc/tìm kiếm hoạt động",
  "Hàng đợi duyệt giá"),
 ("", "Duyệt liên tiếp nhiều báo giá không lẫn phiếu", "P2",
  "TP có 3 phiếu chờ duyệt",
  "1. Duyệt lần lượt 3 phiếu\n2. Kiểm tra trạng thái từng phiếu",
  "—",
  "- Mỗi thao tác duyệt tác động đúng phiếu tương ứng, không nhầm phiếu\n- Danh sách tự cập nhật sau mỗi lần duyệt",
  "Chống lỗi trạng thái dùng chung"),
 ("", "Lịch sử phê duyệt ghi đủ mốc", "P0",
  "BG-53 đã qua: tạo → gửi duyệt → TP duyệt → BGĐ duyệt",
  "1. Mở 'Lịch sử' của BG-53",
  "—",
  "- Có đủ các mốc theo thứ tự thời gian, mỗi mốc ghi người thực hiện + thời điểm + trạng thái trước/sau\n- Nếu có từ chối thì hiện kèm lý do",
  "quotation_histories"),
])

S9 = ("IX", "SAU DUYỆT — CHỐT TRÚNG THẦU, ĐỒNG BỘ ERP, HÀNG TẠM", [
 ("", "Chốt báo giá trúng thầu", "P0",
  "BG-60 trạng thái Đã duyệt, thuộc dự án DA-01 chưa có báo giá trúng thầu",
  "1. Vào chi tiết dự án DA-01 → tab Báo giá\n2. Bấm 'Chốt báo giá (Trúng thầu)' ở dòng BG-60 → xác nhận",
  "—",
  "- Trạng thái BG-60 = Trúng thầu\n- Lịch sử ghi nhận mốc chốt",
  "finalize"),
 ("", "Chốt báo giá chưa duyệt → chặn", "P0",
  "BG-61 trạng thái Đang tạo",
  "1. Gọi chức năng chốt cho BG-61",
  "—",
  "- Bị chặn 'Chỉ chốt được báo giá đã duyệt.'",
  "Gate trạng thái"),
 ("", "Dự án đã có báo giá trúng thầu → chốt báo giá thứ 2 bị chặn", "P0",
  "DA-01 đã có BG-60 Trúng thầu; BG-62 cũng Đã duyệt cùng dự án",
  "1. Bấm chốt BG-62",
  "—",
  "- Bị chặn 'Dự án đã có báo giá trúng thầu, vui lòng hủy chốt trước.'\n- BG-60 vẫn giữ trạng thái Trúng thầu",
  "1 dự án chỉ 1 báo giá trúng thầu"),
 ("", "Hủy chốt báo giá — bắt buộc lý do", "P0",
  "BG-60 đang Trúng thầu",
  "1. Bấm huỷ chốt → để trống lý do → xác nhận\n2. Nhập lý do → xác nhận",
  "—",
  "- Bỏ trống: ô lý do viền đỏ + báo lỗi, không xử lý\n- Có lý do: BG-60 quay lại trạng thái Đã duyệt, lịch sử ghi nhận lý do huỷ chốt",
  "unfinalize"),
 ("", "Sau khi huỷ chốt, chốt được báo giá khác", "P1",
  "BG-60 vừa huỷ chốt, BG-62 Đã duyệt",
  "1. Chốt BG-62",
  "—",
  "- Chốt thành công, BG-62 = Trúng thầu",
  "Ràng buộc 1 trúng thầu/dự án được giải phóng"),
 ("", "Đồng bộ ERP tự động sau khi duyệt", "P0",
  "BG-63 vừa được duyệt",
  "1. Xem cột ERP ở danh sách và thông tin đồng bộ ở chi tiết",
  "—",
  "- Báo giá được đẩy sang ERP; trạng thái đồng bộ thành công hoặc lỗi có mô tả rõ\n- Nếu thành công có mã tham chiếu bên ERP",
  "erp_sync_status"),
 ("", "Thử lại đồng bộ ERP khi lỗi", "P0",
  "BG-64 có trạng thái đồng bộ lỗi",
  "1. Bấm 'Thử lại đồng bộ' (ở danh sách hoặc chi tiết)\n2. Xem kết quả",
  "—",
  "- Chạy lại đồng bộ; thành công → trạng thái chuyển xanh; thất bại → giữ lỗi và cập nhật nội dung lỗi mới\n- Không tạo bản ghi trùng bên ERP",
  "retrySync"),
 ("", "Gửi duyệt hàng tạm sang ERP", "P0",
  "BG-65 có 3 hàng tạm chưa đồng bộ",
  "1. Bấm 'Gửi duyệt hàng tạm' (cấp báo giá hoặc cấp dự án ở tab Báo giá)\n2. Xem trạng thái đồng bộ hàng tạm",
  "3 hàng tạm",
  "- Yêu cầu tạo sản phẩm tạm được gửi sang ERP, trạng thái chuyển 'đã gửi'\n- Ghi nhận mã phiếu yêu cầu bên ERP",
  "sendTmpApproval"),
 ("", "Kéo kết quả duyệt hàng tạm từ ERP", "P0",
  "BG-65 đã gửi duyệt hàng tạm; bên ERP đã duyệt và cấp mã sản phẩm",
  "1. Bấm 'Cập nhật kết quả' (pull)\n2. Xem mã hàng của các dòng hàng tạm",
  "—",
  "- Các dòng được gắn mã ERP mới, trạng thái đồng bộ chuyển 'đã đồng bộ'\n- Dữ liệu giá/số lượng không bị đổi",
  "pullTmpApproval"),
 ("", "Hàng hoá dự án — hàng tạm hiện đúng, không lặp", "P1",
  "Dự án 38 có 2 báo giá cùng dùng hàng tạm mã HHBG000701",
  "1. Mở màn Hàng hoá dự án lọc theo dự án 38\n2. Tìm mã HHBG000701",
  "2 báo giá cùng mã",
  "- Chỉ hiện 1 dòng cho (mã + dự án), không lặp\n- Dòng đại diện ưu tiên báo giá Trúng thầu > Đã duyệt, cùng trạng thái thì lấy bản mới nhất\n"
  "- Hàng ERP GỐC (chọn từ popup ERP) không hiển thị ở màn này",
  "Dedup + filterOutNativeErp"),
])

S10 = ("X", "IN ẤN BÁO GIÁ", [
 ("", "Mở cấu hình in và in báo giá", "P0",
  "BG-70 có 8 dòng hàng hoá (có cha-con), 2 dịch vụ, nhóm 2 cấp",
  "1. Mở BG-70 → bấm 'In'\n2. Quan sát popup 'Cấu hình in báo giá' → bấm In",
  "—",
  "- Popup có: checkbox hiển thị hàng cấp con, checkbox 'Chọn tất cả', danh sách cột chọn được\n"
  "- Bản xem trước hiện đúng thông tin công ty/khách hàng/hàng hoá\n- Hộp thoại in bật lên (không phải tự bấm Ctrl+P)",
  "QuotationPrintConfigModal + PrintPreview"),
 ("", "Chọn/bỏ cột in", "P0",
  "Popup cấu hình in đang mở",
  "1. Bỏ tích Model, Xuất xứ; giữ Ghi chú → In\n2. Đối chiếu bản in",
  "—",
  "- Bản in không còn 2 cột đã bỏ, vẫn có cột Ghi chú đúng nội dung từng dòng\n- Bảng không vỡ, không thừa cột trắng",
  "Cột Ghi chú mặc định hiện"),
 ("", "Cột giảm giá trên bản in đổi theo Loại GG", "P0",
  "BG-71 GG mặt hàng; BG-72 GG tổng; BG-73 không GG",
  "1. Mở cấu hình in từng báo giá → xem danh sách cột chọn được",
  "—",
  "- BG-71: có GG (%), GG (₫), Đơn giá sau GG\n- BG-72: có GG phân bổ\n- BG-73: không có cột giảm giá nào",
  "Cột in động theo discount_method"),
 ("", "Bản in hiển thị nhóm 2 cấp thụt lề", "P0",
  "BG-70 có nhóm Cấp 1 và Cấp 2",
  "1. In BG-70 → xem dòng tiêu đề nhóm",
  "—",
  "- Nhóm Cấp 1 đánh số La Mã 'I. ...'; nhóm Cấp 2 'I.1 ...' và thụt lề\n- Hàng hoá nằm dưới đúng nhóm",
  "Bản in thể hiện phân cấp"),
 ("", "Ẩn hàng cấp con khi in", "P1",
  "BG-70 có cha-con",
  "1. Bỏ tích 'hiển thị hàng cấp con' → In",
  "—",
  "- Bản in chỉ còn dòng cha, tiền dòng cha vẫn đúng (roll-up), tổng không đổi",
  "includeChildren khi in"),
 ("", "In báo giá từ màn danh sách", "P1",
  "BG-70 trong danh sách",
  "1. Bấm icon 'In báo giá' ở dòng BG-70",
  "—",
  "- Mở đúng cấu hình in của BG-70, in ra đúng dữ liệu báo giá đó",
  "In ngay từ danh sách"),
 ("", "In nhiều trang — không mất viền, không cắt cột", "P1",
  "BG-74 có 60 dòng hàng hoá",
  "1. In BG-74 → xem bản PDF nhiều trang",
  "60 dòng",
  "- Mỗi trang có đủ viền bảng, không mất viền phải/dưới khi sang trang\n- Không cột nào bị cắt/tràn lề phải\n- Header bảng lặp lại ở trang sau (nếu thiết kế có)",
  "Chuẩn màn in của dự án"),
 ("", "Bản in báo giá ngoại tệ", "P2",
  "BG-75 tiền tệ USD",
  "1. In BG-75",
  "—",
  "- Số tiền và ký hiệu tiền tệ hiển thị đúng USD, tổng tiền bằng chữ (nếu có) khớp đơn vị",
  "Đơn vị tiền tệ trên bản in"),
])

S11 = ("XI", "EXPORT / IMPORT / SAO CHÉP — MỨC LIÊN THÔNG", [
 ("", "Xuất Excel báo giá từ màn Xem và màn Sửa cho ra CÙNG loại file", "P0",
  "BG-80 (Loại GG = Không), người tạo",
  "1. Màn Xem → 'Xuất Excel' → mở file\n2. Màn Sửa → 'Xuất Excel' → mở file\n3. So sánh 2 file",
  "—",
  "- Cả 2 nút cho ra cùng bản dữ liệu round-trip theo Loại GG (22 cột với Không GG)\n"
  "- Tên file dạng {Mã BG}_{DD-MM-YYYY}.xlsx\n- Không nút nào lỗi HTTP",
  "2 nút đã trỏ cùng endpoint export-quotation-data"),
 ("", "Import Excel rồi Lưu — số liệu chảy đúng vào tổng hợp và cấp duyệt", "P0",
  "BG-81 Đang tạo; file Excel 2 dòng: 2×1.000.000 VAT 10% và 1×500.000 VAT 8%",
  "1. Import file → áp vào lưới → 'Lưu báo giá'\n2. Xem bảng Tổng hợp\n3. Bấm 'Gửi duyệt' → xem cấp duyệt",
  "Tiền hàng 2.500.000",
  "- Tổng tiền hàng 2.500.000, VAT 240.000, tổng sau VAT 2.740.000\n- Cấp duyệt tính trên số liệu MỚI sau import",
  "Import → tổng hợp → cấp duyệt"),
 ("", "Sao chép báo giá rồi thao tác trên bản sao", "P0",
  "BG-82 Đã duyệt",
  "1. Bấm 'Sao chép' → xác nhận (nếu có popup thay đổi ERP)\n2. Ở bản sao: sửa 1 dòng → Lưu → Gửi duyệt",
  "—",
  "- Bản sao ở trạng thái Đang tạo, mã mới, người tạo là người sao chép\n- Sửa/Lưu/Gửi duyệt chạy như báo giá thường; cấp duyệt tính lại theo số liệu bản sao\n"
  "- Báo giá gốc không đổi",
  "Chi tiết đầy đủ ở testcase riêng"),
 ("", "Import/Export/Sao chép không phá quan hệ nhóm 2 cấp", "P1",
  "BG-83 có nhóm 2 cấp và cha-con hàng hoá",
  "1. Xuất Excel → Import lại → Lưu\n2. Sao chép báo giá\n3. In cả 2 bản",
  "—",
  "- Sau round-trip: cây nhóm và cha-con nguyên vẹn\n- Bản sao giữ đúng cây nhóm\n- Bản in của cả 2 thể hiện đúng phân cấp",
  "Liên thông 4 luồng"),
 ("", "Nút Import không xuất hiện khi báo giá không sửa được", "P0",
  "BG-84 Đã duyệt",
  "1. Mở BG-84 (Xem/Sửa)",
  "—",
  "- Không có nút 'Import Excel'\n- Nút 'Xuất Excel', 'In' vẫn dùng được",
  "AC4 của feature import"),
])

S12_OLD = ("XII", "XOÁ, LỊCH SỬ & EDGE CASES", [
 ("", "Xoá báo giá ở trạng thái Đang tạo (người tạo)", "P0",
  "BG-90 Đang tạo, do user đang đăng nhập tạo, có 5 dòng + 2 dịch vụ",
  "1. Mở BG-90 → bấm 'Xoá' → xác nhận\n2. Quay lại danh sách",
  "—",
  "- Có hộp xác nhận trước khi xoá\n- Sau khi xoá: báo giá biến mất khỏi danh sách, mở lại link cũ báo không tồn tại\n"
  "- Các dòng hàng hoá/dịch vụ liên quan cũng bị xoá, không để dữ liệu rác",
  "destroy"),
 ("", "Không xoá được báo giá đã gửi duyệt / đã duyệt", "P0",
  "BG-91 Chờ TP duyệt; BG-92 Đã duyệt",
  "1. Mở từng báo giá → tìm nút Xoá\n2. Gọi thẳng API xoá",
  "—",
  "- Không có nút Xoá\n- Gọi API bị chặn, báo giá vẫn còn nguyên",
  "Chỉ xoá được khi Đang tạo + đúng người tạo"),
 ("", "Xem Lịch sử phê duyệt từ danh sách", "P1",
  "BG-93 đã qua nhiều mốc",
  "1. Bấm icon 'Lịch sử phê duyệt' ở dòng BG-93",
  "—",
  "- Mở popup lịch sử đúng báo giá đó, đủ mốc, sắp xếp theo thời gian",
  "Popup lịch sử dùng chung"),
 ("", "Mở báo giá không tồn tại / không thuộc phạm vi", "P1",
  "id báo giá không tồn tại; và 1 báo giá ngoài phạm vi dữ liệu của user",
  "1. Mở /assign/quotations/999999\n2. Mở báo giá ngoài phạm vi",
  "—",
  "- Hiện thông báo không tìm thấy / không có quyền, không vỡ trang, không lộ dữ liệu",
  "scopedQuotationQuery → 404"),
 ("", "Báo giá có 300+ dòng — hiệu năng màn Sửa", "P2",
  "BG-94 có 300 dòng hàng hoá",
  "1. Mở màn Sửa → cuộn lưới → sửa 1 ô số lượng → Lưu",
  "300 dòng",
  "- Trang tải xong không treo; cuộn mượt\n- Sửa 1 ô tính lại tổng đúng, không đơ\n- Lưu thành công, đủ 300 dòng",
  "Ngưỡng dữ liệu lớn"),
 ("", "Ký tự đặc biệt trong tên hàng / ghi chú", "P1",
  "BG-95 có dòng tên hàng '=Bơm <2HP> & \"Vòng bi\"'",
  "1. Lưu → mở lại → In → Xuất Excel",
  "—",
  "- Hiển thị nguyên văn ở lưới, bản in và file Excel\n- Không lỗi export, không dính lỗi hiển thị HTML",
  "Chuỗi bắt đầu '=' từng gây sập export"),
 ("", "Độ dài vượt giới hạn bị chặn ở tầng ứng dụng", "P0",
  "BG-96",
  "1. Nhập Tên hàng 300 ký tự, Ghi chú 600 ký tự → Lưu\n2. Nếu lưu được, mở lại kiểm tra nội dung",
  "300 / 600 ký tự",
  "- Hệ thống báo lỗi vượt độ dài\n- KHÔNG được lưu bản bị cắt cụt (DB không chạy strict mode nên phải chặn ở ứng dụng)",
  "Cảnh báo mất dữ liệu âm thầm"),
 ("", "Hai người mở cùng 1 báo giá và cùng lưu", "P2",
  "BG-97 mở trên 2 phiên",
  "1. Phiên 1 sửa giá → Lưu\n2. Phiên 2 (dữ liệu cũ) bấm Lưu\n3. Mở lại báo giá",
  "—",
  "- Không mất dữ liệu âm thầm: hệ thống hoặc báo cần tải lại, hoặc kết quả cuối cùng nhất quán và kiểm chứng được",
  "Ghi nhận hành vi thực tế để đánh giá rủi ro"),
 ("", "Thao tác khi mất kết nối / API lỗi", "P2",
  "BG-98 màn Sửa",
  "1. Ngắt mạng → bấm Lưu\n2. Bật lại mạng → bấm Lưu",
  "—",
  "- Lần 1: hiện thông báo lỗi rõ ràng, không mất dữ liệu đang nhập trên form\n- Lần 2: lưu thành công",
  "Chống mất dữ liệu khi lỗi mạng"),
])

# ===== Gộp nội dung Export / Import / Sao chép (phần thuộc BÁO GIÁ) =====
# Phân quyền: TC 1-9 + 12 của section nguồn là của báo giá (10, 11 là của BOM).
S1 = (S1[0], S1[1], S1[2] + pick(EIC.S1, [1, 2, 3, 4, 5, 6, 7, 8, 9, 12]))

S11 = ("XI", "NHÓM HÀNG 2 CẤP & KÉO-THẢ SẮP XẾP NHÓM", EIC.S10[2])
S12 = ("XII", "EXPORT FILE CHI TIẾT BÁO GIÁ", EIC.S2[2])
S13 = ("XIII", "IMPORT BÁO GIÁ — CHỌN FILE, LOAD, VALIDATE", EIC.S3[2])
S14 = ("XIV", "IMPORT BÁO GIÁ — PHƯƠNG THỨC ÁP DỮ LIỆU & CROSS-IMPORT", EIC.S4[2])
S15 = ("XV", "SAO CHÉP BÁO GIÁ", EIC.S5[2])
# Round-trip & E2E: bỏ 2 TC thuần BOM (số 2 và 4 của section nguồn)
S16 = ("XVI", "ROUND-TRIP, CÔ LẬP DỮ LIỆU & E2E",
       pick(EIC.S9, [1, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]))
S17 = ("XVII", S12_OLD[1], S12_OLD[2])

SECTIONS = [S1, S2, S3, S4, S5, S6, S7, S8, S9, S10,
            S11, S12, S13, S14, S15, S16, S17]
SECTIONS = [
    (roman, title, [(f"{i:03d}",) + tuple(tc[1:]) for i, tc in enumerate(tcs, start=1)])
    for roman, title, tcs in SECTIONS
]

build(OUTPUT_FILE, SHEET_NAME, FEATURE_NAME, MODULE_NAME, DESCRIPTION_BLOCK, SECTIONS)
total = sum(len(s[2]) for s in SECTIONS)
p0 = sum(1 for s in SECTIONS for tc in s[2] if tc[2] == 'P0')
print(f"Tổng TC: {total} | P0: {p0} ({round(p0*100/total)}%)")
