"""Generate testcase — Phân quyền XEM DANH SÁCH TASK (/assign/tasks)."""
from _builder import build_testcase

OUTPUT_FILE  = "/Users/manhcuong/Desktop/dns/HRM/.plans/assign-list-view-permission/testcase-task.xlsx"
SHEET_NAME   = "PhanQuyenXemDS_Task"
FEATURE_NAME = "Phân quyền xem danh sách Task"
MODULE_NAME  = "Giao việc — Task"

DESCRIPTION_BLOCK = [
    ("1. Mục đích tính năng",
     "Kiểm thử cơ chế PHÂN QUYỀN XEM DANH SÁCH task (/assign/tasks): xác định mỗi user thấy được những task nào dựa trên "
     "(a) vai trò cá nhân trên task, (b) kế thừa cha-con, (c) là thành viên dự án/giải pháp, "
     "(d) quyền quản lý theo cấp tổ chức (tổng công ty / công ty / phòng ban / bộ phận), (e) vai trò động 'Duyệt triển khai task'."),
    ("2. Đối tượng được tính / hiển thị",
     "► Tầng 1 - vai trò cá nhân: created_by / assignee_id / approver_id / watcher là user.\n"
     "► Kế thừa: task CON của task mình giữ vai trò + task CHA của task mình giữ vai trò.\n"
     "► Tầng 2 - thành viên: mọi task thuộc solution_id / project_id mà user là thành viên.\n"
     "► Tầng 3 - quyền cấp (qua bảng snapshot task_org_units): 'theo tổng công ty' = thấy TẤT CẢ; "
     "'theo công ty' = org company_id = current_company_role; 'theo phòng ban' = org department_id ∈ phòng quản lý "
     "HOẶC part_id ∈ bộ phận quản lý; 'theo bộ phận' = org part_id ∈ bộ phận quản lý.\n"
     "► Vai trò động: có quyền 'Duyệt triển khai task' → thấy thêm task có assignee thuộc phòng user quản lý."),
    ("3. Đối tượng bị ẩn / không tính",
     "► Task user KHÔNG giữ vai trò, KHÔNG thuộc project/solution của user, và KHÔNG nằm trong phạm vi org được quyền.\n"
     "► User không có quyền scope nào → chỉ thấy task cá nhân + task project/solution mình tham gia.\n"
     "► Task của công ty khác công ty đang đăng nhập (trừ khi có quyền 'theo tổng công ty').\n"
     "► Quyền tính theo công ty đang đăng nhập (current_company_role); đổi công ty → phạm vi đổi theo."),
    ("4. Bộ lọc thời gian áp dụng cho",
     "deadline_from / deadline_to (hạn hoàn thành), from_date / to_date (ngày cập nhật). "
     "Bộ lọc thời gian KHÔNG nới rộng phân quyền — chỉ thu hẹp trong phạm vi đã được phép xem."),
    ("5. Cấu trúc dữ liệu / cây phân cấp",
     "► TaskService::applyPermissionScope() nối các tầng bằng OR (whereIn ... orWhereIn ...).\n"
     "► Org snapshot lưu ở bảng phụ task_org_units (company_id, department_id, part_id của MỌI người giữ vai trò), "
     "đồng bộ lại mỗi lần lưu task (syncTaskOrgUnits).\n"
     "► Helper: isCurrentEmployeeHasPermission (lọc quyền theo current_company_role), "
     "listManageDepartmentIds / listManageDepartmentIdsWithOwn (all_department=1 → mọi phòng), listManagePartIds."),
    ("6. Quy tắc cộng dồn / deduplicate",
     "Các tầng nối bằng OR; 1 task thỏa nhiều tầng vẫn chỉ hiển thị 1 dòng (distinct theo tasks.id). "
     "overdue_total đếm riêng (count due_date < hôm nay) TRÊN CÙNG query đã lọc phân quyền."),
    ("7. Phân quyền cấp",
     "• Xem danh sách task theo tổng công ty\n"
     "• Xem danh sách task theo công ty\n"
     "• Xem danh sách task theo phòng ban\n"
     "• Xem danh sách task theo bộ phận\n"
     "• Duyệt triển khai task  (vai trò động)\n"
     "(Định nghĩa tại Modules/Timesheet/Database/Seeders/PermissionsTableSeeder.php; guard_name='api')"),
    ("8. Cách tính các ô thống kê",
     "► Phạm vi DS = (tasks.id ∈ myDirectTaskIds) OR (tasks.parent_id ∈ myDirectTaskIds) OR (tasks.id ∈ myParentTaskIds) "
     "OR (solution_id ∈ mySolutionIds) OR (project_id ∈ myProjectIds) OR (id ∈ task_org_units thỏa tier3).\n"
     "► tier3 = company_id = current_company_role [quyền công ty] | (department_id ∈ managedDepts OR part_id ∈ managedParts) "
     "[quyền phòng ban] | part_id ∈ managedParts [quyền bộ phận].\n"
     "► 'theo tổng công ty' → return sớm, BỎ QUA toàn bộ điều kiện (thấy hết).\n"
     "► overdue_total = COUNT(due_date < hôm nay) trên query đã lọc."),
    ("9. Ghi chú đọc bảng",
     "► Route GET /v1/assign/tasks và /export KHÔNG gắn middleware checkPermission → MỌI user đăng nhập đều gọi được API "
     "(không trả 403); phân quyền là LỌC DỮ LIỆU ở Service, không chặn endpoint.\n"
     "► FE chỉ dùng 4 cờ permission (is_all_company/is_company/is_department/is_part) để ẩn/hiện ô filter org "
     "(V2BaseCompanyDepartmentFilter) và giới hạn option — FE KHÔNG tự lọc dữ liệu bảng.\n"
     "► Quyền nút từng dòng (can_edit/can_delete/can_approve/can_import_result) do BE trả riêng — NGOÀI phạm vi testcase này."),
]

ROLE_TCS = [
    ("00", "Mặc định — user KHÔNG có quyền scope nào", "P0",
     "User U1 không có bất kỳ quyền 'Xem danh sách task theo ...'. Dữ liệu: 2 task U1 là assignee, 1 task U1 tạo; "
     "5 task của người khác (U1 không liên quan).",
     "1. Đăng nhập U1\n2. Vào /assign/tasks\n3. Quan sát danh sách",
     "User: U1 (0 quyền scope)",
     "- Chỉ thấy 3 task U1 giữ vai trò (+ task của solution/project U1 là thành viên nếu có)\n- KHÔNG thấy 5 task của người khác",
     "BR — applyPermissionScope luôn áp dụng tầng 1-2 kể cả khi không có quyền cấp"),
    ("01", "Quyền 'Xem danh sách task theo tổng công ty'", "P0",
     "User U2 có quyền 'Xem danh sách task theo tổng công ty'. Hệ thống có task ở ≥2 công ty.",
     "1. Đăng nhập U2\n2. Vào /assign/tasks\n3. Quan sát phạm vi",
     "User: U2 (quyền tổng công ty)",
     "- Thấy TOÀN BỘ task của MỌI công ty (không giới hạn)\n- Ô filter Công ty hiển thị đầy đủ",
     "Permission: Xem danh sách task theo tổng công ty → return sớm, không lọc"),
    ("02", "Quyền 'Xem danh sách task theo công ty'", "P0",
     "User U3 đăng nhập công ty C1 (current_company_role=C1), có quyền 'Xem danh sách task theo công ty'. "
     "Task org: 4 thuộc C1, 3 thuộc C2.",
     "1. Đăng nhập U3 (C1)\n2. Vào /assign/tasks\n3. Quan sát",
     "User: U3, công ty C1",
     "- Thấy 4 task org thuộc C1 (+ task cá nhân/project)\n- KHÔNG thấy 3 task org chỉ thuộc C2",
     "Permission: Xem danh sách task theo công ty → tier3: company_id = current_company_role"),
    ("03", "Quyền 'Xem danh sách task theo phòng ban'", "P0",
     "User U4 quản lý phòng D1 (managedDepts=[D1], managedParts=[P1]); quyền 'theo phòng ban'. "
     "Task org: 3 thuộc D1, 2 thuộc P1, 4 thuộc phòng D2 khác.",
     "1. Đăng nhập U4\n2. Vào /assign/tasks\n3. Quan sát",
     "User: U4, quản lý D1/P1",
     "- Thấy task org có department_id ∈ [D1] HOẶC part_id ∈ [P1] (3+2)\n- KHÔNG thấy 4 task org của D2",
     "Permission: Xem danh sách task theo phòng ban → department_id ∈ managedDepts OR part_id ∈ managedParts"),
    ("04", "Quyền 'Xem danh sách task theo bộ phận'", "P0",
     "User U5 quản lý bộ phận P1 (managedParts=[P1]); quyền 'theo bộ phận'. Task org: 3 thuộc P1, 4 thuộc P2 khác.",
     "1. Đăng nhập U5\n2. Vào /assign/tasks\n3. Quan sát",
     "User: U5, quản lý P1",
     "- Chỉ thấy 3 task org có part_id ∈ [P1]\n- KHÔNG thấy 4 task org của P2",
     "Permission: Xem danh sách task theo bộ phận → tier3: part_id ∈ managedParts"),
    ("05", "Vai trò động 'Duyệt triển khai task'", "P1",
     "User U6 có quyền 'Duyệt triển khai task', quản lý phòng D1 (listManageDepartmentIdsWithOwn=[D1]). "
     "Task T9: assignee là NV thuộc D1, U6 KHÔNG giữ vai trò nào trên T9.",
     "1. Đăng nhập U6\n2. Vào /assign/tasks\n3. Tìm task T9",
     "User: U6, Duyệt triển khai task, quản lý D1",
     "- Thấy T9 vì assignee của T9 thuộc phòng D1 U6 quản lý",
     "Permission: Duyệt triển khai task → orWhereHas(assignee.info.department_id ∈ managedDepts)"),
    ("06", "Endpoint KHÔNG bị chặn bởi checkPermission", "P0",
     "User U1 không có quyền scope nào, đã đăng nhập (token hợp lệ).",
     "1. Gọi GET /v1/assign/tasks bằng token U1",
     "User: U1, token hợp lệ",
     "- HTTP 200 (KHÔNG trả 403/Forbidden)\n- data đã bị LỌC theo vai trò U1 (không lộ task người khác)",
     "BR — Route index chỉ gắn auth:api, phân quyền = lọc data không chặn endpoint"),
    ("07", "Quyền tính theo CÔNG TY ĐANG ĐĂNG NHẬP", "P1",
     "User U7 có quyền 'theo công ty' ở C1 nhưng KHÔNG có ở C2. U7 thuộc cả 2 công ty.",
     "1. Đăng nhập U7 chọn C1 → /assign/tasks\n2. Đổi sang C2 → /assign/tasks",
     "User: U7; C1 có quyền, C2 không",
     "- Ở C1: thấy task org của C1\n- Ở C2: chỉ thấy task cá nhân (quyền không áp dụng ở C2)",
     "isCurrentEmployeeHasPermission lọc theo current_company_role"),
]

SECTIONS = [
    ("I", "HIỂN THỊ TRANG & TRUY CẬP ENDPOINT", [
        ("001", "Truy cập trang danh sách Task", "P1",
         "User U2 (quyền tổng công ty) đã đăng nhập.",
         "1. Vào /assign/tasks\n2. Quan sát layout",
         "User: U2",
         "- Trang load thành công: panel filter + bảng V2BaseDataTable + nút Tạo mới/Xuất Excel/Cấu hình cột\n- Badge 'Quá hạn' hiển thị overdue_total",
         "BR — Mọi user đăng nhập đều vào được trang"),
        ("002", "User KHÔNG quyền scope vẫn truy cập được trang", "P0",
         "User U1 (0 quyền scope), KHÔNG giữ vai trò trên bất kỳ task nào.",
         "1. Đăng nhập U1\n2. Vào /assign/tasks",
         "User: U1",
         "- Trang load thành công (không 403)\n- Danh sách có thể RỖNG (vì U1 không giữ vai trò/không thuộc project nào)",
         "BR — Không chặn endpoint; data rỗng là hợp lệ"),
        ("003", "Export Task dùng CÙNG phạm vi phân quyền với index", "P1",
         "User U3 (quyền 'theo công ty', C1). Index hiển thị N task.",
         "1. Vào /assign/tasks\n2. Bấm Xuất Excel\n3. Mở file đối chiếu",
         "User: U3, công ty C1",
         "- File export chứa ĐÚNG N task như index (cùng applyPermissionScope), không có task ngoài phạm vi",
         "BR — TaskController::export gọi cùng taskService->index()"),
        ("004", "overdue_total đếm trong phạm vi đã lọc", "P1",
         "User U3 (quyền 'theo công ty'). Trong phạm vi: 2 task due_date < hôm nay; ngoài phạm vi: 5 task quá hạn.",
         "1. Vào /assign/tasks\n2. Đọc badge 'Quá hạn'",
         "Hôm nay = 18/06/2026; User: U3",
         "- Badge 'Quá hạn' = 2 (chỉ đếm trong phạm vi user thấy)\n- KHÔNG cộng 5 task quá hạn ngoài phạm vi",
         "Công thức: overdue_total = COUNT(due_date < today) trên query đã applyPermissionScope"),
    ]),
    ("II", "BỘ LỌC TỔ CHỨC THEO QUYỀN (FE)", [
        ("001", "Quyền tổng công ty → hiện đủ 3 ô filter org", "P0",
         "User U2 có 'Xem danh sách task theo tổng công ty' (is_all_company=true).",
         "1. Vào /assign/tasks\n2. Mở panel filter",
         "User: U2",
         "- Hiện đủ 3 ô: Công ty, Phòng ban, Bộ phận\n- Ô Công ty liệt kê tất cả công ty",
         "FE: V2BaseCompanyDepartmentFilter — ô Công ty v-if is_all_company"),
        ("002", "Chỉ quyền 'theo công ty' → ẨN ô Công ty", "P0",
         "User U3 chỉ có 'Xem danh sách task theo công ty' (is_company=true, is_all_company=false).",
         "1. Vào /assign/tasks\n2. Mở panel filter",
         "User: U3",
         "- ẨN ô Công ty\n- HIỆN ô Phòng ban + Bộ phận",
         "FE: Phòng ban v-if (all_company||company||department)"),
        ("003", "Chỉ quyền 'theo phòng ban' → ẩn Công ty, hiện Phòng ban + Bộ phận", "P1",
         "User U4 chỉ có 'Xem danh sách task theo phòng ban' (is_department=true).",
         "1. Vào /assign/tasks\n2. Mở panel filter",
         "User: U4",
         "- ẨN ô Công ty\n- HIỆN Phòng ban + Bộ phận",
         "FE: Bộ phận v-if (all_company||company||department||part)"),
        ("004", "Chỉ quyền 'theo bộ phận' → chỉ hiện ô Bộ phận", "P1",
         "User U5 chỉ có 'Xem danh sách task theo bộ phận' (is_part=true).",
         "1. Vào /assign/tasks\n2. Mở panel filter",
         "User: U5",
         "- ẨN Công ty + Phòng ban\n- CHỈ HIỆN ô Bộ phận",
         "FE: chỉ Bộ phận thỏa điều kiện v-if"),
        ("005", "Không quyền scope → ẩn HẾT ô filter org", "P0",
         "User U1 không có quyền scope nào (mọi cờ permission=false).",
         "1. Vào /assign/tasks\n2. Mở panel filter",
         "User: U1",
         "- ẨN cả 3 ô Công ty/Phòng ban/Bộ phận\n- Vẫn còn các filter khác (Giải pháp, Dự án, Trạng thái...)",
         "FE: tất cả ô org v-if đều false"),
        ("006", "Option Phòng ban giới hạn theo phòng user quản lý", "P1",
         "User U4 có 'theo phòng ban', manager_department_ids=[D1,D3]. Hệ thống có 10 phòng.",
         "1. Vào /assign/tasks\n2. Mở dropdown Phòng ban",
         "User: U4, quản lý D1,D3",
         "- Dropdown CHỈ liệt kê D1, D3 (không hiện 8 phòng còn lại)",
         "FE: availableDepartments lọc theo auth.manager_department_ids"),
        ("007", "Ô Nhân viên trong filter org bị ẩn (disable_employee)", "P2",
         "User U2 (tổng công ty) ở màn Task.",
         "1. Vào /assign/tasks\n2. Mở panel filter org",
         "User: U2",
         "- KHÔNG có ô 'Nhân viên' trong V2BaseCompanyDepartmentFilter (disable_employee=true)",
         "FE: prop :disable_employee=true"),
    ]),
    ("III", "PHẠM VI DỮ LIỆU — VAI TRÒ CÁ NHÂN & QUYỀN CẤP", [
        ("001", "Assignee thấy task được giao", "P0",
         "User U8 là assignee_id của task T1; không có quyền scope.",
         "1. Đăng nhập U8\n2. Vào /assign/tasks",
         "User: U8 (assignee T1)",
         "- Thấy T1 trong danh sách",
         "Tầng 1: assignee_id = userId"),
        ("002", "Người tạo thấy task mình tạo", "P0",
         "User U8 là created_by của task T2.",
         "1. Đăng nhập U8\n2. Vào /assign/tasks",
         "User: U8 (created_by T2)",
         "- Thấy T2",
         "Tầng 1: created_by = userId"),
        ("003", "Người duyệt thấy task mình duyệt", "P0",
         "User U8 là approver_id của task T3.",
         "1. Đăng nhập U8\n2. Vào /assign/tasks",
         "User: U8 (approver T3)",
         "- Thấy T3",
         "Tầng 1: approver_id = userId"),
        ("004", "Người theo dõi (watcher) thấy task theo dõi", "P1",
         "User U8 là watcher của task T4.",
         "1. Đăng nhập U8\n2. Vào /assign/tasks",
         "User: U8 (watcher T4)",
         "- Thấy T4",
         "Tầng 1: whereHas watchers.employee_id = userId"),
        ("005", "Quyền 'theo công ty' thấy task org công ty mình", "P0",
         "User U3 (C1, quyền theo công ty). Task T5 org company_id=C1 (U3 không giữ vai trò trên T5).",
         "1. Đăng nhập U3 (C1)\n2. Vào /assign/tasks",
         "User: U3, công ty C1",
         "- Thấy T5 (qua tier3 company_id=C1)",
         "Tầng 3: task_org_units.company_id = current_company_role"),
        ("006", "Quyền 'theo phòng ban' thấy task org phòng quản lý", "P0",
         "User U4 (quản lý D1, quyền theo phòng ban). Task T6 org department_id=D1.",
         "1. Đăng nhập U4\n2. Vào /assign/tasks",
         "User: U4, quản lý D1",
         "- Thấy T6 qua tier3 (department_id ∈ managedDepts)",
         "Tầng 3: department_id ∈ managedDepts OR part_id ∈ managedParts"),
        ("007", "Quyền 'theo bộ phận' KHÔNG thấy task của bộ phận khác", "P1",
         "User U5 (quản lý P1, quyền theo bộ phận). Task T7 org part_id=P2 (U5 không liên quan).",
         "1. Đăng nhập U5\n2. Vào /assign/tasks\n3. Tìm T7",
         "User: U5, quản lý P1",
         "- KHÔNG thấy T7 (part_id=P2 không thuộc managedParts)",
         "Tầng 3 bộ phận: chỉ part_id ∈ managedParts"),
        ("008", "Quyền 'theo tổng công ty' thấy mọi task", "P0",
         "User U2 (quyền tổng công ty). Task ở C1, C2; có task U2 không liên quan.",
         "1. Đăng nhập U2\n2. Vào /assign/tasks",
         "User: U2",
         "- Thấy TẤT CẢ task không phân biệt công ty/vai trò",
         "Return sớm trong applyPermissionScope"),
        ("009", "Filter company_id user chọn KHÔNG vượt quyền", "P1",
         "User U3 (quyền theo công ty C1). U3 chỉnh filter company_id=C2.",
         "1. Đăng nhập U3 (C1)\n2. Đặt filter company_id=C2\n3. Quan sát",
         "User: U3; filter company_id=C2",
         "- KHÔNG lộ task org của C2 (applyPermissionScope vẫn giới hạn C1)\n- Kết quả ⊆ phạm vi C1",
         "applyOrgFilter là AND thêm, không thay applyPermissionScope"),
        ("010", "Task hoàn toàn không liên quan + ngoài org → ẩn", "P0",
         "User U1 (0 quyền). Task T8: U1 không giữ vai trò, không thuộc project/solution U1, org không liên quan.",
         "1. Đăng nhập U1\n2. Vào /assign/tasks\n3. Tìm T8",
         "User: U1",
         "- KHÔNG thấy T8",
         "Không thỏa tầng nào → bị loại"),
    ]),
    ("IV", "KẾ THỪA & THÀNH VIÊN DỰ ÁN / GIẢI PHÁP", [
        ("001", "Thấy task CON của task mình giữ vai trò (Cha→Con)", "P1",
         "User U8 là assignee task cha TP1. TP1 có 2 task con TC1, TC2 (U8 không giữ vai trò trên con).",
         "1. Đăng nhập U8\n2. Vào /assign/tasks",
         "User: U8 (assignee TP1)",
         "- Thấy TP1 + TC1 + TC2 (orWhereIn parent_id ∈ myDirectTaskIds)",
         "Kế thừa Cha→Con: tasks.parent_id ∈ myDirectTaskIds"),
        ("002", "Thấy task CHA của task mình giữ vai trò (Con→Cha)", "P1",
         "User U8 là assignee task con TC3 (parent = TP2). U8 không giữ vai trò trên TP2.",
         "1. Đăng nhập U8\n2. Vào /assign/tasks",
         "User: U8 (assignee TC3)",
         "- Thấy TC3 + TP2 (myParentTaskIds)",
         "Kế thừa Con→Cha: tasks.id ∈ myParentTaskIds"),
        ("003", "Thành viên giải pháp thấy mọi task của giải pháp", "P0",
         "User U9 là thành viên solution S1 (không giữ vai trò task nào). S1 có 5 task.",
         "1. Đăng nhập U9\n2. Vào /assign/tasks",
         "User: U9 (thành viên S1)",
         "- Thấy cả 5 task có solution_id=S1",
         "Tầng 2: solution_id ∈ mySolutionIds"),
        ("004", "Thành viên dự án thấy mọi task của dự án", "P0",
         "User U9 là thành viên project PR1. PR1 có 4 task.",
         "1. Đăng nhập U9\n2. Vào /assign/tasks",
         "User: U9 (thành viên PR1)",
         "- Thấy cả 4 task có project_id=PR1",
         "Tầng 2: project_id ∈ myProjectIds"),
        ("005", "Task thỏa NHIỀU tầng vẫn hiển thị 1 dòng (dedup)", "P1",
         "Task T10: U8 vừa là assignee (tầng 1), vừa thuộc solution của T10 (tầng 2), vừa nằm trong org U8 quản lý (tầng 3).",
         "1. Đăng nhập U8 (đủ 3 điều kiện)\n2. Vào /assign/tasks\n3. Đếm T10 xuất hiện",
         "User: U8",
         "- T10 chỉ xuất hiện ĐÚNG 1 dòng (không nhân bản)",
         "OR + distinct theo tasks.id"),
    ]),
    ("V", "EDGE CASES & VALIDATION", [
        ("001", "User all_department=1 → quản lý mọi phòng công ty", "P1",
         "User U10 có CompanyEmployee.all_department=1, quyền 'theo phòng ban'. Công ty C1 có 6 phòng.",
         "1. Đăng nhập U10\n2. Vào /assign/tasks",
         "User: U10, all_department=1",
         "- managedDepts = TẤT CẢ 6 phòng C1\n- Thấy task org thuộc bất kỳ phòng nào của C1",
         "listManageDepartmentIds: all_department=1 → mọi phòng công ty"),
        ("002", "Đổi công ty đăng nhập → phạm vi đổi theo", "P0",
         "User U7 thuộc C1 & C2; quyền 'theo công ty' chỉ ở C1.",
         "1. Đăng nhập C1 → /assign/tasks (ghi nhận DS)\n2. Đổi sang C2 → /assign/tasks",
         "User: U7",
         "- C1: thấy task org C1\n- C2: chỉ thấy task cá nhân (current_company_role=C2, không có quyền)",
         "current_company_role quyết định cả quyền lẫn tier3.company_id"),
        ("003", "User vừa giữ vai trò vừa có quyền scope → hợp (OR)", "P1",
         "User U11 có quyền 'theo bộ phận P1'. Ngoài task org P1, U11 còn là assignee task T12 ở bộ phận P9 khác.",
         "1. Đăng nhập U11\n2. Vào /assign/tasks",
         "User: U11, quản lý P1, assignee T12 (P9)",
         "- Thấy task org P1 + thấy T12 (vì giữ vai trò) — không mất task cá nhân dù khác bộ phận",
         "OR giữa tầng 1 và tầng 3"),
        ("004", "Org snapshot cập nhật khi đổi assignee", "P1",
         "Task T13 assignee ban đầu thuộc P1. Sau đó đổi assignee sang NV thuộc P2. User U12 quản lý P2.",
         "1. Đổi assignee T13 sang NV P2 (lưu)\n2. Đăng nhập U12 (quản lý P2)\n3. Vào /assign/tasks",
         "User: U12, quản lý P2",
         "- U12 thấy T13 (task_org_units đã sync part_id=P2)",
         "syncTaskOrgUnits chạy mỗi lần lưu"),
        ("005", "Có quyền phòng ban nhưng không quản lý phòng nào", "P1",
         "User U13 có quyền 'theo phòng ban' nhưng managedDepts=[] và managedParts=[].",
         "1. Đăng nhập U13\n2. Vào /assign/tasks",
         "User: U13, managedDepts=[]",
         "- tier3 whereIn([]) không khớp bản ghi nào → chỉ thấy task cá nhân/project\n- KHÔNG lỗi, KHÔNG lộ toàn bộ",
         "whereIn mảng rỗng → không mở rộng phạm vi"),
    ]),
    ("VI", "CÔ LẬP DỮ LIỆU & BẢO MẬT", [
        ("001", "User A không thấy task RIÊNG của user B", "P0",
         "User A và B khác phòng, không chung project/solution. Task TB của B (A không giữ vai trò, không cùng org). A không có quyền scope.",
         "1. Đăng nhập A\n2. Vào /assign/tasks\n3. Tìm TB",
         "User: A; TB thuộc B",
         "- A KHÔNG thấy TB",
         "Cô lập: không thỏa tầng nào"),
        ("002", "Filter company_id công ty khác không lộ dữ liệu", "P0",
         "User U3 chỉ quyền 'theo công ty' C1. Cố lọc company_id=C2.",
         "1. Đăng nhập U3 (C1)\n2. Gọi /assign/tasks?company_id=C2",
         "User: U3; company_id=C2",
         "- KHÔNG trả task org C2 (applyPermissionScope C1 ∩ filter C2 ở phần org C2 = rỗng)",
         "Filter là AND, không bypass scope"),
        ("003", "Gọi API trực tiếp (Postman) không bypass phân quyền", "P0",
         "User U1 (0 quyền) lấy token, gọi thẳng API bỏ qua FE.",
         "1. Lấy Bearer token U1\n2. GET /api/v1/assign/tasks (Postman)",
         "User: U1, token hợp lệ",
         "- Response 200 nhưng data vẫn bị applyPermissionScope lọc (không lộ task người khác)\n- Không có param nào bỏ được lọc",
         "Phân quyền ở Service (server-side), FE chỉ là UI"),
        ("004", "Export không bypass phân quyền", "P0",
         "User U1 (0 quyền) gọi endpoint export trực tiếp.",
         "1. GET /api/v1/assign/tasks/export bằng token U1",
         "User: U1",
         "- File export chỉ chứa task trong phạm vi U1, không lộ toàn bộ",
         "export gọi cùng index()"),
        ("005", "Quyền ở công ty A không áp dụng khi đăng nhập công ty B", "P1",
         "User U7 có quyền 'theo công ty' gán ở C1. Đăng nhập C2.",
         "1. Đăng nhập U7 chọn C2\n2. Vào /assign/tasks",
         "User: U7 đăng nhập C2",
         "- Quyền không hiệu lực ở C2 → chỉ thấy task cá nhân/project\n- KHÔNG thấy task org C2",
         "isCurrentEmployeeHasPermission lọc theo company_id=current_company_role"),
    ]),
]

build_testcase(OUTPUT_FILE, SHEET_NAME, FEATURE_NAME, MODULE_NAME,
               DESCRIPTION_BLOCK, ROLE_TCS, SECTIONS)
