"""Generate testcase — Phân quyền XEM DANH SÁCH ISSUE (/assign/issues)."""
from _builder import build_testcase

OUTPUT_FILE  = "/Users/manhcuong/Desktop/dns/HRM/.plans/assign-list-view-permission/testcase-issue.xlsx"
SHEET_NAME   = "PhanQuyenXemDS_Issue"
FEATURE_NAME = "Phân quyền xem danh sách Issue"
MODULE_NAME  = "Giao việc — Issue"

DESCRIPTION_BLOCK = [
    ("1. Mục đích tính năng",
     "Kiểm thử cơ chế PHÂN QUYỀN XEM DANH SÁCH issue (/assign/issues): xác định mỗi user thấy được những issue nào dựa trên "
     "(a) vai trò cá nhân trên issue, (b) là thành viên dự án/giải pháp, "
     "(c) quyền quản lý theo cấp tổ chức (tổng công ty / công ty / phòng ban / bộ phận). "
     "LƯU Ý: Issue KHÔNG có kế thừa cha-con và KHÔNG có vai trò động 'Duyệt triển khai' như Task."),
    ("2. Đối tượng được tính / hiển thị",
     "► Tầng 1 - vai trò cá nhân (6 vai trò): creator_id / detected_by / assignee_id / approver_id / watcher / supporter là user.\n"
     "► Tầng 2 - thành viên: mọi issue thuộc solution_id / project_id mà user là thành viên.\n"
     "► Tầng 3 - quyền cấp (qua bảng snapshot issue_org_units): 'theo tổng công ty' = thấy TẤT CẢ; "
     "'theo công ty' = org company_id = current_company_role; 'theo phòng ban' = org department_id ∈ phòng quản lý "
     "HOẶC part_id ∈ bộ phận quản lý; 'theo bộ phận' = org part_id ∈ bộ phận quản lý."),
    ("3. Đối tượng bị ẩn / không tính",
     "► Issue user KHÔNG giữ vai trò, KHÔNG thuộc project/solution của user, và KHÔNG nằm trong phạm vi org được quyền.\n"
     "► User không có quyền scope nào → chỉ thấy issue cá nhân + issue project/solution mình tham gia.\n"
     "► Issue của công ty khác công ty đang đăng nhập (trừ khi có quyền 'theo tổng công ty').\n"
     "► Quyền tính theo công ty đang đăng nhập (current_company_role); đổi công ty → phạm vi đổi theo.\n"
     "► KHÔNG có cơ chế kế thừa cha-con (khác Task)."),
    ("4. Bộ lọc thời gian áp dụng cho",
     "from_date / to_date (ngày tạo issue). Bộ lọc thời gian KHÔNG nới rộng phân quyền — chỉ thu hẹp trong phạm vi đã được phép xem."),
    ("5. Cấu trúc dữ liệu / cây phân cấp",
     "► IssueService::applyPermissionScope() nối các tầng bằng OR (whereIn ... orWhereIn ...). KHÔNG có nhánh parent/child.\n"
     "► Org snapshot lưu ở bảng phụ issue_org_units (company_id, department_id, part_id của MỌI người giữ vai trò), "
     "đồng bộ lại mỗi lần lưu issue (syncIssueOrgUnits).\n"
     "► Helper: isCurrentEmployeeHasPermission (lọc quyền theo current_company_role), "
     "listManageDepartmentIds (all_department=1 → mọi phòng), listManagePartIds."),
    ("6. Quy tắc cộng dồn / deduplicate",
     "Các tầng nối bằng OR; 1 issue thỏa nhiều tầng vẫn chỉ hiển thị 1 dòng (distinct theo issues.id). "
     "overdue_total (nếu có) đếm trên CÙNG query đã lọc phân quyền."),
    ("7. Phân quyền cấp",
     "• Xem danh sách issue theo tổng công ty\n"
     "• Xem danh sách issue theo công ty\n"
     "• Xem danh sách issue theo phòng ban\n"
     "• Xem danh sách issue theo bộ phận\n"
     "(Định nghĩa tại Modules/Timesheet/Database/Seeders/PermissionsTableSeeder.php; guard_name='api'. "
     "Issue KHÔNG dùng quyền 'Duyệt triển khai task')"),
    ("8. Cách tính các ô thống kê",
     "► Phạm vi DS = (issues.id ∈ myDirectIssueIds) OR (solution_id ∈ mySolutionIds) OR (project_id ∈ myProjectIds) "
     "OR (id ∈ issue_org_units thỏa tier3).\n"
     "► myDirectIssueIds = issue user là 1 trong 6 vai trò (creator/detected_by/assignee/approver/watcher/supporter).\n"
     "► tier3 = company_id = current_company_role [quyền công ty] | (department_id ∈ managedDepts OR part_id ∈ managedParts) "
     "[quyền phòng ban] | part_id ∈ managedParts [quyền bộ phận].\n"
     "► 'theo tổng công ty' → return sớm, BỎ QUA toàn bộ điều kiện (thấy hết)."),
    ("9. Ghi chú đọc bảng",
     "► Route GET /v1/assign/issues và /export KHÔNG gắn middleware checkPermission → MỌI user đăng nhập đều gọi được API "
     "(không trả 403); phân quyền là LỌC DỮ LIỆU ở Service, không chặn endpoint.\n"
     "► FE chỉ dùng 4 cờ permission (is_all_company/is_company/is_department/is_part) để ẩn/hiện ô filter org "
     "(V2BaseCompanyDepartmentFilter) và giới hạn option — FE KHÔNG tự lọc dữ liệu bảng.\n"
     "► Quyền nút từng dòng (can_edit/can_delete/can_handle) do BE trả riêng — NGOÀI phạm vi testcase này."),
]

ROLE_TCS = [
    ("00", "Mặc định — user KHÔNG có quyền scope nào", "P0",
     "User U1 không có bất kỳ quyền 'Xem danh sách issue theo ...'. Dữ liệu: 2 issue U1 là assignee, 1 issue U1 tạo; "
     "5 issue của người khác (U1 không liên quan).",
     "1. Đăng nhập U1\n2. Vào /assign/issues\n3. Quan sát danh sách",
     "User: U1 (0 quyền scope)",
     "- Chỉ thấy 3 issue U1 giữ vai trò (+ issue của solution/project U1 là thành viên nếu có)\n- KHÔNG thấy 5 issue của người khác",
     "BR — applyPermissionScope luôn áp dụng tầng 1-2 kể cả khi không có quyền cấp"),
    ("01", "Quyền 'Xem danh sách issue theo tổng công ty'", "P0",
     "User U2 có quyền 'Xem danh sách issue theo tổng công ty'. Hệ thống có issue ở ≥2 công ty.",
     "1. Đăng nhập U2\n2. Vào /assign/issues\n3. Quan sát phạm vi",
     "User: U2 (quyền tổng công ty)",
     "- Thấy TOÀN BỘ issue của MỌI công ty (không giới hạn)\n- Ô filter Công ty hiển thị đầy đủ",
     "Permission: Xem danh sách issue theo tổng công ty → return sớm, không lọc"),
    ("02", "Quyền 'Xem danh sách issue theo công ty'", "P0",
     "User U3 đăng nhập công ty C1 (current_company_role=C1), có quyền 'Xem danh sách issue theo công ty'. "
     "Issue org: 4 thuộc C1, 3 thuộc C2.",
     "1. Đăng nhập U3 (C1)\n2. Vào /assign/issues\n3. Quan sát",
     "User: U3, công ty C1",
     "- Thấy 4 issue org thuộc C1 (+ issue cá nhân/project)\n- KHÔNG thấy 3 issue org chỉ thuộc C2",
     "Permission: Xem danh sách issue theo công ty → tier3: company_id = current_company_role"),
    ("03", "Quyền 'Xem danh sách issue theo phòng ban'", "P0",
     "User U4 quản lý phòng D1 (managedDepts=[D1], managedParts=[P1]); quyền 'theo phòng ban'. "
     "Issue org: 3 thuộc D1, 2 thuộc P1, 4 thuộc phòng D2 khác.",
     "1. Đăng nhập U4\n2. Vào /assign/issues\n3. Quan sát",
     "User: U4, quản lý D1/P1",
     "- Thấy issue org có department_id ∈ [D1] HOẶC part_id ∈ [P1] (3+2)\n- KHÔNG thấy 4 issue org của D2",
     "Permission: Xem danh sách issue theo phòng ban → department_id ∈ managedDepts OR part_id ∈ managedParts"),
    ("04", "Quyền 'Xem danh sách issue theo bộ phận'", "P0",
     "User U5 quản lý bộ phận P1 (managedParts=[P1]); quyền 'theo bộ phận'. Issue org: 3 thuộc P1, 4 thuộc P2 khác.",
     "1. Đăng nhập U5\n2. Vào /assign/issues\n3. Quan sát",
     "User: U5, quản lý P1",
     "- Chỉ thấy 3 issue org có part_id ∈ [P1]\n- KHÔNG thấy 4 issue org của P2",
     "Permission: Xem danh sách issue theo bộ phận → tier3: part_id ∈ managedParts"),
    ("05", "Endpoint KHÔNG bị chặn bởi checkPermission", "P0",
     "User U1 không có quyền scope nào, đã đăng nhập (token hợp lệ).",
     "1. Gọi GET /v1/assign/issues bằng token U1",
     "User: U1, token hợp lệ",
     "- HTTP 200 (KHÔNG trả 403/Forbidden)\n- data đã bị LỌC theo vai trò U1 (không lộ issue người khác)",
     "BR — Route index chỉ gắn auth:api, phân quyền = lọc data không chặn endpoint"),
    ("06", "Quyền tính theo CÔNG TY ĐANG ĐĂNG NHẬP", "P1",
     "User U7 có quyền 'theo công ty' ở C1 nhưng KHÔNG có ở C2. U7 thuộc cả 2 công ty.",
     "1. Đăng nhập U7 chọn C1 → /assign/issues\n2. Đổi sang C2 → /assign/issues",
     "User: U7; C1 có quyền, C2 không",
     "- Ở C1: thấy issue org của C1\n- Ở C2: chỉ thấy issue cá nhân (quyền không áp dụng ở C2)",
     "isCurrentEmployeeHasPermission lọc theo current_company_role"),
]

SECTIONS = [
    ("I", "HIỂN THỊ TRANG & TRUY CẬP ENDPOINT", [
        ("001", "Truy cập trang danh sách Issue", "P1",
         "User U2 (quyền tổng công ty) đã đăng nhập.",
         "1. Vào /assign/issues\n2. Quan sát layout",
         "User: U2",
         "- Trang load thành công: panel filter + bảng V2BaseDataTable + nút Tạo mới/Xuất Excel/Cấu hình cột",
         "BR — Mọi user đăng nhập đều vào được trang"),
        ("002", "User KHÔNG quyền scope vẫn truy cập được trang", "P0",
         "User U1 (0 quyền scope), KHÔNG giữ vai trò trên bất kỳ issue nào.",
         "1. Đăng nhập U1\n2. Vào /assign/issues",
         "User: U1",
         "- Trang load thành công (không 403)\n- Danh sách có thể RỖNG (vì U1 không giữ vai trò/không thuộc project nào)",
         "BR — Không chặn endpoint; data rỗng là hợp lệ"),
        ("003", "Export Issue dùng CÙNG phạm vi phân quyền với index", "P1",
         "User U4 (quyền 'theo phòng ban'). Index hiển thị M issue.",
         "1. Vào /assign/issues\n2. Bấm Xuất Excel\n3. Đối chiếu",
         "User: U4",
         "- File export chứa ĐÚNG M issue như index (cùng applyPermissionScope), không có issue ngoài phạm vi",
         "BR — IssueController::export gọi cùng issueService->index()"),
    ]),
    ("II", "BỘ LỌC TỔ CHỨC THEO QUYỀN (FE)", [
        ("001", "Quyền tổng công ty → hiện đủ 3 ô filter org", "P0",
         "User U2 có 'Xem danh sách issue theo tổng công ty' (is_all_company=true).",
         "1. Vào /assign/issues\n2. Mở panel filter",
         "User: U2",
         "- Hiện đủ 3 ô: Công ty, Phòng ban, Bộ phận\n- Ô Công ty liệt kê tất cả công ty",
         "FE: V2BaseCompanyDepartmentFilter — ô Công ty v-if is_all_company"),
        ("002", "Chỉ quyền 'theo công ty' → ẨN ô Công ty", "P0",
         "User U3 chỉ có 'Xem danh sách issue theo công ty' (is_company=true, is_all_company=false).",
         "1. Vào /assign/issues\n2. Mở panel filter",
         "User: U3",
         "- ẨN ô Công ty\n- HIỆN ô Phòng ban + Bộ phận",
         "FE: Phòng ban v-if (all_company||company||department)"),
        ("003", "Chỉ quyền 'theo phòng ban' → ẩn Công ty, hiện Phòng ban + Bộ phận", "P1",
         "User U4 chỉ có 'Xem danh sách issue theo phòng ban' (is_department=true).",
         "1. Vào /assign/issues\n2. Mở panel filter",
         "User: U4",
         "- ẨN ô Công ty\n- HIỆN Phòng ban + Bộ phận",
         "FE: Bộ phận v-if (all_company||company||department||part)"),
        ("004", "Chỉ quyền 'theo bộ phận' → chỉ hiện ô Bộ phận", "P1",
         "User U5 chỉ có 'Xem danh sách issue theo bộ phận' (is_part=true).",
         "1. Vào /assign/issues\n2. Mở panel filter",
         "User: U5",
         "- ẨN Công ty + Phòng ban\n- CHỈ HIỆN ô Bộ phận",
         "FE: chỉ Bộ phận thỏa điều kiện v-if"),
        ("005", "Không quyền scope → ẩn HẾT ô filter org", "P0",
         "User U1 không có quyền scope nào (mọi cờ permission=false).",
         "1. Vào /assign/issues\n2. Mở panel filter",
         "User: U1",
         "- ẨN cả 3 ô Công ty/Phòng ban/Bộ phận\n- Vẫn còn các filter khác (Giải pháp, Dự án, Trạng thái...)",
         "FE: tất cả ô org v-if đều false"),
        ("006", "Option Phòng ban giới hạn theo phòng user quản lý", "P1",
         "User U4 có 'theo phòng ban', manager_department_ids=[D1,D3]. Hệ thống có 10 phòng.",
         "1. Vào /assign/issues\n2. Mở dropdown Phòng ban",
         "User: U4, quản lý D1,D3",
         "- Dropdown CHỈ liệt kê D1, D3 (không hiện 8 phòng còn lại)",
         "FE: availableDepartments lọc theo auth.manager_department_ids"),
    ]),
    ("III", "PHẠM VI DỮ LIỆU — VAI TRÒ CÁ NHÂN (6) & QUYỀN CẤP", [
        ("001", "Người tạo (creator) thấy issue mình tạo", "P0",
         "User U8 là creator_id của issue I1; không có quyền scope.",
         "1. Đăng nhập U8\n2. Vào /assign/issues",
         "User: U8 (creator I1)",
         "- Thấy I1",
         "Tầng 1 issue: creator_id = userId"),
        ("002", "Người phát hiện (detected_by) thấy issue", "P0",
         "User U8 là detected_by của issue I2.",
         "1. Đăng nhập U8\n2. Vào /assign/issues",
         "User: U8 (detected_by I2)",
         "- Thấy I2",
         "Tầng 1 issue: detected_by = userId (vai trò riêng của Issue)"),
        ("003", "Assignee thấy issue được giao", "P0",
         "User U8 là assignee_id của issue I3.",
         "1. Đăng nhập U8\n2. Vào /assign/issues",
         "User: U8 (assignee I3)",
         "- Thấy I3",
         "Tầng 1 issue: assignee_id = userId"),
        ("004", "Người duyệt (approver) thấy issue", "P1",
         "User U8 là approver_id của issue I4.",
         "1. Đăng nhập U8\n2. Vào /assign/issues",
         "User: U8 (approver I4)",
         "- Thấy I4",
         "Tầng 1 issue: approver_id = userId"),
        ("005", "Người theo dõi (watcher) thấy issue", "P1",
         "User U8 là watcher của issue I5.",
         "1. Đăng nhập U8\n2. Vào /assign/issues",
         "User: U8 (watcher I5)",
         "- Thấy I5",
         "Tầng 1 issue: whereHas watchers.employee_id = userId"),
        ("006", "Người hỗ trợ (supporter) thấy issue", "P1",
         "User U8 là supporter của issue I6 (vai trò đặc thù riêng của Issue).",
         "1. Đăng nhập U8\n2. Vào /assign/issues",
         "User: U8 (supporter I6)",
         "- Thấy I6",
         "Tầng 1 issue: whereHas supporters.employee_id = userId (Issue có 6 vai trò)"),
        ("007", "Quyền 'theo công ty' thấy issue org công ty mình", "P0",
         "User U3 (C1, quyền theo công ty). Issue I7 org company_id=C1 (U3 không giữ vai trò).",
         "1. Đăng nhập U3 (C1)\n2. Vào /assign/issues",
         "User: U3, công ty C1",
         "- Thấy I7 (qua tier3 company_id=C1)",
         "Tầng 3: issue_org_units.company_id = current_company_role"),
        ("008", "Quyền 'theo bộ phận' KHÔNG thấy issue của bộ phận khác", "P1",
         "User U5 (quản lý P1, quyền theo bộ phận). Issue I8 org part_id=P2.",
         "1. Đăng nhập U5\n2. Vào /assign/issues\n3. Tìm I8",
         "User: U5, quản lý P1",
         "- KHÔNG thấy I8 (part_id=P2 không thuộc managedParts)",
         "Tầng 3 bộ phận: chỉ part_id ∈ managedParts"),
        ("009", "Quyền 'theo tổng công ty' thấy mọi issue", "P0",
         "User U2 (quyền tổng công ty). Issue ở C1, C2; có issue U2 không liên quan.",
         "1. Đăng nhập U2\n2. Vào /assign/issues",
         "User: U2",
         "- Thấy TẤT CẢ issue không phân biệt công ty/vai trò",
         "Return sớm trong applyPermissionScope"),
        ("010", "Issue hoàn toàn không liên quan + ngoài org → ẩn", "P0",
         "User U1 (0 quyền). Issue I9: U1 không giữ vai trò, không thuộc project/solution U1, org không liên quan.",
         "1. Đăng nhập U1\n2. Vào /assign/issues\n3. Tìm I9",
         "User: U1",
         "- KHÔNG thấy I9",
         "Không thỏa tầng nào → bị loại"),
    ]),
    ("IV", "THÀNH VIÊN DỰ ÁN / GIẢI PHÁP & KHÁC BIỆT VỚI TASK", [
        ("001", "Thành viên giải pháp thấy mọi issue của giải pháp", "P0",
         "User U9 là thành viên solution S1 (không giữ vai trò issue nào). S1 có 3 issue.",
         "1. Đăng nhập U9\n2. Vào /assign/issues",
         "User: U9 (thành viên S1)",
         "- Thấy cả 3 issue có solution_id=S1",
         "Tầng 2: solution_id ∈ mySolutionIds"),
        ("002", "Thành viên dự án thấy mọi issue của dự án", "P0",
         "User U9 là thành viên project PR1. PR1 có 4 issue.",
         "1. Đăng nhập U9\n2. Vào /assign/issues",
         "User: U9 (thành viên PR1)",
         "- Thấy cả 4 issue có project_id=PR1",
         "Tầng 2: project_id ∈ myProjectIds"),
        ("003", "Issue KHÔNG kế thừa quan hệ Cha-Con (khác Task)", "P2",
         "User U8 chỉ giữ vai trò trên issue cha I_parent. (Issue không có cơ chế kế thừa như Task.)",
         "1. Đăng nhập U8\n2. Vào /assign/issues",
         "User: U8 (giữ vai trò I_parent)",
         "- Chỉ thấy I_parent\n- KHÔNG tự động thấy issue con/cha qua kế thừa",
         "BR — applyPermissionScope của Issue KHÔNG có nhánh parent/child"),
        ("004", "Issue thỏa NHIỀU tầng vẫn hiển thị 1 dòng (dedup)", "P1",
         "Issue I10: U8 vừa là assignee (tầng 1), vừa thuộc solution của I10 (tầng 2), vừa nằm trong org U8 quản lý (tầng 3).",
         "1. Đăng nhập U8 (đủ 3 điều kiện)\n2. Vào /assign/issues\n3. Đếm I10 xuất hiện",
         "User: U8",
         "- I10 chỉ xuất hiện ĐÚNG 1 dòng (không nhân bản)",
         "OR + distinct theo issues.id"),
    ]),
    ("V", "EDGE CASES & VALIDATION", [
        ("001", "User all_department=1 → quản lý mọi phòng công ty", "P1",
         "User U10 có CompanyEmployee.all_department=1, quyền 'theo phòng ban'. Công ty C1 có 6 phòng.",
         "1. Đăng nhập U10\n2. Vào /assign/issues",
         "User: U10, all_department=1",
         "- managedDepts = TẤT CẢ 6 phòng C1\n- Thấy issue org thuộc bất kỳ phòng nào của C1",
         "listManageDepartmentIds: all_department=1 → mọi phòng công ty"),
        ("002", "Đổi công ty đăng nhập → phạm vi đổi theo", "P0",
         "User U7 thuộc C1 & C2; quyền 'theo công ty' chỉ ở C1.",
         "1. Đăng nhập C1 → /assign/issues (ghi nhận DS)\n2. Đổi sang C2 → /assign/issues",
         "User: U7",
         "- C1: thấy issue org C1\n- C2: chỉ thấy issue cá nhân (current_company_role=C2, không có quyền)",
         "current_company_role quyết định cả quyền lẫn tier3.company_id"),
        ("003", "Có quyền phòng ban nhưng không quản lý phòng nào", "P1",
         "User U13 có quyền 'theo phòng ban' nhưng managedDepts=[] và managedParts=[].",
         "1. Đăng nhập U13\n2. Vào /assign/issues",
         "User: U13, managedDepts=[]",
         "- tier3 whereIn([]) không khớp bản ghi nào → chỉ thấy issue cá nhân/project\n- KHÔNG lỗi, KHÔNG lộ toàn bộ",
         "whereIn mảng rỗng → không mở rộng phạm vi"),
        ("004", "Org snapshot cập nhật khi đổi assignee", "P1",
         "Issue I13 assignee ban đầu thuộc P1. Sau đó đổi assignee sang NV thuộc P2. User U12 quản lý P2.",
         "1. Đổi assignee I13 sang NV P2 (lưu)\n2. Đăng nhập U12 (quản lý P2)\n3. Vào /assign/issues",
         "User: U12, quản lý P2",
         "- U12 thấy I13 (issue_org_units đã sync part_id=P2)",
         "syncIssueOrgUnits chạy mỗi lần lưu"),
    ]),
    ("VI", "CÔ LẬP DỮ LIỆU & BẢO MẬT", [
        ("001", "User A không thấy issue RIÊNG của user B", "P0",
         "User A và B khác phòng, không chung project/solution. Issue IB của B (A không giữ vai trò, không cùng org). A không có quyền scope.",
         "1. Đăng nhập A\n2. Vào /assign/issues\n3. Tìm IB",
         "User: A; IB thuộc B",
         "- A KHÔNG thấy IB",
         "Cô lập: không thỏa tầng nào"),
        ("002", "Filter company_id công ty khác không lộ dữ liệu", "P0",
         "User U3 chỉ quyền 'theo công ty' C1. Cố lọc company_id=C2.",
         "1. Đăng nhập U3 (C1)\n2. Gọi /assign/issues?company_id=C2",
         "User: U3; company_id=C2",
         "- KHÔNG trả issue org C2 (applyPermissionScope C1 ∩ filter C2 ở phần org C2 = rỗng)",
         "Filter là AND, không bypass scope"),
        ("003", "Gọi API trực tiếp (Postman) không bypass phân quyền", "P0",
         "User U1 (0 quyền) lấy token, gọi thẳng API bỏ qua FE.",
         "1. Lấy Bearer token U1\n2. GET /api/v1/assign/issues (Postman)",
         "User: U1, token hợp lệ",
         "- Response 200 nhưng data vẫn bị applyPermissionScope lọc (không lộ issue người khác)\n- Không có param nào bỏ được lọc",
         "Phân quyền ở Service (server-side), FE chỉ là UI"),
        ("004", "Export không bypass phân quyền", "P0",
         "User U1 (0 quyền) gọi endpoint export trực tiếp.",
         "1. GET /api/v1/assign/issues/export bằng token U1",
         "User: U1",
         "- File export chỉ chứa issue trong phạm vi U1, không lộ toàn bộ",
         "export gọi cùng index()"),
        ("005", "Quyền ở công ty A không áp dụng khi đăng nhập công ty B", "P1",
         "User U7 có quyền 'theo công ty' gán ở C1. Đăng nhập C2.",
         "1. Đăng nhập U7 chọn C2\n2. Vào /assign/issues",
         "User: U7 đăng nhập C2",
         "- Quyền không hiệu lực ở C2 → chỉ thấy issue cá nhân/project\n- KHÔNG thấy issue org C2",
         "isCurrentEmployeeHasPermission lọc theo company_id=current_company_role"),
    ]),
]

build_testcase(OUTPUT_FILE, SHEET_NAME, FEATURE_NAME, MODULE_NAME,
               DESCRIPTION_BLOCK, ROLE_TCS, SECTIONS)
