from common import *
with browser_page() as page:
    go(page,'/assign/bom-list/24'); wait_name(page)
    shot(page,'36_bom_khong_duyet')
    b=btn(page,'Sao chép'); icon(page,b,'btn_sao_chep'); b.click(); page.wait_for_timeout(3000); wait_name(page)
    n=page.locator('input[placeholder="VD: BOM điều khiển dây chuyền line 01"]')
    n.fill('BOM tổng hợp hạng mục Xây dựng danh mục thiết bị (bổ sung van điện từ)')
    page.get_by_role('button', name='Thêm mới').first.click(); page.wait_for_timeout(5000); idle(page)
    page.fill('input[placeholder="Tìm theo tên, mã, model hàng hoá"]','van điện từ'); page.keyboard.press('Enter'); page.wait_for_timeout(5000); idle(page)
    page.screenshot(path='x_van.png')
    rows=page.locator('.modal-card tbody tr:has(input[type=checkbox])')
    print(rows.count(), rows.all_inner_texts()[:8])
    rows.filter(has_text='Van điện từ SMC').first.locator('input[type=checkbox]').check(); page.wait_for_timeout(500)
    page.get_by_role('button', name='Thêm 1 hàng hoá').click(); page.wait_for_timeout(3000)
    btn(page.locator('.modal-card'),'Đóng').click(); page.wait_for_timeout(2500)
    shot(page,'37_saochep_form')
    icon(page, btn(page,'Lưu BOM'), 'btn_luu_bom')
    icon(page, btn(page,'Lưu nháp'), 'btn_luu_nhap')
    btn(page,'Lưu BOM').click(); page.wait_for_timeout(5000); idle(page)
    print(page.url)
